Repository red-hat-storage/ocs-ci, pull requests merged in 2019-08, with the labels that each got.

#484 patch gp2 ebs based storage class
  ocs_ci/deployment/deployment.py
Labels: Verified

#496 Adding wait time for PV and pod status check in test case
  tests/manage/pv_services/test_verify_rbd_based_rwo_pvc.py
Labels: Test Case, Verified, enhancement

#495 Deployment logger names
  ocs_ci/deployment/aws.py
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/factory.py
Labels: Needs Deployment Testing, team/ecosystem

#501 Improve wait_for_delete logging
  ocs_ci/ocs/ocp.py
Labels: Verified

#497 Test cases for ec2 instances restart (force True/False)
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/utility/aws.py
  tests/fixtures.py
  tests/helpers.py
  tests/manage/cluster/nodes/test_nodes_restart.py
Labels: Test Case, Verified, team/manage

#505 Add force download for client and installer
  ocs_ci/deployment/aws.py
  tests/conftest.py
Labels: Verified, team/ecosystem

#508 Enhancements for ocp.wait_for_nodes_ready()
  ocs_ci/ocs/ocp.py
  tests/manage/cluster/nodes/test_nodes_restart.py
Labels: Verified, enhancement

#514 Force download client and installer only when deploy
  ocs_ci/deployment/aws.py
  tests/conftest.py
Labels: Verified, enhancement, team/ecosystem

#531 Add bugzilla decorator to add_mds test case
  tests/manage/cluster/test_add_mds_to_cluster.py
Labels: Verified

#515 Implement NooBaa and test NooBaa bucket creation
  ocs_ci/ocs/resources/noobaa.py
  tests/manage/noobaa/test_create_bucket.py
Labels: Test Case, Verified

#533 Add AZ and instance type to deployment
  ocs_ci/templates/install-config.yaml.j2
Labels: Verified, enhancement, team/ecosystem

#539 Skip NooBaa test
  tests/manage/noobaa/test_create_bucket.py
Labels: Verified

#532 Using create_project fixture in test_verify_rbd_based_rwo_pvc
  tests/manage/pv_services/test_verify_rbd_based_rwo_pvc.py
Labels: High Priority, Test Case, Verified

#537 Updated the Deployment yamls and Deployment.py based on rook repo changes
  ocs_ci/deployment/deployment.py
  ocs_ci/templates/ocs-deployment/cluster.yaml
  ocs_ci/templates/ocs-deployment/common.yaml
  ocs_ci/templates/ocs-deployment/operator-openshift.yaml
Labels: Verified

#493 Test case to delete ceph pods while PVCs creation, Pods creation and …
  ocs_ci/ocs/resources/pod.py
  tests/helpers.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Labels: Test Case, Verified

#516 Testcase: OCS-622 and OCS-623 Create multiple SC's with same pool name
  tests/manage/storageclass/test_create_multiple_sc_with_same_pool_name.py
Labels: Test Case, Verified

#519 Add factory fixtures
  tests/conftest.py
Labels: Verified

#536 Add nodes operations
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/ocp.py
  tests/manage/cluster/nodes/test_nodes_restart.py
Labels: Verified

#542 Remove secret from the environment checks
  ocs_ci/utility/environment_check.py
Labels: Verified

#534 Updating OCS-347 with fixtures, removing global variable and handling the leftover PV
  tests/manage/storageclass/test_rbd_csi_default_sc.py
Labels: Verified, team/manage

#526 Separate OCP deployment
  ocs_ci/deployment/aws.py
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/ocp.py
  ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2
  tests/conftest.py
Labels: Verified, enhancement

#547 Node disk failures
  ocs_ci/deployment/aws.py
  ocs_ci/ocs/node.py
  ocs_ci/utility/aws.py
  ocs_ci/utility/utils.py
  tests/manage/cluster/nodes/base_node_ops.py
  tests/manage/cluster/nodes/conftest.py
  tests/manage/cluster/nodes/test_disk_failures.py
  tests/manage/cluster/nodes/test_nodes_restart.py
Labels: Test Case, Verified, team/manage

#548 Update TC OCS-324: Fix #525 and use factory fixtures
  tests/manage/pv_services/test_delete_create_pvc_same_name.py
Labels: team/manage

#511 Generic fixtures for parametrize usage
  tests/conftest.py
  tests/e2e/test_io_performance.py
  tests/helpers.py
Labels: Verified

#561 Add capability to use latest nightly OCP accepted builds
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/utility/utils.py
Labels: Verified, enhancement, team/ecosystem

#553 Time measurement for PVC creation
  ocs_ci/ocs/resources/pod.py
  tests/e2e/test_pvc_creation_performance.py
  tests/helpers.py
Labels: Verified

#550 PV provisioning and deletion while node is down
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/aws.py
  tests/manage/cluster/nodes/base_node_ops.py
  tests/manage/cluster/nodes/test_disk_failures.py
  tests/manage/cluster/nodes/test_nodes_restart.py
  tests/sanity_helpers.py
Labels: Test Case, Verified, team/manage

#554 CSI sidecars downstream images
  conf/ocsci/downstream_config.yaml
  ocs_ci/templates/ocs-deployment/csi/cephfs/csi-node-plugin-psp_cephfs.yaml
  ocs_ci/templates/ocs-deployment/csi/cephfs/csi-nodeplugin-rbac_cephfs.yaml
  ocs_ci/templates/ocs-deployment/csi/cephfs/csi-provisioner-psp_cephfs.yaml
  ocs_ci/templates/ocs-deployment/csi/cephfs/csi-provisioner-rbac_cephfs.yaml
  ocs_ci/templates/ocs-deployment/csi/rbd/csi-node-plugin-psp_rbd.yaml
  ocs_ci/templates/ocs-deployment/csi/rbd/csi-nodeplugin-rbac_rbd.yaml
  ocs_ci/templates/ocs-deployment/csi/rbd/csi-provisioner-psp_rbd.yaml
  ocs_ci/templates/ocs-deployment/csi/rbd/csi-provisioner-rbac_rbd.yaml
  ocs_ci/templates/ocs-deployment/operator-openshift-with-csi.yaml
  ocs_ci/templates/ocs-deployment/operator-openshift.yaml
Labels: High Priority, Verified, enhancement, team/ecosystem

#489 Ripsaw class to run various workloads and scale tests
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ripsaw.py
  ocs_ci/templates/workloads/pgsql/server/ConfigMap.yaml
  ocs_ci/templates/workloads/pgsql/server/Service.yaml
  ocs_ci/templates/workloads/pgsql/server/StatefulSet.yaml
Labels: Code/Infra, Verified

#559 Parse pgsql benchmark data and return in readable format for scripts
  ocs_ci/utility/utils.py
Labels: Verified

#572 Fix ceph_pool_factory fixture
  tests/conftest.py
Labels: Verified, bug

#565 Add teardown factory
  tests/conftest.py
  tests/e2e/test_pvc_creation_performance.py
Labels: Verified, enhancement

#576 Fix issue 562
  ocs_ci/ocs/defaults.py
  ocs_ci/templates/CSI/cephfs/storageclass.yaml
  ocs_ci/templates/CSI/rbd/snapshotclass.yaml
  ocs_ci/templates/CSI/rbd/storageclass.yaml
Labels: Verified

#573 Get the resource "real" status
  ocs_ci/ocs/ocp.py
  tests/manage/cluster/nodes/test_nodes_restart.py
Labels: Verified, enhancement

#580 Wait for build extraction
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/utils.py
Labels: Verified, enhancement, team/ecosystem

#578 Remove duplicate test case 'test_rbd_based_rwo_pvc' which is combined…
  tests/manage/pv_services/test_verify_rbd_based_rwo_pvc.py
Labels: team/manage

#574 Performance testing: Creation of 120 PVCs in 60 seconds
  ocs_ci/ocs/exceptions.py
  tests/e2e/test_pvc_creation_performance.py
  tests/helpers.py
Labels: Test Case, Verified, team/e2e

#570 check is_deleted flag in the base OCS class and avoid repetitive checks
  ocs_ci/ocs/resources/ocs.py
  tests/conftest.py
  tests/manage/pv_services/test_delete_create_pvc_same_name.py
Labels: Verified

#560 use uuid4 in hex as random suffix for ocs objects
  tests/helpers.py
Labels: Verified

#566 Separate wait for resource from resource creation
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/monitoring.py
  ocs_ci/utility/deployment_openshift_logging.py
  tests/conftest.py
  tests/e2e/test_pvc_creation_performance.py
  tests/fixtures.py
  tests/helpers.py
  tests/manage/pv_services/test_create_pvc_random_storage_class.py
  tests/manage/pv_services/test_create_storage_class_pvc.py
  tests/manage/pv_services/test_delete_create_pvc_same_name.py
  tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
  tests/manage/pv_services/test_pvc_concurrent_deletion_creation.py
  tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
  tests/manage/pv_services/test_reclaim_policy.py
  tests/manage/storageclass/test_create_multiple_sc_with_same_pool_name.py
  tests/manage/storageclass/test_create_storageclass_with_wrong_provisioner.py
  tests/manage/storageclass/test_rbd_csi_default_sc.py
  tests/sanity_helpers.py
Labels: Verified

#582 Added guidelines to contribution doc around pairing PRs with Issues
  docs/code_review.md
Labels: documentation

#597 Fix create_pods fixture
  tests/fixtures.py
Labels: Verified

#558 Add test cases to Assign Pods to Node using nodeName field
  tests/conftest.py
  tests/manage/pv_services/test_pvc_assign_pod_node.py
Labels: Test Case, Verified, team/manage

#601 Fix PVC disruptive TCs
  tests/manage/pv_services/test_pvc_disruptive.py
Labels: Verified

#600 Fixing issue-586: broken test case - test_reclaim_policy
  tests/manage/pv_services/test_reclaim_policy.py
Labels: Verified

#587 Basic node maintenance tests
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/node.py
  ocs_ci/utility/aws.py
  tests/helpers.py
  tests/manage/cluster/nodes/test_nodes_maintenance.py
  tests/sanity_helpers.py
Labels: Test Case, Verified, team/manage

#603 update pvc_factory
  tests/conftest.py
Labels: Needs Testing

#608 Fix issue #591
  ocs_ci/ocs/ocp.py
Labels: High Priority, Verified

#609 Fix Pod factory fixture
  tests/conftest.py
Labels: High Priority, Verified

#611 Change PVC disruptive tests to factory
  tests/conftest.py
  tests/manage/pv_services/test_pvc_disruptive.py
Labels: Verified

#617 PGSQL workload: updated review comments
  ocs_ci/ocs/constants.py
  ocs_ci/templates/workloads/pgsql/PGSQL_Benchmark.yaml
  tests/e2e/test_pgsql.py
Labels: Verified, team/e2e

#543 Test Case - Delete ceph pod while pvc/pod deletion is running
  ocs_ci/ocs/resources/pvc.py
  tests/conftest.py
  tests/helpers.py
  tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
Labels: Test Case, Verified, team/manage

#506 OCS-580: Respin ceph pod(osd, mon, mgr) and check the interaction with monitoring pods
  ocs_ci/ocs/monitoring.py
  ocs_ci/ocs/resources/pod.py
  tests/e2e/monitoring/test_when_respin_ceph_pods_interaction_with_prometheus.py
  tests/helpers.py
Labels: Needs Testing, team/e2e

#551 Run IO on multiple Deploymentconfig pod
  ocs_ci/ocs/constants.py
  ocs_ci/templates/app-pods/fedora_dc.yaml
  ocs_ci/templates/ocs-deployment/service_account.yaml
  ocs_ci/utility/workloads/helpers.py
  tests/fixtures.py
  tests/helpers.py
  tests/manage/pv_services/test_run_io_multiple_dc_pods.py
Labels: Verified

#585 Rook repo download
  .gitignore
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/utility/templating.py
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: Verified

#627 Removing test_running_cluster_monitoring_with_persistent_storage.py
  tests/e2e/test_running_cluster_monitoring_with_persistent_storage.py
Labels: Verified, team/ecosystem

#595 Test to create, delete and list multiple s3 buckets
  ocs_ci/ocs/resources/noobaa.py
  tests/manage/noobaa/conftest.py
  tests/manage/noobaa/test_bucket_deletion.py
Labels: Test Case, Verified, team/manage

#635 Fix test_delete_create_pvc_same_name
  tests/manage/pv_services/test_delete_create_pvc_same_name.py
Labels: High Priority, Test Case, Verified, team/manage

#588 Add test OCS-1270
  ocs_ci/ocs/resources/pvc.py
  tests/e2e/test_pvc_creation_performance.py
  tests/helpers.py
Labels: Test Case, Verified, team/e2e

#636 Wait for PV to delete in pvc_factory finalizer
  tests/conftest.py
Labels: enhancement

#607 Adding TCs OCS-626 & 627: Create a StorageClass and make it as a default
  tests/helpers.py
  tests/manage/storageclass/test_create_sc_and_make_it_as_a_default.py
Labels: Test Case, Verified

#606 Change test_run_io_multiple_pods to factory
  tests/manage/pv_services/test_run_io_multiple_pods.py
Labels: Verified, enhancement, team/manage

#616 Implement silent logging option
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/utils.py
Labels: Needs Testing

#610 Test NooBaa object write
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/noobaa.py
  ocs_ci/templates/app-pods/awscli.yaml
  tests/helpers.py
  tests/manage/noobaa/conftest.py
  tests/manage/noobaa/test_create_bucket.py
  tests/manage/noobaa/test_write_to_bucket.py
Labels: Test Case, Verified, team/manage

#567 Stop Ceph Manager alerting test case
  ocs_ci/ocs/constants.py
  ocs_ci/utility/prometheus.py
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/prometheus/test_deployment_status.py
Labels: Needs Testing, Test Case, team/manage

#638 Fix docstring in OCP wait for delete
  ocs_ci/ocs/ocp.py
Labels: Verified

#659 Change NooBaa bucket creation test filename, skip the test
  tests/manage/noobaa/test_bucket_creation.py
Labels: Needs Testing, bug, team/manage

#657 Update test_pvc_assign_pod_node.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/pv_services/test_pvc_assign_pod_node.py
Labels: Test Case, Verified, team/manage

#656 Add isautomated to polarion
  tests/conftest.py
Labels: Needs Testing, enhancement, team/ecosystem

#665 Update ocs_ci/templates/ocs-deployment/common.yaml
  ocs_ci/templates/ocs-deployment/common.yaml
Labels: Needs Deployment Testing, Needs Testing

#623 Delete ceph pod while multiple deletion operations are running
  tests/helpers.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: Test Case, Verified, team/manage

#663 enable OCP/OCS monitoring by default
  ocs_ci/framework/conf/default_config.yaml
Labels: Needs Deployment Testing, team/manage

#669 Fixing issue with deployment and check mons
  ocs_ci/ocs/ocp.py
Labels: High Priority, Verified, team/ecosystem

#664 Fix must gather timeout
  ocs_ci/ocs/ceph.py
  ocs_ci/ocs/clients.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/utils.py
Labels: Verified, bug, enhancement

#644 OCS Scale test case to create delete pvc parallel and check for memory leak
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/pvc.py
  tests/conftest.py
  tests/e2e/test_pv_scale_ocs_create_delete_pvcs.py
  tests/helpers.py
Labels: Needs Testing, Test Case, team/e2e

#545 Deployment of openshift-logging on OCP 4.2
  ocs_ci/ocs/constants.py
  ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/cl-csc.yaml
  ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/cl-sub.yaml
  ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/instance.yaml
  ocs_ci/templates/openshift-infra/logging-deployment/elasticsearch_operator/eo-csc.yaml
  ocs_ci/templates/openshift-infra/logging-deployment/elasticsearch_operator/eo-sub.yaml
  ocs_ci/utility/deployment_openshift_logging.py
Labels: Verified, team/e2e

#546 Uninstall openshift-logging for ocp 4.2
  ocs_ci/utility/uninstall_openshift_logging.py
Labels: Verified, team/e2e

#677 test_run_io_and_delete_pvc: Few improvements
  tests/manage/pv_services/test_pvc_deletion_during_io.py
Labels: Test Case, Verified, team/manage
