Repository red-hat-storage/ocs-ci, pull requests merged in 2019-07, with the labels that each got.

#309 Removing [monitors] and adding [clusterID] in SC creation- ocs-322
  tests/manage/test_create_storageclass_with_same_name.py
Labels: Test Case, Verified

#283 Workload infra and fio workload implementation
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/workload.py
  ocs_ci/templates/workloads/fio/workload_io.yaml
  ocs_ci/utility/workloads/__init__.py
  ocs_ci/utility/workloads/fio.py
  tests/helpers.py
  tests/test_fio_workload.py
Labels: High Priority

#306 use pytest-logger instead of ocsci_logging.py
  ocs_ci/framework/main.py
  ocs_ci/framework/pytest_customization/ocsci_logging.py
  setup.py
  tests/conftest.py
Labels: Verified

#347 Commenting the validation pv exists in backend since it fails due to bug
  tests/manage/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Labels: Verified

#326 Adding test case: OCS-521 and OCS-522
  tests/fixtures.py
  tests/manage/test_verify_all_fields_in_sc_yaml_with_oc_describe_sc.py
Labels: Verified

#334 Add FIO as a function to Pod object
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/workload.py
  ocs_ci/templates/workloads/fio/workload_io_rw.yaml
  ocs_ci/utility/workloads/fio.py
  tests/manage/test_pvc_deletion_during_io.py
Labels: Verified

#337 Test case to verify RBD Based RWO Dynamic PVC creation with Reclaim p…
  tests/helpers.py
  tests/manage/test_verify_rbd_based_rwo_pvc.py
Labels: Test Case, Verified

#230 Testcase to remove Mon pods from cluster(OCS-355)
  ocs_ci/ocs/cluster.py
  tests/helpers.py
  tests/test_remove_mon_from_cluster.py
Labels: Test Case, Verified

#361 fix cluster init
  tests/manage/test_remove_mon_from_cluster.py
Labels: Verified

#367 update api version in the install config
  ocs_ci/templates/install-config.yaml.j2
Labels: Verified

#373 Fixes Issue-371, added ioparam [fio_filename] to pod.run_io
  ocs_ci/ocs/resources/pod.py
Labels: Verified

#329 Adding tests OCS-383 & OCS-384
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/test_reclaim_policy.py
Labels: Test Case, Verified

#377 Destroy cluster in bad shape
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: High Priority, Verified, bug

#366 log yaml output to ocp.create() function
  ocs_ci/ocs/ocp.py
Labels: Verified

#375 Add bugzilla integration
  docs/usage.md
  docs/writing_tests.md
  ocs_ci/framework/pytest_customization/marks.py
  setup.py
Labels: High Priority, Verified, enhancement

#282 Tier4 PVC related tests
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/ocs.py
  tests/disruption_helpers.py
  tests/fixtures.py
  tests/helpers.py
  tests/manage/test_pvc_deletion_during_io.py
  tests/manage/test_pvc_disruptive.py
  tests/test_fio_workload.py
Labels: Verified

#357 Testcase and helpers.py enhancement
  ocs_ci/ocs/constants.py
  tests/fixtures.py
  tests/helpers.py
  tests/manage/test_create_storage_class_pvc.py
  tests/manage/test_pvc_delete_verify_size_is_returned_to_backendpool.py
  tests/manage/test_pvc_disruptive.py
  tests/manage/test_verify_rbd_based_rwo_pvc.py
Labels: High Priority

#383 Suppress captured logs at end of session
  pytest.ini
Labels: High Priority

#391 Ceph block pool may not exists, check before deleting
  tests/fixtures.py
Labels: Verified

#398 Updating the yamls based on upstream rook changes
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/templates/ocs-deployment/cluster.yaml
  ocs_ci/templates/ocs-deployment/common.yaml
Labels: Verified

#400 conftest: Fix teardown finalizer
  tests/conftest.py
Labels: High Priority, bug

#355 TC-OCS-491: Configuring persistent volume on monitoring pods
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/monitoring.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/pvc.py
  ocs_ci/templates/openshift-infra/monitoring/configuring_pvc.yaml
  tests/e2e/test_running_cluster_monitoring_with_persistent_storage.py
Labels: Test Case, Verified

#396 Tier1 failure fix - OCS371
  tests/fixtures.py
  tests/manage/test_pvc_deletion_during_io.py
  tests/test_fio_workload.py
Labels: Verified

#402 Run IO multiple pods
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/pvc.py
  tests/fixtures.py
  tests/helpers.py
  tests/manage/test_pvc_concurrent_deletion_creation.py
  tests/manage/test_pvc_deletion_during_io.py
  tests/manage/test_pvc_disruptive.py
  tests/manage/test_rbd_csi_default_sc.py
  tests/manage/test_run_io_multiple_pods.py
  tests/test_fio_workload.py
Labels: Test Case, Verified

#422 Add delete flag to OCS class
  ocs_ci/ocs/resources/ocs.py
Labels: enhancement

#435 Google api
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/spreadsheet/__init__.py
  ocs_ci/utility/spreadsheet/spreadsheet_api.py
  setup.py
  tests/e2e/test_io_performance.py
  tests/helpers.py
  tests/manage/test_pvc_deletion_during_io.py
Labels: Verified

#440 Fix environment checker print layout
  ocs_ci/utility/environment_check.py
  setup.py
Labels: Verified

#401 Test case enhancement test_pvc_disruptive
  tests/helpers.py
  tests/manage/test_pvc_disruptive.py
Labels: Test Case, Verified, enhancement

#424 Testcase: (RBD & Cephfs) Create StorageClass with wrong provisioner
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/defaults.py
  tests/helpers.py
  tests/manage/test_create_storageclass_with_wrong_provisioner.py
Labels: Test Case, Verified

#368 Add Dynamic PVC creation tests with different combinations of accessmodes and reclaim policies
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/pvc.py
  ocs_ci/templates/app-pods/nginx.yaml
  tests/helpers.py
  tests/manage/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
Labels: Test Case, Verified, team/manage

#444 Deployment logging fix
  ocs_ci/framework/main.py
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: High Priority, Verified, bug

#385 Fix for issue 384
  ocs_ci/ocs/constants.py
  tests/helpers.py
  tests/manage/test_create_pvc_random_storage_class.py
  tests/manage/test_remove_mon_from_cluster.py
Labels: Verified

#464 Adding usage of CSI Ceph DS image
  conf/ocsci/downstream_config.yaml
  ocs_ci/templates/ocs-deployment/operator-openshift-with-csi.yaml
Labels: Verified

#463 Fix issue #456: Teardown getting stuck forever
  tests/helpers.py
  tests/manage/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
Labels: High Priority, Verified

#468 Improve logging on failures
  tests/helpers.py
Labels: Verified

#466 Sync ceph image with upstream rook/master
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified

#474 Organize manage team tests directories
  tests/manage/cluster/__init__.py
  tests/manage/cluster/cluster_expansion/__init__.py
  tests/manage/cluster/cluster_reduction/__init__.py
  tests/manage/cluster/nodes/__init__.py
  tests/manage/cluster/test_add_mds_to_cluster.py
  tests/manage/cluster/test_remove_mon_from_cluster.py
  tests/manage/cluster/upgrade/__init__.py
  tests/manage/monitoring/__init__.py
  tests/manage/monitoring/prometheus/__init__.py
  tests/manage/monitoring/prometheus/test_alerting_works.py
  tests/manage/noobaa/__init__.py
  tests/manage/pv_services/__init__.py
  tests/manage/pv_services/test_create_pvc_random_storage_class.py
  tests/manage/pv_services/test_create_storage_class_pvc.py
  tests/manage/pv_services/test_delete_create_pvc_same_name.py
  tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
  tests/manage/pv_services/test_pv_creation.py
  tests/manage/pv_services/test_pvc_concurrent_deletion_creation.py
  tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
  tests/manage/pv_services/test_pvc_deletion_during_io.py
  tests/manage/pv_services/test_pvc_disruptive.py
  tests/manage/pv_services/test_pvc_invalid_inputs.py
  tests/manage/pv_services/test_reclaim_policy.py
  tests/manage/pv_services/test_run_io_multiple_pods.py
  tests/manage/pv_services/test_verify_rbd_based_rwo_pvc.py
  tests/manage/storageclass/__init__.py
  tests/manage/storageclass/test_create_storageclass_with_same_name.py
  tests/manage/storageclass/test_create_storageclass_with_wrong_provisioner.py
  tests/manage/storageclass/test_rbd_csi_default_sc.py
  tests/manage/storageclass/test_storageclass_invalid.py
  tests/manage/storageclass/test_verify_all_fields_in_sc_yaml_with_oc_describe_sc.py
Labels: Verified

#481 Test case enhancement and fix - test_multiple_pvc_concurrent_creation_deletion
  tests/manage/pv_services/test_pvc_concurrent_deletion_creation.py
Labels: High Priority, Verified, enhancement

#410 Add "Jenkins" simulation workload
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/workloads/fio.py
  ocs_ci/utility/workloads/helpers.py
  ocs_ci/utility/workloads/jenkins.py
  tests/e2e/test_jenkins_simulation.py
Labels: Verified

#485 Adding bugzilla marker in test case test_multiple_pvc_concurrent_crea…
  tests/manage/pv_services/test_pvc_concurrent_deletion_creation.py
Labels: Verified

#414 Deployment of openshift-logging
  ocs_ci/ocs/constants.py
  ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/cl-csc.yaml
  ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/cl-namespace.yaml
  ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/cl-og.yaml
  ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/cl-sub.yaml
  ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/instance.yaml
  ocs_ci/templates/openshift-infra/logging-deployment/elasticsearch_operator/eo-csc.yaml
  ocs_ci/templates/openshift-infra/logging-deployment/elasticsearch_operator/eo-og.yaml
  ocs_ci/templates/openshift-infra/logging-deployment/elasticsearch_operator/eo-project.yaml
  ocs_ci/templates/openshift-infra/logging-deployment/elasticsearch_operator/eo-rbac.yaml
  ocs_ci/templates/openshift-infra/logging-deployment/elasticsearch_operator/eo-sub.yaml
  ocs_ci/utility/deployment_openshift_logging.py
Labels: Verified, team/e2e

#473 Added test for RWX with CephFS - OCS-542 and OCS-529
  tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
Labels: Test Case, Verified, team/manage

#486 Fixing environment checker format and login
  ocs_ci/utility/environment_check.py
  setup.py
Labels: Verified

#477 update reporting (add Test Run ID to reports)
  conf/ocsci/downstream_config.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: Verified

#459 Add validation whether pv exists in ceph backend and fix : test_pvc_delete_verify_size_is_returned_to_backendpool
  ocs_ci/ocs/resources/pvc.py
  tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Labels: Verified
