Repository red-hat-storage/ocs-ci, pull requests merged in 2019-10, with the labels that each got.

#845 Jenkins: Optionally gather logs on deploy failure
  .functional_ci_setup.py
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/utils.py
Labels: Verified

#783 vSphere-UPI Deployment
  conf/ocsci/vsphere_upi.yaml
  conf/ocsci/vsphere_upi_vars.yaml.example
  conf/ocsci/vsphere_upi_vars.yaml.skeleton
  docs/getting_started.md
  docs/usage.md
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/terraform.py
  ocs_ci/deployment/vmware.py
  ocs_ci/framework/main.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/csv.py
  ocs_ci/templates/ocp-deployment/install-config-vsphere-upi.yaml.j2
  ocs_ci/templates/ocp-deployment/terraform.tfvars.j2
  ocs_ci/utility/utils.py
  ocs_ci/utility/vsphere.py
  setup.py
Labels: Needs Deployment Testing, Verified

#847 Wait for catalog source before subscription
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/resources/catalog_source.py
Labels: High Priority, Verified, team/ecosystem

#850 Print consolidated config to the file
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem

#858 Read file before passing to loader for local yaml files
  ocs_ci/utility/templating.py
Labels: bug

#857 Fixing issue 856
  ocs_ci/ocs/resources/pod.py
Labels: Verified

#839 Move to downstream
  conf/ocsci/upstream_config.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/tests/test_config.py
Labels: Verified, team/ecosystem

#862 Allow lower requests/limits for worker instances
  conf/ocsci/production-aws-ipi.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
Labels: High Priority, Verified, team/ecosystem

#870 Change default libra to openshift-dev ssh key
  docs/debugging.md
  docs/getting_started.md
  ocs_ci/framework/conf/default_config.yaml
Labels: Code/Infra, High Priority, Verified

#873 collect_ocs_logs(): Skip if there is no kubeconfig
  ocs_ci/ocs/utils.py
Labels: Needs Testing

#843 check/create toolbox when ocs is deployed by other CI tools
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/utils.py
Labels: Verified

#885 Fixing noobaa requirements
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem

#807 Test MCG data reduction
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/resources/mcg.py
  tests/helpers.py
  tests/manage/mcg/conftest.py
  tests/manage/mcg/test_bucket_creation.py
  tests/manage/mcg/test_bucket_deletion.py
  tests/manage/mcg/test_write_to_bucket.py
Labels: Test Case, Verified, team/manage

#876 Adding vCPU option for vSphere platform
  conf/ocsci/production-vsphere-upi.yaml
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/templating.py
  setup.py
Labels: Verified, team/ecosystem

#877 Verify rook-ceph-operator deletion during resource creation
  tests/manage/pv_services/test_pvc_disruptive.py
Labels: Test Case, Verified, team/manage

#887 Reinitializing the terraform for destroy functionality for vSphere platform
  ocs_ci/deployment/terraform.py
  ocs_ci/deployment/vmware.py
Labels: Needs Deployment Testing, Verified

#880 Test delete operator during resource deletion
  tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
Labels: Test Case, Verified, team/manage

#833 Test delete rook-ceph-operator during deletion of PVCs and pods
  tests/helpers.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: Test Case, Verified, team/manage

#898 Add function for rsync
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/templates/openshift-infra/rsync-pod.yaml
Labels: Verified, enhancement, team/ecosystem

#889 Function to execute cmd on master/worker nodes.
  ocs_ci/ocs/ocp.py
Labels: Verified, team/e2e

#897 Fix for Mon/OSD PVC checks
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/utils.py
Labels: Verified

#900 Read clusterName from deployment metadata instead of from file
  ocs_ci/deployment/aws.py
Labels: Verified, team/ecosystem

#868 Registry backed by OCS and registry library functions
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/registry.py
  tests/helpers.py
Labels: Verified, team/e2e

#893 Rename ocs_operator_image to ocs_registry_image
  .functional_ci_setup.py
  conf/ocsci/downstream_config.yaml
  conf/ocsci/upstream_config.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, team/ecosystem

#907 Deployment of openshift-logging for 4.2 with updated images
  ocs_ci/ocs/constants.py
  ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/cl-sub.yaml
  ocs_ci/templates/openshift-infra/logging-deployment/elasticsearch_operator/eo-sub.yaml
  tests/e2e/logging/test_openshift-logging.py
Labels: Verified, team/e2e

#785 cluster expansion for add node and add capacity
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/cluster/cluster_expansion/test_add_capacity.py
  tests/manage/cluster/cluster_expansion/test_node_expansion.py
Labels: Verified

#899 Adding library for removing nodes
  ocs_ci/ocs/node.py
Labels: Code/Infra, Needs Testing, Verified, enhancement

#910 Add host network
  conf/ocsci/host_network_enabled.yaml
  ocs_ci/deployment/aws.py
  ocs_ci/deployment/deployment.py
  ocs_ci/utility/aws.py
Labels: Verified, team/ecosystem

#914 aws: Safely check for host_network setting
  ocs_ci/deployment/aws.py
Labels: bug

#916 Fix issue with VpcId
  ocs_ci/utility/aws.py
Labels: Needs Deployment Testing, bug, team/ecosystem

#931 Safe load yaml to fix YAMLLoadWarning
  ocs_ci/ocs/cluster.py
Labels: Verified

#928 Adding rbd block type volume creation in test case
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: Test Case, Verified, team/manage

#930 Skip adding disk for operator deployment
  ocs_ci/deployment/vmware.py
Labels: Verified

#925 Add config for us-east-1 region
  conf/ocsci/aws_region_us-east-1.yaml
Labels: Needs Testing, team/ecosystem

#908 Update test_disruptive_during_pod_pvc_deletion to use block type volume
  tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
Labels: Test Case, Verified, enhancement, team/manage

#924 Added additional verification to deployment test
  ocs_ci/ocs/constants.py
  tests/ecosystem/deployment/test_deployment.py
Labels: Verified, team/ecosystem

#938 setup.py: remove particular version for kubernetes
  setup.py
Labels: Needs Deployment Testing, Needs Testing

#946 Skip ocs install verification if we skip ocs deployment
  tests/ecosystem/deployment/test_deployment.py
Labels: High Priority, team/ecosystem

#943 Adding block type RWO pvc in tests
  tests/manage/pv_services/test_pvc_disruptive.py
  tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
Labels: Test Case, Verified, team/manage

#919 Test case update to create rdb block type volume
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Labels: Test Case, Verified, enhancement, team/manage

#945 Adding device size for production environments
  conf/ocsci/production_device_size.yaml
Labels: Verified

#917 Various fixes for Add MDS test
  tests/manage/cluster/test_add_mds_to_cluster.py
Labels: Verified

#951 Minor fix in test_object_integrity
  tests/manage/mcg/test_object_integrity.py
Labels: Verified, bug, team/manage

#947 Fix issue #802
  ocs_ci/utility/environment_check.py
Labels: Verified

#920 Fix storage cluster name to use default name as in UI
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/registry.py
Labels: High Priority, Verified
