Repository red-hat-storage/ocs-ci, pull requests merged in 2020-05, with the labels that each got.

#1951 constant target in fio storageutilization workload
  ocs_ci/ocs/fiojob.py
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/test_workload_fixture.py
Labels: Verified, size/L

#1983 Add sanity test post deployment
  tests/ecosystem/deployment/test_deployment.py
Labels: size/S

#1985 BZ 1830702 decorator to test_recovery_from_volume_deletion
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/XS

#1423 Validate pods are not OOMKILLED
  ocs_ci/ocs/resources/pod.py
  tests/e2e/scale/test_pods_are_not_oomkilled_while_running_ios.py
  tests/helpers.py
Labels: Test Case, Verified, size/L, team/e2e

#1823 Remove BZ decrators from node drain tests
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/XS

#1950 Pgsql: Restructure and enhancements
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/pgsql.py
  ocs_ci/ocs/ripsaw.py
  ocs_ci/utility/utils.py
  tests/e2e/workloads/pgsql/test_pgsql.py
  tests/e2e/workloads/pgsql/test_pgsql_node_drain.py
  tests/e2e/workloads/pgsql/test_pgsql_pod_respin.py
  tests/e2e/workloads/test_pgsql.py
  tests/e2e/workloads/test_pgsql_node_drain.py
  tests/e2e/workloads/test_pgsql_pod_respin.py
Labels: size/XL, team/e2e

#1977 Implementing coverage for BZ 1830015
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/pod.py
  tests/conftest.py
  tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_proactive_IPI.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
  tests/manage/z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: size/L

#1986 Config file to deploy OCP 4.4 GAed version
  conf/ocp_version/ocp-4.4-ga-config.yaml
Labels: Needs Deployment Testing, size/S

#1981 wait for CSRs based on number of nodes
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/csr.py
Labels: Verified, size/M, team/ecosystem

#1988 Fix issue:1987
  tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
Labels: size/XS

#1989 set nrfiles=8 in storage utilization fio config
  ocs_ci/ocs/fiojob.py
Labels: Verified, size/XS

#1825 Support add_capacity() over Baremetal Cluster
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Needs Testing, size/L

#1978 Fixed get_typed_nodes( ) to work for collocated nodes.
  ocs_ci/ocs/node.py
Labels: size/XS

#1973 Add error_condition option for wait_for_resource()
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/fiojob.py
  ocs_ci/ocs/ocp.py
Labels: Verified, size/M

#2004 Changing OCP channel from stable to fast to install OCP 4.4.3
  conf/ocp_version/ocp-4.4-ga-config.yaml
Labels: Verified, size/XS

#2012 Fix test_add_capacity failure on AWS,vmware
  ocs_ci/ocs/resources/storage_cluster.py
Labels: High Priority, Verified, size/S

#1900 OCS label nodes post node expansion
  tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
Labels: Verified, size/M

#1859 Add RHCOS node to an existing OCS cluster
  conf/ocsci/aws_upi_rhcos_workers.yaml
  ocs_ci/deployment/aws.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/aws.py
Labels: Verified, size/XL, team/ecosystem

#2018 Production AWS configs for LSO deployments
  conf/deployment/aws/ipi_1az_rhcos_lso_3m_3w.yaml
  conf/deployment/aws/ipi_3az_rhcos_lso_3m_3w.yaml
  conf/deployment/aws/upi_1az_rhcos_lso_3m_3w.yaml
  conf/deployment/aws/upi_1az_rhel7_lso_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhcos_lso_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhel7_lso_3m_3w.yaml
Labels: size/M, team/ecosystem

#1990 Remove skip from logging testcase
  tests/e2e/logging/test_openshift-logging.py
Labels: Verified, size/XS

#2027 Improve run_io_in_background fixture
  conf/ocsci/io_in_bg.yaml
  ocs_ci/framework/conf/default_config.yaml
  tests/conftest.py
Labels: Verified, size/M

#2031 Minor update to wait_for_cluster_connectivity
  ocs_ci/ocs/ocp.py
Labels: Verified, size/XS

#2003 Fix for Issue 1777: Increase timeout to 60 seconds for pod deletion to start
  tests/manage/pv_services/test_ceph_daemon_kill_during_resource_deletion.py
Labels: Verified, size/XS, team/manage

#2034 Add OCS 4.5 config
  conf/ocs_version/ocs-4.5.yaml
  ocs_ci/framework/main.py
Labels: Verified, size/S, team/ecosystem

#2046 FIX F541 f-string is missing placeholders
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/factory.py
  ocs_ci/deployment/ocp.py
  ocs_ci/framework/pytest_customization/tests/test_pytest.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/ocs/registry.py
  ocs_ci/ocs/resources/cloud_manager.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/ripsaw.py
  ocs_ci/utility/csr.py
  ocs_ci/utility/prometheus.py
  ocs_ci/utility/uninstall_openshift_logging.py
  tests/conftest.py
  tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
  tests/e2e/performance/test_small_file_workload.py
  tests/ecosystem/upgrade/test_noobaa.py
  tests/ecosystem/upgrade/test_resources.py
  tests/fixtures.py
  tests/helpers.py
  tests/libtest/test_cluster_utils.py
  tests/libtest/test_fio_workload.py
  tests/manage/mcg/helpers.py
  tests/manage/mcg/test_bucket_deletion.py
  tests/manage/mcg/test_multi_region.py
  tests/manage/mcg/test_multipart_upload.py
  tests/manage/mcg/test_object_integrity.py
  tests/manage/mcg/test_verify_noobaa_status.py
  tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py
  tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
  tests/manage/pv_services/test_no_space_left.py
  tests/manage/pv_services/test_pv_creation.py
  tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
  tests/manage/pv_services/test_pvc_disruptive.py
  tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
  tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
  tests/manage/storageclass/test_create_multiple_sc_with_different_pool_name.py
  tests/manage/z_cluster/nodes/test_az_failure.py
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
  tests/manage/z_cluster/nodes/test_nodes_restart.py
  tests/manage/z_cluster/test_remove_mon_from_cluster.py
  tests/sanity_helpers.py
Labels: Code/Infra, High Priority, size/L

#1839 Increase timeout for upgrade
  ocs_ci/ocs/resources/storage_cluster.py
Labels: size/XS, team/ecosystem

#2048 add bugzilla marker for utilization tests
  tests/manage/monitoring/prometheus/test_capacity.py
Labels: size/XS

#2047 removed specific imports, changed to constants.X
  ocs_ci/ocs/ocp.py
Labels: Verified, size/XS

#2055 Directly use upstream repo yamls for AMQ
  ocs_ci/ocs/amq.py
  ocs_ci/ocs/constants.py
  tests/e2e/workloads/test_amq_streamer_creation.py
Labels: Verified, size/S

#2057 Pass out_yaml_format=False in get_ceph_status
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/cluster.py
  tests/helpers.py
Labels: Verified, bug, size/S

#1949 Update daemon kill process to handle multiple osd per node
  tests/disruption_helpers.py
Labels: Verified, size/S

#2051 Fix creation of anonymous boto3 S3 resource
  tests/ecosystem/upgrade/test_noobaa.py
  tests/manage/mcg/helpers.py
  tests/manage/mcg/test_object_integrity.py
  tests/manage/mcg/test_write_to_bucket.py
Labels: Verified, size/M

#2028 Improve auth config loading mechanism
  ocs_ci/ocs/constants.py
  ocs_ci/utility/utils.py
Labels: Verified, enhancement, size/M

#2050 Add LSO to generated testrun_name if we are configured for it
  ocs_ci/utility/utils.py
Labels: size/XS, team/ecosystem

#2043 Follow up PR to #1825 Support add_capacity() over Baremetal Cluster
  ocs_ci/ocs/resources/storage_cluster.py
Labels: size/XS

#2068 Added polarion IDs for AWS LSO production configs
  conf/deployment/aws/ipi_1az_rhcos_lso_3m_3w.yaml
  conf/deployment/aws/ipi_3az_rhcos_lso_3m_3w.yaml
  conf/deployment/aws/upi_1az_rhcos_lso_3m_3w.yaml
  conf/deployment/aws/upi_1az_rhel7_lso_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhcos_lso_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhel7_lso_3m_3w.yaml
Labels: size/S, team/ecosystem

#2066 Fix issue 2064: Correction in LocalVolume name
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/XS

#2076 MCG-Test-Fix: Replace resources with clients
  tests/manage/mcg/test_object_integrity.py
  tests/manage/mcg/test_write_to_bucket.py
Labels: Verified, size/XS

#2073 Changing openshift installer to use release-4.3 branch
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/M, team/ecosystem

#2042 Added function to fetch all device paths irrespective of platform
  ocs_ci/utility/localstorage.py
Labels: size/M

#1984 Push the smallfile test results into elasticsearch server.
  ocs_ci/ocs/node.py
  ocs_ci/ocs/ocp.py
  ocs_ci/templates/workloads/smallfile/SmallFile.yaml
  requirements.txt
  tests/e2e/performance/test_small_file_workload.py
Labels: size/L

#2087 Updated requests dependency version to 2.23.0
  setup.py
Labels: High Priority, Verified, size/XS, team/ecosystem

#2001 Keep a list of remaining clusters to log at the end of the execution
  ocs_ci/cleanup/aws/cleanup.py
Labels: size/M, team/ecosystem

#2063 Move add_capacity test as last one
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Labels: Verified, size/M

#2019 Fixes #2017
  tests/e2e/workloads/test_couchbase.py
Labels: Needs Testing, size/S

#2082 Change fio container
  tests/conftest.py
Labels: Verified, size/XS

#2091 Move OCP 4.4 as default
  ocs_ci/framework/conf/default_config.yaml
Labels: Needs Deployment Testing, size/XS, team/ecosystem

#2092 updating memory for nodes in vSphere platform
  ocs_ci/deployment/vmware.py
Labels: Verified, size/S, team/ecosystem

#2094 Asserting on empty list for PVs creation
  ocs_ci/deployment/deployment.py
Labels: Verified, size/XS, team/ecosystem

#2071 get secrets from auth file from s3
  ocs_ci/framework/__init__.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/utility/aws.py
Labels: Verified, size/M

#2089 Move elasticsearch and numpy from requirements.txt to setup.py
  requirements.txt
  setup.py
Labels: size/XS, team/ecosystem

#1994 Function to wait for image/sub-volume deletion in backend
  tests/helpers.py
  tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
Labels: Verified, size/M

#2041 Make sure we use all available zones for workers
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/utils.py
Labels: Verified, size/M, team/ecosystem

#1847 Cluster expansion : Add node AWS+UPI --> RHCOS+RHEL
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
Labels: Verified, size/M

#2114 Fix in updating portable field in LSO deployment
  ocs_ci/deployment/deployment.py
Labels: Verified, size/XS

#1980 Add option to stop cluster nodes when not in use
  docs/usage.md
  ocs_ci/cleanup/aws/cleanup.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/pause/pause.py
  setup.py
  tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: Verified, size/L

#2016 AMQ:Restructure and enhancements
  ocs_ci/ocs/amq.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/workloads/amq/hello-world-consumer.yaml
  ocs_ci/templates/workloads/amq/hello-world-producer.yaml
  tests/e2e/workloads/amq/test_amq_streamer_creation.py
  tests/e2e/workloads/test_amq_streamer_creation.py
Labels: size/XL, team/e2e

#2069 Use proper certificates for AWS, S3 and RPC requests
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/bucket_policy.py
  ocs_ci/ocs/resources/mcg.py
  tests/conftest.py
  tests/ecosystem/upgrade/test_noobaa.py
  tests/helpers.py
  tests/manage/mcg/helpers.py
  tests/manage/mcg/test_bucket_creation.py
  tests/manage/mcg/test_bucket_deletion.py
  tests/manage/mcg/test_bucket_policy.py
  tests/manage/mcg/test_multi_region.py
  tests/manage/mcg/test_multipart_upload.py
  tests/manage/mcg/test_object_integrity.py
  tests/manage/mcg/test_write_to_bucket.py
Labels: Verified, enhancement, size/L

#2117 Wait for CSR to generate and approve after bootstrapping is completed
  ocs_ci/deployment/vmware.py
Labels: Verified, size/S, team/ecosystem

#2121 Run MCG CLI locally instead via operator pod
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/mcg.py
  tests/conftest.py
Labels: Verified, size/M

#2122 separate function for updating machine configuration
  ocs_ci/deployment/vmware.py
Labels: Verified, size/L, team/ecosystem

#2083 Add 3 minutes to wait for bucket quota alert
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/prometheus/test_noobaa.py
Labels: Verified, size/XS

#2130 Install previous version from the new build
  docs/usage.md
  ocs_ci/framework/main.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/ecosystem/deployment/test_deployment.py
Labels: Verified, size/M

#2133 Add OCP 4.5 config file
  conf/ocp_version/ocp-4.5-config.yaml
Labels: Verified, size/S, team/ecosystem

#2080 Use official AWSCLI Docker image for the AWSCLI pod
  ocs_ci/templates/app-pods/awscli.yaml
  tests/conftest.py
  tests/ecosystem/upgrade/conftest.py
  tests/manage/mcg/helpers.py
  tests/manage/mcg/test_object_integrity.py
  tests/manage/mcg/test_write_to_bucket.py
  tests/manage/monitoring/conftest.py
Labels: Verified, enhancement, size/M

#2125 Write failed cluster deletions to a file
  ocs_ci/cleanup/aws/cleanup.py
Labels: size/XS, team/ecosystem

#2139 Work around copying the MCG cert to the AWSCLI pod
  tests/conftest.py
  tests/helpers.py
  tests/manage/mcg/helpers.py
Labels: Verified, size/S

#2126 Adds test for pod reattach time
  tests/e2e/performance/test_pod_reattachtime.py
Labels: Verified, performance, size/L

#2025 Skip TestRemoveMonFromCluster
  tests/manage/z_cluster/test_remove_mon_from_cluster.py
Labels: Verified, size/XS

#2095 docs: add deployment_without_ocs.md
  docs/README.md
  docs/deployment_without_ocs.md
  index.rst
Labels: documentation, size/M

#2123 Temporarily skip some tests in tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py due to #2101
  tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
Labels: Verified, size/S, team/manage

#2144 Fix labels in getting all pods
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/XS, team/ecosystem

#2037 Functionality to determine the cluster throughput limit and run IO at a given percentage of it
  docs/usage.md
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/cluster_load.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: Verified, size/XL

#2135 Fix retry for selection daemon
  tests/disruption_helpers.py
Labels: Verified, size/XS

#2153 Smallfiles | change the deviation calculation
  tests/e2e/performance/test_small_file_workload.py
Labels: size/S

#1996 Test add capacity with restart node, when capacity near full ratio
  ocs_ci/ocs/fiojob.py
  tests/conftest.py
  tests/manage/monitoring/conftest.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
  tests/manage/z_cluster/conftest.py
Labels: Verified, size/L

#2145 fiojob: fetch ceph full rations from osd map
  ocs_ci/ocs/fiojob.py
Labels: Verified, size/S

#2159 Fixes the change in ripsaw's crd directory name
  ocs_ci/ocs/ripsaw.py
Labels: Skip test, bug, size/XS

#2158 Fix registry deployment
  ocs_ci/ocs/registry.py
Labels: Verified, size/S, team/ecosystem

#2113 LSO Deployment - vSphere
  conf/ocsci/vsphere_upi_local_storage_directpath.yaml
  conf/ocsci/vsphere_upi_local_storage_rdm.yaml
  conf/ocsci/vsphere_upi_local_storage_vmdk.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/templates/ocs-deployment/local-volume.yaml
  ocs_ci/utility/vsphere.py
Labels: Verified, size/L, team/ecosystem

#2109 Fixes #2108
  tests/e2e/workloads/test_couchbase.py
Labels: Needs Testing, size/XS

#2167 BZ 1825675 for test_detach_attach_worker_volume
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/XS

#2008 Add functionality to push data to perf dashboard
  ocs_ci/ocs/constants.py
  ocs_ci/utility/performance_dashboard.py
  tests/e2e/performance/test_io_performance.py
Labels: Verified, size/L

#2170 Fix verification of OSDs and MONs backed by PVC
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/M, team/ecosystem

#2085 Updating templates for ocp 4.4 version
  conf/ocp_version/ocp-4.4-config.yaml
  conf/ocp_version/ocp-4.4-ga-config.yaml
Labels: Verified, size/XS, team/ecosystem

#2111 Split capacity tests
  tests/manage/monitoring/prometheus/test_capacity.py
Labels: size/L

#1995 Adding libraries for adding RHCOS nodes - vSphere platform
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/csr.py
Labels: Verified, size/L, team/ecosystem

#2149 Fix #2137 - Smallfile getting user and email
  tests/e2e/performance/test_small_file_workload.py
Labels: Needs Testing, performance, size/M

#2172 Correcting the skip reasons
  ocs_ci/framework/pytest_customization/marks.py
Labels: size/XS, team/ecosystem

#2155 increase the timeout of ceph health check
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/XS

#2183 Fix AWS cleanup and reduce time for 16 hours for PR validation
  ocs_ci/cleanup/aws/cleanup.py
  ocs_ci/cleanup/aws/defaults.py
Labels: High Priority, Verified, bug, size/S, team/ecosystem

#2186 Production config files for LSO Deployment
  conf/deployment/vsphere/upi_1az_rhcos_vmfs_directpath_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vmfs_rdm_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vmfs_vmdk_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_directpath_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_rdm_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_directpath_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_rdm_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_vmdk_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_directpath_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_rdm_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_vmdk_3m_3w.yaml
Labels: size/L

#2148 Fix issue 2147
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/pod.py
Labels: size/S

#2184 Fix MCG upgrade tests
  ocs_ci/ocs/resources/storage_cluster.py
  tests/ecosystem/upgrade/test_noobaa.py
  tests/ecosystem/upgrade/test_upgrade.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Labels: Verified, size/L

#2193 AWS LSO ceph osd tree verification
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S, team/ecosystem

#2119 Add mark to run tests only in red hat internal lab
  ocs_ci/framework/pytest_customization/marks.py
  tests/e2e/performance/test_vdbench_workload.py
Labels: size/XS
