Repository red-hat-storage/ocs-ci, pull requests merged in 2020-06, with the labels that each got.

#2166 Fix node replacement tests to validate also OSD prepare and DC pods
  tests/manage/z_cluster/nodes/helpers.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_proactive_IPI.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
  tests/manage/z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
Labels: Verified, size/L

#2197 Fix OCP 4.3 repo for RHEL
  ocs_ci/repos/ocp_4_3.repo
Labels: Verified, size/XS, team/ecosystem

#2163 Skip the multiregion test because of a bug
  tests/manage/mcg/test_multi_region.py
Labels: Verified, size/XS

#2171 change method of workload_storageutilization_checksum_rbd to use static size
  tests/manage/monitoring/conftest.py
Labels: Verified, bug, size/XS

#2202 Fix RHEL repos for ocp 4.4 and 4.2
  ocs_ci/repos/ocp_4_2.repo
  ocs_ci/repos/ocp_4_4.repo
Labels: Verified, size/XS

#2204 Fix RHEL repos for OCP 4.2 and 4.3
  ocs_ci/repos/ocp_4_2.repo
  ocs_ci/repos/ocp_4_3.repo
Labels: Verified, size/S, team/ecosystem

#2120 downstream ci: tag successful builds with latest-stable-X.Y
  Jenkinsfile
Labels: size/XS

#2191 Load default ocp version conf if ocs version or registry image is provided
  conf/ocp_version/README.md
  conf/ocs_version/README.md
  conf/ocs_version/ocs-4.2.yaml
  conf/ocs_version/ocs-4.3.yaml
  conf/ocs_version/ocs-4.4.yaml
  conf/ocs_version/ocs-4.5.yaml
  index.rst
  ocs_ci/framework/main.py
Labels: Verified, size/S, team/ecosystem

#2157 change OCS-2125 to use fixed storage size
  ocs_ci/ocs/fiojob.py
  tests/manage/monitoring/test_workload_fixture.py
Labels: Verified, size/M

#2164 Added local-storage related functions in utility module properly
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/utility/localstorage.py
Labels: size/L

#2006 Added Support to Stop,Start,Restart baremetal nodes
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/baremetal.py
  setup.py
  tests/sanity_helpers.py
Labels: Verified, size/L

#1895 FIO test using ripsaw tool
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ripsaw.py
  ocs_ci/templates/workloads/fio/benchmark_fio.yaml
  ocs_ci/templates/workloads/fio/drop_cache_pod.yaml
  tests/e2e/performance/test_fio_benchmark.py
Labels: Verified, performance, size/L

#2222 Catching the exception in retry for checking pods in monitoring NS
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/S, team/ecosystem

#2110 Changed restart_nodes() implementation to directly call reboot
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/aws.py
  ocs_ci/utility/vsphere.py
  tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
  tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
  tests/manage/z_cluster/nodes/test_nodes_restart.py
Labels: Verified, size/L

#2112 Skip stop/shutdown test cases on lso based cluster
  ocs_ci/framework/pytest_customization/marks.py
  tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
Labels: Verified, size/XS

#2229 Change order for upgrade mons and mgr
  tests/ecosystem/upgrade/test_upgrade.py
Labels: bug, size/XS, team/ecosystem

#2216 Verify the status of osd-prepare pods workaround
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Labels: Verified, size/S, workaround

#2240 provide interface while creating resources using sanity helpers
  tests/sanity_helpers.py
Labels: Verified, size/XS

#2227 Fixing in getting indexes
  ocs_ci/ocs/platform_nodes.py
Labels: Verified, size/XS, team/ecosystem

#2237 move checksum workload_with_checksum test to tier2
  tests/manage/monitoring/test_workload_with_distruptions.py
Labels: size/XS

#2248 Fixing doc string for get_lunids
  ocs_ci/utility/vsphere.py
Labels: size/XS, team/ecosystem

#2251 Enhancements for openshift-logging
  ocs_ci/utility/deployment_openshift_logging.py
  tests/conftest.py
  tests/e2e/logging/test_openshift-logging.py
Labels: Verified, enhancement, size/S, team/e2e

#2116 Use latest-stable
  conf/ocs_version/ocs-4.2.yaml
  conf/ocs_version/ocs-4.3.yaml
  conf/ocs_version/ocs-4.4.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
Labels: size/S, team/ecosystem

#2142 Assert when number of PVs created doesn't match with expected number
  ocs_ci/deployment/deployment.py
Labels: Verified, size/S, team/ecosystem

#2011 validate noobaa status
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/mcg.py
  tests/manage/mcg/test_verify_noobaa_status.py
Labels: Verified, size/M, team/manage

#2258 Adding retry for approving CSRs
  ocs_ci/utility/csr.py
Labels: Verified, size/XS, team/ecosystem

#2136 Refactor tests to work on OCS 4.5, work around missing `service-ca.crt`
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/bucket_policy.py
  ocs_ci/ocs/resources/mcg.py
  tests/conftest.py
  tests/helpers.py
  tests/manage/mcg/test_bucket_creation.py
Labels: Verified, size/L

#2265 Log thread name in ocs logger
  tests/conftest.py
Labels: Verified, size/XS, team/ecosystem

#2243 Adding wait time after the restart/stop nodes
  tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
Labels: Verified, size/M

#2252 Erase partition on RDM disk before adding to node
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/vsphere.py
Labels: Verified, size/S, team/ecosystem

#2162 set fiojob backoffLimit to 0
  tests/conftest.py
  tests/ecosystem/upgrade/conftest.py
Labels: Verified, size/S

#2188 Changes for disconnected cluster
  conf/ocsci/disconnected_cluster.yaml.example
  ocs_ci/ocs/utils.py
  ocs_ci/utility/utils.py
  tests/conftest.py
  tests/helpers.py
Labels: Verified, size/L, team/ecosystem

#2270 PR to fix get_fio_result() issue in test_pods_are_not_oomkilled_while_running_ios TC
  tests/e2e/scale/test_pods_are_not_oomkilled_while_running_ios.py
Labels: High Priority, Test Case, Verified, scale, size/XS

#2275 Changing the bucket names based on ocp versions
  ocs_ci/deployment/aws.py
Labels: Verified, size/S, team/ecosystem

#2150 Cluster load: Determine cluster limit by latency growth + use DC pods
  docs/usage.md
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/framework/testlib.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/cluster_load.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/templates/workloads/fio/fio_dc.yaml
  ocs_ci/utility/environment_check.py
  ocs_ci/utility/utils.py
  setup.py
  tests/conftest.py
  tests/e2e/logging/test_openshift-logging.py
  tests/fixtures.py
  tests/helpers.py
Labels: Verified, size/XL

#2234 Fix get version for ocs to push to dashboard
  ocs_ci/utility/performance_dashboard.py
Labels: Needs Testing, size/S

#2105 Fixture for running pgsql workload
  ocs_ci/ocs/pgsql.py
  ocs_ci/ocs/ripsaw.py
  tests/conftest.py
Labels: Verified, size/M, team/e2e

#2168 Couchbase workload restructure
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/couchbase.py
  ocs_ci/ocs/pillowfight.py
  ocs_ci/templates/workloads/couchbase/server/couchbase-worker-example.yaml
  tests/e2e/workloads/couchbase/test_couchbase.py
Labels: Verified, size/L

#2254 Default OCP and OCS versions to 4.5
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/S, team/ecosystem

#2241 Fix for issue #2238
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/ocp.py
  ocs_ci/utility/utils.py
  tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
Labels: Verified, size/L

#2279 WA: Skip logging deployment for OCP 4.5
  tests/e2e/logging/test_openshift-logging.py
Labels: size/XS, team/ecosystem

#2214 Fix TC test_detach_attach_2_data_volumes failures
  ocs_ci/ocs/constants.py
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/M

#2200 Throw exception in wait_for_new_node_to_be_ready() when the newly added node failed to reach Ready state
  ocs_ci/ocs/machine.py
Labels: Verified, size/M

#2269 FIO | Pushing results into codespeed
  tests/e2e/performance/test_fio_benchmark.py
Labels: Needs Testing, size/S

#2280 Make sure we use ocs nodes in add capacity test
  ocs_ci/ocs/node.py
  ocs_ci/ocs/platform_nodes.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
Labels: Verified, size/M

#2220 Added decorator ipi_deployment_required to test test_simultaneous_drain_of_two_ocs_nodes
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/XS

#2297 Update: tests/e2e/workloads/couchbase/test_couchbase.py
  tests/e2e/workloads/couchbase/test_couchbase.py
Labels: size/XS

#2282 add pending status to noobaa alerts
  tests/manage/monitoring/prometheus/test_noobaa.py
Labels: Verified, size/M

#2289 Supporting LSO deployment for VMFS datastore in vSphere platform
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/vsphere.py
Labels: Verified, size/L, team/ecosystem

#1869 Fixes: #1638 - Uninstall OCS
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pvc.py
  ocs_ci/ocs/uninstall.py
Labels: Verified, size/L

#2262 pgsql_debug
  ocs_ci/ocs/node.py
  ocs_ci/ocs/pgsql.py
  setup.py
  tests/e2e/workloads/pgsql/test_pgsql.py
  tests/e2e/workloads/pgsql/test_pgsql_node_drain.py
  tests/e2e/workloads/pgsql/test_pgsql_node_reboot.py
  tests/e2e/workloads/pgsql/test_pgsql_pod_respin.py
Labels: Verified, size/L, team/e2e

#2302 Fix issue-2299 and also updated new tc id
  ocs_ci/ocs/amq.py
  tests/e2e/workloads/amq/test_amq_streamer_creation.py
Labels: Verified, bug, size/XS

#2300 Ignore rook-ceph-drain-canary pod leftover for the test cases which d…
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/environment_check.py
  tests/conftest.py
  tests/manage/pv_services/test_pvc_disruptive.py
  tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: Verified, size/M

#2301 Removing the workaround for RSA version since google-auth is compatable with latest rsa version
  setup.py
Labels: Verified, size/XS, team/ecosystem

#2303 Renaming LSO yaml files to reflect consistency
  conf/deployment/vsphere/upi_1az_rhcos_vmfs_lso_directpath_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vmfs_lso_rdm_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vmfs_lso_vmdk_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_lso_directpath_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_lso_rdm_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_lso_vmdk_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_lso_directpath_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_lso_rdm_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_lso_vmdk_3m_3w.yaml
Labels: team/ecosystem

#2308 Collect Noobaa DB dump upon MCG/deployment/upgrade test failures
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/utils.py
  tests/manage/mcg/test_bucket_creation.py
Labels: Verified, size/M

#2287 add ceph health check to alerts tests
  tests/manage/monitoring/conftest.py
Labels: Verified, size/S

#2323 Fix for issue #2319: Modified helper functions used for verifying backend volume deletion
  tests/helpers.py
Labels: High Priority, size/S

#2316 Enhanced get_ceph_cluster_iops() function
  ocs_ci/ocs/cluster.py
Labels: High Priority, scale, size/S

#2330 Fix #2329 with get provider name
  ocs_ci/ocs/node.py
Labels: Verified, size/XS

#2328 Fix issue with missing imge_id for new DS builds
  ocs_ci/utility/utils.py
Labels: size/XS, team/ecosystem

#2291 Fixes minor issues around FIO test
  tests/e2e/performance/test_fio_benchmark.py
Labels: performance, size/XS

#2152 Enhancements for pod_factory_fixture and test_dynamic_pvc_accessmodes_with_reclaim_policies.py
  tests/conftest.py
  tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
Labels: Verified, size/L, team/manage

#2161 Add wait time to start I/O on pod and collect file list
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/M

#2337 Disable the bootstrap removal code due to vSphere provider issue
  ocs_ci/deployment/vmware.py
Labels: Verified, size/S, team/ecosystem

#2056 Add new platform azure support for testing
  conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
  ocs_ci/deployment/azure.py
  ocs_ci/deployment/factory.py
  ocs_ci/ocs/platform_nodes.py
Labels: Needs Testing, size/S

#2294 Convert OCS Upgrade to OOP
  ocs_ci/ocs/ocs_upgrade.py
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, size/XL, team/ecosystem, team/manage

#2343 Update test_pvc_resize
  tests/manage/pv_services/pvc_resize/__init__.py
  tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
  tests/manage/pv_services/test_pvc_resize.py
Labels: Test Case, Verified, team/manage

#2208 Fix disk replacement procedure for VMWare clusters
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/L

#2352 Freeze requirement versions
  requirements-dev.txt
  requirements-docs.txt
  setup.py
Labels: size/M, team/ecosystem

#2353 Pin junit_family to xunit1
  pytest.ini
Labels: Verified, size/XS, team/ecosystem

#2358 Adding ocp4.5 repo file
  ocs_ci/repos/ocp_4_5.repo
Labels: Verified, size/M, team/ecosystem

#2355 Cluster load: Do not load during deployment
  ocs_ci/ocs/cluster_load.py
  tests/conftest.py
Labels: Verified, size/S

#1911 Noobaa workload during upgrade
  index.rst
  ocs_ci/ocs/constants.py
  ocs_ci/templates/workloads/fio/README.md
  ocs_ci/templates/workloads/fio/config_s3.fio
  ocs_ci/utility/utils.py
  tests/ecosystem/upgrade/conftest.py
  tests/ecosystem/upgrade/test_noobaa.py
Labels: Test Case, Verified, size/L, team/ecosystem

#2314 Enable Noobaa auto scale post deployment
  conf/ocsci/noobaa_endpoints_2.yaml
  conf/ocsci/noobaa_endpoints_5.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/resources/storage_cluster.py
  tests/ecosystem/deployment/test_deployment.py
Labels: Verified, size/M

#2366 Have 2 noobaa endpoints as default
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/XS

#2261 Add capacity when one of the osd pods gets deleted
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/cluster_expansion/test_delete_osd_pod.py
Labels: Verified, size/M

#2268 Run amq benchmark pod and get test results
  ocs_ci/ocs/amq.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/workloads/amq/amq_workload.yaml
  ocs_ci/templates/workloads/amq/benchmark/Chart.yaml
  ocs_ci/templates/workloads/amq/benchmark/templates/_helpers.tpl
  ocs_ci/templates/workloads/amq/benchmark/templates/benchmark-worker.yaml
  ocs_ci/templates/workloads/amq/benchmark/templates/benchmark.yaml
  ocs_ci/templates/workloads/amq/benchmark/values.yaml
  ocs_ci/templates/workloads/amq/driver-kafka.yaml
  ocs_ci/templates/workloads/amq/rbac.yaml
  tests/e2e/workloads/amq/test_amq_streamer_creation.py
Labels: Verified, size/XL, team/e2e

#2359 added post_ocp_upgrade marker into 2 tier1 tests
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
Labels: size/XS

#2255 Export all pgbench pods run outputs to google spreadsheet
  ocs_ci/ocs/pgsql.py
  tests/e2e/workloads/pgsql/test_pgsql.py
Labels: Verified, size/L, team/e2e

#2365 Fix: Fails to get pgsql pods when namespace is switched.
  ocs_ci/ocs/pgsql.py
  ocs_ci/ocs/ripsaw.py
Labels: Verified, bug, size/XS, team/e2e

#2107 Remove test_registry_image_push_pull.py
  tests/e2e/registry/test_registry_image_push_pull.py
Labels: size/M

#2373 Fix order in upgrade for subscription
  tests/ecosystem/upgrade/test_upgrade.py
Labels: size/XS

#2226 Warn about misconfiguration with MCG
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/mcg.py
Labels: Verified, size/S

#2272 Remove service-ca workaround
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/templates/app-pods/awscli.yaml
  ocs_ci/templates/mcg/aws-cli-service-ca-configmap.yaml
  tests/conftest.py
  tests/helpers.py
Labels: Verified, size/L

#2370 changing gevent version to compatible with python3.8
  setup.py
Labels: Verified, size/XS, team/ecosystem

#2350 AWS LSO alignment with doc
  conf/deployment/aws/ipi_1az_rhcos_lso_3m_3w.yaml
  conf/deployment/aws/ipi_3az_rhcos_lso_3m_3w.yaml
  conf/deployment/aws/upi_1az_rhcos_lso_3m_3w.yaml
  conf/deployment/aws/upi_1az_rhel7_lso_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhcos_lso_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhel7_lso_3m_3w.yaml
  conf/ocsci/aws_i3_local_storage.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/templates/ocs-deployment/local-volume.yaml
  ocs_ci/utility/localstorage.py
  tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Labels: Verified, size/M, team/ecosystem

#2320 ElasticSearch module to use with ripsaw
  ocs_ci/ocs/elasticsearch.py
  ocs_ci/templates/app-pods/es-pvc.yaml
  ocs_ci/templates/app-pods/esq.yaml
  ocs_ci/templates/workloads/smallfile/SmallFile.yaml
  tests/libtest/test_elasticsearch.py
Labels: Verified, size/L

#2345 Pods check after upgrade
  ocs_ci/ocs/resources/pod.py
  tests/ecosystem/upgrade/test_resources.py
  tests/manage/z_cluster/nodes/helpers.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_proactive_IPI.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
  tests/manage/z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
Labels: Verified, size/L

#2007 Add capacity with cluster filling, entry and exit criteria
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
  tests/conftest.py
  tests/helpers.py
  tests/manage/mcg/helpers.py
  tests/manage/z_cluster/cluster_exp_helpers.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py
  tests/manage/z_cluster/pvc_ops.py
Labels: size/XXL

#2307 Fix few issues for IBM cloud execution
  conf/ocsci/ibm_cloud_upi.yaml
  conf/ocsci/live-must-gather.yaml
  ocs_ci/ocs/utils.py
  ocs_ci/ocs/version.py
  ocs_ci/utility/localstorage.py
  tests/conftest.py
Labels: Verified, size/M, team/ecosystem

#2386 Include retry mechanism for get_pending_csr
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/csr.py
Labels: size/XS

#2382 Removing the bootstrap node since new vSphere provider plugin is released
  ocs_ci/deployment/vmware.py
Labels: Verified, size/S, team/ecosystem

#2393 Fixing teardown for aborted cluster
  tests/conftest.py
Labels: Verified, size/XS, team/ecosystem

#2384 Multiarch container for fio
  tests/conftest.py
Labels: size/S

#2332 Test to verifiy PVC can be expanded more than once
  tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
Labels: Test Case, Verified, size/L, team/manage

#2349 Don't check RGW metrics on any cloud platform
  ocs_ci/ocs/constants.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
Labels: size/XS

#2381 Fixture for running couchbase workload
  tests/conftest.py
Labels: Verified, size/M, team/e2e

#2397 smallfile | Integrate Internal ElasticSearch
  tests/e2e/performance/test_small_file_workload.py
Labels: Verified, performance, size/L

#2396 Test case to create amq cluster and run open messages on it
  tests/e2e/workloads/amq/test_amq_streams.py
Labels: Verified, size/M, team/e2e

#2326 Add Support to install OCS over BM
  conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_3w.yaml
  conf/deployment/baremetal/upi_1az_rhel7_nvme_intel_3m_3w.yaml
  ocs_ci/deployment/baremetal.py
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/node.py
  tests/helpers.py
Labels: Verified, size/M

#2178 Node expansion: Skipping Vmware code
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
Labels: Test Case, Verified, size/M

#2394 Downloading terraform binary version in ocs-ci
  conf/ocp_version/ocp-4.2-config.yaml
  conf/ocp_version/ocp-4.2-ga-config.yaml
  conf/ocp_version/ocp-4.2-ga-minus1-config.yaml
  conf/ocp_version/ocp-4.3-config.yaml
  conf/ocp_version/ocp-4.3-ga-config.yaml
  conf/ocp_version/ocp-4.3-ga-minus1-config.yaml
  conf/ocp_version/ocp-4.4-config.yaml
  conf/ocp_version/ocp-4.4-ga-config.yaml
  conf/ocp_version/ocp-4.5-config.yaml
  ocs_ci/deployment/terraform.py
  ocs_ci/deployment/vmware.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/utility/utils.py
Labels: Verified, size/L, team/ecosystem

#2404 FIO| Setting dataset to 40% of total capacity
  tests/e2e/performance/test_fio_benchmark.py
Labels: performance, size/S

#2177 Upgrade logging post OCP upgrade
  ocs_ci/framework/conf/default_config.yaml
  tests/ecosystem/upgrade/test_logging_upgrade.py
Labels: Test Case, Verified, size/L, team/e2e

#1298 Added simple registry workload test from SVT project
  ocs_ci/utility/svt.py
  registry_requirement.txt
  tests/e2e/test_simple_registry_workload.py
Labels: Needs Testing, size/L, team/e2e
