Repository red-hat-storage/ocs-ci, pull requests merged in 2020-07, with the labels that each got.

#2374 Fix upgrade tests
  ocs_ci/utility/utils.py
  tests/ecosystem/upgrade/conftest.py
  tests/ecosystem/upgrade/test_noobaa.py
Labels: size/M

#2377 Align ocs-ci with OCP 4.5 ( folder structure ) for vsphere platform
  ocs_ci/deployment/terraform.py
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocp-deployment/terraform_4_5.tfvars.j2
  ocs_ci/utility/connection.py
  ocs_ci/utility/load_balancer.py
  ocs_ci/utility/templating.py
  ocs_ci/utility/utils.py
Labels: Verified, size/XL, team/ecosystem

#2313 jenkins workload tests
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/jenkins.py
  ocs_ci/ocs/ocp.py
  ocs_ci/templates/workloads/jenkins/buildconfig.yaml
  tests/e2e/workloads/jenkins/test_jenkins.py
Labels: Verified, size/L, team/e2e

#2405 performane_dashboard | Changing the platform to be more generic.
  ocs_ci/utility/performance_dashboard.py
Labels: performance, size/S

#2325 Integrate Azure platform support for testing
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/azure_utils.py
  setup.py
Labels: Verified, size/L

#2411 Enhance add osd for LSO
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/utility/localstorage.py
Labels: Verified, size/S

#2416 minor fix: postgress pods namespace
  ocs_ci/ocs/ripsaw.py
Labels: Verified, bug, size/XS, team/e2e

#2340 Fixing timeout issue in scale test
  ocs_ci/ocs/cluster.py
  tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
Labels: Needs Testing, scale, size/XS

#2407 Adding required files for OCP4.6 ( support n+1 OCP version )
  conf/ocp_version/ocp-4.6-config.yaml
  ocs_ci/repos/ocp_4_6.repo
Labels: Verified, size/M, team/ecosystem

#2334 Updating RHCOS template
  conf/ocp_version/ocp-4.5-config.yaml
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/XS, team/ecosystem

#2420 Delete mcg target and image-registry buckets during cluster teardown and aws cleanup
  ocs_ci/cleanup/aws/cleanup.py
  ocs_ci/deployment/aws.py
  ocs_ci/utility/aws.py
Labels: Verified, size/M, team/ecosystem

#2430 added function: get_node_name
  ocs_ci/ocs/node.py
Labels: Verified, size/S

#2431 Adding ocs46 config files
  conf/ocs_version/ocs-4.6.yaml
  ocs_ci/framework/main.py
Labels: Verified, size/S, team/ecosystem

#2409 Add capacity when delete pod
  ocs_ci/ocs/constants.py
  tests/manage/z_cluster/cluster_expansion/test_delete_pod.py
Labels: Verified, size/L

#2446 fix work around
  ocs_ci/ocs/ocp.py
Labels: Verified, size/XS

#2423 Skip deployment of tool box for OCP ONLY deployments
  tests/conftest.py
Labels: Verified, size/XS, team/ecosystem

#2445 Jenkins export data spreadsheet
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/jenkins.py
  tests/e2e/workloads/jenkins/test_jenkins.py
Labels: Verified, size/M

#2413 pushing the data to code speed
  ocs_ci/utility/performance_dashboard.py
Labels: size/S

#1976 Scale_library class with helper functions
  conf/ocsci/use_ocs_worker_for_scale.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/scale_lib.py
  tests/e2e/scale/test_ceph_pod_respin_in_scaled_cluster.py
  tests/helpers.py
Labels: Test Case, scale, size/XL

#2408 docs: note about latest tags of ocs dev images
  docs/deployment_without_ocs.md
Labels: documentation, size/S

#2455 add jenkins pod respin tests
  tests/e2e/workloads/jenkins/test_jenkins_pod_respin.py
Labels: Verified, size/M

#2434 Enable limits for production AWS LSO deployments
  conf/ocsci/aws_i3_local_storage.yaml
  ocs_ci/deployment/deployment.py
Labels: Verified, size/S, team/ecosystem

#2432 Enable Registry testcase to run on Proxy env
  tests/helpers.py
Labels: Verified, size/S, team/e2e

#2459 add jenkins fixture
  tests/conftest.py
Labels: Verified, size/M, team/e2e

#2470 Make collecting of the logs more error prone for internall error
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: Verified, size/S

#2458 Adaptations to 2 RGW pods
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/conftest.py
  tests/manage/mcg/helpers.py
Labels: Verified, size/M

#2474 Fix in deprecated warning for oc exec command
  ocs_ci/utility/utils.py
Labels: Verified, size/XS, team/ecosystem

#2483 Fix for allow lower instances in ocs 4.5
  ocs_ci/deployment/deployment.py
Labels: Verified, size/S, team/ecosystem

#2466 Fixing variables in template
  ocs_ci/templates/ocp-deployment/terraform_4_5.tfvars.j2
Labels: Verified, size/XS, team/ecosystem

#2441 Test Noobaa resources restart
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/resources/mcg.py
  tests/libtest/test_cluster_utils.py
  tests/manage/mcg/test_restart_noobaa_resources.py
Labels: MCG, Test Case, Verified, size/M, team/manage

#2456 Use terraform log to download terraform binary version
  ocs_ci/deployment/vmware.py
Labels: Verified, size/S, team/ecosystem

#2469 Try again collecting DB dump
  ocs_ci/ocs/utils.py
Labels: Verified, size/S

#2309 LSO VMDK installation for vSphere platform
  conf/deployment/vsphere/upi_1az_rhcos_vmfs_lso_vmdk_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_lso_vmdk_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_lso_vmdk_3m_3w.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/vmware.py
Labels: Verified, size/S, team/ecosystem

#2486 Enable add node test over Azure
  tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
Labels: size/XS

#2495 change buildconfig.yaml (jenkins)
  ocs_ci/templates/workloads/jenkins/buildconfig.yaml
  tests/e2e/workloads/jenkins/test_jenkins.py
Labels: Verified, size/XS

#2491 Check for pvc creation in monitoring NS
  ocs_ci/ocs/monitoring.py
Labels: Verified, size/S, team/ecosystem

#2497 Fix never ending noobaa db dump
  ocs_ci/ocs/utils.py
Labels: bug, size/XS, team/ecosystem

#2263 Flexy Integration and PSIBaremetal deployment:
  conf/ocsci/flexy_baremetalpsi_upi.yaml
  ocs_ci/deployment/baremetal.py
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/factory.py
  ocs_ci/deployment/flexy.py
  ocs_ci/deployment/ocp.py
  ocs_ci/framework/__init__.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/conf/flexy_default_config.yaml
  ocs_ci/framework/main.py
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/templates/ocp-deployment/ntp_chrony.yaml
  ocs_ci/utility/psiutils.py
  setup.py
Labels: Needs Testing, size/XL, team/ecosystem

#2395 AMQ fixture and testcase amq workload when spinning ceph pods
  ocs_ci/ocs/amq.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/workloads/amq/amq_simple_workload.yaml
  tests/conftest.py
  tests/e2e/workloads/amq/test_amq_pod_respin.py
Labels: Verified, size/L, team/e2e

#2425 Test monitoring backed by OCS after ocp upgrade
  tests/ecosystem/upgrade/test_monitoring_after_ocp_upgrade.py
Labels: Verified, size/M, team/e2e

#2451 Fix lso operator channel
  ocs_ci/ocs/constants.py
  ocs_ci/utility/localstorage.py
Labels: Verified, size/XS

#2379 Move Noobaa max endpoint change to deploy_ocs() and change the minimum to be 2 as a default for clusters that meet the min requirements
  conf/ocsci/noobaa_endpoints_2.yaml
  conf/ocsci/noobaa_endpoints_scale.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/utility/utils.py
  tests/conftest.py
  tests/ecosystem/deployment/test_deployment.py
Labels: Verified, size/L

#2506 Make default registry svc to 4.5
  conf/ocsci/flexy_baremetalpsi_upi.yaml
Labels: size/XS

#2503 Fix db dump collection
  ocs_ci/ocs/utils.py
Labels: Verified, bug, size/XS, team/ecosystem

#2426 Changes for test disk failures to support on Azure platform
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/azure_utils.py
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: platforms, size/L

#2484 Improved report portal tagging
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Needs Testing, size/L, team/ecosystem

#2443 Adding functionality to ElasticSearch module
  ocs_ci/ocs/elasticsearch.py
Labels: performance, size/M

#2494 Couchbase workload with respinning ceph pods
  ocs_ci/ocs/couchbase.py
  tests/conftest.py
  tests/e2e/workloads/couchbase/test_couchbase_pod_respin.py
Labels: Verified, size/L, team/e2e

#2517 Update test test_pvc_expansion to check pod status before running IO
  tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
Labels: Verified, size/XS, team/manage

#2520 Wait for Noobaa health instead of calling it once
  ocs_ci/ocs/cluster.py
Labels: Verified, size/XS

#2522 Added doc around report portal tags
  docs/results.md
Labels: size/M, team/ecosystem

#2529 Fix return code mismatch for unit tests running on OSX
  ocs_ci/utility/tests/test_utils.py
Labels: Verified, size/XS, team/ecosystem

#2514 Use OCP 4.4 stable channel for GA version
  conf/ocp_version/ocp-4.4-ga-config.yaml
Labels: size/XS, team/ecosystem

#2513 Couchbase workload with node reboot and node drain
  ocs_ci/ocs/couchbase.py
  tests/e2e/workloads/couchbase/test_couchbase_node_drain.py
  tests/e2e/workloads/couchbase/test_couchbase_node_reboot.py
Labels: Verified, size/L, team/e2e

#2508 ripsaw | Getting the UUID of a test
  ocs_ci/ocs/ripsaw.py
Labels: Verified, performance, size/S

#2500 Increase wait time for fio setup in test case
  tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
Labels: Verified, size/XS, team/manage

#2537 Added wait_for_delete() for namespace post deletion of namespace
  ocs_ci/ocs/pillowfight.py
Labels: Verified, size/XS, team/e2e

#2501 Updating RHCOS 4.5 template
  conf/ocp_version/ocp-4.5-config.yaml
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/XS, team/ecosystem

#2533 W/A for bug 1857802 - only 1 RGW pod post upgrade to 4.5
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S

#2526 Cluster load: Mute Prometheus query logs for logging cluster metrics in the test background + few minor fixes in ClusterLoad
  ocs_ci/ocs/cluster_load.py
  ocs_ci/utility/prometheus.py
  tests/conftest.py
Labels: Verified, size/L

#2521 Fix for clock mon skew detected
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/load_balancer.py
  ocs_ci/utility/utils.py
  ocs_ci/utility/vsphere_nodes.py
Labels: Verified, size/L, team/ecosystem

#2541 Prevent test failure if can not push results to performance dashboard
  ocs_ci/utility/performance_dashboard.py
Labels: Verified, performance, size/S

#2429 Test to check ceph values on the cluster with the default values
  tests/manage/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/M

#2543 Improved AWS cred-req flow, create cred-reqs only for tests that require them
  ocs_ci/ocs/resources/mcg.py
  tests/conftest.py
  tests/manage/mcg/test_multi_region.py
Labels: MCG, Verified, size/L

#2557 Remove pg autoscale workaround
  ocs_ci/deployment/deployment.py
Labels: High Priority, Verified, size/S, team/ecosystem

#2510 Add Jenkins Drain node tests
  ocs_ci/ocs/jenkins.py
  tests/e2e/workloads/jenkins/test_jenkins_node_drain.py
Labels: Verified, size/L

#2518 Disable tests that generate IOs during upgrade
  tests/ecosystem/upgrade/test_resources.py
Labels: Verified, size/XS

#2410 Export all amq workload run outputs to google spreadsheet
  ocs_ci/ocs/amq.py
  tests/e2e/workloads/amq/test_amq_streamer_creation.py
Labels: Verified, size/M, team/e2e

#2419 Test case:Verify PVC expansion during rook-ceph, csi pod re-spin
  tests/manage/pv_services/conftest.py
  tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Labels: Test Case, Verified, size/L, team/manage

#2562 Use metadata.json to set cluster_name in config if one is not provided
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: Verified, size/S, team/ecosystem

#2561 Delete apps record set before destroying security group stack for AWS UPI teardown
  ocs_ci/cleanup/aws/cleanup.py
  ocs_ci/deployment/aws.py
  ocs_ci/utility/aws.py
Labels: Verified, size/M, team/ecosystem

#2453 Tier4a ocs upgrade
  ocs_ci/ocs/disruptive_operations.py
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/resources/pod.py
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, size/L

#2566 Add back post_uprade marker to test_storage_pods_running that was removed in PR 2518
  tests/ecosystem/upgrade/test_resources.py
Labels: size/XS

#2548 consider cluster wide proxy configuration in tests
  ocs_ci/ocs/constants.py
  tests/helpers.py
Labels: Verified, size/M, team/ecosystem

#2509 test_pvc_creation_measurement_performance improvement
  tests/e2e/performance/test_pvc_creation_performance.py
Labels: Verified, size/M

#2461 setup ceph client when cluster is in independent mode
  ocs_ci/framework/__init__.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/utils.py
  ocs_ci/templates/ocs-deployment/toolbox_pod.yaml
Labels: Verified, size/S

#2577 Add bugzilla marker in test cases - bug 1860891
  tests/manage/pv_services/test_pvc_disruptive.py
  tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: Verified, size/S, team/manage

#2576 Configure Chrony for vsphere platform
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/utility/utils.py
Labels: Verified, size/M, team/ecosystem

#2579 Refine dataclasses dependency
  setup.py
Labels: size/XS

#2539 FIO re-factoring for indexing output in ES
  ocs_ci/ocs/perfresult.py
  ocs_ci/ocs/version.py
  ocs_ci/templates/workloads/fio/benchmark_fio.yaml
  tests/e2e/performance/test_fio_benchmark.py
Labels: Verified, performance, size/L

#2583 Fix parsing version from stable tag
  ocs_ci/utility/utils.py
Labels: Verified, size/XS, team/ecosystem

#2578 Changed a few warning level log messages to info
  ocs_ci/utility/aws.py
Labels: size/XS, team/ecosystem

#2588 proxy config: configure also no_proxy env variable
  tests/helpers.py
Labels: size/S, team/ecosystem

#2597 Fix issue #2592
  ocs_ci/ocs/version.py
  tests/e2e/performance/test_fio_benchmark.py
Labels: size/XS

#2414 Added support to run test over GCP
  conf/deployment/gcp/ipi_1az_rhcos_3m_3w.yaml
  ocs_ci/deployment/factory.py
  ocs_ci/deployment/gcp.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
Labels: platforms, size/S

#2511 Testcases to reboot/shutdown and recovery node when amq workload is running
  ocs_ci/ocs/amq.py
  tests/conftest.py
  tests/e2e/workloads/amq/test_amq_node_reboot_and_shutdown.py
  tests/e2e/workloads/amq/test_amq_pod_respin.py
  tests/e2e/workloads/amq/test_amq_streams.py
Labels: Verified, size/L, team/e2e

#2530 4.5 ga fixes
  conf/ocp_version/ocp-4.5-ga-config.yaml
  conf/ocp_version/ocp-4.5-ga-upgrade.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/utility/localstorage.py
Labels: Verified, size/M, team/ecosystem

#2569 Include hostprefix in vSphere
  ocs_ci/templates/ocp-deployment/install-config-vsphere-upi.yaml.j2
Labels: Verified, size/XS, team/ecosystem

#2611 Except boto errors when deleting cluster buckets
  ocs_ci/utility/aws.py
Labels: Verified, size/S, team/ecosystem
