Repository red-hat-storage/ocs-ci, pull requests merged in 2020-03, with the labels that each got.

#1563 adding option for user to remove disk only from VM
  ocs_ci/utility/vsphere.py
Labels: Verified, team/ecosystem

#1531 fixes: #1474
  ocs_ci/utility/deployment_openshift_logging.py
Labels: Verified, team/e2e

#1560 Update CSI_ENABLE_SNAPSHOTTER value check
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, enhancement

#1574 Fix reportportal import issue
  setup.py
Labels: Verified, size/XS, team/ecosystem

#1568 Download openshift installer before destroying clusters
  ocs_ci/cleanup/aws/cleanup.py
Labels: size/XS, team/ecosystem

#1577 Fix the get_az_count() function to default to 3.
  ocs_ci/utility/utils.py
Labels: size/XS

#1576 fix aws-cleanup TypeError
  ocs_ci/cleanup/aws/cleanup.py
Labels: size/XS, team/ecosystem

#1566 Function to validate pg_balancer is enabled or not
  ocs_ci/ocs/cluster.py
Labels: Verified, size/M, team/e2e

#1546 Modify dc_pod_factory fixture in tests/conftest.py
  tests/conftest.py
Labels: Verified

#1564 Enhance create_pods_parallel function with node_selector param
  tests/helpers.py
Labels: Verified, team/e2e

#1565 Updated create_pod function for nginx pod raw_block support
  tests/helpers.py
Labels: Verified, size/XS, team/e2e

#1532 Collect metrics marker
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/utils.py
  pytest.ini
  tests/manage/monitoring/prometheus/test_capacity.py
Labels: enhancement

#1586 Added new function to get node resource utilization from 'oc describe node'
  ocs_ci/ocs/node.py
Labels: Verified, size/M, team/e2e

#1534 Add ability to read in access token for quay private repo authentication
  docs/getting_started.md
  ocs_ci/utility/utils.py
Labels: Verified, size/L, team/ecosystem

#1479 Fixed PGSQL Master node drain
  tests/e2e/test_pgsql_node_drain.py
Labels: Verified, team/e2e

#1584 Adding option to skip downloading openshit-client
  ocs_ci/utility/utils.py
Labels: Verified, size/XS, team/ecosystem

#1503 build ocp repo names dynamically
  ocs_ci/deployment/install_ocp_on_rhel.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem

#1571 Fix monitor of Ceph health
  ocs_ci/ocs/cluster.py
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, size/L, team/ecosystem

#1600 VDBench: adding new node for app pod
  tests/e2e/performance/test_vdbench_workload.py
Labels: size/M, team/e2e

#1602 Add capacity final
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Labels: size/L

#1552 Add fio_storageutilization_min_mbps option
  conf/deployment/vsphere/upi_1az_rhcos_3m_3w_prod_memory.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vmfs_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_3m_3w_prod_memory.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_3m_3w.yaml
  conf/ocsci/vsphere-upi-ocs4qe-lab.yaml
  conf/ocsci/vsphere_upi.yaml
  ocs_ci/framework/conf/default_config.yaml
  tests/conftest.py
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/test_workload_fixture.py
Labels: Verified, size/L

#1598 Fix a leftover from openshift-monitoring namespace
  ocs_ci/ocs/constants.py
  ocs_ci/utility/environment_check.py
Labels: Verified, size/XS

#1612 Adding retry for check_file_existence
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/XS

#1462 Scale Test case to create 1500 PVC and get PVC creation_time
  tests/e2e/test_pvc_creation_deletion_scale.py
Labels: High Priority, Test Case, Verified, team/e2e

#1616 Propagate default channel for specific version
  conf/ocs_version/ocs-4.2.yaml
  conf/ocs_version/ocs-4.3.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, size/M

#1610 Move workaround for RHEL nodes to different place to enable must-gather
  ocs_ci/deployment/deployment.py
  tests/conftest.py
Labels: Verified, size/M, workaround

#1622 Fix default latest tag for must gather default value
  ocs_ci/framework/conf/default_config.yaml
Labels: size/XS, team/ecosystem

#1611 improving logging in run_cmd()
  ocs_ci/utility/tests/test_utils.py
  ocs_ci/utility/utils.py
Labels: size/L

#1592 Function to terminate an aws instance
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/aws.py
Labels: Verified, size/M

#1580 Function to make node network down
  ocs_ci/ocs/node.py
Labels: Verified, enhancement, size/M

#1595 AWS cleanup enhancements
  ocs_ci/cleanup/aws/cleanup.py
  ocs_ci/cleanup/aws/defaults.py
Labels: Verified, size/L, team/ecosystem

#1627 Fix Issue #1599
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/XS, team/manage

#1626 don't include secrets from stdout into debug logs
  ocs_ci/utility/tests/test_utils.py
  ocs_ci/utility/utils.py
Labels: size/M

#1582 Enhance dc_pod_factory with node_selector param
  tests/conftest.py
Labels: Verified, size/XS

#1591 DC based app pods - Node failure helper functions
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/M

#1629 Report properly issue when channel is missing
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/packagemanifest.py
Labels: Needs Deployment Testing, size/S, team/ecosystem

#1624 test_az_failure: added skip marker
  tests/manage/z_cluster/nodes/test_az_failure.py
Labels: size/XS

#1632 Test to verify ceph block pool is not blocked by another invalid pool…
  tests/helpers.py
  tests/manage/pv_services/test_verify_new_cbp_creation_not_blocked_by_invalid_cbp.py
Labels: Test Case, Verified, size/M, team/manage

#1619 Test case to validate Multipart Upload on buckets
  ocs_ci/ocs/resources/mcg.py
  tests/helpers.py
  tests/manage/mcg/helpers.py
  tests/manage/mcg/test_multipart_upload.py
Labels: Test Case, Verified, size/L, team/manage

#1617 PR to move e2e test cases to respective directories.
  tests/e2e/scale/test_pvc_creation_deletion_scale.py
  tests/e2e/workloads/test_pgsql_node_drain.py
Labels: team/e2e

#1618 Fix test_automated_recovery_from_failed_nodes_proactive_IPI test failure by adding WA
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_proactive_IPI.py
Labels: Verified, size/S, team/manage, workaround

#1585 Filter tests from report if its skipped because of ocs version mismatch
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/framework/testlib.py
  ocs_ci/utility/utils.py
  pytest.ini
  tests/conftest.py
Labels: Verified, size/M, team/ecosystem

#1637 Fixes #1636: Add Capacity: Increase cluster health timeout
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Labels: Verified, size/S

#1588 fio: use a more reasonable IO rate of 1m instead of 16k
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/XS

#1641 Fix OCP GA versions
  conf/ocsci/ocp-4.2-ga-config.yaml
  conf/ocsci/ocp-4.3-ga-config.yaml
Labels: size/XS, team/ecosystem

#1625 Delete folder from templates as post-check
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/vsphere.py
Labels: Verified, size/M, team/ecosystem

#1647 Set pytest to version 5.3.5 because 5.4.0 is breaking unit tests
  setup.py
Labels: High Priority, size/XS, team/ecosystem

#1645 Require kubernetes 10.0.1 to satisfy latest openshift package requirement
  setup.py
Labels: High Priority, size/XS, team/ecosystem

#1635 Fix environment check to exclude specified namespaces and labels
  ocs_ci/utility/environment_check.py
Labels: High Priority, Verified, size/XS

#1653 Take OCS version from registry image if passed
  docs/usage.md
  ocs_ci/framework/main.py
  ocs_ci/utility/utils.py
Labels: Needs Deployment Testing, size/M, team/ecosystem

#1658 Increase drain_nodes timeout to 1200 seconds
  ocs_ci/ocs/node.py
Labels: size/XS

#1593 Fixes: #1594 - Enable FIPS
  conf/ocsci/fips.yaml
  ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2
Labels: Verified, size/XS

#1660 Add --osd-size parameter
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: Verified, team/ecosystem

#1655 Allow upgrade to change channel
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/main.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/utility/utils.py
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, size/L, team/ecosystem

#1651 Move smallfile workload tests into performance tier
  tests/e2e/performance/test_small_file_workload.py
Labels: Skip test, size/XS

#1558 Moving deployment of logging to conftest.py
  ocs_ci/utility/deployment_openshift_logging.py
  tests/conftest.py
  tests/e2e/logging/test_openshift-logging.py
Labels: Needs Testing, enhancement, team/e2e

#1662 Add --ocp-version CLI param
  conf/ocp_version/ocp-4.2-config.yaml
  conf/ocp_version/ocp-4.2-ga-config.yaml
  conf/ocp_version/ocp-4.2-ga-minus1-config.yaml
  conf/ocp_version/ocp-4.3-config.yaml
  conf/ocp_version/ocp-4.3-ga-config.yaml
  conf/ocp_version/ocp-4.3-ga-minus1-config.yaml
  conf/ocp_version/ocp-4.4-config.yaml
  docs/usage.md
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/utils.py
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, size/L, team/ecosystem

#1665 Update test test_pvc_delete_and_verify_size_is_returned_to_backend_pool
  tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Labels: Verified, size/S

#1668 Add check of OCS version is correct in the CSV
  ocs_ci/ocs/resources/storage_cluster.py
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, size/M, team/ecosystem

#1670 Extract proper OCP version from semantic_version
  ocs_ci/utility/utils.py
Labels: Verified, size/XS, team/ecosystem

#1311 Noobaa upgrade check
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/mcg_bucket.py
  tests/conftest.py
  tests/ecosystem/upgrade/test_noobaa.py
  tests/manage/mcg/conftest.py
  tests/manage/mcg/test_multi_region.py
Labels: Test Case, Verified, team/ecosystem

#1682 Add bugzilla marker to tests which delete rook-ceph-operator
  tests/manage/pv_services/test_pvc_disruptive.py
  tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: Verified, size/M, team/manage

#1678 Adding retry and validating nodes is in ready state
  ocs_ci/ocs/monitoring.py
  tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
Labels: Verified, size/S

#1683 Allow pre-commit check-yaml to allow multi-document yaml files
  .pre-commit-config.yaml
Labels: Verified, size/XS, team/ecosystem

#1694 Fixes Issue 1693: Add timeout of 90 sec for disruptive PVC creation tests
  tests/conftest.py
  tests/manage/pv_services/test_pvc_disruptive.py
Labels: Verified, size/XS, team/manage

#1677 Test implementation of S3 Bucket Policy
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/bucket_policy.py
  ocs_ci/ocs/resources/mcg.py
  tests/manage/mcg/helpers.py
  tests/manage/mcg/test_bucket_policy.py
  tests/manage/mcg/test_multipart_upload.py
Labels: Test Case, Verified, size/XL, team/manage

#1690 Increase timeout for monitor to come back
  tests/manage/monitoring/conftest.py
Labels: Verified, size/XS

#1697 Enable FIPS in vsphere
  ocs_ci/templates/ocp-deployment/install-config-aws-upi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-vsphere-upi.yaml.j2
Labels: Verified, size/XS

#1491 OCP upgrade - BZ1788930
  conf/ocp_version/ocp-4.3-ga-upgrade.yaml
  conf/ocp_version/ocp-4.3-upgrade.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/ocp.py
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Needs Testing, team/manage

#1703 Remove kubernetes package from requirements
  setup.py
Labels: Verified, size/XS, team/ecosystem

#1705 Add OCP ugprade related markers
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/constants.py
  pytest.ini
  tests/ecosystem/upgrade/test_upgrade.py
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Verified, size/M

#1719 Fix upgrade test to apply changes in subscription
  conf/upgrade/upgrade_in_current_source.yaml
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, size/M, team/ecosystem

#1710 Log Ceph status in case drain command times out
  ocs_ci/ocs/node.py
Labels: Verified, size/S

#1720 Installs Logging according to OCP version on the cluster
  conf/ocs_version/ocs-4.2.yaml
  conf/ocs_version/ocs-4.3.yaml
  ocs_ci/framework/conf/default_config.yaml
  tests/conftest.py
Labels: Verified, size/S, team/e2e

#1699 Test to verify must_gather_commands
  ocs_ci/ocs/constants.py
  tests/manage/z_cluster/test_must_gather.py
Labels: Verified, size/M, team/manage

#1701 fix test: test_upgrade_ocp
  ocs_ci/ocs/ocp.py
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Verified, size/S

#1707 Set registry to managed state after OCP deployment
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/registry.py
Labels: Verified, size/M, team/ecosystem

#1713 Add config for OCS 4.4
  conf/ocs_version/ocs-4.4.yaml
Labels: size/S

#1715 Use get_cluster_name instead of ocp_deployment object
  ocs_ci/deployment/aws.py
Labels: Verified, size/XS, team/ecosystem

#1607 Node replacement - Reactive(IPI)
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
Labels: Test Case, Verified, size/L, team/manage

#1596 KNIP-894: Replacement of nodes Proactive
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Verified, size/L, team/manage

#1727 Fix get_all_pods function
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/XS, team/ecosystem

#1725 Update test_reclaim_policy to verify PV deletion
  tests/manage/pv_services/test_reclaim_policy.py
Labels: Test Case, Verified, size/S, team/manage

#1722 Bucket policy - OBC initialization fix
  ocs_ci/ocs/resources/bucket_policy.py
Labels: Verified, bug, size/S

#1691 environment_check ignores all OCP ns but OCS one
  ocs_ci/utility/environment_check.py
Labels: Verified, size/M

#1730 Wait longer time in case of upgrade for HEALTH_OK
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/utility/utils.py
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, size/M, team/ecosystem

#1605 Automatic recovery from failed nodes - Reactive(IPI)
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: Test Case, Verified, size/L, team/manage

#1738 Bucket policy - Adding skip for if OCS <4.3
  tests/manage/mcg/test_bucket_policy.py
Labels: Verified, bug, size/XS

#1737 Fix MCG multi-region test
  tests/manage/mcg/test_multi_region.py
Labels: bug, size/XS, team/manage

#1698 Adding get_ceph_capacity function
  ocs_ci/ocs/cluster.py
Labels: size/S

#1740 BZ 1818613 decorator to TestNodesMaintenance
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/XS

#1717 Temporarily skip tests that utilize datasets that are too big
  tests/manage/mcg/test_object_integrity.py
  tests/manage/mcg/test_write_to_bucket.py
Labels: Verified, size/M

#1739 Fix #1687
  tests/manage/z_cluster/test_must_gather.py
Labels: Verified, size/XS

#1741 Improve logging in tests
  ocs_ci/ocs/resources/pod.py
  tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py
  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_and_io.py
  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_deletion_and_io.py
  tests/manage/pv_services/test_pvc_disruptive.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: Verified, size/S, team/manage

#1749 Ignore leftovers post OCP upgrade
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Verified, size/XS

#1704 Support deployments using LSO for AWS IPI on i3 instance types
  conf/ocsci/aws_i3_local_storage.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocs-deployment/local-storage-operator.yaml
  ocs_ci/templates/ocs-deployment/local-volume.yaml
  ocs_ci/utility/templating.py
Labels: Verified, size/L, team/ecosystem

#1736 Fix upgrade in stage
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, size/M

#1734 Fixes: #1716 aws-cleanup, ci-cleanup: Allow deletion of UPI clusters
  ocs_ci/cleanup/aws/cleanup.py
  ocs_ci/cleanup/aws/defaults.py
  ocs_ci/deployment/aws.py
  ocs_ci/deployment/ocp.py
  ocs_ci/utility/aws.py
  ocs_ci/utility/utils.py
Labels: Verified, size/XL

#1757 AWS UPI needs more than 600 seconds as seen in one of the jenkins job…
  ocs_ci/utility/utils.py
Labels: size/XS
