Repository red-hat-storage/ocs-ci, pull requests merged in 2020-11, with the labels that each got.

#3152 Adding pvc_multi_snapshot_performance test
  ocs_ci/ocs/constants.py
  tests/e2e/performance/test_multi_snapshots.py
  tests/e2e/performance/test_pvc_multi_snapshot_performance.py
Labels: Verified, performance, scale, size/XL

#2964 Extend MCG node drain cluster health check tries + reduce load
  ocs_ci/ocs/resources/mcg.py
  tests/conftest.py
  tests/manage/mcg/test_mcg_resources_disruptions.py
Labels: MCG, Verified, size/M

#3236 Fix for get csv neme from install plan
  ocs_ci/ocs/resources/packagemanifest.py
Labels: Verified, bug, size/S, team/ecosystem, upgrade

#3089 Implement Azure, GCP and IBM COS in CloudManager
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/backingstore.py
  ocs_ci/ocs/resources/cloud_manager.py
  ocs_ci/ocs/resources/cloud_uls.py
  ocs_ci/templates/mcg/BackingStore.yaml
  ocs_ci/templates/mcg/BackingStoreSecret.yaml
  setup.py
  tests/conftest.py
  tests/manage/mcg/test_multi_region.py
Labels: MCG, Verified, size/XL

#3245 increase the timeout for collection must-gather on OCS4.6
  conf/ocsci/scale.yaml
  ocs_ci/ocs/utils.py
Labels: Verified, size/XS

#3174 Verify VolumeSnapshotContent is deleted in testcase and fixture finalizer
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  tests/conftest.py
  tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
Labels: Verified, size/M, team/manage

#3253 Add OCS uninstall to cluster teardown
  ocs_ci/deployment/deployment.py
Labels: Verified, size/XS

#3244 Skip PVC clone test cases if OCP version is below 4.6
  tests/manage/pv_services/pvc_clone/test_clone_when_pvc_full.py
  tests/manage/pv_services/pvc_clone/test_clone_with_different_access_mode.py
  tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py
Labels: Verified, size/XS

#3243 Skip snapshot tests if OCP version is below 4.6
  tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py
  tests/manage/pv_services/pvc_snapshot/test_rbd_block_pvc_snapshot.py
  tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
Labels: Verified, size/S

#3257 Change awscli pod to random naming and fix awscli_pod_session teardown issue
  ocs_ci/templates/mcg/aws-cli-service-ca-configmap.yaml
  tests/conftest.py
  tests/manage/mcg/test_write_to_bucket.py
Labels: MCG, Verified, size/M

#3261 Raise an exception for get packagemanifest function
  ocs_ci/ocs/resources/packagemanifest.py
Labels: Verified, size/XS, team/ecosystem

#3247 Retry fetching Noobaa endpoint pods data in case of KeyError
  tests/conftest.py
Labels: Verified, size/XS

#3266 Remove skipping logging TCs on OCP 4.6 & skip for next non-GAed version
  tests/e2e/logging/test_openshift-logging.py
Labels: Verified, size/XS, team/e2e

#3116 NooBaa endpoint autoscale tests
  tests/manage/mcg/test_endpoint_autoscale.py
Labels: size/M

#3264 Allow only pausing and only resuming cluster load
  tests/conftest.py
  tests/ecosystem/upgrade/test_resources.py
  tests/ecosystem/upgrade/test_upgrade_ocp.py
  tests/manage/mcg/test_mcg_resources_disruptions.py
  tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/M

#3193 Fail node hosting RGW pods
  tests/manage/rgw/test_host_node_failure.py
Labels: Test Case, Verified, size/L

#3267 Update default template to latest
  ocs_ci/framework/conf/default_config.yaml
Labels: size/XS, team/ecosystem

#3251 Run IO on cloned PVC pod
  tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py
Labels: Verified, size/XS, team/manage

#3275 Fix unistall issue with logger of Exception
  ocs_ci/deployment/deployment.py
Labels: High Priority, bug, size/XS, team/ecosystem

#3271 Fix indention problem for OCP install config templates
  ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-aws-upi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-azure-ipi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-gcp-ipi.yaml.j2
Labels: Verified, bug, size/M, team/ecosystem

#3221 Add annotations to show ocs disk status on UI for LSO cluster
  ocs_ci/deployment/deployment.py
Labels: Verified, size/XS

#3277 Manually fix files that black could not automatically reformat
  ocs_ci/utility/lvm_utils.py
  tests/manage/mcg/test_object_integrity.py
  tests/manage/pv_services/test_pvc_rwx_writeable_after_pod_deletions.py
Labels: size/L, team/ecosystem

#3250 Run IO after restoring the PVC
  tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py
Labels: Verified, size/S, team/manage

#3280 Code review doc addition
  docs/code_review.md
Labels: documentation, size/XS, team/ecosystem

#3168 Testcase: Multiple clones of PGSQL Workloads PVCs
  ocs_ci/ocs/pgsql.py
  tests/conftest.py
  tests/e2e/lifecycle/pvc_clone/test_pgsql_pvc_clone.py
Labels: Test Case, Verified, size/L, team/e2e

#3163 Create new rbd storage class on a new rbd pool with replica and compression options
  ocs_ci/helpers/helpers.py
  ocs_ci/templates/ocs-deployment/cephblockpool.yaml
  tests/conftest.py
  tests/manage/storageclass/test_new_sc_rbd_replica2_3.py
Labels: Verified, new feature, size/L

#3254 Add nodes manually for vSphere platform
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/node.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/vsphere.py
  ocs_ci/utility/vsphere_nodes.py
Labels: Verified, size/L, team/ecosystem

#3288 Adding RHCOS OCP 4.6 GAed template
  conf/ocp_version/ocp-4.6-ga-config.yaml
Labels: size/XS, team/ecosystem

#3064 MCG namespace tests - tier4
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/objectbucket.py
  tests/conftest.py
  tests/manage/mcg/test_namespace.py
Labels: MCG, Verified, size/L

#3268 reboot external rhcs nodes
  ocs_ci/ocs/external_ceph.py
  ocs_ci/ocs/utils.py
Labels: Verified, size/M, team/ecosystem

#3223 Flowtest - mcg namespace disprution flow
  ocs_ci/ocs/bucket_utils.py
  tests/e2e/flowtest/mcg/test_mcg_namespace_disruptions.py
Labels: Test Case, Verified, size/L, team/e2e

#3276 Add options for FIO profile to generate S3 load for noobaa autoscale
  ocs_ci/ocs/fio_artefacts.py
  tests/manage/mcg/test_endpoint_autoscale.py
Labels: size/S

#3279 Name ocs subscription the same like done by UI
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocs-deployment/subscription.yaml
Labels: Verified, size/XS, team/ecosystem

#3246 Use api key in Prometheus API communication on IBM Cloud
  ocs_ci/ocs/ocp.py
  ocs_ci/utility/prometheus.py
Labels: Verified, size/M

#3305 Add namespace bucket test for azure
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/mcg.py
  tests/conftest.py
  tests/manage/mcg/test_namespace.py
Labels: MCG, Verified, size/L

#3308 Use namespace from config for LSO deployment
  ocs_ci/deployment/deployment.py
Labels: Verified, size/S, team/ecosystem

#3310 Increase timeout for upgrade for BZ: 1895402
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, size/S

#3314 Black formatting preparation
  .pre-commit-config.yaml
  docs/conf.py
  docs/python-examples/fixtures/test_fixtures.py
  ocs_ci/ocs/pod_exec.py
  tests/manage/monitoring/test_workload_example.py
  tests/manage/monitoring/test_workload_with_distruptions.py
  tox.ini
Labels: size/M, team/ecosystem

#3317 dev workflow updates for black
  .git-blame-ignore-revs
  .pre-commit-config.yaml
  .travis.yml
  requirements-dev.txt
  tox.ini
Labels: High Priority, team/ecosystem

#3311 fix squad analysis skipped_message issue
  ocs_ci/utility/utils.py
Labels: Verified, size/S, team/ecosystem

#3043 use pytest-reportportal with backport and add unit test
  ocs_ci/framework/tests/order/a/test_a.py
  ocs_ci/framework/tests/order/e/test_e.py
  ocs_ci/framework/tests/order/z/test_z.py
  requirements-dev.txt
  requirements-docs.txt
  requirements.txt
  setup.py
Labels: Verified, size/L

#3332 pull nginx image from quay.io instead of docker to avoid rate limit issue
  ocs_ci/templates/CSI/cephfs/pod.yaml
  ocs_ci/templates/CSI/rbd/pod.yaml
  ocs_ci/templates/app-pods/nginx.yaml
  ocs_ci/templates/app-pods/raw_block_pod.yaml
Labels: Verified, size/XS

#3300 Increase node drain command timeout in TestNodesMaintenance
  ocs_ci/ocs/node.py
Labels: Verified, size/XS

#3177 Test worker node restart during PVC clone
  tests/manage/pv_services/pvc_clone/test_node_restart_during_pvc_clone.py
Labels: Test Case, Verified, size/L, team/manage

#3322 Move OCP and OCS version config directories under the framework conf dir
  ocs_ci/framework/conf/ocp_version/README.md
  ocs_ci/framework/conf/ocp_version/ocp-4.2-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.2-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.2-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.3-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.3-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.3-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.3-ga-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.3-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.4-candidate-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.4-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.4-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.4-ga-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.4-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.5-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.5-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.5-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.5-ga-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.5-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.6-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.6-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.6-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.6-ga-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.6-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.7-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.7-upgrade.yaml
  ocs_ci/framework/conf/ocs_version/README.md
  ocs_ci/framework/conf/ocs_version/ocs-4.2.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.3.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.4.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.5.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.6.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.7.yaml
  ocs_ci/framework/main.py
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem

#3331 updated codespeed
  tests/e2e/performance/test_pvc_creation_performance.py
  tests/e2e/performance/test_pvc_deletion_performance.py
Labels: size/XS

#3298 Changing network_adapter parameter
  ocs_ci/ocs/platform_nodes.py
Labels: size/XS, team/ecosystem

#3293 Test to verify PVC clone when rook-ceph, csi pods are deleted
  tests/conftest.py
  tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py
Labels: Test Case, Verified, size/L, team/manage

#2633 bucketclass functionality and pv-pool test cases
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/backingstore.py
  ocs_ci/ocs/resources/bucketclass.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/objectbucket.py
  ocs_ci/ocs/resources/pod.py
  tests/conftest.py
  tests/manage/mcg/test_bucket_creation.py
  tests/manage/mcg/test_bucket_deletion.py
  tests/manage/mcg/test_pv_pool.py
Labels: MCG, Verified, size/XL

#3284 Assign lifecycle and flowtest to Magenta squad
  ocs_ci/ocs/constants.py
Labels: size/XS

#3249 Function to check compression and replication
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/exceptions.py
  tests/manage/storageclass/test_new_sc_rbd_replica2_3.py
Labels: Verified, size/L

#3348 Configuration creation for IPI 3AZ RHCOS 3M 6W
  conf/deployment/aws/ipi_3az_rhcos_3m_6w.yaml
Labels: Verified, size/S

#3289 Tests to verify PVC snapshot restore with access mode different than parent PVC
  tests/manage/pv_services/pvc_snapshot/test_snapshot_restore_with_different_access_mode.py
Labels: Test Case, Verified, size/L, team/manage

#3151 Test resource deletion during snapshot and restore
  ocs_ci/helpers/disruption_helpers.py
  ocs_ci/ocs/resources/pod.py
  tests/conftest.py
  tests/manage/pv_services/pvc_snapshot/test_resource_deletion_during_snapshot_restore.py
  tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
Labels: Test Case, Verified, size/L, team/manage

#3359 Use Repo link from mirror.openshift.com instead of internal link
  ocs_ci/repos/ocp_4_6.repo
Labels: Verified, size/XS

#3351 Improve Health Check
  ocs_ci/utility/utils.py
Labels: Verified, size/XS

#3365 Add Polarion Id for BM config file
  conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_3w.yaml
  conf/deployment/baremetal/upi_1az_rhel7_nvme_intel_3m_3w.yaml
Labels: size/XS

#3366 CI reportportal gaps
  ocs_ci/framework/pytest_customization/ocscilib.py
  pytest.ini
  tests/conftest.py
Labels: Verified, size/M

#3330 Test case for mcg namespace supported S3 operations
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/resources/mcg.py
  tests/conftest.py
  tests/e2e/lifecycle/mcg/test_mcg_namespace_s3_ops.py
Labels: Test Case, Verified, size/XL, team/e2e, team/manage

#3334 Add a test to a pvc image with a huge number of files
  tests/e2e/performance/test_pvc_snapshot_performance.py
Labels: Verified, performance, size/L

#3380 Changing the location of the ocs upgrade to the newer location
  ocs_ci/ocs/ocs_upgrade.py
Labels: size/XS

#3215 Wait for PV to delete in finalizer of snapshot_restore_factory and pvc_clone_factory
  ocs_ci/helpers/helpers.py
  tests/conftest.py
Labels: Verified, size/M

#3353 Namespace bucket tests that use RGW
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/cloud_manager.py
  ocs_ci/ocs/resources/cloud_uls.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/rgw.py
  tests/conftest.py
  tests/manage/mcg/test_namespace.py
Labels: Verified, size/L

#3386 Rename Ripsaw repo
  ocs_ci/ocs/ripsaw.py
Labels: Verified, performance, size/XS

#3369 use fedora and postgres images from quay.io to avoid docker rate limits
  ocs_ci/templates/app-pods/fedora_dc.yaml
  ocs_ci/templates/workloads/pgsql/server/StatefulSet.yaml
Labels: Verified, size/XS

#3346 Rewriting OCS destroy on IBM Power
  ocs_ci/deployment/ibm.py
  ocs_ci/ocs/ocp.py
Labels: size/L

#3344 Introducing github actions to ocs-ci
  .github/workflows/pr_checks.yml
  tox.ini
Labels: size/M, team/ecosystem

#3392 changing info to debug in deployment
  ocs_ci/deployment/deployment.py
Labels: size/XS, team/ecosystem

#3216 Add infra nodes to ocp cluster - AWSIPI
  conf/deployment/aws/ipi_3az_rhcos_3m_3w_3i.yaml
  conf/ocsci/infra_nodes.yaml
  ocs_ci/deployment/aws.py
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/scale_lib.py
  ocs_ci/ocs/scale_pgsql.py
Labels: Verified, size/L, team/ecosystem

#3354 Fix function name to use simple form
  ocs_ci/deployment/baremetal.py
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/disruptive_operations.py
  ocs_ci/ocs/flowtest.py
  ocs_ci/ocs/jenkins.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/scale_lib.py
  ocs_ci/ocs/version.py
  ocs_ci/utility/localstorage.py
  ocs_ci/utility/performance_dashboard.py
  ocs_ci/utility/utils.py
  tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
  tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
  tests/e2e/workloads/amq/test_amq_node_reboot_and_shutdown.py
  tests/e2e/workloads/couchbase/test_couchbase_node_drain.py
  tests/e2e/workloads/couchbase/test_couchbase_node_reboot.py
  tests/e2e/workloads/pgsql/test_pgsql_node_drain.py
  tests/manage/pv_services/pvc_clone/test_node_restart_during_pvc_clone.py
  tests/manage/pv_services/pvc_resize/test_node_restart_during_pvc_expansion.py
  tests/manage/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/L

#3349 Test to verify snapshot restore using a SC different than that of parent
  tests/conftest.py
  tests/manage/pv_services/pvc_snapshot/test_restore_snapshot_using_different_sc.py
Labels: Test Case, Verified, size/L, team/manage

#3387 Fix TypeError when calling wait_for_storage_pods
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/XS

#3394 fix issue 3393 and split ns_resource_factory
  tests/conftest.py
Labels: High Priority, MCG, Verified, bug, size/M

#3333 Adding new implementation for multiple clone performance test
  tests/e2e/performance/test_pvc_multi_clone_performance.py
Labels: performance, size/L

#3391 ListObjectsv2 continuation token implementation
  tests/e2e/lifecycle/mcg/test_mcg_namespace_s3_ops.py
Labels: Verified, enhancement, size/L, team/e2e

#3382 Instantiate default cloud clients as None when no auth.yaml is found
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/cloud_manager.py
  ocs_ci/ocs/resources/cloud_uls.py
  ocs_ci/utility/utils.py
Labels: MCG, Verified, size/M

#3374 fix-3370 -- Exclude compute-o-debug pod in Validation
  tests/e2e/scale/test_pods_are_not_oomkilled_while_running_ios.py
Labels: High Priority, Needs Testing, Verified, bug, scale, size/XS

#3373 fix-3371 -- Add 5mins waittime after PVC deletion.
  ocs_ci/helpers/helpers.py
  tests/e2e/scale/test_pvc_creation_deletion_scale.py
Labels: High Priority, Needs Testing, Verified, bug, scale, size/M

#3405 updating RHCOS template for OCP4.7
  ocs_ci/framework/conf/ocp_version/ocp-4.7-config.yaml
Labels: Verified, size/XS, team/ecosystem

#3327 Add multicloud backingstore tests
  ocs_ci/ocs/resources/backingstore.py
  tests/manage/mcg/test_multicloud.py
Labels: MCG, Verified, size/L

#3109 Add must_gather class
  ocs_ci/ocs/must_gather/__init__.py
  ocs_ci/ocs/must_gather/const_must_gather.py
  ocs_ci/ocs/must_gather/must_gather.py
  tests/manage/z_cluster/test_must_gather.py
Labels: Verified, size/XL

#3410 Fix for rgw_service issue in external mode env
  ocs_ci/ocs/constants.py
  tests/conftest.py
Labels: High Priority, MCG, Verified, bug, size/XS

#3421 Fix collection issue
  tests/manage/z_cluster/test_must_gather.py
Labels: High Priority, Verified, bug, size/XS, team/ecosystem

#3423 Revert upgrade timeout increase for 4.6
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, size/XS, team/ecosystem

#3429 Do not fail execution when RP has issues
  tests/conftest.py
Labels: Verified, enhancement, size/XS, team/ecosystem

#2792 docs: note about NooBaa test cases on cloud platforms
  docs/code_review.md
Labels: MCG, docs, size/XS

#3435 MCG: Fix for #3434
  ocs_ci/ocs/resources/rgw.py
Labels: High Priority, MCG, Verified, bug, size/XS

#3422 Instantiate all cloud clients as None by default
  ocs_ci/ocs/resources/backingstore.py
  ocs_ci/ocs/resources/cloud_manager.py
Labels: MCG, Verified, size/M

#3431 Fix-3371 - More fix to github issue
  ocs_ci/helpers/helpers.py
Labels: High Priority, Verified, bug, scale, size/XS
