Repository red-hat-storage/ocs-ci, pull requests merged in 2020-09, with the labels that each got.

#2809 Skip multipart upload test
  tests/manage/rgw/test_multipart_upload.py
Labels: Verified, size/XS

#2847 Adding latest template for ocp45
  conf/ocp_version/ocp-4.5-config.yaml
  conf/ocp_version/ocp-4.5-ga-config.yaml
  conf/ocp_version/ocp-4.5-ga-minus1-config.yaml
Labels: Verified, size/XS, team/ecosystem

#2841 Check if cluster was upgraded for RGW count validation
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/ocs.py
Labels: Verified, size/S

#2862 Set noobaa endpoints to 1 for external mode
  conf/ocsci/external_rhcs_cluster.yaml
Labels: size/XS

#2805 Upgrade polarion ids
  conf/deployment/aws/ipi_1az_rhcos_3m_3w.yaml
  conf/deployment/aws/ipi_3az_rhcos_3m_3w.yaml
  conf/deployment/aws/upi_1az_rhcos_3m_3w.yaml
  conf/deployment/aws/upi_1az_rhel7_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhcos_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhel7_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vmfs_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_3m_3w.yaml
  ocs_ci/utility/reporting.py
  tests/ecosystem/deployment/test_deployment.py
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, size/M, team/ecosystem, upgrade

#2849 Fix get rhcos template
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/utils.py
  setup.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Verified, size/M

#2845 Use Different SC in external mode for openshift-logging
  ocs_ci/utility/deployment_openshift_logging.py
Labels: Verified, size/XS, team/e2e

#2856 Update in tests/helpers.py and tests/conftest.py for getting CBP & CephFS name
  tests/conftest.py
  tests/helpers.py
Labels: Independent-cluster-mode, Verified, size/S

#2868 Add OCP 4.6 upgrade conf file
  conf/ocp_version/ocp-4.6-upgrade.yaml
Labels: Verified, size/XS

#2840 Fix mcg-cli pod issue
  ocs_ci/ocs/cluster.py
Labels: Verified, size/XS, team/ecosystem

#2709 Add functionality to deploy with infra worker nodes
  conf/ocsci/infra_worker_nodes.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
Labels: Verified, size/M

#2851 Skip PVC expansion tests if the cluster is upgraded from OCS4.4
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/utility/utils.py
  pytest.ini
  tests/conftest.py
  tests/manage/pv_services/pvc_resize/test_node_restart_during_pvc_expansion.py
  tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
  tests/manage/pv_services/pvc_resize/test_pvc_expansion_when_full.py
  tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Labels: Verified, size/M

#2874 Fixing the issue for setting the property for mcg_obj
  ocs_ci/ocs/cluster.py
Labels: size/XS

#2860 Retry AWSCLI service CA creation if already exists
  tests/conftest.py
Labels: Verified, size/S

#2870 Set a fixed PVC size for cluster load with external cluster
  ocs_ci/ocs/cluster_load.py
Labels: size/XS

#2776 Vsphere rhel installation for OCP 4.5
  ocs_ci/deployment/helpers/vsphere_helpers.py
  ocs_ci/deployment/install_ocp_on_rhel.py
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocp-deployment/cluster_info.yaml.j2
  ocs_ci/templates/ocp-deployment/inventory_haproxy.yaml.j2
  ocs_ci/templates/ocp-deployment/scale_up_config.yaml.j2
  ocs_ci/templates/ocp-deployment/scale_up_terraform_with_folder_structure.tfvars.j2
  ocs_ci/utility/utils.py
Labels: Verified, size/XL, team/ecosystem

#2762 Fips verification
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/fips.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/M

#2865 update ocp.rsync for disconnected cluster
  ocs_ci/ocs/ocp.py
Labels: Verified, size/XS, team/ecosystem

#2833 monitoring_mgr_pod_OCS-1535
  ocs_ci/ocs/monitoring.py
  tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
Labels: Verified, size/M

#2887 Update test_pvc_delete_verify_size_is_returned_to_backendpool.py to support External mode cluster
  tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Labels: Verified, size/S, team/manage

#2781 Add a check condition before deploying BM cluster
  ocs_ci/deployment/baremetal.py
  ocs_ci/ocs/constants.py
Labels: High Priority, Verified, enhancement, size/M

#2889 Setting toleration for fluentd pods
  ocs_ci/templates/openshift-infra/logging-deployment/clusterlogging_operator/instance.yaml
Labels: Verified, size/XS, team/e2e

#2871 Add conf file to taint worker nodes
  conf/ocsci/tainted_worker_nodes.yaml
Labels: Verified, size/S

#2820 Fixed Vsphere and BareMetal naming in codespeed
  ocs_ci/utility/performance_dashboard.py
Labels: Needs Testing, size/XS

#2878 pgsql scale test: Added support for VMware, Baremetal and Independent mode.
  ocs_ci/ocs/scale_pgsql.py
Labels: Needs Testing, scale, size/M

#2883 Adjustments for RGW as the default backingstore over 4.4 Azure
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/M, workaround

#2808 Update test_pvc_snapshot to use default volumesnapshotclass
  ocs_ci/ocs/constants.py
  tests/helpers.py
  tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py
Labels: Verified, size/M, team/manage

#2734 Fixing Couchbase issues
  ocs_ci/ocs/couchbase.py
  ocs_ci/ocs/pillowfight.py
  tests/e2e/workloads/couchbase/test_couchbase_node_drain.py
  tests/e2e/workloads/couchbase/test_couchbase_node_reboot.py
  tests/e2e/workloads/couchbase/test_couchbase_pod_respin.py
Labels: Verified, size/L, team/e2e

#2866 Log an error instead of raising an exception if ULS is found after deletion
  ocs_ci/ocs/resources/cloud_manager.py
Labels: MCG, Needs Testing, size/XS

#2904 Remove 'test_delete_osd_pod' as it is already included in 'test_delete_pod'
  tests/manage/z_cluster/cluster_expansion/test_delete_osd_pod.py
  tests/manage/z_cluster/cluster_expansion/test_delete_pod.py
Labels: Verified, size/M

#2852 create_workload_job function and workload job factory for mcg io
  ocs_ci/ocs/fio_artefacts.py
  ocs_ci/ocs/mcg_workload.py
  tests/conftest.py
  tests/ecosystem/upgrade/conftest.py
  tests/ecosystem/upgrade/test_noobaa.py
  tests/libtest/test_mcg_workload.py
Labels: Verified, size/XL

#2906 Updating OCP4.6 vm template
  conf/ocp_version/ocp-4.6-config.yaml
Labels: Verified, size/XS, team/ecosystem

#2924 Add latest tags for 4.6 and use stable builds
  conf/ocs_version/ocs-4.5.yaml
  conf/ocs_version/ocs-4.6.yaml
  ocs_ci/ocs/constants.py
Labels: size/XS, team/ecosystem

#2921 vSphere: Do cold power off in node restart scnenarios instead of graceful OS shutdown
  ocs_ci/ocs/platform_nodes.py
  tests/manage/z_cluster/nodes/test_nodes_restart.py
Labels: Verified, size/S

#2893 IPI fixes for test_node_replacement_proactive case
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: platforms, size/M

#2914 increase timeout of santiy health check in test_node_maintenance
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: size/XS

#2930 test_pod_reattachtime_fix
  tests/e2e/performance/test_pod_reattachtime.py
Labels: size/XS

#2933 Increases timeout for configuring chrony on nodes
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/utils.py
Labels: size/XS, team/ecosystem

#2926 Add OCP 4.6 images for BM
  ocs_ci/templates/ocp-deployment/rhcos_images.yaml
Labels: Verified, size/XS

#2931 Test NB recovery from node drain
  tests/conftest.py
  tests/manage/mcg/test_mcg_resources_disruptions.py
Labels: MCG, Test Case, Verified, size/M

#2928 Cluster load: Allow reduce load in addition to pause
  ocs_ci/ocs/cluster_load.py
  tests/conftest.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/M

#2898 Skip collecting items for skipif_ocs_version or skipif_upgraded_from for deployments
  tests/conftest.py
Labels: Verified, size/M, team/ecosystem

#2712 Test node replacement proactive with vSphere UPI
  conf/ocsci/vsphere_scale_cluster_rhcos.yaml
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Verified, size/L

#2938 Avoid using latest tags
  ocs_ci/ocs/constants.py
  ocs_ci/utility/utils.py
Labels: Verified, size/S, team/ecosystem

#2949 Fix typo for client_version
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: High Priority, Verified, bug, team/ecosystem

#2913 Skip ocs must gather for ocp deployment failures
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: Verified, size/XS, team/ecosystem

#2900 Extend OBC health verification timeout
  ocs_ci/ocs/resources/objectbucket.py
Labels: size/XS

#2925 Update test_pvc_to_pvc_clone to run IO before creating clone
  tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py
Labels: Verified, size/M, team/manage

#2756 added mutiple pvc deletion case
  tests/e2e/performance/test_pvc_deletion_performance.py
Labels: size/M

#2945 Change the PVC multiple creation to work as bulk
  tests/helpers.py
Labels: High Priority, Verified, bug, performance, size/M

#2953 Move to OCS 4.6 as default version
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/S, team/ecosystem

#2915 downstream ci: change ocs-bundle-operator to ocs-operator-bundle
  Jenkinsfile
Labels: size/XS

#2955 PVC bulk creation fixing measurement time
  tests/e2e/performance/test_pvc_creation_performance.py
  tests/helpers.py
Labels: High Priority, Verified, bug, performance, size/M

#2956 Remove duplicate logging in test_upgrade_ocp
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: size/S, team/ecosystem

#2961 Disable test case: add MDS to cluster
  tests/manage/z_cluster/test_add_mds_to_cluster.py
Labels: Verified, size/XS

#2963 Changing the PVC type that create to be taken from variable
  tests/e2e/performance/test_pod_reattachtime.py
Labels: bug, performance, size/S

#2766 Add user_factory
  ocs_ci/ocs/constants.py
  ocs_ci/templates/authentication/htpasswd_provider.yaml
  ocs_ci/utility/users.py
  ocs_ci/utility/utils.py
  tests/conftest.py
  tests/libtest/test_user.py
Labels: size/L

#2959 Add support for OCS deployment via OCS-CI for IBM Power platform - Re…
  conf/ocsci/production_powervs_upi.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/factory.py
  ocs_ci/deployment/ibm.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/templates/ocs-deployment/clean.sh
  ocs_ci/templates/ocs-deployment/ibm-storage-cluster.yaml
Labels: Verified, size/XL

#2960 Include squad analysis into email results report
  docs/usage.md
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/framework/pytest_customization/reports.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/utils.py
Labels: Verified, size/L, team/ecosystem

#2966 Decrease the number of pools created to two
  tests/manage/storageclass/test_create_multiple_sc_with_different_pool_name.py
Labels: Verified, size/XS

#2934 Skip performance stats collection for external mode RHCS cluster
  tests/helpers.py
Labels: External-cluster-mode, performance, scale, size/S

#2975 vSphere: Abort deployment if cluster with the same name prefix already exists
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/vsphere.py
Labels: Verified, size/M

#2909 Add ceph health check at the end of the test
  conf/ocp_version/ocp-4.5-upgrade.yaml
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Verified, size/XS

#2922 Customer Defect rook-ceph-crashcollector went into CLBO
  ocs_ci/framework/pytest_customization/marks.py
  tests/manage/z_cluster/test_delete_local_volume_sym_link.py
Labels: Customer defects, Needs Testing, Verified, size/M

#2978 fix squad analysis report
  ocs_ci/framework/pytest_customization/reports.py
Labels: Verified, team/ecosystem

#2958 Download terraform ignition provider for destroy job.
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/utils.py
Labels: Verified, size/M, team/ecosystem

#2946 fix osd tree verification for baremetalpsi platform
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S

#2965 Test to verify snapshot when PVC usage is at different levels
  ocs_ci/ocs/resources/pvc.py
  ocs_ci/templates/CSI/cephfs/pvc-restore.yaml
  ocs_ci/templates/CSI/cephfs/snapshot.yaml
  ocs_ci/templates/CSI/rbd/pvc-restore.yaml
  ocs_ci/templates/CSI/rbd/snapshot.yaml
  tests/conftest.py
  tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
Labels: Test Case, Verified, size/L, team/manage

#2880 Collecting must gather after every status of deployment
  .functional_ci_setup.py
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/utils.py
  tests/conftest.py
Labels: size/M

#2982 Squad analysis: highlight yellow title
  ocs_ci/utility/utils.py
Labels: size/XS, team/ecosystem

#2943 GCP deployment
  conf/deployment/gcp/ipi_1az_rhcos_3m_3w.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/gcp.py
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/templates/ocp-deployment/install-config-gcp-ipi.yaml.j2
  ocs_ci/templates/ocs-deployment/storageclass.gcp.yaml
  ocs_ci/utility/gcp.py
  ocs_ci/utility/tests/test_gcp.py
  tests/libtest/test_gcp.py
Labels: Verified, platforms, size/L

#2984 Add minimum size of '256' GB for test purpose (non production use)
  conf/ocsci/minimum_test_device_size.yaml
Labels: size/XS

#2991 Delete the vdbench benchmark test
  tests/e2e/performance/test_vdbench_workload.py
Labels: size/L

#2997 Mirror images before using it
  tests/helpers.py
Labels: Verified, size/XS, team/e2e

#2950 Fix registry failures
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/registry.py
  tests/e2e/registry/test_registry_pod_respin.py
  tests/e2e/registry/test_registry_pull_and_push_images_to_registry.py
Labels: Verified, size/L, team/e2e

#2999 checking the number of builds succeeded instead of failures
  tests/e2e/test_simple_registry_workload.py
Labels: Verified, size/XS, team/e2e

#2675 Test case to increase number of registry pods
  ocs_ci/ocs/registry.py
  tests/e2e/registry/test_registry_by_increasing_num_of_image_registry_pods.py
Labels: Test Case, Verified, size/L, team/e2e

#2979 Use optional-operators catalogsource for LSO on non-GA OCP versions
  conf/ocsci/local_storage_namespace.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/uninstall.py
  ocs_ci/templates/ocs-deployment/local-storage-operator.yaml
  ocs_ci/templates/ocs-deployment/local-storage-optional-operators.yaml
  ocs_ci/templates/ocs-deployment/local-volume.yaml
  ocs_ci/utility/deployment.py
  ocs_ci/utility/localstorage.py
Labels: Verified, size/L, team/ecosystem

#2794 Add verifications steps after node replacement
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Verified, size/L

#3003 added storage_size parameter to create_pvc_clone method
  ocs_ci/ocs/resources/pvc.py
Labels: size/XS

#3004 Added new marker "flowtests" for running flowbased tests
  ocs_ci/framework/pytest_customization/marks.py
  pytest.ini
  tests/e2e/flowtest/test_base_operation_node_drain.py
Labels: Verified, size/XS, team/e2e

#3014 retry for patching imageregistry operator
  ocs_ci/deployment/vmware.py
Labels: size/XS, team/ecosystem

#2905 move create and delete obc as part of create_resource and delete_resource…
  ocs_ci/ocs/constants.py
  tests/sanity_helpers.py
Labels: External-cluster-mode, Verified, size/L, team/ecosystem
