Repository red-hat-storage/ocs-ci, pull requests merged in 2020-04, with the labels that each got.

#1752 Increase wait time for pvc to Bound
  tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py
Labels: Verified, size/XS, team/manage

#1760 Do not delete floating cloudformation stacks
  ocs_ci/cleanup/aws/cleanup.py
Labels: Verified, size/S

#1750 Fix max attempt check, range will return integers before final stop.
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, size/XS

#1759 Deleting extra disks for RHEL.
  ocs_ci/deployment/vmware.py
Labels: Verified, size/XS, team/ecosystem

#1742 Fixes: #1743 - Fix vSphere get_vms() method for RHEL workers
  ocs_ci/ocs/platform_nodes.py
Labels: size/XS

#1754 Stabilize the MCG data reduction test
  ocs_ci/ocs/resources/mcg.py
  tests/manage/mcg/test_write_to_bucket.py
Labels: Verified, bug, size/S, team/manage

#1762 add another ocp upgrade validation - check cluter operator status
  ocs_ci/ocs/ocp.py
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Verified, size/M

#1482 Couchbase e2e test added.
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/pillowfight.py
  ocs_ci/templates/workloads/couchbase/server/MutatingWebhookConfiguration.yaml
  ocs_ci/templates/workloads/couchbase/server/ValidatingWebhookConfiguration.yaml
  ocs_ci/templates/workloads/couchbase/server/admissionClusterRole.yaml
  ocs_ci/templates/workloads/couchbase/server/admissionClusterRoleBinding.yaml
  ocs_ci/templates/workloads/couchbase/server/admissionDeployment.yaml
  ocs_ci/templates/workloads/couchbase/server/admissionSecret.yaml
  ocs_ci/templates/workloads/couchbase/server/admissionService.yaml
  ocs_ci/templates/workloads/couchbase/server/admissionServiceAccount.yaml
  ocs_ci/templates/workloads/couchbase/server/basic-pillowfight.yaml
  ocs_ci/templates/workloads/couchbase/server/couchbase-worker-example.yaml
  ocs_ci/templates/workloads/couchbase/server/couchbase-worker-secret.yaml
  ocs_ci/templates/workloads/couchbase/server/couchbaseCrd.yaml
  ocs_ci/templates/workloads/couchbase/server/operator-deployment.yaml
  ocs_ci/templates/workloads/couchbase/server/operator-role.yaml
  ocs_ci/templates/workloads/couchbase/server/pillowfight/basic-pillowfight.yaml
  tests/e2e/workloads/test_couchbase.py
Labels: Verified, enhancement, size/L, team/e2e

#1766 Fixing teardown of cluster
  ocs_ci/deployment/aws.py
  ocs_ci/utility/aws.py
Labels: Verified, size/S, team/ecosystem

#1661 Node and NodeUtils class for handling nodes of a cluster
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/XL, team/ecosystem

#1654 Housekeeping of registry test cases
  tests/e2e/registry/test_pod_from_registry.py
  tests/e2e/registry/test_registry_image_push_pull.py
Labels: Needs Testing

#1773 added some logs, add exception if logs directory dosent found
  tests/manage/z_cluster/test_must_gather.py
Labels: Verified, size/S, team/manage

#1656 Health check for all the tier tests
  tests/conftest.py
Labels: Verified, size/S, team/ecosystem

#1784 Pin Sphinx version to 2.4.4
  requirements-docs.txt
Labels: Verified, bug, size/XS, team/ecosystem

#1781 Added configuration option to preserve the bootstrap node
  conf/ocsci/preserve_bootstrap_node.yaml
  ocs_ci/deployment/aws.py
  ocs_ci/deployment/vmware.py
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/M, team/ecosystem

#1787 Add missing worker instance type to production configs
  conf/deployment/aws/upi_1az_rhcos_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhcos_3m_3w.yaml
Labels: size/XS, team/ecosystem

#1791 Fix Indentation in storage_cluster
  ocs_ci/ocs/resources/storage_cluster.py
Labels: size/M, team/ecosystem

#1796 Add OCS 4.4 to --ocs-version param
  ocs_ci/framework/main.py
Labels: size/XS, team/ecosystem

#1793 Wait longer time for OSD upgrade
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, size/XS, team/ecosystem

#1789 Add RHEL repos for OCP 4.4
  ocs_ci/repos/ocp_4_4.repo
Labels: size/M, team/ecosystem

#1804 Disable rhcos_ami
  conf/deployment/aws/upi_1az_rhel7_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhel7_3m_3w.yaml
  conf/ocp_version/ocp-4.2-config.yaml
  conf/ocp_version/ocp-4.3-config.yaml
  conf/ocp_version/ocp-4.4-config.yaml
Labels: size/XS

#1805 Fix ansible repo for OCP 4.4
  ocs_ci/repos/ocp_4_4.repo
Labels: Verified, size/XS, team/ecosystem

#1810 Fixes: #1811: Fix for a few issues in aws-cleanup
  ocs_ci/cleanup/aws/cleanup.py
Labels: Verified, size/XS

#1815 test_change_reclaim_policy_of_pv test optimization
  tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
Labels: Verified, size/S

#1817 Add capacity test: Fix Ceph health check
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Labels: Verified, size/XS

#1820 Fix: #1819 - Fix OSD distribution validation to handle multiple OSDs per node
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/XS

#1245 Test case for recovery from disk deletion over vSphere
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/pvc.py
  ocs_ci/utility/vsphere.py
  tests/manage/z_cluster/nodes/test_disk_failures.py
  tests/sanity_helpers.py
Labels: Test Case, Verified, size/L

#1614 BZ-1769667: Simultaneous drain of two OCS nodes
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Test Case, Verified, size/L, team/manage

#1666 Update test_automated_recovery_from_failed_nodes_proactive_IPI
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_proactive_IPI.py
Labels: Test Case, Verified, size/L, team/manage

#1785 Still gather bootstrap if no master IPs are gathered
  ocs_ci/utility/bootstrap.py
Labels: Verified, size/S, team/ecosystem

#1803 Increase timeout for terraform commands
  ocs_ci/deployment/terraform.py
Labels: size/XS, team/ecosystem

#1827 Fix in teardown cluster.
  tests/conftest.py
Labels: Verified, size/XS, team/ecosystem

#1832 Fixing skip_ocs_deployment teardown
  tests/conftest.py
Labels: Needs Deployment Testing, size/XS, team/ecosystem

#1822 Persistent logs for terraform
  ocs_ci/deployment/vmware.py
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/S, team/ecosystem

#1780 Fix scale issues observed during jenkins run
  tests/e2e/scale/test_pvc_creation_deletion_scale.py
  tests/helpers.py
Labels: High Priority, Needs Testing, size/M, team/e2e

#1714 Data verification of previously written fio data
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/fiojob.py
  ocs_ci/ocs/tests/fio.output
  ocs_ci/ocs/tests/test_fiojob.py
  ocs_ci/utility/workloadfixture.py
  tests/conftest.py
  tests/ecosystem/upgrade/conftest.py
  tests/ecosystem/upgrade/test_resources.py
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/test_workload_example.py
  tests/manage/monitoring/test_workload_with_distruptions.py
Labels: Verified, size/XXL

#1838 check_query_range_result is function, add tests
  ocs_ci/utility/prometheus.py
  ocs_ci/utility/tests/test_prometheus.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_negative.py
Labels: size/L

#1808 Update test to use default cephblockpool
  tests/conftest.py
  tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
Labels: Verified, size/XS

#1834 Skipping logging deployment/tests on OCP 4.4
  tests/e2e/logging/test_openshift-logging.py
Labels: Verified, size/XS, team/ecosystem

#1775 Make sure couchbase-operator namespace is deleted. (#1774)
  ocs_ci/ocs/pillowfight.py
Labels: size/XS

#1844 Check more than one instance if the cluster_io_tag isn't found on the first
  ocs_ci/cleanup/aws/cleanup.py
  ocs_ci/ocs/exceptions.py
Labels: High Priority, Verified, size/S, team/ecosystem

#1845 Removed logging of skip_condition during test collection
  tests/conftest.py
Labels: enhancement, size/XS, team/ecosystem

#1671 Add more logs to noobaa quota alerting test
  ocs_ci/ocs/resources/mcg.py
  tests/manage/monitoring/conftest.py
Labels: Verified, size/M

#1849 Add retry for monitoring deployment check
  ocs_ci/deployment/deployment.py
Labels: Verified, size/XS, team/ecosystem

#1755 Remove the 1TB object deletion test from Tier3 because of a long execution time
  tests/manage/mcg/test_bucket_deletion.py
Labels: size/XS, team/manage

#1840 Change logic for wait for registry based on replicas
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/registry.py
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/L, team/ecosystem

#1770 Enable internal reportportal host
  ocs_ci/framework/main.py
  ocs_ci/framework/pytest_customization/reports.py
  pytest.ini
  setup.py
Labels: Verified, size/S

#1858 Log warning instead of raising Error if cluster isn't an OCS cluster
  ocs_ci/cleanup/aws/cleanup.py
  ocs_ci/ocs/exceptions.py
Labels: Verified, bug, size/S, team/ecosystem

#1842 Fix of issue 1709: test OCS-1306 checks only exp. mon downtime
  ocs_ci/utility/prometheus.py
  ocs_ci/utility/tests/test_prometheus.py
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_negative.py
Labels: Needs Testing, size/M

#1865 less strict check of the stderr in unitttest
  ocs_ci/utility/tests/test_utils.py
Labels: Verified, size/S

#1863 log ceph mon_osd_*_ratio ratio values
  tests/manage/monitoring/conftest.py
Labels: Verified, size/S

#1875 Fix issue with mount command
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/monitoring.py
  ocs_ci/ocs/registry.py
Labels: Verified, size/S, team/ecosystem

#1868 added config file for ocp4.4 candidate channel
  conf/ocp_version/ocp-4.4-candidate-upgrade.yaml
Labels: Verified, size/XS

#1874 move assert statements to the end
  tests/manage/monitoring/prometheusmetrics/test_monitoring_negative.py
Labels: size/S

#1864 try to double a small utilization target if met
  tests/manage/monitoring/conftest.py
Labels: Verified, size/S

#1867 Testcase - RBD: Assign nodeName to a POD using RWX PVC
  tests/manage/pv_services/test_pvc_assign_pod_node.py
Labels: Test Case, Verified, size/M, team/manage

#1853 Verify status of osd-prepare pods after adding capacity
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Labels: Test Case, Verified, size/XS, team/manage

#1886 checkout version specific openshift installer branch
  ocs_ci/deployment/vmware.py
Labels: Verified, size/XS, team/ecosystem

#1882 fetch logs of all job pods in case of a failure
  ocs_ci/ocs/fiojob.py
  ocs_ci/ocs/ocp.py
Labels: Verified, size/M

#1877 Replace run_cmd with exec_cmd
  ocs_ci/utility/utils.py
Labels: Verified, size/M

#1887 Update StatefulSet api version.
  ocs_ci/templates/workloads/pgsql/server/StatefulSet.yaml
Labels: Verified, size/XS

#1893 run `oc describe` when wait timeouts
  ocs_ci/ocs/ocp.py
Labels: size/XS

#1876 Change to OCS 4.4 as default
  conf/ocp_version/ocp-4.4-config.yaml
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/S, team/ecosystem

#1896 Approve csrs
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/csr.py
Labels: Verified, size/M, team/ecosystem

#1897 Add tier_after_upgrade
  ocs_ci/framework/pytest_customization/marks.py
  pytest.ini
Labels: size/XS

#1672 Cloud Manager and ULS & Backingstore factories
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/cloud_manager.py
  ocs_ci/templates/mcg/PVBackingStore.yaml
  setup.py
  tests/conftest.py
  tests/manage/mcg/helpers.py
Labels: Verified, size/XL, team/manage

#1898 Add one more approve of CSRs after deployment finish
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/csr.py
Labels: Verified, size/XS, team/ecosystem

#1828 [MCG] Exec CLI commands through the NooBaa operator pod's binary
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/registry.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/mcg_bucket.py
  ocs_ci/utility/utils.py
  tests/conftest.py
  tests/e2e/registry/test_registry_image_push_pull.py
  tests/manage/mcg/helpers.py
  tests/manage/mcg/test_bucket_creation.py
  tests/manage/mcg/test_bucket_deletion.py
  tests/manage/mcg/test_verify_noobaa_status.py
Labels: Verified, enhancement, size/L, team/manage

#1799 Improve bucket creation test
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/mcg_bucket.py
  tests/ecosystem/upgrade/test_noobaa.py
  tests/manage/mcg/test_bucket_creation.py
Labels: Verified, size/L, team/manage

#1778 Add test case for cephfs and rbd pv resize.
  ocs_ci/ocs/resources/pvc.py
  ocs_ci/templates/CSI/cephfs/storageclass.yaml
  ocs_ci/templates/CSI/rbd/storageclass.yaml
  tests/helpers.py
  tests/manage/pv_services/test_pvc_resize.py
Labels: Test Case, Verified, size/L, team/manage

#1906 Cluster prefix duplication fix
  ocs_ci/cleanup/aws/defaults.py
  ocs_ci/deployment/aws.py
Labels: Verified, size/S, team/ecosystem

#1855 vdbench| Dynamicly calculate dataset
  ocs_ci/ocs/constants.py
  ocs_ci/templates/workloads/vdbench/VDBench-Basic-FS.yaml
  tests/e2e/performance/test_vdbench_workload.py
Labels: Needs Testing, size/L

#1901 code style fix in fiojob module
  ocs_ci/ocs/fiojob.py
Labels: size/S

#1913 Handle case where vpc_obj tags returns a NoneType
  ocs_ci/cleanup/aws/cleanup.py
Labels: Verified, bug, size/M, team/ecosystem

#1910 Improving teardown cluster in vSphere
  ocs_ci/deployment/vmware.py
Labels: Verified, size/S, team/ecosystem

#1903 Fix in Approving CSRs
  ocs_ci/utility/csr.py
Labels: Verified, size/M, team/ecosystem

#1915 Fix OCP 4.4 repos
  ocs_ci/repos/ocp_4_4.repo
Labels: size/XS, team/ecosystem

#1679 Function to check rebalance status and time taken
  ocs_ci/ocs/cluster.py
  tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
Labels: Test Case, Verified, size/L, team/e2e

#1917 Test detach attach worker volume: Increase health check timeout
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/XS

#1930 Fix: #1929 - Fix in AWS cleanup - replace() instead of strip()
  ocs_ci/cleanup/aws/cleanup.py
Labels: Verified, size/XS

#1934 Cleanup of unused configs and update production sizes
  conf/deployment/vsphere/upi_1az_rhcos_3m_3w_dc1_dc2.yaml
  conf/deployment/vsphere/upi_1az_rhcos_3m_3w_prod_memory.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vmfs_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_3m_3w_dc1_dc2.yaml
  conf/deployment/vsphere/upi_1az_rhel_3m_3w_prod_memory.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_3m_3w.yaml
  conf/ocsci/ocp-4.2-config.yaml
  conf/ocsci/ocp-4.2-ga-config.yaml
  conf/ocsci/ocp-4.3-config.yaml
  conf/ocsci/ocp-4.3-ga-config.yaml
  conf/ocsci/ocp-4.4-config.yaml
  conf/ocsci/ocs-4.3.yaml
  conf/ocsci/production_device_size.yaml
  ocs_ci/ocs/defaults.py
Labels: size/L, team/ecosystem

#1923 Improve verify_health to utilize TimeoutSampler and wait for bucket
  ocs_ci/ocs/resources/mcg_bucket.py
Labels: Verified, size/M, team/manage

#1932 updates vdbench test with performance marker
  tests/e2e/performance/test_vdbench_workload.py
Labels: size/XS

#1852 NooBaa bucket state check after upgrade
  tests/ecosystem/upgrade/conftest.py
  tests/ecosystem/upgrade/test_noobaa.py
Labels: Verified, size/M

#1904 log events in test namespaces before teardown
  tests/conftest.py
Labels: size/S

#1933 Scale - Add ceph_health_check in ceph pod respin test
  tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Labels: High Priority, size/S, team/e2e

#1936 helpers for uninstall OCS automation
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/pvc.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/M

#1928 Move ceph health to the end of install verification
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Needs Testing, size/S, team/ecosystem

#1944 move workload_fio_storageutilization into fiojob
  ocs_ci/ocs/fiojob.py
  tests/manage/monitoring/conftest.py
Labels: Verified, size/L

#1938 Improvement in approve_csr functionality
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/node.py
  ocs_ci/utility/csr.py
Labels: Verified, size/L, team/ecosystem

#1921 Improve ocp upgrade
  ocs_ci/ocs/ocp.py
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Verified, size/L

#1899 Test-Verify RWO volumes are exclusively mounted by adding replica 2 i…
  tests/helpers.py
  tests/manage/pv_services/test_verify_rwo_using_dc_pod.py
Labels: Test Case, Verified, size/L, team/manage

#1953 Test add capacity pre upgrade
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Labels: Verified, size/XS

#1831 Bucket policy - Adding additional tier1 and tier3 testcases
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/resources/bucket_policy.py
  tests/manage/mcg/helpers.py
  tests/manage/mcg/test_bucket_policy.py
Labels: Test Case, Verified, size/XL, team/manage

#1935 Add retry for fetching daemon pid
  tests/disruption_helpers.py
Labels: Verified, enhancement, size/XS

#1958 Fix - Add retry to get aws-cloudcred secret
  ocs_ci/ocs/resources/mcg.py
Labels: Verified, bug, size/XS

#1416 Add tests for KNIP-677: OCS support for Automated fencing/unfencing RWO PV
  tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
Labels: Test Case, Verified, size/XL, team/manage

#1952 Add Support to run test over BAREMETAL
  conf/deployment/baremetal/upi_1az_rhcos_3m_3w.yaml
  ocs_ci/deployment/baremetal.py
  ocs_ci/deployment/factory.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/utils.py
Labels: Verified, size/M

#1969 Add Rhel config for baremetal deployment
  conf/deployment/baremetal/upi_1az_rhel7_3m_3w.yaml
  ocs_ci/utility/utils.py
Labels: Verified, size/S

#1970 OCP upgreade: fixed indentation
  ocs_ci/ocs/ocp.py
Labels: Verified, size/XS

#1964 vdbench | Adding teardown ceph_health_check to the test
  tests/e2e/performance/test_vdbench_workload.py
Labels: size/XS

#1971 Remove tier4a marker from test_scale_osds_fill_75%_reboot_workers.py
  tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
Labels: size/XS

#1581 collect performance stats when OCS operation fails for scale and perfomance test cases
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/node.py
  tests/helpers.py
Labels: Verified, enhancement, size/M

#1961 Fix: #1960 - Wait for cluster connectivity after disruptive node tests
  ocs_ci/ocs/ocp.py
  tests/sanity_helpers.py
Labels: Verified, size/S

#1931 Make sure that open calls use file descriptors that can be closed Fixes: #1889
  ocs_ci/utility/utils.py
  tests/e2e/scale/test_pvc_creation_deletion_scale.py
  tests/manage/storageclass/test_storageclass_invalid.py
Labels: Needs Testing, size/M
