Repository red-hat-storage/ocs-ci, pull requests merged in 2020-10, with the labels that each got.

#2896 Polarion upgrade fix
  conf/deployment/aws/ipi_1az_rhcos_3m_3w.yaml
  conf/deployment/aws/ipi_3az_rhcos_3m_3w.yaml
  conf/deployment/aws/upi_1az_rhcos_3m_3w.yaml
  conf/deployment/aws/upi_1az_rhel7_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhcos_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhel7_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vmfs_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_3m_3w.yaml
  conf/upgrade/upgrade_3m.yaml
  conf/upgrade/upgrade_3m_3w.yaml
  conf/upgrade/upgrade_greater_than_3w.yaml
Labels: Needs Testing, size/M, team/ecosystem

#2696 Enable encryption at rest
  conf/ocsci/encryption_at_rest.yaml
  docs/usage.md
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/exceptions.py
Labels: Verified, new feature, size/M, team/ecosystem

#3038 drop pip requires from tox.ini
  tox.ini
Labels: size/XS

#3025 Optional parameter to gather logs when deployment runs successfully
  docs/usage.md
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/utils.py
Labels: size/S

#3032 Skip namespace tests in case AWS credentials are unavailable
  tests/manage/mcg/test_namespace.py
Labels: MCG, size/XS

#3017 Fio fill up functionality
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/templates/workloads/fio/workload_io_fillup.yaml
  tests/internal/test_fio_fillup.py
Labels: Verified, performance, size/L

#3034 Fix cred dict issue
  ocs_ci/ocs/resources/cloud_manager.py
Labels: size/XS, team/ecosystem

#3051 Add a wait after creating LSO yaml
  ocs_ci/deployment/deployment.py
Labels: High Priority, Verified, bug, size/XS

#3008 adding a new test for single pvc clone performance
  tests/e2e/performance/test_single_pvc_clone_perf.py
Labels: performance, size/L

#3048 Preventing call of collect ocs logs when status_failure=False is sent
  .functional_ci_setup.py
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/utils.py
  tests/conftest.py
Labels: High Priority, Verified, size/S

#2970 Changes needed for OCP 4.6 on BM platform
  ocs_ci/deployment/baremetal.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/baremetal-pxefile/bootstrap
  ocs_ci/templates/baremetal-pxefile/master
  ocs_ci/templates/baremetal-pxefile/worker
  ocs_ci/templates/ocp-deployment/rhcos_images.yaml
Labels: Verified, platforms, size/L

#3029 Add config file for rhv platform
  conf/deployment/rhv/ipi_1az_rhcos_3m_3w.yaml
Labels: platforms, size/S

#3053 Fix skipif_no_lso marker
  ocs_ci/framework/pytest_customization/marks.py
Labels: Verified, size/XS

#3058 Adding configurations for AWS VMware to support 32RAM 8VCPU Clusters
  conf/ocsci/aws_lower_resource_reqs.yaml
  conf/ocsci/vsphere_lower_resource_reqs.yaml
Labels: size/S

#3046 doc fix: don't show readme in FAQ section
  docs/conf.py
Labels: size/XS

#3015 Unblock parent PVC deletion for cephfs PVC
  tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
Labels: Verified, size/S, team/manage

#3024 Update the source image to fedora
  tests/e2e/registry/test_pod_from_registry.py
  tests/helpers.py
Labels: Verified, size/XS, team/e2e

#3062 add new prefix for production clusters to cleanup script
  ocs_ci/cleanup/aws/defaults.py
Labels: Verified, size/XS, team/ecosystem

#3067 Create new conf file the configurations: vSphere, UPI, RHCOS, 6 worker nodes
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_6w.yaml
Labels: size/S

#3057 fix jenkins issue on OCP4.6
  ocs_ci/ocs/jenkins.py
  ocs_ci/ocs/ocp.py
Labels: Verified, size/S

#3061 Set log level of ocscilib module based on pytest.ini log_cli_level
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/S, team/ecosystem

#3020 Use new way of installing OCS over LSO based cluster
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocs-deployment/local-volume-discovery.yaml
  ocs_ci/templates/ocs-deployment/local-volume-set.yaml
Labels: Verified, size/L

#3066 Avoid creating pxe file for all nodes
  ocs_ci/deployment/baremetal.py
Labels: High Priority, Verified, platforms, size/S

#3074 Fixing log handler issue
  ocs_ci/framework/pytest_customization/reports.py
Labels: Needs Deployment Testing, size/XS, team/ecosystem

#3039 Stage bundle 4.6
  conf/ocsci/stage-rh-osbs-4.5.yaml
  conf/ocsci/stage-rh-osbs-4.6.yaml
  conf/ocsci/stage-rh-osbs.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocs-deployment/stageImageContentSourcePolicy.yaml
Labels: Verified, size/M, team/ecosystem

#3022 Environment pre-checks for on-prem platforms
  ocs_ci/deployment/helpers/prechecks.py
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/vsphere.py
Labels: Verified, size/L, team/ecosystem

#3077 Adding marker for skip depend on OCP version
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: High Priority, Verified, enhancement

#3072 deployment: add 15 min to Azure ocp install timeout
  conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
  ocs_ci/deployment/cloud.py
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, platforms, size/S

#3081 Explicitly add StreamHandler to ocscilib logger instead of using basicConfig
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/framework/pytest_customization/reports.py
Labels: High Priority, Verified, size/S, team/ecosystem

#3063 NooBaa endpoint autoscale infra
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/testlib.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/conftest.py
  tests/manage/mcg/test_bucket_creation.py
  tests/manage/mcg/test_bucket_deletion.py
  tests/manage/mcg/test_bucket_policy.py
  tests/manage/mcg/test_mcg_resources_disruptions.py
  tests/manage/mcg/test_multi_region.py
  tests/manage/mcg/test_multipart_upload.py
  tests/manage/mcg/test_namespace.py
  tests/manage/mcg/test_object_integrity.py
  tests/manage/mcg/test_write_to_bucket.py
Labels: Verified, size/L

#3079 skip environment prechecks for teardown
  ocs_ci/deployment/vmware.py
Labels: Verified, size/XS, team/ecosystem

#3076 Increase snapshot restore wait time in test
  tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
Labels: size/XS, team/manage

#3086 Look for 1 min and 1 max NB EPs with 4.5 and lower clusters
  conf/ocsci/noobaa_endpoints_scale.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/testlib.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S

#3095 Adding updated template for OCP 4.6
  conf/ocp_version/ocp-4.6-config.yaml
Labels: Verified, size/XS, team/ecosystem

#3070 Enhance pvc creations scale using kube_job
  ocs_ci/ocs/scale_lib.py
  tests/e2e/scale/test_pvc_creation_deletion_scale.py
Labels: High Priority, Verified, bug, enhancement, scale, size/L

#3096 Change scale TC fixture scope to "Class"
  tests/e2e/scale/test_ceph_pod_respin_in_scaled_cluster.py
Labels: High Priority, Verified, bug, scale, size/XS

#2935 Enhanced TC for External mode, fixed pvc capacity problem
  tests/e2e/scale/test_pods_are_not_oomkilled_while_running_ios.py
Labels: High Priority, TestCase failing, Verified, scale, size/M

#3101 deployment: Don't run vsphere code on all nodes
  ocs_ci/deployment/deployment.py
Labels: bug, size/XS

#2994 Adding test for PVC snapshot performance - Create and Restore
  ocs_ci/ocs/resources/pod.py
  tests/e2e/performance/test_pvc_snapshot_performance.py
  tests/helpers.py
Labels: performance, size/L

#2795 Testcase OCS-2230
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
Labels: Test Case, Verified, bug, size/L, team/e2e

#3111 changing timeout for ripsaw cleanup
  ocs_ci/ocs/ripsaw.py
Labels: Skip test, performance, size/XS

#3009 Test case: PVC clone when full
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/pvc.py
  tests/conftest.py
  tests/manage/pv_services/pvc_clone/test_clone_when_pvc_full.py
Labels: Test Case, Verified, size/L, team/manage

#3104 Remove replica counts from upgrade config files
  conf/upgrade/upgrade_3m.yaml
  conf/upgrade/upgrade_3m_3w.yaml
  conf/upgrade/upgrade_greater_than_3w.yaml
Labels: size/XS, team/ecosystem

#3091 Set min NB EPs to 2 for all MCG tests and fix a bug in nb_ensure_endpoint_count
  ocs_ci/framework/testlib.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/conftest.py
Labels: Verified, size/S

#3117 Fixing the skipif_ocp_version
  ocs_ci/utility/utils.py
Labels: High Priority, bug, performance, size/XS

#3018 Fix for test_object_actions test case for OCS >=4.6
  tests/manage/mcg/test_bucket_policy.py
Labels: High Priority, Verified, bug, size/M, team/manage

#3108 added function: get_ocs_parsed_version
  ocs_ci/ocs/ocp.py
Labels: Verified, size/S

#3082 Couchbase: export pillowfight pods log info to google sheet
  ocs_ci/ocs/pillowfight.py
  tests/conftest.py
  tests/e2e/workloads/couchbase/test_couchbase.py
Labels: Verified, size/M, team/e2e

#3102 Added config file for OCP 4.7
  conf/ocp_version/ocp-4.7-config.yaml
Labels: size/XS, team/ecosystem

#2694 Add ocs-monkey test
  ocs_ci/ocs/constants.py
  tests/ocs-monkey/test_ocs_monkey.py
Labels: Verified, size/M

#3130 Added config file for OCS 4.7
  conf/ocs_version/ocs-4.7.yaml
  ocs_ci/framework/main.py
Labels: Verified, size/S, team/ecosystem

#3127 skipif_ocp get the version from running cluster and not from config file
  ocs_ci/utility/utils.py
  tests/internal/test_skipif_ocp.py
Labels: bug, performance, size/M

#3099 Use Rotational to detect HDD disk for LocalVolumeSet for Vmware LSO deployment
  ocs_ci/deployment/deployment.py
Labels: Verified, size/XS

#3139 Change log level for job pod logs
  ocs_ci/ocs/mcg_workload.py
Labels: High Priority

#3119 consider `force_deploy_multiple_clusters` for VMware
  ocs_ci/deployment/vmware.py
Labels: Verified, size/XS, team/ecosystem

#3093 Fix for test_uninstall_ocs verification
  ocs_ci/framework/pytest_customization/ocscilib.py
  tests/conftest.py
Labels: Needs Testing, size/S, team/ecosystem

#3097 Testcase: Snapshot creation and restore of PGSQL Workloads PVCs
  ocs_ci/ocs/pgsql.py
  ocs_ci/templates/workloads/pgsql/server/StatefulSet.yaml
  tests/conftest.py
  tests/e2e/lifecycle/pvc_snapshot/test_pgsql_pvc_snapshot.py
Labels: Test Case, Verified, size/L, team/e2e

#3141 Verify usage on new pods in snapshot test
  tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
Labels: Verified, size/S, team/manage

#3128 Test to verify PVC clone with access mode different than parent PVC
  ocs_ci/ocs/resources/pod.py
  tests/conftest.py
  tests/manage/pv_services/conftest.py
  tests/manage/pv_services/pvc_clone/test_clone_with_different_access_mode.py
Labels: Test Case, Verified, size/L, team/manage

#3134 Fix getting Hostname for worker nodes
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/node.py
Labels: High Priority, Verified, size/M

#3026 fixes #2971. RGW pod count verification check modification
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: size/M

#3150 Add OCP 4.7 upgrade config
  conf/ocp_version/ocp-4.7-upgrade.yaml
Labels: size/XS, team/ecosystem

#3142 Verify OSD is Encrypted [deployment test]
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/M

#3090 docs: how to report test results without jenkins
  docs/usecases/reporting_tests_results_from_cluster_not_deployed_by_ocsci.rst
Labels: documentation, size/L

#3137 Fix pod name in log - test test_clone_when_full
  tests/manage/pv_services/pvc_clone/test_clone_when_pvc_full.py
Labels: size/XS, team/manage

#3068 Mcg namespace lifecycle test
  ocs_ci/ocs/bucket_utils.py
  tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle.py
Labels: Test Case, Verified, size/L, team/e2e

#2383 Update to check running pods are on same node
  tests/manage/pv_services/test_verify_rwo_using_dc_pod.py
Labels: Test Case, Verified, size/M, team/manage

#3171 using logger instead of logging module
  tests/conftest.py
Labels: size/XS, team/ecosystem

#3159 retry Prometheus query in cluster load in case of IndexError
  ocs_ci/ocs/cluster_load.py
Labels: Verified, size/XS

#3054 Skip irrelevant tests in tests/manage/storageclass/ on External mode
  tests/manage/storageclass/test_create_multiple_sc_with_different_pool_name.py
  tests/manage/storageclass/test_create_multiple_sc_with_same_pool_name.py
  tests/manage/storageclass/test_create_storageclass_with_wrong_provisioner.py
  tests/manage/storageclass/test_rbd_csi_default_sc.py
  tests/manage/storageclass/test_verify_all_fields_in_sc_yaml_with_oc_describe_sc.py
Labels: External-cluster-mode, Skip test, Verified, size/S, team/manage

#3060 Test to take snapshots of RBD Block VolumeMode PVCs
  tests/manage/pv_services/pvc_snapshot/test_rbd_block_pvc_snapshot.py
Labels: Test Case, Verified, size/L, team/manage

#3146 exec_oc_cmd: use kubeconfig from cluster dir if env. variable KUBECONFIG not set
  ocs_ci/ocs/ocp.py
Labels: size/S, team/ecosystem

#3124 RGW monitoring test
  ocs_ci/ocs/constants.py
  tests/conftest.py
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/prometheus/test_rgw.py
Labels: Verified, size/L

#3019 Update validation for node restart operations
  ocs_ci/ocs/platform_nodes.py
Labels: TestCase failing, Verified, size/M

#3169 add polarion IDs for Azure and GCP deployment
  conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
  conf/deployment/gcp/ipi_1az_rhcos_3m_3w.yaml
Labels: size/XS

#3036 AWS UPI Cluster behind Proxy - using Flexy
  conf/ocsci/aws_upi_flexy_rhcos_3m_3w_proxy.yaml
  conf/ocsci/flexy_baremetalpsi_upi.yaml
  ocs_ci/deployment/aws.py
  ocs_ci/deployment/factory.py
  ocs_ci/deployment/flexy.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/conf/flexy_default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/utility/aws.py
Labels: size/L, team/ecosystem

#3105 add OCS-2364 test case, covering BZ 1849309
  ocs_ci/utility/prometheus.py
  ocs_ci/utility/tests/test_prometheus.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_negative.py
  tests/manage/monitoring/prometheusmetrics/test_ocs_utilization.py
Labels: Test Case, Verified, size/L

#2779 Add conftest.py hook for vSphere (#2779)
  tests/e2e/scale/conftest.py
Labels: High Priority, scale, size/M

#3143 bump gevent version to 20.9.0 for ABI changes
  setup.py
Labels: Needs Testing, size/XS

#3164 Change FIO timeout for long running test
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/workloads/fio.py
Labels: Verified, performance, size/S

#3175 Change function get_ocp_version to get_running_ocp_version
  tests/conftest.py
Labels: Verified, size/XS, team/e2e

#3181 Fix usage of cluster existence check on VMware
  ocs_ci/deployment/vmware.py
Labels: size/XS, team/ecosystem

#3178 Introducing development mode option which skips the few checks like collecting version, collecting logs etc
  ocs_ci/framework/pytest_customization/ocscilib.py
  tests/conftest.py
Labels: size/S, team/ecosystem

#3059 added amq scale test
  tests/e2e/scale/test_scale_amq.py
Labels: Needs Testing, scale, size/M

#3183 fix handling of error raised during flexy execution
  ocs_ci/deployment/flexy.py
Labels: Verified, size/XS, team/ecosystem

#3184 Allow z-stream upgrade from live content
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/packagemanifest.py
Labels: Verified, size/M, team/ecosystem

#3153 Set constant limits and requests for noobaa endpoints
  ocs_ci/deployment/deployment.py
Labels: size/XS

#3188 Adding documentation for development mode
  docs/usage.md
Labels: size/XS, team/ecosystem

#3187 Fix getting wrong value from get_compute_node_names
  ocs_ci/ocs/node.py
Labels: size/S

#3157 Fixes for IBM Power
  conf/ocsci/production_powervs_upi.yaml
  ocs_ci/deployment/ibm.py
  ocs_ci/utility/utils.py
Labels: size/M

#3195 log details about prometheus query parsing error
  ocs_ci/utility/prometheus.py
Labels: Verified, size/M

#3198 Fix PVC status check in pvc_clone_factory
  tests/conftest.py
Labels: size/XS

#3197 Fixed how we determine method for retrieving compute node names based on platform
  ocs_ci/ocs/node.py
Labels: Verified, bug, team/ecosystem

#3122 External RHCS cluster Utilities for osd disruptive operations
  ocs_ci/ocs/ceph.py
  ocs_ci/ocs/external_ceph.py
  ocs_ci/ocs/utils.py
Labels: Verified, size/XXL, team/ecosystem

#3044 docs: running tests on non ocs-ci cluster
  .gitignore
  docs/usecases/running_tests_on_cluster_not_deployed_by_ocsci.rst
Labels: documentation, platforms, size/L

#3176 disable test_ceph_rbd_metrics_available test
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
Labels: size/XS

#3191 Fix the NB sanity test to not run too many iterations
  tests/sanity_helpers.py
Labels: High Priority, Verified, size/XS

#2787 removed workaround for OSD timeout after upgrade
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, size/XS

#2954 Add initial version of scale test for one million cephfs files.
  tests/e2e/scale/test_cephfs_many_files.py
Labels: Needs Testing, scale, size/L

#3192 Fix cluster load fixture
  ocs_ci/ocs/cluster_load.py
  tests/conftest.py
Labels: Needs Testing, size/M, team/ecosystem

#3207 fix indentation of if conditions blocks in vmware.py
  ocs_ci/deployment/vmware.py
Labels: size/S, team/ecosystem

#3201 Add upgrade OCP version CLI options
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: size/M, team/ecosystem

#3155 Revert "Skip relevant pv_services test cases on IBM cloud due to Bug 1871314 and 1871315"
  tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
  tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
  tests/manage/pv_services/test_pvc_assign_pod_node.py
  tests/manage/pv_services/test_raw_block_pv.py
  tests/manage/pv_services/test_verify_rwo_using_multiple_pods.py
Labels: size/M

#3167 force cluster destroy - vsphere platform
  ocs_ci/cleanup/vsphere/cleanup.py
  ocs_ci/utility/aws.py
  setup.py
Labels: Verified, size/L, team/ecosystem

#3210 Added generic file for scale tests to override must gather timeout
  conf/ocsci/scale.yaml
Labels: size/XS, team/ecosystem

#3194 Test cases for BZ #1836299 and #1873162
  ocs_ci/ocs/constants.py
  tests/manage/monitoring/prometheus/test_hpa.py
  tests/manage/monitoring/prometheusmetrics/test_mcg_hpa.py
Labels: Test Case, Verified, size/M, team/e2e

#3213 Ignore rook-ceph-detect-version pods in wait_for_storage_pods()
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/XS

#3228 Couchbase teardown failure fix
  ocs_ci/ocs/couchbase.py
  ocs_ci/ocs/pillowfight.py
Labels: Verified, size/S, team/e2e

#3190 Default snapshot class name in external mode
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pvc.py
  tests/conftest.py
Labels: Verified, size/S

#3225 Changing default osd size to 100
  ocs_ci/ocs/defaults.py
Labels: Verified, size/XS, team/ecosystem

#3231 Enable rotational disks for LSO PSI deployment
  conf/ocsci/flexy_baremetalpsi_upi.yaml
  conf/ocsci/lso_enable_rotational_disks.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
Labels: size/S

#3233 Adding extra repos for RHEL installation for vsphere
  ocs_ci/repos/ocp_4_6.repo
Labels: Verified, size/S, team/ecosystem

#2440 Improve mcg deduplication and reduction tests
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/resources/mcg.py
  tests/ecosystem/upgrade/test_noobaa.py
  tests/manage/mcg/test_write_to_bucket.py
Labels: Verified, size/M, team/manage
