Repository red-hat-storage/ocs-ci, pull requests merged in 2020-12, with the labels that each got.

#3199 Story/Flow based test scenario for pgsql snapshot and clone
  ocs_ci/ocs/flowtest.py
  ocs_ci/ocs/resources/pod.py
  tests/conftest.py
  tests/e2e/flowtest/pvc_snapshot_and_clone/test_pgsql_pvc_snapshot_and_clone_with_base_operation.py
Labels: Test Case, Verified, size/L, team/e2e

#3173 Fixes: unable to locate templates "eap-cd-basic-s2i" on s390s platform.
  ocs_ci/ocs/registry.py
Labels: Verified, bug, size/M, team/e2e

#3273 PVC snapshot, clone, expansion combination test
  tests/manage/pv_services/test_expansion_snapshot_clone.py
Labels: Test Case, Verified, size/L, team/manage

#3425 Namespace bucket tier2 and tier3 tests
  ocs_ci/ocs/bucket_utils.py
  tests/manage/mcg/test_namespace.py
Labels: Verified, size/L

#3447 Jenkins: Optionally set OCP version
  .functional_ci_setup.py
  ocs_ci/framework/main.py
Labels: size/XS

#3446 Improve in approving CSRs fro vSphere
  ocs_ci/utility/csr.py
  ocs_ci/utility/vsphere.py
Labels: Verified, size/M, team/ecosystem

#3427 Enable infra_nodes flag in production yaml
  conf/deployment/aws/ipi_3az_rhcos_3m_3w_3i.yaml
Labels: Verified, size/XS, team/ecosystem

#3450 Fix GCP and Azure prod config files
  conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
  conf/deployment/gcp/ipi_1az_rhcos_3m_3w.yaml
Labels: size/XS, team/ecosystem

#3412 update integration with flexy
  ocs_ci/deployment/flexy.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/L, team/ecosystem

#3459 Remove 'app' label in case of infra nodes
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/machine.py
Labels: size/XS, team/ecosystem

#3469 Ignore oc debug pods in leftover checks
  ocs_ci/utility/environment_check.py
Labels: Verified, size/XS

#3472 Change default instance type to m5.4xlarge
  conf/ocsci/allow_lower_instance_requirements.yaml
  conf/ocsci/aws_ipi.yaml
  conf/ocsci/aws_lower_resource_reqs.yaml
  conf/ocsci/aws_upi.yaml
  conf/ocsci/vsphere_upi.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-aws-upi.yaml.j2
Labels: Verified, size/M, team/ecosystem

#3466 Document all known configuration settings
  conf/README.md
Labels: documentation, size/L, team/ecosystem

#3012 Noobaa scale: Writing 1M objects to a single bucket
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/hsbench.py
  ocs_ci/templates/app-pods/golang.yaml
  ocs_ci/templates/workloads/hsbench/hsbench_obj.yaml
  tests/e2e/scale/noobaa/test_hsbench.py
Labels: Verified, scale, size/L

#3478 must gather, delete 'rook-ceph-mon-a.yaml'
  ocs_ci/ocs/must_gather/const_must_gather.py
Labels: size/XS

#3482 Change the codespeed Error to Warning for non RH runs
  ocs_ci/utility/performance_dashboard.py
Labels: size/XS

#3179 Checking space reclaimed post deletion of Elasticsearch PVC
  ocs_ci/helpers/helpers.py
  ocs_ci/utility/uninstall_openshift_logging.py
  tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Labels: Customer defects, Verified, size/L, team/e2e

#3430 add without_presistent_monitoring.yam conf file
  conf/examples/without_presistent_monitoring.yaml
Labels: size/XS

#3474 Production yaml:Infra deployment on vsphere
  conf/deployment/vsphere/upi_1az_rhcos_vmfs_3m_3w_3i.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_3i.yaml
Labels: size/M, team/ecosystem

#3397 use delete reclaim policy for GCP storageclass
  ocs_ci/templates/ocs-deployment/storageclass.gcp.yaml
Labels: Verified, platforms, size/XS

#3486 Fix operator bundle image
  ocs_ci/templates/ocs-deployment/stageImageContentSourcePolicy.yaml
Labels: Verified, size/XS, team/ecosystem

#3287 disable workaround from deploy-with-olm.yaml
  ocs_ci/deployment/deployment.py
Labels: Verified, size/S, team/ecosystem

#3399 move Azure baseDomainResourceGroupName to conf file
  conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
  ocs_ci/templates/ocp-deployment/install-config-azure-ipi.yaml.j2
Labels: platforms, size/XS

#3409 Adding production configurations for 32RAM & 8VCPU Nodes & 16RAM & 4VCPU Masters
  conf/deployment/aws/ipi_1az_rhcos_lowerreq_3m_3w.yaml
  conf/deployment/aws/ipi_3az_rhcos_lowerreq_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_lowerreq_vmfs_3m_3w.yaml
Labels: size/M

#3445 New test : test_pvc_bulk_clone_performance.py and fixed test test_pvc_clone_performance.py
  ocs_ci/helpers/helpers.py
  ocs_ci/helpers/performance_lib.py
  ocs_ci/ocs/scale_lib.py
  tests/e2e/performance/test_pvc_bulk_clone_performance.py
  tests/e2e/performance/test_pvc_clone_performance.py
Labels: size/L

#3259 Update the test 'test_recovery_from_volume_deletion' to be compatible with OCP 4.6
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/L

#3470 Unskipping 'list' ops & added a workaround for 'markers' for azure res.
  tests/e2e/lifecycle/mcg/test_mcg_namespace_s3_ops.py
Labels: MCG, Verified, size/L

#3491 Update the AWSCLI pod creation to support disconnected clusters
  tests/conftest.py
Labels: MCG, Verified, size/XS

#3496 replace fedora image by quay.io/ocsci/fedora
  ocs_ci/helpers/helpers.py
Labels: Verified, size/XS, team/ecosystem

#3426 Deploying ocs if storage disks increases
  conf/ocsci/production_powervs_upi.yaml
  ocs_ci/deployment/deployment.py
Labels: Verified, size/XS

#3487 Improve CLDMGR docs
  ocs_ci/ocs/resources/cloud_uls.py
Labels: MCG, Verified, size/S

#3196 bug 1873938, Unexpected PV is created after node reboot
  ocs_ci/helpers/helpers.py
  tests/manage/z_cluster/nodes/test_nodes_restart.py
Labels: Verified, size/M

#3501 add polarion id mark
  tests/manage/z_cluster/nodes/test_nodes_restart.py
Labels: Verified, size/XS

#3364 Add RGW metrics test
  ocs_ci/ocs/metrics.py
  tests/manage/monitoring/prometheusmetrics/test_rgw.py
Labels: Verified, size/M

#3497 Implement IBM Cloud deployment
  conf/ocsci/ibm_cloud_cluster_conf.yaml
  conf/ocsci/ibm_cloud_upi.yaml
  conf/ocsci/upstream-must-gather.yaml
  docs/index.rst
  docs/supported_platforms.md
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/factory.py
  ocs_ci/deployment/ibmcloud.py
  ocs_ci/deployment/ocp.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/ocp.py
  ocs_ci/templates/ocs-deployment/catalog-source.yaml
  ocs_ci/templates/ocs-deployment/ocs-secret.yaml
  ocs_ci/utility/ibmcloud.py
Labels: Needs Deployment Testing, platforms, size/XL, team/ecosystem

#3499 Invalid node name - compute-0
  tests/e2e/scale/test_cephfs_many_files.py
Labels: size/XS

#3504 device replacement, verify new device is encrypted
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: size/M

#3503 updating ocs-olm-operator to ocs-registry in default_config
  ocs_ci/framework/conf/default_config.yaml
Labels: size/XS, team/ecosystem

#3508 email report enhancement
  ocs_ci/utility/utils.py
Labels: Verified, size/M, team/ecosystem

#3510 generate node names in case of empty resource pool
  ocs_ci/cleanup/vsphere/cleanup.py
Labels: Verified, size/S, team/ecosystem

#3505 add capacity, verify all relevant osds are encrypted
  ocs_ci/ocs/resources/storage_cluster.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
Labels: Verified, size/M

#3513 node replacement test, verify the new osd is encrypted
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
  tests/manage/z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
Labels: Verified, size/S

#3512 add Logs URL to html test report and email report
  conf/README.md
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/framework/pytest_customization/reports.py
  ocs_ci/utility/utils.py
Labels: Verified, size/M, team/ecosystem

#3517 Don't collect noobaa DB dump if cluster version is 4.7
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: Verified, size/S

#3528 Adding retries to the function
  ocs_ci/ocs/amq.py
  tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
Labels: Verified, size/S

#3521 Mirror the AWSCLI image to Quay
  ocs_ci/templates/app-pods/awscli.yaml
Labels: MCG, Verified, size/XS

#3402 update setup.py to match released version
  docs/index.rst
  docs/release_guidelines.md
  setup.py
Labels: size/S

#3531 Flow based test scenario for pgsql snapshot and clone
  tests/e2e/flowtest/pvc_snapshot_and_clone/test_pgsql_pvc_snapshot_and_clone.py
Labels: Test Case, Verified, size/M, team/e2e

#3481 Cldmgr unique secret names
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/resources/backingstore.py
  ocs_ci/ocs/resources/cloud_manager.py
Labels: MCG, Verified, size/S

#3532 Don't fail deployment if we have more PV's
  ocs_ci/deployment/deployment.py
Labels: Verified, size/S

#3493 Use external mode sc in workloads if the deployment type is independent mode
  ocs_ci/ocs/amq.py
  ocs_ci/ocs/couchbase.py
  ocs_ci/ocs/jenkins.py
  ocs_ci/ocs/pgsql.py
Labels: Verified, size/M, team/e2e

#3556 Bump version to 4.6.0
  setup.py
Labels: size/XS, team/ecosystem

#2895 Fix tier1 test failures in tests/manage/z_cluster/ on External mode
  ocs_ci/ocs/must_gather/const_must_gather.py
  ocs_ci/ocs/must_gather/must_gather.py
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
  tests/manage/z_cluster/test_ceph_default_values_check.py
  tests/manage/z_cluster/test_must_gather.py
Labels: External-cluster-mode, Verified, size/M, team/manage

#3552 Use the correct NB DB pod label for 4.7
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/utils.py
  tests/manage/mcg/test_mcg_resources_disruptions.py
Labels: MCG, Verified, size/S

#3542 Test PVC resize of cloned and restored PVC
  tests/e2e/pvc_snapshot_and_clone/test_cloned_and_restored_pvc_resize.py
Labels: Test Case, Verified, size/L, team/e2e

#3560 Increase wait_time of measure_pvc_creation_time_bulk call
  tests/e2e/scale/test_pvc_creation_deletion_scale.py
Labels: size/XS

#3553 Add oc_output files to must gather test lists
  ocs_ci/ocs/must_gather/const_must_gather.py
Labels: Verified, size/M

#3571 Allow the MCG health check to fail
  ocs_ci/ocs/resources/mcg.py
Labels: MCG, Verified, size/XS, workaround

#3576 Fixing the API version in the ECK yaml file
  ocs_ci/templates/app-pods/eck.1.3.1-all-in-one.yaml
Labels: bug, performance, size/XS

#3520 Update the test 'test_recovery_from_volume_deletion' to be compatible with vSphere LSO
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/vsphere.py
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/L

#3437 Parameterize multicloud tests
  ocs_ci/ocs/resources/bucketclass.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/objectbucket.py
  tests/conftest.py
  tests/manage/mcg/test_bucket_creation.py
  tests/manage/mcg/test_bucket_deletion.py
  tests/manage/mcg/test_object_integrity.py
  tests/manage/mcg/test_pv_pool.py
  tests/manage/mcg/test_write_to_bucket.py
Labels: MCG, Verified, size/L

#3515 Use external RBD storageclass for NooBaa PV backingstore creation in external mode
  ocs_ci/ocs/resources/backingstore.py
Labels: MCG, Verified, size/S

#3490 Add methods to start azure node
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/azure_utils.py
Labels: Verified, size/M

#3483 Add methods to stop azure nodes
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/azure_utils.py
Labels: Verified, size/M

#3544 Verify thorough PV backingstore deletion
  ocs_ci/ocs/resources/backingstore.py
Labels: MCG, Verified, size/M

#3537 Verify ULS state upon creation and deletion
  ocs_ci/ocs/resources/cloud_manager.py
Labels: MCG, Medium Priority, Verified, size/M

#3587 Handle EndpointConnectionError when trying to retrieve auth.yaml
  ocs_ci/ocs/resources/cloud_manager.py
Labels: MCG, Verified, size/XS

#3534 Look for the correct RGW secret name in external mode clusters
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/rgw.py
Labels: Verified, size/S

#3541 Adding test multiple sc with replica 2 and 3 with IO
  ocs_ci/ocs/exceptions.py
  tests/manage/storageclass/test_create_2sc_at_once_with_io.py
Labels: Verified, size/L

#3546 Disruptive upgrade test: reboot OSD during upgrade.
  ocs_ci/ocs/disruptive_operations.py
  ocs_ci/ocs/ocs_upgrade.py
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, size/M

#3596 added acceptance related changes and verify
  ocs_ci/ocs/node.py
  tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
Labels: size/S

#3597 Skipping mcg related tests for openshift dedicated acceptance testing and verify
  conf/ocsci/openshift_dedicated.yaml
  ocs_ci/framework/pytest_customization/marks.py
  tests/manage/mcg/test_bucket_creation.py
  tests/manage/mcg/test_bucket_deletion.py
  tests/manage/mcg/test_write_to_bucket.py
Labels: size/S

#3594 Skip tests where cloud credentials are missing
  ocs_ci/ocs/resources/cloud_uls.py
Labels: MCG, Verified, size/S

#3543 Skipping mcg related tests for openshift dedicated acceptance testing
  conf/ocsci/openshift_dedicated.yaml
  ocs_ci/framework/pytest_customization/marks.py
  tests/manage/mcg/test_bucket_creation.py
  tests/manage/mcg/test_bucket_deletion.py
  tests/manage/mcg/test_write_to_bucket.py
Labels: Verified, size/S

#3586 Acceptance test related changes for openshift dedicated
  ocs_ci/ocs/node.py
  tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
Labels: Verified, size/S

#3595 Move RPLogHandler import to prevent PytestAssertRewriteWarning
  ocs_ci/framework/pytest_customization/reports.py
Labels: Verified, size/XS

#3591 Handle GCP ULS deletion race condition
  ocs_ci/ocs/resources/cloud_manager.py
Labels: MCG, Verified, size/XS

#3592 Test multiple storageclasses data deletion with compression and replication
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/exceptions.py
  tests/manage/storageclass/test_multiple_sc_comp_rep_data_delete.py
Labels: Verified, size/L

#3603 Check if the new node with OCS storage label
  ocs_ci/ocs/node.py
Labels: Verified, size/M

#3572 Creating the QPAS helper library
  ocs_ci/helpers/performance_lib.py
Labels: Verified, performance, size/M

#3602 Replace logger.warn() with warning()
  tests/conftest.py
Labels: MCG, size/XS

#3550 Print OBC YAML and `oc describe` if it fails to bind on creation
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/objectbucket.py
  tests/conftest.py
Labels: MCG, Verified, size/M

#3555 Adding fio test on compressed volume
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/defaults.py
  ocs_ci/templates/workloads/fio/benchmark_fio_cmp.yaml
  tests/e2e/performance/test_fio_benchmark.py
Labels: Verified, performance, size/XL
