Repository red-hat-storage/ocs-ci, pull requests merged in 2020-02, with the labels that each got.

#1346 Verify osd tree output and ensure it have device set PVC names
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/pvc.py
  setup.py
Labels: Verified, enhancement

#1419 Add 4.3 latest tags
  conf/ocsci/ocs-4.3.yaml
  ocs_ci/ocs/constants.py
Labels: Verified

#1424 Added --ocs-version argument for specifying ocs version from CLI
  conf/ocs_version/ocs-4.2.yaml
  conf/ocs_version/ocs-4.3.yaml
  ocs_ci/framework/main.py
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/constants.py
Labels: Needs Deployment Testing, team/ecosystem

#1422 Include sync_guest_time for RHEL nodes in vSphere platform
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem

#1427 Fix ocs-version parameter
  conf/ocs_version/ocs-4.2.yaml
  conf/ocs_version/ocs-4.3.yaml
  docs/usage.md
  ocs_ci/framework/main.py
Labels: Needs Deployment Testing

#1428 Add config for 4.3 GA OCP version
  conf/ocsci/ocp_4.2_ga_version.yaml
  conf/ocsci/ocp_4.3_ga_version.yaml
Labels: team/ecosystem

#1433 Add new 4.3 coreoes image for 4.3 ocp conf
  conf/ocsci/ocp-4.2-config.yaml
  conf/ocsci/ocp-4.3-config.yaml
Labels: team/ecosystem

#1417 Include memory option for master and computer nodes individually
  ocs_ci/deployment/vmware.py
  ocs_ci/templates/ocp-deployment/terraform.tfvars.j2
Labels: Verified, team/ecosystem

#1429 Verify CSI snapshotter sidecar container is not present
  ocs_ci/ocs/resources/ocs.py
Labels: Verified, enhancement

#1443 Move ocs-ci to use OCP/OCS 4.3 as default
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, team/ecosystem

#1437 Change ManagementState for image registry for non cloud platforms
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/registry.py
Labels: Verified, team/ecosystem

#1435 add capacity message for ocs 4.3
  tests/manage/monitoring/prometheus/test_capacity.py
Labels: Verified, team/manage

#1447 Update 4.2 config to use latest-4.2 tag
  conf/ocs_version/ocs-4.2.yaml
  ocs_ci/utility/utils.py
Labels: team/ecosystem

#1454 Fix osd tree schema- remove maximum and minimum value for crush_weight
  ocs_ci/ocs/constants.py
Labels: High Priority, Verified

#1456 Deploy toolbox pod via ocs for 4.3
  ocs_ci/ocs/utils.py
Labels: Verified, team/ecosystem

#1441 Run gather bootstrap if recommended after OCP install fail
  ocs_ci/deployment/aws.py
  ocs_ci/deployment/vmware.py
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/utils.py
  ocs_ci/utility/bootstrap.py
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem

#1458 Ability to cleanup AWS clusters in a periodic way
  ocs_ci/cleanup/aws/cleanup.py
  ocs_ci/cleanup/aws/defaults.py
  setup.py
Labels: Verified, size/M

#1414 Registry Testcase to perform image push pull.
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/registry.py
  tests/e2e/registry/test_registry_image_push_pull.py
Labels: Test Case, Verified, team/e2e

#1457 Adding post destroy checks for vSphere platform
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/vsphere.py
Labels: Verified, team/ecosystem

#690 OCS-651, Respin the elasticsearch pod and check for logs in .operations index
  ocs_ci/ocs/constants.py
  tests/e2e/logging/test_openshift-logging.py
Labels: Test Case, Verified, team/e2e

#1408 Verify pool crush rule is with "type": "zone"
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/ocs.py
Labels: Verified, enhancement

#1448 Enable UI testing
  docs/getting_started.md
  docs/usage.md
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/openshift_console.py
  tests/ui/test_ui.py
Labels: Verified, team/ecosystem

#1467 AWS cleanup: skip cloudformation VPCs
  ocs_ci/cleanup/aws/cleanup.py
Labels: Verified

#1478 skip test_ceph.py test cases
  tests/manage/monitoring/prometheus/test_ceph.py
Labels: Skip test

#1471 Rely on CSV for fetching ocs version info
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/utility/utils.py
Labels: Verified

#1444 Decorator to skip tests based on ocs version
  docs/writing_tests.md
  ocs_ci/framework/testlib.py
Labels: Verified

#1475 Don't fail when channel info is missing because of issues/1338
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/packagemanifest.py
  ocs_ci/ocs/resources/test_packagemanifest.py
Labels: Needs Deployment Testing

#1488 Change RHCOS 4.2 image to the new one
  conf/ocsci/ocp-4.2-config.yaml
Labels: Verified

#1403 pre-pull container images on all nodes during pod creation
  tests/helpers.py
Labels: Verified

#1413 Test to measure pod start time
  tests/e2e/test_pvc_attachtime.py
  tests/helpers.py
Labels: Verified

#1459 Testcase to verify noobaa status output
  ocs_ci/ocs/defaults.py
  tests/manage/mcg/test_verify_noobaa_status.py
Labels: Test Case, Verified, team/manage

#1451 Function to get osd utilization and validate the osd utilization
  ocs_ci/ocs/cluster.py
Labels: team/e2e

#1489 OCP 4.4
  conf/ocsci/ocp-4.4-config.yaml
Labels: Verified

#1421 Increasing timeout and fixing JSONDecoderError
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/monitoring.py
  tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
Labels: bug

#1369 Modifed dc_pod_factory to have node selection and run_io_bg to include fedora dc pod
  ocs_ci/ocs/resources/pod.py
  tests/conftest.py
Labels: Verified

#1481 AWS cleanup: Enable treatment of different prefixes with different max running hours
  ocs_ci/cleanup/aws/cleanup.py
  ocs_ci/cleanup/aws/defaults.py
Labels: Verified

#1470 Ensure Nonetype values are not added to the master_ips list for gathering bootstrap data
  ocs_ci/utility/bootstrap.py
Labels: Verified, team/ecosystem

#1476 Add polarion ID from config to test_deployment
  conf/examples/polarion_id.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/utility/reporting.py
  tests/ecosystem/deployment/test_deployment.py
Labels: Verified, team/ecosystem

#1379 Adding test for rgw pod restart in mcg_write_to_bucket
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/mcg/conftest.py
  tests/manage/mcg/helpers.py
  tests/manage/mcg/test_bucket_creation.py
  tests/manage/mcg/test_bucket_deletion.py
  tests/manage/mcg/test_write_to_bucket.py
Labels: Test Case, Verified, team/manage

#1495 Move 4.2 to use RC builds as default
  conf/ocs_version/ocs-4.2.yaml
Labels: team/ecosystem

#1502 Organizes tests in E2E
  tests/e2e/performance/test_io_performance.py
  tests/e2e/performance/test_pvc_attachtime.py
  tests/e2e/performance/test_pvc_creation_performance.py
  tests/e2e/performance/test_pvc_deletion_performance.py
  tests/e2e/performance/test_vdbench_workload.py
  tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
  tests/e2e/scale/test_pv_scale_ocs_create_delete_pvcs.py
  tests/e2e/workloads/test_amq_streamer_creation.py
  tests/e2e/workloads/test_jenkins_simulation.py
  tests/e2e/workloads/test_pgsql.py
  tests/e2e/workloads/test_pgsql_pod_respin.py
  tests/e2e/workloads/test_small_file_workload.py
Labels: Skip test

#1501 Adds basic test for Logging, Monitoring, Registry as tier1
  tests/e2e/logging/test_openshift-logging.py
  tests/e2e/registry/test_registry_image_push_pull.py
Labels: Skip test, team/e2e

#1484 Create a large sized PVC while IO in progress (Bug 1748939)
  ocs_ci/ocs/resources/pod.py
  tests/manage/pv_services/test_create_large_sized_pvc_while_io_in_progress.py
Labels: Test Case, Verified, team/manage

#1507 Fix must gather image tag
  conf/ocs_version/ocs-4.2.yaml
  conf/ocs_version/ocs-4.3.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/utils.py
Labels: team/ecosystem

#1496 Allow upgrade between versions like 4.2 -> 4.3
  conf/ocs_version/ocs-4.2.yaml
  conf/ocsci/upgrade.yaml
  conf/ocsci/upgrade_to_next_build.yaml
  docs/upgrade.md
  docs/usage.md
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/__init__.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/utils.py
  ocs_ci/utility/reporting.py
  ocs_ci/utility/utils.py
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, team/ecosystem

#1510 Fix to verify rgw pod is not present on aws platform
  ocs_ci/ocs/resources/mcg.py
Labels: High Priority, Verified, bug

#1514 Fix in getting OCP version when we have batch version
  ocs_ci/utility/utils.py
Labels: Needs Deployment Testing, team/ecosystem

#1530 fix condition in supported_configuration fixture
  tests/conftest.py
Labels: bug

#1521 Issue 1519 test decorator
  tests/manage/pv_services/test_pvc_disruptive.py
Labels: Verified, team/manage

#1536 Add timeout for verifying image/subvolume deletion in testcase
  tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
Labels: Verified, enhancement

#1549 Skip test case due to #1547
  ocs_ci/ocs/registry.py
  tests/e2e/registry/test_registry_image_push_pull.py
Labels: High Priority, team/e2e

#1538 Create custom machineset for creating nodes with different instance type and node scale
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/machine.py
  ocs_ci/templates/openshift-infra/machine-set.yaml
Labels: Verified, team/e2e

#1518 Revert "BZ 1790558 workaround"
  pytest.ini
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
Labels: Verified

#1539 ocs_install_verification place change
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/ecosystem/deployment/test_deployment.py
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified

#1460 Function to create custom image locally and test to validate
  ocs_ci/ocs/exceptions.py
  tests/e2e/workloads/test_pod_from_registry.py
  tests/helpers.py
Labels: Verified, team/e2e

#1540 Removes the extra disks from vSphere environment
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/vsphere.py
Labels: Verified, team/ecosystem

#1528 Added options to skip interactive prompts during AWS cleanup
  ocs_ci/cleanup/aws/cleanup.py
Labels: team/ecosystem

#1527 Deployment configuration polarion IDs
  conf/deployment/aws/ipi_1az_rhcos_3m_3w.yaml
  conf/deployment/aws/ipi_3az_rhcos_3m_3w.yaml
  conf/deployment/aws/upi_1az_rhcos_3m_3w.yaml
  conf/deployment/aws/upi_1az_rhel7_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhcos_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhel7_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vmfs_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_3m_3w.yaml
Labels: team/ecosystem

#1543 Fix issue with leftover must-gather pod
  ocs_ci/ocs/constants.py
  ocs_ci/utility/environment_check.py
Labels: Needs Testing, enhancement

#1555 Fix upgrade tag for specific image
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, team/ecosystem

#1562 Add new 4.3.1 to repo map for OCP RHEL
  ocs_ci/ocs/constants.py
Labels: Verified

#1515 Add ceph health check before doing node drain
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified
