Repository red-hat-storage/ocs-ci, pull requests merged in 2021-09, with the labels that each got.

#4714 GSS bz 1974343, Verify expected log exist after upgrade
  ocs_ci/ocs/resources/pod.py
  tests/ecosystem/upgrade/test_resources.py
Labels: Verified, size/M

#4792 Add polarion ID to scale tests
  tests/e2e/scale/test_cephfs_many_files.py
  tests/e2e/scale/test_osd_node_balancing.py
Labels: Test Case, size/S, scale

#3888 Automates BZ OCS podDisruptionBudget prevents successful OCP upgrades
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  tests/ecosystem/upgrade/test_upgrade.py
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
  tests/manage/z_cluster/upgrade/test_check_pdb_post_upgrade.py
Labels: Verified, team/e2e, size/L, upgrade, Customer defects

#4763 update ECK version to 1.7
  ocs_ci/ocs/elasticsearch.py
  ocs_ci/templates/app-pods/eck.1.6.0-all-in-one.yaml
  ocs_ci/templates/app-pods/esq.yaml
Labels: size/XXL

#4774 Skip UI tests on openshift dedicated ODF-managed service
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: enhancement, Verified, size/S, ui_testing

#4789 change the condition of waiting for the OSD pod in the test "test_automated_recovery_from_stopped_node_and_start"
  ocs_ci/helpers/helpers.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: size/L

#4794 "test_multiple_pvc_deletion_measurement_performance" test case impro…
  ocs_ci/helpers/helpers.py
  tests/e2e/performance/test_pvc_creation_deletion_performance.py
Labels: size/S

#4706 Skip ui_deployment on cluster with Infra nodes
  ocs_ci/ocs/ui/helpers_ui.py
Labels: Verified, size/S

#4647 Align ocs-ci to ODF changes
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/defaults.py
  ocs_ci/templates/ocs-deployment/storagesystem_odf.yaml
  ocs_ci/templates/ocs-deployment/subscription_odf.yaml
Labels: Verified, team/ecosystem, size/M, Merge As Is (Don't Squash)

#4799 Force delete storage when destroy IBM Cloud cluster
  ocs_ci/utility/ibmcloud.py
Labels: team/ecosystem, size/XS

#4528 Skip mcg related test on openshift dedicated platform
  tests/manage/mcg/conftest.py
Labels: Verified, size/S, Managed Services

#4791 Fixed certificate issue when getting hsbench package.
  ocs_ci/ocs/hsbench.py
Labels: Verified, size/XS, scale

#4803 Skip tests if flexy deployment
  ocs_ci/framework/pytest_customization/marks.py
  tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
  tests/manage/z_cluster/cluster_expansion/test_verify_ceph_csidriver_runs_on_non_ocs_nodes.py
Labels: Verified, team/ecosystem, size/S, lgtm

#4677 Test RBD Block volume mode RWX PVC
  tests/conftest.py
  tests/manage/pv_services/test_rbd_rwx_pvc.py
Labels: Test Case, Needs Testing, Verified, team/manage, size/L, Squad/Green, lgtm

#4779 Configure proxy server for Chrome browser if required
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/templates/ui/chrome-proxy-extension-background.js.j2
  ocs_ci/templates/ui/chrome-proxy-extension-manifest.json.j2
  ocs_ci/utility/flexy.py
Labels: Verified, team/ecosystem, size/L

#4816 Check the osd node name exist in the node replacement verification steps
  ocs_ci/ocs/node.py
Labels: Verified, size/S, lgtm

#4795 PR to fix scale pvc expand test
  ocs_ci/ocs/resources/objectconfigfile.py
  ocs_ci/ocs/scale_lib.py
  tests/e2e/scale/test_scale_pvc_expand.py
Labels: bug, Test Case, size/L, scale, lgtm

#4810 Re-try cluster on PVC validation
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: Needs Testing, team/ecosystem, size/M, lgtm

#4823 Increase max operations per run to 100 for stale workflow
  .github/workflows/stale.yml
Labels: team/ecosystem, size/XS, lgtm

#4806 Modify PVC Resize UI
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/pvc_ui.py
  ocs_ci/ocs/ui/views.py
  tests/ui/test_pvc_ui.py
Labels: Verified, size/M, ui_testing

#4821 Add BM Config Files for OCP 4.9
  ocs_ci/templates/ocp-deployment/rhcos_images.yaml
Labels: Verified, size/XS

#4828 Patch the benchmark job for timeout different from default of 1 Hour
  ocs_ci/templates/workloads/fio/benchmark_fio.yaml
  ocs_ci/templates/workloads/smallfile/SmallFile.yaml
Labels: bug, High Priority, size/XS, performance

#4825 Fix function which wait for benchmark to finish
  ocs_ci/ocs/perftests.py
Labels: size/S, performance

#4801 Fix condition in wait_for_storage_pods() to ignore rook-ceph-detect-version pod
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/M, lgtm

#4782 Move pvc_snapshot_and_clone folder to workloads dir
  ocs_ci/ocs/resources/pvc.py
  tests/conftest.py
  tests/e2e/lifecycle/pvc_clone/test_pgsql_pvc_clone.py
  tests/e2e/lifecycle/pvc_snapshot/test_pgsql_pvc_snapshot.py
  tests/e2e/performance/test_pvc_clone_performance.py
  tests/e2e/workloads/pvc_snapshot_and_clone/test_cloned_and_restored_pvc_resize.py
  tests/e2e/workloads/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py
  tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py
Labels: Verified, size/M, lgtm

#4771 Cluster prefix match fix
  ocs_ci/deployment/aws.py
  ocs_ci/deployment/cloud.py
  ocs_ci/utility/deployment.py
  ocs_ci/utility/tests/test_deployment_utils.py
Labels: Verified, team/ecosystem, size/M, lgtm

#4817 VMware ipi support for scale tests
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/scale_lib.py
  ocs_ci/templates/openshift-infra/machineset-vmware.yaml
  tests/e2e/scale/test_scale_3_OCS_worker_nodes_and_1500_PVCs.py
Labels: enhancement, Needs Testing, size/L, scale

#4830 Include odf chnages in external cluster deployment
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/S

#4815 Verify noobaa-operator during odf deployment
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/defaults.py
Labels: Verified, team/ecosystem, size/XS

#4829 disabling master machine set for AWS UPI deployment
  ocs_ci/deployment/aws.py
Labels: Verified, team/ecosystem

#4838 Use json instead of hcl for reading terraform state file
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/XS

#4837 fix for bucket policy tests in 4.9
  ocs_ci/ocs/resources/bucket_policy.py
Labels: Verified, size/S

#4820 Quay test on 4.6
  tests/e2e/workloads/quay/test_quay_operator.py
Labels: Verified, team/e2e, size/XS

#4848 Add support for upgrade to ODF 4.9
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/XS

#4843 Add skip if marker for ROSA platform
  ocs_ci/framework/pytest_customization/marks.py
Labels: enhancement, Verified, size/XS

#4844 Skip mcg related test on ROSA platform
  tests/manage/mcg/conftest.py
Labels: Needs Testing, size/XS, Managed Services

#4845 Skip UI tests on ROSA platform
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: enhancement, size/XS, ui_testing, Managed Services

#4609 Add multus network check to post install verification
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/M

#4851 log marker args instead of Marker
  tests/conftest.py
Labels: team/ecosystem, size/XS

#4849 Verify StorageSystem status
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/S

#4852 Enhancement to "test_pv_scale_and_respin_ceph_pods" test with additional resource types
  tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Labels: size/S

#4854 Add Polarion ID to vSphere deployment behind proxy
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_proxy.yaml
Labels: size/XS

#4713 Add test case for snapshot and restore of encrypted RBD PVCs
  ocs_ci/utility/kms.py
  tests/conftest.py
  tests/manage/pv_services/pvc_snapshot/test_encrypted_rbd_pvc_snapshot.py
Labels: Test Case, Verified, size/L, Squad/Green

#4860 Skip RBD thick SC verification in 4.9
  ocs_ci/ocs/resources/storage_cluster.py
Labels: High Priority, size/XS

#4808 Restore snapshot to different pool
  tests/manage/pv_services/pvc_snapshot/test_restore_snapshot_using_different_sc.py
Labels: Verified, team/manage, size/M, Squad/Green

#4832 Tests to verify PVC snapshot feature when snapshotclass deleted
  tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot_when_snapshotclass_deleted.py
Labels: Verified, size/L, Customer defects

#4846 Add openshift dedicated platform in CLOUD_PLATFORMS constants list
  ocs_ci/ocs/constants.py
Labels: enhancement, size/XS, Managed Services

#4869 Checks for odf-console and odf-operator-controller-manager
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/S

#4870 Adding OCP 4.10 config files
  ocs_ci/framework/conf/ocp_version/ocp-4.10-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.10-upgrade.yaml
Labels: Needs Deployment Testing, team/ecosystem, size/S

#4861 Fix for get_ceph_default_replica returning None value.
  ocs_ci/ocs/cluster.py
  tests/e2e/performance/test_pvc_snapshot_performance.py
Labels: size/XS

#4835 PR to fix scale_12_OCS worker nodes OSD
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/scale_lib.py
  tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
Labels: Test Case, High Priority, Verified, size/M, scale

#4811 Skip test_verify_rwo_using_replicated_pod if all pods are created on the same node
  tests/manage/pv_services/test_verify_rwo_using_dc_pod.py
Labels: Verified, team/manage, size/M, Squad/Green

#4594 Test case - Verify RBD trash purge command if the RBD PVCs have snapshots
  tests/conftest.py
  tests/manage/pv_services/pvc_snapshot/test_verify_rbd_trash_purge.py
Labels: Test Case, Verified, team/manage, size/L, Squad/Green

#4877 Enable change ROOK LOG LEVEL during the deployment
  conf/README.md
  conf/ocsci/set_debug_rook_log_level.yaml
  docs/debugging.md
  ocs_ci/deployment/deployment.py
  ocs_ci/helpers/helpers.py
Labels: enhancement, Verified, team/ecosystem

#4880 fix flexy_post_processing: terraform part is applicable only for vSphere platform
  ocs_ci/deployment/flexy.py
Labels: team/ecosystem, size/M

#4878 Fix to 'list index out of range error in 'helpers.py::get_provision_time' and added 'namespace' argument in 'test_pvc_snapshot_performance_multiple_files' test
  ocs_ci/helpers/helpers.py
  tests/e2e/performance/test_pvc_snapshot_performance.py
Labels: size/XS

#4872 Fix version comparison
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/helpers/lso_helpers.py
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/utility/tests/test_version.py
  ocs_ci/utility/version.py
Labels: size/L, Merge As Is (Don't Squash)

#4858 Fix `test_block_read_resource_in_namespace_bucket_crd`
  tests/manage/mcg/test_namespace_crd.py
Labels: Verified, size/S, MCG

#4884 Reducing limits for nooba-endpoints
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/XS

#4443 Add support for custom vCPU configuration in RHV platform
  conf/deployment/rhv/ipi_1az_rhcos_3m_3w.yaml
  conf/deployment/rhv/ipi_1az_rhcos_lso_3m_3w.yaml
  conf/ocsci/rhv_ipi.yaml
  ocs_ci/templates/ocp-deployment/install-config-rhv-ipi.yaml.j2
Labels: enhancement, Verified, size/S

#4873 Adding namespace while collecting logs for pgbench
  ocs_ci/ocs/pgsql.py
Labels: size/XS

#4840 Added timeout sampler to wait volume method
  ocs_ci/utility/ibmcloud.py
  tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
Labels: size/M

#4638 Test case to verify subpath
  ocs_ci/helpers/helpers.py
  tests/conftest.py
  tests/manage/pv_services/test_verify_subpath.py
Labels: Test Case, Verified, team/manage, size/L, Squad/Green

#4867 Test case to verify creation of encrypted RBD PVC clone
  tests/manage/pv_services/pvc_clone/test_encrypted_rbd_pvc_clone.py
Labels: Test Case, Verified, team/manage, size/L, Squad/Green

#4886 Fix version comparison for more modules
  ocs_ci/ocs/must_gather/must_gather.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/bucket_policy.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/objectbucket.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/utils.py
  ocs_ci/ocs/version.py
  ocs_ci/utility/rgwutils.py
  tests/e2e/scale/test_osd_node_balancing.py
Labels: size/L

#4876 [Close loop BZ: 1991361] Test case for noobaa rebuild
  ocs_ci/ocs/constants.py
  tests/e2e/kcs/test_noobaa_rebuild.py
Labels: Verified, team/e2e, size/L, Customer defects

#4645 Block pool UI create use and delete
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/block_pool.py
  ocs_ci/ocs/ui/storageclass.py
  ocs_ci/ocs/ui/views.py
  tests/conftest.py
  tests/ui/test_create_pool_block_pool.py
Labels: Verified, size/XL, ui_testing
