Repository red-hat-storage/ocs-ci, pull requests merged in 2021-02, with the labels that each got.

#3734 Adding ceph volumeMounts for creating toolbox in external cluster
  ocs_ci/ocs/utils.py
Labels: Needs Deployment Testing, Verified, size/XS, team/ecosystem

#3730 Use Latest RHCOS images
  ocs_ci/templates/ocp-deployment/rhcos_images.yaml
Labels: Verified, size/S

#3762 Update azure node related methods in platform_nodes and azure_utils
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/azure_utils.py
Labels: Verified, platforms, size/M

#3774 Add libtest to test get_vm_power_status method
  tests/libtest/test_azure.py
Labels: Verified, size/S

#3739 [Openshift-Dedicated] Added changes related to tier 1 tests
  ocs_ci/helpers/sanity_helpers.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/must_gather/const_must_gather.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/ocp.py
  tests/conftest.py
  tests/e2e/logging/test_openshift-logging.py
  tests/manage/mcg/test_bucket_policy.py
  tests/manage/mcg/test_endpoint_autoscale.py
  tests/manage/mcg/test_multi_region.py
  tests/manage/mcg/test_multicloud.py
  tests/manage/mcg/test_multipart_upload.py
  tests/manage/mcg/test_namespace.py
  tests/manage/mcg/test_object_integrity.py
  tests/manage/mcg/test_verify_noobaa_status.py
  tests/manage/monitoring/prometheus/test_hpa.py
  tests/manage/monitoring/prometheusmetrics/test_mcg_hpa.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
  tests/manage/monitoring/prometheusmetrics/test_ocs_utilization.py
  tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
  tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
Labels: Verified, size/L

#3783 downstream ci: use python3.8
  Jenkinsfile
Labels: size/S

#3769 Configure monitoring and registry during OCS deployment in external mode
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/registry.py
Labels: Verified, size/L, team/ecosystem

#3799 Allow deploying OCS > 4.6 on Power
  ocs_ci/deployment/deployment.py
Labels: size/XS

#3804 Update Node replacement verification steps when we use more than 3 OCS worker nodes
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Needs Testing, size/M

#3632 Fix MCG CLI bucketclass creation in 4.7
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/mcg.py
Labels: Verified, size/S

#3669 Look for the right ObjectBucketName field dependent on version
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/objectbucket.py
Labels: MCG, Verified, size/S

#3473 Add code to handle teardown errors and disruptive tests - IBM Power
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/powernodes.py
Labels: size/L

#3809 Smallfiles - use the new ES method to retrieve data from internal ES
  ocs_ci/ocs/perfresult.py
  ocs_ci/ocs/perftests.py
  tests/e2e/performance/test_small_file_workload.py
Labels: High Priority, bug, performance, size/L

#3749 Add OCS Installation via UI to deployment procedure
  conf/ocsci/ui_deployment.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/pvc_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/XL

#3814 Increase timeout for mon pods for IBM Cloud
  ocs_ci/deployment/deployment.py
Labels: size/XS, team/ecosystem

#3819 Skip node_replacement_proactive test for IBM as the logic doesn't handle the IBM specific instance
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Needs Testing, size/XS

#3787 Fix for s3 delete_object invalid/empty version string
  ocs_ci/ocs/bucket_utils.py
Labels: MCG, Verified, size/S

#3817 Loading elasticsearch data as bulk and not one by one
  ocs_ci/ocs/elasticsearch.py
Labels: High Priority, Verified, performance, size/M

#3806 Remove acceptance marker from namespace bucket test cases
  tests/manage/mcg/test_namespace.py
Labels: Verified, size/XS

#3824 Remove workaround: [AZURE] Apply SSD tuning as a workaround for bug 1909793
  ocs_ci/deployment/deployment.py
  ocs_ci/utility/utils.py
Labels: size/M

#3818 Install OCS operator via ui
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/M

#3821 get proxies: logging and performance improvement
  ocs_ci/helpers/proxy.py
Labels: Verified, size/XS, team/ecosystem

#3788 OCS disconnected installation from live content
  docs/getting_started.md
  ocs_ci/deployment/disconnected.py
  ocs_ci/deployment/flexy.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/helpers/disconnected.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/utils.py
Labels: Verified, size/L, team/ecosystem

#3833 Increase ceph health check timeout in test test_add_capacity_node_restart
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
Labels: Verified, size/XS

#3718 modifying new timeout values for power architecture
  ocs_ci/ocs/ocp.py
  ocs_ci/utility/utils.py
Labels: size/XS

#3707 Add small file workload test for scale
  ocs_ci/ocs/small_file_workload.py
  tests/e2e/scale/test_scale_small_file_workload.py
Labels: Verified, scale, size/L

#3822 skip test_rwo_pvc_fencing_unfencing test case for IBM since PlatformNodesFactory is not implemented for IBM
  ocs_ci/framework/pytest_customization/marks.py
  tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
Labels: size/S, team/ecosystem

#3805 generating manifests and removing Machines and MachineSets
  ocs_ci/deployment/vmware.py
Labels: Verified, size/M, team/ecosystem

#3840 Fix for test_object_actions with explicit allow
  tests/manage/mcg/test_bucket_policy.py
Labels: MCG, bug, size/S

#3845 1. Add a new marker skipif_bmpsi for skipping tests on baremetal psi
  ocs_ci/framework/pytest_customization/marks.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Verified, size/S, team/ecosystem

#3838 Make sure pvc and pod names are unique.
  tests/e2e/scale/test_cephfs_many_files.py
Labels: Verified, scale, size/XS

#3816 Fixing osd tree verification on BM platform
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/XS, team/ecosystem

#3852 remove base_domain from azure configs
  conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
  conf/deployment/azure/ipi_3az_rhcos_3m_3w.yaml
  conf/ocsci/azure2_qe_rh_ocs_com_domain.yaml
  conf/ocsci/azure_qe_rh_ocs_com_domain.yaml
  docs/supported_platforms.md
Labels: size/S, team/ecosystem

#3829 docs: LSO CI note in FAQ entry for manual OCS setup
  docs/usecases/deployment_without_ocs.md
Labels: documentation, size/S

#3837 FIO | clean code duplication
  tests/conftest.py
  tests/e2e/performance/test_fio_benchmark.py
Labels: Verified, performance, size/L

#3851 Test to validate available size in object bucket. CustoBZ(1880747 and 1880748)
  ocs_ci/ocs/bucket_utils.py
  tests/manage/rgw/test_object_bucket_size.py
Labels: Customer defects, MCG, Test Case, Verified, size/L, team/e2e

#3825 Add nodes using terraform in vSphere
  ocs_ci/deployment/terraform.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/load_balancer.py
Labels: Verified, size/L, team/ecosystem

#3873 Disable ipv6 before starting postfix service
  Jenkinsfile
Labels: size/XS

#3880 Jenkins: Drop postfix
  Jenkinsfile
Labels: Verified, size/XS

#3882 Doc installer client cli args
  docs/usage.md
  docs/usecases/using_alternative_ocp_mirrors.md
Labels: documentation, size/S, team/ecosystem

#3883 Fixes:3862
  tests/e2e/logging/test_openshift-logging.py
Labels: Verified, size/XS, team/e2e

#3857 Change Node replacement proactive test to run on vSphere and cloud platforms
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: size/XS

#3867 Skip namespace tests when unsupported OCS version is installed
  tests/manage/mcg/test_namespace.py
Labels: Verified, size/XS

#3793 Modify test_nodes_restart to run on all Cloud platforms
  tests/manage/z_cluster/nodes/test_nodes_restart.py
Labels: Verified, platforms, size/XS

#3875 Fix kubelet path for IBM Cloud OCP 4.6
  ocs_ci/deployment/deployment.py
Labels: High Priority, IBM Cloud, Verified, size/M, team/ecosystem

#3889 Jenkins: Install gcc
  Jenkinsfile
Labels: size/XS

#3901 Fix flake8 issue with skipif_ocs_version
  tests/manage/mcg/test_namespace.py
Labels: High Priority, bug, size/XS

#3904 Remove node replacement test from acceptance suite
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Verified, size/XS

#3872 Config file which contains necessary values for early testing of RHCOS
  conf/ocsci/early_testing_rhcos.yaml
  ocs_ci/deployment/vmware.py
  tests/conftest.py
Labels: Verified, size/S, team/ecosystem

#3912 Adding OCS 4.8 config file
  ocs_ci/framework/conf/ocs_version/ocs-4.8.yaml
  ocs_ci/framework/main.py
Labels: Verified, size/S, team/ecosystem

#3791 OCS deployment with external Vault
  conf/README.md
  conf/examples/vault_external_standalone_mode.yaml
  conf/ocsci/vault_external_standalone_mode.yaml
  conf/ocsci/vault_internal_ocp_mode.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/templates/openshift-infra/vault/ocs-kms-ca-secret.yaml
  ocs_ci/templates/openshift-infra/vault/ocs-kms-client-cert.yaml
  ocs_ci/templates/openshift-infra/vault/ocs-kms-client-key.yaml
  ocs_ci/templates/openshift-infra/vault/ocs-kms-connection-details.yaml
  ocs_ci/templates/openshift-infra/vault/ocs-kms-token.yaml
  ocs_ci/utility/kms.py
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: Verified, size/XL, team/ecosystem
