Repository red-hat-storage/ocs-ci, pull requests merged in 2021-07, with the labels that each got.

#4496 move VIPS needed to constants module
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/ipam.py
Labels: Needs Deployment Testing, size/S, team/ecosystem

#4477 Skip RBD thick test if OCS version is below 4.8
  tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
Labels: Squad/Green, size/S

#4457 cache bucket lifecycle test
  ocs_ci/ocs/resources/bucketclass.py
  tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
Labels: MCG, size/L, team/e2e

#4369 [RHV] Add function to restart rhv node by stop and start
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/rhv.py
Labels: Verified, enhancement, size/M

#4455 UI validation on OCP4.8
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/M

#4062 Initial draft for adding ibmcloud ci impl
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/ibmcloud.py
  tests/libtest/test_ibmcloud.py
  tests/ui/test_quickstarts.py
Labels: DO NOT MERGE, size/L

#4468 Test nodereplacement with multiple osd ids
  ocs_ci/ocs/node.py
  ocs_ci/ocs/osd_operations.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/pv.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Verified, size/M

#4500 Add squad marker to test items and junit properties
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: size/XS, team/ecosystem

#4506 Fix OCP 4.6 installation on vSphere: use main.tf for updating gateway
  ocs_ci/deployment/vmware.py
Labels: Verified, size/XS, team/ecosystem

#4510 Fix OCP 4.6 installation on vSphere: use main.tf for updating gateway - branch release-4.6
  ocs_ci/deployment/vmware.py
Labels: size/XS, team/ecosystem

#4511 Fix OCP 4.6 installation on vSphere: use main.tf for updating gateway - branch release-4.7
  ocs_ci/deployment/vmware.py
Labels: size/XS, team/ecosystem

#4509 Adding OCS 4.9 yaml file
  ocs_ci/framework/conf/ocs_version/ocs-4.9.yaml
  ocs_ci/framework/main.py
Labels: size/S, team/ecosystem

#4516 Fix test_delete_provisioner_pod_while_thick_provisioning failure on external mode
  tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
Labels: External-cluster-mode, Squad/Green, Verified, size/XS

#4467 RHV - create new machineset for scaling nodes to run app pods
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/scale_lib.py
  ocs_ci/templates/openshift-infra/machineset-rhv.yaml
Labels: Verified, scale, size/L

#4419 Test case to verify the impact of plugin pod deletion on app pod
  tests/manage/pv_services/test_delete_plugin_pod.py
Labels: Squad/Green, Test Case, Verified, size/M, team/manage

#4338 Skip rbd-thick storage class verification in external mode
  ocs_ci/ocs/resources/storage_cluster.py
Labels: size/XS

#4350 Test to verify storage utilization of RBD thick provisioned PVC
  ocs_ci/helpers/helpers.py
  tests/manage/pv_services/test_verify_thick_pvc_utilization.py
Labels: Squad/Green, Test Case, Verified, size/L, team/manage

#3847 Check whether the df output is empty before processing the value in test test_pvc_expand_expanded_pvc
  tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
Labels: Squad/Green, Verified, size/XS, team/manage

#4515 Squad mark fix
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: size/XS, team/ecosystem

#4501 Updating Snapshot creation time log parsing
  ocs_ci/helpers/helpers.py
  tests/e2e/performance/test_pvc_snapshot_performance.py
Labels: size/S

#4502 Supporting multus deployment
  conf/ocsci/enable_multus.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocs-deployment/multus.yaml
Labels: Verified, size/M, team/ecosystem

#4530 deployment: Don't check for rbd-thick sc in OCS4.8
  ocs_ci/ocs/resources/storage_cluster.py
  tests/ui/test_pvc_ui.py
Labels: size/XS

#4513 Supporting external cluster secret data for OCP 4.8 and in upgrade path
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/utility/deployment.py
Labels: Verified, size/M, team/ecosystem

#3928 Remove manual exposure of RGW service on OCS 4.7+
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/rgw.py
  tests/conftest.py
Labels: Verified, size/M

#4214 Skip deletion for PVC backingstores that couldn't be found
  ocs_ci/ocs/resources/backingstore.py
Labels: MCG, Verified, size/S

#4473 Add rerun markers for flaky tests
  setup.py
  tests/manage/mcg/test_bucket_deletion.py
  tests/manage/mcg/test_object_integrity.py
  tests/manage/mcg/test_write_to_bucket.py
  tests/manage/rgw/test_bucket_deletion.py
  tests/manage/rgw/test_object_integrity.py
Labels: Verified, size/S

#4493 Rely on OCS version rather than OCP for MCG UI tests
  ocs_ci/ocs/ui/mcg_ui.py
Labels: MCG, Verified, size/S, ui_testing

#4525 Adding Black squad for UI test cases
  ocs_ci/ocs/constants.py
Labels: size/XS, team/ecosystem

#4487 Update toolbox_pod.yaml and utils.py to use new creds format
  ocs_ci/ocs/utils.py
  ocs_ci/templates/ocs-deployment/toolbox_pod.yaml
Labels: External-cluster-mode, Verified, size/M

#4538 Skip RBD thick test cases in OCS4.8
  tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
  tests/manage/pv_services/test_delete_pvc_while_provisioning.py
  tests/manage/pv_services/test_expansion_snapshot_clone.py
  tests/manage/pv_services/test_rbd_thick_provisioning.py
  tests/manage/pv_services/test_verify_thick_pvc_utilization.py
Labels: Squad/Green, Verified, size/S

#4524 Adding documentation for prerequisites for vSphere IPI
  docs/getting_started.md
Labels: size/S, team/ecosystem

#4499 Add kv-v2 support for vault deployment
  conf/ocsci/vault_external_standalone_mode_v1.yaml
  conf/ocsci/vault_external_standalone_mode_v2.yaml
  ocs_ci/ocs/defaults.py
  ocs_ci/templates/openshift-infra/vault/ocs-kms-connection-details.yaml
  ocs_ci/utility/kms.py
Labels: Verified, size/S, team/ecosystem

#4485 Arbiter setup for production CI
  conf/README.md
  conf/deployment/aws/ipi_3az_rhcos_3m_4w_arbiter.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_6w_arbiter.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/helpers/lso_helpers.py
  ocs_ci/deployment/zones.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
Labels: Code/Infra, Merge As Is (Dont Squash), Squad/Green, Verified, size/L

#4152 Scale Upgrade testcase
  ocs_ci/ocs/scale_lib.py
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_pvcs_pods.py
Labels: High Priority, Test Case, Verified, scale, size/L

#4527 Verify ceph health is HEALTH_WARN after ceph daemon killing
  tests/manage/z_cluster/test_coredump_check_for_ceph_daemon_crash.py
Labels: Needs Testing, size/S

#4534 Change must-gather image to live image + tag
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: Verified, enhancement, size/S, team/ecosystem

#4437 Fix ovirt-dependencies
  ocs_ci/deployment/factory.py
  ocs_ci/ocs/platform_nodes.py
Labels: size/L

#4364 Verify PV is available before add capacity
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/pv.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/uninstall.py
  ocs_ci/utility/localstorage.py
  tests/e2e/flowtest/test_base_operation_node_drain.py
  tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
  tests/manage/z_cluster/cluster_expansion/test_delete_pod.py
Labels: Verified, size/L

#4512 Increased the transactions count for pgbench pod and few enhancements to pgsql tests
  ocs_ci/ocs/pgsql.py
  tests/e2e/workloads/pgsql/test_pgsql.py
  tests/e2e/workloads/pgsql/test_pgsql_node_drain.py
  tests/e2e/workloads/pgsql/test_pgsql_node_reboot.py
  tests/e2e/workloads/pgsql/test_pgsql_pod_respin.py
Labels: size/M, team/e2e

#4463 Helper functions for encrypted storageclass creation with KMS vault
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/CSI/rbd/csi-kms-connection-details.yaml
  ocs_ci/templates/CSI/rbd/csi-kms-secret.yaml
  ocs_ci/utility/kms.py
Labels: Verified, size/L, team/ecosystem

#4547 Fix `get_ocs_version()`
  ocs_ci/ocs/ocp.py
Labels: bug, size/XS

#4555 Add polarion id for external mode conf file
  conf/ocsci/external_rhcs_cluster.yaml
Labels: size/XS

#4548 Add `rgw_endpoint` support for clusters running in external mode
  tests/conftest.py
Labels: RGW, size/XS

#4558 Fix Add capacity failure for non-LSO cluster.
  ocs_ci/ocs/resources/storage_cluster.py
Labels: High Priority, size/S

#4561 Fix regression in DeploymentFactory
  ocs_ci/deployment/factory.py
Labels: bug, platforms

#4529 Fixed issues to ran Tier1 and 4 on ibmcloud
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/ibmcloud.py
  tests/conftest.py
  tests/libtest/test_ibmcloud.py
  tests/manage/pv_services/pvc_snapshot/test_rbd_block_pvc_snapshot.py
  tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
  tests/manage/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
  tests/manage/z_cluster/nodes/test_check_pods_status_after_node_failure.py
  tests/manage/z_cluster/nodes/test_nodes_restart.py
  tests/ui/test_pvc_ui.py
  tests/ui/test_validation_ui.py
Labels: size/L

#4563 Seperate v1 and v2 for vault production job yamls
  conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v1_external_with_namespace.yaml
  conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v2_external_with_namespace.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_external_vault_v1_with_namespace.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_external_vault_v2_with_namespace.yaml
Labels: Needs Deployment Testing, team/ecosystem

#4440 GSS bug,Verify the num of mon pods is 3 when drain node
  ocs_ci/helpers/helpers.py
  tests/manage/z_cluster/test_rook_operator_restart_during_mon_failover.py
Labels: Verified, size/L

#4552 Ypersky new perf mark
  ocs_ci/framework/pytest_customization/marks.py
  pytest.ini
  tests/e2e/performance/test_pvc_creation_deletion_performance.py
Labels: performance, size/S

#4498 Update ClusterObjectStoreState alert message for higher version
  tests/manage/monitoring/prometheus/test_rgw.py
Labels: Squad/Blue, Verified, size/S

#4556 optionally use ocp-network-split during deployment
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_6w_arbiter.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/netsplit.py
  ocs_ci/deployment/zones.py
  ocs_ci/framework/conf/default_config.yaml
  requirements.txt
  setup.py
  tox.ini
Labels: Code/Infra, Merge As Is (Dont Squash), Needs Deployment Testing, size/L

#4568 disable ES from smallfile used in snapshot test
  tests/e2e/performance/test_pvc_snapshot_performance.py
Labels: Verified, bug, performance

#4572 Fixes:4564
  ocs_ci/utility/uninstall_openshift_logging.py
Labels: Squad/Magenta, Verified, team/e2e

#4571 Prameterize kmsid and allow updating connectiondetails
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/defaults.py
  ocs_ci/utility/kms.py
Labels: Verified, team/ecosystem

#4546 Adjust tests in test_node_replacement_proactive.py to run on vSphere IPI
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Verified, platforms, size/L

#4578 Revert #3928 and #4548
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/rgw.py
  tests/conftest.py
Labels: RGW, Verified

#4574 Improve run_ibmcloud_cmd functionality
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/ibmcloud.py
Labels: team/ecosystem

#4536 increased waiting for rebalance timeout when io in background
  ocs_ci/ocs/cluster.py
Labels: Verified, size/XS

#4579 Pushing attach_time results to ES for the performance-dashboard
  tests/e2e/performance/test_pvc_attachtime.py
Labels: Squad/Gray, performance

#4598 Fix disks cleanup over BM
  ocs_ci/deployment/baremetal.py
Labels: High Priority, Verified

#4535 Add TimeoutSampler generator for test_osd_heap_profile
  tests/manage/z_cluster/test_osd_heap_profile.py
Labels: Verified, size/M

#4557 On teardown validate replica count of registry pod
  tests/e2e/registry/test_registry_by_increasing_num_of_image_registry_pods.py
Labels: Verified, size/S

#4604 updating template for ocp 48 and ocp 49
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.8-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.9-config.yaml
Labels: Verified, team/ecosystem

#4600 Add multus prod configs
  conf/deployment/vsphere/upi_1az_rhcos_multus_vmfs_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_multus_vsan_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_multus_vmfs_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_multus_vsan_3m_3w.yaml
Labels: team/ecosystem

#4543 Introducing new tier scale_long_run and scale_changed_layout
  ocs_ci/framework/pytest_customization/marks.py
  pytest.ini
Labels: High Priority, Squad/Orange, performance, scale, size/M

#4565 Fix for Scale test failure during upgrade tests
  ocs_ci/ocs/scale_lib.py
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_pvcs_pods.py
Labels: High Priority, Test Case, scale

#4549 GSS, test the mechanism to enable and disable debug logs
  ocs_ci/helpers/helpers.py
  tests/manage/z_cluster/test_rook_ceph_operator_log_type.py
Labels: size/L

#4576 Fix UI infra
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/utility/utils.py
  tests/conftest.py
  tests/ui/test_validation_ui.py
Labels: Verified

#4520 Validate that mon db gets trimmed.
  ocs_ci/ocs/constants.py
  tests/manage/z_cluster/test_mon_log_trimming.py
Labels: Verified, size/L

#4519 Fix BZ automation
  tests/manage/z_cluster/test_delete_rook_ceph_mon_pod.py
Labels: size/S

#4570 Update external cluster upgrade procedure
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, size/M, team/ecosystem

#4608 Increase timeout for tar creation in
  tests/e2e/scale/test_cephfs_many_files.py
Labels: size/XS

#4616 Increase expected CSR count in OCP 4.9
  ocs_ci/utility/csr.py
Labels: Verified, size/XS, team/ecosystem

#4617 Fix flexible scaling enabled condition in the 'add capacity' tests
  tests/e2e/flowtest/test_base_operation_node_drain.py
  tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
  tests/manage/z_cluster/cluster_expansion/test_delete_pod.py
Labels: size/S

#4607 4.8 GA config files
  ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-upgrade.yaml
Labels: size/M, team/ecosystem

#4603 Clear warnings and leftovers after test disk failures
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/osd_operations.py
  ocs_ci/ocs/resources/job.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/L

#2697 Scale 12 OCS workers, 36 OSDs and 6000 PVCs attached to PODs and perform tests
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/scale_lib.py
  tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
Labels: Test Case, scale, size/L

#4628 Update GA template for OCP 4.8
  ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-minus1-config.yaml
Labels: Verified, size/XS, team/ecosystem

#4613 Catch and report session scope fixture teardown failures in a separated dedicated test case
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
  tests/test_failure_propagator.py
Labels: Verified, size/S

#4623 Add new Ceph values to ceph config values saved in constants.py
  ocs_ci/ocs/constants.py
Labels: Squad/Brown, Verified, size/XS

#4587 skip template check for vSphere IPI
  ocs_ci/deployment/helpers/prechecks.py
Labels: Verified, size/XS, team/ecosystem

#4633 log vm names instead of objects
  ocs_ci/ocs/platform_nodes.py
Labels: Verified, size/XS, team/ecosystem

#4619 Wait for new nodes to settle down in IBM cloud
  ocs_ci/ocs/node.py
  ocs_ci/utility/utils.py
Labels: Verified, size/S, team/ecosystem

#4614 Fix osd_encryption_verification function
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Squad/Brown, Verified, size/M

#4592 GSS bug, Verify there is no xss vulnerability with noobaa management console.
  ocs_ci/helpers/helpers.py
  tests/manage/z_cluster/test_noobaa_xss_vulnerability.py
Labels: Verified, size/M
