Repository red-hat-storage/ocs-ci, pull requests merged in 2021-11, with the labels that each got.

#5016 Skip MCG cloud tests when running on a disconnected cluster
  ocs_ci/ocs/constants.py
  tests/manage/mcg/conftest.py
Labels: Verified, size/S

#5008 Fix tests selection based on squad marks
  ocs_ci/framework/pytest_customization/ocscilib.py
  tests/conftest.py
Labels: Verified, team/ecosystem, size/S

#5003 Enhance Bare Metal locking
  ocs_ci/deployment/baremetal.py
Labels: Verified, size/S

#4986 Updateing test parameters for Smallfiles performance test
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/perfresult.py
  ocs_ci/ocs/perftests.py
  ocs_ci/templates/workloads/smallfile/SmallFile.yaml
  tests/e2e/performance/test_small_file_workload.py
Labels: Verified, size/L, performance

#5017 Adding a new test_bulk_pod_attachtime_performance test
  tests/e2e/performance/test_bulk_pod_attachtime_performance.py
Labels: size/L, performance

#4967 Fix OCS deployment via UI
  ocs_ci/ocs/ui/deployment_ui.py
Labels: size/XS

#5026 Skip test_osd_node_balacing due to bz
  tests/e2e/scale/conftest.py
  tests/e2e/scale/test_osd_node_balancing.py
Labels: Skip test, size/XS, scale

#5002 Add GA config file for BM OCP 4.9
  ocs_ci/templates/ocp-deployment/rhcos_images.yaml
Labels: Verified, size/XS

#4966 Implement tests for NooBaa component rescheduling improvements
  tests/manage/mcg/test_host_node_failure.py
  tests/manage/mcg/test_mcg_resources_disruptions.py
Labels: Verified, size/L

#5045 Disable add node for IBM Flash system
  conf/README.md
  conf/ocsci/ibm_flash.yaml
  ocs_ci/framework/pytest_customization/marks.py
  tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
Labels: size/S

#5029 adding vm_network to install config
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/XS

#4958 Implement tier 1 MCG replication policy tests
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/bucketclass.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/objectbucket.py
  tests/conftest.py
  tests/manage/mcg/test_bucket_replication.py
Labels: Verified, size/XL, MCG

#4931 Obc creation and deletion time
  ocs_ci/ocs/scale_noobaa_lib.py
  tests/e2e/scale/noobaa/test_scale_obc_create_delete.py
Labels: Needs Testing, size/L, scale, MCG

#5047 adding additional keys to the ES reports
  tests/e2e/performance/test_bulk_pod_attachtime_performance.py
  tests/e2e/performance/test_pvc_attachtime.py
Labels: size/S, performance

#5038 deployment: remove checks for rbd-thick sc
  ocs_ci/ocs/resources/storage_cluster.py
  tests/ui/test_pvc_ui.py
Labels: size/M

#5043 Fix jenkins workload on OCP4.9
  ocs_ci/ocs/jenkins.py
  ocs_ci/ocs/ocp.py
Labels: size/S

#5034 allow override automatically added squad marks
  ocs_ci/framework/pytest_customization/marks.py
  tests/conftest.py
Labels: team/ecosystem, size/S

#5060 Modify pgbench replicas count to 1 in pgsql functional tests
  ocs_ci/templates/workloads/pgsql/PGSQL_Benchmark.yaml
  tests/e2e/lifecycle/pvc_clone/test_pgsql_pvc_clone.py
  tests/e2e/lifecycle/pvc_snapshot/test_pgsql_pvc_snapshot.py
  tests/e2e/workloads/pgsql/test_pgsql.py
  tests/e2e/workloads/pgsql/test_pgsql_node_drain.py
  tests/e2e/workloads/pgsql/test_pgsql_node_reboot.py
  tests/e2e/workloads/pgsql/test_pgsql_pod_respin.py
  tests/e2e/workloads/pvc_snapshot_and_clone/test_cloned_and_restored_pvc_resize.py
  tests/e2e/workloads/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py
Labels: Verified, team/e2e, size/M

#5039 Adding OCS 4.10 yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.10.yaml
  ocs_ci/framework/main.py
Labels: team/ecosystem, size/S

#5035 Test object policy fix
  tests/manage/mcg/test_bucket_policy.py
Labels: bug, Verified, size/S

#5075 Update black version
  .pre-commit-config.yaml
  ocs_ci/ocs/api_client.py
  ocs_ci/ocs/openstack.py
  requirements-dev.txt
  tox.ini
Labels: size/S

#5062 Added UI infrastructure for ACM
  ocs_ci/ocs/ui/acm_ui.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/L

#4874 Add marker for aws based platforms only test
  ocs_ci/framework/pytest_customization/marks.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_proactive_IPI.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
  tests/manage/z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: enhancement, size/S

#5081 Change of noobaa operator CSV
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/defaults.py
Labels: Verified, team/ecosystem, size/S

#5057 Add mon_data_avail_warn to rook ceph config saved values
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/manage/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/M

#5058 skip mcg replication tests for versions below 4.9
  tests/manage/mcg/test_bucket_replication.py
Labels: Verified, size/XS

#5020 Directory changes for performance io and csi tests
  tests/e2e/performance/csi_tests/test_bulk_pod_attachtime_performance.py
  tests/e2e/performance/csi_tests/test_multi_snapshots.py
  tests/e2e/performance/csi_tests/test_pod_reattachtime.py
  tests/e2e/performance/csi_tests/test_pvc_attachtime.py
  tests/e2e/performance/csi_tests/test_pvc_bulk_clone_performance.py
  tests/e2e/performance/csi_tests/test_pvc_bulk_creation_deletion_performance.py
  tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
  tests/e2e/performance/csi_tests/test_pvc_creation_deletion_performance.py
  tests/e2e/performance/csi_tests/test_pvc_multi_clone_performance.py
  tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py
  tests/e2e/performance/csi_tests/test_pvc_snapshot_performance.py
  tests/e2e/performance/io_workload/test_fio_benchmark.py
  tests/e2e/performance/io_workload/test_io_performance.py
  tests/e2e/performance/io_workload/test_small_file_workload.py
Labels: size/XS

#5041 Add support for Disconnected deployment on vSphere
  conf/README.md
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_disconnected.yaml
  ocs_ci/deployment/flexy.py
  ocs_ci/ocs/ocp.py
  ocs_ci/utility/proxy.py
Labels: Verified, team/ecosystem, size/M

#5089 Fix for IBM cloud upgrade
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/XS

#5053 Add upgrade check for all CSV to be in succeeded state
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/resources/csv.py
Labels: Verified, team/ecosystem, size/M

#5068 Fix failure in compression test
  tests/manage/storageclass/test_create_2_sc_with_1_pool_comp_rep2.py
  tests/manage/storageclass/test_create_2sc_at_once_with_io.py
  tests/manage/storageclass/test_create_sc_reclaim_policy_rep2_comp.py
  tests/manage/storageclass/test_multiple_sc_comp_rep_data_delete.py
  tests/manage/storageclass/test_new_sc_rbd_replica2_3.py
Labels: size/M

#5085 Skip RBD thick test cases
  tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
  tests/manage/pv_services/test_delete_pvc_while_provisioning.py
  tests/manage/pv_services/test_expansion_snapshot_clone.py
  tests/manage/pv_services/test_rbd_thick_provisioning.py
  tests/manage/pv_services/test_verify_thick_pvc_utilization.py
Labels: Verified, team/manage, size/S, Squad/Green

#5084 Add red_squad marker to noobaa upgrade tests
  tests/ecosystem/upgrade/test_noobaa.py
  tests/ecosystem/upgrade/test_resources.py
Labels: Verified, size/XS

#4814 Adding shutdown_wait_timeout for compute and control-plane machines
  ocs_ci/deployment/flexy.py
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/utils.py
  setup.py
Labels: Verified, team/ecosystem, size/M

#4938 Deploy KMS with CA Certificate[without Client Certificate and Client Private Key]
  conf/ocsci/vault_external_standalone_ca_only_v1.yaml
  conf/ocsci/vault_external_standalone_ca_only_v2.yaml
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/utility/kms.py
Labels: size/L

#5093 Fix Test: text_osd_heap_profile
  tests/manage/z_cluster/test_osd_heap_profile.py
Labels: Verified, size/XS

#5092 updating pre-commit version to match with requirements-dev
  .pre-commit-config.yaml
Labels: Needs Testing, team/ecosystem, size/XS

#4952 Aligning storagesystem name with UI naming
  ocs_ci/templates/ocs-deployment/storagesystem_odf.yaml
Labels: Needs Deployment Testing, team/ecosystem, size/XS

#5087 Add magenta_squad marker to logging and monitoring upgrade tests
  tests/ecosystem/upgrade/test_logging_upgrade.py
  tests/ecosystem/upgrade/test_monitoring_after_ocp_upgrade.py
Labels: size/XS

#5086 Possibility to add param --binary-image to opm index prune command
  conf/README.md
  ocs_ci/deployment/disconnected.py
Labels: Verified, team/ecosystem, size/XS

#5094 Add configuration file for disconnected lso deployment on vSphere UPI
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w_disconnected.yaml
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/M

#5083 Fix disconnected lso deployment
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/XS

#5013 Remove legacy reportportal
  conf/README.md
  docs/results.md
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/templates/reporting/report_portal.cfg
  pytest.ini
  requirements.txt
  tests/conftest.py
Labels: team/ecosystem, size/L

#5101 fix disconnected odf > 4.9.0-231 deployment
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/XS

#5102 Remove --rp-launch from main function
  ocs_ci/framework/main.py
Labels: team/ecosystem, size/XS

#5105 Donot fail whole execution when rp_launch_tags not found
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: Verified, team/ecosystem, size/XS

#5107 Updating pre-commit-hooks rev to 4.0.1
  .pre-commit-config.yaml
  requirements-dev.txt
Labels: Verified, team/ecosystem, size/XS

#5103 Adding marker to skip the test: test_pod_start_time while running with param: CEPHBLOCKPOOL_THICK
  tests/e2e/performance/csi_tests/test_pvc_attachtime.py
Labels: size/XS

#5111 Fix doc string
  ocs_ci/ocs/bucket_utils.py
Labels: size/XS

#5077 changing the reporting of OCS version in performance tests
  ocs_ci/ocs/version.py
Labels: bug, size/XS, performance

#5061 ODF4.9, LSO deployment via UI
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/views.py
Labels: size/M

#5019 Adding Performance Dashboard DB management Module
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/utility/perf_dash/__init__.py
  ocs_ci/utility/perf_dash/dashboard_api.py
  setup.py
Labels: enhancement, size/XL, performance, Squad/Gray

#5040 MCG Only deployment
  conf/ocsci/mcg_only_deployment.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/helpers/mcg_helpers.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/resources/storage_cluster.py
  tests/conftest.py
  tests/ecosystem/deployment/test_deployment.py
Labels: Needs Deployment Testing, team/ecosystem, size/L, Merge As Is (Don't Squash)

#5115 Skip registry workload
  tests/e2e/registry/test_simple_registry_workload.py
Labels: size/XS

#5117 Stop adding rp_launch_tags to pytest.ini
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: Verified, team/ecosystem, size/S

#5025 Add capactiy via UI on ODF4.9
  ocs_ci/ocs/ui/add_replace_device_ui.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/views.py
Labels: size/M

#5123 Remove acceptance marker from the test test_rbd_thick_provisioning
  tests/manage/pv_services/test_rbd_thick_provisioning.py
Labels: Verified, size/XS

#5108 Couchbase workload new implementation
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/couchbase_new.py
  ocs_ci/ocs/pillowfight.py
  ocs_ci/templates/workloads/couchbase_new/pillowfight/basic-pillowfight.yaml
  ocs_ci/templates/workloads/couchbase_new/server/cb-operatorgroup.yaml
  ocs_ci/templates/workloads/couchbase_new/server/cb-subscription.yaml
  ocs_ci/templates/workloads/couchbase_new/server/couchbase-data-bucket.yaml
  ocs_ci/templates/workloads/couchbase_new/server/couchbase-worker-secret.yaml
  ocs_ci/templates/workloads/couchbase_new/server/couchbase-worker.yaml
  tests/conftest.py
  tests/e2e/workloads/couchbase/test_couchbase.py
  tests/e2e/workloads/couchbase/test_couchbase_node_drain.py
  tests/e2e/workloads/couchbase/test_couchbase_node_reboot.py
  tests/e2e/workloads/couchbase/test_couchbase_pod_respin.py
Labels: Verified, team/e2e, size/XL

#5124 UI deployment, Added refresh page [PopUp]
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/views.py
Labels: size/S

#5126 Skipping ODF Storage System UI validation for OCS 4.8 and below versions
  tests/ui/test_validation_ui.py
Labels: ui_testing

#4866 Adding RHEL_MAJOR_OS to scale_up_terraform.tfvars file
  ocs_ci/deployment/helpers/vsphere_helpers.py
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocp-deployment/inventory_haproxy.yaml.j2
  ocs_ci/templates/ocp-deployment/scale_up_terraform_with_folder_structure.tfvars.j2
  ocs_ci/utility/load_balancer.py
Labels: Verified, team/ecosystem, size/M

#5121 adding ES parameters to test_pod_reattachtime.py test
  tests/e2e/performance/csi_tests/test_pod_reattachtime.py
Labels: size/S, performance

#5129 Update RHCOS template for OCP 4.9
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.10-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.9-config.yaml
Labels: Needs Deployment Testing, team/ecosystem, size/XS

#5119 added noobaa_db_backup_and_recovery function to test_mcg_recovery
  tests/e2e/system/conftest.py
  tests/e2e/system/test_mcg_recovery.py
Labels: size/L

#5005 ROSA deployment
  conf/ocsci/rosa.yaml
  docs/supported_platforms.md
  ocs_ci/deployment/factory.py
  ocs_ci/deployment/rosa.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/uninstall.py
  ocs_ci/utility/rosa.py
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: Verified, size/XL, Managed Services

#5135 Couchbase workload new implementation - 4.8 (#5108)
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/couchbase_new.py
  ocs_ci/ocs/pillowfight.py
  ocs_ci/templates/workloads/couchbase_new/pillowfight/basic-pillowfight.yaml
  ocs_ci/templates/workloads/couchbase_new/server/cb-operatorgroup.yaml
  ocs_ci/templates/workloads/couchbase_new/server/cb-subscription.yaml
  ocs_ci/templates/workloads/couchbase_new/server/couchbase-data-bucket.yaml
  ocs_ci/templates/workloads/couchbase_new/server/couchbase-worker-secret.yaml
  ocs_ci/templates/workloads/couchbase_new/server/couchbase-worker.yaml
  tests/conftest.py
  tests/e2e/workloads/couchbase/test_couchbase.py
  tests/e2e/workloads/couchbase/test_couchbase_node_drain.py
  tests/e2e/workloads/couchbase/test_couchbase_node_reboot.py
  tests/e2e/workloads/couchbase/test_couchbase_pod_respin.py
Labels: Verified, team/e2e, size/XL

#5130 Remove old couchbase workload code
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/couchbase.py
  ocs_ci/templates/workloads/couchbase/server/MutatingWebhookConfiguration.yaml
  ocs_ci/templates/workloads/couchbase/server/ValidatingWebhookConfiguration.yaml
  ocs_ci/templates/workloads/couchbase/server/admissionClusterRole.yaml
  ocs_ci/templates/workloads/couchbase/server/admissionClusterRoleBinding.yaml
  ocs_ci/templates/workloads/couchbase/server/admissionDeployment.yaml
  ocs_ci/templates/workloads/couchbase/server/admissionSecret.yaml
  ocs_ci/templates/workloads/couchbase/server/admissionService.yaml
  ocs_ci/templates/workloads/couchbase/server/admissionServiceAccount.yaml
  ocs_ci/templates/workloads/couchbase/server/basic-pillowfight.yaml
  ocs_ci/templates/workloads/couchbase/server/couchbase-worker-example.yaml
  ocs_ci/templates/workloads/couchbase/server/couchbase-worker-secret.yaml
  ocs_ci/templates/workloads/couchbase/server/couchbaseCrd.yaml
  ocs_ci/templates/workloads/couchbase/server/operator-deployment.yaml
  ocs_ci/templates/workloads/couchbase/server/operator-role.yaml
  ocs_ci/templates/workloads/couchbase/server/pillowfight/basic-pillowfight.yaml
Labels: Verified, team/e2e, size/XXL

#5049 Managed service post-installation tests
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/managed-service/test_post_installation_state.py
Labels: size/L

#5138 move constants.VM_MAIN json file if it already exists
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/S

#5143 ODF dashboard validation changes as per new OCP console
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/ui/views.py
Labels: size/S, ui_testing

#5149 Add connection refresh when Prometheus service unavailable
  ocs_ci/utility/prometheus.py
Labels: Verified, size/S, Squad/Blue

#5136 Teardown fixes in "test_pvc_bulk_creation_deletion_performance" test case
  ocs_ci/helpers/helpers.py
  tests/e2e/performance/csi_tests/test_pvc_bulk_creation_deletion_performance.py
Labels: size/M, performance

#5151 MCG_ONLY Deployment via UI
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/views.py
Labels: size/S
