Repository red-hat-storage/ocs-ci, pull requests merged in 2021-08, with the labels that each got.

#4653 get volume IDs for cluster in IBM cloud
  ocs_ci/utility/ibmcloud.py
Labels: Verified, size/S, team/ecosystem

#4655 Added ipi_deployment_required marker in scale tests where node scaling is done for app pods.
  tests/e2e/scale/test_ceph_pod_respin_in_scaled_cluster.py
  tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_pvcs_pods.py
Labels: High Priority, TestCase failing, scale, size/S

#4650 fix AWS UPI RHEL installation: add required var
  ocs_ci/deployment/aws.py
Labels: Verified, size/S, team/ecosystem

#4591 Fixing the Tier4b issues
  ocs_ci/utility/ibmcloud.py
  tests/libtest/test_ibmcloud.py
  tests/manage/pv_services/pvc_clone/test_clone_when_pvc_full.py
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: Needs Testing, size/M

#4626 Add multus baremetal configuration
  conf/deployment/baremetal/upi_1az_rhcos_multus_nvme_intel_3m_3w.yaml
Labels: size/S, team/ecosystem

#4595 Added load config file functionality, fix issue #4588
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Verified, size/M

#4658 Fix BZ 1941939 automation.
  tests/manage/z_cluster/test_mon_log_trimming.py
Labels: Verified, size/XS

#4648 remove duplicate line of subscription_plan_approval
  ocs_ci/deployment/deployment.py
Labels: size/XS, team/ecosystem

#4670 Change channel for OCP 4.8-GA config to stable
  ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-upgrade.yaml
Labels: size/XS, team/ecosystem

#4620 Skip RBD thick test cases in OCS 4.9
  tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
  tests/manage/pv_services/test_delete_pvc_while_provisioning.py
  tests/manage/pv_services/test_expansion_snapshot_clone.py
  tests/manage/pv_services/test_rbd_thick_provisioning.py
  tests/manage/pv_services/test_verify_thick_pvc_utilization.py
Labels: Verified, size/S

#4644 quay operator on ocs
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/quay_operator.py
  ocs_ci/templates/workloads/quay/quay_registry.yaml
  ocs_ci/templates/workloads/quay/quay_subscription.yaml
  tests/e2e/workloads/quay/test_quay_operator.py
Labels: Verified, size/L, team/e2e

#4472 Pvc resize UI
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/pvc_ui.py
  ocs_ci/ocs/ui/views.py
  tests/ui/test_pvc_ui.py
Labels: size/L

#4354 Update tests to run IO on pods attached with PVCs having unique access mode and volume mode combination
  ocs_ci/helpers/helpers.py
  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_and_io.py
  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_deletion_and_io.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: Squad/Green, Verified, size/L

#4596 Test to verify creation and deletion of encrypted RBD PVC with vaulttoken
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/helpers/helpers.py
  ocs_ci/utility/kms.py
  tests/conftest.py
  tests/manage/pv_services/test_rbd_pv_encryption.py
Labels: Squad/Green, Test Case, Verified, size/L, team/manage

#4675 Changing default_latest_tag to stable for OCS 4.9
  ocs_ci/framework/conf/ocs_version/ocs-4.9.yaml
Labels: team/ecosystem, size/XS

#4634 A testcase to verifies multiple mons on same node
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/test_multiple_mon_pods_stays_on_same_node.py
Labels: Verified, size/L

#4678 quay operator test for bz1959331
  tests/e2e/workloads/quay/test_quay_operator.py
Labels: Verified, team/e2e, size/XS

#4656 Fix bucketclass UI tests
  ocs_ci/ocs/ui/mcg_ui.py
Labels: size/XS, MCG, ui_testing

#4680 [Multus] Update cniVersion in NAD template to align with the docs
  ocs_ci/templates/ocs-deployment/multus.yaml
Labels: size/XS

#4664 Check whether the df output is empty before processing the value in test_resource_deletion_during_pvc_expansion
  tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Labels: team/manage, size/XS, Squad/Green

#4686 Upgrading the Elasticsearch module to use ECK 1.6.0 and ES 7.14
  ocs_ci/ocs/elasticsearch.py
  ocs_ci/templates/app-pods/eck.1.6.0-all-in-one.yaml
  ocs_ci/templates/app-pods/es-pvc.yaml
  ocs_ci/templates/app-pods/esq.yaml
  setup.py
  tests/libtest/test_elasticsearch.py
Labels: bug, size/XXL, performance

#4690 Fixing IBM cloud login issue
  ocs_ci/utility/ibmcloud.py
Labels: team/ecosystem, size/XS

#4669 Defaulting to OCS 4.9
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, team/ecosystem, size/S

#4133 Add tests/e2e/scale/test_osd_node_balancing.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/scale_lib.py
  ocs_ci/templates/workloads/osd_scale/osd_scale_benchmark.yaml
  tests/e2e/scale/test_osd_node_balancing.py
Labels: Verified, size/L, scale

#4698 Fix post_upgrade scale test failure
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_pvcs_pods.py
Labels: High Priority, size/XS, scale, upgrade

#4676 Add github action for labeling and closing stale issues and pull requests
  .github/workflows/stale.yml
Labels: team/ecosystem, size/S

#4704 Add priority for ocs-catalogsource
  ocs_ci/templates/ocs-deployment/catalog-source.yaml
Labels: Verified, team/ecosystem, size/XS

#4692 Fix key validation for PV encryption in OCS 4.7
  tests/manage/pv_services/test_rbd_pv_encryption.py
Labels: Verified, size/S, Squad/Green

#4707 Add polarion ID for existing scale test
  tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
  tests/e2e/scale/test_scale_osds_fill_75%_reboot_workers.py
Labels: High Priority, size/S, scale

#4705 Fix issue with retrieving ocp channel
  ocs_ci/ocs/ocp.py
Labels: size/XS

#4700 Fio implement benchmark-operator
  ocs_ci/templates/workloads/fio/benchmark_fio.yaml
  ocs_ci/templates/workloads/fio/benchmark_fio_cmp.yaml
  ocs_ci/templates/workloads/smallfile/SmallFile.yaml
  tests/e2e/performance/test_fio_benchmark.py
Labels: bug, High Priority, Verified, size/M, performance

#4518 Add a new node and verify crashcollector pod created
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
Labels: Verified, size/L

#4703 Adjust Pgsql with the new benchmark-operator changes
  ocs_ci/ocs/pgsql.py
  ocs_ci/templates/workloads/pgsql/PGSQL_Benchmark.yaml
  ocs_ci/templates/workloads/pgsql/server/ConfigMap.yaml
  ocs_ci/templates/workloads/pgsql/server/Service.yaml
  ocs_ci/templates/workloads/pgsql/server/StatefulSet.yaml
Labels: team/e2e, size/M

#4709 Fix format string in python
  ocs_ci/utility/service.py
Labels: size/S

#4654 Create a new fixture to use in the "add capacity" tests setup
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/pv.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/manage/z_cluster/cluster_expansion/conftest.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
  tests/manage/z_cluster/cluster_expansion/test_delete_pod.py
Labels: size/M

#4681 [Multus] Add namespace reference along with NAD name in the StorageCluster network spec
  ocs_ci/deployment/deployment.py
Labels: Verified, size/XS

#4716 Fix file validation in Scale test
  tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
Labels: bug, Test Case, High Priority, size/XS, scale

#4697 Update Pull-secret link
  docs/getting_started.md
Labels: documentation, size/XS

#4723 Add BAREMETALPSI_PLATFORM in the 'if' condition for instantiating pla…
  ocs_ci/deployment/factory.py
  ocs_ci/ocs/constants.py
Labels: bug, Verified, team/ecosystem, size/XS

#4728 requre specific google-auth version
  setup.py
Labels: Verified, team/ecosystem, size/XS

#4725 fix logging hanledrs hardcoded idex issue
  ocs_ci/framework/pytest_customization/reports.py
Labels: Verified, team/ecosystem, size/S

#4693 Add post upgrade validation for pod ocs_metrics_exporter
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, size/XS, upgrade

#4712 Skipping the stop nodes testcases for ibmcloud
  tests/e2e/monitoring/test_monitoring_on_negative_scenarios.py
  tests/e2e/registry/test_registry_shutdown_and_recovery_node.py
  tests/e2e/workloads/amq/test_amq_node_reboot_and_shutdown.py
Labels: size/S

#4730 requre specific google-auth version - branch release-4.8
  setup.py
Labels: team/ecosystem, size/XS

#4731 requre specific google-auth version - branch release-4.7
  setup.py
Labels: team/ecosystem, size/XS

#4734 requre specific google-auth version - branch release-4.6
  setup.py
Labels: team/ecosystem, size/XS

#4090 Adding skip for some of tier4 tests for power
  tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
  tests/manage/z_cluster/nodes/test_worker_nodes_network_failures.py
Labels: size/XS

#4683 Update back constants' Ceph config values for 4.7 and below clusters
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/manage/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/S

#4733 Ignore images with the same SHA
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/S

#4729 Refine configuration values for our stale issue/pr workflow
  .github/workflows/stale.yml
Labels: team/ecosystem, size/S

#4642 Run add capacity test via cli if there is a SSL ERROR
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/ui/add_replace_device_ui.py
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/views.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Labels: Verified, size/L

#4738 delete all vdbench leftovers
  ocs_ci/ocs/constants.py
  ocs_ci/templates/workloads/vdbench/VDBench-BCurve-FS.yaml
  ocs_ci/templates/workloads/vdbench/VDBench-BCurve.yaml
  ocs_ci/templates/workloads/vdbench/VDBench-Basic-FS.yaml
  ocs_ci/templates/workloads/vdbench/VDBench-Basic.yaml
  ocs_ci/templates/workloads/vdbench/VDBench-Max-All.yaml
  ocs_ci/templates/workloads/vdbench/VDBench.yaml
  ocs_ci/templates/workloads/vdbench/vdbench_full.yaml
Labels: size/L, Squad/Gray

#4719 fix create_pod when raw block is used with no pod_dict_path
  ocs_ci/helpers/helpers.py
Labels: size/XS

#4745 Add new j-ddd prefix
  ocs_ci/cleanup/aws/defaults.py
Labels: team/ecosystem, size/XS

#4715 Adding reboot tests to scale script test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
  ocs_ci/ocs/scale_lib.py
  tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
Labels: Test Case, size/L, scale

#4743 Remove debug-only from stale workflow
  .github/workflows/stale.yml
Labels: team/ecosystem, size/XS

#4737 Add polarion ID for existing performance test
  tests/e2e/performance/test_fio_benchmark.py
  tests/e2e/performance/test_pvc_bulk_clone_performance.py
  tests/e2e/performance/test_pvc_creation_deletion_performance.py
  tests/e2e/performance/test_pvc_multi_clone_performance.py
  tests/e2e/performance/test_pvc_multi_snapshot_performance.py
  tests/e2e/performance/test_pvc_snapshot_performance.py
Labels: size/S

#4744 Update scale_pgsql with new benchmark-operator changes
  ocs_ci/ocs/scale_pgsql.py
Labels: Verified, size/XS, scale

#3754 Replace awscli-pod fixture to session level in mcg tests
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/templates/app-pods/awscli.yaml
  ocs_ci/templates/app-pods/awscli_multiarch.yaml
  tests/conftest.py
  tests/manage/mcg/test_bucket_deletion.py
  tests/manage/mcg/test_multi_region.py
  tests/manage/mcg/test_multipart_upload.py
  tests/manage/mcg/test_namespace_crd.py
  tests/manage/mcg/test_namespace_rpc.py
  tests/manage/mcg/test_write_to_bucket.py
  tests/manage/rgw/test_bucket_deletion.py
  tests/manage/rgw/test_multipart_upload.py
  tests/manage/rgw/test_object_integrity.py
Labels: Verified, size/XL, MCG

#4239 Update must_gather test for External Mode
  ocs_ci/ocs/must_gather/const_must_gather.py
Labels: Verified, size/M, External-cluster-mode, Squad/Purple

#4741 Change the condition to wait for the new osd node to come up after node replacement process
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: size/M

#4751 Must Gather test on OCS4.9
  ocs_ci/ocs/must_gather/const_must_gather.py
Labels: Verified, size/XS

#2772 Test case test_worker_node_restart_during_pvc_expansion enhancement
  tests/manage/pv_services/pvc_resize/test_node_restart_during_pvc_expansion.py
Labels: Verified, team/manage, size/M, Squad/Green

#4756 Fixing bug in ignoring same SHA iamges
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, size/XS

#4754 Catch IndexError when unable to find noobaa db pod
  ocs_ci/ocs/utils.py
Labels: team/ecosystem, size/S, MCG

#4735 Fix upgrade for IBM Cloud ROKS cluster
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/secret.py
Labels: Verified, team/ecosystem, size/L

#4739 Added debug logging before and after upgrade
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: size/XS

#4710 Implement the benchmark-operator into pvc_snapshot-performance test
  tests/e2e/performance/test_pvc_snapshot_performance.py
Labels: size/L

#4759 fix benchmark test from run for indefinitely
  ocs_ci/ocs/perftests.py
Labels: bug, Verified, size/M, performance, Squad/Gray

#4777 Add namespace parameter to snapshot test case
  tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot.py
Labels: High Priority, size/XS, Squad/Green

#4747 Installation of vSphere UPI cluster behind proxy via Flexy
  conf/README.md
  conf/deployment/aws/upi_1az_rhcos_3m_3w_proxy.yaml
  conf/deployment/aws/upi_3az_rhcos_3m_3w_proxy.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_proxy.yaml
  conf/ocsci/aws_upi_flexy_rhcos_3m_3w_proxy.yaml
  ocs_ci/deployment/factory.py
  ocs_ci/deployment/flexy.py
  ocs_ci/deployment/vmware.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/helpers/proxy.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/utility/flexy.py
  ocs_ci/utility/proxy.py
Labels: team/ecosystem, size/L

#4773 improvements to test_pvc_attachtime.py
  tests/e2e/performance/test_pvc_attachtime.py
Labels: size/L, performance

#4750 Deployment and Add capacity tests via UI on Azure Internal cluster
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/S

#4749 Change all timeoutsamplars of wl_setup_done from 180 to 360 in relevant tests
  tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py
  tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_and_io.py
  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_deletion_and_io.py
  tests/manage/pv_services/test_pvc_disruptive.py
  tests/manage/pv_services/test_rbd_thick_provisioning.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: size/S

#4788 Adding retry mechanism for setup_persistent_monitoring
  ocs_ci/deployment/deployment.py
Labels: Needs Deployment Testing, team/ecosystem, size/XS

#4768 Add VAULT_BACKEND parameter as a work around for BZ 1997624
  ocs_ci/ocs/defaults.py
  ocs_ci/templates/CSI/rbd/csi-kms-connection-details.yaml
  ocs_ci/utility/kms.py
  tests/manage/pv_services/test_rbd_pv_encryption.py
Labels: Verified, workaround, size/S

#4772 Autoscale scale test case improvement.
  ocs_ci/ocs/scale_noobaa_lib.py
  tests/e2e/scale/noobaa/test_scale_endpoint.py
Labels: Needs Testing, size/L, scale

#4785 Increase time for AWS cleanup job
  ocs_ci/cleanup/aws/defaults.py
Labels: team/ecosystem, workaround, size/XS
