Repository red-hat-storage/ocs-ci, pull requests merged in 2021-04, with the labels that each got.

#4084 Update base install-config file for BM
  ocs_ci/templates/ocp-deployment/install-config-baremetal-upi.yaml.j2
Labels: Verified, size/XS

#4082 Add PrometheusRuleFailures alert test
  ocs_ci/ocs/constants.py
  tests/manage/monitoring/prometheus/test_alerting_works.py
Labels: Verified, size/S

#4076 Ypersky - pvc creation deletion performance
  ocs_ci/helpers/performance_lib.py
  tests/e2e/performance/test_pvc_creation_deletion_performance.py
  tests/e2e/performance/test_pvc_deletion_performance.py
  tests/e2e/performance/test_pvc_multiple_creation_performance.py
Labels: performance, size/XL

#4094 OC download fixes
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: Merge As Is (Dont Squash), enhancement, size/M, team/ecosystem

#3957 Test case - RBD thick provisioned PVC
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  tests/conftest.py
  tests/manage/pv_services/test_rbd_thick_provisioning.py
Labels: Test Case, Verified, size/L, team/manage

#4081 Skip capacity tests due to bz 1943137
  tests/manage/monitoring/prometheus/test_capacity.py
Labels: Skip test, size/XS

#3971 Remove unsafe access to potentially-unbound cld_mgr client attributes
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/utility/tests/test_utils.py
  ocs_ci/utility/utils.py
Labels: MCG, Needs Testing, size/L

#4107 Ypersky clone perf lib adjustment
  tests/e2e/performance/test_pvc_multi_clone_performance.py
Labels: performance, size/L

#4036 Configuration to install compact mode cluster
  conf/deployment/baremetal/upi_1az_rhcos_compact_mode.yaml
Labels: Verified, size/S

#4112 Start using Memory leak function
  tests/e2e/scale/test_pv_scale_ocs_create_delete_pvcs.py
Labels: High Priority, enhancement, scale, size/S

#4061 Change Instance type to m4.4xlarge in conf/deployment/aws/ipi_6az_rhcos_3m_6w.yaml
  conf/deployment/aws/ipi_6az_rhcos_3m_6w.yaml
Labels: size/XS

#4095 Add support multiple daemons on one worker node [coredump test]
  ocs_ci/helpers/helpers.py
  tests/manage/z_cluster/test_coredump_check_for_ceph_daemon_crash.py
Labels: Verified, size/XS

#3955 MCG Cache Bucket Tier1
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/resources/bucketclass.py
  ocs_ci/ocs/resources/mcg.py
  tests/manage/mcg/test_namespace_crd.py
  tests/manage/mcg/test_object_integrity.py
Labels: MCG, Verified, size/L

#4087 Pass NSS list instead of object in `test_namespace_bucket_creation_with_many_resources_crd`
  tests/manage/mcg/test_namespace_crd.py
Labels: MCG, Verified, size/XS

#4121 OCP 4.8 upgrade config file
  ocs_ci/framework/conf/ocp_version/ocp-4.8-upgrade.yaml
Labels: size/XS, team/ecosystem

#4104 Function To scale pods using Kube_Job, DC and attach multiple PVCs
  ocs_ci/ocs/scale_lib.py
Labels: High Priority, Verified, scale, size/L

#4123 Enable Flexible Scaling on LSO cluster
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/M

#3976 add must_gather test for OCS4_7
  ocs_ci/ocs/must_gather/const_must_gather.py
  ocs_ci/ocs/must_gather/must_gather.py
Labels: Verified, size/M

#4101 Test for unsigned access of namespace bucket
  tests/manage/mcg/test_namespace_crd.py
Labels: MCG, Verified, size/M

#4117 Modify NSS_MAPPING's get_attr_chain usage to be safer
  ocs_ci/ocs/resources/mcg.py
Labels: Verified, size/XS

#4116 Initialize RGW cloud client as None in case regular init failed
  ocs_ci/ocs/resources/cloud_manager.py
Labels: Verified, size/XS

#4088 Fix registry for non OCS-CI OCP deployed clusters
  ocs_ci/deployment/deployment.py
  ocs_ci/utility/utils.py
Labels: Verified, size/S, team/ecosystem

#4115 Added --skip-download-client CLI option
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: Verified, size/S, team/ecosystem

#4135 Adding OCP 4.8 repo
  ocs_ci/repos/ocp_4_8.repo
Labels: size/M, team/ecosystem

#4113 Explicitly set log level for reportportal_client logger
  conf/README.md
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: size/S, team/ecosystem

#4114 Added doc for skip_download_client config
  conf/README.md
Labels: documentation, size/XS, team/ecosystem

#4111 Enhance TC scale/test_ceph_pod_respin_in_scaled_cluster.py to use kube_job for pod creation
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/scale_lib.py
  tests/e2e/scale/test_ceph_pod_respin_in_scaled_cluster.py
  tests/e2e/scale/test_scale_pvc_expand.py
Labels: High Priority, Verified, enhancement, scale, size/L

#4122 Cust issue: Test for changing default scc on noobaa db
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  tests/manage/mcg/test_mcg_resources_disruptions.py
Labels: Verified, size/L, team/e2e

#4137 Increase PVC provisioning timeout in test test_rbd_thick_provisioning
  tests/manage/pv_services/test_rbd_thick_provisioning.py
Labels: High Priority, Verified, size/XS, team/manage

#3933 Tests to verify PVC creation after deleting mon services manually
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  tests/manage/pv_services/test_del_mon_service_and_create_pvc.py
Labels: Test Case, Verified, size/L, team/e2e

#4130 Adding vSphere IPI config files
  conf/deployment/vsphere/ipi_1az_rhcos_vmfs_3m_3w.yaml
  conf/ocsci/vsphere_ipi.yaml
Labels: size/S, team/ecosystem

#4089 RBD thick provisioning - verify PVC expansion, snapshot and clone
  ocs_ci/helpers/helpers.py
  tests/manage/pv_services/conftest.py
  tests/manage/pv_services/test_expansion_snapshot_clone.py
Labels: Test Case, Verified, size/L, team/manage

#4086 Creating KMS config
  conf/ocsci/kms_deployment.yaml
Labels: size/XS

#4149 Fix must gather tests
  ocs_ci/ocs/must_gather/const_must_gather.py
  ocs_ci/ocs/must_gather/must_gather.py
Labels: Verified, size/XS

#4124 Recreate DNS record at the time of BM Install
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/aws.py
Labels: Verified, enhancement, size/L

#4146 Add timeout sampler to verify cached objects
  ocs_ci/ocs/bucket_utils.py
  tests/manage/mcg/test_namespace_crd.py
Labels: MCG, Verified, size/M

#4020 Install lso cluster + encryption via UI
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/helpers/lso_helpers.py
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Needs Testing, Verified, size/L

#4142 Add ocs build utility
  docs/usage.md
  ocs_ci/utility/ocs_build.py
  setup.py
Labels: enhancement, size/M, team/ecosystem

#4165 Skip tests/e2e/scale/test_scale_amq.py TC due to issue #3372
  tests/e2e/scale/test_scale_amq.py
Labels: High Priority, bug, scale, size/XS

#3859 Update node replacement process to be compatible with OCP 4.7
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/pv.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Verified, size/L

#4145 add the test of adding a new worker node on vSphere platform
  tests/manage/z_cluster/cluster_expansion/conftest.py
Labels: size/M

#4048 Check whether all nodes are created after OCP deployment
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/node.py
Labels: Verified, size/S, team/ecosystem

#3871 Noobaa scale obc creation
  ocs_ci/ocs/scale_noobaa_lib.py
  tests/e2e/scale/noobaa/test_scale_obc_creation.py
Labels: MCG, Verified, scale, size/L

#4168 Fix OCP upgrade
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.3-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.4-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.5-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.6-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.7-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.8-upgrade.yaml
Labels: Verified, size/S

#4102 Test "add capacity" via UI on tier1 suite
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/M

#4173 Remove elastic search usage from Scale tests
  ocs_ci/ocs/small_file_workload.py
  tests/e2e/scale/test_scale_small_file_workload.py
Labels: High Priority, Verified, scale, size/XS

#4132 Test to verify rgw kafka notifications
  ocs_ci/ocs/amq.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/workloads/amq/kafkadrop.yaml
  ocs_ci/utility/utils.py
  tests/e2e/workloads/amq/test_rgw_kafka_notifications.py
Labels: Verified, size/L

#4163 Enable health check for performance, scale and workload markers
  ocs_ci/framework/pytest_customization/marks.py
Labels: Verified, size/S, team/ecosystem

#4164 Add Chrony related files at the time of OCP deployment
  conf/README.md
  ocs_ci/deployment/baremetal.py
  ocs_ci/deployment/vmware.py
  ocs_ci/framework/conf/ocp_version/ocp-4.4-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.4-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.5-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.5-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.5-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.6-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.6-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.6-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.7-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.7-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.7-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.8-config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocp-deployment/99-role-chrony-configuration.yaml
  ocs_ci/utility/utils.py
Labels: Verified, enhancement, size/M

#4184 Add BM Config Files for OCP 4.8
  ocs_ci/templates/ocp-deployment/rhcos_images.yaml
Labels: Verified, size/XS

#4182 Adding infra nodes in verify_all_nodes_created function
  ocs_ci/ocs/node.py
Labels: Verified, size/XS, team/ecosystem

#4176 Template check for vsphere
  ocs_ci/deployment/helpers/prechecks.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/vsphere.py
Labels: size/M, team/ecosystem

#4100 Add RHV Platform support for testing
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/rhv.py
Labels: Verified, size/M

#4200 Define MCG code owners
  .github/CODEOWNERS
Labels: size/XS

#4217 Download openshift client while setting kubeconfig if needed
  ocs_ci/ocs/openshift_ops.py
Labels: Verified, size/XS, team/ecosystem

#4150 Azure Scale: Enhancement to add custom_machineset/node which will be used to running app pods
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/scale_lib.py
  ocs_ci/templates/openshift-infra/machineset-azure.yaml
Labels: High Priority, Verified, enhancement, scale, size/L

#4220 Use `verify_health()` in test_noobaa
  tests/ecosystem/upgrade/test_noobaa.py
Labels: MCG, size/S

#4157 Skip on failure domain verification on upgraded lso cluster
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S

#4221 Remove test_noobaa verify_health() assertions
  tests/ecosystem/upgrade/test_noobaa.py
Labels: MCG, size/S

#4223 Fix to remove added machinesets and nodes in Azure
  ocs_ci/ocs/scale_lib.py
Labels: High Priority, Verified, bug, scale, size/XS

#4208 add AWS disconnected and proxy deployment production configs
  conf/deployment/aws/upi_1az_rhcos_3m_3w_disconnected.yaml
  conf/deployment/aws/upi_1az_rhcos_3m_3w_proxy.yaml
  conf/deployment/aws/upi_3az_rhcos_3m_3w_disconnected.yaml
  conf/deployment/aws/upi_3az_rhcos_3m_3w_proxy.yaml
Labels: Verified, size/M, team/ecosystem

#4218 Support multiple UI tests
  ocs_ci/ocs/ui/base_ui.py
Labels: Verified, size/XS

#4197 Fix `skipif_ocs_version` logic
  ocs_ci/utility/utils.py
Labels: Verified, size/XS

#4199 Skip RGW alerting test due to bz 1953615
  tests/manage/monitoring/prometheus/test_rgw.py
Labels: Skip test, size/XS

#4219 Add vsphere/aws ocs with vault production yamls
  conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_external_with_namespace.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_external_vault_with_namespace.yaml
Labels: size/M
