Repository red-hat-storage/ocs-ci, pull requests merged in 2021-05, with the labels that each got.

#4188 Skip endpoint_autoscale test when running on OCS 4.7+
  tests/manage/mcg/test_endpoint_autoscale.py
Labels: MCG, Verified, size/XS

#4195 Add cache-dropper pod to the benchmark-operator base tests
  ocs_ci/ocs/ripsaw.py
Labels: performance, size/S

#4253 Adding Osd cache drop for performance tests
  Docker_files/osd_cache_dropping
  ocs_ci/ocs/resources/cache_drop.py
  ocs_ci/templates/workloads/fio/drop_cache_pod.yaml
Labels: performance, size/L

#4257 Skip test over external mode cluster
  tests/e2e/workloads/amq/test_rgw_kafka_notifications.py
Labels: size/XS

#4193 Add function for adding new LSO UPI worker node
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/cluster_expansion/conftest.py
Labels: size/M

#4175 Reduce the number of app pods in tests which run fio simultaneously
  ocs_ci/helpers/helpers.py
  tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py
  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_deletion_and_io.py
  tests/manage/pv_services/test_pvc_disruptive.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: Squad/Green, Verified, size/M, team/manage

#4260 Fix get_osd_count for upgrade of external cluster
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/ecosystem/upgrade/test_upgrade.py
Labels: Verified, size/M, team/ecosystem

#4242 Ability to use Diff POD n/w
  conf/ocsci/enable_diff_pod_nw.yaml
  ocs_ci/templates/ocp-deployment/install-config-baremetal-upi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-vsphere-upi.yaml.j2
Labels: Verified, enhancement, size/S

#4240 Remove nodename when creating hsbench-pod.
  ocs_ci/ocs/hsbench.py
Labels: Verified, scale, size/XS

#4225 Add additonal FIO workload to trigger Noobaa autoscale
  tests/e2e/scale/noobaa/test_scale_endpoint.py
  tests/manage/mcg/test_endpoint_autoscale.py
Labels: MCG, Verified, scale, size/S

#4258 Adding rgw annotation to bucket_size test if upgraded from OCS 4.6
  tests/manage/rgw/test_object_bucket_size.py
Labels: Verified, size/S, team/e2e

#4179 Modify test_check_mon_pdb_post_upgrade with the new mon pdb changes
  ocs_ci/helpers/helpers.py
  tests/ecosystem/upgrade/test_upgrade.py
  tests/manage/z_cluster/upgrade/test_check_mon_pdb_post_upgrade.py
Labels: Verified, size/M

#4059 Handle remote execution scenario for services
  ocs_ci/utility/powernodes.py
  ocs_ci/utility/service.py
Labels: size/M

#4255 Increase timeout for pod status check
  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_and_io.py
  tests/manage/pv_services/test_pvc_disruptive.py
Labels: Verified, size/S

#4270 Added arguments for ignore ssl
  ocs_ci/ocs/ui/base_ui.py
Labels: Verified, size/XS

#4265 Define OCS-CI CODEOWNERS by squads
  .github/CODEOWNERS
Labels: size/S

#4224 Update device replacement test to be compatible with OCS 4.7
  ocs_ci/ocs/constants.py
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/M

#4252 Extend the node replacement verification steps to work with more than 3 OSDs
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Verified, size/M

#4269 Adding fixture for cleanup function.
  ocs_ci/ocs/scale_noobaa_lib.py
  tests/e2e/scale/noobaa/test_scale_obc_creation.py
Labels: Verified, scale, size/S

#4279 Github actions: install libcurl4-openssl-dev package
  .github/workflows/pr_checks.yml
Labels: size/XS, team/ecosystem

#4192 Add ovirt sdk python package in virtual env of ocs-ci execution
  setup.py
Labels: size/XS

#4262 Skip version comparison and download if unable to expose the OCP version
  ocs_ci/utility/utils.py
Labels: size/S, team/ecosystem

#4091 Add quickstart tests for UI
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
  tests/ui/test_quickstarts.py
Labels: size/M

#4291 Disconnected instalation from live: wait for machineconfig status
  ocs_ci/deployment/disconnected.py
Labels: Verified, size/XS, team/ecosystem

#4303 Use equality instead of identity checks
  ocs_ci/ocs/amq.py
Labels: size/XS, team/ecosystem

#4281 run load_cluster_info_file before cluster_load
  ocs_ci/utility/utils.py
Labels: Verified, size/XS, team/ecosystem

#4154 Check RBD thick storage class in install verification
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/XS

#4298 Fix Must Gather test, add node names [BM,Azure]
  ocs_ci/ocs/must_gather/must_gather.py
Labels: Verified, size/M

#4294 Skipping noobaa cache test on ocs 4.6
  tests/manage/mcg/test_object_integrity.py
Labels: High Priority, MCG, Skip test, Verified, size/XS

#4312 Remove test_git_clone from acceptance suite
  tests/e2e/workloads/test_jenkins_simulation.py
Labels: size/XS

#4321 Retry configuring storage for image registry
  ocs_ci/deployment/baremetal.py
Labels: Verified, size/XS

#4323 Update doc sections about UI testing
  docs/getting_started.md
  docs/usage.md
Labels: size/S

#4326 Wait till toolbox pod will come up
  ocs_ci/ocs/utils.py
Labels: size/XS, team/ecosystem

#4316 Update defaults to OCS 4.8
  ocs_ci/framework/conf/default_config.yaml
Labels: size/S, team/ecosystem

#4309 Include ignition_version in default_config.yaml
  ocs_ci/framework/conf/default_config.yaml
Labels: size/XS, team/ecosystem

#4127 Adding option for setting up elasticsearch server for performance tests
  docs/getting_started.md
  ocs_ci/framework/__init__.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/perfresult.py
  ocs_ci/ocs/perftests.py
  ocs_ci/templates/workloads/fio/benchmark_fio.yaml
  ocs_ci/templates/workloads/fio/benchmark_fio_cmp.yaml
  tests/e2e/performance/test_fio_benchmark.py
  tests/e2e/performance/test_small_file_workload.py
Labels: Verified, performance, size/XL

#4327 Adding OCP 4.9 config, upgrade and repo files
  ocs_ci/framework/conf/ocp_version/ocp-4.9-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.9-upgrade.yaml
  ocs_ci/repos/ocp_4_9.repo
Labels: size/M, team/ecosystem

#4229 Check all noobaa pod are up before creation of OBC
  tests/manage/rgw/test_host_node_failure.py
Labels: Verified, size/M

#4148 Flexible component deployment
  conf/README.md
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/__init__.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/main.py
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/L, team/ecosystem

#4332 Must-gather test on OCS4.8
  ocs_ci/ocs/must_gather/const_must_gather.py
Labels: Verified, size/XS

#4243 Update test_del_mon_service_and_create_pvc.py to be compatible with LSO cluster
  tests/manage/pv_services/test_del_mon_service_and_create_pvc.py
Labels: Verified, size/S

#4314 Update add capacity tests
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
  tests/manage/z_cluster/cluster_expansion/test_delete_pod.py
Labels: Verified, size/M

#4330 Push pvc_create_delete perf. results into ES server
  tests/e2e/performance/test_pvc_creation_deletion_performance.py
Labels: size/L

#4340 Update osd tree verification steps when we use flexible scaling
  ocs_ci/ocs/cluster.py
Labels: Verified, size/L

#4311 Combine 3 test case of coredump test
  ocs_ci/framework/pytest_customization/marks.py
  tests/manage/z_cluster/test_coredump_check_for_ceph_daemon_crash.py
Labels: Verified, size/L

#4324 Testcase: Delete RBD PVC and provisioner while thick provisioning is progressing
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  tests/manage/pv_services/test_delete_pvc_while_provisioning.py
Labels: Squad/Green, Test Case, Verified, size/L, team/manage
