Repository red-hat-storage/ocs-ci, pull requests merged in 2021-06, with the labels that each got.

#4344 change cluster-launcher repo to v4-scaleup
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/S, team/ecosystem

#4204 [RHV] Define all arguments with default values
  ocs_ci/utility/rhv.py
Labels: Verified, enhancement, size/S

#4345 Add --re-trigger-failed-tests parameter
  docs/usage.md
  ocs_ci/framework/pytest_customization/ocscilib.py
  setup.py
Labels: Verified, size/M, team/ecosystem

#4288 Fix checking number of nodes on IMB Cloud
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
Labels: Verified, size/XS, team/ecosystem

#4351 Enable add node for tier1 over Vmware IPI
  tests/manage/z_cluster/cluster_expansion/conftest.py
Labels: Verified, size/M

#4359 Push version of terraform to 0.11.15
  ocs_ci/framework/conf/ocp_version/ocp-4.2-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.2-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.3-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.3-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.4-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.4-ga-config.yaml
Labels: size/S, team/ecosystem

#4356 Mon PDB changes applied to 4.6.5
  tests/manage/z_cluster/upgrade/test_check_mon_pdb_post_upgrade.py
Labels: Verified, size/XS

#4337 update doc with requirements for ovirt-engine-sdk
  docs/getting_started.md
Labels: size/XS, team/ecosystem

#4363 Don't add ignition_version for OCP 43
  ocs_ci/deployment/vmware.py
Labels: size/XS, team/ecosystem

#4347 Skip test_rgw_host_node_failure for vsphere IPI platform
  tests/manage/rgw/test_host_node_failure.py
Labels: size/XS, team/ecosystem

#4180 remove deprecated registry.svc.ci.openshift.org and use registry.ci.o…
  conf/ocsci/flexy_baremetalpsi_upi.yaml
Labels: size/XS

#4119 GSS-BUG: Generate heap profile dump file for OSD
  tests/manage/z_cluster/test_osd_heap_profile.py
Labels: Customer defects, Verified, size/M

#4368 Increase timeout for generating CSR's
  ocs_ci/deployment/vmware.py
Labels: Verified, size/XS, team/ecosystem

#4365 Fixing docstring in update_hosted_zone_record
  ocs_ci/utility/aws.py
Labels: size/XS, team/ecosystem

#4292 OCS4.6/4.8 Installation via UI
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/views.py
Labels: size/L

#4249 Cosbench workload for MCG
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/cosbench.py
  ocs_ci/templates/workloads/cosbench/cosbench_configmap.yaml
  ocs_ci/templates/workloads/cosbench/cosbench_pod.yaml
  tests/e2e/workloads/cosbench/test_cosbench.py
Labels: MCG, Verified, size/XL, team/e2e

#4205 [RHV] Add function to stop RHV nodes
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/rhv.py
  tests/libtest/test_rhv.py
Labels: Verified, enhancement, size/L

#3831 Revert increased PV deletion timeout for Azure platform
  tests/conftest.py
Labels: Verified, size/XS

#4336 Validates mon_max_pg_per_osd on ceph cluster
  ocs_ci/ocs/cluster.py
  tests/manage/z_cluster/test_ceph_default_values_check.py
Labels: Customer defects, Verified, size/M, team/e2e

#4250 UI validation test tier1
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/ui/views.py
  ocs_ci/utility/utils.py
  tests/conftest.py
  tests/ui/test_validation_ui.py
Labels: Verified, size/L

#4384 extend test_read_cached_object ttl
  ocs_ci/ocs/bucket_utils.py
  tests/manage/mcg/test_namespace_crd.py
Labels: MCG, bug, size/XS

#4390 Add updateStrategy for catalogSource
  ocs_ci/templates/ocs-deployment/catalog-source.yaml
Labels: enhancement, size/XS, team/ecosystem

#4381 Few more dependency packages to be listed in getting started doc
  docs/getting_started.md
Labels: size/S

#4377 Add rhel_workers to all configs with RHEL
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_lso_directpath_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_lso_rdm_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vmfs_lso_vmdk_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_lso_directpath_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_lso_rdm_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhel_vsan_lso_vmdk_3m_3w.yaml
  conf/ocsci/vsphere_scale_cluster.yaml
Labels: size/S, team/ecosystem

#4370 io - Remove performance marker
  tests/e2e/performance/test_io_performance.py
Labels: size/XS

#4392 Increased the CSI log timout to 6mins to add more wait for PVC creation data in CSI logs
  ocs_ci/helpers/helpers.py
Labels: High Priority, bug, scale, size/XS

#4407 Change openshift-release.svc.ci.openshift.org to amd64.ocp.releases.ci.openshift.org
  ocs_ci/utility/utils.py
Labels: Verified, size/XS, team/ecosystem

#4401 Donot check svc site when skipping download
  ocs_ci/utility/utils.py
Labels: Verified, size/XS, team/ecosystem

#4402 Increase timeout in the test 'test_add_capacity'
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Labels: size/XS

#4411 Handling new CSR for OCP 4.8 deployments
  ocs_ci/utility/csr.py
Labels: Verified, size/XS, team/ecosystem

#4374 destroy_cluster and deploy_ocp methods of vSphereIPI should be under its own class
  ocs_ci/deployment/vmware.py
Labels: Verified, size/M, team/ecosystem

#4397 Added some info around our usage of black in our coding guidelines doc
  docs/coding_guidelines.md
Labels: documentation, size/XS, team/ecosystem

#4386 Fix leftover errors in amq
  ocs_ci/ocs/amq.py
Labels: Verified, size/M

#4388 ClusterLoad: fix timeout condition while determining the cluster IOPS limit
  ocs_ci/ocs/cluster_load.py
Labels: Verified, bug, size/S

#4417 Use catalogSource secrets directly
  ocs_ci/deployment/deployment.py
Labels: Verified, enhancement, size/XS, team/ecosystem

#4353 Add function to start RHV Nodes
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/rhv.py
  tests/libtest/test_rhv.py
Labels: Verified, enhancement, size/M

#4335 Disconnected cluster: prepare installation of cluster-logging operator
  ocs_ci/deployment/disconnected.py
  ocs_ci/deployment/flexy.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/L, team/ecosystem

#4396 Add retry decorator on login_ui function
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/M

#4422 Change openshift-release.svc.ci.openshift.org to amd64.ocp.releases.ci.openshift.org
  ocs_ci/utility/utils.py
Labels: size/XS, team/ecosystem

#4423 Change openshift-release.svc.ci.openshift.org to amd64.ocp.releases.ci.openshift.org
  ocs_ci/utility/utils.py
Labels: size/XS, team/ecosystem

#4424 Change openshift-release.svc.ci.openshift.org to amd64.ocp.releases.ci.openshift.org
  ocs_ci/utility/utils.py
Labels: size/XS, team/ecosystem

#4333 Remove cpu and memory limits for ceph pods
  ocs_ci/deployment/deployment.py
Labels: High Priority, Verified, size/XS

#4409 Cleanup old unused state deployment related code
  conf/ocsci/stage.yaml.example
  ocs_ci/deployment/deployment.py
Labels: Verified, size/M, team/ecosystem

#4406 Ensure that email with test results is send even in case of failure in sessionfinish
  ocs_ci/utility/utils.py
Labels: Verified, size/S, team/ecosystem

#4413 Fix test_create_storageclass_with_same_name to initiate SC delete only if it is created
  tests/manage/storageclass/test_create_storageclass_with_same_name.py
Labels: Squad/Green, Verified, size/XS, team/manage

#4391 Implement UI MCG tests
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/objectbucket.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
  ocs_ci/ocs/utils.py
  tests/manage/mcg/ui/test_mcg_ui.py
Labels: MCG, Verified, size/XL, ui_testing

#4315 Test to create new compressed sc and their support for snapshot-clone
  tests/e2e/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py
Labels: Verified, size/L

#4284 Timestamp displayed in the bucket event notifications received
  tests/e2e/workloads/amq/test_rgw_kafka_notifications.py
Labels: Verified, size/M

#4054 Enhancements for pv_services/test_rwo_pvc_fencing_unfencing.py
  ocs_ci/framework/pytest_customization/marks.py
  tests/conftest.py
  tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
Labels: Squad/Green, Verified, size/L, team/manage

#4438 Fix doc depe issue
  .readthedocs.yaml
Labels: Verified, size/S, team/ecosystem

#4421 Improve logic to restart nodes when IP's are not generated
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/csr.py
  ocs_ci/utility/vsphere.py
Labels: Verified, size/M, team/ecosystem

#4366 Adding filesystem parameter for chrony based on ignition version
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/utils.py
Labels: Verified, size/S, team/ecosystem

#4435 Adding environment variable HOSTS_SCRIPT_DIR for AWS UPI deployment
  ocs_ci/deployment/aws.py
Labels: Verified, size/XS, team/ecosystem

#4382 Check rook ceph pods status after a node failure event
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/nodes/test_check_pods_status_after_node_failure.py
Labels: Test Case, size/L

#4446 Avoid logging object into console
  ocs_ci/deployment/helpers/lso_helpers.py
Labels: team/ecosystem

#4319 Automate bz#1840539:
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: size/M

#4456 Fixed timeout to match the value in a similar call in a helper class.
  ocs_ci/helpers/pvc_ops.py
  tests/e2e/scale/test_cephfs_many_files.py
Labels: size/XS

#4434 mpu operations on namespace cache bucket
  tests/e2e/lifecycle/mcg/test_mcg_namespace_s3_ops_crd.py
Labels: MCG, Verified, size/S, team/e2e

#4395 fix delete_cluster_buckets function
  ocs_ci/utility/aws.py
Labels: Verified, size/XS, team/ecosystem

#4362 [RHV] Add function to reboot RHV VMs
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/rhv.py
Labels: Verified, enhancement, size/M

#4296 Add RBD thick provision verification in test
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/resources/pvc.py
  tests/manage/pv_services/test_expansion_snapshot_clone.py
Labels: Squad/Green, Verified, enhancement, size/L, team/manage

#4444 improve performance for prechecks in vSphere platform
  ocs_ci/deployment/helpers/prechecks.py
  ocs_ci/utility/vsphere.py
Labels: Verified, size/M, team/ecosystem

#4300 Testcase-Verify rbd provisioner pod deletion will not break thick provisioning
  ocs_ci/helpers/disruption_helpers.py
  tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
Labels: Squad/Green, Test Case, Verified, size/L, team/manage

#4451 Load report portal settings only when option is enabled
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: size/XS, team/ecosystem

#4447 Conditions for installing the OCS operator via UI
  docs/usage.md
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/ui/deployment_ui.py
Labels: size/M

#4203 Scale noobaa namespace test cases
  ocs_ci/ocs/hsbench.py
  ocs_ci/templates/workloads/hsbench/hsbench_obj.yaml
  tests/e2e/scale/noobaa/test_hsbench.py
  tests/e2e/scale/noobaa/test_scale_namespace_crd.py
  tests/e2e/scale/noobaa/test_scale_namespace_rpc.py
Labels: MCG, Verified, scale, size/L

#4334 GSS bug bz1830215 automation
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Customer defects, Verified, size/S, team/e2e

#4459 Flexy deployment: use common configuration parameters
  conf/deployment/aws/upi_1az_rhcos_3m_3w_disconnected.yaml
  conf/deployment/aws/upi_1az_rhcos_3m_3w_proxy.yaml
  conf/deployment/aws/upi_3az_rhcos_3m_3w_disconnected.yaml
  conf/deployment/aws/upi_3az_rhcos_3m_3w_proxy.yaml
  conf/ocsci/aws_upi_flexy_rhcos_3m_3w_disconnected.yaml
  conf/ocsci/aws_upi_flexy_rhcos_3m_3w_proxy.yaml
  ocs_ci/deployment/flexy.py
  ocs_ci/framework/conf/default_config.yaml
Labels: size/M, team/ecosystem

#4348 OSD device replacement fixes for ocs 4.8
  ocs_ci/ocs/osd_operations.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/L

#4408 Test for PVC creation and deletion from UI
  ocs_ci/ocs/resources/pvc.py
  ocs_ci/ocs/ui/pvc_ui.py
  ocs_ci/ocs/ui/views.py
  tests/conftest.py
  tests/ui/test_pvc_ui.py
Labels: size/L

#4427 Increase PVC creation timeout in test test_rbd_thick_provisioning
  tests/manage/pv_services/test_rbd_thick_provisioning.py
Labels: Squad/Green, Verified, size/XS, team/manage

#4414 Fix test case test_pv_creation to skip PVC and yaml file deletion based on its existence
  tests/manage/pv_services/test_pv_creation.py
Labels: Squad/Green, Verified, size/XS, team/manage

#4461 Add function to enable huge pages
  conf/README.md
  conf/ocsci/enable_huge_pages.yaml
  docs/usecases/enable_huge_pages.md
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocp-deployment/huge_pages.yaml
  ocs_ci/utility/utils.py
Labels: Verified, enhancement, size/M, team/ecosystem

#4371 [RHV] Add function to start -down nodes of a cluster
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/rhv.py
Labels: Verified, enhancement, size/M

#4466 aws: update delete_cluster_buckets
  ocs_ci/utility/aws.py
Labels: Verified, size/XS, team/ecosystem

#4476 Fixing OCP 4.7 installation
  ocs_ci/deployment/vmware.py
Labels: Verified, size/XS, team/ecosystem

#4464 Add patterns to must-gather test
  ocs_ci/ocs/must_gather/must_gather.py
Labels: Verified, size/S

#4480 Fixing OCP 4.7 installation
  ocs_ci/deployment/vmware.py
Labels: size/XS, team/ecosystem

#4481 Fixing OCP 4.7 installation
  ocs_ci/deployment/vmware.py
Labels: size/XS, team/ecosystem

#4482 Adding fsync in the end to fio command
  ocs_ci/templates/workloads/fio/workload_io_fillup.yaml
Labels: High Priority, bug, size/XS

#4453 Testcase to check mds cache memory limit post ocs upgrade
  ocs_ci/ocs/cluster.py
  tests/manage/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/M

#4454 Prepare optional-operators for installation on disconnected cluster
  conf/README.md
  ocs_ci/deployment/disconnected.py
  ocs_ci/deployment/helpers/lso_helpers.py
Labels: Verified, size/L, team/ecosystem

#4462 Adding limits for AWS i3 platform for storageDeviceSets
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
Labels: size/S, team/ecosystem

#4394 Dynamic installation of vSphere IPI cluster
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/aws.py
  ocs_ci/utility/ipam.py
Labels: Merge As Is (Dont Squash), Verified, size/L, team/ecosystem

#4465 fix "skipif_ui" decorator
  ocs_ci/utility/utils.py
Labels: size/XS

#4436 Adding support for rbd thick provisioning to test_pvc_creation_deletion_performance.py
  ocs_ci/helpers/helpers.py
  ocs_ci/helpers/performance_lib.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
  tests/e2e/performance/test_pvc_creation_deletion_performance.py
Labels: performance, size/L

#4483 move coredump test from "tier1" to "tier2"
  tests/manage/z_cluster/test_coredump_check_for_ceph_daemon_crash.py
Labels: size/XS
