Repository red-hat-storage/ocs-ci, pull requests merged in 2022-08, with the labels that each got.

#6248 Add support for WaitForFirstConsumer to storageclass
  ocs_ci/helpers/helpers.py
  tests/conftest.py
  tests/manage/storageclass/test_new_sc_rbd_replica2_3.py
Labels: Needs Testing, size/M

#6197 Fix issue#6189- Woraround for MS post deplyment test inconsitent issue
  tests/ecosystem/deployment/test_deployment.py
Labels: Verified, workaround, size/S, Managed Services

#5974 close loop 2039265: Check Test pvc cloned status of small size files
  tests/manage/pv_services/pvc_snapshot/test_small_files_pvc_cloned_status.py
Labels: Verified, team/e2e, size/L, Customer defects

#6233 Add squad marker decorator values to junit item properties
  tests/conftest.py
Labels: Verified, team/ecosystem, size/S

#6252 user configurable cephfs for external cluster deployments
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/XS

#6237 use dry-run with client
  ocs_ci/utility/pagerduty.py
  ocs_ci/utility/users.py
Labels: Verified, team/ecosystem, size/XS, Managed Services

#6257 In the test "test_nodes_restart" use "SanityExternalCluster" in case we use the external mode
  tests/manage/z_cluster/nodes/test_nodes_restart.py
Labels: Verified, size/S, Squad/Brown

#5934 close loop 2075068: Checks for node panic after fsync
  ocs_ci/ocs/constants.py
  ocs_ci/templates/workloads/helper_scripts/fsync.py
  tests/manage/z_cluster/nodes/test_node_kernel_crash_ceph_fsync.py
Labels: Verified, team/e2e, size/L, Customer defects

#6269 Rename rosa deployment configs with stable inead of stage iname
  conf/deployment/rosa/managed_1az_consumer_stable_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_stable_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_provider_stable_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_stable_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_stable_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_stable_3m_3w_m54x.yaml
Labels: enhancement, Verified, size/XS, Managed Services

#6267 force checkout option for cloning
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/S

#6276 Enhancements for DR helper methods
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/drpc.py
Labels: size/XL, DR

#6281 Fix UI title for OCP4.11 in pre-ACM Login
  ocs_ci/ocs/ui/views.py
Labels: size/XS

#6260 Update ACM 2.5 image to 2.5.2
  conf/examples/acm_hub_unreleased_image.yaml
  ocs_ci/framework/conf/default_config.yaml
Labels: size/XS

#6274 Added new template file, for small disks lvmo installation
  ocs_ci/templates/lvmo-deployment/lvmo_deployment_3_disk_X_75GB
Labels: size/XS

#6261 Check if content-encoding is being stored as object metadata on s3 put
  ocs_ci/ocs/bucket_utils.py
  tests/manage/mcg/test_write_to_bucket.py
Labels: Verified, team/e2e, size/M, Customer defects

#6116 Test nodes restart scenarios using the Managed Service
  tests/manage/z_cluster/nodes/test_nodes_restart_ms.py
Labels: Verified, size/L, Managed Services

#6285 Fix the condition to get file path on pod
  tests/manage/pv_services/pvc_clone/test_node_restart_during_pvc_clone.py
Labels: Verified, size/XS, Squad/Green

#6238 TC pvc_bulk_clone performance improvement
  tests/e2e/performance/csi_tests/test_pvc_bulk_clone_performance.py
Labels: Verified, size/L, performance

#6298 wait for install-complete in vSphere IPI deployments
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/S

#5575 Implement Submariner Deployment with UI [Downstream]
  conf/ocsci/submariner_downstream.yaml
  ocs_ci/deployment/acm.py
  ocs_ci/ocs/acm/__init__.py
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/views.py
  tests/ecosystem/deployment/test_acm.py
Labels: team/ecosystem, size/M

#6287 use upstream must gather image for Managed service live deploy
  tests/conftest.py
Labels: Verified, team/ecosystem, size/XS, Managed Services

#6279 remove unused converged mode config files in MS
  conf/deployment/rosa/managed_1az_converged_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_converged_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_converged_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_converged_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_converged_3m_3w_m54x.yaml
Labels: team/ecosystem, size/L, Managed Services

#6310 wait for all nodes to create in vSphere IPI deployment
  ocs_ci/ocs/node.py
Labels: Verified, team/ecosystem, size/M

#6273 Update ACM channel to 2.5
  ocs_ci/framework/conf/ocp_version/ocp-4.10-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.10-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.10-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.11-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.12-config.yaml
Labels: size/S

#6265 Remove first fail from sampler as there is a fail with sampler timeout
  ocs_ci/ocs/cluster.py
Labels: Verified, size/XS, Lvmo

#6262 Find leader csi-provisioner pods using log messages
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/M

#6132 Add wait time after cluster load is paused for a test
  tests/conftest.py
  tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py
  tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Labels: Verified, team/manage, size/S, Squad/Green

#6245 Fix UI deployment ODF4.11 on Azure
  ocs_ci/ocs/ui/views.py
Labels: size/XS

#6317 Increase timeout for EC of submariner install button
  ocs_ci/ocs/acm/acm.py
Labels: team/ecosystem, size/XS

#6313 Scale - wait for resource is getting a list of nested PVC list instead of PVC obj list.
  ocs_ci/helpers/helpers.py
  tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
  tests/e2e/scale/test_pv_scale_ocs_create_delete_pvcs.py
Labels: size/L

#6282 UI deployment + UI Add capacity on GCP
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/views.py
Labels: size/XS

#6323 Get LSO channel fix
  ocs_ci/utility/localstorage.py
Labels: Verified, team/ecosystem, size/XS

#6283 Remove 'odf-csi-addons-operator.yaml' file from 4.11 Must-Gather
  ocs_ci/ocs/must_gather/const_must_gather.py
Labels: Verified, size/S

#5770 Get the output mg-helper pod in failure
  ocs_ci/ocs/utils.py
Labels: Verified, size/S

#6320 Add IBM cloud stage configs
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_stage.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos_stage.yaml
  ocs_ci/utility/ibmcloud.py
Labels: Verified, team/ecosystem, size/M

#6309 Minor fix on Quay workload
  ocs_ci/ocs/quay_operator.py
  tests/e2e/workloads/app/quay/test_quay_operator.py
Labels: Verified, team/e2e, size/XS

#6336 Skip the test "test_rolling_shutdown_and_recovery" when using MS
  tests/manage/z_cluster/nodes/test_rolling_shutdown_and_recovery.py
Labels: size/XS, Managed Services

#6319 Fix issue with upgrade OCP and specific image
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: size/XS

#6264 Fix PGSQL parse logs and validate run
  ocs_ci/ocs/pgsql.py
  ocs_ci/utility/utils.py
Labels: Verified, team/e2e, size/M

#6338 pvc_snapshot TC Improvements
  tests/e2e/performance/csi_tests/test_pvc_snapshot_performance.py
Labels: Verified, size/L, performance

#6344 Skip the test 'test_recovery_from_volume_deletion' when using external mode
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: size/XS, Squad/Brown

#6337 SKip ceph health check after OCP upgrade in MCG Only deployment
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Verified, team/ecosystem, size/S

#6352 add subnet_ids to provider when set
  ocs_ci/utility/rosa.py
Labels: Verified, size/XS, Managed Services

#6143 Test MCG secrets
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/cloud_manager.py
  tests/manage/mcg/test_noobaa_secret.py
Labels: Verified, team/e2e, size/L, Customer defects

#6203 Test topolvm alerts - thin pool capacity
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/utils.py
  ocs_ci/utility/workloads/fio.py
  tests/lvmo/test_lvm_alerts.py
Labels: Verified, size/L, Lvmo

#6211 simple OCP deployment for external mode
  conf/deployment/vsphere/ipi_1az_rhcos_vsan_3m_3w_external.yaml
Labels: size/S, DR

#6355 Update namespace and app pod config to comply with podsecurity profiles
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/templates/app-pods/raw_block_pod.yaml
  ocs_ci/utility/version.py
  tests/manage/pv_services/test_pvc_assign_pod_node.py
  tests/manage/pv_services/test_raw_block_pv.py
Labels: Needs Testing, team/manage, DO NOT MERGE, size/S

#6316 Adding OCP 4.11 GA config files
  ocs_ci/framework/conf/ocp_version/ocp-4.11-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.11-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.11-ga-upgrade.yaml
Labels: Verified, team/ecosystem, size/M

#6331 get terraform ignition provider for adding nodes
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/M

#6350 remove selinux_permissions for RHEL nodes
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/XS

#6367 get running OCP version while creating new project
  ocs_ci/ocs/ocp.py
Labels: Needs Testing, team/ecosystem, size/XS

#6357 Fixing postgress max connections for test_noobaa_postgres_cm_post_ocs_upgrade
  ocs_ci/ocs/constants.py
  tests/manage/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/S

#6368 fix the collection of deletion performance
  tests/e2e/performance/csi_tests/test_pvc_creation_deletion_performance.py
Labels: Verified, size/XS, performance

#6353 Enable OVN network
  conf/ocsci/enable_ovn_network.yaml
  ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-aws-upi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-azure-ipi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-baremetal-upi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-gcp-ipi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-rhv-ipi.yaml.j2
Labels: Needs Testing, team/ecosystem, size/S

#6373 raise exception for KMS deployments if encryption is not enabled
  ocs_ci/utility/kms.py
Labels: team/ecosystem, size/XS

#6374 Update rosa cli version to 1.2.6
  ocs_ci/framework/conf/default_config.yaml
Labels: enhancement, Verified, size/XS, Managed Services

#6043 Added automation tests for happy path validations for nfs feature testing
  ocs_ci/utility/nfs_utils.py
  tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Labels: Verified, size/XXL

#6376 skip mcg-operator check for ODF 4.10 live deployment
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/M

#6375 Multi snapshot - fix API version
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/perftests.py
  ocs_ci/templates/CSI/cephfs/snapshot.yaml
  ocs_ci/templates/CSI/cephfs/snapshotclass.yaml
  ocs_ci/templates/CSI/rbd/snapshot.yaml
  ocs_ci/templates/CSI/rbd/snapshotclass.yaml
  tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py
Labels: Verified, size/M, performance

#6365 remove unused OCP object from verify_pods_upgraded
  ocs_ci/ocs/resources/pod.py
Labels: Verified, team/ecosystem, size/XS, upgrade

#6371 Quick fix for addon based deployment using byo-vpc ODFMS-262
  ocs_ci/utility/rosa.py
Labels: Verified, Needs Deployment Testing, size/M, Managed Services

#6381 Modifying qe provider addons storage cluster default configuration to 4 T
  conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
Labels: Verified, size/XS, Managed Services

#6389 installation of ODF 4.12 to stable builds
  ocs_ci/framework/conf/ocs_version/ocs-4.12.yaml
Labels: Verified, team/ecosystem, size/XS

#6387 function to change the terraform statefile
  ocs_ci/deployment/terraform.py
Labels: Verified, team/ecosystem, size/M

#6392 Skip PagerDuty integration when there is no CephCluster available
  tests/conftest.py
Labels: Verified, size/S, Managed Services
