Repository red-hat-storage/ocs-ci, pull requests merged in 2022-05, with the labels that each got.

#5822 Add provider server log test
  ocs_ci/ocs/constants.py
  tests/managed-service/test_post_installation_state.py
Labels: Verified, size/S, Managed Services, Squad/Yellow

#5697 ACM Hub Downstream Installation
  conf/examples/acm_hub_downstream_image.yaml
  conf/ocsci/acm_hub_downstream_deploy.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/templates/acm-deployment/imagecontentsourcepolicy.yaml
  ocs_ci/templates/acm-deployment/pull-secret.yaml.j2
Labels: Verified, team/ecosystem, size/L, DR

#5829 Skip the test 'check_pods_status_after_node_failure' when using ms consumer and external mode
  tests/manage/z_cluster/nodes/test_check_pods_status_after_node_failure.py
Labels: size/XS, Managed Services

#5778 Use shallow clone and support clone types in clone_repo function.
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/M

#5819 Adding repo files for OCP 4.11
  ocs_ci/repos/ocp_4_11_rhel7.repo
  ocs_ci/repos/ocp_4_11_rhel8.repo
Labels: team/ecosystem, size/M

#5828 fix cluster health check for MS Consumer cluster
  ocs_ci/ocs/cluster.py
Labels: Verified, team/ecosystem, size/S, Managed Services

#5826 Fix auth_path assignment
  ocs_ci/utility/kms.py
  tests/conftest.py
Labels: Verified, team/manage, size/XS, Squad/Green

#5790 upload performance data to portal.
  ocs_ci/ocs/cosbench.py
  tests/e2e/performance/mcg/test_mcg_cosbench.py
Labels: Verified, size/M, performance, MCG

#5833 Add test for ceph clients in provider cluster
  ocs_ci/ocs/resources/storage_cluster.py
  tests/managed-service/test_post_installation_state.py
Labels: Verified, size/M, Managed Services, Squad/Yellow

#5836 commenting sensitive variable as current terraform doesn't support
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/S

#5810 Update performance image
  Docker_files/performance_image
  Docker_files/scripts/multiple_files.sh
Labels: enhancement, Verified, size/L, performance

#5837 get RGW endpoint port using config dump
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/ocs/exceptions.py
Labels: Verified, team/ecosystem, size/M

#5832 Fix various NSFS test issues
  tests/conftest.py
  tests/manage/mcg/test_nsfs.py
Labels: size/M, MCG

#5845 RGW malformed yaml fix
  ocs_ci/ocs/resources/objectbucket.py
  tests/manage/rgw/test_obc_quota.py
Labels: High Priority, Verified, size/S

#5846 update terraform ignition provider path for destroy job
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/XS

#5847 Increased timeout for some test failures
  tests/conftest.py
  tests/manage/z_cluster/nodes/test_check_pods_status_after_node_failure.py
Labels: bug, size/S, Squad/Brown

#5787 Modify test test_log_reader_writer_parallel to run on MS
  tests/e2e/workloads/test_data_consistency.py
Labels: Verified, size/XS, Managed Services

#5857 Wait for the pod to reach running state before doing rsh into it
  ocs_ci/ocs/resources/mcg.py
Labels: bug, size/XS, Squad/Brown

#5858 Changing fixture scope to class for improving performance and reducing test execution time for UI test cases
  tests/manage/mcg/ui/test_mcg_ui.py
  tests/ui/test_add_capacity_ui.py
  tests/ui/test_capacity_breakdown_ui.py
  tests/ui/test_pvc_ui.py
  tests/ui/test_quickstarts.py
  tests/ui/test_validation_ui.py
Labels: enhancement, size/M, ui_automation

#5531 Get the node in the same rack or zone of the new added node
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: Verified, size/L, Squad/Brown

#5860 Skip the test test_add_capacity_with_resource_delete on MS
  tests/manage/z_cluster/cluster_expansion/test_delete_pod.py
Labels: Verified, size/XS, Managed Services

#5869 Update rosa cli version to 1.2.0 and add in default config
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_converged_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_converged_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_converged_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_provider_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_converged_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_converged_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/utility/rosa.py
Labels: enhancement, Verified, size/S, Managed Services

#5861 Run tier4c pagerduty tests on provider
  tests/manage/monitoring/pagerduty/test_deployment_status.py
Labels: Verified, size/XS, Managed Services

#5553 Update wait_for_storage_pods() to ignore controller detect version pods and check correct state for osd prepare pods
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/S

#5775 Modify test_del_mon_service_and_create_pvc to run on MS
  tests/manage/pv_services/test_del_mon_service_and_create_pvc.py
Labels: Verified, size/M, Managed Services

#5850 Move fixture 'create_pvcs_and_pods' to tests/conftest.py
  tests/conftest.py
  tests/manage/pv_services/conftest.py
Labels: enhancement, Verified, size/L, Squad/Green

#5872 use string instead text in soup object
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem

#5820 Defaulting ocs-ci to ODF 4.11
  ocs_ci/framework/conf/default_config.yaml
Labels: team/ecosystem, size/S

#5889 Move platform check to setup function in test to avoid collection error
  tests/manage/pv_services/test_del_mon_service_and_create_pvc.py
Labels: High Priority, Verified, size/XS, Managed Services, Squad/Yellow

#5854 Closed loop 2054540: mpu with bucket policy
  tests/manage/mcg/test_bucket_policy.py
Labels: Verified, team/e2e, size/M, Customer defects

#5892 Move the storage system verification after ceph helth.
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/XS

#5897 updating the Perf container image
  Docker_files/build.sh
  Docker_files/performance_image
  Docker_files/scripts/multiple_files.sh
Labels: size/XS

#5613 test_s3_benchmark_object_bucket: Increase timeout for bucket health check.
  ocs_ci/ocs/hsbench.py
  tests/e2e/scale/noobaa/test_hsbench.py
Labels: Verified, size/S, scale

#5880 Total creation time fix and csi time added
  ocs_ci/helpers/helpers.py
  ocs_ci/helpers/performance_lib.py
  tests/e2e/performance/csi_tests/test_pvc_snapshot_performance.py
Labels: size/L, performance

#5903 pin cryptography to 36.0.2
  setup.py
Labels: Verified, team/ecosystem, size/XS

#5890 Implement get_node_by_attached_volume for vSphere platform
  ocs_ci/ocs/platform_nodes.py
Labels: team/ecosystem, size/S

#5909 Fix getting CSV from install plan
  ocs_ci/ocs/resources/packagemanifest.py
Labels: Verified, team/ecosystem, size/XS

#5883 Use timeoutsampler for getting reboot events for node
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/platform_nodes.py
Labels: Verified, team/ecosystem, size/M

#5906 Add prometheus version check
  ocs_ci/ocs/resources/storage_cluster.py
Labels: size/S, Managed Services, Squad/Yellow

#5912 Skip the test 'test_add_capacity_with_node_restart' when using ms
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
Labels: size/XS, Managed Services

#5886 Change acm hub downstream references to unreleased
  conf/examples/acm_hub_downstream_image.yaml
  conf/examples/acm_hub_unreleased_image.yaml
  conf/ocsci/acm_hub_unreleased_deploy.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
Labels: team/ecosystem, size/M

#5747 RDR changes for 4.10
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/multicluster_deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/ui/acm_ui.py
  ocs_ci/ocs/ui/views.py
  ocs_ci/templates/ocs-deployment/multicluster/dr_policy_acm_hub.yaml
  ocs_ci/templates/ocs-deployment/multicluster/mirror_peer.yaml
  ocs_ci/templates/ocs-deployment/multicluster/odf_multicluster_orchestrator.yaml
  ocs_ci/templates/ocs-deployment/multicluster/openshift_dr_hub_operator.yaml
  ocs_ci/templates/ocs-deployment/multicluster/openshift_dr_system_operatorgroup.yaml
  ocs_ci/utility/utils.py
Labels: team/ecosystem, Code/Infra, size/XL, DR

#5918 Download external exporter script based on csv
  ocs_ci/deployment/helpers/external_cluster_helpers.py
Labels: Verified, team/ecosystem, size/S

#5873 Modify test test_resource_deletion_during_pvc_expansion for MS
  tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Labels: Verified, size/S, Managed Services

#5875 Modify test test_resource_deletion_during_pvc_clone for MS
  ocs_ci/helpers/disruption_helpers.py
  tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py
Labels: Verified, size/M, Managed Services

#5923 Adding bootstrap instance type for AWS UPI deployments
  ocs_ci/deployment/aws.py
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, team/ecosystem, size/XS

#5911 Increase wait time of fetch_used_size to workaround 5310 and 5707
  ocs_ci/helpers/helpers.py
Labels: Verified, team/manage, size/XS, Squad/Green

#5905 fix buildconfig file on jenkins workload
  ocs_ci/templates/workloads/jenkins/buildconfig.yaml
Labels: Verified, size/XS

#5925 Update NTP server
  ocs_ci/ocs/constants.py
Labels: team/ecosystem, size/XS

#5930 Disconnected cluster: update used int-svc user for ocp 4.11
  ocs_ci/utility/flexy.py
Labels: Verified, team/ecosystem, size/S

#5881 Added MG test on ODF4.11
  ocs_ci/ocs/must_gather/const_must_gather.py
Labels: size/S

#5910 Including version 4.8 after fix for luks header info issue in 4.8.11
  ocs_ci/ocs/resources/storage_cluster.py
Labels: size/XS

#5938 get all resource record sets from base domain in AWS
  ocs_ci/utility/aws.py
Labels: Verified, team/ecosystem, size/S

#5610 Helper functions for RDR validation from OCP side
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/constants.py
Labels: size/L, DR

#5939 Update rosa to current released version 1.2.2
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/XS, Managed Services

#5839 Update logic for IBM Cloud W/A for must gather image
  conf/README.md
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_hpcs_external.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
  conf/ocsci/ocs-live-must-gather.yaml
  conf/ocsci/odf-live-must-gather.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/ocs_upgrade.py
  tests/conftest.py
Labels: team/ecosystem, size/L, IBM Cloud

#5647 Add cluster ctx to the logger format persistently
  ocs_ci/framework/logger_factory.py
  ocs_ci/framework/pytest_customization/ocscilib.py
  pytest.ini
  pytest_unittests.ini
Labels: Verified, team/ecosystem, size/M

#5927 ypersly - multi snapshot csi times
  tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py
Labels: Verified, size/L, performance

#5866 refactoring pvc_clones test
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/perftests.py
  tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
Labels: High Priority, Verified, size/XL, performance, Environment issue

#5874 Load subnet ids from config if available
  ocs_ci/utility/rosa.py
Labels: Verified, size/XS, Managed Services

#5928 comment sensitive variable based on OCP version
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/version.py
Labels: Verified, team/ecosystem, size/M

#5922 ceph health check at the end of deploymnet TC
  tests/ecosystem/deployment/test_deployment.py
Labels: Verified, team/ecosystem, size/XS

#5959 Add protobuf==3.20.1 to fix google-api package conflict
  setup.py
Labels: team/ecosystem, size/XS

#5940 Remove headless=false from multicluster acm-ocp deployment configuration
  conf/ocsci/multicluster_acm_ocp_deployment.yaml
Labels: size/XS

#5954 Update ACM 2.5 image to RC6
  conf/examples/acm_hub_unreleased_image.yaml
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/XS

#5147 Skip `test_scale_rgw_down` on external mode clusters
  tests/manage/mcg/test_mcg_resources_disruptions.py
Labels: size/XS, RGW

#5949 Remove storageclass check for provider cluster
  ocs_ci/ocs/resources/storage_cluster.py
  tests/managed-service/test_post_installation_state.py
Labels: Verified, size/M, Managed Services, Squad/Yellow

#5965 test_pvc_clones - fix teardown issues of trying to log doesn't exist object
  tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
Labels: bug, size/XS, performance

#5755 Run the node managed service tests with cephfs workload
  ocs_ci/ocs/cephfs_workload.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_ms.py
Labels: Verified, size/L, Managed Services
