Repository red-hat-storage/ocs-ci, pull requests merged in 2022-02, with the labels that each got.

#5390 Dashboard Integration for test_pvc_clone_performance
  tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
Labels: size/L, performance

#5331 Change test_snapshot_at_different_usage_level to tier2
  tests/manage/pv_services/pvc_snapshot/test_snapshot_at_different_pvc_utlilization_level.py
Labels: size/XS, Squad/Green

#5408 fix config initialization for multicluster
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: Verified, team/ecosystem, size/XS

#5410 Improve logging of BM when resource are locked
  ocs_ci/deployment/baremetal.py
Labels: Verified, size/S

#5413 switch to default cluster ctx after config inititalization
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: team/ecosystem, size/XS

#5414 Do not fail when configuration file is emtpy
  ocs_ci/framework/__init__.py
Labels: size/XS

#5419 skip pager duty integration till it get fix
  tests/conftest.py
Labels: Verified, size/XS, Managed Services

#5418 Fix OCS4.7 UI deployment
  ocs_ci/ocs/ui/base_ui.py
Labels: size/XS, ui_automation

#5423 Update openshiftdedicated conditions as MANAGED_SERVICE_PLATFORMS
  ocs_ci/ocs/must_gather/const_must_gather.py
  ocs_ci/ocs/node.py
  tests/conftest.py
  tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
  tests/manage/pv_services/test_raw_block_pv.py
Labels: enhancement, Verified, size/S, Managed Services

#5426 Disable the redundant tier4 pv_services tests
  tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py
  tests/manage/pv_services/test_ceph_daemon_kill_during_resource_deletion.py
  tests/manage/pv_services/test_pvc_disruptive.py
  tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
Labels: Verified, size/M, Squad/Green

#5422 Add skipif managed service marker and update it in OSD skip tests
  ocs_ci/framework/pytest_customization/marks.py
  tests/e2e/flowtest/mcg/test_mcg_namespace_disruptions_crd.py
  tests/e2e/flowtest/mcg/test_mcg_namespace_disruptions_rpc.py
  tests/e2e/kcs/test_noobaa_db_backup_and_recovery.py
  tests/e2e/kcs/test_noobaa_rebuild.py
  tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
  tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_rpc.py
  tests/e2e/lifecycle/mcg/test_mcg_namespace_s3_ops_crd.py
  tests/e2e/lifecycle/mcg/test_mcg_namespace_s3_ops_rpc.py
  tests/e2e/workloads/ocp/logging/test_openshift-logging.py
  tests/manage/mcg/test_bucket_creation.py
  tests/manage/mcg/test_bucket_deletion.py
  tests/manage/mcg/test_bucket_policy.py
  tests/manage/mcg/test_endpoint_autoscale.py
  tests/manage/mcg/test_mcg_resources_disruptions.py
  tests/manage/mcg/test_multi_region.py
  tests/manage/mcg/test_multicloud.py
  tests/manage/mcg/test_multipart_upload.py
  tests/manage/mcg/test_namespace_crd.py
  tests/manage/mcg/test_namespace_rpc.py
  tests/manage/mcg/test_object_integrity.py
  tests/manage/mcg/test_verify_noobaa_status.py
  tests/manage/mcg/test_write_to_bucket.py
  tests/manage/monitoring/prometheus/test_hpa.py
  tests/manage/monitoring/prometheus/test_noobaa.py
  tests/manage/monitoring/prometheusmetrics/test_mcg_hpa.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
  tests/manage/monitoring/prometheusmetrics/test_ocs_utilization.py
  tests/manage/rgw/test_object_bucket_size.py
  tests/manage/storageclass/conftest.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
  tests/manage/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
  tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: enhancement, Verified, size/L, Managed Services

#5427 Use default storage class in test test_change_reclaim_policy_of_pv if the reclaim policy is Delete
  tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
Labels: Verified, team/manage, size/S, Squad/Green

#5251 Added mg test on ODF 4.10
  ocs_ci/ocs/must_gather/const_must_gather.py
Labels: Verified, size/XS

#4906 Fix storage_type parameter in the test test_ceph_daemon_kill_during_pod_pvc_deletion
  tests/manage/pv_services/test_ceph_daemon_kill_during_resource_deletion.py
Labels: Verified, team/manage, size/S, Squad/Green

#5295 Test case to verify PVC clone from GUI
  ocs_ci/ocs/ui/pvc_ui.py
  ocs_ci/ocs/ui/views.py
  tests/ui/test_pvc_ui.py
Labels: Test Case, Verified, size/L, ui_automation

#5415 Add example for multicluster test scenario
  docs/index.rst
  docs/multicluster_test_example.md
Labels: size/L

#5432 Rename, add and update rosa platform configs
  conf/deployment/rosa/ipi_1az_rhcos_3m_3w.yaml
  conf/deployment/rosa/ipi_1az_rhcos_3m_3w_m52x.yaml
  conf/deployment/rosa/ipi_1az_rhcos_3m_3w_m54x.yaml
  conf/deployment/rosa/ipi_3az_rhcos_3m_3w.yaml
  conf/deployment/rosa/ipi_3az_rhcos_3m_3w_m52x.yaml
  conf/deployment/rosa/ipi_3az_rhcos_3m_3w_m54x.yaml
Labels: enhancement, size/L, Managed Services

#5406 Pass build name when creating images
  ocs_ci/ocs/registry.py
  tests/e2e/workloads/ocp/registry/test_registry_by_increasing_num_of_image_registry_pods.py
  tests/e2e/workloads/ocp/registry/test_registry_pod_respin.py
  tests/e2e/workloads/ocp/registry/test_registry_pull_and_push_images_to_registry.py
  tests/e2e/workloads/ocp/registry/test_registry_reboot_node.py
  tests/e2e/workloads/ocp/registry/test_registry_shutdown_and_recovery_node.py
Labels: Verified, size/M, Squad/Magenta

#5358 Dashboard Integration for test_pvc_snapshot_performance and test_pvc_snapshot_performance_multiple_files
  ocs_ci/ocs/perfresult.py
  tests/e2e/performance/csi_tests/test_pvc_snapshot_performance.py
Labels: size/L, performance

#5396 GSS Closed Loop BZ-2004130: Validate old noobaa-db service in cli and logs
  tests/manage/mcg/test_verify_noobaa_status.py
Labels: Verified, team/e2e, size/M, Customer defects

#5438 Wait and version fixes
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/ui/views.py
Labels: size/S, ui_automation

#5445 Skip the tests which create new storage class on MS
  tests/manage/pv_services/pvc_clone/test_encrypted_rbd_pvc_clone.py
  tests/manage/pv_services/pvc_snapshot/test_encrypted_rbd_pvc_snapshot.py
  tests/manage/pv_services/pvc_snapshot/test_verify_rbd_trash_purge.py
  tests/manage/pv_services/test_rbd_pv_encryption.py
Labels: Verified, team/manage, size/XS, Squad/Green, Managed Services

#5441 Quay workload: super user creation on quay registry to enable api access
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/quay_operator.py
  ocs_ci/templates/workloads/quay/quay_registry.yaml
  ocs_ci/templates/workloads/quay/quay_subscription.yaml
  ocs_ci/templates/workloads/quay/quay_super_user_config.yaml
Labels: enhancement, Verified, team/e2e, size/M

#5446 add newly required packages for disconnected deployment - ODF 4.10
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/XS

#5451 Changes:
  tests/e2e/system_test/test_full_cluster_health.py
Labels: size/XS

#5436 Fix ROSA deployment and pagerduty service creation
  ocs_ci/utility/pagerduty.py
  ocs_ci/utility/rosa.py
  tests/conftest.py
Labels: Verified, size/L, Squad/Yellow

#5444 adding the backed SC to platform name in the performance dashboard
  ocs_ci/ocs/perftests.py
Labels: Verified, size/S, performance

#5433 Update config env data for missing add-on parameter
  conf/deployment/rosa/ipi_1az_rhcos_3m_3w_m52x.yaml
  conf/deployment/rosa/ipi_1az_rhcos_3m_3w_m54x.yaml
  conf/deployment/rosa/ipi_3az_rhcos_3m_3w_m52x.yaml
  conf/deployment/rosa/ipi_3az_rhcos_3m_3w_m54x.yaml
Labels: enhancement, Verified, size/S, platforms, Managed Services

#5409 send multi_snapshot results into elasticsearch server
  ocs_ci/ocs/perfresult.py
  ocs_ci/ocs/perftests.py
  tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py
Labels: Verified, size/L, performance

#5469 Allow availability zone as configurable parameters for Rosa deployment
  ocs_ci/utility/rosa.py
Labels: enhancement, Verified, size/XS, Managed Services

#5467 Add configs for rosa RH-ODF-MS provider,consumer ad-ons and its combinations
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_converged_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_converged_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_provider_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_converged_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_converged_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml
  ocs_ci/utility/rosa.py
Labels: size/L, Managed Services

#5424 Add RHEL8 repos
  conf/README.md
  conf/deployment/aws/upi_3az_rhel8_3m_3w.yaml
  conf/ocsci/aws_upi_rhel8_workers.yaml
  ocs_ci/deployment/aws.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/repos/ocp_4_10_rhel7.repo
  ocs_ci/repos/ocp_4_10_rhel8.repo
  ocs_ci/repos/ocp_4_6_rhel7.repo
  ocs_ci/repos/ocp_4_7_rhel7.repo
  ocs_ci/repos/ocp_4_8_rhel7.repo
  ocs_ci/repos/ocp_4_9_rhel7.repo
  ocs_ci/repos/ocp_4_9_rhel8.repo
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/L

#5466 test_mcg_hpa uses both
  ocs_ci/ocs/version.py
  tests/conftest.py
  tests/manage/monitoring/prometheusmetrics/test_mcg_hpa.py
Labels: Test Case, Verified, size/M, Merge As Is (Don't Squash)

#5355 Correct a typo in the MCG CLI binary retrieval logging
  ocs_ci/ocs/resources/mcg.py
Labels: size/XS

#5470 Additional rsync debugging in OCS-2735
  tests/e2e/workloads/test_data_consistency.py
Labels: Test Case, Verified, size/M, Merge As Is (Don't Squash)

#5457 Correct replication test IDs
  tests/manage/mcg/test_bucket_replication.py
Labels: Verified, size/XS, MCG

#5416 Skip namespace bucket creation via MCG RPC.
  tests/e2e/scale/noobaa/test_scale_namespace_rpc.py
Labels: size/XS, scale

#5307 ACM HUB Deployment
  conf/ocsci/acm_hub_deploy.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.10-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.9-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.9-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.9-ga-minus1-config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/templates/acm-deployment/multiclusterhub.yaml
  ocs_ci/templates/acm-deployment/operatorgroup.yaml
  ocs_ci/templates/acm-deployment/subscription.yaml
  ocs_ci/templates/ocp-deployment/namespace.yaml
Labels: Verified, size/L, DR

#5481 Fix "pipeline-utility-steps" plugin version on Jenkins workload
  ocs_ci/ocs/jenkins.py
Labels: size/XS

#5491 Update jinja2 template
  setup.py
Labels: Verified, team/ecosystem, size/XS

#5473 Add marker for managed service provider and consumer
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/marks.py
  tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
Labels: enhancement, size/M, Managed Services

#5437 UI elements for create cluster through ACM
  ocs_ci/ocs/ui/views.py
Labels: team/ecosystem, size/M, DR

#5486 Fix test case test_clone_pvc
  tests/ui/test_pvc_ui.py
Labels: Verified, size/XS, ui_automation

#5327 Test case: RBD space reclaim
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pvc.py
  ocs_ci/templates/CSI/rbd/reclaimspacejob.yaml
  tests/manage/pv_services/space_reclaim/test_rbd_space_reclaim.py
Labels: Test Case, Verified, team/manage, size/L, Squad/Green

#5488 Run the node replacement proactive test on the managed service deployment
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: size/XS

#4720 Move pytest to 6.2.5
  pytest.ini
  setup.py
Labels: size/XS

#5461 Dynamic external cluster installation
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/connection.py
  ocs_ci/utility/deployment.py
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/L, Merge As Is (Don't Squash)

#5244 <Closed loop BZ: 1944513> CephMonQuorumLost Alert raised when mon quorum lost
  ocs_ci/ocs/constants.py
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/prometheus/test_deployment_status.py
Labels: Verified, team/e2e, size/M, Customer defects

#5495 Wait for machineConfigPool after applying SSL cert
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/disconnected.py
  ocs_ci/deployment/flexy.py
  ocs_ci/deployment/helpers/lso_helpers.py
  ocs_ci/utility/ssl_certs.py
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/S

#5507 get rgwendpoint port dynamically
  ocs_ci/deployment/helpers/external_cluster_helpers.py
Labels: Verified, team/ecosystem, size/S

#5509 changing compressed FIO test timeout
  ocs_ci/templates/workloads/fio/benchmark_fio_cmp.yaml
Labels: size/XS, performance

#5512 removing tini from external tookbox config in external mode deployment
  ocs_ci/ocs/utils.py
Labels: Verified, team/ecosystem, size/S

#5505 docs: stress the need for listing `tests` testpath
  docs/usage.md
Labels: size/S

#5516 Docstring correction
  ocs_ci/utility/connection.py
Labels: team/ecosystem, size/XS

#5460 Check Noobaa_diagnose dir content
  ocs_ci/ocs/must_gather/const_must_gather.py
  ocs_ci/ocs/must_gather/must_gather.py
Labels: Verified, size/S

#5517 Install yq as it's required for AWS UPI deployment
  setup.py
Labels: Verified, team/ecosystem, size/XS

#5513 measuring the CSI time for create and delete of PVC
  ocs_ci/helpers/performance_lib.py
  tests/e2e/performance/csi_tests/test_pvc_creation_deletion_performance.py
Labels: Verified, size/L, performance

#5506 Skip the test case test_rbd_space_reclaim in MS
  tests/manage/pv_services/space_reclaim/test_rbd_space_reclaim.py
Labels: team/manage, size/XS, Managed Services
