Repository red-hat-storage/ocs-ci, pull requests merged in 2022-03, with the labels that each got.

#5525 Rename daemon kill test
  tests/manage/pv_services/test_ceph_daemon_kill_during_resource_creation.py
  tests/manage/pv_services/test_ceph_daemon_kill_during_resource_deletion.py
  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_and_io.py
  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_deletion_and_io.py
Labels: size/XS

#5527 get RHEL version from external RHCS cluster
  ocs_ci/deployment/helpers/external_cluster_helpers.py
Labels: Verified, team/ecosystem, size/S

#5528 Add OCP 4.11 config files
  ocs_ci/framework/conf/ocp_version/ocp-4.11-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.11-upgrade.yaml
Labels: Verified, team/ecosystem, size/S

#5530 Performance Dashboard - remove the check if cluster is compressed
  ocs_ci/ocs/perftests.py
Labels: bug, size/XS, performance

#5524 General function to check test results
  ocs_ci/ocs/perftests.py
  tests/e2e/performance/csi_tests/test_pvc_attachtime.py
Labels: Verified, size/M, performance

#5431 Use semantic version for version comparison in test_rwo_pvc_fencing_unfencing.py
  tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
Labels: Verified, team/manage, size/XS, Squad/Green

#5440 Import Clusters to ACM Hub including a separated test mark
  conf/ocsci/import_clusters_to_acm.yaml
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
  tests/ecosystem/deployment/test_acm.py
Labels: Verified, size/M, DR

#5443 Add WebDriver Data type hint in UI Base Class
  ocs_ci/ocs/ui/base_ui.py
Labels: Verified, size/XS

#5533 Change the default imagepullpolicy for performance test
  ocs_ci/templates/app-pods/performance.yaml
  tests/e2e/performance/csi_tests/test_bulk_pod_attachtime_performance.py
  tests/e2e/performance/csi_tests/test_pod_reattachtime.py
Labels: size/M, performance

#5536 Donot raise exception during pytest collections
  ocs_ci/utility/kms.py
  tests/conftest.py
Labels: Verified, team/ecosystem, size/S

#5472 Applies huge pages and verifies cluster pods are running
  ocs_ci/utility/utils.py
  tests/manage/z_cluster/test_hugepages.py
Labels: Verified, team/e2e, size/L

#5545 Fix key error in case of 'import_clusters_to_acm'
  ocs_ci/ocs/ui/base_ui.py
Labels: team/ecosystem, size/XS, DR

#4893 Add libraries for vaulttenantsa encryptionKMSType
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/defaults.py
  ocs_ci/templates/CSI/rbd/csi-kms-connection-details.yaml
  ocs_ci/templates/CSI/rbd/rbd-csi-vault-token-reviewer.yaml
  ocs_ci/templates/CSI/rbd/tenant-sa.yaml
  ocs_ci/templates/CSI/rbd/tenant-vault-configmap.yaml
  ocs_ci/utility/kms.py
  tests/conftest.py
Labels: Verified, team/manage, size/XL, new feature

#5462 Increase time in test_rgw_unavailable to wait for clearing alert
  tests/manage/monitoring/prometheus/test_rgw.py
Labels: Verified, size/XS, Squad/Blue

#5554 Changing samples number from 1 to 10
  tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
Labels: size/S

#5549 Getting the CSI time for bulk of PVCs create/delete
  ocs_ci/helpers/performance_lib.py
  ocs_ci/ocs/perftests.py
  tests/e2e/performance/csi_tests/test_pvc_bulk_creation_deletion_performance.py
Labels: size/L

#5559 Move RHEL7 config files to be without version
  conf/deployment/aws/upi_1az_rhel_lso_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhel_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhel_lso_3m_3w.yaml
  conf/deployment/baremetal/upi_1az_rhel_nvme_intel_3m_3w.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.6-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.7-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.8-config.yaml
Labels: team/ecosystem, size/XS

#5544 updated the osd_memory_target_cgroup_limit_ratio to 0.8 wrt bug 2012082
  ocs_ci/ocs/constants.py
  tests/manage/z_cluster/test_ceph_default_values_check.py
Labels: size/M

#5561 vSphere IPI/UPI specs conf: Reduce master and increase worker memory
  conf/ocsci/vsphere_ipi.yaml
  conf/ocsci/vsphere_upi.yaml
Labels: Verified, size/XS

#5564 dump performance results to a JSON file in any case (ES exists or not)
  ocs_ci/ocs/perfresult.py
Labels: Verified, size/S, performance

#5563 Upgrade external cluster
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: Needs Deployment Testing, team/ecosystem, size/L, upgrade

#5578 Adding OCP 4.10 GA config files
  ocs_ci/framework/conf/ocp_version/ocp-4.10-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.10-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.10-ga-upgrade.yaml
Labels: team/ecosystem, size/M

#5573 Fix the ElasticSearch link
  ocs_ci/ocs/perfresult.py
Labels: Verified, size/XS, performance

#5494 Quay workload api ops test
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/quay_operator.py
  tests/e2e/workloads/app/quay/test_quay_operator.py
Labels: team/e2e, size/L

#5580 delete csi users during cluster deletion
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/S

#5514 Updating tier definitions[tier4a]
  tests/manage/mcg/test_host_node_failure.py
  tests/manage/mcg/test_mcg_resources_disruptions.py
  tests/manage/mcg/test_multi_region.py
  tests/manage/mcg/test_namespace_crd.py
  tests/manage/monitoring/pagerduty/test_deployment_status.py
  tests/manage/monitoring/prometheus/test_deployment_status.py
  tests/manage/monitoring/prometheus/test_noobaa.py
  tests/manage/monitoring/prometheus/test_rgw.py
  tests/manage/monitoring/prometheusmetrics/test_rgw.py
  tests/manage/pv_services/test_del_mon_service_and_create_pvc.py
  tests/manage/pv_services/test_delete_plugin_pod.py
  tests/manage/rgw/test_host_node_failure.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
  tests/manage/z_cluster/cluster_expansion/test_delete_pod.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
  tests/manage/z_cluster/nodes/test_nodes_restart.py
  tests/manage/z_cluster/nodes/test_toleration.py
  tests/manage/z_cluster/test_delete_local_volume_sym_link.py
  tests/manage/z_cluster/test_rook_operator_restart_during_mon_failover.py
Labels: Verified, size/L

#5586 Prepare for ODF 4.11
  ocs_ci/framework/conf/ocs_version/ocs-4.11.yaml
  ocs_ci/framework/main.py
Labels: size/S

#5587 Disable odf operator
  ocs_ci/ocs/managedservice.py
Labels: Verified, size/M, Managed Services

#5591 add function for generating onboarding token
  ocs_ci/utility/managedservice.py
Labels: Verified, team/ecosystem, size/M

#5583 Skip tests on MS platform
  tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py
  tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
  tests/manage/pv_services/pvc_snapshot/test_resource_deletion_during_snapshot_restore.py
  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_deletion_and_io.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: Verified, size/M, Squad/Green, Managed Services

#5566 Disable/Enable OCS/OCP mg collection
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: size/S

#5605 Add markers as property to junit result file
  tests/conftest.py
Labels: Verified, team/ecosystem, size/XS

#5595 Remove duplicated constants
  ocs_ci/ocs/constants.py
Labels: size/XS

#5600 Add host_network_update for rosa
  ocs_ci/deployment/rosa.py
Labels: Verified, size/M, Managed Services

#5576 Extend encrypted rbd pv/pvc test cases to include IBM HPCS as KMS option
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_hpcs_external.yaml
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/templates/CSI/rbd/csi-kms-connection-details-hpcs.yaml
  ocs_ci/templates/openshift-infra/hpcs/ibm-kp-kms-secret.yaml
  ocs_ci/templates/openshift-infra/hpcs/ocs-kms-connection-details.yaml
  ocs_ci/utility/kms.py
  tests/conftest.py
  tests/manage/pv_services/pvc_clone/test_encrypted_rbd_pvc_clone.py
  tests/manage/pv_services/pvc_snapshot/test_encrypted_rbd_pvc_snapshot.py
  tests/manage/pv_services/test_rbd_pv_encryption.py
Labels: Verified, size/XL

#5220 Add SendGrid capacity test
  tests/conftest.py
  tests/manage/monitoring/sendgrid/__init__.py
  tests/manage/monitoring/sendgrid/conftest.py
  tests/manage/monitoring/sendgrid/test_capacity.py
Labels: Verified, size/M, Managed Services, Squad/Yellow

#5589 Add on boarding-validation-key parameter in provider add-on installation
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/utility/rosa.py
Labels: Verified, size/S, Managed Services

#5624 Pin pytest-metadata version
  setup.py
Labels: team/ecosystem

#5569 Changed pillowfight image pull from docker to quay.io
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/couchbase.py
  ocs_ci/ocs/pillowfight.py
  ocs_ci/templates/workloads/couchbase/pillowfight/basic-pillowfight.yaml
  ocs_ci/templates/workloads/couchbase/server/cb-operatorgroup.yaml
  ocs_ci/templates/workloads/couchbase/server/cb-subscription.yaml
  ocs_ci/templates/workloads/couchbase/server/couchbase-data-bucket.yaml
  ocs_ci/templates/workloads/couchbase/server/couchbase-worker-secret.yaml
  ocs_ci/templates/workloads/couchbase/server/couchbase-worker.yaml
  tests/conftest.py
  tests/e2e/workloads/app/couchbase/test_couchbase.py
  tests/e2e/workloads/app/couchbase/test_couchbase_node_drain.py
  tests/e2e/workloads/app/couchbase/test_couchbase_node_reboot.py
  tests/e2e/workloads/app/couchbase/test_couchbase_pod_respin.py
Labels: Verified, team/e2e, size/M

#5612 Workaround for BZ 2066211
  conf/ocsci/odf_compose_operator.yaml
  ocs_ci/deployment/rosa.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocs-deployment/provider-catalogsource.yaml
  ocs_ci/templates/ocs-deployment/provider-namespace.yaml
  ocs_ci/utility/rosa.py
Labels: Verified, size/M, Managed Services

#5617 Update PV encryption test cases
  ocs_ci/ocs/defaults.py
  ocs_ci/templates/CSI/rbd/csi-kms-connection-details.yaml
  tests/conftest.py
  tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_clone.py
  tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_snapshot.py
  tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption.py
Labels: Verified, team/manage, size/M, Squad/Green

#5626 Add KMS vault prod config files without namespaces
  conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v1.yaml
  conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v2.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_vault_v1.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_vault_v2.yaml
Labels: team/ecosystem, size/L

#5555 #bz2030291 checks label on luks header info for all the encrypted osds
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/e2e, size/M, Customer defects

#5627 Update get_providers_subnet function
  ocs_ci/utility/aws.py
  ocs_ci/utility/rosa.py
Labels: Verified, size/M, Managed Services

#5585 External cluster upgrade changes for ODF 4.10
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/M, upgrade

#5634 Enhancing timeout for rosa Create commands
  ocs_ci/utility/rosa.py
Labels: enhancement, Verified, size/XS, Managed Services

#5635 Enabling host network update for provider
  conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_provider_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml
Labels: enhancement, size/XS, Managed Services

#5629 Remove workaround for BZ 2066211
  conf/ocsci/odf_compose_operator.yaml
  ocs_ci/deployment/rosa.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocs-deployment/provider-catalogsource.yaml
  ocs_ci/templates/ocs-deployment/provider-namespace.yaml
  ocs_ci/utility/rosa.py
Labels: Verified, size/M, Managed Services

#5450 Added mg files on ODF4.10 [bz-2042866]
  ocs_ci/ocs/must_gather/const_must_gather.py
  ocs_ci/ocs/must_gather/must_gather.py
Labels: size/S

#5632 unifying the use of addon_name config key defination
  ocs_ci/ocs/managedservice.py
Labels: Verified, size/XS, Managed Services

#5348 PagerDuty tests for managed service minimal testing and deployment resource definition
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/ocs/rados_utils.py
  ocs_ci/ocs/resources/deployment.py
  ocs_ci/utility/pagerduty.py
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/pagerduty/test_ceph.py
  tests/manage/monitoring/pagerduty/test_deployment_status.py
Labels: Verified, size/XL, Managed Services, Squad/Yellow

#5642 update black version to 22.3.0
  .pre-commit-config.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/cluster_load.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/fiojob.py
  ocs_ci/ocs/tests/test_fiojob.py
  ocs_ci/utility/kms.py
  requirements-dev.txt
  tests/manage/monitoring/test_workload_with_distruptions.py
  tox.ini
Labels: Verified, team/ecosystem, size/M

#5628 RHEL8 deployment in vsphere platform
  ocs_ci/deployment/helpers/vsphere_helpers.py
  ocs_ci/deployment/install_ocp_on_rhel.py
  ocs_ci/deployment/vmware.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/templates/ocp-deployment/scale_up_terraform_with_folder_structure.tfvars.j2
Labels: Verified, team/ecosystem, size/S

#5601 Deploy ODF with HPCS as KMS for encryption
  conf/README.md
  conf/examples/hpcs_external_standalone_mode.yaml
  conf/ocsci/hpcs_external_standalone_mode.yaml
  ocs_ci/utility/kms.py
Labels: size/L

#5636 pvc_create_delete refactoring
  ocs_ci/helpers/helpers.py
  ocs_ci/helpers/performance_lib.py
  ocs_ci/ocs/perfresult.py
  ocs_ci/ocs/perftests.py
  tests/e2e/performance/csi_tests/test_pvc_creation_deletion_performance.py
Labels: Verified, size/XL, performance

#5649 Add retry to report version fixture
  tests/conftest.py
Labels: team/ecosystem, size/XS
