Repository red-hat-storage/ocs-ci, pull requests merged in 2022-06, with the labels that each got.

#5971 Omit use of size and unit parameter from consumer deployment
  ocs_ci/utility/rosa.py
Labels: enhancement, Verified, size/S, Managed Services

#5970 Ypersky multi clones csi times
  tests/e2e/performance/csi_tests/test_pvc_multi_clone_performance.py
Labels: Verified, size/M, performance

#5853 test s3 list objects with prefix not giving infinite outputs
  ocs_ci/ocs/bucket_utils.py
  tests/manage/mcg/test_s3_prefix_list.py
Labels: Verified, team/e2e, size/L, Customer defects

#5782 Deployment Update for appliance mode
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_provider_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml
  ocs_ci/deployment/rosa.py
  ocs_ci/utility/rosa.py
Labels: Verified, size/L, In Progress, Managed Services

#5745 Skip the testcase test_rbd_space_reclaim on External mode cluster
  tests/manage/pv_services/space_reclaim/test_rbd_space_reclaim.py
Labels: size/XS

#5979 Increasing timeouts to avoid couchbase failures
  ocs_ci/ocs/pillowfight.py
  tests/conftest.py
Labels: team/e2e, size/XS

#5983 allow usage of client proxy on private link cluster
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/ui/base_ui.py
Labels: team/ecosystem, size/XS

#5984 Add private link mode enabling config for rosa deployment
  conf/deployment/rosa/private_link_deployment.yaml
Labels: enhancement, size/XS, Managed Services

#5962 Skip PV encryption using vaulttenantsa on disconnected and proxy clusters
  tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption_vaulttenantsa.py
Labels: Verified, team/manage, size/XS, Squad/Green

#5989 doc update: use bugzilla_api_key for bugzilla authentication
  docs/usage.md
Labels: team/ecosystem, size/XS

#5990 config for add-on deployment for Managed Services
  conf/ocsci/ms_addon_type_deployment.yaml
Labels: team/ecosystem, size/XS

#5986 use client http proxy if configured
  ocs_ci/framework/main.py
  ocs_ci/utility/proxy.py
  tests/conftest.py
Labels: Verified, team/ecosystem, size/S

#5994 remove unused version parameter in MS
  ocs_ci/utility/rosa.py
Labels: team/ecosystem, size/XS

#5987 adding csi times and renaming the test
  ocs_ci/helpers/performance_lib.py
  tests/e2e/performance/csi_tests/test_pod_attachtime.py
Labels: Verified, size/L, performance

#5919 Create resources using kube job
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/scale_lib.py
  tests/conftest.py
  tests/e2e/workloads/test_create_scale_pods_and_pvcs_using_kube_job.py
Labels: Verified, size/L, Managed Services

#5953 use oc-mirror command for mirroring images
  ocs_ci/deployment/disconnected.py
  ocs_ci/helpers/disconnected.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocp-deployment/oc-mirror-imageset-config.yaml
Labels: Verified, team/ecosystem, size/L

#5913 Fix NSFS retry mechanism
  tests/conftest.py
  tests/manage/mcg/test_nsfs.py
Labels: size/XS, MCG

#5884 4.11 MCG fixes
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/namespacestore.py
Labels: Verified, size/M, MCG

#6004 drop unnecessary log info call
  ocs_ci/utility/prometheus.py
Labels: size/XS

#5996 refactoring the multi_clone TC
  ocs_ci/helpers/performance_lib.py
  ocs_ci/ocs/perftests.py
  ocs_ci/templates/app-pods/performance.yaml
  tests/e2e/performance/csi_tests/test_pvc_multi_clone_performance.py
Labels: enhancement, Verified, size/XL, performance

#5999 Change default SC in Azure platform
  ocs_ci/deployment/azure.py
  ocs_ci/ocs/ui/base_ui.py
Labels: Verified, team/ecosystem, size/S

#6008 Adding RHCOS template locations to download
  docs/getting_started.md
Labels: team/ecosystem, size/S

#6006 Enhance logger for multi cluster + adding cluster name in prefix
  ocs_ci/framework/__init__.py
  ocs_ci/framework/logger_factory.py
Labels: team/ecosystem, size/S

#5901 directio deployment for vSphere
  ocs_ci/deployment/helpers/lso_helpers.py
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/utils.py
  ocs_ci/utility/vsphere.py
Labels: Verified, team/ecosystem, size/L, Merge As Is (Don't Squash)

#5992 Fix typo + Debug line in ACM and UI functions
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/ui/base_ui.py
Labels: team/ecosystem, size/XS

#5421 Automate MCG admission control webhooks tests
  ocs_ci/ocs/bucket_utils.py
  tests/manage/mcg/test_admission_control.py
Labels: Verified, size/L, MCG

#5540 Longevity Testing - Stage 2
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/longevity_stage2.py
  ocs_ci/templates/app-pods/performance_block.yaml
  tests/conftest.py
  tests/e2e/test_longevity_stage2.py
Labels: Verified, team/e2e, size/XL, Longevity

#6022 Skip storage system validation for upgrade cluster with OCP 4.10 + upgrade OCS version 4.10
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/S

#6017 Fetch node names from object's existing data
  ocs_ci/ocs/platform_nodes.py
Labels: size/XS

#6027 Fix: Added check for SCALING state in test_pv_pool
  tests/manage/mcg/test_pv_pool.py
Labels: Verified, size/S

#6016 Fix: Added retry for sync_object_directory() in test_multiregion_mirror
  tests/manage/mcg/test_multi_region.py
Labels: Verified, size/XS

#6005 Handle page appears before the login of UI Console if necessary
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
Labels: team/ecosystem, size/S, ui_automation

#6031 Acceptance test for MS
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/resources/pod.py
  tests/test_acceptance.py
Labels: Verified, size/L

#5677 RBD ReclaimSpaceJob and ReclaimSpaceCronJob
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pvc.py
  ocs_ci/templates/CSI/rbd/reclaimspacecronjob.yaml
  tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py
  tests/manage/pv_services/space_reclaim/test_rbd_space_reclaim.py
Labels: Test Case, team/manage, size/L

#6001 Update deployment code for appliance mode private link cluster
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/private_link_deployment.yaml
  ocs_ci/deployment/rosa.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/utility/rosa.py
Labels: Verified, size/M, Managed Services

#5972 Generate Ingress certs post ACM managed clusters deployment
  conf/ocsci/skip_submariner_deploy.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/multicluster_deployment.py
Labels: Verified, team/ecosystem, size/S, DR

#6034 Add endpoint checks
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S, Managed Services

#6039 Retry addon status for Ready even after fail
  ocs_ci/utility/rosa.py
Labels: Verified, size/S, Managed Services

#5985 Update post deployment check of node counts for managed service platform
  ocs_ci/ocs/node.py
Labels: bug, size/XS, Managed Services

#4819 Mon recovery procedure validation
  tests/conftest.py
  tests/e2e/kcs/test_monitor_recovery.py
Labels: Verified, team/e2e, size/XL, Customer defects

#6029 fix image mirroring for upgrade on OCP 4.11
  ocs_ci/deployment/disconnected.py
Labels: Verified, team/ecosystem, size/XS

#5715 SNO/LVMO deployment
  conf/deployment/aws/ipi_1az_rhcos_lso_sno.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_1mw.yaml
  docs/usage.md
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/ocp.py
  ocs_ci/deployment/vmware.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/templates/lvmo-deployment/lvm-bundle.yaml
  ocs_ci/templates/lvmo-deployment/lvm-cluster-410.yaml
  ocs_ci/templates/lvmo-deployment/lvm-cluster-411.yaml
  ocs_ci/templates/lvmo-deployment/lvmo_deployment_10_disk_X_200GB.yaml
  ocs_ci/templates/lvmo-deployment/lvmo_deployment_3_disk_X_500GB.yaml
  ocs_ci/templates/lvmo-deployment/lvmo_deployment_5_disk_X_150GB.yaml
  ocs_ci/templates/ocp-deployment/ens192.nmconnection
  ocs_ci/templates/ocp-deployment/install-config-vsphere-upi-sno.yaml.j2
  ocs_ci/templates/ocp-deployment/terraform_4_5_sno.tfvars.j2
  ocs_ci/utility/utils.py
  setup.py
Labels: Verified, size/XL, new feature

#6042 ODF4.11 UI deployment
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/M

#5950 To test modify resource options in PV Pool Backingstore
  ocs_ci/ocs/bucket_utils.py
  tests/manage/mcg/test_pv_pool.py
Labels: Verified, team/e2e, size/L, Customer defects

#6049 Change snapshot apiversion based on OCP version
  ocs_ci/ocs/resources/pvc.py
Labels: Verified, size/XS

#6007 create admin account and login to cluster for ROSA prod env
  ocs_ci/deployment/helpers/rosa_prod_cluster_helpers.py
  ocs_ci/deployment/rosa.py
  ocs_ci/ocs/exceptions.py
Labels: Verified, team/ecosystem, size/L, Managed Services

#6052 Skip the test 'test_non_ocs_taint_and_toleration' when using MS
  tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Labels: size/XS, Managed Services

#6036 Ypersky csi pod reattach
  ocs_ci/templates/app-pods/performance.yaml
  tests/e2e/performance/csi_tests/test_pod_reattachtime.py
Labels: Verified, size/M, performance

#5977 Fix the test 'test_check_pods_status_after_node_failure' to run on the managed service
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/nodes/test_check_pods_status_after_node_failure.py
Labels: Verified, size/M, Managed Services

#6024 Refactored Longevity Stage2
  ocs_ci/ocs/longevity.py
  ocs_ci/ocs/longevity_helpers.py
  tests/conftest.py
  tests/e2e/longevity/test_stage2.py
Labels: Verified, team/e2e, size/L, Longevity

#6033 Fix for nsfs external sc
  ocs_ci/ocs/resources/namespacestore.py
Labels: Verified, size/S

#5848 Managed Service pod disruption test
  ocs_ci/helpers/disruption_helpers.py
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/managedservice.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/pvc.py
  tests/conftest.py
  tests/managed-service/test_pod_disruptions.py
Labels: Verified, size/L, Managed Services

#5648 Handle concurrent oc commands with threading.Lock
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/utility/prometheus.py
  ocs_ci/utility/utils.py
  tests/conftest.py
  tests/manage/monitoring/conftest.py
Labels: Verified, size/M

#6069 Skip the test 'test_rwo_pvc_fencing_unfencing' when using ms
  tests/manage/pv_services/test_rwo_pvc_fencing_unfencing.py
Labels: size/XS, Managed Services

#6071 Add role binding for BZ2101343
  ocs_ci/deployment/deployment.py
  ocs_ci/templates/lvmo-deployment/role_rolebinding.yaml
Labels: Verified, size/M, Lvmo

#6056 Fixes health check with no provided ugprade version
  ocs_ci/ocs/cluster.py
Labels: team/ecosystem, size/XS

#6064 use podman as default instead of docker in the build.sh script
  Docker_files/build.sh
Labels: Verified, size/S

#6073 Update rosa cli version to rosa 1.2.3
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/XS, Managed Services

#6070 move managed-service test_acceptance to respective folder
  tests/managed-service/test_acceptance.py
Labels: team/ecosystem, size/XS

#6026 fix dployment of OCP 4.11 via Flexy on vsphere (Disconnected and Proxy environment)
  ocs_ci/deployment/flexy.py
Labels: Verified, Needs Deployment Testing, team/ecosystem, size/S

#6068 Add teardown handling for appliance mode
  ocs_ci/deployment/rosa.py
  ocs_ci/utility/rosa.py
Labels: Verified, size/M, Managed Services

#6063 Skip Running status check of 'Completed' pods when checking for all pods in the namespace openshift-storage
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/S, Managed Services

#5963 Add support for using vault namespaces using HCP Vault
  conf/ocsci/vault_hcp_namespace_token_v1.yaml
  conf/ocsci/vault_hcp_namespace_token_v2.yaml
  docs/usecases/odf_with_kms.md
  ocs_ci/ocs/constants.py
  ocs_ci/utility/kms.py
Labels: Verified, team/manage, size/M

#6079 Label change in LVMO pods in image quay.io/rhceph-dev/ocs-registry:4.11.0-105
  ocs_ci/ocs/constants.py
Labels: Verified, size/XS, Lvmo

#6020 Create a new fixture for creating scale pods and PVCs using a Kube job on MS consumers
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/scale_lib.py
  tests/conftest.py
  tests/e2e/workloads/test_create_scale_pods_and_pvcs_using_kube_job.py
Labels: Verified, size/L, Managed Services

#6060 Close loop 1970123: Validate Noobaa storage account on azure
  ocs_ci/ocs/constants.py
  tests/manage/mcg/test_azure_noobaa_sa.py
Labels: team/e2e, size/M

#6087 Update ACM 2.5 image to 2.5.1
  conf/examples/acm_hub_unreleased_image.yaml
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/XS, DR

#6084 Fix ui_deployment on ODF4.11
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/M

#6097 Try to get client with proper role for RHCS cluster
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/M

#6046 external cluster deployment with restricted-auth-permission
  conf/ocsci/enable_restricted_auth_permission.yaml
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/L
