Repository red-hat-storage/ocs-ci, pull requests merged in 2022-04, with the labels that each got.

#5662 Consumer and provider conf
  conf/deployment/rosa/consumer_cluster_type.yaml
  conf/deployment/rosa/provider_cluster_type.yaml
Labels: size/XS, Managed Services

#5579 Update consumer add-on install rosa command for additional parameter
  ocs_ci/utility/managedservice.py
  ocs_ci/utility/rosa.py
Labels: size/M, Managed Services

#5659 Patch rook-ceph-tools deployment in consumer cluster
  tests/conftest.py
Labels: Needs Testing, Verified, size/M, Managed Services

#5663 add disable pagerduty config
  conf/ocsci/disable_pagerduty.yaml
  tests/conftest.py
Labels: Verified, size/S, Managed Services

#5661 Fix#5660 host network update for source
  ocs_ci/deployment/rosa.py
Labels: Verified, size/M, Managed Services

#5653 check luks header info for encrypted devices
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/XS

#5668 Update fixture patch_consumer_toolbox_with_secret
  tests/conftest.py
Labels: enhancement, Verified, size/S, Managed Services

#5667 Fix region config place for ROSA deployment
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_converged_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_converged_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_converged_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_provider_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_converged_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_converged_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml
  conf/ocsci/rosa.yaml
  ocs_ci/deployment/rosa.py
  ocs_ci/utility/rosa.py
Labels: Verified, size/M, Managed Services

#5672 Update default storage cluster size as per change in add-on default
  ocs_ci/framework/conf/default_config.yaml
Labels: size/XS, Managed Services

#5645 Skip test cases on MS
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
  tests/manage/z_cluster/cluster_expansion/test_node_expansion.py
  tests/manage/z_cluster/cluster_expansion/test_verify_ceph_csidriver_runs_on_non_ocs_nodes.py
  tests/manage/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/S, Managed Services

#5675 Add size and unit parameters for consumer
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
  ocs_ci/utility/rosa.py
Labels: Verified, size/M, Managed Services

#5654 pull-secret workaround for ROSA deployment
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_provider_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml
  ocs_ci/deployment/rosa.py
  ocs_ci/ocs/managedservice.py
Labels: Verified, size/M, Managed Services

#5644 Get cephfilesystemsubvolumegroup
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/S, Managed Services

#5658 [external cluster]: update json output after upgrade
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/M

#5681 increase rosa cli version to v1.1.12
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_converged_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_converged_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_converged_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_provider_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_converged_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_converged_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml
  conf/ocsci/rosa.yaml
Labels: Verified, size/M, Managed Services

#5673 Add version check for VAULT_AUTH_METHOD
  ocs_ci/utility/kms.py
Labels: Verified, size/XS

#5496 Scale bucket replication
  tests/e2e/scale/noobaa/test_scale_bucket_replication.py
Labels: Needs Testing, Verified, scale

#5639 MCG Cosbench performance test
  ocs_ci/ocs/cosbench.py
  tests/e2e/performance/mcg/test_mcg_cosbench.py
Labels: Verified, size/L, performance

#5615 Add affinityGroups and affinityGroupsNames for RHV deployment
  ocs_ci/templates/ocp-deployment/install-config-rhv-ipi.yaml.j2
Labels: Verified, team/ecosystem, size/XS

#5656 Add test case for OSD deployment deletion
  tests/manage/z_cluster/test_delete_osd_deployment.py
Labels: Test Case, Verified, team/manage, size/M

#5683 skip noobaa diagnostics on managed service platform
  ocs_ci/ocs/must_gather/must_gather.py
Labels: Verified, size/XS, Managed Services

#5688 update time out of add-on install check
  ocs_ci/utility/rosa.py
Labels: Verified, size/XS, Managed Services

#5687 Skip test cases on MS
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/XS, Managed Services

#5691 Add bugzilla marker in test test_connection_time_out
  tests/managed-service/test_post_installation_state.py
Labels: Verified, size/XS, Managed Services

#5690 Update test_must_gather to run on MS
  ocs_ci/ocs/must_gather/const_must_gather.py
  ocs_ci/ocs/must_gather/must_gather.py
Labels: Verified, size/M, Managed Services

#5637 "Adding toleration to the OcsInitialization custom resource inside the spec"
  ocs_ci/ocs/constants.py
  tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Labels: Verified, size/S

#5694 Disable auto mode for cluster creation
  ocs_ci/utility/rosa.py
Labels: Verified, size/M, Managed Services

#5541 Adjust the 'Automated recovery from failed nodes' tests to run on managed service
  ocs_ci/framework/__init__.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_ms.py
Labels: Verified, size/XL, Managed Services

#5682 rephrase pullsecret_workaround parameter
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_provider_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_stage_3m_3w_m54x.yaml
  conf/deployment/rosa/pullsecret_for_non_ga.yaml
Labels: Verified, size/S, Managed Services

#5630 Use external mode sc in test_log_reader_writer_parallel when executed on external mode clusters
  tests/e2e/workloads/test_data_consistency.py
Labels: size/XS

#5562 Ocp deployment using acm UI
  conf/ocsci/multicluster_acm_ocp_deployment.yaml
  conf/ocsci/multicluster_mode_rdr.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/factory.py
  ocs_ci/deployment/multicluster_deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/ui/acm_ui.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, team/ecosystem, size/XL, DR

#5646 PagerDuty monitor tests
  ocs_ci/ocs/rados_utils.py
  ocs_ci/utility/pagerduty.py
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/pagerduty/test_deployment_status.py
Labels: Verified, size/L, Managed Services

#5393 Automate NSFS tests
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/mcg_params.py
  ocs_ci/ocs/resources/namespacestore.py
  ocs_ci/ocs/resources/objectbucket.py
  ocs_ci/templates/app-pods/ubi8.yaml
  tests/conftest.py
  tests/manage/mcg/test_nsfs.py
Labels: Verified, size/XL, MCG

#5714 log reader writer: local image mirroring when disconnected
  tests/e2e/workloads/test_data_consistency.py
Labels: size/S

#5593 Fixes #5582; Removing Black Squad
  tests/ui/test_add_capacity_ui.py
  tests/ui/test_capacity_breakdown_ui.py
  tests/ui/test_create_pool_block_pool.py
  tests/ui/test_pvc_ui.py
  tests/ui/test_quickstarts.py
  tests/ui/test_validation_ui.py
Labels: size/S

#5717 verify csi users and caps in external mode
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/S

#5611 Closed loop 2040682: multipart upload ops with 0 size(no body) while uploading part
  tests/manage/mcg/test_multipart_upload.py
Labels: Verified, team/e2e, size/M, Customer defects

#5387 Update flag of --delete-local-data in all locations since it's deprecated
  ocs_ci/deployment/aws.py
  ocs_ci/ocs/node.py
Labels: size/S

#5638 Adjust checks to provider cluster
  ocs_ci/ocs/resources/storage_cluster.py
  tests/managed-service/test_post_installation_state.py
Labels: Verified, size/L, Managed Services, Squad/Yellow

#5716 tox: avoid install or sdist setup for logging env
  tox.ini
Labels: size/XS

#3689 external storage class names in fiojob
  ocs_ci/ocs/fiojob.py
  ocs_ci/ocs/tests/test_fiojob.py
Labels: size/M, Squad/Blue

#5721 Remove yq from python requirements
  docs/getting_started.md
  setup.py
Labels: Verified, team/ecosystem, size/XS

#5727 Wait till subscribe appear before checking for version
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/M

#5686 Ypersky clone with multiple files
  tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
Labels: size/L, performance

#5706 Addressing ODF 4.10 console changes
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/ui/views.py
Labels: bug, size/L, ui_automation

#5723 Fixes #5608
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: size/XS

#5719 Update monitoring tests with managed services markers
  tests/manage/monitoring/pagerduty/test_ceph.py
  tests/manage/monitoring/pagerduty/test_deployment_status.py
  tests/manage/monitoring/prometheus/test_capacity.py
  tests/manage/monitoring/prometheus/test_deployment_status.py
  tests/manage/monitoring/prometheus/test_rgw.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_negative.py
  tests/manage/monitoring/prometheusmetrics/test_rgw.py
  tests/manage/monitoring/sendgrid/test_capacity.py
  tests/manage/monitoring/test_workload_example.py
  tests/manage/monitoring/test_workload_fixture.py
  tests/manage/monitoring/test_workload_with_distruptions.py
Labels: Verified, size/M, Managed Services

#5732 Skip tier3 mp test < 4.10
  tests/manage/mcg/test_multipart_upload.py
Labels: size/XS

#5722 Add marker in test based on MS cluster type
  tests/manage/z_cluster/test_must_gather.py
Labels: Verified, size/S, Managed Services

#5711 Do do fail the run if provider is not found
  tests/conftest.py
Labels: enhancement, Verified, size/XS, Managed Services

#5741 Fix condition for monitor down alerting tests
  tests/manage/monitoring/conftest.py
Labels: Verified, size/XS, Managed Services

#5739 fix the test_bulk_pod_attachtime_performance.py dumping results to file
  tests/e2e/performance/csi_tests/test_bulk_pod_attachtime_performance.py
Labels: Verified, size/S, performance

#5744 remove assert statements from PrometheusAPI
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/prometheus.py
Labels: Verified, size/M

#5726 Test case adjustment to run on MS
  ocs_ci/helpers/disruption_helpers.py
  ocs_ci/ocs/ocp.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Labels: Verified, size/L, Managed Services

#5740 PVC UI code enhancement
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/pvc_ui.py
Labels: Verified, size/M, ui_automation

#5759 Add test for consumer's subvolumegroup and cephblockpool
  ocs_ci/ocs/managedservice.py
  tests/managed-service/test_post_installation_state.py
Labels: Verified, size/M, Managed Services, Squad/Yellow

#5761 fix remove_rhcos_workers function
  ocs_ci/deployment/aws.py
Labels: Verified, team/ecosystem, size/XS

#5733 Cosbench workload: small, medium and large size objects
  ocs_ci/ocs/cosbench.py
  tests/e2e/workloads/app/cosbench/test_cosbench.py
Labels: Verified, team/e2e, size/M

#5750 fix aws upi deployment
  ocs_ci/deployment/aws.py
Labels: Verified, team/ecosystem, size/XS

#5680 Skip snapshot tests on MS platform
  tests/manage/pv_services/conftest.py
Labels: Verified, size/S, Managed Services

#5762 Fix marker in test_resource_deletion_during_pvc_pod_creation_and_io
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Labels: Verified, size/XS, Managed Services

#5758 Modify test_disruptive_during_pod_pvc_deletion_and_io to run on MS
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: Verified, size/M, Managed Services

#5602 #Bz1940823 test obc quota feature
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/resources/objectbucket.py
  tests/manage/rgw/conftest.py
  tests/manage/rgw/test_obc_quota.py
Labels: Verified, team/e2e, size/L, Customer defects

#5757 Patch rook-ceph-tools deployment on consumer
  ocs_ci/deployment/rosa.py
  ocs_ci/ocs/managedservice.py
Labels: Verified, size/L, Managed Services

#5763 Add cephresources check
  tests/managed-service/test_post_installation_state.py
Labels: Verified, size/M, Managed Services, Squad/Yellow

#5752 Bulk attach improvement
  tests/e2e/performance/csi_tests/test_bulk_pod_attachtime_performance.py
Labels: Verified, size/L, performance

#5765 Fix ignition version for OCP 4.11
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/utils.py
  ocs_ci/utility/version.py
Labels: Verified, team/ecosystem, size/M

#5557 Add the logic to deploy ocs with addon
  conf/README.md
  conf/ocsci/ibmcloud_disable_odf_addon_deployment.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/resources/mcg.py
Labels: size/M

#5781 Avoid creating duplicate namespace and operator group
  ocs_ci/deployment/deployment.py
Labels: Needs Deployment Testing, team/ecosystem, size/XS

#5783 Update default size to 20 Tib
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/XS, Managed Services

#5769 increasing num of files in the pod and getting rid of teardown factory
  tests/e2e/performance/csi_tests/test_pod_reattachtime.py
Labels: size/XS

#5766 Remove skipif_ms_provider from tests
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: Verified, size/XS, Managed Services

#5779 Add storagecluster postinstall checks
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/M, Managed Services, Squad/Yellow

#5784 Skip PV encryption tests on disconnected and proxy clusters
  ocs_ci/framework/pytest_customization/marks.py
  tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_clone.py
  tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_snapshot.py
  tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption.py
Labels: Verified, team/manage, size/S, Squad/Green

#5702 Enabling deployment on production environment
  conf/README.md
  conf/ocsci/ms_production_env.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/utility/openshift_dedicated.py
Labels: Verified, size/S, Managed Services

#5797 skip mcg-operator check for ODF 4.9 with live deployment
  ocs_ci/deployment/deployment.py
Labels: Needs Deployment Testing, team/ecosystem, size/XS

#5794 Support for ocp installer version parameter for MS ROSA deployment
  ocs_ci/utility/rosa.py
Labels: Verified, size/M, Managed Services

#5800 ES dump bug fix
  tests/e2e/performance/csi_tests/test_pvc_snapshot_performance.py
Labels: size/S

#5791 Add BM Config Files for OCP 4.11
  ocs_ci/templates/ocp-deployment/rhcos_images.yaml
Labels: size/XS

#5799 remove getting internal build number during deployment
  ocs_ci/deployment/deployment.py
Labels: Needs Deployment Testing, team/ecosystem, size/XS

#5619 Add test cases for PV encryption using vaulttenantsa
  ocs_ci/utility/kms.py
  tests/conftest.py
  tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption_vaulttenantsa.py
Labels: Test Case, Verified, team/manage, size/L, new feature, Squad/Green

#5807 Add some consumer cluster checks
  ocs_ci/ocs/resources/storage_cluster.py
Labels: size/M, Managed Services, Squad/Yellow

#5813 W/A for nooobaa 4.10 operator installed on ODF 4.9
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, workaround, size/S
