Repository red-hat-storage/ocs-ci, pull requests merged in 2022-11, with the labels that each got.

#6596 add retry to post flexy backup commands
  ocs_ci/deployment/flexy.py
Labels: Verified, size/S

#6587 Increase MG timeout for ODF4.11 and above
  ocs_ci/ocs/utils.py
Labels: size/XS

#6608 Fix patching the consumer toolbox with MS consumer deployment
  ocs_ci/deployment/rosa.py
Labels: Verified, size/XS, Managed Services

#6573 Remove WA BZ-2124379 [PodSecurity admission]
  ocs_ci/deployment/baremetal.py
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/helpers/lso_helpers.py
  ocs_ci/ocs/ui/deployment_ui.py
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: size/M

#6598 Allow re-try for check ceph health after add_capacity_test
  tests/conftest.py
Labels: team/ecosystem, size/S

#6614 Increasing timeout for toolbox pod readiness check
  ocs_ci/utility/utils.py
Labels: size/XS, Squad/Brown

#6615 Collect OCP must-gather logs for node related tests
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: Verified, size/XS, Squad/Brown

#6616 Adding sleep to avoid flakiness in the MCG test
  ocs_ci/ocs/ui/mcg_ui.py
Labels: Verified, TestCase failing, size/XS, ui_automation

#6620 Fix AWS LSO verification on devicesets
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/XS

#6599 Adjust the number of alertmanager pods
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/XS, Managed Services

#6601 Remove unsupported flags from NSFS tests running on ODF >= 4.12
  tests/conftest.py
Labels: size/XS, MCG

#6604 Update the bucketclass CLI creation to support the replication schema of ODF >= 4.12
  ocs_ci/ocs/resources/mcg.py
Labels: Verified, size/XS, MCG

#6538 Add support for ODF clusterwide encryption using KMIP
  conf/ocsci/ciphertrust_kms_deployment.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/templates/openshift-infra/kmip/ocs-kms-connection-details.yaml
  ocs_ci/templates/openshift-infra/kmip/thales-kmip-ocs-secret.yaml
  ocs_ci/utility/kms.py
Labels: Verified, size/L, new feature

#6627 Ext rgw test fixes
  ocs_ci/ocs/resources/rgw.py
  tests/manage/rgw/test_obc_quota.py
Labels: bug, Verified, size/XS

#6612 Disable lb test 4.12 fix
  tests/manage/mcg/test_s3_routes.py
Labels: Verified, size/M, MCG

#6644 Adding OCP 4.13 config files
  ocs_ci/framework/conf/ocp_version/ocp-4.13-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.13-upgrade.yaml
Labels: Verified, team/ecosystem, size/S

#6058 PR to collect container rpm package details during ocs collect logs phase
  ocs_ci/ocs/utils.py
  tests/conftest.py
Labels: Verified, size/M

#6632 fix for vsphere cleanup for UPI
  ocs_ci/cleanup/vsphere/cleanup.py
Labels: Verified, team/ecosystem, size/XS

#6647 Limit IBM Cloud IPI deployments to OCP version 4.10 or greater
  ocs_ci/deployment/ibmcloud.py
Labels: Verified, team/ecosystem, size/S

#6585 Remove RBD thick provisioning test cases
  tests/manage/pv_services/test_delete_provisioner_pod_while_thick_provisioning.py
  tests/manage/pv_services/test_delete_pvc_while_provisioning.py
  tests/manage/pv_services/test_expansion_snapshot_clone.py
  tests/manage/pv_services/test_rbd_thick_provisioning.py
  tests/manage/pv_services/test_verify_thick_pvc_utilization.py
Labels: Verified, size/XL, Squad/Green

#6619 Test rolling terminate and recovery of the OCS worker nodes for the Managed Service and IPI deployments
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/rosa.py
  tests/manage/z_cluster/nodes/test_rolling_terminate_and_recovery.py
Labels: Verified, size/L, Managed Services

#6664 remove tini from multus tool box
  ocs_ci/ocs/utils.py
Labels: Verified, team/ecosystem, size/XS

#6402 Fix test_overprovision_level_policy_control
  ocs_ci/helpers/helpers.py
  tests/manage/pv_services/test_overprovision_level_policy_control.py
Labels: Verified, size/M

#6655 Fix wrong condition that cause clone_yaml to be None
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/resources/pvc.py
  tests/conftest.py
Labels: Verified, size/S, Squad/Aqua

#6669 added exception for lvmcluster status not exist right after its creation
  ocs_ci/utility/lvmo_utils.py
Labels: Verified, size/XS, Squad/Aqua

#6623 Fix test case error when SC is marked as default
  ocs_ci/ocs/ocp.py
Labels: Verified, team/manage, size/XS, Squad/Green

#6658 skip test_ceph_mons_quorum_lost if ocs version is <4.9
  tests/manage/monitoring/prometheus/test_deployment_status.py
Labels: size/XS, Squad/Blue

#6673 Skip PV Encryption UI test for all versions except OCS 4.8
  tests/ui/test_pv_encryption_ui.py
Labels: Verified, size/XS, ui_automation

#6637 Test Overprovision level policy control with capacity.
  ocs_ci/ocs/ocp.py
  tests/manage/pv_services/test_overprovision_level_policy_control_with_capacity.py
Labels: size/L

#6677 include Loader in yaml.load function
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/XS

#6676 VM's start/stop using FQDN
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/utils.py
Labels: Needs Testing, team/ecosystem, size/S

#6672 Add Managed Service related upgrade checks
  tests/managed-service/conftest.py
  tests/managed-service/test_ms_upgrade.py
Labels: Verified, size/L, Managed Services

#6668 multus public interface config file for OCP 4.12
  conf/ocsci/multus_public_network_interface_412_vsphere.yaml
Labels: Verified, team/ecosystem, size/XS

#6685 Make baremetal debug namespace as privileged
  ocs_ci/deployment/baremetal.py
Labels: Verified, team/ecosystem, size/XS

#6635 Add arbiter deployment over 6 worker nodes in AWS
  conf/deployment/aws/ipi_3az_rhcos_3m_6w_arbiter.yaml
  ocs_ci/deployment/aws.py
  ocs_ci/deployment/helpers/lso_helpers.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/aws.py
Labels: Verified, size/M
