Repository red-hat-storage/ocs-ci, pull requests merged in 2022-12, with the labels that each got.

#6656 Add the consumers verification steps after a provider node replacement to the relevant MS node tests
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_ms.py
  tests/manage/z_cluster/nodes/test_rolling_shutdown_and_recovery_ms.py
  tests/manage/z_cluster/nodes/test_rolling_terminate_and_recovery.py
Labels: Verified, size/L, Managed Services

#6698 Update google package versions
  setup.py
Labels: Verified, team/ecosystem, size/XS

#6701 Update machine CIDR and take it from config
  ocs_ci/templates/ocp-deployment/install-config-rhv-ipi.yaml.j2
Labels: Verified, size/XS

#6695 Increase namespacestore verify_health timeout to 180s
  ocs_ci/ocs/resources/namespacestore.py
Labels: Verified, size/XS, Longevity

#6686 Add a production config for thales kms on aws
  conf/deployment/aws/ipi_1az_rhcos_3m_3w_thales.yaml
Labels: Verified, team/ecosystem, size/S

#6428 close loop 2050056:Test pvc state after tenant configmap is used to o…
  ocs_ci/utility/kms.py
  tests/conftest.py
  tests/manage/pv_services/pv_encryption/test_vault_namespace_override_using_tenant_configmap.py
Labels: Verified, team/e2e, size/L, Customer defects

#6642 Test case to verify noobaa db pw reset
  ocs_ci/helpers/helpers.py
  tests/e2e/kcs/test_noobaadb_pw_reset.py
Labels: Verified, team/e2e, size/L, MCG

#6370 Test OCS deployments/pods with creation of custom SCC
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/security/scc.yaml
  tests/conftest.py
  tests/manage/z_cluster/test_custom_scc.py
Labels: Verified, team/e2e, size/L, Customer defects

#6703 Create a new function to check if the rados connect error is in the exception
  ocs_ci/ocs/managedservice.py
  ocs_ci/utility/utils.py
Labels: Verified, size/S, Managed Services

#6588 Add managedocs security checks
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/M, Managed Services

#6718 review fix
  ocs_ci/ocs/resources/pod.py
Labels: size/S

#6720 fix code
  ocs_ci/ocs/osd_operations.py
  ocs_ci/ocs/resources/pod.py
Labels: size/XS

#6663 Ypersky test ceph capacity recover
  ocs_ci/helpers/helpers.py
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/resources/pod.py
  tests/e2e/performance/csi_tests/test_pvc_bulk_creation_deletion_performance.py
  tests/manage/pv_services/test_ceph_capacity_recovery.py
Labels: size/L, Automation Backlog

#6690 Wait more time for the nodes recovery in the test "test_rolling_nodes_restart" for MS
  ocs_ci/helpers/sanity_helpers.py
  tests/manage/z_cluster/nodes/test_nodes_restart_ms.py
Labels: Verified, size/M, Managed Services

#6725 ocs-osd-removal update job with review fixes
  ocs_ci/ocs/osd_operations.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/utils.py
Labels: size/M

#6681 setup.py upd with gevent and greenlet latest versions
  setup.py
Labels: size/S

#6714 skip test_crashcollector_pod_existence_on_ceph_pods_running_nodes on baremetal
  tests/manage/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
Labels: size/XS

#6733 Add vsphere ipi vault external namespace configs
  conf/deployment/vsphere/ipi_1az_rhcos_vsan_3m_3w_external_vault_v1_with_namespace.yaml
  conf/deployment/vsphere/ipi_1az_rhcos_vsan_3m_3w_external_vault_v2_with_namespace.yaml
Labels: team/ecosystem, size/M

#6693 Fix Installation Doc because Numpy issue
  docs/getting_started.md
Labels: size/S

#6665 OCSCI Container
  Docker_files/ocsci_container/Dockerfile_ocsci
  Docker_files/ocsci_container/README.md
  Docker_files/ocsci_container/k8s.repo
  Docker_files/ocsci_container/scripts/install-ocs-ci.sh
  Docker_files/ocsci_container/scripts/run-ocs-ci.sh
Labels: size/L

#6709 set tag to v4.y instaed of v4.y.0 for GA'ed versions
  ocs_ci/utility/reporting.py
Labels: Verified, team/ecosystem, size/XS

#6707 Fix the mcg-cli command in the mcg_account_factory fixture
  tests/conftest.py
Labels: size/XS, MCG, Squad/Red

#6640 relax the exact PVs verification for BM platform
  ocs_ci/deployment/helpers/lso_helpers.py
Labels: Verified, team/ecosystem, size/S

#6562 Check metadata for rbd images created during the test only
  tests/manage/pv_services/test_rbd_image_metadata.py
Labels: Verified, team/manage, size/S, Squad/Green

#6809 Remove shallow oc get Pod requests
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/utils.py
Labels: size/M

#6797 Update XPath for resize value in UI
  ocs_ci/ocs/ui/views.py
Labels: Verified, team/manage, size/XS, ui_automation

#6821 Use different login method only for managed ibm cluster
  ocs_ci/utility/prometheus.py
Labels: Verified, size/S, IBM Cloud, Squad/Blue

#6810 Fix the test "test_worker_node_restart_during_pvc_expansion" when using MS
  tests/manage/pv_services/pvc_resize/test_node_restart_during_pvc_expansion.py
Labels: Verified, size/S, Managed Services

#6571 Test taint toleration
  tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Labels: Verified, team/e2e, size/M, Customer defects

#6823 Skip test case in external mode
  tests/manage/pv_services/pvc_snapshot/test_verify_rbd_trash_purge.py
Labels: size/XS, Squad/Green

#6820 Add resource type for oc describe command
  ocs_ci/ocs/jenkins.py
Labels: Verified, team/e2e, size/XS

#6829 Skip test cases in external mode
  tests/e2e/workloads/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py
  tests/e2e/workloads/test_new_sc_rbd_e2e_workloads.py
Labels: size/S

#6710 BZ #2124469 automation
  tests/manage/pv_services/test_pvc_delete_subvolumegroup.py
Labels: Verified, team/e2e, size/L, Customer defects

#6808 Ui automate bz2103975
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/ui/views.py
  ocs_ci/utility/users.py
  tests/ui/test_non_admin_user.py
Labels: Verified, team/e2e, size/M, Customer defects, ui_automation

#6839 Catch the exception of "NotFoundError" when going over the pods in the function "get_node_pods"
  ocs_ci/ocs/node.py
Labels: Verified, size/XS

#6852 fix tox issue
  tox.ini
Labels: size/XS

#6851 Adding ODF 4.13 config files
  ocs_ci/framework/conf/ocs_version/ocs-4.13.yaml
  ocs_ci/framework/main.py
Labels: Verified, team/ecosystem, size/S

#6798 Added BlockPools tabs count verification to cover BZ #2096513
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/validation_ui.py
Labels: High Priority, Verified, size/S, Squad/Brown, product-bug

#6869 Removing skip version 4.12
  tests/e2e/workloads/ocp/logging/test_openshift-logging.py
Labels: team/e2e, size/XS

#6828 Skip test_verify_new_cbp_creation_not_blocked_by_invalid_cbp in external mode
  tests/manage/pv_services/test_verify_new_cbp_creation_not_blocked_by_invalid_cbp.py
Labels: size/XS, Squad/Green

#6873 Update ms_osd_pod_memory value
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/XS, Managed Services

#6871 Fixes #6870 and bz marker
  tests/e2e/system_test/test_mcg_replication_with_disruptions.py
  tests/manage/mcg/test_admission_control.py
Labels: team/e2e, size/S

#6868 Skip "test_rook_ceph_operator_log_type" for external mode cluster
  tests/manage/z_cluster/test_rook_ceph_operator_log_type.py
Labels: size/XS, Squad/Brown
