Repository red-hat-storage/ocs-ci, pull requests merged in 2022-10, with the labels that each got.

#6053 Respect the amount parameter that's passed in a namespacestore's dictionary
  ocs_ci/ocs/resources/namespacestore.py
Labels: size/M, MCG, MCG-4.11

#6525 Extend the S3CLI pod health check timeout
  tests/conftest.py
Labels: size/XS, MCG

#6532 closed loop 1954708: Validate noobaa disableLoadBalancerService
  tests/manage/mcg/test_s3_routes.py
Labels: Verified, team/e2e, size/M, MCG, Customer defects

#6546 switch to default namespace before deleting cosbench namespace
  ocs_ci/ocs/cosbench.py
Labels: team/e2e, size/XS

#6547 update protobuf
  setup.py
Labels: Verified, team/ecosystem, size/XS

#6543 Bucket policy fixes
  ocs_ci/ocs/resources/bucket_policy.py
  tests/manage/mcg/test_bucket_policy.py
Labels: Verified, size/L, MCG

#6519 Enhancements for openshift-logging
  ocs_ci/ocs/constants.py
  ocs_ci/utility/deployment_openshift_logging.py
  ocs_ci/utility/uninstall_openshift_logging.py
  tests/conftest.py
Labels: Verified, team/e2e, size/L

#6537 Update OSD cpu in MS topology check
  ocs_ci/helpers/managed_services.py
Labels: Verified, size/XS, Managed Services

#6014 Fix: Updated kmscondition string to check in logs
  tests/manage/mcg/test_kms.py
Labels: size/XS

#6533 changes for : ACM 2.5 and odf4.11
  conf/ocsci/skip_dr_deploy.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/acm_ui.py
  ocs_ci/ocs/ui/views.py
  ocs_ci/templates/ocs-deployment/multicluster/dr_policy_acm_hub.yaml
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/L, DR

#6488 adding heterogeneous variable for AWS UPI deployments
  ocs_ci/deployment/aws.py
  ocs_ci/framework/conf/default_config.yaml
Labels: Needs Deployment Testing, team/ecosystem, size/XS

#6522 Fix UI LSO deployment for 4.12
  ocs_ci/ocs/ui/deployment_ui.py
Labels: Verified, team/ecosystem, size/XS, ui_automation

#6564 Fix rhel UPI deployment
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/XS

#6565 ocp 4-12 repo file for RHEL UPI
  ocs_ci/repos/ocp_4_12_rhel7.repo
  ocs_ci/repos/ocp_4_12_rhel8.repo
Labels: Verified, team/ecosystem, size/M

#6469 Test MCG cached buckets
  ocs_ci/ocs/bucket_utils.py
  tests/manage/mcg/test_cached_buckets.py
Labels: size/L, MCG

#6429 LVMO - Manual disk path
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/lvmo-deployment/lvm-cluster-default.yaml
  ocs_ci/utility/lvmo_utils.py
  tests/lvmo/conftest.py
  tests/lvmo/test_lvm_manual_diskpath.py
Labels: Verified, size/L, Lvmo, Squad/Aqua

#6165 Modify `cal_md5sum` to support pods without PVCs
  ocs_ci/ocs/resources/pod.py
  tests/manage/mcg/test_bucket_replication.py
Labels: size/S

#6555 Filter PagerDuty incidents based on a service
  ocs_ci/utility/pagerduty.py
  ocs_ci/utility/workloadfixture.py
  tests/conftest.py
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/pagerduty/test_ceph.py
  tests/manage/monitoring/pagerduty/test_deployment_status.py
Labels: Verified, size/L, Managed Services

#6474 Add verification steps on the MS consumers after a provider node replacement
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/utility/decorators.py
  ocs_ci/utility/rosa.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Verified, size/L, Managed Services

#6568 Locator changes based upon ODF version
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/M, ui_automation

#6570 Update the OBC replication schema
  ocs_ci/ocs/resources/objectbucket.py
Labels: Verified, size/XS, MCG

#6470 [RDR] Change default workload repo and support new directory structure of ocs-workloads repository
  conf/ocsci/dr_workload.yaml
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/dr/dr_workload.py
Labels: Verified, size/M, DR

#6545 Fix 6544
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/XS

#6572 Skip volume detach tests in MS
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/XS, Managed Services

#6569 Update OSD expected state in test_automated_recovery_from_failed_nodes_reactive_ms[drain_node]
  ocs_ci/ocs/constants.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_ms.py
Labels: Verified, size/XS, Managed Services

#6275 Add IBM Cloud IPI Deployment support
  conf/deployment/ibmcloud/ipi_3az_rhcos_3m_3w.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/factory.py
  ocs_ci/deployment/ibmcloud.py
  ocs_ci/deployment/ocp.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/exceptions.py
  ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
Labels: Verified, team/ecosystem, size/L

#6567 updated lvmcluster name to be aligned with dev configuration
  ocs_ci/templates/lvmo-deployment/lvm-cluster-411.yaml
  ocs_ci/templates/lvmo-deployment/lvm-cluster-412.yaml
Labels: Verified, size/XS, Lvmo, Squad/Aqua

#6583 Pin google-auth-oauthlib to specific version
  setup.py
Labels: team/ecosystem, size/XS

#6580 Disable NFS tests
  tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Labels: team/ecosystem, size/XS

#6578 Add repeat for wait_for_rebalance
  ocs_ci/ocs/cluster.py
Labels: size/M

#6576 Look for the correct external RGW route name
  ocs_ci/ocs/resources/rgw.py
Labels: size/S, RGW

#6178 PV Encryption via User Interface
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/pvc_ui.py
  ocs_ci/ocs/ui/storageclass.py
  ocs_ci/ocs/ui/views.py
  tests/conftest.py
  tests/ui/test_pv_encryption_ui.py
Labels: Verified, size/XL, ui_automation

#6591 supporting vSphere IPI cleanup
  ocs_ci/cleanup/vsphere/cleanup.py
Labels: team/ecosystem, size/M

#6594 Support new MCG replication rules schema for OBC patches and bucketclasses
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/resources/mcg.py
  tests/e2e/scale/noobaa/test_scale_bucket_replication.py
  tests/e2e/system_test/test_mcg_replication_with_disruptions.py
  tests/manage/mcg/test_bucket_replication.py
Labels: size/L, MCG
