Repository red-hat-storage/ocs-ci, pull requests merged in 2022-09, with the labels that each got.

#6388 Fix cosbench cleanup
  ocs_ci/ocs/cosbench.py
Labels: Verified, team/e2e, size/XS

#6312 Test if RBD images have metadata being set
  tests/manage/pv_services/test_rbd_image_metadata.py
Labels: Verified, team/e2e, size/M

#6271 Modify the Managed service markers to use the default cluster context
  ocs_ci/framework/__init__.py
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/managedservice.py
  tests/managed-service/test_ms_markers.py
Labels: Verified, size/L, Managed Services

#6280 [RDR] Improve resource leftover detection on managed cluster and cleanup
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/dr/dr_workload.py
  tests/conftest.py
Labels: Verified, size/L, DR

#6341 Bz 2111895 automation - PVC resize on lvm cluster
  tests/lvmo/test_lvmo_pvc_resize.py
Labels: Verified, size/L, Lvmo

#6286 Unblock snapshot tests in MS if ODF version is 4.11 or above
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  tests/manage/pv_services/conftest.py
  tests/manage/pv_services/pvc_snapshot/test_pvc_snapshot_when_snapshotclass_deleted.py
Labels: Verified, size/S, Managed Services

#6369 Fix issues related to pod security admission
  ocs_ci/deployment/helpers/lso_helpers.py
  ocs_ci/helpers/disruption_helpers.py
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/templates/app-pods/performance_block.yaml
  tests/conftest.py
  tests/manage/pv_services/test_ceph_daemon_kill_during_resource_deletion.py
  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_deletion_and_io.py
  tests/manage/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
  tests/manage/z_cluster/test_coredump_check_for_ceph_daemon_crash.py
Labels: Verified, team/manage, size/M

#6400 Added the flexibilty to skip waiting for the workload to complete to all workload fixtures
  ocs_ci/ocs/couchbase.py
  ocs_ci/ocs/pillowfight.py
  tests/conftest.py
Labels: Verified, team/e2e, size/M

#6378 Add the step of terminating the VM in the node replacement UPI steps
  ocs_ci/ocs/node.py
  ocs_ci/ocs/platform_nodes.py
Labels: Verified, size/M, Squad/Brown

#6394 Add consumer's capacity check
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S, Managed Services

#6409 set must gather tag to v4.11.0 for ODF 4.11 GA'ed versions
  ocs_ci/utility/reporting.py
Labels: Verified, team/ecosystem, size/XS

#6417 Fix snapshot apiVersion based on OCP version
  ocs_ci/ocs/resources/pvc.py
Labels: Verified, size/XS

#6399 Increasing re balance timeout and retrying to get PDB's post node drain
  ocs_ci/ocs/cluster.py
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: size/S, Squad/Brown

#6328 Create a new file for testing the rolling shutdown and recovery of the OCS worker nodes when using MS
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/nodes/test_rolling_shutdown_and_recovery_ms.py
Labels: Verified, size/L, Managed Services

#5935 Test case to verify StorageClassClaim
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storageclassclaim.py
  ocs_ci/templates/storageclassclaim/storageclassclaim.yaml
  tests/managed-service/test_storageclassclaim.py
Labels: Verified, size/L, Managed Services

#6395 squad for nfs feature
  ocs_ci/ocs/constants.py
Labels: team/ecosystem, size/XS

#6418 Add wait for managedocs components to get ready
  ocs_ci/ocs/managedservice.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/M, Managed Services

#6362 Create a new sanity helper class for the Managed Sevice
  ocs_ci/helpers/sanity_helpers.py
  tests/managed-service/test_sanity_ms.py
Labels: Verified, size/L, Managed Services

#6414 Add label to NS openshift-storage for PodSecurity admission
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/utils.py
Labels: Verified, team/ecosystem, size/S

#6403 Fix disk replacement test
  ocs_ci/ocs/osd_operations.py
Labels: Verified, size/S

#6421 update RHCOS template for OCP 4.12
  ocs_ci/framework/conf/ocp_version/ocp-4.12-config.yaml
Labels: Verified, team/ecosystem, size/XS

#6423 Fix OCP 4.12 upgrade
  ocs_ci/ocs/utils.py
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Verified, team/ecosystem, size/S

#6415 Added must-gather on ODF4.12
  ocs_ci/ocs/must_gather/const_must_gather.py
Labels: Verified, size/S

#6432 Added marker polarion_id for TestUserInterfaceValidation
  tests/ui/test_validation_ui.py
Labels: size/XS

#6379 Test case to verify unschedule, drain and restart of a worker node in the provider
  tests/manage/z_cluster/nodes/test_nodes_restart_ms.py
Labels: Test Case, Verified, size/L, Managed Services

#6420 Update cephfs RWO PVC tests for ODF 4.12
  tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
  tests/manage/pv_services/test_verify_rwo_using_dc_pod.py
  tests/manage/pv_services/test_verify_rwo_using_multiple_pods.py
Labels: High Priority, Verified, team/manage, size/M, Squad/Green

#6259 skip test_scale_obc pre and post upgrade tests in managed service
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_obc.py
Labels: enhancement, Verified, size/XS, upgrade, Managed Services

#6435 Added Polarion-ID,UI storage_system
  tests/ui/test_validation_ui.py
Labels: size/XS

#6229 close loop 2031705:Validate OBC access to admin of a Project on Console
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
  tests/conftest.py
  tests/ui/test_other_user.py
Labels: Needs Testing, team/e2e, size/L, Customer defects

#6361 Test object versioning with parallel ops
  tests/manage/mcg/test_object_versioning.py
Labels: Verified, team/e2e, size/L, Customer defects

#6436 Add 4.12 Images for BareMetal Deployment
  ocs_ci/deployment/baremetal.py
Labels: Verified, size/M

#6443 Fix login UI function
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/base_ui.py
Labels: size/XS

#6383 make test_log_reader_writer_paraller more error resilient
  tests/e2e/workloads/test_data_consistency.py
Labels: size/XS

#6438 Added aws_platform_required tag for the suite to run it only for AWS clusters
  tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Labels: Verified, size/XS, Squad/Brown

#6270 [GSS] Add 2 disks on same node for Flexible Scaling
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/views.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Labels: Verified, team/e2e, size/L, Customer defects

#6460 Scale s3 delete bucket for buckets having huge number of objects
  ocs_ci/ocs/resources/objectbucket.py
Labels: Verified, team/e2e, size/XS, MCG

#6425 Create new markers for checking if we use the Managed Service with provider and consumer clusters
  ocs_ci/framework/__init__.py
  ocs_ci/framework/pytest_customization/marks.py
  tests/e2e/workloads/test_create_scale_pods_and_pvcs_using_kube_job.py
Labels: Verified, size/M, Managed Services

#6464 Revert changes made in PR 6420
  tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
Labels: Verified, team/manage, size/S

#6457 Change pod label dictionary above 4.11 to default and add pod security label to openshift-storage
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/lvmo-deployment/lvm-cluster-412.yaml
Labels: Verified, size/S, Lvmo, Squad/Aqua

#6456 Added skipif_external_mode tag for the nfs testsuite
  tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Labels: Verified, size/XS, Squad/Brown

#6277 Scale testing: Add Warp S3 benchmark
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/scale_noobaa_lib.py
  ocs_ci/ocs/warp.py
  ocs_ci/templates/app-pods/warp.yaml
  ocs_ci/templates/workloads/warp/warp_obj.yaml
  tests/e2e/scale/noobaa/test_warp.py
Labels: size/L, scale

#6386 fix function convert_device_size
  ocs_ci/ocs/node.py
  ocs_ci/utility/utils.py
Labels: Verified, size/M

#6468 Skip the test test_overprovision_level_policy_control in MS
  tests/manage/pv_services/test_overprovision_level_policy_control.py
Labels: Verified, size/XS, Managed Services

#6345 Add lvm cluster health check
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/lvmo_utils.py
  tests/lvmo/test_lvm_alerts.py
Labels: Verified, size/L, Lvmo

#6397 fixing pod_attach_csi_time function
  ocs_ci/helpers/performance_lib.py
  tests/e2e/performance/csi_tests/test_bulk_pod_attachtime_performance.py
  tests/e2e/performance/csi_tests/test_pod_attachtime.py
  tests/e2e/performance/csi_tests/test_pod_reattachtime.py
Labels: Verified, size/L, performance

#6449 Update bugzilla marker in the test test_connection_time_out
  tests/managed-service/test_post_installation_state.py
Labels: Verified, size/XS, Managed Services

#6377 Defaulting ocs-ci to ODF 4.12
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, team/ecosystem, size/S

#6461 Increase pod wait time in test test_change_reclaim_policy_of_pv
  tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
Labels: Verified, team/manage, size/XS, Squad/Green

#6445 Use Different namespace for debug for Baremetal Deployment
  ocs_ci/deployment/baremetal.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
Labels: size/M

#6442 Add capacity on ODF4.12 via UI
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/S

#5947 Add failover and relocate tests for Regional DR
  ocs_ci/framework/pytest_customization/marks.py
  pytest.ini
  tests/conftest.py
  tests/disaster-recovery/regional-dr/test_failover.py
  tests/disaster-recovery/regional-dr/test_failover_and_relocate.py
  tests/disaster-recovery/regional-dr/test_relocate.py
Labels: Verified, size/L, DR

#6475 Set AWS SC to gp2-csi from 4.12
  ocs_ci/deployment/aws.py
  ocs_ci/ocs/ui/base_ui.py
Labels: Verified, team/ecosystem, size/XS

#6477 Polarion ID on Flexible Scaling
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Labels: size/XS

#6480 Fix test_validate_ceph_config_values_in_rook_config_override for ODF 4.10
  ocs_ci/ocs/constants.py
Labels: Verified, size/XS, Squad/Brown

#6484 Increasing timeout for cluster health check
  ocs_ci/helpers/sanity_helpers.py
Labels: Verified, size/XS, Squad/Brown

#6408 UI deployment on 4.12
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, Needs Deployment Testing, size/S

#6482 Add securityAdmissions for Localstorage
  ocs_ci/deployment/helpers/lso_helpers.py
Labels: Verified, team/ecosystem, size/XS

#6478 Splitting the performance suite to 3
  ocs_ci/framework/pytest_customization/marks.py
  pytest.ini
  tests/e2e/performance/csi_tests/test_bulk_pod_attachtime_performance.py
  tests/e2e/performance/csi_tests/test_pod_attachtime.py
  tests/e2e/performance/csi_tests/test_pod_reattachtime.py
  tests/e2e/performance/csi_tests/test_pvc_bulk_clone_performance.py
  tests/e2e/performance/csi_tests/test_pvc_bulk_creation_deletion_performance.py
  tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
  tests/e2e/performance/csi_tests/test_pvc_creation_deletion_performance.py
  tests/e2e/performance/csi_tests/test_pvc_multi_clone_performance.py
  tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py
  tests/e2e/performance/csi_tests/test_pvc_snapshot_performance.py
  tests/e2e/performance/io_workload/test_fio_benchmark.py
  tests/e2e/performance/io_workload/test_perf_pgsql.py
  tests/e2e/performance/io_workload/test_small_file_workload.py
  tests/e2e/performance/mcg/test_mcg_cosbench.py
Labels: size/M

#6390 Fix pod count parsing in get_pod_restarts_count()
  ocs_ci/ocs/resources/pod.py
Labels: size/XS

#6486 get latest lso channel
  ocs_ci/utility/localstorage.py
Labels: Verified, team/ecosystem, size/M

#6495 Disconnected deployment: add required packages for OCP/ODF 4.12
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/S

#5894 <GSS Closed Loop BZ: 2052079> To list whole objects without any failures
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/app-pods/fedoraServiceCA.yaml
  ocs_ci/templates/app-pods/fedora_with_linuxtar_files.yaml
  tests/conftest.py
  tests/e2e/scale/noobaa/test_list_objects.py
Labels: Test Case, Verified, size/L, Customer defects

#6221 Longevity testing all stages
  ocs_ci/helpers/longevity_helpers.py
  ocs_ci/ocs/couchbase.py
  ocs_ci/ocs/longevity.py
  ocs_ci/ocs/pgsql.py
  ocs_ci/ocs/pillowfight.py
  tests/conftest.py
  tests/e2e/longevity/test_all_stages.py
  tests/e2e/longevity/test_stage0.py
  tests/e2e/longevity/test_stage1.py
  tests/e2e/longevity/test_stage3.py
Labels: Verified, team/e2e, size/L, Longevity

#6498 Fix UI GCP 4.12 SC for deployment
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, team/ecosystem, size/S

#6504 Fix get resource for node status
  ocs_ci/ocs/ocp.py
Labels: size/S

#6447 Closed loop 2067079 2063691: Test s3 routes update/reconcile
  tests/manage/mcg/test_object_expiration.py
  tests/manage/mcg/test_s3_routes.py
Labels: Verified, team/e2e, size/L, MCG, Customer defects

#6508 update cryptography to 38.0.1
  setup.py
Labels: Verified, team/ecosystem, size/XS

#6343 Increase timeout for mon pods to upgrade
  ocs_ci/ocs/ocs_upgrade.py
Labels: size/XS

#6501 Add dev addon config files
  conf/deployment/rosa/managed_1az_consumer_dev_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_1az_consumer_dev_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_1az_provider_dev_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_consumer_dev_3m_3w_m52x.yaml
  conf/deployment/rosa/managed_3az_consumer_dev_3m_3w_m54x.yaml
  conf/deployment/rosa/managed_3az_provider_dev_3m_3w_m54x.yaml
Labels: Verified, size/L, Managed Services

#6493 Use TimeoutIterator to fix too many failed Prometheus requests after upgrade
  ocs_ci/utility/prometheus.py
Labels: bug, Verified, size/M, Squad/Blue

#6514 Skipping logging for odf 4.12 as per https://issues.redhat.com/browse…
  tests/e2e/workloads/ocp/logging/test_openshift-logging.py
Labels: size/XS

#6492 Use the ingress cert for IBM Cloud deployments
  ocs_ci/ocs/bucket_utils.py
Labels: size/XS, MCG

#6441 RHSTOR-3506: Qualify "Support resource modification for MCG PV pool pods - Test and Docs only"
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/resources/backingstore.py
  tests/manage/mcg/test_pv_pool.py
Labels: Verified, team/e2e, size/L, MCG

#6524 Fix logging test skip condition
  tests/e2e/workloads/ocp/logging/test_openshift-logging.py
Labels: team/e2e, size/XS

#6526 Skip test <4.9 ocs version
  tests/manage/z_cluster/test_ceph_default_values_check.py
Labels: size/XS

#6516 Verify topology in MS
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/L, Managed Services

#6527 Update topology check in MS
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S, Managed Services

#6510 Collect OCP must-gather for all cluster expansion test
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: size/XS, Squad/Brown

#6529 Fix network split setup for arbiter deployment
  ocs_ci/deployment/deployment.py
Labels: bug, Verified, team/ecosystem, size/XS
