Repository red-hat-storage/ocs-ci, pull requests merged in 2022-01, with the labels that each got.

#5110 Implement MCG DB recovery system test
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/resources/cloud_manager.py
  tests/e2e/conftest.py
  tests/e2e/kcs/test_noobaa_db_backup_and_recovery.py
  tests/e2e/system/test_mcg_recovery.py
Labels: team/e2e, size/XL

#5291 Wait after approving install plan
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/XS

#4921 Fix test failures in test_worker_nodes_network_failures.py
  ocs_ci/helpers/helpers.py
  tests/manage/z_cluster/nodes/test_worker_nodes_network_failures.py
Labels: Verified, size/L

#5257 PGSQL AUTOMATION
  ocs_ci/ocs/perf_pgsql.py
  tests/e2e/performance/io_workload/test_perf_pgsql.py
Labels: size/L, performance

#5297 Fix getting CSV from install plan
  ocs_ci/ocs/resources/packagemanifest.py
Labels: Verified, Code/Infra, size/XS

#5293 Adding OCP 4.10 repo
  ocs_ci/repos/ocp_4_10.repo
Labels: team/ecosystem, size/M

#5206 <Closed loop BZ: 1992472> Non-ocs Taint and toleration
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
  tests/manage/z_cluster/nodes/test_toleration.py
Labels: Verified, team/e2e, size/L, Customer defects

#5302 Fix manual approval strategy upgrade for 4.9
  ocs_ci/ocs/ocs_upgrade.py
Labels: team/ecosystem, size/S, upgrade

#5258 Introduce a common cli option '--default-cluster-context-index'
  ocs_ci/framework/__init__.py
  ocs_ci/framework/main.py
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: Verified, team/ecosystem, size/M

#5037 Must Gather, verify ceph command does not return an error
  ocs_ci/ocs/must_gather/const_must_gather.py
  ocs_ci/ocs/must_gather/must_gather.py
Labels: size/S

#5288 bulk_deletion_send_to_es
  tests/e2e/performance/csi_tests/test_pvc_creation_deletion_performance.py
Labels: size/M

#5284 Fix the test 'test_automated_recovery_from_stopped_node_and_start' to run with vsphere ipi
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/vsphere.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: size/L

#5264 MCG DB SCC name changed for test_db_scc
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  tests/manage/mcg/test_mcg_resources_disruptions.py
Labels: size/M

#5308 Use rsync for copy noobaa CLI binary
  ocs_ci/ocs/resources/mcg.py
Labels: team/ecosystem, size/S

#5306 Log cluster load massages in debug instead of info
  ocs_ci/ocs/cluster_load.py
  ocs_ci/utility/prometheus.py
Labels: Verified, size/S

#5303 pod_reattach TC - push the results into the performance dashboard
  tests/e2e/performance/csi_tests/test_pod_reattachtime.py
Labels: Verified, size/L, performance, Squad/Gray

#5292 Deploy an AWS cluster with the new storage classes gp2-csi, gp3-csi
  conf/README.md
  conf/deployment/aws/gp2_csi_storage_class.yaml
  conf/deployment/aws/gp2_storage_class.yaml
  conf/deployment/aws/gp3_csi_storage_class.yaml
  ocs_ci/deployment/aws.py
Labels: size/S

#5304 Improving manual approval strategy installation and wait for CSV
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, Code/Infra, size/XS

#5180 Configuration files for minimal resources deployment
  conf/ocsci/aws_minimal_deployment.yaml
  conf/ocsci/vsphere_minimal_deployment.yaml
Labels: Verified, size/S

#5144 Enables to run test cases on MCG only deployment
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/helpers/sanity_helpers.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/utils.py
  tests/conftest.py
Labels: Verified, team/ecosystem

#5317 sending results to perf dashboard
  tests/e2e/performance/csi_tests/test_pvc_bulk_creation_deletion_performance.py
Labels: size/M

#5318 changing keep_on_remove state to false in state file
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/XS

#5235 Readd MCG CLI copying support for OCS <4.6
  ocs_ci/ocs/resources/mcg.py
Labels: Verified, size/M, MCG

#5326 Increase timeout for rebalance after OCP upgrade
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Needs Testing, size/XS

#5325 skip record_testsuite_property for OCP only deployments
  tests/conftest.py
Labels: Verified, team/ecosystem, size/XS

#5248 Scale bucket replication test cases
  tests/e2e/scale/noobaa/test_scale_bucket_replication.py
Labels: size/L, scale

#5328 Skip the test_mcg_db_backup_recovery if the version is lower than 4.9
  tests/e2e/system/test_mcg_recovery.py
Labels: size/XS

#5319 updating squads to include TestMCGRecovery
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/XS

#5323 Delete template folder during post destroy
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/XS

#5313 Fixing Scale endpoint test failure
  ocs_ci/ocs/machine.py
Labels: size/XS, scale

#5282 OCP4.10, UI deployment
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/views.py
Labels: size/M

#5315 Enhanced TC tests/e2e/performance/csi_tests/test_pvc_bulk_clone_performance.py for Dashboard Integration
  tests/e2e/performance/csi_tests/test_pvc_bulk_clone_performance.py
Labels: Verified, size/S, performance

#5332 Fix test_ceph_metrics_available
  ocs_ci/ocs/metrics.py
  ocs_ci/ocs/monitoring.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_negative.py
Labels: Test Case, size/L, Merge As Is (Don't Squash), Squad/Blue

#5338 adding push to dashboard
  tests/e2e/performance/csi_tests/test_pvc_attachtime.py
Labels: size/M

#5340 Fix missing ocs secret for upgrade to 4.9 on IBM Cloud
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/XS, upgrade

#5322 Add run_id to rp launch attributes
  ocs_ci/utility/reporting.py
Labels: team/ecosystem, size/XS, Report Portal

#5337 improve the create_storage_class helper function
  ocs_ci/helpers/helpers.py
Labels: Verified, size/M

#5309 Use Basic auth for accessing OCP repos
  ocs_ci/deployment/aws.py
  ocs_ci/deployment/install_ocp_on_rhel.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/repos/ocp_4_10.repo
  ocs_ci/repos/ocp_4_2.repo
  ocs_ci/repos/ocp_4_3.repo
  ocs_ci/repos/ocp_4_4.repo
  ocs_ci/repos/ocp_4_5.repo
  ocs_ci/repos/ocp_4_6.repo
  ocs_ci/repos/ocp_4_7.repo
  ocs_ci/repos/ocp_4_8.repo
  ocs_ci/repos/ocp_4_9.repo
  ocs_ci/utility/mirror_openshift.py
Labels: Verified, team/ecosystem, size/L

#5346 fix typo of acm namespace
  ocs_ci/ocs/acm/acm_constants.py
Labels: size/XS

#5345 fix test_ceph_metrics_available issue for 4.9 as well
  ocs_ci/ocs/metrics.py
  ocs_ci/ocs/monitoring.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_negative.py
Labels: Test Case, size/L

#5311 Update live must gather image for ODF
  conf/README.md
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
  conf/ocsci/ocs-live-must-gather.yaml
  conf/ocsci/odf-live-must-gather.yaml
  docs/upgrade.md
  docs/usage.md
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.10.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.5.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.6.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.7.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.8.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.9.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/utils.py
  ocs_ci/utility/reporting.py
Labels: Verified, team/ecosystem, size/L

#5347 Add pytest-repeat module
  setup.py
Labels: team/ecosystem, size/XS

#5298 Enabling upgrade testing during acceptance pipeline
  .functional_ci_setup.py
  Jenkinsfile
  ocs_ci/framework/main.py
  ocs_ci/framework/tests/test_main.py
Labels: Verified, size/L

#5330 Must-Gather, disconnected environment, bz-1974959
  ocs_ci/ocs/utils.py
Labels: Verified, team/e2e, size/S, Customer defects

#5273 Update OCP deployment templates to be able to use different pod network
  ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-aws-upi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-azure-ipi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-gcp-ipi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-vsphere-ipi.yaml.j2
Labels: Verified, size/S, DR

#5349 Added "ui" marker for ui tests
  tests/manage/mcg/ui/test_mcg_ui.py
  tests/ui/test_add_capacity_ui.py
  tests/ui/test_capacity_breakdown_ui.py
  tests/ui/test_pvc_ui.py
  tests/ui/test_ui.py
  tests/ui/test_validation_ui.py
Labels: Verified, size/M

#5188 Add possibility to skip index image prune and images mirroring on disconnected environment
  conf/README.md
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/S

#5299 refactoring the multi-snapshot TC for better performance
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/perftests.py
  tests/e2e/performance/csi_tests/test_multi_snapshots.py
  tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py
Labels: Verified, size/XXL, performance, Squad/Gray

#5362 Return to const usage for noobaa scc test
  ocs_ci/ocs/bucket_utils.py
  tests/manage/mcg/test_mcg_resources_disruptions.py
Labels: size/S

#5375 Skip amq tests on fips enabled cluster
  ocs_ci/ocs/amq.py
  ocs_ci/templates/workloads/amq/kafkadrop.yaml
Labels: Verified, team/e2e, size/XS

#5370 Fix disconnected live upgrade
  ocs_ci/deployment/disconnected.py
Labels: team/ecosystem, size/S

#5343 Adding new "system_test" marker for running systemtests
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/constants.py
  pytest.ini
  tests/e2e/system_test/test_mcg_recovery.py
Labels: Verified, team/e2e, size/S

#5379 Fixing concatenation of variable
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/XS

#5377 Verify odf-csi-addons during deployment
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/defaults.py
Labels: Verified, team/ecosystem, size/XS

#5363 Ypersky multi clone dashboard
  tests/e2e/performance/csi_tests/test_pvc_multi_clone_performance.py
Labels: size/L, performance

#5359 Update fio server pod count in test_fio_benchmark.py
  tests/e2e/performance/io_workload/test_fio_benchmark.py
Labels: size/XS, performance

#5388 Add UI deployment parameter to minimal deployment config files
  conf/ocsci/aws_minimal_deployment.yaml
  conf/ocsci/vsphere_minimal_deployment.yaml
Labels: Verified, size/XS

#5381 upate test_mcg_hpa to horizontal-pod-autoscaler-v2
  tests/manage/monitoring/prometheusmetrics/test_mcg_hpa.py
Labels: Verified, size/S, Squad/Blue

#5237 Test mon disk threshold when disk usage >= 85%
  tests/manage/z_cluster/test_mon_data_avail_warn.py
Labels: Verified, team/e2e, size/L, Customer defects

#5167 Mon recovery system test automation
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  tests/e2e/system_test/mon/test_restore_ceph_mon_quorum.py
Labels: Test Case, Verified, team/e2e, size/L

#5320 Use the correct port when adding nodes to the HAProxy config
  ocs_ci/utility/load_balancer.py
Labels: Verified, size/XS

#5275 Change rosa cli version to 1.1.7
  conf/ocsci/rosa.yaml
  ocs_ci/deployment/rosa.py
  ocs_ci/utility/openshift_dedicated.py
  ocs_ci/utility/rosa.py
Labels: Verified, size/M, Managed Services

#5344 Submariner creation via UI on ACM console
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/ui/views.py
  tests/conftest.py
  tests/ecosystem/deployment/test_acm.py
Labels: Verified, size/L, ui_automation, DR

#5389 increase mon timeout during deployment
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/XS

#5392 Update ocm cli version
  conf/ocsci/openshift_dedicated.yaml
  conf/ocsci/rosa.yaml
  ocs_ci/deployment/rosa.py
Labels: Verified, size/XS, Managed Services, Squad/Yellow

#5207 Encrypt PVC support for snapshot and clone
  ocs_ci/ocs/pgsql.py
  tests/conftest.py
  tests/e2e/flowtest/pvc_snapshot_and_clone/test_pgsql_pvc_snapshot_and_clone.py
  tests/e2e/flowtest/pvc_snapshot_and_clone/test_pgsql_pvc_snapshot_and_clone_with_base_operation.py
  tests/e2e/lifecycle/pvc_clone/test_pgsql_pvc_clone.py
  tests/e2e/lifecycle/pvc_snapshot/test_pgsql_pvc_snapshot.py
  tests/e2e/workloads/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py
Labels: Test Case, Verified, team/e2e, size/XL

#5243 Test case for bz 1989301 reproducer
  .github/CODEOWNERS
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/job.py
  ocs_ci/ocs/resources/objectconfigfile.py
  ocs_ci/ocs/resources/topology.py
  ocs_ci/templates/workloads/logwriter/README.md
  ocs_ci/templates/workloads/logwriter/cephfs.logreader.yaml
  ocs_ci/templates/workloads/logwriter/cephfs.logwriter.yaml
  ocs_ci/templates/workloads/logwriter/cephfs.reproducer.yaml
  tests/e2e/workloads/test_data_consistency.py
Labels: Test Case, Verified, size/XL, Customer defects, Merge As Is (Don't Squash)

#5394 Disconnected upgrade: make imageContentSourcePolicy name unique
  ocs_ci/deployment/disconnected.py
Labels: team/ecosystem, size/XS

#5368 Add RHEL 7.9 AMI and possibility to define RHEL 8
  conf/README.md
  conf/deployment/aws/upi_1az_rhel7_3m_3w.yaml
  conf/deployment/aws/upi_1az_rhel7_lso_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhel7_3m_3w.yaml
  conf/deployment/aws/upi_3az_rhel7_lso_3m_3w.yaml
  conf/ocsci/aws_upi_rhel7_workers.yaml
  conf/ocsci/aws_upi_rhel8_workers.yaml
  ocs_ci/deployment/aws.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
Labels: Verified, team/ecosystem, size/M

#5395 Add capacity via UI on OCP4.10
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/S

#5404 Change the IP of the development elasticsearch server
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/defaults.py
  ocs_ci/templates/workloads/osd_scale/osd_scale_benchmark.yaml
  ocs_ci/templates/workloads/smallfile/SmallFile.yaml
Labels: size/XS

#5391 Closed Loop BZ-2012930 'noobaa-postgres-config' configmap doesn't get…
  ocs_ci/ocs/constants.py
  tests/manage/z_cluster/test_ceph_default_values_check.py
Labels: team/e2e, size/M, Customer defects

#5098 OCS deployment with ACM and DR workload
  conf/ocsci/dr_workload.yaml
  conf/ocsci/multicluster_acm_cluster.yaml
  conf/ocsci/multicluster_dr_rbd.yaml
  conf/ocsci/multicluster_primary_cluster.yaml
  conf/ocsci/submariner_upstream.yaml
  ocs_ci/deployment/acm.py
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/__init__.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/dr/dr_workload.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/utils.py
  ocs_ci/templates/ocs-deployment/multicluster/dr_aws_s3_profile.yaml
  ocs_ci/templates/ocs-deployment/multicluster/dr_policy_acm_hub.yaml
  ocs_ci/templates/ocs-deployment/multicluster/mirror_peer.yaml
  ocs_ci/templates/ocs-deployment/multicluster/odf_multicluster_orchestrator.yaml
  ocs_ci/templates/ocs-deployment/multicluster/odf_orchestrator_operatorgroup.yaml
  ocs_ci/templates/ocs-deployment/multicluster/odr_s3_secret.yaml
  ocs_ci/templates/ocs-deployment/multicluster/openshift_dr_cluster_operator.yaml
  ocs_ci/templates/ocs-deployment/multicluster/openshift_dr_hub_operator.yaml
  ocs_ci/templates/ocs-deployment/multicluster/openshift_dr_system.yaml
  ocs_ci/templates/ocs-deployment/multicluster/openshift_dr_system_operatorgroup.yaml
  ocs_ci/templates/ocs-deployment/multicluster/volume_replication_class.yaml
  ocs_ci/utility/utils.py
  setup.py
  tests/conftest.py
  tests/ecosystem/deployment/test_deployment.py
Labels: Verified, team/ecosystem, Code/Infra, size/XXL, DR

#5401 Add namespace resources creation with multi type test cases.
  tests/e2e/scale/noobaa/test_scale_namespace_crd.py
Labels: Verified, size/M, scale

#5402 Fix OCP version string while building the testrun name
  ocs_ci/utility/utils.py
Labels: bug, Verified, team/ecosystem, size/XS
