Repository red-hat-storage/ocs-ci, pull requests merged in 2023-03, with the labels that each got.

#7145 Fix test_nodereplacement_proactive by waiting for node deletion on AWS
  ocs_ci/ocs/node.py
Labels: Verified, size/S, Squad/Brown

#7176 do not fail MS destroy job for non-existing cluster
  ocs_ci/deployment/rosa.py
Labels: Verified, team/ecosystem, size/M

#7113 Update the test "test_rolling_terminate_and_recovery" for MS and non-MS clusters
  tests/manage/z_cluster/nodes/test_rolling_terminate_and_recovery.py
Labels: Verified, size/M, Squad/Brown, Managed Services

#7162 Increase timeout of "refresh pop-up"
  ocs_ci/ocs/ui/deployment_ui.py
Labels: size/XS

#7181 Removed log of ZombieProcess and NoSuchProcess exceptions
  ocs_ci/utility/memory.py
Labels: size/XS

#7203 rename vsphere upi lowerreq config
  conf/deployment/vsphere/upi_1az_rhcos_lowerreq_3m_3w.yaml
Labels: team/ecosystem, size/XS

#7205 rename vsphere upi lowerreq config - backport to release-4.12 branch
  conf/deployment/vsphere/upi_1az_rhcos_lowerreq_3m_3w.yaml
Labels: team/ecosystem, size/XS

#7206 rename vsphere upi lowerreq config - backport to release-4.11 branch
  conf/deployment/vsphere/upi_1az_rhcos_lowerreq_3m_3w.yaml
Labels: team/ecosystem, size/XS

#7207 rename vsphere upi lowerreq config - backport to release-4.10 branch
  conf/deployment/vsphere/upi_1az_rhcos_lowerreq_3m_3w.yaml
Labels: team/ecosystem, size/XS

#7209 rename vsphere upi lowerreq config - backport to release-4.9 branch
  conf/deployment/vsphere/upi_1az_rhcos_lowerreq_3m_3w.yaml
Labels: team/ecosystem, size/XS

#6595 Added testcases for cephfs and rbd metadata validation
  ocs_ci/utility/metadata_utils.py
  tests/conftest.py
  tests/manage/add_metadata_feature/test_metadata.py
  tests/manage/pv_services/test_rbd_image_metadata.py
Labels: Verified, size/XXL, Customer defects

#7227 Update 4.12 rhcos template
  ocs_ci/framework/conf/ocp_version/ocp-4.12-config.yaml
Labels: size/XS

#7146 BZ-2142763 Prometheus File
  ocs_ci/helpers/helpers.py
  tests/manage/monitoring/prometheus/test_prometheus_rules.py
Labels: team/e2e, size/M, Customer defects

#6925 Coverage for Bug 2128263
  ocs_ci/ocs/constants.py
  tests/e2e/workloads/ocp/registry/test_registry_by_increasing_num_of_image_registry_pods.py
Labels: team/e2e, size/M, Customer defects

#7174 Skip test_check_pod_status_after_two_nodes_shutdown_recovery for External mode
  tests/manage/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
Labels: Verified, size/XS

#7156 Skipping "test_check_mds_cache_memory_limit" for MCG only deployment
  tests/manage/z_cluster/test_ceph_default_values_check.py
Labels: size/XS, Squad/Brown

#7125 Ypersky multi clones used capacity enhancement
  ocs_ci/helpers/performance_lib.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/perftests.py
  tests/e2e/performance/csi_tests/test_pvc_multi_clone_performance.py
Labels: size/L, performance

#7158 UI deployment on ODF4.13
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/L

#7091 Fix `test_noobaa_kms` to look for the same record on all versions
  tests/manage/mcg/test_kms.py
Labels: size/M, MCG, Squad/Red

#7233 Add _get_bucket_name() method to query the bucket name
  ocs_ci/ocs/hsbench.py
Labels: size/M, MCG

#7178 Fix test_ceph_pg_log_dups_trim. Replace oc cp calls (Updated)
  ocs_ci/ocs/rados_utils.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: Verified, TestCase failing, size/M

#7241 Add Capacity via UI on ODF4.13
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/XS

#7236 test_ceph_capacity_recovery.py - adding retries for pulling perf image, adding skips for external and disconnected clusters
  ocs_ci/helpers/helpers.py
  tests/manage/pv_services/test_ceph_capacity_recovery.py
Labels: size/S

#7243 Add Sleep after Creating NS
  ocs_ci/deployment/baremetal.py
Labels: Verified, size/XS

#7166 Rename restart_nodes_teardown with restart_nodes_by_stop_and_start_teardown for BM
  ocs_ci/ocs/platform_nodes.py
Labels: Verified, size/XS, Squad/Brown

#7215 removed log of ZombieProcess and NoSuchProcess exceptions
  ocs_ci/utility/memory.py
Labels: size/XS

#7218 removed log of ZombieProcess and NoSuchProcess exceptions
  ocs_ci/utility/memory.py
Labels: size/XS

#7219 removed log of ZombieProcess and NoSuchProcess exceptions
  ocs_ci/utility/memory.py
Labels: size/XS

#7220 removed log of ZombieProcess and NoSuchProcess exceptions
  ocs_ci/utility/memory.py
Labels: size/XS

#7134 Try remove Object Bucket before OBC Test Case
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
  tests/manage/mcg/ui/test_mcg_ui.py
Labels: size/L, Customer defects

#7169 Longevity stage0 fix
  ocs_ci/ocs/longevity.py
  tests/e2e/longevity/test_stage0.py
Labels: Verified, team/e2e, size/S, Longevity

#7190 Skip test_resource_deletion_during_pvc_pod_deletion_and_io tests in external mode
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: size/S, Squad/Green

#7137 Increase wait time for pod to reach running state
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Labels: size/XS, Squad/Green

#7177 Increasing the timeout for checking PVC status of compact mode clusters
  ocs_ci/helpers/helpers.py
Labels: size/S, Squad/Brown

#7202 Fix tests to run on external mode
  tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py
  tests/manage/pv_services/pvc_snapshot/test_resource_deletion_during_snapshot_restore.py
Labels: Verified, size/XS, Squad/Green

#7268 Skip test for external mode (#7174)
  tests/manage/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
Labels: size/XS, Squad/Brown

#7269 Skip test for external mode (#7174)
  tests/manage/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
Labels: size/XS, Squad/Brown

#7272 Skip test for external mode (#7174)
  tests/manage/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
Labels: size/XS, Squad/Brown

#7265 Remove redundant use_shell from exec_cmd
  ocs_ci/ocs/rados_utils.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/utils.py
Labels: Verified, size/S

#7276 Fix test_nodereplacement_proactive by waiting for node deletion (#7145)
  ocs_ci/ocs/node.py
Labels: size/S, Squad/Brown

#7277 Fix test_nodereplacement_proactive by waiting for node deletion (#7145)
  ocs_ci/ocs/node.py
Labels: size/S, Squad/Brown

#7278 Fix test_nodereplacement_proactive by waiting for node deletion (#7145)
  ocs_ci/ocs/node.py
Labels: size/S, Squad/Brown

#6987 Get the actual replica size of pool in test
  tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Labels: Verified, size/XS, Squad/Green

#7284 test_obc_creation_and_deletion fix. cherry-pick 412
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
  tests/manage/mcg/ui/test_mcg_ui.py
Labels: Verified, size/L, ui_automation

#7285 Test_obc_creation_and_deletion fix. cherry-pick 411
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
  tests/manage/mcg/ui/test_mcg_ui.py
Labels: size/L, ui_automation

#7287 Test_obc_creation_and_deletion fix. cherry-pick 49
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
  tests/manage/mcg/ui/test_mcg_ui.py
Labels: size/L, ui_automation

#7288 Test_obc_creation_and_deletion fix. cherry-pick 48
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
  tests/manage/mcg/ui/test_mcg_ui.py
Labels: size/L, ui_automation

#7245 Fixing OBC bound list count mismatch (#7021)
  ocs_ci/ocs/scale_noobaa_lib.py
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_obc.py
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_rgw_obc.py
Labels: size/M, scale, MCG

#7244 Fixing OBC bound list count mismatch (#7021)
  ocs_ci/ocs/scale_noobaa_lib.py
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_obc.py
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_rgw_obc.py
Labels: size/M, MCG

#7326 Fixing OBC bound list count mismatch (#7021)
  ocs_ci/ocs/scale_noobaa_lib.py
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_obc.py
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_rgw_obc.py
Labels: size/M, scale, MCG

#7251 Modify `Backingstore.py::delete` so it raises deletion errors if retrying is disabled
  ocs_ci/ocs/resources/backingstore.py
Labels: size/S, MCG, Squad/Red

#7185 Fix the use of TimeoutExpiredError in `bucket_utils.py::wait_for_pv_backingstore`
  ocs_ci/ocs/bucket_utils.py
Labels: size/XS, MCG, Squad/Red

#7327 Temporarily disable all format generation for readthedocs
  .readthedocs.yml
Labels: team/ecosystem, size/XS

#7333 Temporarily disable all format generation for readthedocs
  .readthedocs.yml
Labels: team/ecosystem, size/XS

#7332 Temporarily disable all format generation for readthedocs
  .readthedocs.yml
Labels: team/ecosystem, size/XS

#7334 Temporarily disable all format generation for readthedocs
  .readthedocs.yml
Labels: team/ecosystem, size/XS

#7335 Temporarily disable all format generation for readthedocs
  .readthedocs.yml
Labels: team/ecosystem, size/XS

#7037 Switch to the correct cluster index at setup
  ocs_ci/framework/__init__.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/managedservice.py
  ocs_ci/utility/utils.py
  tests/managed-service/test_switch_to_correct_index_at_setup.py
Labels: Verified, size/L, Managed Services

#6589 Implement MCG load balancer incoming subnet rules test
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/cloud_manager.py
  tests/conftest.py
  tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
  tests/manage/mcg/test_loadbalancer_subnet_config.py
  tests/manage/mcg/test_namespace_crd.py
Labels: size/L, MCG

#7341 In the function 'wait_for_ct_pod_recovery' catch the 'AssertionError' if the rook-ceph-tool pod is not ready yet
  ocs_ci/helpers/helpers.py
Labels: Verified, size/S, Squad/Brown

#7348 Add RHEL 8.7 pod template
  ocs_ci/templates/app-pods/rhel-8_7.yaml
Labels: team/ecosystem

#7261 Update the `NOOBAA_DB_SERVICE_ACCOUNT_NAME` constant for `test_db_scc `
  ocs_ci/ocs/constants.py
  tests/manage/mcg/test_mcg_resources_disruptions.py
Labels: size/S, MCG, Squad/Red

#7040 remove unused variable selector
  ocs_ci/ocs/resources/packagemanifest.py
Labels: team/ecosystem, size/XS

#7102 Fail the run if BM cluster has lock
  ocs_ci/deployment/baremetal.py
Labels: team/ecosystem, size/XS

#6843 Tests to check upgrade of OCS when we set without expansion secre…
  ocs_ci/helpers/helpers.py
  tests/conftest.py
  tests/ecosystem/upgrade/test_upgrade_sc_allowexpansion_false.py
Labels: team/e2e, size/L, Customer defects

#7354 fix pg_dump command for nbcore
  ocs_ci/ocs/utils.py
Labels: size/XS

#7226 Automate KCS (https://access.redhat.com/solutions/6686081) and Bug 2141035
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/warp.py
  ocs_ci/templates/workloads/warp/warp_service.yaml
  tests/e2e/conftest.py
  tests/e2e/kcs/test_noobaa_db_backup_and_recovery.py
Labels: Verified, team/e2e, size/L, MCG, Customer defects

#7356 fix pg_dump command for nbcore
  ocs_ci/ocs/utils.py
Labels: size/XS

#7371 Change Azure resource group name to odfqe
  conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
  conf/deployment/azure/ipi_3az_rhcos_3m_3w.yaml
Labels: team/ecosystem, size/XS

#7370 Fix bm fail issue
  ocs_ci/deployment/baremetal.py
Labels: Verified, size/XS

#7092 add avoid_stale to do_click
  ocs_ci/ocs/ui/add_replace_device_ui.py
  ocs_ci/ocs/ui/base_ui.py
Labels: TestCase failing, size/M, ui_automation

#7374 Update rosa version to 1.2.15
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/XS, Managed Services

#7355 fix pg_dump command for nbcore
  ocs_ci/ocs/utils.py
Labels: size/XS

#7349 fix pg_dump command for nbcore
  ocs_ci/ocs/utils.py
Labels: size/XS

#7238 Test pvc multi snapshot performance - increasing timeout for pod deletion
  tests/e2e/performance/csi_tests/test_pvc_multi_snapshot_performance.py
Labels: Verified, size/M, performance

#7378 use new version of ocp-network-split - v0.3.0
  requirements.txt
Labels: Verified, team/ecosystem, size/XS

#7388 Improve Disk Cleanup for Bare Metal
  ocs_ci/deployment/baremetal.py
Labels: size/L

#7386 Tc try remove object bucket 4.13
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
  tests/manage/mcg/ui/test_mcg_ui.py
Labels: Test Case, Verified, size/M, ui_automation

#7317 Tc try remove object bucket UI 412
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
  tests/manage/mcg/ui/test_mcg_ui.py
Labels: Test Case, Verified, size/L, Customer defects, ui_automation

#7318 Tc try remove object bucket UI 411
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/L

#7319 Tc try remove object bucket UI 410
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/L

#7394 Change Azure resource group name to odfqe
  conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
  conf/deployment/azure/ipi_3az_rhcos_3m_3w.yaml
Labels: size/XS, cherry-pick

#7395 Change Azure resource group name to odfqe
  conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
  conf/deployment/azure/ipi_3az_rhcos_3m_3w.yaml
Labels: size/XS, cherry-pick

#7396 Change Azure resource group name to odfqe
  conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
  conf/deployment/azure/ipi_3az_rhcos_3m_3w.yaml
Labels: size/XS, cherry-pick

#7320 Tc try remove object bucket UI 49
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/L

#7398 Change azure resource group release 4.8
  conf/deployment/azure/ipi_1az_rhcos_3m_3w.yaml
  conf/deployment/azure/ipi_3az_rhcos_3m_3w.yaml
Labels: team/ecosystem, size/XS, cherry-pick

#7399 Change worker instance type for all IBM Cloud deployments to bx2-16x64
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_hpcs_external.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_stage.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos_stage.yaml
  conf/deployment/ibmcloud/ipi_3az_rhcos_3m_3w.yaml
  ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
Labels: Verified, team/ecosystem, size/S

#7406 Change worker instance type for all IBM Cloud deployments to bx2-16x64
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_hpcs_external.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_stage.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos_stage.yaml
  conf/deployment/ibmcloud/ipi_3az_rhcos_3m_3w.yaml
  ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
Labels: team/ecosystem, size/S, cherry-pick

#7407 Change worker instance type for all IBM Cloud deployments to bx2-16x64
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_hpcs_external.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_stage.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos_stage.yaml
  conf/deployment/ibmcloud/ipi_3az_rhcos_3m_3w.yaml
  ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
Labels: team/ecosystem, size/S, cherry-pick

#7408 Change worker instance type for all IBM Cloud deployments to bx2-16x64
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_hpcs_external.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_stage.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos_stage.yaml
  conf/deployment/ibmcloud/ipi_3az_rhcos_3m_3w.yaml
  ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
Labels: team/ecosystem, size/S, cherry-pick

#7409 Change worker instance type for all IBM Cloud deployments to bx2-16x64
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_hpcs_external.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_stage.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos_stage.yaml
  conf/deployment/ibmcloud/ipi_3az_rhcos_3m_3w.yaml
  ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
Labels: team/ecosystem, size/S, cherry-pick

#7410 Change worker instance type for all IBM Cloud deployments to bx2-16x64
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_hpcs_external.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_stage.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos_stage.yaml
  conf/deployment/ibmcloud/ipi_3az_rhcos_3m_3w.yaml
  ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
Labels: team/ecosystem, size/S, cherry-pick
