Repository red-hat-storage/ocs-ci, pull requests merged in 2023-10, with the labels that each got.

#8571 fixed minor logic issue
  ocs_ci/ocs/ui/odf_topology.py
Labels: Verified, TestCase failing, size/XS, ui_automation, lgtm, Squad/Black

#8550 storageclass changed if external mode [4.11]
  ocs_ci/ocs/constants.py
  tests/manage/mcg/ui/test_mcg_ui.py
Labels: Verified, TestCase failing, size/XS, ui_automation, lgtm, Squad/Black

#8360 namespace-selection-fix
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/page_objects/page_navigator.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/L, ui_automation, lgtm, Squad/Black

#8272 Add test_kms_unavailable
  ocs_ci/ocs/constants.py
  ocs_ci/utility/kms.py
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/prometheus/test_encryption.py
Labels: Verified, size/L, Squad/Blue, lgtm

#8565 fix function call args test_obc_creation_deletion fails
  ocs_ci/ocs/ui/page_objects/resource_list.py
Labels: Verified, TestCase failing, size/S, ui_automation, lgtm, Squad/Black

#8610 Set OCP 4.15 as a default for ODF 4.15 and upstream builds
  ocs_ci/framework/conf/ocs_version/ocs-4.15.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.99.yaml
Labels: team/ecosystem, size/XS, lgtm

#8612 Increase timeout for nodes ready check in test_check_pods_status_after_node_failure
  tests/manage/z_cluster/nodes/test_check_pods_status_after_node_failure.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#8349 BZ 2139037 Coverage - `test_rgw_routes`
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/rgw.py
  tests/manage/rgw/test_rgw_routes.py
Labels: Verified, size/L, Customer defects, RGW, Squad/Red, lgtm

#8313 Compare AWS regions and Noobaa regions list
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/views.py
  tests/manage/mcg/ui/test_verify_region_list.py
Labels: Verified, team/e2e, size/L, MCG, Customer defects, Squad/Red, lgtm

#8620 delete template folder for vsphere IPI in vSphere cleanup
  ocs_ci/cleanup/vsphere/cleanup.py
Labels: Needs Testing, size/M, lgtm

#8607 test_dashboard_validation_ui-adjust-locator-4.14
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/M, ui_automation, lgtm, Squad/Black

#8616 Extend timeout for waiting for machineconfigpoool
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#8544 Measure operation thread safe 4.11
  ocs_ci/utility/prometheus.py
  ocs_ci/utility/workloadfixture.py
  tests/manage/monitoring/conftest.py
Labels: Verified, size/L, Squad/Blue, lgtm, cherry-pick

#8543 Measure operation thread safe 4.12
  ocs_ci/utility/prometheus.py
  ocs_ci/utility/workloadfixture.py
  tests/manage/monitoring/conftest.py
Labels: Verified, size/L, Squad/Blue, lgtm, cherry-pick

#8542 Measure operation thread safe 4.13
  ocs_ci/utility/prometheus.py
  ocs_ci/utility/workloadfixture.py
  tests/manage/monitoring/conftest.py
Labels: Verified, size/L, Squad/Blue, lgtm, cherry-pick

#8628 Skip the test case test_mon_failures_with_intransit_encryption due to the ocs-ci issue 8464
  tests/encryption/test_mon_failure_in_intransit_encryption.py
Labels: Verified, size/XS, Squad/Green, lgtm

#8618 Move deployment test case to new location
  tests/functional/deployment/__init__.py
  tests/functional/deployment/test_deployment.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#8538 Revert back to default fio timeout value in get_fio_rw_iops() - backport for 4.13
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/XS, lgtm, cherry-pick

#8219 [Closed Loop][GSS]Automation of GSS BZ-2176354
  tests/manage/pv_services/test_write_to_cephfs_pvc_with_nonroot_user.py
Labels: Verified, team/e2e, size/L, Customer defects, lgtm

#8634 Fix: Scale ceph pod respin test while loop is not exited
  tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Labels: bug, size/M, scale, lgtm

#8650 Cherry Pick PR-8634 for release 4.12
  tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Labels: Verified, size/M, scale, lgtm, cherry-pick

#8652 add bz mark for failing test
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
Labels: bug, Verified, size/XS, lgtm

#8625 extend finalizer to fix teardown issue
  tests/ui/test_odf_topology.py
Labels: Verified, TestCase failing, size/M, lgtm, Squad/Black

#8622 remove OCP title validation on login
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/S, lgtm, Squad/Black

#8545 Measure operation thread safe 4.10
  ocs_ci/utility/prometheus.py
  ocs_ci/utility/workloadfixture.py
  tests/manage/monitoring/conftest.py
Labels: Verified, size/L, Squad/Blue, lgtm, cherry-pick

#8536 create store tests adapted to 4.14
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/page_objects/backing_store_tab.py
  ocs_ci/ocs/ui/page_objects/bucket_class_tab.py
  ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
  ocs_ci/ocs/ui/page_objects/namespace_store_tab.py
  ocs_ci/ocs/ui/page_objects/object_bucket_claims_tab.py
  ocs_ci/ocs/ui/page_objects/object_buckets_tab.py
  ocs_ci/ocs/ui/page_objects/object_storage.py
  ocs_ci/ocs/ui/page_objects/page_navigator.py
  ocs_ci/ocs/ui/page_objects/resource_list.py
  ocs_ci/ocs/ui/page_objects/resource_page.py
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/ui/views.py
  tests/manage/mcg/ui/test_mcg_ui.py
Labels: Verified, size/L, ui_automation, lgtm, Squad/Black

#8651 Cherry Pick PR 8634 to 4.13 release branch
  tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Labels: Verified, size/M, scale, lgtm, cherry-pick

#8632 get volume path in vsphere using volumeHandle from PV
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/osd_operations.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/vsphere.py
Labels: Verified, team/ecosystem, size/M, lgtm

#8657 A fixing to performance lib for correct calculation of pvc/clone deletion time in 4.14
  ocs_ci/helpers/performance_lib.py
  tests/e2e/performance/csi_tests/test_pvc_bulk_clone_performance.py
Labels: size/S, lgtm

#8357 In the test "test_add_capacity_node_restart" restart the nodes without waiting for the Reboot event when using vSphere IPI 4.12 #8076
  ocs_ci/ocs/cluster.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
Labels: Verified, size/S, Squad/Brown, lgtm

#8654 change ceph debug_mon to 30
  ocs_ci/ocs/constants.py
Labels: team/ecosystem, size/XS, lgtm

#8660 Fix error with invalid XML character which breaks XML with report
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, lgtm, cherry-pick

#8452 Refactor `nsfs_bucket_factory_fixture` and fix various NSFS issues
  ocs_ci/ocs/resources/mcg_params.py
  ocs_ci/ocs/resources/objectbucket.py
  ocs_ci/ocs/resources/pod.py
  tests/conftest.py
  tests/manage/mcg/test_nsfs.py
Labels: High Priority, Verified, size/L, MCG, Squad/Red, lgtm

#8608 `s3cli-sts.yaml`: Use the new, actually multi-arch 3.0 tag
  ocs_ci/templates/mcg/s3cli-sts.yaml
Labels: High Priority, Verified, size/XS, MCG, Squad/Red, lgtm

#8664 Increasing timeouts for bulk pod attach and bulk clone creation
  tests/e2e/performance/csi_tests/test_pvc_bulk_clone_performance.py
Labels: size/XS, performance, lgtm

#8385 Adding hook to create a timing report for the tests run
  ocs_ci/framework/__init__.py
  ocs_ci/framework/pytest_customization/reports.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/html_reports/test_time_table.html.j2
  ocs_ci/utility/utils.py
Labels: Verified, size/L, lgtm

#8665 dump configuration to file at the end of the execution
  ocs_ci/framework/pytest_customization/reports.py
  ocs_ci/utility/tests/test_utils.py
  ocs_ci/utility/utils.py
  tests/test_failure_propagator.py
Labels: Verified, team/ecosystem, size/L, lgtm

#8680 Fix skipif_ui_not_support function for IBM cloud IPI
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/XS, lgtm

#8599 Adds "skipif_mcg_only" decorator to the tests which are using ceph resources for mcg_only deployment
  tests/manage/rgw/test_bucket_creation.py
  tests/manage/rgw/test_bucket_deletion.py
  tests/manage/rgw/test_multipart_upload.py
  tests/manage/rgw/test_obc_quota.py
  tests/manage/rgw/test_object_bucket_size.py
  tests/manage/rgw/test_object_integrity.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm

#8261 [release-4.12 backport] Mirror ubi8 in disconnected environments for `test_nsfs.py`
  tests/conftest.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm, cherry-pick

#8263 [release-4.12 backport] test_noobaa_kms_validation: Remove the use of RE and generalize the search based on environment config
  tests/manage/mcg/test_kms.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm, cherry-pick

#8656 Skipping RGW type storageclass for AWS deployment
  tests/manage/storageclass/test_custom_storageclass_names.py
Labels: Verified, size/M, lgtm

#8685 In the test "test_automated_recovery_from_failed_nodes_reactive_ms" fix calling the function "verify_osd_distribution_on_provider"
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_ms.py
Labels: Verified, size/XS, Managed Services, lgtm

#8646 When getting the rook-ceph-tool pod use the provider kubeconfig parameter if exist in the run
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/XS, Managed Services, lgtm

#8380 Update the test "test_simultaneous_drain_of_two_ocs_nodes" when we have 1az and 3 racks 4.12 #7987
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/L, Squad/Brown, lgtm

#8692 Implement additional force destroy functionality for IBM Cloud
  conf/README.md
  conf/ocsci/skip_ocp_destroy.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/ibmcloud.py
  ocs_ci/ocs/exceptions.py
Labels: Verified, team/ecosystem, size/L, lgtm

#8094 Updated metadata validation testcases to fix issue#7459
  ocs_ci/utility/metadata_utils.py
  tests/manage/add_metadata_feature/test_metadata.py
Labels: Verified, size/M, Squad/Green, lgtm

#8688 fix test_failure_propagator
  conf/README.md
  ocs_ci/framework/conf/default_config.yaml
  tests/test_failure_propagator.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#8689 fix test_failure_propagator - backport for 4.13
  conf/README.md
  ocs_ci/framework/conf/default_config.yaml
  tests/test_failure_propagator.py
Labels: Verified, team/ecosystem, size/XS, lgtm, cherry-pick

#8700 Move removal of PVCs back after the opnshift-install destroy command
  ocs_ci/deployment/ibmcloud.py
Labels: team/ecosystem, size/S, lgtm

#8146 [release-4.13 backport] `test_noobaa_kms_validation`: Remove the use of RE and generalize the search based on environment config
  tests/manage/mcg/test_kms.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm, MCG-4.13, cherry-pick

#8670 Check both incidents CephOSDDisdUnavailable and CephOSDDiskNotResponding in test_ceph_osd_stopped_pd
  ocs_ci/utility/pagerduty.py
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/pagerduty/test_ceph.py
  tests/manage/monitoring/pagerduty/test_deployment_status.py
Labels: Verified, size/M, Squad/Blue, Managed Services, lgtm

#8677 [release-4.13] get volume path in vsphere using volumeHandle from PV
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/osd_operations.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/vsphere.py
Labels: Verified, size/M, lgtm, cherry-pick

#8604 storage device check after add capacity
  ocs_ci/utility/utils.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Labels: Needs Testing, team/ecosystem, size/M, lgtm

#8693 In the "snapshot_restore_factory_fixture" get the correct storageclass(rbd or cephfs) when using MS consumer cluster
  tests/conftest.py
Labels: Verified, size/XS, Managed Services, lgtm

#8701 Delete PVCs for IBM Cloud deployment
  ocs_ci/deployment/ibmcloud.py
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/resources/pvc.py
Labels: size/L, lgtm

#8704 fix add_time_report_to_email keyError issue
  ocs_ci/framework/pytest_customization/reports.py
  ocs_ci/utility/utils.py
Labels: Verified, size/XS, lgtm

#8553 thread_lock added to all PrometheusAPI calls
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/cluster_load.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/fiojob.py
  ocs_ci/ocs/monitoring.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/utils.py
  ocs_ci/utility/prometheus.py
  ocs_ci/utility/utils.py
  ocs_ci/utility/workloadfixture.py
  tests/conftest.py
  tests/e2e/system_test/test_cluster_full_and_recovery.py
  tests/e2e/workloads/ocp/monitoring/test_monitoring_on_negative_scenarios.py
  tests/e2e/workloads/ocp/registry/test_registry_by_increasing_num_of_image_registry_pods.py
  tests/lvmo/test_lvm_alerts.py
  tests/lvmo/test_lvm_clone_base.py
  tests/lvmo/test_lvm_clone_bigger_than_disk.py
  tests/lvmo/test_lvm_multi_clone.py
  tests/lvmo/test_lvm_multi_snapshot.py
  tests/lvmo/test_lvm_snapshot_base.py
  tests/lvmo/test_lvm_snapshot_bigger_than_disk.py
  tests/lvmo/test_lvmo_pvc_resize.py
  tests/manage/mcg/test_noobaa_prometheus.py
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/prometheus/test_alerting_works.py
  tests/manage/monitoring/prometheus/test_capacity.py
  tests/manage/monitoring/prometheus/test_ceph.py
  tests/manage/monitoring/prometheus/test_deployment_status.py
  tests/manage/monitoring/prometheus/test_hpa.py
  tests/manage/monitoring/prometheus/test_noobaa.py
  tests/manage/monitoring/prometheus/test_rgw.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
  tests/manage/monitoring/prometheusmetrics/test_ocs_utilization.py
  tests/manage/monitoring/prometheusmetrics/test_rgw.py
  tests/manage/monitoring/test_workload_fixture.py
  tests/manage/monitoring/test_workload_with_distruptions.py
  tests/manage/pv_services/pvc_clone/test_clone_when_pvc_full.py
  tests/manage/pv_services/pvc_resize/test_pvc_expansion_when_full.py
Labels: Verified, size/L, Squad/Blue, lgtm

#8691 [release-4.12 backport] `test_public_website`: Use `s3_get_object` with `retry`
  tests/manage/mcg/test_bucket_policy.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm, MCG-4.12, cherry-pick

#8690 [release-4.13 backport] `test_public_website`: Use `s3_get_object` with `retry`
  tests/manage/mcg/test_bucket_policy.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm, MCG-4.13, cherry-pick

#8426 [release-4.12 backport] Adjust `namespace_bucket_update` to the new schema
  ocs_ci/ocs/bucket_utils.py
  tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
Labels: Verified, size/M, MCG, lgtm, cherry-pick

#8712 Change gcp project ID
  conf/deployment/gcp/ipi_1az_rhcos_3m_3w.yaml
Labels: Verified, team/ecosystem, size/XS, lgtm

#8655 Review fix - test_ceph_osd_slow_ops_alert 4.13
  ocs_ci/ocs/cluster.py
  tests/conftest.py
  tests/manage/monitoring/test_workload_with_distruptions.py
Labels: size/M, Squad/Blue, lgtm, cherry-pick

#8339 cherry-pick test_reclaim_space_cronjob_with_annotation 4.10
  ocs_ci/ocs/cluster.py
  tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py
Labels: Verified, size/L, Squad/Green, lgtm, cherry-pick

#8338 cherry-pick test_reclaim_space_cronjob_with_annotation 4.11
  ocs_ci/ocs/cluster.py
  tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py
Labels: Verified, size/L, lgtm, cherry-pick

#8336 cherry-pick test_reclaim_space_cronjob_with_annotation 4.13
  tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py
Labels: Verified, size/L, lgtm, cherry-pick

#8337 cherry-pick test_reclaim_space_cronjob_with_annotation 4.12
  ocs_ci/ocs/cluster.py
  tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py
Labels: Verified, size/L, Squad/Green, Squad/Blue, lgtm, cherry-pick

#8578 Design and implement MCG background features entry criteria setup
  ocs_ci/helpers/e2e_helpers.py
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
  tests/conftest.py
  tests/e2e/conftest.py
  tests/e2e/system_test/test_mcg_recovery.py
Labels: Verified, team/e2e, size/XXL, MCG, Squad/Red, lgtm

#8633 Test case OCS-4761
  tests/disaster-recovery/regional-dr/test_failover_and_relocate.py
Labels: Test Case, Verified, size/L, lgtm, DR

#8711 Wait for node deletion and verify original node count during teardown of test_automated_recovery_from_stopped_node_and_start[True]
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: High Priority, Verified, size/S, Squad/Brown, lgtm

#8708 Adding FileNotFoundError exception
  ocs_ci/framework/pytest_customization/reports.py
Labels: size/XS, lgtm

#8358 In the test "test_add_capacity_node_restart" restart the nodes without waiting for the Reboot event when using vSphere IPI 4.11 #8076
  ocs_ci/ocs/cluster.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
Labels: Verified, size/S, Squad/Brown, lgtm

#8268 Replace FIO image for cluster load
  ocs_ci/templates/workloads/fio/fedora_deployment.yaml
Labels: Verified, size/XS, lgtm

#8729 Differentiate between platforms in measure_operation and add threading_lock where missing
  tests/manage/monitoring/conftest.py
Labels: size/M, Squad/Blue, lgtm

#8719 Remove the try and except from the function "get_mds_cache_memory_limit" and move it to the test "test_check_mds_cache_memory_limit"
  ocs_ci/ocs/cluster.py
  tests/manage/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/S, Squad/Brown, lgtm

#8673 test_pvc_snapshot_performance.py fix - increasing get_fio_results timeout
  tests/e2e/performance/csi_tests/test_pvc_snapshot_performance.py
Labels: Verified, size/XS, performance, lgtm

#8743 update cryptography to latest version
  setup.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#8739 Change test ownership back to magenta squad
  tests/e2e/workloads/ocp/monitoring/test_monitoring_on_negative_scenarios.py
Labels: size/XS, Squad/Magenta, lgtm

#8749 [release-4.12] update cryptography to latest version
  setup.py
Labels: team/ecosystem, size/XS, lgtm

#8750 [release-4.11] Update cryptography release 411
  setup.py
Labels: team/ecosystem, size/XS, lgtm

#8738 ci: fix mgr pdb resource count
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/version.py
Labels: size/S, lgtm

#8746 pin versions for python packages
  setup.py
Labels: Verified, team/ecosystem, size/S, lgtm

#8755 Add RHEL repo for OCP 4.15
  ocs_ci/repos/ocp_4_15_rhel8.repo
Labels: Needs Deployment Testing, team/ecosystem, size/M, lgtm

#8591 Fix test_noobaa_db_backup_recovery_locally on KMS enabled cluster
  tests/e2e/conftest.py
Labels: Verified, team/e2e, size/XS, Squad/Magenta, lgtm

#8760 Skipping some tests due to issue https://github.com/red-hat-storage/o…
  tests/encryption/test_intransit_encryption_sanity.py
  tests/manage/add_metadata_feature/test_metadata.py
Labels: size/XS, lgtm

#8442 Change the method 'is_node_rack_or_zone_exist' to get the node name instead of the node object 4.11 #8344
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
Labels: Verified, size/L, Squad/Brown, lgtm

#8526 Add coverage for Bz 2210289
  tests/manage/mcg/test_bucket_policy.py
Labels: team/e2e, size/M, Customer defects, lgtm

#8771 set mgr count for 4.15 upgrades and deployment
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/S, lgtm

#8710 fix rounding issue in reports
  ocs_ci/framework/pytest_customization/reports.py
Labels: Verified, team/ecosystem, size/S, lgtm
