Repository red-hat-storage/ocs-ci, pull requests merged in 2023-07, with the labels that each got.

#7879 Enhance the ignore_leftover_label to support labels other than app for release-4.10 (#7710)
  ocs_ci/ocs/constants.py
  ocs_ci/utility/environment_check.py
  tests/libtest/test_skip_labeled_leftover.py
  tests/managed-service/test_pod_disruptions.py
Labels: enhancement, Verified, size/M, Squad/Brown

#7806 In the test "test_delete_rook_ceph_osd_deployment" ignore the "rook-ceph-osd" labels in the leftovers #7790
  tests/manage/z_cluster/test_delete_osd_deployment.py
Labels: Verified, size/XS, Squad/Brown

#7666 Adding try except block in function "wait_for_nodes_status" to ignore "CommandFailed" exception release-4.10 (#7451)
  ocs_ci/ocs/node.py
Labels: size/S, Squad/Brown

#7925 Release 4.10 cherry pick pr 7466
  tests/manage/pv_services/test_overprovision_level_policy_control.py
Labels: size/XS

#7893 Skip mcg tests in FaaS test runs
  tests/manage/mcg/conftest.py
Labels: Verified, Managed Services

#7871 locators 4.14 provided
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
Labels: size/M, ui_automation, Squad/Black

#7943 ODF4.14,Add Must-agther test
  ocs_ci/ocs/must_gather/const_must_gather.py
Labels: Verified, team/ecosystem, size/S

#7951 disconnected packages for ODF 4.14 deployment
  ocs_ci/ocs/constants.py
Labels: team/ecosystem

#7952 Use latest image tag for ACM unreleased Install (#7918) Backport 4-13
  conf/ocsci/acm_2.7.yaml
  conf/ocsci/acm_2.8.yaml
  conf/ocsci/acm_2.9.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.12-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.13-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.13-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.13-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.14-config.yaml
  ocs_ci/utility/utils.py
Labels: size/M

#7955 Use latest image tag for ACM unreleased Install Backport 4-12
  conf/ocsci/acm_2.7.yaml
  conf/ocsci/acm_2.8.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.12-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.13-config.yaml
  ocs_ci/utility/utils.py
Labels: size/M

#7936 delete PVC's before teardown
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/M

#7950 Release 4.12 cherry pick pr 6687
  ocs_ci/ocs/constants.py
  ocs_ci/utility/nfs_utils.py
  tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Labels: Verified, Squad/Brown

#7874 Increasing 'wait_for_pods_to_be_running' timeout to address intermittent failures in test_toleration.py
  tests/manage/z_cluster/nodes/test_toleration.py
Labels: Verified, size/XS, Squad/Brown

#7661 Updated nfs tests to fix failures (#6687)
  ocs_ci/ocs/constants.py
  ocs_ci/utility/nfs_utils.py
  tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Labels: Verified, size/L, Squad/Brown

#6646 Test to validate storage cluster status on UI
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/ui/views.py
  tests/ui/test_validation_ui.py
Labels: Verified, size/L, ui_automation

#7935 Added new test to check the number of storage class in UI
  ocs_ci/ocs/ui/block_pool.py
  ocs_ci/ocs/ui/views.py
  tests/ui/test_creation_and_deletion_of_sc_and_rbdpool.py
Labels: size/M

#7966 change instance type for disconnected deployments
  conf/deployment/aws/ipi_1az_rhcos_lso_sno.yaml
  conf/deployment/aws/upi_1az_rhcos_3m_3w_disconnected.yaml
  conf/deployment/aws/upi_1az_rhcos_3m_3w_proxy.yaml
  conf/deployment/aws/upi_1az_rhcos_lso_3m_3w_disconnected.yaml
  conf/deployment/aws/upi_3az_rhcos_3m_3w_disconnected.yaml
  conf/deployment/aws/upi_3az_rhcos_3m_3w_proxy.yaml
  conf/deployment/aws/upi_3az_rhcos_lso_3m_3w_disconnected.yaml
Labels: Verified, team/ecosystem, size/S

#7946 Use the function "get_ceph_tools_pod" in the utility "ceph_health_check_base" to make it more generic
  ocs_ci/ocs/managedservice.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/utils.py
Labels: enhancement, Verified, size/L, Managed Services

#7976 Fix multicluster_mode flag in multicluster_mode_mdr.yaml
  conf/ocsci/multicluster_mode_mdr.yaml
  ocs_ci/helpers/dr_helpers.py
  tests/conftest.py
Labels: size/S, cherry-pick

#7533 Test if pv pool BS pod node ephemeral storage getting consumed
  tests/manage/mcg/test_pv_pool.py
Labels: team/e2e, size/M, MCG, Customer defects

#7924 Add squad for disaster recovery
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem

#7963 Create klusterlet addons on managed clusters
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/acm-deployment/klusterlet-addon-config.yaml
Labels: Verified, size/M, DR

#7985 correct doc string for fusion deployment
  ocs_ci/deployment/fusion.py
Labels: team/ecosystem, size/XS

#7970 verify storage cluster version
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/S

#7983 [4.13]: Remove pvc before teardown
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/M, cherry-pick

#7989 disable storage cluster version check
  ocs_ci/ocs/resources/storage_cluster.py
Labels: team/ecosystem, size/S

#7942 ODF4.14 Add capacity via UI
  ocs_ci/ocs/ui/helpers_ui.py
Labels: Verified, size/S

#7979 Test KCS: Disabling Multicloud Object Gateway external service and make sure disableLoadBalancerService isn't reconciled
  tests/e2e/kcs/test_disable_mcg_external_service.py
Labels: Verified, team/e2e, size/M, Customer defects, Squad/Red

#7973 test noobaa_bucket_used_bytes prometheus metrics
  ocs_ci/ocs/exceptions.py
  tests/manage/mcg/test_noobaa_prometheus.py
Labels: Verified, team/e2e, size/M, MCG, Customer defects, Squad/Red

#7937 Cherry pick 412 test_quickstart_presence
  ocs_ci/ocs/ui/base_ui.py
  tests/ui/test_quickstarts.py
Labels: size/S

#7938 Cherry pick 411 test_quickstart_presence
  ocs_ci/ocs/ui/base_ui.py
  tests/ui/test_quickstarts.py
Labels: size/S

#7940 Cherry pick 410 test_quickstart_presence-a
  ocs_ci/ocs/ui/base_ui.py
  tests/ui/test_quickstarts.py
Labels: size/S

#7956 Refactor UI modules
  ocs_ci/ocs/ui/add_replace_device_ui.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/block_pool.py
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/page_objects/backing_store_tab.py
  ocs_ci/ocs/ui/page_objects/block_pools.py
  ocs_ci/ocs/ui/page_objects/bucket_class_tab.py
  ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
  ocs_ci/ocs/ui/page_objects/namespace_store_tab.py
  ocs_ci/ocs/ui/page_objects/object_bucket_claim.py
  ocs_ci/ocs/ui/page_objects/odf_topology_tab.py
  ocs_ci/ocs/ui/page_objects/overview_tab.py
  ocs_ci/ocs/ui/page_objects/page_navigator.py
  ocs_ci/ocs/ui/page_objects/storage_system_details.py
  ocs_ci/ocs/ui/page_objects/storage_system_tab.py
  ocs_ci/ocs/ui/pvc_ui.py
  ocs_ci/ocs/ui/storageclass.py
  ocs_ci/ocs/ui/validation_ui.py
  tests/manage/mcg/ui/test_mcg_ui.py
  tests/ui/test_error_improvements.py
  tests/ui/test_non_admin_user.py
  tests/ui/test_odf_topology.py
  tests/ui/test_quickstarts.py
Labels: Verified, size/XXL, ui_automation, Squad/Black

#7930 revert the workaround of noobaa endpoint count
  tests/conftest.py
Labels: Verified, team/ecosystem, size/XS

#7889 Skip UI tests in FaaS test runs
  tests/conftest.py
Labels: Verified, size/XS, Managed Services

#7887 Add runs_on_provider marker in MS tests
  tests/managed-service/test_post_installation_state.py
Labels: Verified, size/XS, Managed Services

#7926 Automating GSS BZ https://bugzilla.redhat.com/show_bug.cgi?id=2179271
  tests/manage/mcg/test_bucket_creation.py
Labels: Verified, team/e2e, size/M, Customer defects

#7958 Cherry pick PR-7899: Refractor get_credentials method to fetch endpoint details from cephobjectstore for external cluster
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/rgw.py
Labels: size/S, Squad/Red, cherry-pick

#7959 Cherry pick PR-7899: Refractor get_credentials method to fetch endpoint details from cephobjectstore for external cluster
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/rgw.py
Labels: size/S, Squad/Red, cherry-pick

#8000 In the test "test_osd_node_restart_and_check_osd_pods_status" increase timeout of waiting for the osd node
  tests/manage/z_cluster/nodes/test_nodes_restart_ms.py
Labels: Verified, size/XS, Squad/Brown, Managed Services

#7967 Added multi_client=False to the run_benchmark function of warp
  ocs_ci/ocs/warp.py
  tests/e2e/scale/noobaa/test_warp.py
Labels: size/S, scale, Squad/Orange

#7847 PR to remove memory leak function
  tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
  tests/e2e/scale/test_pv_scale_ocs_create_delete_pvcs.py
Labels: Verified, size/M, scale

#7980 adding squad for allowexpansion test case
  tests/ecosystem/upgrade/test_upgrade_sc_allowexpansion_false.py
Labels: team/ecosystem, size/XS

#7992 Fix attribute error for RDRMultiClusterDROperatorsDeploy class
  ocs_ci/deployment/deployment.py
Labels: Verified, size/XS, DR

#7872 Ignore the noobaa-endpoint pods leftovers at `test_nsfs.py`
  tests/manage/mcg/test_nsfs.py
Labels: size/XS, MCG, Squad/Red

#7660 `test_noobaa_kms_validation`: Remove the use of RE and generalize the search based on environment config
  tests/manage/mcg/test_kms.py
Labels: size/S, MCG, Squad/Red

#7767 Fixed issue of test_scale_obc_create_delete_time
  ocs_ci/ocs/scale_noobaa_lib.py
  tests/e2e/scale/noobaa/test_scale_obc_create_delete.py
Labels: bug, Verified, size/XS, scale, MCG

#8006 Get noobaa CLI from the image provided by build team or the released …
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/mcg.py
Labels: team/ecosystem, size/L, cherry-pick

#8007 Get noobaa CLI from the image provided by build team or the released …
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/mcg.py
Labels: team/ecosystem, size/L, cherry-pick

#7975 run MDR tests only incase of MDR deployments
  ocs_ci/ocs/constants.py
  tests/disaster-recovery/mdr/__init__.py
  tests/disaster-recovery/mdr/conftest.py
Labels: Verified, team/ecosystem, size/S

#7934 use SC with vSAN Default Storage Policy as default for ODF deployment
  conf/ocsci/vsphere_disable_custom_sc_in_deployment.yaml
  ocs_ci/deployment/vmware.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/templates/ocs-deployment/storageclass_thin-csi-odf.yaml
Labels: Verified, team/ecosystem, size/S

#7820 Fix packagemanifest timeout for acm
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/XS, DR

#8031 discon. cl.: ensure that metadata.json file exists
  ocs_ci/deployment/flexy.py
Labels: Verified, team/ecosystem, size/XS

#8012 Combine test cases OCS-2495 and OCS-2494 to save run time
  tests/manage/pv_services/test_del_mon_service_and_create_pvc.py
Labels: Verified, size/S, Squad/Green

#8018 fix removal of MS tests from skiped list
  tests/e2e/conftest.py
Labels: Verified, team/ecosystem, size/S

#8017 Enhance PVC creation to use kube_job which avoids memory issue
  ocs_ci/ocs/scale_lib.py
  tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Labels: Verified, size/L, scale

#8038 correcting logging info for downloading mcg-cli
  ocs_ci/ocs/resources/mcg.py
Labels: team/ecosystem, size/XS

#8037 verify maximum openshift version allowed
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/M

#8036 Apply ICSP also for upgrade scenario
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: team/ecosystem, size/XS, cherry-pick

#8024 cherry picked changes of pr 7873
  ocs_ci/framework/pytest_customization/marks.py
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/XS

#8043 version check for verifying max openshift version
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/utility/version.py
Labels: Verified, team/ecosystem, size/XS

#8046 Pin new version of webdriver_manager to 3.9.1
  setup.py
Labels: team/ecosystem, size/XS

#8049 Pin new version of webdriver_manager to 3.9.1
  setup.py
Labels: team/ecosystem, size/XS, cherry-pick

#8050 Pin new version of webdriver_manager to 3.9.1
  setup.py
Labels: team/ecosystem, size/XS, cherry-pick

#8051 Pin new version of webdriver_manager to 3.9.1
  setup.py
Labels: team/ecosystem, size/XS, cherry-pick

#8052 Fix webdriver issue release 4.10
  setup.py
Labels: team/ecosystem, size/XS, cherry-pick

#8042 Release 4.13 cherry pick pr 7979: Disabling Multicloud Object Gateway external service and make sure disableLoadBalancerService isn't reconciled
  tests/e2e/kcs/test_disable_mcg_external_service.py
Labels: size/M, MCG, Customer defects, Squad/Red, cherry-pick

#8040 Release 4.13 cherry pick pr 7973 : test noobaa_bucket_used_bytes prometheus metrics
  ocs_ci/ocs/exceptions.py
  tests/manage/mcg/test_noobaa_prometheus.py
Labels: team/e2e, size/M, MCG, Customer defects, Squad/Red, cherry-pick

#8009 Get noobaa CLI from the image provided by build team or the released …
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/mcg.py
Labels: team/ecosystem, size/L, cherry-pick

#8008 Get noobaa CLI from the image provided by build team or the released …
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/mcg.py
Labels: team/ecosystem, cherry-pick

#8033 Apply ICSP also for upgrade scenario
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: team/ecosystem, size/XS, cherry-pick

#8034 Apply ICSP also for upgrade scenario
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: team/ecosystem, size/XS, cherry-pick

#7916 Fix issues with multus verification for cluster network only deployments
  conf/deployment/baremetal/upi_1az_rhcos_multus_cluster_nvme_intel_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_multus_cluster_vsan_3m_3w.yaml
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/utils.py
Labels: Verified, team/ecosystem, size/M

#8005 update backupschedule for mdr hub recovery
  ocs_ci/deployment/deployment.py
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/templates/ocs-deployment/multicluster/backupschedule.yaml
Labels: Verified, size/M, DR

#7678 Add appset support for RDR test
  conf/ocsci/dr_workload.yaml
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/dr/dr_workload.py
  ocs_ci/templates/DR/drpc.yaml
  tests/conftest.py
  tests/disaster-recovery/regional-dr/test_failover_and_relocate.py
Labels: Verified, size/L, DR

#7978 Configuration of DRclusters to enable fencing
  ocs_ci/deployment/deployment.py
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/utils.py
Labels: Verified, size/L, DR

#8066 Cherry pick PR 7862-8018-release-4.11
  ocs_ci/ocs/bdi/bdi_base_class.py
  tests/e2e/conftest.py
  tests/e2e/workloads/app/amq/test_amq_streamer_creation.py
  tests/e2e/workloads/ocp/registry/test_simple_registry_workload.py
  tests/ecosystem/upgrade/test_logging_upgrade.py
Labels: size/M

#8065 Cherry pick PR 7862-8018-release-4.10
  ocs_ci/ocs/bdi/bdi_base_class.py
  tests/e2e/conftest.py
  tests/e2e/workloads/app/amq/test_amq_streamer_creation.py
  tests/e2e/workloads/ocp/registry/test_simple_registry_workload.py
  tests/ecosystem/upgrade/test_logging_upgrade.py
Labels: size/M

#8063 Release 4.13 cherry pick pr 7916
  conf/deployment/baremetal/upi_1az_rhcos_multus_cluster_nvme_intel_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_multus_cluster_vsan_3m_3w.yaml
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/utils.py
Labels: team/ecosystem, size/M, cherry-pick

#7920 GSS Automation, Remove the entry of removed node from Storagecluster under Node Topology
  ocs_ci/helpers/helpers.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
  tests/manage/z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
Labels: team/e2e, size/M, Customer defects

#8030 Add OCP 4.12 and 4.13 GA upgrade config files
  ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.13-ga-upgrade.yaml
Labels: Verified, team/ecosystem, size/S

#8085 Add OCP 4.12 and 4.13 GA upgrade config files
  ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.13-ga-upgrade.yaml
Labels: team/ecosystem, size/S, cherry-pick

#8084 Add OCP 4.12 and 4.13 GA upgrade config files
  ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.13-ga-upgrade.yaml
Labels: team/ecosystem, cherry-pick

#8086 Backport fixPR 8018 to release-4.13
  tests/e2e/conftest.py
Labels: size/S

#8025 cherry picked changes of pr 7873
  ocs_ci/framework/pytest_customization/marks.py
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/XS, Squad/Brown

#7995 Scale test obc_start_time_respin_noobaa_pods
  ocs_ci/ocs/scale_noobaa_lib.py
  tests/e2e/scale/noobaa/test_scale_obc_start_time_respin_noobaa_pods.py
Labels: Verified, size/L, scale

#7604 ClusterLoad: Replace FIO DeploymentConfig with Deployment
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/cluster_load.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/workloads/fio/fedora_deployment.yaml
  ocs_ci/templates/workloads/fio/fio_dc.yaml
  tests/conftest.py
Labels: Verified, size/L

#7647 NSFS noobaa-endpoint SCC workaround
  ocs_ci/ocs/constants.py
  tests/conftest.py
  tests/manage/mcg/test_nsfs.py
Labels: size/L, MCG, Squad/Red

#8106 Disconnected ODF deployment: apply icsp rules when mirroring images
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/disconnected.py
  ocs_ci/utility/deployment.py
Labels: Verified, team/ecosystem, size/L

#7977 Test if access_key or secret_key details are found in pv pool backingstore pod
  tests/manage/mcg/test_pv_pool.py
Labels: Verified, team/e2e, size/S, MCG, Customer defects, Squad/Red

#8096 use absolute path for bin directory
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem

#8127 Fix for the common tox issue: 'isinstance instead of type(obj) == type'
  ocs_ci/ocs/fiojob.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/objectbucket.py
  ocs_ci/ocs/resources/packagemanifest.py
  ocs_ci/ocs/tests/test_fiojob.py
  ocs_ci/ocs/ui/odf_topology.py
  ocs_ci/utility/utils.py
Labels: Verified, size/S

#8108 delete custom sc backed pvc's during teardown
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/XS

#8132 flake8 isinstance backport 4.13
  ocs_ci/ocs/fiojob.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/objectbucket.py
  ocs_ci/ocs/resources/packagemanifest.py
  ocs_ci/ocs/tests/test_fiojob.py
  ocs_ci/utility/utils.py
Labels: size/S, cherry-pick

#8133 flake8 isinstance backport 4.12
  ocs_ci/ocs/fiojob.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/objectbucket.py
  ocs_ci/ocs/resources/packagemanifest.py
  ocs_ci/ocs/tests/test_fiojob.py
  ocs_ci/utility/utils.py
Labels: size/S, cherry-pick

#8134 flake8 isinstance backport 4.11
  ocs_ci/ocs/fiojob.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/objectbucket.py
  ocs_ci/ocs/resources/packagemanifest.py
  ocs_ci/ocs/tests/test_fiojob.py
  ocs_ci/utility/utils.py
Labels: size/S, cherry-pick

#8135 flake8 isinstance backport 4.10
  ocs_ci/ocs/fiojob.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/objectbucket.py
  ocs_ci/ocs/resources/packagemanifest.py
  ocs_ci/ocs/tests/test_fiojob.py
  ocs_ci/utility/utils.py
Labels: size/S, cherry-pick

#8128 change FLEXY_IMAGE_URL to images.paas.redhat.com - backport for 4.12
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/XS, cherry-pick

#8129 change FLEXY_IMAGE_URL to images.paas.redhat.com - backport for 4.11
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/XS, cherry-pick

#8104 Update Bare metal Deployment to Support new Server
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/connection.py
Labels: Verified, size/M

#8130 change FLEXY_IMAGE_URL to images.paas.redhat.com - backport for 4.10
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/XS, cherry-pick
