Repository red-hat-storage/ocs-ci, pull requests merged in 2023-01, with the labels that each got.

#6848 Verify provider topology based on deployer version in MS
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S, Managed Services

#6836 BZ #2096395 automation.
  tests/e2e/workloads/app/test_jenkins_simulation.py
Labels: Verified, team/e2e, size/M, Customer defects

#6856 Add the skipif_disconnected_cluster flag to test_s3_with_java_sdk.py::TestS3WithJavaSDK
  tests/manage/mcg/test_s3_with_java_sdk.py
Labels: size/XS

#6858 Fix the expected error message when providing an empty secret name at TestAdmissionWebhooks::test_namespacestore_creation_webhook[Empty secret name]
  tests/manage/mcg/test_admission_control.py
Labels: size/XS, MCG, Squad/Red

#6650 Split add capacity test on tier1 suite [ui] and acceptance test [cli]
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/ui/add_replace_device_ui.py
  ocs_ci/ocs/ui/views.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
Labels: size/M

#6803 Fix validation for namespacestore creation webhook test
  tests/manage/mcg/test_admission_control.py
Labels: size/XS

#6800 Fix a mismatch between the PyTest param and it's ID at test_unidirectional_namespace_bucket_replication
  tests/manage/mcg/test_bucket_replication.py
Labels: good first issue, size/XS, MCG, Squad/Red

#6801 Add the skipif_mcg_only mark to MCG PVPool tests
  tests/manage/mcg/test_bucket_creation.py
  tests/manage/mcg/test_bucket_deletion.py
Labels: good first issue, size/S, MCG, Squad/Red

#6859 `test_noobaa_kms_validation` - Also check the logs with --previous if the noobaa-operator pod restarted
  tests/manage/mcg/test_kms.py
Labels: size/M, MCG, Squad/Red

#6652 [RDR] Update mirroring status related helper methods to check correct replaying image count
  ocs_ci/helpers/dr_helpers.py
Labels: Verified, size/M, DR

#6784 Include Deployment resource kind to be removed during DR workload cleanup
  ocs_ci/ocs/dr/dr_workload.py
Labels: size/XS, DR

#6788 Turquoise squad for RDR test cases
  .github/CODEOWNERS
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/constants.py
  pytest.ini
Labels: size/XS, DR, Squad/Turquoise

#6874 Added skipif_external_mode tag for test_mon_log_trimming testcase
  tests/manage/z_cluster/test_mon_log_trimming.py
Labels: Verified, size/XS

#6879 Skip couchbase workload tests on OCP version >= 4.12
  tests/e2e/workloads/app/couchbase/test_couchbase.py
  tests/e2e/workloads/app/couchbase/test_couchbase_node_drain.py
  tests/e2e/workloads/app/couchbase/test_couchbase_node_reboot.py
  tests/e2e/workloads/app/couchbase/test_couchbase_pod_respin.py
Labels: team/e2e, size/S

#6825 Fix test_rbd_image_metadata in external mode
  tests/manage/pv_services/test_rbd_image_metadata.py
Labels: Verified, size/XS, Squad/Green

#6830 Collect OCP logs for whole z_cluster directory
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: Verified, size/XS, Squad/Brown

#6732 Update pre-commit-config with new repository of flake8
  .pre-commit-config.yaml
Labels: Verified, size/XS

#6885 Fix test_validate_ceph_config_values_in_rook_config_override for ODF 4.12
  ocs_ci/ocs/constants.py
  tests/manage/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/S, Squad/Brown

#6818 Automation analysis backlog. Skip test for external mode. Test is not designed…
  tests/manage/z_cluster/test_hugepages.py
  tests/manage/z_cluster/test_mon_data_avail_warn.py
Labels: Verified, size/S

#6832 added skip annotation for external mode deployments
  tests/manage/z_cluster/test_delete_rook_ceph_mon_pod.py
Labels: Verified, size/XS

#6887 Fix test_over_provision_level_policy_control on ODF4.10 because bz-2158277
  tests/manage/pv_services/test_overprovision_level_policy_control.py
Labels: Verified, size/XS

#6787 wait for all nodes to create in IBM Cloud IPI
  ocs_ci/ocs/node.py
Labels: team/ecosystem, size/XS

#6804 config changes required after renaming operator name lvmo to lvms.
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pvc.py
  ocs_ci/templates/CSI/lvm/volume-snapshot-lvms.yaml
  ocs_ci/templates/lvmo-deployment/lvms-bundle.yaml
  ocs_ci/templates/lvmo-deployment/lvms-cluster.yaml
  ocs_ci/utility/lvmo_utils.py
  tests/conftest.py
  tests/lvmo/test_lvm_manual_diskpath.py
Labels: Verified, size/L

#6789 Add test for PV encryption using Ciphertrust
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/defaults.py
  ocs_ci/templates/CSI/rbd/csi-kms-connection-details-kmip.yaml
  ocs_ci/templates/CSI/rbd/thales-kmip-csi-secret.yaml
  ocs_ci/utility/kms.py
  tests/conftest.py
  tests/manage/pv_services/pv_encryption/test_kmip_rbd_pv_encryption.py
Labels: Verified, team/manage, size/L, new feature

#6888 Fix the deletion of the underlying storage of GCP BackingStores and minor refactor regarding CloudClient.delete_uls
  ocs_ci/ocs/resources/cloud_manager.py
Labels: size/L, MCG, Squad/Red

#6898 Donot fail teardown incase of KMS cleanup failures
  tests/conftest.py
Labels: Verified, team/ecosystem, size/XS

#6880 Adding black squad for test_quickstarts
  tests/ui/test_quickstarts.py
Labels: team/ecosystem, size/XS

#6321 Upgrade with RGW obc bucket contains objects
  ocs_ci/ocs/hsbench.py
  ocs_ci/ocs/scale_noobaa_lib.py
  ocs_ci/templates/workloads/hsbench/hsbench_obj.yaml
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_rgw_obc.py
Labels: Needs Testing, size/L, scale, MCG

#6919 update rosa version
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/XS, Managed Services

#6920 Update MS provider topology verification
  ocs_ci/helpers/managed_services.py
Labels: size/L, Managed Services

#6923 Disconnected deplyoment: lvm operator moved out from odf
  ocs_ci/ocs/constants.py
Labels: team/ecosystem, size/XS

#6912 In the test "test_noobaa_sts_host_node_failure" Change how we check the old noobaa operator status
  tests/manage/mcg/test_host_node_failure.py
Labels: Verified, size/M

#6915 comment senstive variable in destroy cluster
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/XS

#6896 Garbage collector for WebDriver
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/utility/retry.py
Labels: Verified, size/M

#6934 Skip test_overprovision_level_policy_control_with_capacity on external mode
  tests/manage/pv_services/test_overprovision_level_policy_control_with_capacity.py
Labels: team/manage, size/XS, Squad/Green

#6931 Add OCP 4.12-ga files
  ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-minus1-config.yaml
Labels: size/M

#6938 Increase timeout to rosa version command
  ocs_ci/utility/rosa.py
  ocs_ci/utility/utils.py
Labels: Verified, size/XS, Managed Services

#6926 Enable subnet ids from config parameter for appliance mode provider
  ocs_ci/utility/rosa.py
Labels: Verified, size/S, Managed Services

#6907 add VAULT_CA_ONLY to the external_vault_v1_with_namespace config
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_external_vault_v1_with_namespace.yaml
Labels: team/ecosystem, size/XS

#6805 pause MachineHealthCheck during OCP upgrade
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/utility/ocp_upgrade.py
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Verified, team/ecosystem, size/M

#6940 Disable managed ODF topology check
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S, Managed Services

#6950 Add billing model paramater to rosa install addon command
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/utility/rosa.py
Labels: Verified, Managed Services

#6956 MS: Move OSD memory check to verify_provider_topology function
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: size/M, Managed Services

#6959 Fix login UI urllib3 exceptions MaxRetryError
  ocs_ci/ocs/ui/base_ui.py
Labels: Verified, size/XS

#6961 add VAULT_CA_ONLY parameter to external vault config files
  conf/deployment/vsphere/ipi_1az_rhcos_vsan_3m_3w_external_vault_v1_with_namespace.yaml
  conf/deployment/vsphere/ipi_1az_rhcos_vsan_3m_3w_external_vault_v2_with_namespace.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_external_vault_v2_with_namespace.yaml
Labels: Verified, team/ecosystem, size/S

#6894 Skip MCG tests that make external requests in disconnected deployments
  tests/manage/mcg/test_cached_buckets.py
  tests/manage/mcg/test_multi_region.py
  tests/manage/mcg/test_namespace_crd.py
  tests/manage/mcg/test_noobaa_secret.py
  tests/manage/mcg/test_object_integrity.py
Labels: size/S, MCG, Squad/Red

#6967 Don't create custom catalog in UI live deployment
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/XS

#6932 Fixed test_s3_benchmark_object_bucket resource leftover and test case…
  ocs_ci/ocs/hsbench.py
Labels: size/XS, scale, MCG

#6984 use GA'ed RHCOS template for OCP 4.12 GA'ed version
  ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-minus1-config.yaml
Labels: team/ecosystem

#6992 Verify provider topology for dev-addon
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/XS, Managed Services

#6978 Skip test on disconnected/proxy clusters
  tests/manage/pv_services/pv_encryption/test_vault_namespace_override_using_tenant_configmap.py
Labels: Verified, team/manage, size/XS, Squad/Green

#6889 Delete noobaa-scc-describe.txt from mg list
  ocs_ci/ocs/must_gather/const_must_gather.py
Labels: size/XS

#7003 remove myself from CODEOWNERS file
  .github/CODEOWNERS
Labels: size/XS

#6991 latency setup for a single cluster
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_6w_arbiter.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/netsplit.py
  ocs_ci/ocs/resources/machineconfig.py
  requirements.txt
Labels: Verified, size/L

#7001 Add retry for OSD schema validation in post upgrade
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/M

#6986 Update markers of NooBaa alerting tests
  tests/manage/monitoring/prometheus/test_noobaa.py
Labels: Verified, size/XS, Squad/Blue

#7010 Fix local variable reference in post deployment check
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S, Managed Services

#6989 Create a new function for generating nodes for the provider worker node tests
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/nodes/test_nodes_restart_ms.py
Labels: Verified, size/M, Managed Services

#6641 Acm changes for 4 12
  conf/examples/acm_hub_unreleased_image.yaml
  ocs_ci/deployment/acm.py
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/acm/acm_constants.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/ui/acm_ui.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/L, DR

#7014 fix for Quay workload
  tests/e2e/workloads/app/quay/test_quay_operator.py
Labels: Verified, team/e2e, size/S

#6997 Fix #6726 skip test_check_mon_pdb_post_upgrade on MS-consumers
  tests/manage/z_cluster/upgrade/test_check_pdb_post_upgrade.py
Labels: Verified, size/XS, Managed Services

#6998 support Terraform version 1.0.11
  ocs_ci/deployment/terraform.py
  ocs_ci/deployment/vmware.py
  ocs_ci/framework/conf/ocp_version/ocp-4.13-config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/utility/load_balancer.py
  ocs_ci/utility/version.py
Labels: Verified, team/ecosystem, size/L

#7018 Add option for SSH key in external cluster deployment
  conf/README.md
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/M
