Repository red-hat-storage/ocs-ci, pull requests merged in 2023-06, with the labels that each got.

#7723 Add Prometheus version check for faas
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/helpers/managed_services.py
Labels: Verified, size/S, Managed Services

#7718 Fix the check for storageclassclaims and sc in FaaS consumer
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S, Managed Services

#7719 Fix the check for storageclassclaims in test_verify_storageclassclaim
  ocs_ci/ocs/resources/storageclassclaim.py
  tests/managed-service/test_storageclassclaim.py
Labels: Verified, size/M, Managed Services

#7600 test error message improvements for name inputs. new feature
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
  tests/ui/test_error_improvements.py
Labels: size/XXL, ui_automation, Squad/Black

#7612 ibmcloud fix node_restart
  ocs_ci/utility/ibmcloud.py
Labels: size/S, IBM Cloud

#7724 IBM Cloud machineset yaml support
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/scale_lib.py
  ocs_ci/templates/openshift-infra/machineset-ibm-cloud.yaml
Labels: size/L, scale

#7742 ibmcloud fix node_restart (#7612)
  ocs_ci/utility/ibmcloud.py
Labels: size/S

#7744 ibmcloud fix node_restart (#7612)
  ocs_ci/utility/ibmcloud.py
Labels: size/S

#7733 Add FAAS OSD PVC check
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/M, Managed Services

#7593 Adding reclaim space cron job tc and refactoring
  ocs_ci/templates/CSI/addons/ReclaimSpaceCronJob.yaml
  ocs_ci/templates/CSI/addons/ReclaimSpaceJob.yaml
  ocs_ci/templates/CSI/addons/volumeReplicationCR.yaml
  ocs_ci/templates/CSI/addons/volumeReplicationClass.yaml
  tests/e2e/system_test/test_cr_resources_validation.py
Labels: Verified, size/L

#7708 Remove the `rgw_endpoint` fixture
  ocs_ci/ocs/constants.py
  tests/conftest.py
  tests/manage/rgw/test_bucket_creation.py
  tests/manage/rgw/test_bucket_deletion.py
  tests/manage/rgw/test_multipart_upload.py
  tests/manage/rgw/test_object_integrity.py
Labels: size/M, RGW, Squad/Red

#7738 Enable in-transit encryption for external mode deployment
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/helpers/external_cluster_helpers.py
Labels: Verified, team/ecosystem, size/S

#7741 In the test "test_rolling_nodes_restart" add retry decorator when creating resources
  tests/manage/z_cluster/nodes/test_nodes_restart.py
Labels: Verified, size/XS, Squad/Brown

#7715 Update fio_dc.yaml - to suppress debconf messages | Fixes: #7711
  ocs_ci/templates/workloads/fio/fio_dc.yaml
Labels: Verified, size/XS

#7721 update noobaa quota alert names
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/objectbucket.py
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/prometheus/test_noobaa.py
Labels: Verified, size/M

#7652 Fix test_ceph_pg_log_dups_trim. Replace oc cp calls (Updated) (#7178)
  ocs_ci/ocs/rados_utils.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: Verified, size/M, Squad/Brown

#7430 MDR Multicluster ODF external mode deployment with MDR operator configurations
  conf/ocsci/external_rhcs_cluster.yaml
  conf/ocsci/multicluster_active_acm.yaml
  conf/ocsci/multicluster_mode_mdr.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/utils.py
  ocs_ci/templates/ocs-deployment/multicluster/backupschedule.yaml
  ocs_ci/templates/ocs-deployment/multicluster/dpa_acm.yaml
  ocs_ci/templates/ocs-deployment/multicluster/mirror_peer_mdr.yaml
  ocs_ci/templates/ocs-deployment/multicluster/mirror_peer_rdr.yaml
  tests/ecosystem/deployment/test_deployment.py
Labels: Verified, team/ecosystem, size/XL, DR

#7756 fix patch cmd to enable in-transit encryption
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/S

#7736 Adding green squad for encryption feature
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem

#7720 Update ManagedFusionOffering template and remove storageclassclaim CRD workaround
  ocs_ci/ocs/fusion.py
  ocs_ci/templates/fusion-aas/managedfusionoffering-dfc.yaml.j2
  ocs_ci/templates/fusion-aas/managedfusionoffering.yaml.j2
Labels: Verified, size/M, Managed Services

#7740 get and apply ICPS from catalog image
  ocs_ci/deployment/deployment.py
Labels: size/M

#7759 Fix the verification of usableCapacityInTiB
  ocs_ci/helpers/managed_services.py
Labels: Verified, size/XS, Managed Services

#7762 get and apply ICPS from catalog image - backport to 4.12
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/M

#7764 get and apply ICPS from catalog image - backport to 4.10
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/M

#7765 get and apply ICPS from catalog image - backport to 4.9
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/M

#7766 get and apply ICPS from catalog image - backport to 4.8
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/M

#7752 Increase capacity of utilization tests
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/prometheus/test_capacity.py
  tests/manage/monitoring/sendgrid/test_capacity.py
Labels: Verified, size/M

#7771 Create ICSP only if non GA
  ocs_ci/ocs/fusion.py
Labels: Verified, size/S, Managed Services

#7770 Fix issue with applying ICSP for upgrade scenario
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/XS

#7768 Fix the verification of onboardingValidationKey
  ocs_ci/helpers/managed_services.py
Labels: Verified, size/XS, Managed Services

#7772 Fix issue with applying ICSP for upgrade scenario
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/XS, cherry-pick

#7776 Fix issue with applying ICSP for upgrade scenario
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/XS, cherry-pick

#7775 Fix issue with applying ICSP for upgrade scenario
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/XS, cherry-pick

#7773 Fix issue with applying ICSP for upgrade scenario
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/XS, cherry-pick

#7731 Added flexibility to pull desired channel for Quay operator deployment
  ocs_ci/ocs/quay_operator.py
Labels: Verified, team/e2e, size/S, Squad/Magenta

#7727 Jenkins Workload, change the image
  ocs_ci/ocs/jenkins.py
  ocs_ci/templates/workloads/jenkins/buildconfig.yaml
Labels: Verified, team/e2e, size/S, Squad/Magenta

#7753 Run the nodes restart tests with vSphere IPI
  ocs_ci/ocs/cluster.py
  tests/manage/z_cluster/nodes/test_nodes_restart.py
Labels: Verified, size/M, Squad/Brown

#7631 Add missing toleration
  ocs_ci/templates/gitops-deployment/gitops_placement.yaml
Labels: Verified, size/XS, DR

#7790 In the test "test_delete_rook_ceph_osd_deployment" ignore the "rook-ceph-osd" labels in the leftovers
  tests/manage/z_cluster/test_delete_osd_deployment.py
Labels: Verified, size/XS, Squad/Brown

#7777 add cluster_dir_full_path to result xml - backport to 4.12
  conf/README.md
  tests/conftest.py
Labels: team/ecosystem, size/XS, cherry-pick

#7779 add cluster_dir_full_path to result xml - backport to 4.10
  conf/README.md
  tests/conftest.py
Labels: team/ecosystem, size/XS, cherry-pick

#7683 Fixes:7468
  ocs_ci/ocs/cosbench.py
Labels: Verified, team/e2e, size/M, Squad/Magenta

#7749 Cherry pick PR 7514 : Fixes purge bucket with versioning at the teardown
  ocs_ci/ocs/resources/objectbucket.py
Labels: size/XS, MCG, Squad/Red

#7789 Add wait to avoid race condition in test_obc_quota
  tests/manage/rgw/test_obc_quota.py
Labels: size/XS, RGW, Squad/Red

#7345 Check for an existing pod before calling `awscli_pod_fixture`, and leverage the retry decorator in it
  tests/conftest.py
Labels: size/S, MCG, Squad/Red

#7795 Adjust send_rpc_query to send RPC requests via the NooBaa CLI
  ocs_ci/ocs/resources/mcg.py
Labels: Verified, size/M, MCG

#7808 supporting IPI for ntp update
  ocs_ci/utility/vsphere_nodes.py
Labels: Verified, team/ecosystem, size/XS

#7748 Add waiting to cephcluster check
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S, Managed Services

#7807 Remove rbdpool from rhcs external config file
  conf/ocsci/external_rhcs_cluster.yaml
Labels: team/ecosystem, size/XS

#7810 Update metrics list according to bz 2203795 and allow test_ceph_rbd_metrics_available
  ocs_ci/ocs/metrics.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
Labels: Verified, size/S

#7726 `test_mcg_namespace_lifecycle_crd`: Add allow policies to bucket for the new user
  tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
Labels: size/M, MCG, Squad/Magenta, Squad/Red

#7745 BaseUI: added module_loc to page_has_loaded
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
Labels: size/S

#7801 fix for failing tests
  ocs_ci/ocs/ui/base_ui.py
Labels: TestCase failing, size/XS, ui_automation, Squad/Black

#7548 Fix test_quickstart_presence ODF 413
  ocs_ci/ocs/ui/base_ui.py
  tests/ui/test_quickstarts.py
Labels: size/S

#7822 update RHCOS template for 4.13
  ocs_ci/framework/conf/ocp_version/ocp-4.13-config.yaml
Labels: Verified, team/ecosystem, size/XS

#7802 Don't collect must gather twice for deployment
  ocs_ci/framework/pytest_customization/ocscilib.py
Labels: Verified, team/ecosystem, size/XS

#7314 Get ODF must-gather logs
  ocs_ci/ocs/utils.py
Labels: team/ecosystem, size/L

#7819 Fusion deployment
  conf/ocsci/fusion_deployment.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/fusion.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/defaults.py
  ocs_ci/templates/fusion/catalog-source.yaml
  ocs_ci/templates/fusion/namespace.yaml
  ocs_ci/templates/fusion/subscription.yaml
Labels: Verified, team/ecosystem, size/L

#7836 Apply ICSP also for upgrade scenario
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/XS

#7834 Add Vsphere IPI compact mode in-transit encryption config
  conf/deployment/vsphere/ipi_1az_rhcos_vsan_compact_mode_3m_0w_intransit_encryption.yaml
Labels: team/ecosystem, size/S

#7832 added exclude for noobaa-db-pg-0-init.log
  ocs_ci/ocs/must_gather/const_must_gather.py
Labels: Verified, size/XS, Squad/Brown

#7827 Skipping test on 4.13 due to bz2209616
  tests/e2e/workloads/app/amq/test_rgw_kafka_notifications.py
Labels: size/XS

#7818 Use old must gather live image when installing pre 4.13 versions
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/utility/reporting.py
Labels: Verified, team/ecosystem, size/S

#7792 Adding a new test case for VolumeReplication CR edit
  tests/e2e/system_test/test_cr_resources_validation.py
Labels: Verified, size/L

#7855 use insecure for disconnected environment
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/S

#7839 use stable build for ODF 4.14
  ocs_ci/framework/conf/ocs_version/ocs-4.14.yaml
Labels: Verified, team/ecosystem, size/XS

#7746 Check there is no storagecluster on consumer
  ocs_ci/helpers/managed_services.py
Labels: Verified, size/S, Managed Services

#7850 gather bootstrap logs when deployment failed with TimeoutExpired exception
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem

#7794 Fix PG corrupt alerting tests
  ocs_ci/ocs/rados_utils.py
  tests/manage/monitoring/conftest.py
  tests/manage/monitoring/prometheus/test_ceph.py
Labels: Verified, size/M

#7862 skip few workloads tests from results summary report
  ocs_ci/ocs/bdi/bdi_base_class.py
  tests/e2e/conftest.py
  tests/e2e/workloads/app/amq/test_amq_streamer_creation.py
  tests/e2e/workloads/ocp/registry/test_simple_registry_workload.py
  tests/ecosystem/upgrade/test_logging_upgrade.py
Labels: Verified, team/e2e, size/M, Squad/Magenta

#7840 Fix test_registry_shutdown_and_recovery_node failure
  tests/e2e/workloads/ocp/registry/test_registry_shutdown_and_recovery_node.py
Labels: Verified, team/e2e, size/XS, Squad/Magenta

#7838 Support test_non_ocs_taint_and_tolerations for external mode
  tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Labels: Verified, size/M, Squad/Brown

#7882 Update ACM version to 2.8 GAed
  ocs_ci/framework/conf/ocp_version/ocp-4.13-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.13-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.13-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.14-config.yaml
Labels: Verified, size/XS, DR

#7876 Allow to extract installer and client from custom OCP build
  conf/README.md
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/M

#7892 Allow to extract installer and client from custom OCP build
  conf/README.md
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/M, cherry-pick

#7890 Allow to extract installer and client from custom OCP build
  conf/README.md
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/M, cherry-pick

#7891 Allow to extract installer and client from custom OCP build
  conf/README.md
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/M, cherry-pick

#7894 Cherry-pick test_non_ocs_taint_and_tolerations for external mode on 4.12
  tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Labels: Verified, size/L, Squad/Brown

#7863 Enhance the `ignore_leftover_label` to support labels other than app for release-4.12 (#7710)
  ocs_ci/ocs/constants.py
  ocs_ci/utility/environment_check.py
  tests/libtest/test_skip_labeled_leftover.py
  tests/managed-service/test_pod_disruptions.py
Labels: enhancement, Verified, size/M, Squad/Brown

#7883 Add checking aws volumes for osd and mon pvcs
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/aws.py
Labels: size/L, Managed Services

#7563 Test to verify application failover and relocate between managed
  conf/ocsci/dr_ui.yaml
  conf/ocsci/mdr_workload.yaml
  conf/ocsci/multicluster_mode_mdr.yaml
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/helpers/dr_helpers_ui.py
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/dr/dr_workload.py
  ocs_ci/ocs/node.py
  tests/conftest.py
  tests/disaster-recovery/mdr/test_app_failover_and_relocate.py
Labels: Verified, size/XL

#7878 Enhance the ignore_leftover_label to support labels other than app for release-4.11 (#7710)
  ocs_ci/ocs/constants.py
  ocs_ci/utility/environment_check.py
  tests/libtest/test_skip_labeled_leftover.py
  tests/managed-service/test_pod_disruptions.py
Labels: enhancement, Verified, size/M, Squad/Brown

#6675 RDR node failure tests
  ocs_ci/ocs/constants.py
  tests/disaster-recovery/regional-dr/test_managed_cluster_node_failure.py
Labels: Test Case, Verified, size/L, DR, Squad/Turquoise

#7796 [BM] Fix multus deployment
  conf/deployment/baremetal/upi_1az_rhcos_multus_cluster_nvme_intel_3m_3w.yaml
  conf/deployment/baremetal/upi_1az_rhcos_multus_nvme_intel_3m_3w.yaml
  ocs_ci/deployment/deployment.py
Labels: Needs Deployment Testing, team/ecosystem, size/S

#7843 Azure ARO deployment
  conf/deployment/azure/managed_aro_3az_rhcos_3m_3w.yaml
  ocs_ci/deployment/azure.py
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/factory.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/monitoring.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/ui/views.py
  ocs_ci/utility/azure_utils.py
  ocs_ci/utility/ssl_certs.py
  ocs_ci/utility/utils.py
  tests/ecosystem/deployment/test_deployment.py
Labels: Needs Deployment Testing, team/ecosystem, size/XL

#7846 Remove Skip marker in 12 node Scale Test
  tests/e2e/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
Labels: size/XS, scale

#7919 Update the multicluster_mode_mdr.yaml
  conf/ocsci/multicluster_mode_mdr.yaml
  ocs_ci/helpers/dr_helpers.py
  tests/conftest.py
Labels: size/S

#7915 Defaulting OCS-CI to 4.14
  ocs_ci/framework/conf/default_config.yaml
  setup.py
Labels: team/ecosystem, size/S

#7797 In the test "test_delete_rook_ceph_osd_deployment" ignore the "rook-ceph-osd" labels in the leftovers #7790
  tests/manage/z_cluster/test_delete_osd_deployment.py
Labels: size/S, Squad/Brown

#7852 Adding test automation for OCS-3885 and OCS-3886
  ocs_ci/ocs/ui/block_pool.py
  ocs_ci/ocs/ui/views.py
  tests/conftest.py
  tests/ui/test_creation_and_deletion_of_sc_and_rbdpool.py
Labels: size/L

#7798 In the test "test_delete_rook_ceph_osd_deployment" ignore the "rook-ceph-osd" labels in the leftovers #7790
  tests/manage/z_cluster/test_delete_osd_deployment.py
Labels: Verified, size/S, Squad/Brown

#7873 Skipping 'test_pdb_check_simultaneous_node_drains' for more than three worker nodes
  ocs_ci/framework/pytest_customization/marks.py
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/XS, Squad/Brown

#7922 skip test_bucket_creation[3-S3-DEFAULT-BACKINGSTORE]
  tests/conftest.py
  tests/manage/mcg/test_bucket_creation.py
Labels: Verified, team/ecosystem, size/S

#7867 login_ui minor improvements
  ocs_ci/ocs/ui/base_ui.py
Labels: Verified, size/L, ui_automation

#7898 add additional locator to confirm delete action
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/XS

#7782 ODF topology view tests
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/odf_topology.py
  ocs_ci/ocs/ui/views.py
  ocs_ci/templates/ocp-deployment/busybox.yaml
  tests/ui/test_error_improvements.py
  tests/ui/test_odf_topology.py
Labels: size/XXL, ui_automation, Squad/Black

#7911 Increase wait for storageclassclaim
  ocs_ci/helpers/managed_services.py
Labels: Verified, size/XS, Managed Services

#7905 Add aws volume name tag check
  ocs_ci/helpers/managed_services.py
  ocs_ci/utility/aws.py
Labels: Verified, size/L, Managed Services

#7899 Refractor get_credentials method to fetch endpoint details from cephobjectstore for external cluster
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/rgw.py
Labels: Verified, size/S, MCG, Squad/Red

#7657 Patch ocs-storagecluster instead the NooBaa CR at `test_disable_nb_lb`
  tests/manage/mcg/test_s3_routes.py
Labels: size/S, MCG, Squad/Red

#7931 Add faas configmap check
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/S, Managed Services

#7918 Use latest image tag for ACM unreleased Install
  conf/ocsci/acm_2.7.yaml
  conf/ocsci/acm_2.8.yaml
  conf/ocsci/acm_2.9.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.12-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.13-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.13-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.13-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.14-config.yaml
  ocs_ci/utility/utils.py
Labels: Verified, size/M, DR

#7877 remove fusion catalog source
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/defaults.py
Labels: Verified, team/ecosystem, size/S
