Repository red-hat-storage/ocs-ci, pull requests merged in 2023-04, with the labels that each got.

#7328 Adjust test rolling nodes terminate for provider release412
  tests/manage/z_cluster/nodes/test_rolling_terminate_and_recovery.py
Labels: Verified, size/M, Squad/Brown

#7393 Use specific RGW endpoint from zone for MDR deployment
  ocs_ci/deployment/helpers/external_cluster_helpers.py
Labels: Verified, team/ecosystem, size/S

#7253 Merge pull request #7166 from prsurve/bm_node_functions
  ocs_ci/ocs/platform_nodes.py
Labels: size/XS, Squad/Brown

#7382 Skip test_automated_recovery_from_stopped_node_and_start for external mode
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: Verified, size/XS, Squad/Brown

#7308 Release 4.9 cherry pick pr 7137
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Labels: Verified, size/XS, Squad/Green

#7301 Release 4.9 cherry pick pr 6987
  tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Labels: Verified, size/XS, Squad/Green

#7292 Backport PR 7202 to release-4.9
  tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py
  tests/manage/pv_services/pvc_snapshot/test_resource_deletion_during_snapshot_restore.py
Labels: Verified, size/XS, Squad/Green

#6472 RFE 2103256: Test maintenance pod for OSDs and Mons
  ocs_ci/ocs/ceph_debug.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/deployment.py
  ocs_ci/templates/krew_plugin/krew_install.sh
  ocs_ci/templates/krew_plugin/rookcephplugin_install.sh
  tests/conftest.py
  tests/e2e/kcs/test_maintenance_pod.py
Labels: Verified, team/e2e, size/XL

#7424 Fix worker instance type for ROKS IBM Cloud deployments
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_hpcs_external.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_stage.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos_stage.yaml
Labels: Verified, team/ecosystem, size/S

#7425 Fix worker instance type for ROKS IBM Cloud deployments
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_hpcs_external.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_stage.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos_stage.yaml
Labels: team/ecosystem, size/S, cherry-pick

#7426 Fix worker instance type for ROKS IBM Cloud deployments
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_hpcs_external.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_stage.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos_stage.yaml
Labels: team/ecosystem, size/S, cherry-pick

#7427 Fix worker instance type for ROKS IBM Cloud deployments
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_hpcs_external.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_stage.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos_stage.yaml
Labels: team/ecosystem, size/S, cherry-pick

#7428 Fix worker instance type for ROKS IBM Cloud deployments
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_hpcs_external.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_stage.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos.yaml
  conf/deployment/ibmcloud/ibm_cloud_vpc_cluster_without_cos_stage.yaml
Labels: team/ecosystem, size/S, cherry-pick

#7437 change FLEXY_IMAGE_URL to images.paas.redhat.com
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/XS

#7385 Fix the testcase test_git_clone
  tests/e2e/workloads/app/test_jenkins_simulation.py
Labels: team/e2e, size/M, Squad/Magenta

#7434 Skip test_stop_worker_nodes_pd
  tests/manage/monitoring/pagerduty/test_deployment_status.py
Labels: Verified, size/XS, Managed Services

#7242 Fix aws cleanup via cli
  ocs_ci/cleanup/aws/cleanup.py
Labels: size/S

#7452 Adding OCP 4.14 config files
  ocs_ci/framework/conf/ocp_version/ocp-4.14-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.14-upgrade.yaml
Labels: Verified, team/ecosystem, size/S

#7300 Release 4.9 cherry pick pr 7194
  tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Labels: size/XS, Squad/Green

#7312 Release 4.12 cherry pick pr 7190
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: size/S, Squad/Green

#7311 Release 4.11 cherry pick pr 7190
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: size/S, Squad/Green

#7310 Release 4.10 cherry pick pr 7190
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: size/S, Squad/Green

#7309 Release 4.9 cherry pick pr 7190
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: size/S, Squad/Green

#7299 Release 4.10 cherry pick pr 7194
  tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Labels: size/XS, Squad/Green

#7298 Release 4.11 cherry pick pr 7194
  tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Labels: size/XS, Squad/Green

#7297 Release 4.12 cherry pick pr 7194
  tests/manage/pv_services/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Labels: size/XS, Squad/Green

#7456 use latest-stable tag for ODF 4.13 version
  ocs_ci/framework/conf/ocs_version/ocs-4.13.yaml
Labels: Verified, team/ecosystem, size/XS

#7372 Use v4scaleup for rhel - vSphere
  ocs_ci/deployment/helpers/vsphere_helpers.py
  ocs_ci/deployment/terraform.py
  ocs_ci/deployment/vmware.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/M

#7307 Release 4.10 cherry pick pr 7137
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Labels: size/XS, Squad/Green

#7306 Release 4.11 cherry pick pr 7137
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Labels: size/XS, Squad/Green

#7305 Release 4.12 cherry pick pr 7137
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Labels: size/XS, Squad/Green

#7304 Release 4.12 cherry pick pr 6987
  tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Labels: size/XS, Squad/Green

#7303 Release 4.11 cherry pick pr 6987
  tests/manage/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
Labels: size/XS, Squad/Green

#7296 Release 4.12 cherry pick pr 7202
  tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py
  tests/manage/pv_services/pvc_snapshot/test_resource_deletion_during_snapshot_restore.py
Labels: size/XS, Squad/Green

#7295 Release 4.11 cherry pick pr 7202
  tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py
  tests/manage/pv_services/pvc_snapshot/test_resource_deletion_during_snapshot_restore.py
Labels: size/XS, Squad/Green

#7294 Release 4.10 cherry pick pr 7202
  tests/manage/pv_services/pvc_clone/test_resource_deletion_during_pvc_clone.py
  tests/manage/pv_services/pvc_snapshot/test_resource_deletion_during_snapshot_restore.py
Labels: size/XS, Squad/Green

#7454 Fix deployment for IBM ROKS
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: Verified, team/ecosystem, size/S

#7361 Update live odf must gather image repo
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.12.yaml
Labels: team/ecosystem, size/XS

#7464 Rosav1.2.16
  ocs_ci/framework/conf/default_config.yaml
Labels: enhancement, Verified, size/XS, Managed Services

#7470 Fix ibm roks deployment release 4.11
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: team/ecosystem, size/S, cherry-pick

#7469 Fix ibm roks deployment release 4.12
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: team/ecosystem, size/S, cherry-pick

#7473 Use --replicas flag
  ocs_ci/utility/rosa.py
Labels: Verified, size/XS

#7360 Add Multi-Stage build Containerfile
  .dockerignore
  Docker_files/Containerfile.ci
  Docker_files/ocsci_container/scripts/run-managed-service.sh
Labels: size/M

#7351 increase-num-dups-411
  ocs_ci/ocs/rados_utils.py
Labels: size/XS

#7357 increase-num-dups-49
  ocs_ci/ocs/rados_utils.py
Labels: size/XS

#7350 increase-num-dups-412
  ocs_ci/ocs/rados_utils.py
Labels: Verified, size/XS, Squad/Brown

#7471 Adding respective pod name along with container name while capturing rpm package list
  ocs_ci/ocs/utils.py
Labels: Verified, size/XS

#7367 Automation for BZ2142901
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/test_no_liveness_probe.py
Labels: team/e2e, size/M, Customer defects

#7060 Non ocs taint and tolerations for NooBaa in standalone mode
  tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Labels: team/e2e, size/L

#7411 Add the 'cluster_type' param to the nodes restart MS tests
  tests/manage/z_cluster/nodes/test_nodes_restart_ms.py
Labels: Verified, size/M, Managed Services

#7466 test_over_provision_level_policy_control [BZ-2158277 Fixed]
  tests/manage/pv_services/test_overprovision_level_policy_control.py
Labels: Verified, size/XS

#7461 Handle deleting rbd images during teardown for deployment failure scenario
  ocs_ci/deployment/vmware.py
Labels: team/ecosystem, size/S

#6785 Log rotate bz-2116416
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/test_rook_ceph_log_rotate.py
Labels: Verified, team/e2e, size/L, Customer defects

#6976 [RDR] Additional health checks, validation for PV and backend image deletion
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/dr/dr_workload.py
  tests/disaster-recovery/regional-dr/test_failover.py
  tests/disaster-recovery/regional-dr/test_failover_and_relocate.py
Labels: Verified, size/L, DR, Squad/Turquoise

#7453 Fusion aaS deployment
  conf/deployment/fusion_aas/managed_3az_provider_qe_3m_3w_m52x.yaml
  ocs_ci/deployment/factory.py
  ocs_ci/deployment/fusion_aas.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/fusion.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/templates/fusion-aas/catalogsource.yaml.j2
  ocs_ci/templates/fusion-aas/managedfusionoffering.yaml.j2
  ocs_ci/templates/fusion-aas/monitoringsecret.yaml.j2
  ocs_ci/templates/fusion-aas/operatorgroup.yaml
  ocs_ci/templates/fusion-aas/subscription.yaml
  tests/conftest.py
Labels: Verified, size/L, Managed Services

#7289 Update markers for RDR tests
  ocs_ci/framework/pytest_customization/marks.py
  pytest.ini
  tests/disaster-recovery/__init__.py
  tests/disaster-recovery/regional-dr/__init__.py
  tests/disaster-recovery/regional-dr/conftest.py
  tests/disaster-recovery/regional-dr/test_failover.py
  tests/disaster-recovery/regional-dr/test_failover_and_relocate.py
  tests/disaster-recovery/regional-dr/test_relocate.py
Labels: Verified, size/M, Squad/Turquoise

#7497 Add cluster to installconfig for vSphere UPI
  ocs_ci/templates/ocp-deployment/install-config-vsphere-upi.yaml.j2
Labels: team/ecosystem, size/XS, cherry-pick

#7439 Revert "Implement MCG load balancer incoming subnet rules test (#6589)"
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/cloud_manager.py
  tests/conftest.py
  tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
  tests/manage/mcg/test_loadbalancer_subnet_config.py
  tests/manage/mcg/test_namespace_crd.py
Labels: size/L

#7499 Use rhel 8.7 for RHEL deployments
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, team/ecosystem, size/XS

#7420 4.12. Cherry-pick. test_obc_creation_and_deletion added RGW sc
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
  tests/manage/mcg/ui/test_mcg_ui.py
Labels: Verified, size/M, ui_automation, Squad/Red, Squad/Black

#7496 Update ACM channel to release-2.7
  ocs_ci/framework/conf/ocp_version/ocp-4.12-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.12-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.13-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.14-config.yaml
Labels: size/S, DR

#7412 Test Automation: CephFS Testing under MDS Pod Network Failure Scenarios for BZ 2130925
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/vsphere.py
  tests/manage/pv_services/test_cephfs_with_mds_network_failure.py
Labels: Verified, team/e2e, size/L, Customer defects

#7163 Test Failover/Relocate from ACM UI for Regional DR
  conf/ocsci/dr_ui.yaml
  ocs_ci/helpers/dr_helpers_ui.py
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/acm_ui.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
  tests/disaster-recovery/regional-dr/test_failover.py
  tests/disaster-recovery/regional-dr/test_failover_and_relocate.py
  tests/disaster-recovery/regional-dr/test_relocate.py
Labels: Verified, size/XL, DR, Squad/Turquoise

#7359 Fix `template_pvc` to specify the PVC's capacity units
  ocs_ci/ocs/resources/namespacestore.py
Labels: size/XS, MCG, Squad/Red

#7022 Collect mustgather from all clusters in case of multicluster scenario
  ocs_ci/framework/main.py
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/ui/acm_ui.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
  ocs_ci/ocs/utils.py
  ocs_ci/utility/flexy.py
  ocs_ci/utility/utils.py
  ocs_ci/utility/version.py
Labels: Verified, team/ecosystem, size/L, DR

#7524 Enable Globalnet for Submariner connectivity
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/M, DR, Squad/Turquoise

#7369 Fix test_verify_storageclassclaim
  tests/managed-service/test_storageclassclaim.py
Labels: Verified, Managed Services

#7502 Fix OCS-CI container
  .dockerignore
  Docker_files/ocsci_container/Containerfile.ci
  Docker_files/ocsci_container/Dockerfile_ocsci
  Docker_files/ocsci_container/README.md
  Docker_files/ocsci_container/build-image.sh
  Docker_files/ocsci_container/k8s.repo
  Docker_files/ocsci_container/scripts/common.sh
  Docker_files/ocsci_container/scripts/debug-odf.sh
  Docker_files/ocsci_container/scripts/install-ocs-ci.sh
  Docker_files/ocsci_container/scripts/run-managed-service.sh
  Docker_files/ocsci_container/scripts/run-ocs-ci.sh
  Docker_files/ocsci_container/scripts/run-odf.sh
Labels: size/L

#7544 change default sc to thin-ci in vsphere for release branch 4.12
  ocs_ci/deployment/vmware.py
Labels: team/ecosystem, size/XS

#7267 Verify defult storageclassclaims in MS consumer
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S, Managed Services

#7493 Remove workaround of scaling down the RBD mirror daemon
  ocs_ci/helpers/dr_helpers.py
Labels: Verified, size/S, DR, Squad/Turquoise
