Repository red-hat-storage/ocs-ci, pull requests merged in 2023-02, with the labels that each got.

#7030 Update ACM to latest image
  conf/examples/acm_hub_unreleased_image.yaml
  ocs_ci/framework/conf/default_config.yaml
Labels: team/ecosystem, size/XS, DR

#6850 Add memory monitoring for process/subprocesses
  .functional_ci_setup.py
  conf/README.md
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/framework/pytest_customization/reports.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/memory.py
  ocs_ci/utility/utils.py
  setup.py
Labels: Verified, size/L

#7008 Fix #6953 test_node_maintenence. Add wait ceph plugin provisioner ready
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: bug, Verified, size/S

#6780 Backlog automation for bz-2096414
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/ui/views.py
  tests/ui/test_validation_ui.py
Labels: Verified, size/L, ui_automation, product-bug, Automation Backlog

#7027 delete rbd images from external RHCS cluster after cluster teardown
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/M

#7039 Fix pd.DataFrame call in teardown
  ocs_ci/utility/utils.py
Labels: size/XS

#7034 Verify MS provider topology based on version
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S, Managed Services

#7038 Update project version to 4.12
  setup.py
Labels: team/ecosystem, size/XS

#7035 Increase must gather timeout on ODF4.10
  ocs_ci/ocs/utils.py
Labels: size/XS

#7031 Add documentation around release branches
  docs/release_guidelines.md
Labels: documentation, team/ecosystem, size/L

#7033 Added collect_memory_usage.yaml
  conf/ocsci/collect_memory_usage.yaml
Labels: size/XS

#6990 Remove SYS_ADMIN capability for fedora DC workload to comply with pod security profiles
  ocs_ci/helpers/helpers.py
Labels: Verified, size/XS

#6884 test_encrypted_rbd_block_pvc_snapshot I/O enhancement
  tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_snapshot.py
Labels: Verified, size/XS, Squad/Green

#7013 Skipping s3cli pod from respin in test_toleration.py
  tests/manage/z_cluster/nodes/test_toleration.py
Labels: size/XS, Squad/Brown

#7032 Create BareMetal cluster with user provided cluster_name
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/aws.py
Labels: Verified, size/L

#6962 Skip ceph daemon tests on external mode
  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_deletion_and_io.py
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Labels: Verified, team/manage, size/M, Squad/Green

#6905 Increase timeout for PVC clone
  tests/conftest.py
Labels: Verified, team/manage, size/XS, Squad/Green

#7023 [RDR] Updated failover procedure to include the WA for Bug 2007376
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/S

#7026 Skipping test cases that are not relevant for external mode cluster
  tests/manage/z_cluster/cluster_expansion/test_delete_pod.py
  tests/manage/z_cluster/test_restart_mgr_while_two_mons_down.py
Labels: size/XS

#7028 Defaulting ocs-ci to ODF 4.13
  ocs_ci/framework/conf/default_config.yaml
  setup.py
Labels: Verified, team/ecosystem, size/S

#7041 Workaround for the bug 2166900
  ocs_ci/deployment/rosa.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/S, Managed Services

#6499 Bug 2110504 List large number of objects with prefix and delimeter
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/backingstore.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/templates/mcg/scale-cli-service-ca-configmap.yaml
  ocs_ci/templates/mcg/scalecli_pod.yaml
  tests/conftest.py
  tests/e2e/scale/noobaa/test_list_objects.py
Labels: team/e2e, size/L, MCG, Customer defects

#7057 Update osd cpu and memory check in MS
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/helpers/managed_services.py
Labels: size/XS

#7061 Skip tests in MS
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: size/XS, Managed Services

#7068 Fixing mem table issue which was failing to send email reports
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/XS

#7059 updated RHCOS template for 4.12
  ocs_ci/framework/conf/ocp_version/ocp-4.12-config.yaml
Labels: Verified, team/ecosystem, size/XS

#7076 Fixing mem table issue which was failing to send email reports
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/XS

#7077 Fixing mem table issue which was failing to send email reports
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/XS

#7078 Fixing mem table issue which was failing to send email reports
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/XS

#7072 Fixing mem table issue which was failing to send email reports
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/XS

#6882 Validation for BZ-2132270
  tests/e2e/workloads/app/test_jenkins_simulation.py
Labels: Verified, team/e2e, size/S, Customer defects

#7056 Enable multi-cidr deployment using config
  conf/deployment/rosa/custom_primary_cidr_config.yaml
  conf/deployment/rosa/custom_secondary_cidr1_config.yaml
  conf/deployment/rosa/custom_secondary_cidr2_config.yaml
  conf/deployment/rosa/private_link_deployment.yaml
  ocs_ci/deployment/rosa.py
  ocs_ci/utility/rosa.py
Labels: Verified, Needs Deployment Testing, size/M, Managed Services

#7089 Increase timeout waiting for pod to reach running in test test_resource_deletion_during_pvc_pod_creation_and_io
  tests/manage/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
Labels: size/XS

#7062 Fix LSO UI deployment
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/deployment_ui.py
Labels: size/S

#7097 remove RHCOS compute IP's from load balancer in RHEL deployments
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/load_balancer.py
Labels: Verified, team/ecosystem, size/S

#7019 Switch to the default cluster index at the "create_scale_pods_and_pvcs_using_kube_job_on_ms_consumers" fixture finalizer
  ocs_ci/utility/decorators.py
  tests/conftest.py
Labels: Verified, size/S, Managed Services

#7021 Fixing OBC bound list count mismatch
  ocs_ci/ocs/scale_noobaa_lib.py
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_obc.py
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_rgw_obc.py
Labels: size/M

#7043 Fix test nodes restart for MS
  tests/manage/z_cluster/nodes/test_nodes_restart_ms.py
Labels: Verified, size/M, Managed Services

#7103 Verify osd distribution on provider
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/M, Managed Services

#6928 PR for verification of bug 2136852
  tests/manage/pv_services/test_pvc_assign_pod_node.py
Labels: Verified, team/e2e, size/M, Customer defects

#7104 Generate nodes for provider cluster in the test "test_rolling_shutdown_and_recovery_in_controlled_fashion"
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/nodes/test_rolling_shutdown_and_recovery_ms.py
Labels: Verified, size/M, Managed Services

#7120 Skip the testcase test_nodereplacement_twice in MS
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: size/XS, Managed Services

#7111 test_obc_creation_and_deletion fix
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
  tests/manage/mcg/ui/test_mcg_ui.py
Labels: Verified, size/L, Automation Backlog

#7107 Update Azure machineset yaml and libraries for scale tests
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/scale_lib.py
  ocs_ci/templates/openshift-infra/machineset-azure.yaml
Labels: Verified, size/S, scale

#7124 Skiping the logging upgrade tyestcase due to changes in upgrade process
  tests/ecosystem/upgrade/test_logging_upgrade.py
Labels: team/e2e, size/XS, Squad/Magenta

#7123 Skiping the logging upgrade testcase due to changes in upgrade process
  tests/ecosystem/upgrade/test_logging_upgrade.py
Labels: size/XS, Squad/Magenta

#7126 Skiping the logging upgrade tyestcase due to changes in upgrade process
  tests/ecosystem/upgrade/test_logging_upgrade.py
Labels: size/XS

#7131 Skip the test 'test_check_pods_status_after_node_failure' when using MS
  tests/manage/z_cluster/nodes/test_check_pods_status_after_node_failure.py
Labels: size/XS, Managed Services

#7109 Verify OCS version in test test_pvc_assign_pod_node
  tests/manage/pv_services/test_pvc_assign_pod_node.py
Labels: Verified, size/S, Squad/Green

#7135 Fix teardown issue in Scale POD OOM KILL Test case
  tests/e2e/scale/test_pods_are_not_oomkilled_while_running_ios.py
Labels: size/XS, scale

#7087 Remove unsupported ocp/ocs version config files
  ocs_ci/framework/conf/ocp_version/ocp-4.2-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.2-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.2-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.3-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.3-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.3-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.3-ga-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.3-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.4-candidate-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.4-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.4-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.4-ga-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.4-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.5-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.5-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.5-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.5-ga-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.5-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.6-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.6-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.6-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.6-ga-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.6-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.7-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.7-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.7-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.7-ga-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.7-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.8-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.8-ga-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.8-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.9-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.9-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.9-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.9-ga-upgrade.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.9-upgrade.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.2.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.3.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.4.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.5.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.6-eus.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.6.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.7-eus.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.7.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.8-eus.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.8.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.9.yaml
  ocs_ci/framework/main.py
Labels: team/ecosystem, size/XL

#7127 Skiping the logging upgrade tyestcase due to changes in upgrade process
  tests/ecosystem/upgrade/test_logging_upgrade.py
Labels: size/XS

#6975 AWS cleanup via aws-cleanup
  ocs_ci/cleanup/aws/cleanup.py
Labels: Verified, size/M

#7144 In the function "wait_for_silence_ceph_osd_crash_warning" change the exception from "TimeoutError" to "TimeoutExpiredError"
  ocs_ci/ocs/cluster.py
Labels: Verified, size/XS, Squad/Brown

#7153 Fix verify_provider_topology
  ocs_ci/helpers/managed_services.py
Labels: Verified, size/XS, Managed Services

#7151 Change to thin-csi from OCP 4.13
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/XS

#6954 Change pod.py::cal_md5sum to use oc exec instead of oc rsh
  ocs_ci/ocs/resources/pod.py
Labels: High Priority, size/XS, MCG, Squad/Red

#7122 skip ui tests for IBM cloud deployment. Authorization to console not …
  ocs_ci/framework/pytest_customization/marks.py
  tests/ui/test_non_admin_user.py
  tests/ui/test_validation_ui.py
Labels: bug, Verified, size/S, Squad/Black

#7082 replaced rsh to tool-pod with get_osd_pods
  tests/manage/monitoring/conftest.py
Labels: Verified, size/S, Squad/Blue

#7165 Add cluster to install config for vsphere UPI
  ocs_ci/templates/ocp-deployment/install-config-vsphere-upi.yaml.j2
Labels: size/XS

#7139 Reducing number of files
  tests/e2e/performance/csi_tests/test_pvc_clone_performance.py
Labels: size/S, performance

#6891 [Automate bug 2024870] Honor 'fsGroupChangePolicy: OnRootMismatch' scc setting on deployments are scaled down / up
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/templates/app-pods/simple-app.yaml
  tests/conftest.py
  tests/manage/z_cluster/test_custom_scc.py
  tests/manage/z_cluster/test_scc.py
Labels: Verified, team/e2e, size/L, Customer defects

#7164 Changes for disconnected ODF 4.13 deployment
  ocs_ci/ocs/constants.py
Labels: team/ecosystem, size/XS
