Repository red-hat-storage/ocs-ci, pull requests merged in 2023-09, with the labels that each got.

#8197 Adding new test and template for the pvc to check rox access mode
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/app-pods/csi-cephfs-rox.yaml
  tests/manage/pv_services/pvc_clone/test_pvc_to_pvc_clone.py
Labels: Verified, size/L

#8384 Ignore the post-validation storagecluster version keyError when using MS
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, workaround, size/S, Managed Services

#8343 In the test "rolling_terminate_and_recovery_of_ocs_worker_nodes" with AWS and vSphere IPI delete the machine associated with the terminated worker node
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/nodes/test_rolling_terminate_and_recovery.py
Labels: Verified, size/M, Squad/Brown

#8366 Disconnected cluster related fixes for various tests
  ocs_ci/deployment/disconnected.py
  ocs_ci/ocs/amq.py
  ocs_ci/ocs/benchmark_operator.py
  ocs_ci/ocs/benchmark_operator_fio.py
  ocs_ci/ocs/pgsql.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/scale_pgsql.py
  ocs_ci/utility/utils.py
  tests/manage/z_cluster/test_scc.py
Labels: Verified, team/ecosystem, size/M

#8365 handled 'AttributeError'NoneType' object has no attribute 'get'' exce…
  tests/conftest.py
Labels: Verified, size/XS

#8362 Enable external mode using SSL with RGW - backport of PR#7645 to release-4.12
  conf/README.md
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/utility/ssl_certs.py
Labels: Verified, team/ecosystem, size/L

#8373 Text formatting test_quickstart_presence
  tests/ui/test_quickstarts.py
Labels: Verified, size/XS, Squad/Black

#8182 add a tests to try delete rbd reffered by sc
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/ui/page_objects/block_pools.py
  ocs_ci/ocs/ui/page_objects/object_bucket_claims_tab.py
  ocs_ci/ocs/ui/page_objects/page_navigator.py
  ocs_ci/ocs/ui/page_objects/searchbar.py
  ocs_ci/ocs/ui/views.py
  tests/conftest.py
  tests/manage/storageclass/test_delete_rbd_pool_attached_to_sc.py
Labels: size/L, ui_automation

#8139 Test_ceph_osd_low_ops_alert backport 4.13
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/fiojob.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/monitoring/test_workload_with_distruptions.py
Labels: Verified, size/L

#8378 use appropriate installer release
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/XS

#8375 Fixing test_node_replacement tests for Vmware IPI platforms
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Verified, size/XS, Squad/Brown

#8388 Revert "BZ #2096395 automation. (#6836)" in 4.11
  tests/e2e/workloads/app/test_jenkins_simulation.py
Labels: team/e2e, size/M, Squad/Magenta

#8404 Exclude the pods with the prefix name of 'report-status-to-provider' in the leftovers check
  ocs_ci/ocs/constants.py
  ocs_ci/utility/environment_check.py
Labels: Verified, size/XS, Managed Services

#8235 Adjust `namespace_bucket_update` to the new schema
  ocs_ci/ocs/bucket_utils.py
  tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
Labels: Medium Priority, Verified, size/M, MCG, Squad/Red

#8416 Add missing networktype for vsphere ipi
  ocs_ci/templates/ocp-deployment/install-config-vsphere-ipi.yaml.j2
Labels: Verified, size/XS

#8406 bz mark is stale.
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
Labels: Verified, size/XS

#8400 cherry-pick fix_couchbase 4.12
  ocs_ci/ocs/couchbase.py
  tests/e2e/workloads/app/couchbase/test_couchbase.py
  tests/e2e/workloads/app/couchbase/test_couchbase_node_drain.py
  tests/e2e/workloads/app/couchbase/test_couchbase_node_reboot.py
  tests/e2e/workloads/app/couchbase/test_couchbase_pod_respin.py
Labels: team/e2e, size/S, Squad/Magenta

#8411 remove ceph crashes after upgrade
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/M, upgrade

#8432 bz mark is stale -to remove
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
Labels: size/XS, cherry-pick

#8436 Aro deployment release 4.12
  conf/deployment/azure/managed_aro_3az_rhcos_3m_3w.yaml
  ocs_ci/deployment/azure.py
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/factory.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/monitoring.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/ui/views.py
  ocs_ci/utility/azure_utils.py
  ocs_ci/utility/ssl_certs.py
  ocs_ci/utility/utils.py
  tests/ecosystem/deployment/test_deployment.py
Labels: team/ecosystem, size/XL, cherry-pick

#8414 Adding a new test case for test_auto_reclaim_space_cronjob.py test
  tests/manage/pv_services/space_reclaim/test_auto_reclaim_space_cronjob.py
Labels: Verified, size/M

#8353 Adding MDR appset tests
  conf/ocsci/mdr_workload.yaml
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/dr/dr_workload.py
  tests/disaster-recovery/mdr/test_app_failover_and_relocate.py
Labels: Verified, size/L, DR

#8392 cherry-pick Validate pv deletion in teardown (#7266) 4.11
  ocs_ci/ocs/pgsql.py
Labels: team/e2e, size/S, Squad/Magenta

#8441 Change the method 'is_node_rack_or_zone_exist' to get the node name instead of the node object 4.12 #8344
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
Labels: Verified, size/L, Squad/Brown

#8438 Fix test_odf_storagesystems_ui
  ocs_ci/ocs/ui/page_objects/storage_system_details.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/S, Squad/Black

#8361 Updating ocs_ci/templates/app-pods/esclient.yaml to address security context issues
  ocs_ci/templates/app-pods/esclient.yaml
Labels: Verified, size/S, scale

#8448 Aro deployment release 4.11
  conf/deployment/azure/managed_aro_3az_rhcos_3m_3w.yaml
  ocs_ci/deployment/azure.py
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/factory.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/monitoring.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/ui/views.py
  ocs_ci/utility/azure_utils.py
  ocs_ci/utility/ssl_certs.py
  ocs_ci/utility/utils.py
  tests/ecosystem/deployment/test_deployment.py
Labels: Verified, team/ecosystem, size/XL, cherry-pick

#8430 bz mark is stale -to remove
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
Labels: Verified, size/XS, Squad/Blue, cherry-pick

#8429 bz mark is stale -to remove
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
Labels: Verified, size/XS, Squad/Blue, cherry-pick

#8443 In case of high skip rate due to Ceph health not OK - Report test case and squad causing that
  ocs_ci/framework/conf/default_config.yaml
  tests/conftest.py
  tests/test_failure_propagator.py
Labels: Verified, size/L

#8405 test_ceph_csidriver_runs_on_non_ocs_nodes: remove from tier1
  tests/manage/z_cluster/cluster_expansion/test_verify_ceph_csidriver_runs_on_non_ocs_nodes.py
Labels: size/XS, Squad/Brown

#8470 PDB changes for arbiter deployment
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem

#7947 Edit multiple Red Squad tests' decorators
  tests/manage/mcg/test_admission_control.py
  tests/manage/mcg/test_mcg_resources_disruptions.py
  tests/manage/mcg/test_object_integrity.py
  tests/manage/mcg/test_pv_pool.py
  tests/manage/mcg/test_s3_routes.py
Labels: High Priority, size/S, MCG, Squad/Red

#8408 Cherry Pick PR 4.13: Fixing test_node_replacement tests for Vmware IPI platforms (#8375)
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Verified, size/XS, Squad/Brown

#8423 Run the consumers verification steps if we use the ocs-provider-server service type 'NodePort' on Provider
  ocs_ci/ocs/managedservice.py
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_ms.py
Labels: Verified, size/M, Managed Services

#8434 Exclude checking the pod statuses with the name prefix "report-status-to-provider-"
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/nodes/test_rolling_terminate_and_recovery.py
Labels: Verified, size/M, Squad/Brown, Managed Services

#8391 test_dashboard_validation_ui rework. added acceptance mark
  ocs_ci/framework/logger_helper.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/page_objects/backing_store_tab.py
  ocs_ci/ocs/ui/page_objects/bucket_class_tab.py
  ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
  ocs_ci/ocs/ui/page_objects/namespace_store_tab.py
  ocs_ci/ocs/ui/page_objects/object_bucket_claims_tab.py
  ocs_ci/ocs/ui/page_objects/object_service.py
  ocs_ci/ocs/ui/page_objects/overview_tab.py
  ocs_ci/ocs/ui/page_objects/resource_list.py
  ocs_ci/ocs/ui/page_objects/searchbar.py
  ocs_ci/ocs/ui/page_objects/storage_system_details.py
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/ui/views.py
  tests/ui/test_validation_ui.py
Labels: Verified, size/XL, ui_automation, Squad/Black

#8383 Test stop start node validate topology fix
  ocs_ci/ocs/platform_nodes.py
  tests/ui/test_odf_topology.py
Labels: Verified, size/XS, Squad/Black

#8393 fix locator for skip_tour
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/XS, Squad/Black

#8433 adjust provider id
  ocs_ci/ocs/ui/odf_topology.py
  tests/ui/test_odf_topology.py
Labels: Verified, TestCase failing, size/XS, ui_automation, Squad/Black

#8449 UI Deployment, add a new step 'Data Protection'
  ocs_ci/ocs/ui/deployment_ui.py
Labels: Verified, size/S

#8497 Backporting missing parts from #7579
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/azure_utils.py
  setup.py
Labels: Verified, team/ecosystem, size/M, cherry-pick

#8496 Backporting missing parts from #7579
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/azure_utils.py
  setup.py
Labels: Verified, team/ecosystem, size/M, cherry-pick

#8507 Ignore aro cluster operator in OCP upgrade
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: team/ecosystem, size/XS

#8510 Ignore aro cluster operator in OCP upgrade
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Verified, team/ecosystem, size/XS, cherry-pick

#8509 Ignore aro cluster operator in OCP upgrade
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: team/ecosystem, size/XS, cherry-pick

#8511 Ignore aro cluster operator in OCP upgrade
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Verified, team/ecosystem, size/XS, cherry-pick

#8513 Increase number of attempts for ARO cluster ssl ready
  ocs_ci/utility/azure_utils.py
Labels: team/ecosystem, size/XS, cherry-pick

#8514 Increase number of attempts for ARO cluster ssl ready
  ocs_ci/utility/azure_utils.py
Labels: team/ecosystem, size/XS, cherry-pick

#8515 Increase number of attempts for ARO cluster ssl ready
  ocs_ci/utility/azure_utils.py
Labels: team/ecosystem, cherry-pick

#8516 Increase number of attempts for ARO cluster ssl ready
  ocs_ci/utility/azure_utils.py
Labels: team/ecosystem, size/XS

#8480 Enhance destroy of MS clusters to avoid failures
  ocs_ci/deployment/rosa.py
  ocs_ci/utility/rosa.py
Labels: Verified, team/ecosystem, size/M

#8499 Get the pagerduty service id of the default cluster if we use multicluster run
  tests/manage/monitoring/pagerduty/test_deployment_status.py
Labels: Verified, size/S, Managed Services, lgtm

#8520 fix wrong PRs merging
  ocs_ci/ocs/ui/views.py
Labels: size/XS, lgtm

#8521 Skip the test "test_toleration" when using MS
  tests/manage/z_cluster/nodes/test_toleration.py
Labels: size/XS, Squad/Brown, Managed Services, lgtm

#8500 use threading.lock, use Timer in measure_operation
  ocs_ci/utility/prometheus.py
  ocs_ci/utility/workloadfixture.py
  tests/manage/monitoring/conftest.py
Labels: Verified, TestCase failing, size/L, lgtm

#8506 Adjust the ROOK_CEPH_CONFIG_VALUES for 4.14, issue#8505
  ocs_ci/ocs/constants.py
  tests/manage/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/S, lgtm

#8484 A new performance test - tests/e2e/performance/csi_tests/test_auto_reclaim_space_multi_clones.py
  ocs_ci/helpers/performance_lib.py
  tests/e2e/performance/csi_tests/test_auto_reclaim_space_multi_clones.py
  tests/manage/pv_services/space_reclaim/test_auto_reclaim_space_cronjob.py
Labels: size/L, performance, lgtm

#8403 `test_log_based_bucket_replication.py` Change logs-dir and improve the test's performance
  ocs_ci/ocs/resources/mockup_bucket_logger.py
Labels: High Priority, Verified, size/S, MCG, Squad/Red, lgtm

#8459 BM deployment: use config.AUTH instead of load_auth_config
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/baremetal.py
Labels: Verified, team/ecosystem, size/S

#8431 bz mark is stale -to remove
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
Labels: size/XS, Squad/Blue, lgtm, cherry-pick

#8491 BM deployment: use config.AUTH instead of load_auth_config - backport for 4.10
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/baremetal.py
Labels: team/ecosystem, size/S, lgtm, cherry-pick

#8490 BM deployment: use config.AUTH instead of load_auth_config - backport for 4.11
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/baremetal.py
Labels: team/ecosystem, size/S, lgtm, cherry-pick

#8489 BM deployment: use config.AUTH instead of load_auth_config - backport for 4.12
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/baremetal.py
Labels: team/ecosystem, size/S, lgtm, cherry-pick

#8539 Fix the test "test_pvc_to_pvc_rox_clone" when using MS consumer cluster
  tests/conftest.py
Labels: Verified, size/XS, Managed Services, lgtm

#8532 Skip test_mon_crash_recovery_scenario
  tests/e2e/kcs/test_mon_crash_recovery_scenario.py
Labels: team/e2e, size/XS, Squad/Magenta, lgtm

#8555 fix squad assignment for manage/rgw tests
  tests/manage/rgw/test_bucket_creation.py
  tests/manage/rgw/test_bucket_deletion.py
  tests/manage/rgw/test_host_node_failure.py
  tests/manage/rgw/test_multipart_upload.py
  tests/manage/rgw/test_obc_quota.py
  tests/manage/rgw/test_object_bucket_size.py
  tests/manage/rgw/test_object_integrity.py
  tests/manage/rgw/test_rgw_pod_existence.py
Labels: Verified, team/ecosystem, size/S, lgtm

#8556 Squad validation on collectonly
  tests/conftest.py
Labels: Verified, team/ecosystem, size/L, lgtm

#8522 Add additional check of api clusterOperator after cert change
  ocs_ci/ocs/constants.py
  ocs_ci/utility/ssl_certs.py
Labels: team/ecosystem, size/S, lgtm

#8325 Add Polarion ID for Appset Workload test
  tests/disaster-recovery/regional-dr/test_failover_and_relocate.py
Labels: size/S, DR

#8402 cherry-pick jenkins_failure 4.11
  ocs_ci/ocs/jenkins.py
  ocs_ci/templates/workloads/jenkins/buildconfig.yaml
Labels: team/e2e, size/M, Squad/Magenta, lgtm

#8474 [4.10] ClusterLoad: Replace DeploymentConfig with Deployment
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/cluster_load.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/workloads/fio/fedora_deployment.yaml
  tests/conftest.py
Labels: Verified, size/L, lgtm

#8473 [4.11] ClusterLoad: Replace DeploymentConfig with Deployment
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/cluster_load.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/workloads/fio/fedora_deployment.yaml
  tests/conftest.py
Labels: Verified, size/L, lgtm

#8472 [4.12] ClusterLoad: Replace DeploymentConfig with Deployment
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/cluster_load.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/workloads/fio/fedora_deployment.yaml
  tests/conftest.py
Labels: Verified, size/L, lgtm

#8471 [4.13] ClusterLoad: Replace FIO DeploymentConfig with Deployment
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/cluster_load.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/workloads/fio/fedora_deployment.yaml
  tests/conftest.py
Labels: Verified, size/L, lgtm

#8541 [4.13]: Run mdr tests only in case of mdrconfig release 4.13
  ocs_ci/ocs/constants.py
  tests/disaster-recovery/mdr/__init__.py
  tests/disaster-recovery/mdr/conftest.py
Labels: team/ecosystem, size/S, lgtm, cherry-pick

#8512 Extended workload run time for noobaa endpoint
  tests/manage/mcg/test_endpoint_autoscale.py
Labels: Needs Testing, size/XS, MCG, Squad/Red, lgtm

#8498 [release-4.12 backport] Update the RPC payload at `test_buckets_before_upgrade`
  tests/ecosystem/upgrade/conftest.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm, MCG-4.12

#8477 `test_public_website`: Use `s3_get_object` with `retry`
  tests/manage/mcg/test_bucket_policy.py
Labels: Verified, size/S, MCG, Squad/Red, backport-required

#8481 A few improvements for skips Ceph health reporting
  conf/README.md
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/utility/reporting.py
  ocs_ci/utility/utils.py
  tests/test_failure_propagator.py
Labels: Verified, size/M, lgtm

#8407 Add minimal deployment for IBM Cloud
  conf/deployment/ibmcloud/ipi_3az_rhcos_lowerreq_3m_3w.yaml
Labels: Verified, size/S, lgtm

#8415 Change name of noobaa hpa in metrics test
  tests/manage/monitoring/prometheusmetrics/test_mcg_hpa.py
Labels: Verified, size/S, Squad/Blue, lgtm

#8281 [release-4.11 backport] Choose to use only the MCG-CLI for RPC calls elsewhere
  ocs_ci/ocs/resources/mcg.py
  tests/manage/mcg/test_nb_mgmt_endpoint.py
Labels: High Priority, size/M, MCG, Squad/Red, lgtm, cherry-pick

#8533 Enable bluestore for osds in case of RDR greenfield deployments
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/M, lgtm, DR

#8585 Fix typo in bluestore-rdr failure message
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/XS, lgtm, DR

#8355 In the test "test_add_capacity_node_restart" restart the nodes without waiting for the Reboot event when using vSphere IPI 4.13 #8076
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
Labels: Verified, size/S, Squad/Brown, lgtm

#8425 [release-4.13 backport] Adjust `namespace_bucket_update` to the new schema
  ocs_ci/ocs/bucket_utils.py
  tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
Labels: Verified, size/M, MCG, lgtm

#5946 Check for correct pool name on ms cluster
  ocs_ci/ocs/fiojob.py
Labels: Verified, size/S, Managed Services, lgtm

#6133 Introduce new top level test directory modules
  tests/README.md
  tests/cross_functional/README.md
  tests/functional/README.md
  tests/libtest/README.md
Labels: enhancement, documentation, team/ecosystem, size/M

#8348 Adding OCP 4.15 config files
  ocs_ci/framework/conf/ocp_version/ocp-4.15-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.15-upgrade.yaml
Labels: Verified, team/ecosystem, size/S, lgtm

#8563 Fixed in-transit encryption tests failure.
  ocs_ci/ocs/resources/storage_cluster.py
  tests/conftest.py
  tests/encryption/test_intransit_encryption_sanity.py
Labels: Verified, size/M, lgtm

#8493 [release-4-12 backport] Disregard the users array of noobaa-db SCC at test_db_scc
  tests/manage/mcg/test_mcg_resources_disruptions.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm, MCG-4.12

#8564 Fixed in-transit encryption tests failure for external mode cluster
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S, lgtm

#8579 [release-4.13] Ceph health skip reporting
  conf/README.md
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/utility/reporting.py
  ocs_ci/utility/utils.py
  tests/conftest.py
  tests/test_failure_propagator.py
Labels: Verified, size/L, lgtm, cherry-pick

#8580 [release-4.12] Ceph health skip reporting
  conf/README.md
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/utility/reporting.py
  ocs_ci/utility/utils.py
  tests/conftest.py
  tests/test_failure_propagator.py
Labels: Verified, size/L, lgtm, cherry-pick

#8582 [release-4.11] Ceph health skip reporting
  conf/README.md
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/utility/reporting.py
  ocs_ci/utility/utils.py
  tests/conftest.py
  tests/test_failure_propagator.py
Labels: Verified, size/L, lgtm, cherry-pick

#8583 [release-4.10] Ceph health skip reporting
  conf/README.md
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/utility/reporting.py
  ocs_ci/utility/utils.py
  tests/conftest.py
  tests/test_failure_propagator.py
Labels: Verified, size/L, lgtm, cherry-pick

#8592 Fix obc ui test leftovers
  ocs_ci/ocs/ui/page_objects/object_bucket_claims_tab.py
  tests/ui/test_non_admin_user.py
Labels: Verified, size/M, lgtm, Squad/Black

#8329 Fix failure to clear field
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/pvc_ui.py
Labels: Verified, size/S, lgtm, Squad/Black
