Repository red-hat-storage/ocs-ci, pull requests merged in 2023-08, with the labels that each got.

#8047 Fix TypeError when calling install_submariner_ui and submariner_validation_ui
  ocs_ci/ocs/acm/acm.py
Labels: Verified, size/S, lgtm, DR

#8054 Add Polarion ID for RDR node failure tests
  tests/disaster-recovery/regional-dr/test_managed_cluster_node_failure.py
Labels: size/M, lgtm

#7996 test if nb db successfully initializes after nfs mount
  conf/README.md
  tests/manage/mcg/test_db_nfs_mount.py
Labels: Verified, team/e2e, size/L, MCG, Customer defects, Squad/Red, lgtm

#8110 Extract the pull-secret and place it under /data dir
  ocs_ci/ocs/resources/mcg.py
Labels: Verified, size/S, MCG, Squad/Red

#8100 change flexy_template for vsphere discon. depl.
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_disconnected.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w_disconnected.yaml
  ocs_ci/deployment/flexy.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#8113 Disconnected ODF deployment: apply icsp rules when mirroring images - backport for 4.13
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/disconnected.py
  ocs_ci/utility/deployment.py
Labels: Verified, team/ecosystem, size/L, cherry-pick

#8148 change flexy_template for vsphere disconnected deployment - backport for 4.13
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_disconnected.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w_disconnected.yaml
  ocs_ci/deployment/flexy.py
Labels: team/ecosystem, size/XS, lgtm, cherry-pick

#8162 skip test_create_scale_pods_and_pvcs_using_kube_job on baremetal
  tests/e2e/workloads/test_create_scale_pods_and_pvcs_using_kube_job.py
Labels: team/e2e, size/XS, Squad/Magenta

#8149 change flexy_template for vsphere disconnected deployment - backport for 4.12
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_disconnected.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w_disconnected.yaml
  ocs_ci/deployment/flexy.py
Labels: Verified, team/ecosystem, size/XS, lgtm, cherry-pick

#8164 Enable chmod +x of /test_objects of the s3cli pod
  ocs_ci/templates/mcg/s3cli-sts.yaml
  tests/conftest.py
  tests/manage/mcg/test_write_to_bucket.py
Labels: High Priority, Verified, size/XS, MCG, Squad/Red, MCG-4.14

#8136 delete custom sc backed pvc's during teardown
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/XS, cherry-pick

#8159 Increase timeout for volume deletion in backend
  tests/manage/pv_services/test_daemon_kill_during_pvc_pod_creation_deletion_and_io.py
Labels: team/manage, Squad/Green

#8089 cherry-pick remove redundant param use_shell from exec_cmd
  ocs_ci/ocs/rados_utils.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/utility/utils.py
Labels: Verified, size/S

#8150 change flexy_template for vsphere disconnected deployment - backport for 4.11
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_disconnected.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w_disconnected.yaml
  ocs_ci/deployment/flexy.py
Labels: Verified, team/ecosystem, size/XS, lgtm, cherry-pick

#8175 s3cli-sts: runAsUser 0 with image 2.0
  ocs_ci/templates/mcg/s3cli-sts.yaml
  tests/conftest.py
Labels: Verified, size/XS, MCG, Squad/Red, MCG-4.14

#8172 [4.13]: Add squad for disaster recovery
  ocs_ci/ocs/constants.py
Labels: team/ecosystem, cherry-pick

#8166 ignore oc mirror command failure if icsp is used
  ocs_ci/deployment/disconnected.py
Labels: Verified, team/ecosystem, size/S

#8169 ignore oc mirror command failure if icsp is used - backport for 4.12
  ocs_ci/deployment/disconnected.py
Labels: Verified, team/ecosystem, size/S, cherry-pick

#8170 ignore oc mirror command failure if icsp is used - backport for 4.13
  ocs_ci/deployment/disconnected.py
Labels: Verified, team/ecosystem, size/S, cherry-pick

#8151 change flexy_template for vsphere disconnected deployment - backport for 4.10
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_disconnected.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w_disconnected.yaml
  ocs_ci/deployment/flexy.py
Labels: Verified, team/ecosystem, size/XS, cherry-pick

#7994 KCS automation: ODF mon daemon crash scenario
  tests/e2e/kcs/test_mon_crash_recovery_scenario.py
Labels: Verified, team/e2e, size/L, Customer defects, lgtm

#7511 Selinux-relabel solution
  ocs_ci/ocs/constants.py
  ocs_ci/templates/app-pods/performance_dc.yaml
  tests/e2e/kcs/test_selinux_relabel_solution.py
Labels: team/e2e, size/L

#7917 Test automation of mon failure scenarios with intransit encryption.
  tests/encryption/test_mon_failure_in_intransit_encryption.py
Labels: Verified, size/L

#8119 verify disks marked as ssd for internal deployment
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/M

#8179 [Release 4.13 cherry-pick] Added multi_client=False to the run_benchmark function of warp (#7967)
  ocs_ci/ocs/warp.py
  tests/e2e/scale/noobaa/test_warp.py
Labels: size/S, scale, cherry-pick

#8074 Update the RPC payload at `test_buckets_before_upgrade`
  tests/ecosystem/upgrade/conftest.py
Labels: High Priority, Verified, size/S, MCG, Squad/Red

#8181 Download the mcg-cli if the current binary has a different minor version than OCS
  ocs_ci/ocs/resources/mcg.py
Labels: High Priority, Verified, size/L, MCG, Squad/Red, MCG-4.14

#8196 chnage vmc7 proxy repo
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_proxy.yaml
Labels: Verified, team/ecosystem

#7981 [GSS closed loop] BZ-2182943 FSGroup is not correctly set on subPath volume for CephFS CSI
  ocs_ci/helpers/helpers.py
  tests/manage/pv_services/test_cephfs_pvc_with_necessary_scc_permissions.py
Labels: size/L

#8202 [4.13]: fix repo http proxy
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_proxy.yaml
Labels: team/ecosystem, size/XS, cherry-pick

#8201 [4.12]: chnage vmc7 proxy repo
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_proxy.yaml
Labels: team/ecosystem, size/XS, cherry-pick

#8200 [4.11]: chnage vmc7 proxy repo
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_proxy.yaml
Labels: team/ecosystem, size/XS, cherry-pick

#8199 [4.10]: chnage vmc7 proxy repo
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_proxy.yaml
Labels: team/ecosystem, size/XS, cherry-pick

#8145 [4.10] - get correct pool name for external mode in fiojob
  ocs_ci/ocs/fiojob.py
Labels: Verified, team/ecosystem, size/XS

#8143 [4.12] - get correct pool name for external mode in fiojob
  ocs_ci/ocs/fiojob.py
Labels: Verified, team/ecosystem, size/XS

#8144 [4.11] - get correct pool name for external mode in fiojob
  ocs_ci/ocs/fiojob.py
Labels: Verified, team/ecosystem

#8204 Update webdriver_manager to 4.0.0
  setup.py
Labels: Verified, team/ecosystem, size/XS

#8208 Update webdriver_manager to 4.0.0
  setup.py
Labels: team/ecosystem, size/XS, cherry-pick

#8207 Update webdriver_manager to 4.0.0
  setup.py
Labels: team/ecosystem, size/XS, cherry-pick

#8183 cherry-pick Update Bare metal Deployment to Support new Server (#8104)
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/connection.py
Labels: size/M, cherry-pick

#8206 Update webdriver_manager to 4.0.0
  setup.py
Labels: team/ecosystem, size/XS, cherry-pick

#8205 Update webdriver_manager to 4.0.0
  setup.py
Labels: team/ecosystem, size/XS, cherry-pick

#8184 cherry-pick Update Bare metal Deployment to Support new Server
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/connection.py
Labels: size/M, cherry-pick

#8185 cherry-pick Update Bare metal Deployment to Support new Server
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/connection.py
Labels: size/M, cherry-pick

#8186 cherry-pick Update Bare metal Deployment to Support new Server
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/connection.py
Labels: size/M, cherry-pick

#8203 'SeleniumDriver' object has no attribute 'driver' - fix
  ocs_ci/ocs/ui/base_ui.py
Labels: size/XS, ui_automation

#8212 skip application of icsp from ocs-registry on disonnected cluster
  ocs_ci/ocs/ocs_upgrade.py
Labels: Needs Testing, Verified, team/ecosystem, size/XS

#8214 skip application of icsp from ocs-registry on disonnected cluster - backport 4.12
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/XS, cherry-pick

#8215 skip application of icsp from ocs-registry on disonnected cluster - backport 4.11
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/XS, cherry-pick

#8076 In the test "test_add_capacity_node_restart" restart the nodes without waiting for the Reboot event when using vSphere IPI
  tests/manage/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
Labels: Verified, size/S, Squad/Brown

#8178 [Release 4.13 cherry-pick] Fixed issue of test_scale_obc_create_delete_time (#7767)
  ocs_ci/ocs/scale_noobaa_lib.py
  tests/e2e/scale/noobaa/test_scale_obc_create_delete.py
Labels: size/XS, scale, cherry-pick

#8123 [release-4.13 backport] NSFS noobaa-endpoint SCC workaround + Ignore the noobaa-endpoint pods leftovers at `test_nsfs.py`
  ocs_ci/ocs/constants.py
  tests/conftest.py
  tests/manage/mcg/test_nsfs.py
Labels: Verified, size/L, MCG, Squad/Red, MCG-4.13

#8077 Enhance exec_cmd to Include emoji filtering for stderr output
  ocs_ci/utility/utils.py
  tests/libtest/test_stderr_emoji_filter.py
Labels: enhancement, Verified, size/M, MCG

#7884 updated setup teardown method for nfs testclass
  tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Labels: Verified, size/S, Squad/Brown

#7900 Automate bug 2168788
  ocs_ci/ocs/resources/pod.py
  tests/conftest.py
  tests/manage/mcg/test_bucket_replication.py
Labels: Verified, team/e2e, size/L, MCG, Customer defects, Squad/Red

#8222 Disconected deployment: extend time for mirroring images (for 4.10) - cherry-pick for 4.11
  ocs_ci/deployment/disconnected.py
Labels: Verified, size/XS, cherry-pick

#8221 Disconected deployment: extend time for mirroring images (for 4.10)
  ocs_ci/deployment/disconnected.py
Labels: Verified, size/XS, cherry-pick

#8107 Add kubectl and 'make' packages to ocs-ci image
  Docker_files/ocsci_container/Containerfile.ci
Labels: size/XS

#8188 PDB verification
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
Labels: Verified, team/ecosystem, size/S

#8220 patch correct SC when using custom storageclass
  ocs_ci/deployment/deployment.py
Labels: Needs Testing, Verified, team/ecosystem

#7445 [Release-4.10 cherry pick] PR6499 and PR7066
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/backingstore.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/templates/mcg/scale-cli-service-ca-configmap.yaml
  ocs_ci/templates/mcg/scalecli_pod.yaml
  tests/conftest.py
  tests/e2e/scale/noobaa/test_list_objects.py
Labels: Verified, team/e2e, size/L, MCG, Customer defects, Squad/Red

#8223 cherry-pick. SeleniumDriver attribute error fix
  ocs_ci/ocs/ui/base_ui.py
Labels: Verified, size/XS, ui_automation

#8154 Change network interface for multus deployment
  conf/deployment/baremetal/upi_1az_rhcos_multus_cluster_nvme_intel_3m_3w.yaml
  conf/deployment/baremetal/upi_1az_rhcos_multus_nvme_intel_3m_3w.yaml
  conf/deployment/baremetal/upi_1az_rhcos_multus_public_nvme_intel_3m_3w.yaml
Labels: Verified, size/XS

#8236 Cherry Pick PR 7135 to branch release-4.12
  tests/e2e/scale/test_pods_are_not_oomkilled_while_running_ios.py
Labels: Verified, size/XS, scale, cherry-pick

#8237 Cherry Pick PR 7845 to branch release-4.12
  tests/e2e/scale/test_cephfs_many_files.py
Labels: Verified, size/XS, scale, cherry-pick

#8232 Cherry-pick PR 7107 to release-4.12 branch to fix Azure machineset issue
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/scale_lib.py
  ocs_ci/templates/openshift-infra/machineset-azure.yaml
Labels: Verified, size/S, scale, cherry-pick

#8239 Cherry Pick PR 7847 to branch release-4.13
  tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
  tests/e2e/scale/test_pv_scale_ocs_create_delete_pvcs.py
Labels: Verified, size/M, scale, cherry-pick

#8238 Cherry Pick PR 7847 to branch release-4.12
  tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
  tests/e2e/scale/test_pv_scale_ocs_create_delete_pvcs.py
Labels: Verified, size/M, scale, cherry-pick

#8251 make icsp unique to avoid conflict during upgrade
  ocs_ci/utility/deployment.py
Labels: Verified, team/ecosystem, size/XS

#8252 make icsp name unique to avoid conflict during upgrade - backport for 4.13
  ocs_ci/utility/deployment.py
Labels: Verified, team/ecosystem, size/XS, cherry-pick

#8253 make icsp name unique to avoid conflict during upgrade - backport for 4.12
  ocs_ci/utility/deployment.py
Labels: Verified, team/ecosystem, size/XS, cherry-pick

#8254 make icsp name unique to avoid conflict during upgrade - backport for 4.11
  ocs_ci/utility/deployment.py
Labels: Verified, team/ecosystem, size/XS, cherry-pick

#8255 make icsp name unique to avoid conflict during upgrade - backport for 4.10
  ocs_ci/utility/deployment.py
Labels: Verified, team/ecosystem, size/XS, cherry-pick

#8225 [4.13] - add marker for test upgrade sc allowexpansion false
  tests/ecosystem/upgrade/test_upgrade_sc_allowexpansion_false.py
Labels: team/ecosystem

#8245 Adding ODF 4.15 config files
  ocs_ci/framework/conf/ocs_version/ocs-4.15.yaml
  ocs_ci/framework/main.py
Labels: Verified, team/ecosystem

#8230 Fixing incorrect pod count
  ocs_ci/ocs/cluster.py
Labels: Verified, team/ecosystem, size/S

#8147 [MCG] Assert when objects in source & target bucket don't match
  ocs_ci/ocs/bucket_utils.py
  tests/manage/mcg/test_bucket_replication.py
Labels: Verified, size/M, MCG, Squad/Red

#8211 Adding 'green_squad' marker to encryption tests.
  .github/CODEOWNERS
  tests/encryption/test_intransit_encryption_data_integrity.py
  tests/encryption/test_intransit_encryption_sanity.py
  tests/encryption/test_mon_failure_in_intransit_encryption.py
Labels: size/XS

#8259 [release-4.12 backport] Enhance exec_cmd to Include emoji filtering for stderr output
  ocs_ci/utility/utils.py
  tests/libtest/test_stderr_emoji_filter.py
Labels: High Priority, size/M, MCG, Squad/Red, cherry-pick

#8258 [release-4.13 backport] Enhance exec_cmd to Include emoji filtering for stderr output
  ocs_ci/utility/utils.py
  tests/libtest/test_stderr_emoji_filter.py
Labels: High Priority, size/M, MCG, Squad/Red, cherry-pick

#8224 destroy folder in templates in vsphere-cleanup script
  ocs_ci/cleanup/vsphere/cleanup.py
Labels: Verified, team/ecosystem, size/S

#8250 add bugzilla marker to test
  tests/manage/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
Labels: bug, size/XS, Squad/Brown

#7856 block_pool_edit_label_check_added
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/block_pool.py
  ocs_ci/ocs/ui/page_objects/block_pools.py
  ocs_ci/ocs/ui/page_objects/edit_label_form.py
  ocs_ci/ocs/ui/page_objects/page_navigator.py
  ocs_ci/ocs/ui/views.py
  tests/ui/test_error_improvements.py
Labels: size/L, ui_automation, Squad/Black

#8227 Object Storage UI update 4.14
  ocs_ci/ocs/ui/page_objects/backing_store_tab.py
  ocs_ci/ocs/ui/page_objects/bucket_class_tab.py
  ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
  ocs_ci/ocs/ui/page_objects/namespace_store_tab.py
  ocs_ci/ocs/ui/page_objects/object_bucket_claims_tab.py
  ocs_ci/ocs/ui/page_objects/object_buckets_tab.py
  ocs_ci/ocs/ui/page_objects/object_service.py
  ocs_ci/ocs/ui/page_objects/page_navigator.py
  ocs_ci/ocs/ui/views.py
  tests/manage/mcg/ui/test_mcg_ui.py
  tests/ui/test_error_improvements.py
  tests/ui/test_non_admin_user.py
Labels: size/L, ui_automation, Squad/Black

#7875 Choose to use only the MCG-CLI for RPC calls elsewhere
  ocs_ci/ocs/resources/mcg.py
  tests/manage/mcg/test_nb_mgmt_endpoint.py
Labels: size/L, MCG, Squad/Red

#8267 PDB verification skip for external mode
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/XS

#7848 Add allow policies to the MCG user (#7726)
  tests/e2e/lifecycle/mcg/test_mcg_namespace_lifecyle_crd.py
Labels: team/e2e, size/M, Squad/Magenta

#8192 Update logs and docs around the mcg-cli retrieval at mcg.py and add consts
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/mcg.py
Labels: enhancement, Verified, size/S, MCG

#7993 GSS BZ 2158922 Create namespacestore via UI
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/page_objects/object_service.py
  ocs_ci/ocs/ui/page_objects/page_navigator.py
  ocs_ci/ocs/ui/views.py
  tests/manage/mcg/ui/test_namespace_store.py
Labels: Verified, team/e2e, size/L, Customer defects

#8271 Add an S3 readiness check to `ObjectBucket.verify_health`
  ocs_ci/ocs/resources/objectbucket.py
Labels: High Priority, Verified, size/XS, MCG, Squad/Red

#8256 [release-4.13 backport]Download the mcg-cli if the current binary has a different minor version than OCS
  ocs_ci/ocs/resources/mcg.py
Labels: High Priority, Verified, size/L, MCG, Squad/Red, cherry-pick

#7844 Test coverage for log based bucket replication
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/mcg_replication_policy.py
  ocs_ci/ocs/resources/mockup_bucket_logger.py
  ocs_ci/ocs/resources/objectbucket.py
  ocs_ci/templates/mcg/aws-bucket-log-template
  tests/conftest.py
  tests/manage/mcg/test_bucket_replication.py
  tests/manage/mcg/test_log_based_bucket_replication.py
Labels: Verified, size/XL, MCG, Squad/Red, MCG-4.13

#8290 fix mcg-cli download issue
  ocs_ci/ocs/constants.py
Labels: Needs Deployment Testing, team/ecosystem

#8039 revert the workaround of storage cluster version check
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/S

#8283 Fix error with invalid XML character which breaks XML with report
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/M

#8284 Fix error with invalid XML character which breaks XML with report
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/M, cherry-pick

#8302 Fix error with invalid XML character which breaks XML with report
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/M, cherry-pick

#8298 [4.12]: MachineConfigPool skip for IBM Managed cloud
  ocs_ci/utility/deployment.py
Labels: Verified, team/ecosystem, size/XS

#8279 [release-4.13 backport] Choose to use only the MCG-CLI for RPC calls elsewhere
  ocs_ci/ocs/resources/mcg.py
  tests/manage/mcg/test_nb_mgmt_endpoint.py
Labels: High Priority, Verified, size/L, MCG, Squad/Red, cherry-pick

#8292 MachineConfigPool skip for IBM Managed cloud
  ocs_ci/utility/deployment.py
Labels: Needs Testing, team/ecosystem, size/XS

#8174 Jenkins Workload, Create our own repo for maven job
  ocs_ci/templates/workloads/jenkins/buildconfig.yaml
Labels: Verified, team/e2e, size/XS

#8105 Use ACM 2.9 for OCP 4.14
  ocs_ci/framework/conf/ocp_version/ocp-4.14-config.yaml
Labels: Verified, size/XS, DR

#8299 [4.11]: MachineConfigPool skip for IBM Managed cloud
  ocs_ci/utility/deployment.py
Labels: team/ecosystem, size/XS, cherry-pick

#8296 [4.13]: MachineConfigPool skip for IBM Managed cloud
  ocs_ci/utility/deployment.py
Labels: team/ecosystem, size/XS, cherry-pick

#8269 Use deviceclass in storagecluster
  conf/ocsci/use_device_class_fast.yaml
  conf/ocsci/use_device_class_hdd.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem

#7577 Stretch cluster: Net split test case automation
  ocs_ci/helpers/stretchcluster_helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/templates/workloads/logwriter/logwriter.rbd.yaml
  tests/conftest.py
  tests/disaster-recovery/sc_arbiter/conftest.py
  tests/disaster-recovery/sc_arbiter/test_netsplit.py
Labels: Verified, team/e2e, size/XL, new feature

#8194 Test reclaim chronjob by annotation
  tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py
Labels: Verified, size/L

#8330 Fix ObjectBucket::verify_health to only check S3 existence of MCG buckets
  ocs_ci/ocs/resources/objectbucket.py
Labels: High Priority, Verified, size/S, MCG, Squad/Red

#8308 Provide option for choosing specific upstream submariner based on tags
  conf/ocsci/submariner_upstream.yaml
  ocs_ci/deployment/acm.py
Labels: Verified, team/ecosystem, size/M, DR

#8280 [release-4.12 backport] Choose to use only the MCG-CLI for RPC calls elsewhere
  ocs_ci/ocs/resources/mcg.py
  tests/manage/mcg/test_nb_mgmt_endpoint.py
Labels: High Priority, size/M, MCG, Squad/Red, cherry-pick

#8293 Topology tests adjustments 4.14
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/odf_topology.py
  ocs_ci/ocs/ui/page_objects/odf_topology_tab.py
  ocs_ci/ocs/ui/views.py
  tests/ui/test_odf_topology.py
Labels: size/M, ui_automation, Squad/Black

#8331 DeviceClass verification in ceph osd tree
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/M

#8035 Increase timeout to allow pods to reach Running state in test_non_ocs_taint_and_tolerations after pod respin
  tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Labels: Verified, size/XS, Squad/Brown

#8297 support network type in IBM CLOUD IPI deployments
  ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
Labels: Verified, size/XS

#8228 fix mixed deployments OCP 4.14 OCS 4.13
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/L, ui_automation

#8260 [release-4.12 backport] NSFS noobaa-endpoint SCC workaround + Ignore the noobaa-endpoint pods leftovers at `test_nsfs.py`
  ocs_ci/ocs/constants.py
  tests/conftest.py
  tests/manage/mcg/test_nsfs.py
Labels: Verified, size/L, MCG, Squad/Red, cherry-pick

#8265 Cherry Pick PR 8017 to release-4.13
  ocs_ci/ocs/scale_lib.py
  tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Labels: Verified, size/L, scale, cherry-pick

#8264 Cherry Pick PR 8017 to release 4.12
  ocs_ci/ocs/scale_lib.py
  tests/e2e/scale/test_pv_scale_and_respin_ceph_pods.py
Labels: Verified, size/L, scale, cherry-pick

#8347 [4.12] Increase timeout to allow pods to reach Running state in test_non_ocs_taint_and_tolerations after pod respin
  tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Labels: Verified, size/XS, Squad/Brown

#8341 Wait for nodes to become ready to allow pods to come up in test_automated_recovery_from_stopped_node_and_start
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: Verified, size/XS, Squad/Brown

#8301 update various pods with proxy env vars
  tests/conftest.py
  tests/manage/mcg/test_s3_with_java_sdk.py
Labels: Verified, team/ecosystem, size/XS

#8344 Change the method 'is_node_rack_or_zone_exist' to get the node name instead of the node object
  ocs_ci/ocs/node.py
  tests/manage/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
Labels: Verified, size/M, Squad/Brown

#8257 [release-4.12 backport]Download the mcg-cli if the current binary has a different minor version than OCS
  ocs_ci/ocs/resources/mcg.py
Labels: High Priority, Verified, size/L, MCG, Squad/Red, cherry-pick

#8346 [4.13] Increase timeout to allow pods to reach Running state in test_non_ocs_taint_and_tolerations after pod respin
  tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Labels: Verified, size/XS, Squad/Brown

#8248 [release-4.13 backport] s3cli-sts: runAsUser 0 with image 2.0
  ocs_ci/templates/mcg/s3cli-sts.yaml
Labels: Verified, size/XS, MCG, Squad/Red, cherry-pick

#8249 [release-4.13 backport] Patch ocs-storagecluster instead the NooBaa CR at `test_disable_nb_lb`
  tests/manage/mcg/test_s3_routes.py
Labels: Verified, size/S, MCG, Squad/Red, cherry-pick

#8209 Disconnected ocp deployment on vsphere
  conf/README.md
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_disconnected.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_disconnected_flexy.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w_disconnected.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w_disconnected_flexy.yaml
  ocs_ci/deployment/disconnected.py
  ocs_ci/deployment/ocp.py
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/connection.py
  ocs_ci/utility/load_balancer.py
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Verified, team/ecosystem, size/L

#8356 [4.11] Support on external mode and increase timeout to allow pods to reach Running state in test_non_ocs_taint_and_tolerations after pod respin
  tests/manage/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Labels: Verified, size/L, Squad/Brown

#8350 [4.13] Wait for nodes to become ready to allow pods to come up in test_automated_recovery_from_stopped_node_and_start
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: Verified, size/XS, Squad/Brown

#8368 Add prints for must-gather-log
  ocs_ci/ocs/must_gather/const_must_gather.py
  ocs_ci/ocs/must_gather/must_gather.py
Labels: Verified, size/S, Squad/Brown

#8352 [4.11] Wait for nodes to become ready to allow pods to come up in test_automated_recovery_from_stopped_node_and_start
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: Verified, size/XS, Squad/Brown

#8351 [4.12] Wait for nodes to become ready to allow pods to come up in test_automated_recovery_from_stopped_node_and_start
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: Verified, size/XS, Squad/Brown

#8286 Cherry Pick 7874 in 4.12 branch (Increasing 'wait_for_pods_to_be_running' timeout to address intermitent failures in test_toleration )
  tests/manage/z_cluster/nodes/test_toleration.py
Labels: Verified, size/XS, Squad/Brown

#8345 RFE from pr 8139
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/resources/pod.py
  tests/manage/monitoring/test_workload_with_distruptions.py
Labels: Verified, size/L

#8023 cherry picked changes of pr 7873
  ocs_ci/framework/pytest_customization/marks.py
  tests/manage/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/XS, Squad/Brown

#8314 Add fio parameter direct=1 in the test case test_rbd_block_pvc_snapshot
  tests/manage/pv_services/pvc_snapshot/test_rbd_block_pvc_snapshot.py
Labels: size/XS, Squad/Green

#8363 Added flexibility to pull latest image to create couchbase cluster
  ocs_ci/ocs/couchbase.py
  tests/e2e/workloads/app/couchbase/test_couchbase.py
  tests/e2e/workloads/app/couchbase/test_couchbase_node_drain.py
  tests/e2e/workloads/app/couchbase/test_couchbase_node_reboot.py
  tests/e2e/workloads/app/couchbase/test_couchbase_pod_respin.py
Labels: team/e2e, size/S, Squad/Magenta

#8285 Release 4.12 cherry pick pr 7727
  ocs_ci/ocs/jenkins.py
  ocs_ci/templates/workloads/jenkins/buildconfig.yaml
Labels: team/e2e, size/M, Squad/Magenta
