Repository red-hat-storage/ocs-ci, pull requests merged in 2023-05, with the labels that each got.

#7438 Add GitOps Operator for AppSet deployment
  conf/ocsci/deploy_gitops_operator.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/gitops-deployment/gitops_cluster.yaml
  ocs_ci/templates/gitops-deployment/gitops_placement.yaml
  ocs_ci/templates/gitops-deployment/managedcluster_setbinding.yaml
  ocs_ci/templates/gitops-deployment/subscription.yaml
Labels: Verified, size/L, DR

#7366 test covers the new feature Alert improvements Follow-ups
  ocs_ci/ocs/constants.py
  ocs_ci/utility/monitoring_tool.py
  ocs_ci/utility/utils.py
  tests/internal/conftest.py
  tests/internal/test_monitoring_tool.py
Labels: Medium Priority, Verified, size/L

#7413 external mode does not have osds, add skip-mark
  tests/manage/monitoring/prometheusmetrics/test_monitoring_negative.py
Labels: size/XS, Squad/Blue

#7554 fix broken logic
  ocs_ci/framework/pytest_customization/marks.py
Labels: size/XS

#7518 Skip ui tests for IBM cloud deployment. Cherry-pick 4.12
  ocs_ci/framework/pytest_customization/marks.py
  tests/ui/test_non_admin_user.py
  tests/ui/test_validation_ui.py
Labels: Verified, size/S, ui_automation, Squad/Black, cherry-pick

#7520 Skip ui tests for IBM cloud deployment. Cherry-pick 4.10
  ocs_ci/framework/pytest_customization/marks.py
  tests/ui/test_non_admin_user.py
  tests/ui/test_validation_ui.py
Labels: Verified, size/S, ui_automation, Squad/Black, cherry-pick

#7519 Skip ui tests for IBM cloud deployment. Cherry-pick 4.11
  ocs_ci/framework/pytest_customization/marks.py
  tests/ui/test_non_admin_user.py
  tests/ui/test_validation_ui.py
Labels: Verified, size/S, ui_automation, Squad/Black, cherry-pick

#7521 Skip ui tests for IBM cloud deployment. Cherry-pick 4.9
  ocs_ci/framework/pytest_customization/marks.py
  tests/ui/test_non_admin_user.py
  tests/ui/test_validation_ui.py
Labels: size/S, ui_automation, Squad/Black, cherry-pick

#7537 Functions to verify storageclient and storageclassclaims
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/L, Managed Services

#7545 Install DFC offering in FaaS
  ocs_ci/ocs/fusion.py
  ocs_ci/templates/fusion-aas/icsp.yaml
  ocs_ci/templates/fusion-aas/managedfusionoffering-dfc.yaml.j2
Labels: Verified, size/L, Managed Services

#6687 Updated nfs tests to fix failures
  ocs_ci/ocs/constants.py
  ocs_ci/utility/nfs_utils.py
  tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Labels: Verified, size/L, Squad/Brown

#7457 Tagged the tests to squads
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_obc.py
  tests/e2e/scale/upgrade/test_upgrade_with_scaled_pvcs_pods.py
  tests/ecosystem/upgrade/test_upgrade_ocp.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
  tests/manage/z_cluster/upgrade/test_check_pdb_post_upgrade.py
Labels: size/S, Squad/Brown

#7536 Csi addons validation - RHSTOR-3863
  ocs_ci/ocs/constants.py
  ocs_ci/templates/CSI/addons/NetworkFence.yaml
  ocs_ci/templates/CSI/addons/ReclaimSpaceCronJob.yaml
  ocs_ci/templates/CSI/addons/ReclaimsSpaceJob.yaml
  ocs_ci/templates/CSI/addons/volumeReplicationCR.yaml
  ocs_ci/templates/CSI/addons/volumeReplicationClass.yaml
  tests/e2e/system_test/test_cr_resources_validation.py
Labels: Verified, size/L, new feature

#7523 added code to delete nooba secrets based on kms enabled or not
  tests/e2e/kcs/test_noobaa_rebuild.py
Labels: team/e2e, size/S, Squad/Magenta

#7541 Add new functionality to wait for stop and terminate nodes
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/aws.py
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_ms.py
  tests/manage/z_cluster/nodes/test_rolling_shutdown_and_recovery_ms.py
Labels: Verified, size/L, Managed Services

#7550 Load ocp version in the main module.
  ocs_ci/framework/main.py
Labels: Verified, team/ecosystem, size/S

#7576 use explicit parameters in clone_repo
  ocs_ci/deployment/flexy.py
  ocs_ci/deployment/vmware.py
  ocs_ci/helpers/disconnected.py
  ocs_ci/ocs/dr/dr_workload.py
Labels: Verified, team/ecosystem, size/M

#7578 Load ocp version in the main module in release 4.12
  ocs_ci/framework/main.py
Labels: team/ecosystem, size/S, cherry-pick

#7512 Fix Fusion aaS post deployment checks
  conf/deployment/fusion_aas/managed_3az_consumer_dev_3m_3w_m52x.yaml
  conf/deployment/fusion_aas/managed_3az_provider_qe_3m_3w_m52x.yaml
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/fusion.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/M, Managed Services

#7555 In the function "wait_for_silence_ceph_osd_crash_warning" change the exception from "TimeoutError" to "TimeoutExpiredError"
  ocs_ci/ocs/cluster.py
Labels: size/XS, Squad/Brown

#7556 In the function "wait_for_silence_ceph_osd_crash_warning" change the exception from "TimeoutError" to "TimeoutExpiredError"
  ocs_ci/ocs/cluster.py
Labels: size/XS, Squad/Brown

#7557 In the function "wait_for_silence_ceph_osd_crash_warning" change the exception from "TimeoutError" to "TimeoutExpiredError"
  ocs_ci/ocs/cluster.py
Labels: size/XS, Squad/Brown

#7558 In the function "wait_for_silence_ceph_osd_crash_warning" change the exception from "TimeoutError" to "TimeoutExpiredError"
  ocs_ci/ocs/cluster.py
Labels: size/XS, Squad/Brown

#7582 Remove spaces from onboarding ticket string if present while creating managedfusionoffering DFC
  ocs_ci/ocs/fusion.py
Labels: Verified, size/XS, Managed Services

#7574 Function to verify the status of pods in managed-fusion namespace
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/M, Managed Services

#7584 Fix post install verification for FaaS consumer
  ocs_ci/deployment/fusion_aas.py
  ocs_ci/helpers/sanity_helpers.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/fusion.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/ecosystem/deployment/test_deployment.py
Labels: Verified, size/L, Managed Services

#7572 Fix jenkins workload on OCP4.13
  ocs_ci/ocs/jenkins.py
Labels: team/e2e, size/S, Squad/Magenta

#7589 Verify all nodes are created for MS incaseof pull secret update
  ocs_ci/ocs/node.py
Labels: team/ecosystem, size/S

#7592 get correct pool name for external mode in fiojob
  ocs_ci/ocs/fiojob.py
Labels: Verified, team/ecosystem, size/XS

#7256 Merge pull request #7166 from prsurve/bm_node_functions
  ocs_ci/ocs/platform_nodes.py
Labels: size/XS, Squad/Brown

#7255 Merge pull request #7166 from prsurve/bm_node_functions
  ocs_ci/ocs/platform_nodes.py
Labels: size/XS, Squad/Brown

#7254 Merge pull request #7166 from prsurve/bm_node_functions
  ocs_ci/ocs/platform_nodes.py
Labels: Verified, size/XS, Squad/Brown

#7595 Increased timeout to wait for new osd deployment to come up
  tests/manage/z_cluster/test_delete_osd_deployment.py
Labels: Verified, size/XS, Squad/Brown

#7586 Post installation verifications for FaaS
  ocs_ci/deployment/fusion_aas.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/L, Managed Services

#7553 update test_odf_cephblockpool_compression_status with skip for 4.10
  tests/ui/test_validation_ui.py
Labels: Verified, size/XS

#7353 increase-num-dups
  ocs_ci/ocs/rados_utils.py
Labels: Verified, size/XS

#7603 update in-transit encryption vsphere upi config
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_intransit_encryption.yaml
Labels: Verified, team/ecosystem, size/S

#7583 Fix pagerduty and csv checks
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/utility/pagerduty.py
Labels: Verified, size/XS, Managed Services

#7599 Increase the timeout of `wait_for_pv_backingstore` by a minute
  ocs_ci/ocs/bucket_utils.py
Labels: size/XS, MCG, Squad/Red

#7546 [Release-4.11 cherry pick] Fix template_pvc to specify the PVC's capacity units
  ocs_ci/ocs/resources/namespacestore.py
Labels: size/XS, MCG, Squad/Red, MCG-4.11

#7590 use alias-rbd-data-pool-name if rbd name contains dot
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, team/e2e, size/S, Customer defects

#7444 [Release-4.11 cherry pick] PR6499 and PR7066
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/backingstore.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/templates/mcg/scale-cli-service-ca-configmap.yaml
  ocs_ci/templates/mcg/scalecli_pod.yaml
  tests/conftest.py
  tests/e2e/scale/noobaa/test_list_objects.py
Labels: Verified, team/e2e, size/L, Customer defects

#7517 fix storage class for external cluster, improve page_has_loaded
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  tests/manage/mcg/ui/test_mcg_ui.py
Labels: size/M, ui_automation, Squad/Black

#7514 Fixes purge bucket with versioning at the teardown of test_versioning_parallel_ops #6849
  ocs_ci/ocs/resources/objectbucket.py
Labels: Verified, size/XS, MCG, Squad/Red

#7525 Fix deploy pod status value for DeploymentConfig workload in pod_factory_fixture
  tests/conftest.py
Labels: Verified, size/XS, Squad/Green

#7477 [Release-4.12 cherry pick] Fix the expeced error for test_namespacestore_creation_webhook[Empty secret name]
  tests/manage/mcg/test_admission_control.py
Labels: size/XS, MCG, Squad/Red, MCG-4.12

#7392 Update the `NOOBAA_DB_SERVICE_ACCOUNT_NAME` constant for `test_db_scc` - 4.12 Cherry Pick
  ocs_ci/ocs/constants.py
  tests/manage/mcg/test_mcg_resources_disruptions.py
Labels: size/S, MCG, Squad/Red, MCG-4.12

#7623 move in-transit verification to ocs_install_verification
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: team/ecosystem, size/XS

#7280 Automation of intransit encryption sanity test.
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/encryption/test_intransit_encryption_sanity.py
Labels: Verified, size/L

#7510 Fixing node replacement issue in vSphere platform
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/csr.py
  tests/manage/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Verified, team/ecosystem, size/L, Squad/Brown

#7630 Update verify faas provider resources
  ocs_ci/helpers/managed_services.py
Labels: Verified, size/XS, Managed Services

#7633 Update OperatorGroup yaml and label namespaces for FaaS installation
  ocs_ci/ocs/fusion.py
  ocs_ci/templates/fusion-aas/operatorgroup.yaml
Labels: Verified, size/XS, Managed Services

#7620 Fixes bug of Terraform file name
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/azure_utils.py
Labels: team/ecosystem, size/M

#7640 Skip access token check in test_pvc_assign_pod_node if platform is FaaS
  tests/manage/pv_services/test_pvc_assign_pod_node.py
Labels: Verified, size/XS, Managed Services

#7491 [RDR] Add new tests for sequential failover or relocate action
  conf/ocsci/dr_workload.yaml
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/dr/dr_workload.py
  tests/conftest.py
  tests/disaster-recovery/regional-dr/test_failover.py
  tests/disaster-recovery/regional-dr/test_failover_and_relocate.py
  tests/disaster-recovery/regional-dr/test_relocate.py
  tests/disaster-recovery/regional-dr/test_sequential_failover.py
  tests/disaster-recovery/regional-dr/test_sequential_relocate.py
Labels: Test Case, Verified, size/L, DR, Squad/Turquoise

#7635 Add vsphere ipi compact mode config
  conf/deployment/vsphere/ipi_1az_rhcos_vsan_compact_mode_3m_0w.yaml
Labels: Verified, team/ecosystem, size/S

#7628 Fix UI deployment ODF4.13 on Vsphere
  ocs_ci/ocs/ui/base_ui.py
Labels: size/XS

#7451 Adding try except block in function "wait_for_nodes_status" to ignore "CommandFailed" exception
  ocs_ci/ocs/node.py
Labels: Verified, size/S, Squad/Brown

#7607 Increase wait time to check machineconfigpool before updating pull secret
  ocs_ci/deployment/fusion_aas.py
Labels: Verified, size/XS, Managed Services

#7615 Get rid of hardcoded namespace
  ocs_ci/helpers/helpers.py
  ocs_ci/helpers/managed_services.py
  ocs_ci/helpers/performance_lib.py
  ocs_ci/ocs/uninstall.py
Labels: Verified, size/S, Managed Services

#7624 Added ignore_leftovers to avoid ResourceLeftoversException
  tests/manage/z_cluster/cluster_expansion/test_verify_ceph_csidriver_runs_on_non_ocs_nodes.py
Labels: Verified, size/XS

#7648 Allow to overwrite DATA_DIR via environment variable
  conf/ocsci/README.md
  ocs_ci/deployment/aws.py
  ocs_ci/deployment/disconnected.py
  ocs_ci/deployment/ibmcloud.py
  ocs_ci/deployment/install_ocp_on_rhel.py
  ocs_ci/deployment/ocp.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/utility/utils.py
Labels: Needs Testing, size/M

#7642 Add bz marker to affected monitoring tests
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
  tests/manage/monitoring/prometheusmetrics/test_monitoring_negative.py
Labels: Verified, size/XS

#7474 [DR] Import cluster via CLI
  conf/README.md
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/acm/acm.py
  ocs_ci/templates/acm-deployment/auto-import-secret.yaml
  ocs_ci/templates/acm-deployment/managed-cluster.yaml
  tests/ecosystem/deployment/test_acm.py
Labels: size/L, DR

#7602 Support multiple ACM hubs
  conf/README.md
  conf/ocsci/multicluster_active_acm_cluster.yaml
  ocs_ci/deployment/acm.py
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/__init__.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/utils.py
  tests/conftest.py
Labels: team/ecosystem, size/M

#7579 Issue ocsqe947
  ocs_ci/utility/azure_utils.py
  setup.py
  tests/ecosystem/deployment/test_deployment.py
Labels: team/e2e, size/L, Customer defects

#7594 [GSS]Unable to expand ocs-storagecluster-ceph-rbd PVCs provisioned in Filesystem mode
  tests/manage/pv_services/pvc_resize/test_pod_deletion_during_pvc_expansion.py
Labels: Verified, team/e2e, size/L, Customer defects

#7625 cherry-pick for obc_create test, page_has_loaded improve, locators 4.13 for depl 4.12
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/mcg_ui.py
  ocs_ci/ocs/ui/views.py
  tests/manage/mcg/ui/test_mcg_ui.py
Labels: size/L, ui_automation, Squad/Black

#7644 check error from external script
  ocs_ci/deployment/helpers/external_cluster_helpers.py
Labels: Verified, team/ecosystem, size/XS

#7632 use realm in external script
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: team/ecosystem, size/M, Customer defects

#7539 Ignore must-gather-helper in environment check
  ocs_ci/ocs/constants.py
  tests/conftest.py
Labels: Verified, size/XS

#7552 Added post_upgrade marker to tier_marks list
  ocs_ci/framework/pytest_customization/marks.py
  tests/conftest.py
Labels: Needs Testing, Verified, team/ecosystem, size/M

#7627 Check the provider Faas storagecluster resources limits and requests, and check the storages in the storagecluster
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/L, Managed Services

#7560 Test negative failover/relocate scenarios via ACM UI
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/helpers/dr_helpers_ui.py
  ocs_ci/ocs/ui/views.py
  tests/disaster-recovery/regional-dr/test_failover.py
  tests/disaster-recovery/regional-dr/test_failover_and_relocate.py
  tests/disaster-recovery/regional-dr/test_negative_failover_relocate_ui.py
Labels: Verified, size/L, DR

#7641 Adding StrictHostKeyChecking=no while doing ssh into the node for IBM Power
  ocs_ci/utility/service.py
Labels: size/S

#7622 Validate pv deletion in teardown (#7266)
  ocs_ci/ocs/pgsql.py
Labels: team/e2e, size/S, Squad/Magenta

#7653 Increased timeout to add node to 900sec after machineset creation
  ocs_ci/ocs/scale_lib.py
Labels: bug, Verified, size/S, scale

#7650 catch exception during teardown when toolbox is in bad shape
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/XS

#7670 Release 4.9 cherry pick pr 7539
  ocs_ci/ocs/constants.py
  tests/conftest.py
Labels: size/XS

#7671 Release 4.10 cherry pick PR 7539
  ocs_ci/ocs/constants.py
  tests/conftest.py
Labels: size/XS

#7672 Release 4.11 cherry pick PR 7539
  ocs_ci/ocs/constants.py
  tests/conftest.py
Labels: size/XS

#7686 Allow ceph health re-try for specific test cases
  ocs_ci/framework/pytest_customization/marks.py
  tests/conftest.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
  tests/ui/test_add_capacity_ui.py
Labels: Verified, team/ecosystem, size/S

#7691 Add get_status_after_execution as finalizer only if get_status_before execution is enabled
  tests/conftest.py
Labels: Verified, Managed Services

#7675 Increase the number of workloads in sequential failover, relocate tests
  tests/disaster-recovery/regional-dr/test_sequential_failover.py
  tests/disaster-recovery/regional-dr/test_sequential_relocate.py
Labels: Verified, size/XS, DR, Squad/Turquoise

#7682 Create tools pod on FaaS consumer
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/utils.py
  tests/conftest.py
Labels: Verified, size/L, Managed Services

#7638 Disregard the users array of noobaa-db SCC at test_db_scc
  tests/manage/mcg/test_mcg_resources_disruptions.py
Labels: size/S, Squad/Red

#7681 pass parameter to TimeoutExpiredError exception
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/benchmark_operator_fio.py
  ocs_ci/ocs/quay_operator.py
  ocs_ci/ocs/ui/deployment_ui.py
Labels: team/ecosystem, size/S

#7694 Allow ceph health re-try for specific test cases
  ocs_ci/framework/pytest_customization/marks.py
  tests/conftest.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
  tests/ui/test_add_capacity_ui.py
Labels: team/ecosystem, size/S, cherry-pick

#7695 Allow ceph health re-try for specific test cases
  ocs_ci/framework/pytest_customization/marks.py
  tests/conftest.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
  tests/ui/test_add_capacity_ui.py
Labels: team/ecosystem, size/S, cherry-pick

#7696 Allow ceph health re-try for specific test cases
  ocs_ci/framework/pytest_customization/marks.py
  tests/conftest.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
  tests/ui/test_add_capacity_ui.py
Labels: team/ecosystem, size/S, cherry-pick

#7697 Allow ceph health re-try for specific test cases
  ocs_ci/framework/pytest_customization/marks.py
  tests/conftest.py
  tests/manage/z_cluster/cluster_expansion/test_add_capacity.py
  tests/ui/test_add_capacity_ui.py
Labels: team/ecosystem, size/S, cherry-pick

#7626 Add catsrc and subscription checks
  ocs_ci/helpers/managed_services.py
Labels: Verified, size/S, Managed Services

#7580 GSS BZ-2155743 automation
  tests/ui/test_validation_ui.py
Labels: Verified, team/e2e, size/S, Customer defects

#7702 Skip test_automated_recovery_from_stopped_node_and_start for IBM Cloud platform
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: team/ecosystem, size/XS

#7698 [Release-4.12 cherry pick] test fix up (#7385)
  tests/e2e/workloads/app/test_jenkins_simulation.py
Labels: team/e2e, size/M, Squad/Magenta

#7669 Updating functions of BlockPoolUI
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/block_pool.py
  ocs_ci/ocs/ui/storageclass.py
  ocs_ci/ocs/ui/views.py
  tests/ui/test_create_pool_block_pool.py
Labels: size/M

#7705 Faas: Add mon pvc storageclass check
  ocs_ci/helpers/managed_services.py
Labels: Verified, size/S, Managed Services

#7665 Adding try except block in function "wait_for_nodes_status" to ignore "CommandFailed" exception release-4.11 (#7451)
  ocs_ci/ocs/node.py
Labels: size/S, Squad/Brown

#7664 Adding try except block in function "wait_for_nodes_status" to ignore "CommandFailed" exception release-4.12 (#7451)
  ocs_ci/ocs/node.py
Labels: size/S, Squad/Brown

#7645 Enable external mode using SSL with RGW
  conf/README.md
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/utility/ssl_certs.py
Labels: Verified, team/ecosystem, size/L

#7688 remove wait parameter in stop_node since its not exists on all platforms
  tests/manage/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: team/ecosystem, size/XS

#7668 Set PagerDuty service for Fusion aaS use
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/utility/pagerduty.py
  tests/conftest.py
Labels: Verified, size/M, Managed Services

#7601 Test Coverage for BZ https://bugzilla.redhat.com/show_bug.cgi?id=2092737
  ocs_ci/helpers/disruption_helpers.py
  ocs_ci/ocs/resources/pod.py
  tests/e2e/scale/test_scale_3_OCS_worker_nodes_and_1500_PVCs.py
Labels: Verified, team/e2e, size/L, scale, Customer defects

#7709 Add managedfusionoffering check
  ocs_ci/helpers/managed_services.py
Labels: Verified, size/M, Managed Services
