Repository red-hat-storage/ocs-ci, pull requests merged in 2023-12, with the labels that each got.

#8969 Cephblockpool and sc creation is ideally not supported to customer on HCI PC platform
  tests/e2e/workloads/pvc_snapshot_and_clone/test_compressed_sc_and_support_snap_clone.py
  tests/e2e/workloads/test_new_sc_rbd_e2e_workloads.py
  tests/manage/monitoring/test_workload_with_distruptions.py
  tests/manage/pv_services/pvc_snapshot/test_verify_rbd_trash_purge.py
  tests/manage/pv_services/space_reclaim/test_rbd_space_reclaim.py
  tests/manage/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
  tests/manage/storageclass/conftest.py
  tests/manage/z_cluster/test_scc.py
Labels: Verified, size/M, lgtm, provider-client

#8970 Fix clone fixture error for HCI Provider Client setup
  tests/conftest.py
Labels: Verified, size/XS, lgtm

#8966 Create the Google Cloud Platform node functionalities 4.14
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/gcp.py
  setup.py
Labels: Verified, size/L, lgtm, cherry-pick, GCP

#8975 Skip unsupported Feature Encryption, new SC and NFS TC for HCI PC Platform
  tests/e2e/flowtest/pvc_snapshot_and_clone/test_pgsql_pvc_snapshot_and_clone.py
  tests/e2e/flowtest/pvc_snapshot_and_clone/test_pgsql_pvc_snapshot_and_clone_with_base_operation.py
  tests/e2e/lifecycle/pvc_clone/test_pgsql_pvc_clone.py
  tests/e2e/lifecycle/pvc_snapshot/test_pgsql_pvc_snapshot.py
  tests/encryption/test_intransit_encryption_sanity.py
  tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
  tests/manage/pv_services/space_reclaim/test_rbd_reclaimspace_cronjob.py
  tests/manage/pv_services/space_reclaim/test_rbd_space_reclaim.py
  tests/manage/pv_services/test_change_reclaim_policy_of_pv.py
  tests/manage/pv_services/test_pvc_assign_pod_node.py
  tests/manage/pv_services/test_raw_block_pv.py
  tests/manage/storageclass/test_create_multiple_sc_with_different_pool_name.py
  tests/manage/storageclass/test_create_multiple_sc_with_same_pool_name.py
Labels: Verified, size/M, lgtm, provider-client

#8835 Fix test_run_pod_local_image testcase
  tests/e2e/workloads/ocp/registry/test_pod_from_registry.py
Labels: team/e2e, size/XS, Squad/Magenta, lgtm

#8968 Skip test_dashboard_validation_ui from acceptance suite
  tests/ui/test_validation_ui.py
Labels: size/XS, lgtm

#8974 Update the test test_pvc_expansion to check a range of filesystem size
  tests/manage/pv_services/pvc_resize/test_pvc_expansion.py
Labels: Verified, size/XS, Squad/Green, lgtm

#8818 Tests to verify RDR failover with CephFS
  conf/ocsci/dr_workload.yaml
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/dr/dr_workload.py
  tests/conftest.py
  tests/disaster-recovery/regional-dr/test_failover.py
Labels: Test Case, Verified, size/L, lgtm

#8982 Update the function to get pool name in HCI platform
  ocs_ci/ocs/fiojob.py
Labels: Verified, size/M, lgtm, provider-client

#8983 Fix storageclassclaim creation for HCI provider-client setup
  ocs_ci/ocs/resources/storageclassclaim.py
Labels: Verified, size/XS, lgtm, provider-client

#8944 [release-4.12] Update flake8 and minimal python version
  .pre-commit-config.yaml
  docs/getting_started.md
  setup.py
Labels: team/ecosystem, size/XS, lgtm, cherry-pick

#8989 Add runs_on_provider marker in the tests test_monitoring_defaults
  tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py
Labels: Verified, size/XS, lgtm, provider-client

#8998 Fix cluster switching in the function storagecluster_independent_check
  ocs_ci/helpers/helpers.py
Labels: Verified, size/XS, lgtm, provider-client

#8992 create toolbox using storagecluster
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/utils.py
Labels: Verified, team/ecosystem, size/S, lgtm

#9000 Fixing provider_client_ms_platform_required marker
  ocs_ci/framework/pytest_customization/marks.py
Labels: Verified, size/XS, lgtm, provider-client

#9003 Updating ocs_must_gather_latest_tag for HCI platform
  conf/deployment/fusion_hci_pc/client_bm_upi_1az_rhcos_nvme_3w.yaml
  conf/deployment/fusion_hci_pc/provider_bm_upi_1az_rhcos_nvme_3m_3w.yaml
Labels: Verified, size/XS, lgtm, provider-client

#9021 vSphere Assisted Installer deployment (terraform scripts): create api and ingress records
  terraform/ai/vsphere/main.tf
  terraform/ai/vsphere/terraform.tfvars.example
  terraform/ai/vsphere/variables.tf
Labels: Verified, team/ecosystem, size/M, lgtm

#9015 Fixes missing argument issue
  tests/manage/mcg/test_noobaa_prometheus.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#9035 Update test_pvc_assign_pod_node to skip the check for api access token in HCI provider-client platform
  tests/manage/pv_services/test_pvc_assign_pod_node.py
Labels: Verified, size/S, lgtm, provider-client

#8994 Create assisted_installer low level api module
  ocs_ci/deployment/ocp.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/assisted_installer.py
Labels: Verified, team/ecosystem, size/XL, lgtm

#8658 Fixes mirroring timeout issue
  ocs_ci/ocs/resources/mcg.py
Labels: Verified, size/M, MCG, Squad/Red, lgtm

#9042 Assisted Installer deployment module
  ocs_ci/deployment/assisted_installer.py
  ocs_ci/ocs/exceptions.py
Labels: Verified, team/ecosystem, size/L, lgtm

#8962 Update getting the "ocs-osd-removal-job" name 4.13 #8879
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/M, Squad/Brown, lgtm, cherry-pick

#8964 Update getting the "ocs-osd-removal-job" name 4.14 #8879
  ocs_ci/ocs/resources/pod.py
  tests/manage/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/M, Squad/Brown, lgtm, cherry-pick

#9044 Fix threading_lock missing arg issue in test test_monitoring_shutdown_mgr_pod
  tests/e2e/workloads/ocp/monitoring/test_monitoring_on_negative_scenarios.py
Labels: Verified, team/e2e, size/XS, Squad/Magenta, lgtm

#8999 Blue squad test directory re-structure
  tests/functional/monitoring/__init__.py
  tests/functional/monitoring/conftest.py
  tests/functional/monitoring/libtest/test_workload_example.py
  tests/functional/monitoring/libtest/test_workload_fixture.py
  tests/functional/monitoring/pagerduty/__init__.py
  tests/functional/monitoring/pagerduty/alerts/__init__.py
  tests/functional/monitoring/pagerduty/alerts/test_ceph.py
  tests/functional/monitoring/pagerduty/alerts/test_deployment_status.py
  tests/functional/monitoring/prometheus/__init__.py
  tests/functional/monitoring/prometheus/alerts/__init__.py
  tests/functional/monitoring/prometheus/alerts/test_alerting_works.py
  tests/functional/monitoring/prometheus/alerts/test_capacity.py
  tests/functional/monitoring/prometheus/alerts/test_ceph.py
  tests/functional/monitoring/prometheus/alerts/test_deployment_status.py
  tests/functional/monitoring/prometheus/alerts/test_encryption.py
  tests/functional/monitoring/prometheus/alerts/test_hpa.py
  tests/functional/monitoring/prometheus/alerts/test_noobaa.py
  tests/functional/monitoring/prometheus/alerts/test_prometheus_rules.py
  tests/functional/monitoring/prometheus/alerts/test_rgw.py
  tests/functional/monitoring/prometheus/metrics/__init__.py
  tests/functional/monitoring/prometheus/metrics/test_mcg_hpa.py
  tests/functional/monitoring/prometheus/metrics/test_monitoring_defaults.py
  tests/functional/monitoring/prometheus/metrics/test_monitoring_negative.py
  tests/functional/monitoring/prometheus/metrics/test_ocs_utilization.py
  tests/functional/monitoring/prometheus/metrics/test_rgw.py
  tests/functional/monitoring/sendgrid/__init__.py
  tests/functional/monitoring/sendgrid/alerts/__init__.py
  tests/functional/monitoring/sendgrid/alerts/test_capacity.py
  tests/functional/monitoring/sendgrid/conftest.py
  tests/functional/monitoring/workload/__init__.py
  tests/functional/monitoring/workload/test_workload_with_distruptions.py
  tests/manage/monitoring/prometheus/test_ceph.py
Labels: Verified, size/XL, Squad/Blue, lgtm

#9063 Add noobaa marker for noobaa test selection
  ocs_ci/framework/pytest_customization/marks.py
Labels: team/ecosystem, size/XS, lgtm

#9052 [release-4.12 backport] Check for an existing pod before calling `awscli_pod_fixture`, and leverage the retry decorator in it
  tests/conftest.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm, MCG-4.12, cherry-pick

#9068 Increase timeout for creating the resources after rolling nodes restart
  tests/manage/z_cluster/nodes/test_nodes_restart.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#9005 Update ocs_install_verification for hci setup
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/M, lgtm, provider-client

#9036 Fixes ClientSecretCredential token issue
  tests/manage/mcg/test_azure_noobaa_sa.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#9074 Disable monitoring for ARO deployment
  conf/deployment/azure/managed_aro_3az_rhcos_3m_3w.yaml
Labels: Verified, team/ecosystem, lgtm

#9075 User defined storage cluster version check
  conf/ocsci/disable_storage_cluster_version_check.yaml
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Needs Testing, team/ecosystem, size/S, lgtm

#9056 [release-4.12 backport] Fix ObjectBucket::verify_health to only check S3 existence of MCG buckets
  ocs_ci/ocs/resources/objectbucket.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm, MCG-4.12, cherry-pick

#9055 [release-4.13 backport] Fix ObjectBucket::verify_health to only check S3 existence of MCG buckets
  ocs_ci/ocs/resources/objectbucket.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm, MCG-4.13, cherry-pick

#9004 Skip `test_upgrade_mcg_io` until https://url.corp.redhat.com/c960ed4 is complete
  tests/ecosystem/upgrade/test_noobaa.py
Labels: Verified, size/XS, MCG, upgrade, Squad/Red, lgtm

#8547 Move the check for "not found" buckets from ObjectBucket.delete to its subclasses
  ocs_ci/ocs/resources/objectbucket.py
Labels: Verified, size/M, MCG, Squad/Red, lgtm

#9090 Add support for CNV deployment in DR cluster deployment jobs, skipping it on ACM cluster
  ocs_ci/deployment/cnv.py
  ocs_ci/deployment/deployment.py
Labels: Verified, team/e2e, size/S, lgtm

#9061 [Release-4.14 backport] CNV deployment
  conf/ocsci/cnv_deployment.yaml
  ocs_ci/deployment/cnv.py
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/ocp.py
  ocs_ci/templates/cnv-deployment/catalog-source.yaml
  ocs_ci/templates/cnv-deployment/hyperconverged.yaml
  ocs_ci/templates/cnv-deployment/namespace.yaml
  ocs_ci/templates/cnv-deployment/operatorgroup.yaml
  ocs_ci/templates/cnv-deployment/subscription.yaml
Labels: Verified, team/e2e, size/XL, lgtm

#8990 Test s3 upload/download in virtual hosted bucket
  tests/manage/mcg/test_virtual_hosted_buckets.py
Labels: Verified, team/e2e, size/M, MCG, Customer defects, Squad/Red, lgtm
