Repository red-hat-storage/ocs-ci, pull requests merged in 2024-09, with the labels that each got.

#10344 Test Automation for feature PV key rotation.
  ocs_ci/helpers/keyrotation_helper.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/utility/kms.py
  tests/functional/pv/pv_encryption/test_pv_keyrotation.py
Labels: Verified, size/L, lgtm

#10336 Update Csi SideCar count for RDR deployment
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/S, lgtm, DR

#10341 Fix issue 10340
  ocs_ci/utility/utils.py
Labels: Verified, size/XS, lgtm, DR

#10395 Skiping recovery cluster while creating drpolicy 1st time
  ocs_ci/deployment/deployment.py
Labels: team/e2e, size/XS, lgtm

#10187 Prerequisite for Discovered Apps
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/DR/dpa_discovered_apps.yaml
Labels: Verified, size/M, lgtm, DR, Squad/Turquoise

#10216 Add the kubevirt VM node functionalities for the hosted cluster
  ocs_ci/deployment/helpers/hypershift_base.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/decorators.py
  ocs_ci/utility/kubevirt_vm.py
  ocs_ci/utility/utils.py
  tests/functional/z_cluster/nodes/test_nodes_restart_hci.py
Labels: Verified, size/XL, Squad/Brown, lgtm, provider-client

#10377 Deploy and configure Ingress Node Firewall to be able to restrict SSH access to nodes.
  conf/README.md
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/ingress_node_firewall.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ingress-node-firewall-deployment/config.yaml
  ocs_ci/templates/ingress-node-firewall-deployment/namespace.yaml
  ocs_ci/templates/ingress-node-firewall-deployment/operatorgroup.yaml
  ocs_ci/templates/ingress-node-firewall-deployment/rules.yaml
  ocs_ci/templates/ingress-node-firewall-deployment/subscription.yaml
Labels: Verified, team/ecosystem, size/L, lgtm

#10398 Fix issue with maintenance pod
  ocs_ci/ocs/ceph_debug.py
  tests/conftest.py
  tests/cross_functional/kcs/test_maintenance_pod.py
Labels: Verified, team/e2e, size/L, Squad/Magenta, lgtm

#9123 Deploy apps on both primary and secondary cluster
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/helpers/dr_helpers_ui.py
  ocs_ci/ocs/dr/dr_workload.py
  ocs_ci/ocs/ui/acm_ui.py
  ocs_ci/ocs/ui/views.py
  ocs_ci/ocs/utils.py
  tests/conftest.py
  tests/functional/disaster-recovery/metro-dr/test_multiple_apps_failover_and_relocate.py
Labels: Verified, size/XL, lgtm, DR

#10397 Remove the Bugzilla decorators from the test "test_check_mds_cache_memory_limit"
  tests/functional/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#10413 Allow osd_size configuration for IBM Cloud Managed clusters
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#10364 Test Automation for space reclaim with storageclass annotations.
  ocs_ci/helpers/helpers.py
  tests/conftest.py
  tests/functional/storageclass/test_storageclass_reclaim_space.py
Labels: Verified, size/L, lgtm

#9808 New changes in custom taint and toleration from ODF 4.16
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/pod.py
  tests/functional/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Labels: Verified, team/e2e, size/L, lgtm

#10077 Stretch cluster + CNV automation
  ocs_ci/deployment/cnv.py
  ocs_ci/helpers/stretchcluster_helper.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/stretchcluster.py
  tests/conftest.py
  tests/functional/disaster-recovery/sc_arbiter/test_netsplit.py
  tests/functional/disaster-recovery/sc_arbiter/test_zone_shutdown_and_crash.py
Labels: Verified, team/e2e, size/XL, lgtm

#9757 [RHSTOR-4798] MDSCacheUsageHigh alert feature test cases automation.
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/templates/workloads/helper_scripts/file_creator_io.py
  ocs_ci/templates/workloads/helper_scripts/meta_data_io.py
  ocs_ci/utility/prometheus.py
  tests/functional/monitoring/prometheus/alerts/test_alert_mds_cache_high_usage.py
  tests/functional/monitoring/prometheus/alerts/test_alert_mds_cpu_high_usage.py
Labels: Verified, team/e2e, size/XL, new feature, lgtm

#10419 Allow osd_size configuration for IBM Cloud Managed clusters - backport to release 4.13
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/XS, lgtm, cherry-pick

#9974 S3 cleanup with new method
  ocs_ci/cleanup/aws/cleanup.py
Labels: Verified, team/ecosystem, size/S, lgtm

#9545 Replace Cluster
  conf/ocsci/recovery_cluster.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/dr/dr_workload.py
  ocs_ci/ocs/utils.py
  ocs_ci/templates/DR/dr_conf_removal.sh
  ocs_ci/templates/gitops-deployment/gitops_og.yaml
  ocs_ci/templates/gitops-deployment/subscription.yaml
  tests/functional/disaster-recovery/metro-dr/test_replace_cluster.py
Labels: Verified, team/e2e, size/XL, lgtm, DR, Squad/Turquoise

#10371 Fix LSO UI deployment
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/ui/deployment_ui.py
Labels: Needs Deployment Testing, team/ecosystem, size/S, lgtm

#10434 fix object storage issues
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/utility/utils.py
Labels: Verified, size/XS, Environment issue, lgtm, backport-required

#10359 Parsing and validation for ceph df details
  ocs_ci/ocs/cluster.py
  tests/functional/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/L, lgtm, product-bug

#10438 Adding ODF 4.18 config files
  ocs_ci/framework/conf/ocs_version/ocs-4.18.yaml
  ocs_ci/framework/main.py
Labels: Verified, team/ecosystem, size/S, lgtm

#10426 Use the secure external endpoint and the needed CA for RGW SSL external deployments
  ocs_ci/ocs/awscli_pod.py
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/rgw.py
Labels: Verified, size/S, External-cluster-mode, RGW, Squad/Red, lgtm

#10268 Provider client context manager
  ocs_ci/framework/__init__.py
  ocs_ci/ocs/resources/storageconsumer.py
  tests/functional/monitoring/conftest.py
Labels: Verified, size/L, lgtm, provider-client

#9892 Set a priviliged service account for the NSFS interface deployment for NSFS tests
  tests/conftest.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm

#9872 Update `test_s3_route_reconcile` to 4.16 expectations
  tests/functional/object/mcg/test_s3_routes.py
Labels: Verified, size/M, Squad/Red, lgtm

#10435 [Provider mode] Update the verification of the number of CephFS, RBD pods and owner verification of deployments and daemonsets
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: High Priority, Verified, size/M, lgtm, provider-client

#10407 Fixes issue:8631: Update the steps of test case to get rgw_alerts
  tests/functional/monitoring/conftest.py
  tests/functional/monitoring/prometheus/alerts/test_rgw.py
Labels: Verified, size/S, Squad/Blue, lgtm, backport-required

#10357 <GSS Closed Loop BZ: 2264900> Tests to verify restore a pvc from snapshot when the parent PVC is deleted
  tests/functional/pv/pvc_snapshot/test_restore_snapshot_when_parent_pvc_deleted.py
Labels: Verified, team/e2e, size/L, Customer defects, Squad/Green, lgtm

#10428 Fix test: test_ceph_manager_stopped
  tests/functional/monitoring/conftest.py
Labels: Verified, size/S, Squad/Blue, lgtm, backport-required

#10453 address ns and common issues shown up during tier1 execution
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/kms.py
  tests/conftest.py
  tests/cross_functional/kcs/test_selinux_relabel_solution.py
  tests/functional/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
  tests/functional/pv/add_metadata_feature/test_metadata.py
  tests/functional/pv/pv_encryption/test_secrets_on_pods.py
Labels: Verified, size/M, lgtm, backport-required

#10347 Run parallel must gather for ocp, ocs and mcg
  ocs_ci/ocs/utils.py
Labels: Verified, team/ecosystem, size/L, lgtm

#10459 Update PVC access mode choice
  ocs_ci/ocs/ui/pvc_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/S, lgtm

#10393 Add deployment checks
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
Labels: team/ecosystem, size/M, lgtm

#10465 Fix stretchcluster_required mark
  ocs_ci/framework/pytest_customization/marks.py
  pytest.ini
Labels: Verified, size/XS, lgtm

#10469 Update numpy version to 1.23.2
  setup.py
Labels: team/ecosystem, size/XS, lgtm

#10468 Fix direct use of logging module
  ocs_ci/templates/workloads/helper_scripts/file_creator_io.py
  ocs_ci/templates/workloads/helper_scripts/meta_data_io.py
Labels: team/ecosystem, size/S, lgtm

#10422 Deploy and configure Ingress Node Firewall to be able to restrict SSH access to nodes - release-4.16
  conf/README.md
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/ingress_node_firewall.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ingress-node-firewall-deployment/config.yaml
  ocs_ci/templates/ingress-node-firewall-deployment/namespace.yaml
  ocs_ci/templates/ingress-node-firewall-deployment/operatorgroup.yaml
  ocs_ci/templates/ingress-node-firewall-deployment/rules.yaml
  ocs_ci/templates/ingress-node-firewall-deployment/subscription.yaml
Labels: team/ecosystem, size/L, lgtm, cherry-pick

#9860 Discovered Apps Failover and Relocate
  conf/ocsci/dr_workload.yaml
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/dr/dr_workload.py
  ocs_ci/ocs/resources/drpc.py
  ocs_ci/templates/DR/drpc.yaml
  ocs_ci/templates/DR/placement.yaml
  tests/conftest.py
  tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate_discovered_apps.py
Labels: Verified, size/XL, lgtm, DR, Squad/Turquoise

#10471 ignore failure in Ingress Node Firewall deployment
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/ingress_node_firewall.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#10472 [release 4.16] Update numpy version to 1.23.2
  setup.py
Labels: team/ecosystem, size/XS, lgtm, cherry-pick

#10473 [release 4.15] python 3.11 support
  setup.py
  tox.ini
Labels: team/ecosystem, size/S, lgtm, cherry-pick

#10474 [release 4.14] python 3.11 support
  setup.py
  tox.ini
Labels: team/ecosystem, size/S, lgtm, cherry-pick

#10475 [release 4.13] python 3.11 support
  setup.py
  tox.ini
Labels: team/ecosystem, size/S, lgtm, cherry-pick

#10485 Add python 3.11 execution to github action pr_checks
  .github/workflows/pr_checks.yml
Labels: Verified, team/ecosystem, size/XS, lgtm

#10464 Make Ceph upgrade params to be configurable
  conf/README.md
  conf/ocsci/ceph_upgrade_params.yaml
  ocs_ci/deployment/deployment.py
Labels: size/M, lgtm

#10481 ignore failure in Ingress Node Firewall deployment - release-4.16
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/ingress_node_firewall.py
Labels: team/ecosystem, size/XS, lgtm, cherry-pick

#10486 Fix RDR tests fails with "KeyError: 'matchExpressions'"
  ocs_ci/ocs/dr/dr_workload.py
Labels: Verified, size/XS, lgtm, DR

#10427 test storagecluster ceph full thresholds params
  ocs_ci/helpers/helpers.py
  tests/functional/z_cluster/test_storagecluster_ceph_full_thresholds_params.py
Labels: Verified, size/L, lgtm

#10466 mustgather for rosa hcp. change the image regestry
  ocs_ci/ocs/ocs_upgrade.py
  tests/conftest.py
Labels: Verified, TestCase failing, size/S, lgtm

#10384 logs improved, timeout increased
  ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
  tests/functional/object/mcg/ui/test_mcg_ui.py
Labels: Verified, TestCase failing, size/M, lgtm, Squad/Black, backport-required

#10493 Fix resource wrong status exception
  tests/conftest.py
  tests/functional/pv/pv_encryption/test_encrypted_pvc_no_expansion_option.py
Labels: Verified, size/XS, lgtm

#10141 Fixed default sc tests case which was failing
  ocs_ci/helpers/helpers.py
  tests/functional/storageclass/test_rbd_default_storageclass.py
Labels: Verified, size/S, lgtm

#10507 fix black formatting
  ocs_ci/ocs/dr/dr_workload.py
Labels: team/ecosystem, size/XS, lgtm

#10506 Add setup_cnv fixture to workload suite CNV basic tests
  tests/functional/workloads/cnv/test_vm_lifecycle_and_io.py
  tests/functional/workloads/cnv/test_vm_single_disk_hot_plugging_unplugging.py
Labels: Verified, team/e2e, size/XS, Squad/Magenta

#10510 quick syntax fix
  ocs_ci/ocs/ocs_upgrade.py
Labels: bug, size/XS, lgtm

#10499 Fix IBM Cloud ROKS 4.15 deployment
  ocs_ci/utility/ibmcloud.py
Labels: Verified, size/XS, lgtm

#10342 Expose upgrade settings storagecluster Feature
  tests/functional/upgrade/test_storagecluster_upgrade_params.py
Labels: Verified, size/L, lgtm

#10498 Run black to fix formatting in conftest.py
  tests/manage/monitoring/conftest.py
Labels: team/ecosystem, size/XS, lgtm

#10518 Fix stretchcluster_required mark
  ocs_ci/framework/pytest_customization/marks.py
  pytest.ini
Labels: size/XS, lgtm

#10519 Fix stretchcluster_required mark
  ocs_ci/framework/pytest_customization/marks.py
  pytest.ini
Labels: size/XS, lgtm

#10431 WORKAROUND: add possibility to mark disks as ssd
  conf/README.md
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocp-deployment/workaround-ssd-machine-config.yaml
  ocs_ci/utility/deployment.py
Labels: team/ecosystem, size/M, lgtm

#10523 lower ingress node firewall timeout to 15 minutes
  ocs_ci/deployment/ingress_node_firewall.py
Labels: team/ecosystem, size/XS, lgtm

#10524 Fix external mode rgw_secure condition
  ocs_ci/ocs/awscli_pod.py
  ocs_ci/ocs/resources/rgw.py
Labels: size/XS, lgtm

#10515 Remove must-gather parameter -pc for clients
  ocs_ci/ocs/utils.py
Labels: Verified, size/XS, lgtm, provider-client

#10514 try-exept_on_close_browser
  ocs_ci/ocs/ui/base_ui.py
Labels: bug, Verified, size/S, lgtm, Squad/Black

#10533 Added delete versions to delete_buckets function
  ocs_ci/cleanup/aws/cleanup.py
Labels: Verified, size/XS, lgtm

#10532 Switch to acm ctx before checking S3storeprofiles
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/XS, lgtm, DR

#10172 Set cluster_kubeconfig based on the type of resource available in provider cluster only
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
Labels: Verified, size/M, provider-client

#10539 Reduce backoff time when looking for Serviceexport
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/XS, lgtm, DR, Squad/Turquoise

#10529 Revert "Remove Bluestore-rdr check"
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/S, lgtm, DR, Squad/Turquoise

#10548 Add ROSA_HCP_PLATFORM constant
  ocs_ci/ocs/constants.py
Labels: Needs Deployment Testing, team/ecosystem, size/XS, lgtm

#10536 Fixes incorrect comparison for test_bucket_used_bytes_metric
  tests/functional/object/mcg/test_noobaa_prometheus.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#10550 ODF4.17 UI deployment, add 'data protection' page
  ocs_ci/ocs/ui/deployment_ui.py
Labels: Verified, size/XS, lgtm

#10505 use ocp-network-split from red-hat-storage org fork
  requirements.txt
  setup.py
Labels: team/ecosystem, size/XS, lgtm

#10555 increase timeout for MCP incase of more nodes
  ocs_ci/utility/deployment.py
Labels: Verified, team/ecosystem, size/XS, upgrade, lgtm

#10570 increase timeout for MCP incase of more nodes
  ocs_ci/utility/deployment.py
Labels: team/ecosystem, size/XS, lgtm

#10538 Update python version requirement in doc
  docs/getting_started.md
Labels: documentation, team/ecosystem, size/XS, lgtm

#10574 Change acm ctx switch order
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/XS, lgtm, DR

#10277 New Test for ODF CLI
  ocs_ci/helpers/odf_cli.py
  tests/functional/odf-cli/test_get_commands.py
  tests/functional/odf-cli/test_operator_restart.py
  tests/functional/z_cluster/test_rook_ceph_operator_log_type.py
Labels: Test Case, Verified, size/L, lgtm

#10589 Add new conf file for 'openshift-storage' cluster namespace
  conf/ocsci/cluster_namespace_openshift_storage.yaml
Labels: team/ecosystem, size/XS, lgtm, provider-client

#10436 tests for rhstor5518
  tests/functional/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
  tests/functional/odf-cli/test_pvc_stale_volume_cleanup_cli.py
Labels: Verified, size/L

#10596 Add another error message when getting the IBMCloud Baremetal servers
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/scale_lib.py
  ocs_ci/utility/ibmcloud_bm.py
Labels: Verified, size/M, lgtm, provider-client

#10598 Reduce Backoff tries
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, lgtm, DR, Squad/Turquoise
