Repository red-hat-storage/ocs-ci, pull requests merged in 2024-07, with the labels that each got.

#9996 Adding OCP 4.16-ga files
  ocs_ci/framework/conf/ocp_version/ocp-4.16-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.16-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.16-ga-upgrade.yaml
Labels: Verified, team/ecosystem, size/M, lgtm

#9990 [release-4.14]: openshift installer download using oc
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/S, lgtm

#9991 [release-4.13]: openshift installer download using oc
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/S, lgtm

#9992 [release-4.12]: openshift installer download using oc
  ocs_ci/utility/utils.py
Labels: size/S, lgtm

#10018 Fix variable name to allow search for firing alerts
  ocs_ci/utility/prometheus.py
Labels: Verified, size/XS, Squad/Blue, lgtm

#10001 move get_openshift_mirror_url to try block
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#10000 add Deployment init to constructor
  ocs_ci/deployment/hosted_cluster.py
Labels: Verified, size/XS, lgtm

#9975 Test the new total storage size is reflected in the UI post resize osd
  ocs_ci/helpers/osd_resize.py
  tests/functional/z_cluster/cluster_expansion/test_resize_osd.py
Labels: Test Case, Verified, size/M, Squad/Brown, lgtm, Squad/Black

#10030 Add production configuration for STS deployment with KMS Thales
  conf/deployment/aws/ipi_3az_rhcos_sts_3m_3w_thales.yaml
Labels: Verified, team/ecosystem, size/S, lgtm

#10023 [release-4.12] Python 3.10 support
  .github/workflows/pr_checks.yml
  docs/getting_started.md
  docs/unit_tests.md
  setup.py
  tox.ini
Labels: team/ecosystem, size/M, lgtm, cherry-pick

#10041 Cross Class Clone and Restore - adding support for compressed pool
  tests/functional/storageclass/test_cross_sc_clone_snap_restore.py
Labels: size/S, lgtm

#9988 Fix broken modify_csv() feature #9869
  ocs_ci/deployment/deployment.py
Labels: Verified, size/S

#10043 test_validate_ceph_config_values_in_rook_config_override - Test ready for 4.16
  ocs_ci/ocs/constants.py
  tests/functional/z_cluster/test_ceph_default_values_check.py
Labels: bug, Verified, size/M, lgtm

#10048 Fix syntax for HEALTHY_PV_BS list by removing backticks
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#10045 check pv-backingstore pod before upgrade
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#10049 [cherry-pick-9885][release-4.14]Removed skip test marker form the test
  tests/manage/add_metadata_feature/test_metadata.py
Labels: Verified, size/XS, lgtm, cherry-pick

#10050 [cherry-pick-9885][release-4.15]Removed skip test marker form the test
  tests/functional/pv/add_metadata_feature/test_metadata.py
Labels: Verified, size/XS, lgtm, cherry-pick

#10051 Skip all the tests in the resize osd feature until the related BZs are fixed
  tests/functional/z_cluster/cluster_expansion/test_resize_osd.py
Labels: Verified, size/XS, lgtm

#10054 Adding pvc resize functionality to RWOP test
  tests/functional/pv/pv_services/test_pvc_change_access_modes_rwop.py
  tests/functional/pv/pv_services/test_rwop_pvc.py
Labels: size/XS, lgtm

#7888 test objects deletion from a OBC when there is huge number of objects ~ 2M
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/resources/backingstore.py
  ocs_ci/ocs/resources/bucketclass.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/pvc.py
  tests/conftest.py
  tests/cross_functional/conftest.py
  tests/cross_functional/scale/noobaa/test_delete_objects.py
Labels: Verified, team/e2e, size/L, MCG, Customer defects, lgtm

#10042 [cherry-pick-9177][Release 4.12] Replacing crypt device check from pod to node.
  ocs_ci/ocs/node.py
  tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_clone.py
  tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_snapshot.py
  tests/manage/pv_services/pv_encryption/test_kmip_rbd_pv_encryption.py
  tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption.py
  tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption_vaulttenantsa.py
  tests/ui/test_pv_encryption_ui.py
Labels: Verified, size/L, lgtm, cherry-pick

#10040 [cherry-pick-9177][Release 4.13] Replacing crypt device check from pod to node.
  ocs_ci/ocs/node.py
  tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_clone.py
  tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_snapshot.py
  tests/manage/pv_services/pv_encryption/test_kmip_rbd_pv_encryption.py
  tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption.py
  tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption_vaulttenantsa.py
  tests/ui/test_pv_encryption_ui.py
Labels: Verified, size/L, lgtm, cherry-pick

#9924 Multus Upgarde 4.15->4.16 - dropping holder design
  conf/ocsci/multus_delete_csi_holder_pods.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, size/L, lgtm

#9994 Increase timeout for allow successful data re-balance on VSphere/Azure platforms
  tests/functional/z_cluster/cluster_expansion/test_add_capacity.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#10039 [Cherry-pick-9177][release-4.14] Replacing crypt device check from pod to node.
  ocs_ci/ocs/node.py
  tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_clone.py
  tests/manage/pv_services/pv_encryption/test_encrypted_rbd_pvc_snapshot.py
  tests/manage/pv_services/pv_encryption/test_kmip_rbd_pv_encryption.py
  tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption.py
  tests/manage/pv_services/pv_encryption/test_rbd_pv_encryption_vaulttenantsa.py
  tests/ui/test_pv_encryption_ui.py
Labels: Verified, size/L, lgtm, cherry-pick

#10073 Adding pod deletion and verification that second pod is reaching Running state
  tests/functional/pv/pv_services/test_rwop_pvc.py
Labels: Verified, size/M, lgtm

#10076 Added skip marker to test if azure KV config is not set.
  ocs_ci/framework/pytest_customization/marks.py
  tests/functional/pv/pv_encryption/test_azure_kms_pv_encryption.py
Labels: Verified, size/S, lgtm

#10079 [release-4.15]: download OCP nightly through GA'ed version incase of failures
  ocs_ci/utility/utils.py
  ocs_ci/utility/version.py
Labels: Verified, team/ecosystem, size/L, lgtm

#10089 Adding new test cases for creating clone and snap and snap restore for rwop pvc
  tests/functional/pv/pv_services/test_rwop_pvc.py
Labels: Verified, size/M, lgtm

#10087 Adding a new test for rwo to rwop migration
  ocs_ci/helpers/helpers.py
  tests/functional/pv/pv_services/test_pvc_migrate_rwo_to_rwop.py
Labels: Verified, size/L, lgtm

#10092 Changing tests/functional/pv/pv_services/test_pvc_migrate_rwo_to_rwop.py marker from tier1 to tier2
  tests/functional/pv/pv_services/test_pvc_migrate_rwo_to_rwop.py
Labels: size/XS, lgtm

#10107 test_store_creation_and_deletion fix
  ocs_ci/ocs/ui/page_objects/odf_topology_tab.py
  ocs_ci/ocs/ui/views.py
  tests/cross_functional/ui/test_odf_topology.py
Labels: Verified, size/S, lgtm

#10074 add hci_baremetal deployment type to map
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/factory.py
  ocs_ci/deployment/hosted_cluster.py
  ocs_ci/deployment/metallb.py
Labels: Verified, size/M, lgtm

#10065 first portion of fixes. Topology tests and error msg improvements
  ocs_ci/ocs/ui/odf_topology.py
  ocs_ci/ocs/ui/page_objects/odf_topology_tab.py
  tests/cross_functional/ui/test_odf_topology.py
  tests/functional/ui/test_error_improvements.py
Labels: Verified, size/M, lgtm

#10032 Dependency installation separate
  ocs_ci/deployment/hosted_cluster.py
  tests/libtest/test_metallb.py
  tests/libtest/test_provider_create_hosted_cluster.py
Labels: Verified, size/M, lgtm

#10098 skip fetching upgrade version if its external mode
  ocs_ci/ocs/ocs_upgrade.py
Labels: team/ecosystem, size/XS, lgtm

#10066 Fix kebab menu locator for add capacity UI test
  ocs_ci/ocs/ui/add_replace_device_ui.py
  ocs_ci/ocs/ui/views.py
  ocs_ci/utility/localstorage.py
  tests/functional/z_cluster/cluster_expansion/test_add_capacity.py
Labels: Verified, size/S, Squad/Brown, lgtm, Squad/Black

#10072 Reduce the number of PVCs created and IO running in the test "tests/functional/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py"
  ocs_ci/helpers/sanity_helpers.py
  tests/functional/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py
Labels: Verified, team/e2e, size/M, Squad/Brown, lgtm

#10095 Deploy ODF4.17 via UI
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/M, lgtm

#10096 Adding a new test case for reclaim space job and cronjob on rwop pvc
  ocs_ci/helpers/helpers.py
  tests/functional/pv/pv_services/test_rwop_pvc.py
  tests/functional/pv/pv_services/test_rwop_pvc_reclaim_space.py
Labels: Verified, size/L, lgtm

#9948 Adding test to check for values in securityKeyRef in pod
  tests/internal/test_secrets_on_pods.py
Labels: Verified, size/L, lgtm

#9738 To verify that the cluster remains accessible and NO DU/DL after failures
  tests/functional/disaster-recovery/metro-dr/test_no_data_loss_and_corruption_on_failures.py
Labels: Verified, team/e2e, size/L, lgtm, Squad/Turquoise

#10119 Security fixes for dependencies
  setup.py
Labels: size/XS, lgtm

#10110 mdr+cnv unique namespaces for cnv workloads
  conf/ocsci/mdr_workload.yaml
  ocs_ci/ocs/dr/dr_workload.py
  tests/conftest.py
Labels: Verified, size/M, lgtm, DR

#10116 vsphere ipi deployment - not all nodes created
  ocs_ci/ocs/node.py
Labels: Verified, team/ecosystem, size/M, lgtm

#10080 change python version from 3.8 to 3.9 in precommit yaml file
  .pre-commit-config.yaml
Labels: team/ecosystem, size/XS, lgtm

#10137 Fix s3_list_objects_v2 function keyword args default value
  ocs_ci/ocs/bucket_utils.py
Labels: team/e2e, size/XS, MCG, lgtm

#10143 removed unused dynamic variable at class level
  tests/lvmo/test_lvm_clone_base.py
  tests/lvmo/test_lvm_multi_clone.py
  tests/lvmo/test_lvm_multi_snapshot.py
  tests/lvmo/test_lvm_snapshot_base.py
Labels: team/ecosystem, size/XS, lgtm

#10142 Disable auto reclaimspace cronjob test at namespace level
  tests/functional/pv/space_reclaim/test_auto_reclaim_space_cronjob.py
Labels: Verified, size/XS, lgtm

#10147 use silent and location for curl downloads
  Docker_files/ocsci_container/Containerfile.ci
Labels: Verified, team/ecosystem, size/XS, lgtm

#10071 change pdb max unavailable to 2 if we have at least 5 mons in a cluster
  ocs_ci/ocs/cluster.py
  tests/functional/z_cluster/upgrade/test_check_pdb_post_upgrade.py
Labels: Verified, team/ecosystem, size/S, lgtm

#9905 Fix OADP and Gitops Operator install
  ocs_ci/deployment/deployment.py
  ocs_ci/templates/gitops-deployment/subscription.yaml
  ocs_ci/templates/oadp-deployment/subscription.yaml
Labels: Verified, size/M, lgtm, DR

#9961 Add DR prefix when creating s3bucket for hub recovery
  ocs_ci/deployment/deployment.py
Labels: Verified, size/XS, DR

#10105 removed osd_removal_job support for versions older than 4.6
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/M, lgtm

#10128 Pass secret key as one of the arguments to create credentials
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/XS, lgtm, DR

#10151 Fix OADP operator install
  ocs_ci/deployment/deployment.py
Labels: Verified, size/XS, lgtm, DR

#10122 add capacity via UI odf4.17
  ocs_ci/ocs/ui/add_replace_device_ui.py
  ocs_ci/ocs/ui/helpers_ui.py
Labels: Verified, size/XS, lgtm

#10163 Add carriage_return to const file
  ocs_ci/ocs/constants.py
Labels: size/XS, lgtm

#10154 Add IBM Cloud custom network
  conf/README.md
  conf/deployment/ibmcloud/ipi_1az_us_east1_rhcos_custom_vpc_3m_3w.yaml
  conf/deployment/ibmcloud/ipi_1az_us_south1_rhcos_custom_vpc_3m_3w.yaml
  ocs_ci/deployment/ibmcloud.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
  ocs_ci/utility/ibmcloud.py
Labels: Verified, team/ecosystem, size/L, lgtm

#10165 fixing the get_latest_release_version
  ocs_ci/ocs/utils.py
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#9859 Update dr_workload fixture and test_failover_and_relocate.py
  tests/conftest.py
  tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate.py
Labels: Verified, size/M, lgtm, DR, Squad/Turquoise

#10129 reboot nfs_client_vm if not accessible and retry connection
  tests/functional/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Labels: Verified, team/ecosystem, size/M, lgtm

#10120 Provider mode deployment with Hosted clusters
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/helpers/hypershift_base.py
  ocs_ci/deployment/helpers/lso_helpers.py
  ocs_ci/deployment/hosted_cluster.py
  ocs_ci/deployment/metallb.py
  ocs_ci/helpers/managed_services.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/storage_client.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/scale_lib.py
  ocs_ci/ocs/ui/deployment_ui.py
  tests/libtest/test_provider_create_hosted_cluster.py
Labels: size/L, lgtm

#10113 thresholds for pvc run of space alerts were changed. tuned hashes
  tests/functional/ui/test_alert_text.py
Labels: Verified, size/XS, lgtm

#9999 Create two tests: "test_stop_provider_endpoint_node_and_check_client_connection'" and "test_stop_provider_mgr_node_and_check_client_connection"
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/utility/decorators.py
  tests/functional/z_cluster/nodes/test_nodes_restart_hci.py
Labels: Verified, size/L, Squad/Brown, lgtm, provider-client

#10125 Update pools locator
  ocs_ci/ocs/ui/block_pool.py
  ocs_ci/ocs/ui/page_objects/edit_label_form.py
  ocs_ci/ocs/ui/page_objects/storage_system_details.py
  ocs_ci/ocs/ui/views.py
  tests/functional/ui/test_error_improvements.py
Labels: Verified, size/M, lgtm, Squad/Black

#8233 Test for Graceful node shutdown
  ocs_ci/ocs/node.py
  tests/cross_functional/system_test/test_graceful_nodes_shutdown.py
Labels: team/e2e, size/L, lgtm

#10170 Disabling test_auto_reclaim_space_multi_clones test
  tests/cross_functional/performance/csi_tests/test_auto_reclaim_space_multi_clones.py
Labels: size/S, performance, Squad/Gray, lgtm

#9956 Version details for DR operators
  ocs_ci/framework/__init__.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/utils.py
  ocs_ci/utility/utils.py
  ocs_ci/utility/version.py
  tests/conftest.py
Labels: Verified, team/ecosystem, size/L, lgtm

#10158 Adding post upgrade marker to tests/functional/pv/pv_services/test_rwop_pvc.py test
  tests/functional/pv/pv_services/test_rwop_pvc.py
Labels: size/XS, lgtm

#10159 Adding post upgrade marker to tests/functional/storageclass/test_cross_sc_clone_snap_restore.py test
  tests/functional/storageclass/test_cross_sc_clone_snap_restore.py
Labels: size/XS, lgtm

#10178 include back slash for url
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/XS, lgtm

#10166 Remove redundant pod disruption tests
  tests/functional/pv/pv_services/test_pvc_disruptive.py
  tests/functional/pv/pv_services/test_resource_deletion_during_pod_pvc_deletion.py
  tests/functional/pv/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
  tests/functional/pv/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: size/XXL, Squad/Green, lgtm

#10174 Fix UI login
  ocs_ci/ocs/ui/base_ui.py
Labels: size/XS, lgtm

#10176 Make Ceph Full threshold to be configurable
  conf/README.md
  conf/ocsci/ceph_full_threshold.yaml
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/M, lgtm

#10184 Fix the method to obtain pids of ceph daemons
  ocs_ci/helpers/disruption_helpers.py
Labels: Verified, size/S, Squad/Green, lgtm

#10136 Defaulting ocs-ci to ODF 4.17
  ocs_ci/framework/conf/default_config.yaml
  setup.py
Labels: team/ecosystem, size/S, lgtm

#10011 Longevity enhancements
  ocs_ci/helpers/e2e_helpers.py
  ocs_ci/ocs/longevity.py
  tests/cross_functional/conftest.py
  tests/cross_functional/longevity/test_stage2.py
  tests/cross_functional/longevity/test_stage3.py
  tests/cross_functional/longevity/test_stage4.py
Labels: Verified, team/e2e, size/L, lgtm, Longevity

#10197 Bumping webdriver-manager version to 4.0.2 due to selenium issue
  setup.py
Labels: Verified, size/XS, lgtm

#10169 ODF4.17 UI deployment, remove 'data protection' page
  ocs_ci/ocs/ui/deployment_ui.py
Labels: Verified, size/XS, lgtm, Squad/Black

#9910 Fix the issue in object expiration failure in system test runs
  ocs_ci/helpers/e2e_helpers.py
  tests/cross_functional/conftest.py
Labels: Verified, team/e2e, size/S, lgtm

#10212 Skip test_automated_recovery_from_stopped_node_and_start failed on Compact mode deployments
  ocs_ci/framework/pytest_customization/marks.py
  tests/functional/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#10188 [release-4.14]: download OCP nightly through GA'ed version incase of failures
  ocs_ci/utility/utils.py
  ocs_ci/utility/version.py
Labels: Verified, team/ecosystem, size/L, lgtm

#10190 [release-4.13]: download OCP nightly through GA'ed version incase of failures
  ocs_ci/utility/utils.py
  ocs_ci/utility/version.py
Labels: Verified, team/ecosystem, size/L, lgtm

#10191 [release-4.12]: download OCP nightly through GA'ed version incase of failures
  ocs_ci/utility/utils.py
  ocs_ci/utility/version.py
Labels: Verified, team/ecosystem, size/L, lgtm

#10219 Fix project for GCP to new odf-dev-test
  conf/deployment/gcp/ipi_1az_rhcos_3m_3w.yaml
  conf/deployment/gcp/ipi_1az_rhcos_3m_3w_shielded_compute.yaml
  conf/deployment/gcp/ipi_1az_rhcos_3m_3w_shielded_control_plane.yaml
  conf/deployment/gcp/ipi_1az_rhcos_3m_3w_shielded_machines.yaml
Labels: Verified, size/XS, lgtm

#10220 Release 4.13 gcp account change
  conf/deployment/gcp/ipi_1az_rhcos_3m_3w.yaml
Labels: size/XS, lgtm

#10214 Pytest jira plugin
  docs/writing_tests.md
  ocs_ci/framework/pytest_customization/marks.py
  setup.py
Labels: Verified, size/M, lgtm
