Repository red-hat-storage/ocs-ci, pull requests merged in 2024-08, with the labels that each got.

#10224 Fix cephfilesystem name in rox clone tests
  tests/functional/pv/pvc_clone/test_pvc_to_pvc_clone.py
Labels: Verified, size/S, Squad/Green, lgtm

#10218 Fixing validation for keys fro ciphertrust Thales KMS
  ocs_ci/utility/kms.py
Labels: Verified, team/ecosystem, size/M, lgtm

#10189 Fix floating tag for odf-tools image
  ocs_ci/helpers/helpers.py
Labels: size/XS, lgtm

#10232 Take more screenshot and add logs for BM LSO deployment
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/deployment_ui.py
Labels: team/ecosystem, size/S, lgtm

#9888 [release-4.15 backport] Remove the redundant util func `write_random_test_objects_to_s3_path` and adjust usage in affected tests
  ocs_ci/ocs/bucket_utils.py
  tests/functional/object/mcg/test_object_expiration.py
  tests/libtest/test_s3_tag_utils.py
Labels: Verified, size/L, Squad/Red, lgtm, cherry-pick

#9890 Skip the default backingstore override tests in deployments with limited connectivity
  tests/functional/object/mcg/test_default_backingstore_override.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#10106 Fixes TypeError while creating default backing_store
  ocs_ci/ocs/resources/backingstore.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#10183 Apply new pool workflow for 4.17 only
  ocs_ci/ocs/ui/block_pool.py
  ocs_ci/ocs/ui/page_objects/block_pools.py
  tests/functional/ui/test_error_improvements.py
Labels: Verified, size/S, lgtm, Squad/Black

#10037 adding setup_ui_class_factory fixture
  ocs_ci/ocs/ui/base_ui.py
  tests/conftest.py
  tests/cross_functional/ui/test_validation_ui.py
  tests/functional/object/mcg/ui/test_mcg_ui.py
  tests/functional/object/mcg/ui/test_namespace_store.py
  tests/functional/ui/test_pvc_ui.py
Labels: Verified, size/M, lgtm, Squad/Black

#10240 ignore rook-ceph-detect-version pods if FIPS checking
  ocs_ci/ocs/resources/fips.py
  ocs_ci/ocs/resources/pod.py
Labels: Verified, team/ecosystem, size/M, lgtm

#9646 [RDR] Enable ACM observability for DR monitoring dashboard on RHACM console
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/ui/acm_ui.py
  ocs_ci/templates/DR/multiclusterobservability.yaml
  ocs_ci/templates/DR/observability-metrics-configmap.yaml
  ocs_ci/templates/DR/thanos.yaml
Labels: Verified, size/L, lgtm, DR, Squad/Turquoise

#10181 Added a flag, mark_masters_schedulable to mark master nodes scheduleable
  ocs_ci/deployment/baremetal.py
  ocs_ci/deployment/provider_client/storage_client_deployment.py
  ocs_ci/ocs/resources/storage_client.py
  ocs_ci/templates/ocs-deployment/provider-mode/ocs_storagecluster.yaml
  ocs_ci/templates/ocs-deployment/provider-mode/ocs_storagecluster_updated.yaml
Labels: size/L, lgtm

#10231 [release-4.15] Skip test_automated_recovery_from_stopped_node_and_start on compact mode deployment
  ocs_ci/framework/pytest_customization/marks.py
  tests/functional/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#10152 RDR CNV workload updates for Appset pull model and unique namespace
  conf/ocsci/dr_workload.yaml
  tests/functional/disaster-recovery/regional-dr/test_cnv_app_failover_and_relocate.py
Labels: Verified, size/M, lgtm, DR

#10243 Pass ACM Backup Namespace to get OADP version
  ocs_ci/deployment/deployment.py
Labels: High Priority, Verified, size/XS, lgtm, DR

#10229 Wait and check for crashes before archiving them to avoid failures in later steps
  tests/functional/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/S, Squad/Brown, lgtm

#10271 Skip test which has active bugs, because of problems with bugzilla plugin
  tests/functional/z_cluster/cluster_expansion/test_resize_osd.py
Labels: team/ecosystem, size/XS, lgtm

#10257 hcp version request correction
  ocs_ci/deployment/helpers/hypershift_base.py
Labels: Verified, size/S, lgtm

#10265 Remove environment specific `disk_pattern` configuration from baremetal config files
  conf/deployment/baremetal/ai_1az_rhcos_nvme_intel_3m_3w.yaml
  conf/deployment/baremetal/upi_1az_rhcos_compact_mode.yaml
  conf/deployment/baremetal/upi_1az_rhcos_multus_cluster_nvme_intel_3m_3w.yaml
  conf/deployment/baremetal/upi_1az_rhcos_multus_nvme_intel_3m_3w.yaml
  conf/deployment/baremetal/upi_1az_rhcos_multus_public_nvme_intel_3m_3w.yaml
  conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_3w.yaml
  conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_4w.yaml
  conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_3m_5w.yaml
  conf/deployment/baremetal/upi_1az_rhcos_nvme_intel_mcg_only_3m_3w.yaml
  conf/deployment/baremetal/upi_1az_rhel_nvme_intel_3m_3w.yaml
Labels: team/ecosystem, size/S, lgtm

#10138 Remove stale dirs from tests/ and move all remaining tests to the new structure
  tests/conftest.py
  tests/disaster-recovery/__init__.py
  tests/e2e/__init__.py
  tests/functional/lvmo/conftest.py
  tests/functional/lvmo/test_lvm_alerts.py
  tests/functional/lvmo/test_lvm_clone_base.py
  tests/functional/lvmo/test_lvm_clone_bigger_than_disk.py
  tests/functional/lvmo/test_lvm_manual_diskpath.py
  tests/functional/lvmo/test_lvm_multi_clone.py
  tests/functional/lvmo/test_lvm_multi_snapshot.py
  tests/functional/lvmo/test_lvm_snapshot_base.py
  tests/functional/lvmo/test_lvm_snapshot_bigger_than_disk.py
  tests/functional/lvmo/test_lvmo_pvc_resize.py
  tests/functional/monitoring/test_monitoring_tool.py
  tests/functional/pv/pv_encryption/test_secrets_on_pods.py
  tests/functional/pv/pv_services/test_create_pvc_random_storage_class.py
  tests/functional/storageclass/test_cephfilesystem_creation.py
  tests/functional/storageclass/test_create_storage_class_pvc.py
  tests/internal/conftest.py
  tests/libtest/test_fio_fillup.py
  tests/libtest/test_skipif_ocp.py
  tests/libtest/test_update_catalogsource.py
  tests/manage/__init__.py
Labels: Verified, size/L, lgtm

#10200 Adding polarion ids to tests/functional/pv/pv_services/test_rwop_pvc_reclaim_space.py
  tests/functional/pv/pv_services/test_rwop_pvc_reclaim_space.py
Labels: Verified, size/XS, lgtm

#10201 Adding polarion ids to tests/functional/storageclass/test_cross_sc_clone_snap_restore.py
  tests/functional/storageclass/test_cross_sc_clone_snap_restore.py
Labels: Verified, size/S, lgtm

#10198 Adding polarion ids to tests/functional/pv/pv_services/test_rwop_pvc.py
  tests/functional/pv/pv_services/test_rwop_pvc.py
Labels: Verified, size/S, lgtm

#10199 Adding polarion id to tests/functional/pv/pv_services/test_pvc_migrate_rwo_to_rwop.py
  tests/functional/pv/pv_services/test_pvc_migrate_rwo_to_rwop.py
Labels: Verified, size/XS, lgtm

#10238 Skip recovery_cluster from checking token_exchange-pod
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/utils.py
Labels: size/M, lgtm

#10281 volume path for LSO disk operations
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/osd_operations.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/vsphere.py
Labels: team/ecosystem, size/M, lgtm

#10292 Increase timeout for change in the node rook ceph pod statuses after node failure
  tests/functional/z_cluster/nodes/test_check_pods_status_after_node_failure.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#10215 Add must-gather parameter for client cluster
  conf/deployment/fusion_hci_pc/client_bm_upi_1az_rhcos_nvme_2w.yaml
  conf/deployment/fusion_hci_pc/client_bm_upi_1az_rhcos_nvme_3w.yaml
  conf/deployment/fusion_hci_pc/provider_bm_upi_1az_rhcos_nvme_3m_3w.yaml
  ocs_ci/ocs/utils.py
Labels: Verified, size/XS, lgtm, provider-client

#10264 Fix disconnected ODF 4.17 deployment
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/S, lgtm

#10301 GLIBC version for Ubuntu
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#10308 Add runs_on_provider decorator in test_noobaa_postgres_cm_post_ocs_upgrade
  tests/functional/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/XS, lgtm, provider-client

#10305 Remove reduntant test_create_pvc_with_random_sc
  tests/functional/pv/pv_services/test_create_pvc_random_storage_class.py
Labels: size/M, Squad/Green, lgtm, redundant_test

#10280 allow standalone LSO deployment (without ODF)
  conf/README.md
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#10306 Skip test_crashcollector_pod_existence_on_ceph_pods_running_nodes on compact mode deployments
  tests/functional/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#10157 Install MCO operator on all acm clusters RDR
  ocs_ci/deployment/deployment.py
Labels: Verified, size/XS, lgtm, DR

#9971 Verify the owner of CSI deployments and daemonsets in provider and client
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/M, provider-client

#10304 Set the namespace dynamically in OC BS creation of GCP and Azure
  ocs_ci/ocs/bucket_utils.py
Labels: High Priority, Verified, size/S, MCG, Squad/Red, lgtm

#10322 use oc instead of specific rhel version in extracting client
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#10294 login_ui and namespace selection for rosa hcp clusters
  conf/deployment/aws/rosa_hcp_1az_3w_m5.12x.yaml
  conf/deployment/aws/rosa_hcp_1az_6w_m5.2x.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/utils.py
  ocs_ci/utility/prometheus.py
Labels: Verified, size/M, ui_automation, lgtm

#9555 [Close loop BZ: 2239208] Test case to create PVC in megabytes
  tests/functional/pv/pv_services/test_pvc_creation_in_megabytes.py
Labels: team/e2e, size/M, Customer defects, lgtm

#10323 Remove Bluestore-rdr check
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/S, lgtm, DR

#9501 Replica1 tests
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/replica_one.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/utility/utils.py
  tests/conftest.py
  tests/functional/storageclass/test_replica1.py
Labels: Test Case, Verified, size/XL, lgtm

#10149 GSS bug automation: #2240714 and #2188032
  tests/functional/object/mcg/test_object_versioning.py
  tests/functional/object/rgw/test_obc_quota.py
Labels: Verified, team/e2e, size/L, MCG, Customer defects, Squad/Red, lgtm

#10338 fix login issue
  ocs_ci/ocs/ui/base_ui.py
Labels: Verified, size/S, lgtm

#10343 update numpy and scipy version
  setup.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#10310 Fix test case test_selinux_relabel_for_existing_pvc[5] and remove the default arg value setting from dict in the function modify_deploymentconfig_replica_count
  ocs_ci/helpers/helpers.py
  tests/cross_functional/kcs/test_selinux_relabel_solution.py
Labels: Verified, size/XS, Squad/Magenta, lgtm, provider-client

#10332 Check the presence of ceph-csi pod
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/XS, lgtm

#10331 Add cephcsi-operator in the list of required csv
  ocs_ci/deployment/helpers/odf_deployment_helpers.py
  ocs_ci/ocs/defaults.py
Labels: Verified, size/XS, lgtm

#10253 Support cnv workloads dv/dvt
  ocs_ci/helpers/cnv_helpers.py
  ocs_ci/ocs/cnv/virtual_machine.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/cnv-vm-workload/vm-standalone-pvc/dv.yaml
  ocs_ci/templates/cnv-vm-workload/vm-standalone-pvc/pvc.yaml
  ocs_ci/templates/cnv-vm-workload/vm-standalone-pvc/vm.yaml
  tests/conftest.py
  tests/functional/workloads/cnv/test_vm_lifecycle_and_io.py
  tests/functional/workloads/cnv/test_vm_single_disk_hot_plugging_unplugging.py
Labels: Verified, team/e2e, size/L, Squad/Magenta, lgtm

#10339 PVC alert threshold checks added
  tests/functional/pv/pvc_resize/test_pvc_expansion_when_full.py
Labels: Verified, size/L, new feature, lgtm

#9542 [Close loop BZ: 2171225] Test case to run large chunk file IO
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/workloads/helper_scripts/chunk.py
  tests/functional/pv/pv_services/test_cephfs_pvc_with_chunk_size.py
Labels: Verified, team/e2e, size/L, Customer defects, lgtm

#10121 Add Must Gather Test to ODF4.17
  ocs_ci/ocs/must_gather/const_must_gather.py
Labels: Verified, size/S, lgtm

#10162 Adds test coverage for "Set credentials manually to an account" feature
  tests/functional/object/mcg/test_custom_credentials_using_mcg_cli.py
Labels: Verified, size/L, MCG, Squad/Red, lgtm

#10070 fix test_rgw_kafka_notifications
  tests/functional/workloads/app/amq/test_rgw_kafka_notifications.py
Labels: team/e2e, size/M, Squad/Magenta

#10302 This is for adding placement based workload
  conf/ocsci/mdr_workload.yaml
  ocs_ci/ocs/dr/dr_workload.py
  tests/conftest.py
Labels: size/L, lgtm, DR

#10267 Test cases for RDR Monitoring dashboard and UI failover/relocate support for Appset workloads
  ocs_ci/helpers/dr_helpers_ui.py
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/ui/acm_ui.py
  ocs_ci/ocs/ui/page_objects/page_navigator.py
  ocs_ci/ocs/ui/views.py
  tests/functional/disaster-recovery/regional-dr/test_rdr_monitoring_dashboard_ui.py
Labels: Verified, size/XL, lgtm, Squad/Turquoise, Squad/Black

#10286 In-transit configuration for provider mode
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/encryption.py
  ocs_ci/deployment/provider_client/storage_client_deployment.py
Labels: Verified, size/L, lgtm, provider-client

#10303 Support python 3.11
  setup.py
  tox.ini
Labels: Verified, team/ecosystem, size/XS, lgtm

#10352 Add second attempt to fetch the mountpoints from the node
  ocs_ci/helpers/helpers.py
Labels: Verified, size/XS, Squad/Green, lgtm

#10350 Ignore noobaa-endpoint pods leftovers in MCG tests
  ocs_ci/framework/testlib.py
  tests/functional/object/mcg/test_nsfs.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm

#10354 Created a method for pre cleanup required for lso install
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/helpers/lso_helpers.py
  ocs_ci/deployment/provider_client/storage_client_deployment.py
Labels: Verified, size/M, lgtm

#10213 [GSS] Test secrets are not exposed in Noobaa
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/functional/object/mcg/test_noobaa_db_cleartext_postgres_password.py
  tests/functional/object/mcg/test_noobaa_secret.py
Labels: Verified, team/e2e, size/L, MCG, Customer defects, Squad/Red, lgtm

#9973 [BZ-2249640] verify nodeAffinity for cephtoolbox pod
  ocs_ci/ocs/node.py
  tests/functional/pod_and_daemons/test_cephtoolbox_pod_nodeaffinity.py
Labels: Verified, team/e2e, size/L, lgtm, bugzilla/valid-bug

#10360 [DR] Improved backend volume deletion verification and removed redundant code
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/dr/dr_workload.py
  ocs_ci/ocs/resources/pvc.py
  tests/conftest.py
Labels: Verified, size/L, lgtm, DR, Squad/Turquoise

#10368 [release-4.15 backport] Ignore noobaa-endpoint pods leftovers in MCG tests
  ocs_ci/framework/testlib.py
  tests/functional/object/mcg/test_nsfs.py
Labels: size/S, MCG, Squad/Red, lgtm, cherry-pick

#10367 [release-4.16 backport] Ignore noobaa-endpoint pods leftovers in MCG tests
  ocs_ci/framework/testlib.py
  tests/functional/object/mcg/test_nsfs.py
Labels: size/S, MCG, Squad/Red, lgtm, cherry-pick

#10285 Rename hci metrics to provider metrics
  ocs_ci/ocs/metrics.py
  tests/functional/monitoring/prometheus/metrics/test_monitoring_defaults.py
Labels: Verified, size/S, Squad/Blue, lgtm, provider-client

#10369 remove extra doublequote in config file
  ocs_ci/framework/conf/ocp_version/ocp-4.13-ga-config.yaml
Labels: team/ecosystem, size/XS, lgtm

#10299 remove rgw user from external RHCS
  ocs_ci/deployment/helpers/external_cluster_helpers.py
Labels: Verified, team/ecosystem, size/M, lgtm

#10321 Removes CephBlockPool interface from parameterised argument
  ocs_ci/ocs/resources/cloud_manager.py
  tests/cross_functional/scale/noobaa/test_warp.py
Labels: Verified, size/S, Squad/Orange, lgtm
