Repository red-hat-storage/ocs-ci, pull requests merged in 2024-12, with the labels that each got.

#10935 Remove Bluestore-rdr check
  ocs_ci/deployment/deployment.py
Labels: High Priority, Verified, size/S, lgtm, DR

#10965 Deprecate test_amq_streamer_creation.py
  tests/functional/workloads/app/amq/test_amq_streamer_creation.py
Labels: size/XS, Squad/Magenta, lgtm

#10950 Remove unwanted tests that are already disabled
  tests/functional/pv/pv_services/test_ceph_daemon_kill_during_resource_creation.py
  tests/functional/pv/pv_services/test_ceph_daemon_kill_during_resource_deletion.py
  tests/functional/pv/pv_services/test_daemon_kill_during_pvc_pod_creation_and_io.py
Labels: size/XXL, Squad/Green, lgtm

#10912 Set the namespace of the NSFS interface deployment dynamically
  tests/conftest.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#10915 Wait for the ceph command to execute successfully in the rolling nodes terminate and rolling nodes restart tests
  ocs_ci/ocs/resources/pod.py
  tests/functional/z_cluster/nodes/test_nodes_restart.py
  tests/functional/z_cluster/nodes/test_rolling_terminate_and_recovery.py
Labels: Verified, size/M, Squad/Brown, lgtm

#10840 Update strategy for ODF upgrade testing
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/resources/daemonset.py
  tests/functional/upgrade/conftest.py
  tests/functional/upgrade/test_configuration.py
  tests/functional/upgrade/test_upgrade.py
Labels: Verified, size/L, upgrade, lgtm

#10932 Fixes dynamic namespace selection issue for test_account_update_with_custom_creds_using_cli script
  tests/functional/object/mcg/test_custom_credentials_using_mcg_cli.py
Labels: Verified, TestCase failing, size/XS, MCG, Squad/Red, lgtm, backport-required

#10964 config namespace reference is set to every odf cli call
  ocs_ci/helpers/odf_cli.py
  tests/functional/odf-cli/test_pvc_stale_volume_cleanup_cli.py
Labels: Verified, size/M, Squad/Brown, lgtm

#10942 remove gather_common_ceph_resources in external mg script
  scripts/bash/mg_external.sh
Labels: team/ecosystem, size/XS, lgtm

#10937 RBD namespace in external cluster
  conf/README.md
  conf/ocsci/external_rhcs_with_rbd_namespace.yaml
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/ocs/exceptions.py
Labels: Verified, team/ecosystem, size/M, lgtm

#10969 add skip_if_rosa_hcp
  tests/functional/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, TestCase failing, size/XS, lgtm

#10948 add skipp collecting data on CP for managed_cp. test_capacity_recovery
  ocs_ci/ocs/perftests.py
Labels: Verified, size/XS, lgtm

#10981 Fix black check
  ocs_ci/ocs/resources/daemonset.py
Labels: size/XS, lgtm

#10702 Move awscli pod CA setup related commands to container startup
  ocs_ci/ocs/awscli_pod.py
Labels: High Priority, Verified, size/M, MCG, Squad/Red, lgtm

#10954 Add odf-dependencies to csv check
  ocs_ci/deployment/helpers/odf_deployment_helpers.py
  ocs_ci/ocs/defaults.py
Labels: Verified, size/XS, lgtm

#10979 Download subctl binary in anycase
  ocs_ci/deployment/acm.py
  ocs_ci/ocs/utils.py
Labels: Verified, size/M, lgtm

#10987 Download subctl binary in anycase
  ocs_ci/deployment/acm.py
  ocs_ci/ocs/utils.py
Labels: size/M, lgtm

#10854 add-new-test--test_add_ocs_node_non_default_machinepool
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/machinepool.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/platform_nodes.py
  tests/functional/z_cluster/cluster_expansion/conftest.py
  tests/functional/z_cluster/cluster_expansion/test_nodes_rosa_hcp.py
Labels: Verified, size/L, new feature, lgtm

#10994 Remove redundant test of basic cephfs and rbd PVC
  tests/functional/storageclass/test_create_storage_class_pvc.py
Labels: size/L, Squad/Green, lgtm

#10953 Added code to select active mgr pod always
  tests/functional/workloads/ocp/monitoring/test_monitoring_on_negative_scenarios.py
Labels: Verified, team/e2e, size/S, Squad/Magenta, lgtm

#10852 [Red Squad] - Remove obsolete and redundant tests
  tests/functional/object/mcg/test_bucket_creation_deletion.py
  tests/functional/object/mcg/test_bucket_deletion.py
  tests/functional/object/mcg/test_multicloud.py
  tests/functional/object/mcg/test_namespace_crd.py
  tests/functional/object/mcg/test_object_integrity.py
  tests/functional/object/mcg/test_write_to_bucket.py
  tests/functional/upgrade/test_noobaa.py
  tests/functional/upgrade/test_resources.py
Labels: size/L, Squad/Red, lgtm

#11014 Update list of packages required for 4.18 disconected deployment
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#10999 delete COS bucket during teardown of cluster
  ocs_ci/deployment/ibmcloud.py
  ocs_ci/ocs/resources/backingstore.py
  ocs_ci/utility/ibmcloud.py
  setup.py
Labels: Verified, team/ecosystem, size/L, lgtm

#11018 fix typo in retrieve_verification_mode
  ocs_ci/ocs/bucket_utils.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#11020 Remove redundant MS tests
  tests/cross_functional/system_test/multicluster/test_ms_markers.py
  tests/cross_functional/system_test/multicluster/test_sanity_ms.py
  tests/cross_functional/system_test/multicluster/test_switch_to_correct_index_at_setup.py
Labels: size/L, Squad/Magenta, lgtm, provider-client

#10657 <GSS Closed Loop BZ:2253013>: Test to create SC & CBP from UI and validate pg_num
  ocs_ci/ocs/cluster.py
  tests/cross_functional/ui/test_create_pool_block_pool.py
Labels: Verified, team/e2e, size/M, Customer defects, lgtm, Squad/Black

#10945 Removes redundant tests from Orange squad
  tests/cross_functional/scale/noobaa/test_scale_endpoint.py
  tests/cross_functional/scale/noobaa/test_scale_obc_create_delete.py
  tests/cross_functional/scale/noobaa/test_scale_obc_creation.py
  tests/cross_functional/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
  tests/cross_functional/scale/test_scale_3_OCS_worker_nodes_and_1500_PVCs.py
  tests/cross_functional/scale/test_scale_amq.py
  tests/cross_functional/scale/test_scale_osds_fill_75%_reboot_workers.py
  tests/cross_functional/scale/test_scale_pgsql.py
Labels: size/M, Squad/Orange, lgtm

#10940 Add new production configuration for job intransit encryption
  conf/deployment/vsphere/ipi_1az_rhcos_vsan_3m_6w_intransit_encryption.yaml
Labels: size/S, lgtm

#11030 Added 4.18 to must gather const
  ocs_ci/ocs/must_gather/const_must_gather.py
Labels: Verified, size/S, Squad/Brown, lgtm

#11024 Rosa hcp node labeling
  conf/README.md
  conf/deployment/aws/rosa_hcp_1az_3w_m5.12x.yaml
  conf/deployment/aws/rosa_hcp_1az_6w_m5.2x.yaml
  ocs_ci/deployment/rosa.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/machinepool.py
  ocs_ci/utility/rosa.py
Labels: Verified, size/M, platforms, lgtm

#10910 fix error in test 0.2
  ocs_ci/utility/deployment_openshift_logging.py
  tests/conftest.py
Labels: Verified, size/M, lgtm

#11031 test_detach_attach_worker_volume add jira ticket to prevent cascade skips
  tests/functional/z_cluster/nodes/test_disk_failures.py
Labels: size/XS, lgtm

#10990 add managed platforms to exclusion and stop collect rgw-data for test
  tests/functional/z_cluster/test_rook_ceph_log_rotate.py
Labels: Verified, size/XS, lgtm

#11016 test_obc_creation_and_deletion add dynamic noobaa sc name
  tests/functional/object/mcg/ui/test_mcg_ui.py
Labels: Verified, size/M, lgtm

#10705 [release-4.16] Backport RDR Fixes and Enhancements
  conf/ocsci/dr_workload.yaml
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/dr/dr_workload.py
  ocs_ci/ocs/resources/drpc.py
  ocs_ci/ocs/resources/pvc.py
  pytest.ini
  tests/conftest.py
  tests/functional/disaster-recovery/regional-dr/test_cnv_app_failover_and_relocate.py
  tests/functional/disaster-recovery/regional-dr/test_failover.py
  tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate.py
  tests/functional/disaster-recovery/regional-dr/test_managed_cluster_node_failure.py
  tests/functional/disaster-recovery/regional-dr/test_negative_failover_relocate_ui.py
  tests/functional/disaster-recovery/regional-dr/test_node_operations_during_failover_relocate.py
  tests/functional/disaster-recovery/regional-dr/test_rdr_monitoring_dashboard_ui.py
  tests/functional/disaster-recovery/regional-dr/test_relocate.py
  tests/functional/disaster-recovery/regional-dr/test_sequential_failover.py
  tests/functional/disaster-recovery/regional-dr/test_sequential_relocate.py
Labels: Verified, size/XXL, lgtm, DR, Squad/Turquoise

#10922 CNV vm pvc/dv/dvt cloning ops
  ocs_ci/helpers/cnv_helpers.py
  ocs_ci/ocs/cnv/virtual_machine.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/cnv-vm-workload/clone_dv.yaml
  ocs_ci/templates/cnv-vm-workload/dv_cluster_role.yaml
  ocs_ci/templates/cnv-vm-workload/dv_role_binding.yaml
  ocs_ci/templates/cnv-vm-workload/vm.yaml
  tests/conftest.py
  tests/functional/workloads/cnv/test_vm_cloning_ops.py
Labels: Verified, team/e2e, size/XL, lgtm

#10458 Provider-client context for in-transit verification tests
  ocs_ci/framework/__init__.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/functional/encryption/test_intransit_encryption_sanity.py
  tests/functional/encryption/test_mon_failure_in_intransit_encryption.py
Labels: Verified, size/L, lgtm

#9925 Fix bad file name
  -
  tests/functional/upgrade/test_ms_upgrade.py
Labels: size/L, lifecycle/stale, lgtm, Squad/Yellow

#10924 [MCG] Assert when objects are not replicated in MCG replication system test and fix replication sync issue
  tests/cross_functional/system_test/test_mcg_replication_with_disruptions.py
Labels: Verified, team/e2e, size/S, Squad/Magenta, lgtm

#11005 improve destroy rosa hcp cluster
  ocs_ci/deployment/rosa.py
  ocs_ci/utility/rosa.py
Labels: TestCase failing, Code/Infra, size/S, platforms, lgtm

#10618 Check for Kube Object Sync time before running failover for Discovered Apps
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/dr/dr_workload.py
  ocs_ci/ocs/resources/drpc.py
  tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate_discovered_apps.py
Labels: Verified, size/M, lgtm, DR

#11051 Skip test_securityContext_in_Crashcollector test in external mode deployment
  tests/functional/pv/pv_encryption/test_secrets_on_pods.py
Labels: size/XS, lgtm

#11049 Adds label parameter to session-fedora-pod
  ocs_ci/templates/app-pods/fedora_with_linuxtar_files.yaml
Labels: TestCase failing, size/XS, scale, MCG, Squad/Orange, lgtm

#10906 Multus for vsphere
  conf/deployment/vsphere/upi_1az_rhcos_multus_public_cluster_vsan_3m_3w.yaml
  ocs_ci/deployment/vmware.py
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocs-deployment/node_network_configuration_policy.yaml
  ocs_ci/utility/vsphere.py
Labels: size/L, lgtm

#11050 mcg-cli delete for object which doesn't exist
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/objectbucket.py
Labels: Verified, team/ecosystem, size/S, lgtm

#11061 UI deployment verification for operators
  ocs_ci/ocs/ui/deployment_ui.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#11065 [ROSA HCP] test_nodereplacement_proactive - fixed
  ocs_ci/ocs/node.py
Labels: Verified, size/S, lgtm

#11047 get_ceph_tools_pod - stop collecting and printing yaml's of all pods
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/S, lgtm

#11070 Revert "[release-4.16] get_ceph_tools_pod - stop collecting and printing yaml's of all pods"
  ocs_ci/ocs/resources/pod.py
Labels: size/S, lgtm

#11069 Revert "get_ceph_tools_pod - stop collecting and printing yaml's of all pods"
  ocs_ci/ocs/resources/pod.py
Labels: size/S, lgtm

#11042 add vsphere upi compact mode configs and related automation
  conf/deployment/vsphere/upi_1az_rhcos_vsan_compact_mode_3m_0w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_compact_mode_3m_0w_disconnected.yaml
  ocs_ci/deployment/vmware.py
  ocs_ci/utility/load_balancer.py
Labels: Verified, team/ecosystem, size/M, lgtm

#10673 create multiple cnv workloads
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/cnv-vm-workload/cnv_vm_workload.yaml
  tests/conftest.py
  tests/functional/workloads/cnv/test_multi_vm_configurations.py
Labels: Verified, size/L, lgtm

#11045 vm snapshot test case
  ocs_ci/helpers/cnv_helpers.py
  ocs_ci/ocs/cnv/virtual_machine.py
  tests/conftest.py
  tests/functional/workloads/cnv/test_vm_snapshot_cloning_ops.py
Labels: Verified, team/e2e, size/L, lgtm

#11057 [ROSA HCP] exclude external dns if unavailable in CLI
  ocs_ci/ocs/ui/odf_topology.py
  ocs_ci/ocs/ui/page_objects/odf_topology_tab.py
Labels: Verified, TestCase failing, size/XS, lgtm

#11079 stretch cluster add capacity with ssd disks
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/S, lgtm

#11019 Deploy an external mode cluster and create resources with the rbd rados namespace
  ocs_ci/deployment/helpers/external_cluster_helpers.py
Labels: Verified, team/ecosystem, size/XS, new feature, lgtm

#11046 Adding a new test file for mcg cli commands validation with bucket list command verification
  tests/functional/object/mcg/test_mcg_cli.py
Labels: Verified, size/M, MCG, Squad/Red, lgtm

#11055 Adds custom config to verify dedup feature
  ocs_ci/ocs/constants.py
  tests/conftest.py
  tests/functional/object/mcg/test_write_to_bucket.py
Labels: High Priority, Verified, size/S, MCG, Squad/Red, lgtm

#11040 redesign of bucket page, init changes
  ocs_ci/ocs/ui/page_objects/buckets_tab.py
  ocs_ci/ocs/ui/page_objects/confirm_dialog.py
  ocs_ci/ocs/ui/page_objects/object_storage.py
  ocs_ci/ocs/ui/page_objects/page_navigator.py
  ocs_ci/ocs/ui/page_objects/resource_list.py
  ocs_ci/ocs/ui/page_objects/resource_page.py
  ocs_ci/ocs/ui/views.py
  tests/functional/object/mcg/ui/test_mcg_ui.py
Labels: Verified, TestCase failing, size/L, lgtm
