Repository red-hat-storage/ocs-ci, pull requests merged in 2024-02, with the labels that each got.

#9185 Test directory changes for performance tests
  tests/cross_functional/performance/csi_tests/test_auto_reclaim_space_multi_clones.py
  tests/cross_functional/performance/csi_tests/test_bulk_pod_attachtime_performance.py
  tests/cross_functional/performance/csi_tests/test_pod_attachtime.py
  tests/cross_functional/performance/csi_tests/test_pod_reattachtime.py
  tests/cross_functional/performance/csi_tests/test_pvc_bulk_clone_performance.py
  tests/cross_functional/performance/csi_tests/test_pvc_bulk_creation_deletion_performance.py
  tests/cross_functional/performance/csi_tests/test_pvc_clone_performance.py
  tests/cross_functional/performance/csi_tests/test_pvc_creation_deletion_performance.py
  tests/cross_functional/performance/csi_tests/test_pvc_multi_clone_performance.py
  tests/cross_functional/performance/csi_tests/test_pvc_multi_snapshot_performance.py
  tests/cross_functional/performance/csi_tests/test_pvc_snapshot_performance.py
  tests/cross_functional/performance/io_workload/test_fio_benchmark.py
  tests/cross_functional/performance/io_workload/test_io_performance.py
  tests/cross_functional/performance/io_workload/test_perf_pgsql.py
  tests/cross_functional/performance/io_workload/test_small_file_workload.py
  tests/cross_functional/performance/mcg/test_mcg_cosbench.py
Labels: size/XS, lgtm

#9262 use us-east-2c availability zone for single AZ configs
  conf/deployment/aws/ipi_1az_rhcos_3m_3w.yaml
  conf/deployment/aws/ipi_1az_rhcos_3m_3w_thales.yaml
  conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v1.yaml
  conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v1_external_with_namespace.yaml
  conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v2.yaml
  conf/deployment/aws/ipi_1az_rhcos_3m_3w_vault_v2_external_with_namespace.yaml
  conf/deployment/aws/ipi_1az_rhcos_lowerreq_3m_3w.yaml
  conf/deployment/aws/ipi_1az_rhcos_lso_3m_3w.yaml
  conf/deployment/aws/ipi_1az_rhcos_lso_sno.yaml
Labels: Verified, team/ecosystem, size/M, lgtm

#9267 Add the sleep param to the function "wait_for_nodes_status"
  ocs_ci/ocs/node.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#9257 Downgrade the boto3 version from 1.34.14 to 1.24.96
  setup.py
Labels: High Priority, Needs Testing, workaround, size/XS, MCG, Squad/Red, lgtm

#9100 Movement of Scale tests from e2e dir to cross-functional dir
  tests/cross_functional/scale/conftest.py
  tests/cross_functional/scale/test_cephfs_many_files.py
  tests/cross_functional/scale/test_osd_node_balancing.py
  tests/cross_functional/scale/test_pods_are_not_oomkilled_while_running_ios.py
  tests/cross_functional/scale/test_pv_scale_and_respin_ceph_pods.py
  tests/cross_functional/scale/test_pv_scale_ocs_create_delete_pvcs.py
  tests/cross_functional/scale/test_pvc_creation_deletion_scale.py
  tests/cross_functional/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
  tests/cross_functional/scale/test_scale_3_OCS_worker_nodes_and_1500_PVCs.py
  tests/cross_functional/scale/test_scale_amq.py
  tests/cross_functional/scale/test_scale_osds_fill_75%_reboot_workers.py
  tests/cross_functional/scale/test_scale_pgsql.py
  tests/cross_functional/scale/test_scale_pvc_expand.py
  tests/cross_functional/scale/test_scale_small_file_workload.py
  tests/cross_functional/scale/upgrade/test_upgrade_with_scaled_pvcs_pods.py
Labels: Verified, size/XS, scale, lgtm

#9202 Create the node functionalities for IBMCloud with Bare Metal
  conf/deployment/fusion_hci_pc/provider_bm_upi_1az_rhcos_nvme_3m_3w.yaml
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/ibmcloud_bm.py
  tests/functional/z_cluster/nodes/test_nodes_restart_hci.py
Labels: Verified, size/XL, lgtm, provider-client

#9285 [release-4.14 backport] Downgrade the boto3 version from 1.34.14 to 1.24.96
  setup.py
Labels: High Priority, workaround, size/XS, MCG, Squad/Red, lgtm

#9286 [release-4.13 backport] Downgrade the boto3 version from 1.34.14 to 1.24.96
  setup.py
Labels: High Priority, workaround, size/XS, MCG, Squad/Red, lgtm

#9287 [release-4.12 backport] Downgrade the boto3 version from 1.34.14 to 1.24.96
  setup.py
Labels: High Priority, workaround, size/XS, MCG, Squad/Red, lgtm

#9291 Increase the timeout for internal bucket health verification
  tests/functional/object/mcg/test_admission_control.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm

#9121 MDR+CNV app deployment and failover/relocate
  conf/ocsci/mdr_workload.yaml
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/dr/dr_workload.py
  tests/conftest.py
  tests/functional/disaster-recovery/metro-dr/test_cnv_app_failover_relocate.py
Labels: Test Case, Verified, team/e2e, size/XL, lgtm, DR

#9293 Extend timeout for ocp deployment via Assisted Installer
  ocs_ci/deployment/assisted_installer.py
Labels: team/ecosystem, size/XS, lgtm

#9274 restructure baremetal configuration
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/baremetal.py
Labels: Verified, team/ecosystem, size/L, lgtm

#9290 Fix ES issue
  ocs_ci/ocs/perfresult.py
  ocs_ci/ocs/perftests.py
Labels: Verified, size/S, lgtm

#9279 update assisted_installer code base on recent changes in api
  ocs_ci/deployment/assisted_installer.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#9266 Fix stretchcluster_required marker
  ocs_ci/framework/pytest_customization/marks.py
Labels: Verified, team/e2e, size/XS, lgtm

#9309 Fix subcmd string check
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/XS, lgtm

#8193 Test overriding the noobaa-default backingstore + add support for RGW backingstore creation
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/backingstore.py
  ocs_ci/ocs/resources/mcg.py
  tests/conftest.py
  tests/functional/object/mcg/test_bucket_deletion.py
  tests/functional/object/mcg/test_default_backingstore_override.py
  tests/functional/object/mcg/test_write_to_bucket.py
Labels: Needs Testing, size/XL, MCG, Squad/Red, lgtm, MCG-4.14, backport-required

#9259 Test role capabilities for ceph-objectstoreuser CRD
  ocs_ci/ocs/constants.py
  ocs_ci/templates/rgw/cephobjectstoreuser.yaml
  tests/functional/object/rgw/test_cephobjectstore_user.py
Labels: Verified, team/e2e, size/M, MCG, Customer defects, Squad/Red, lgtm

#9117 CSI-Addons CR resources should not be editable after creation in 4.15
  tests/functional/pv/pv_services/test_cr_resources_validation.py
Labels: Verified, size/S, Squad/Green, lgtm

#9264 Test if pv-pool backingstore reaching rejected phase in FIPS cluster
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/constants.py
  tests/functional/object/mcg/test_pv_pool.py
Labels: Verified, team/e2e, size/M, MCG, Customer defects, Squad/Red, lgtm

#9306 Add performance profile for deployment
  conf/README.md
  conf/ocsci/performance_profiles/balanced.yaml
  conf/ocsci/performance_profiles/lean.yaml
  conf/ocsci/performance_profiles/performance.yaml
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/S, lgtm

#9288 Ignore 'check if MCG root secret is public' if we use MS
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/XS, Managed Services, lgtm

#8694 [release-4.13] Fixed in-transit encryption tests failure for external mode cluster (…
  ocs_ci/ocs/resources/storage_cluster.py
Labels: size/S, lgtm

#8629 cherry picked pr 7884 to release 4.13
  tests/manage/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Labels: Verified, size/S, Squad/Brown, lifecycle/stale, lgtm

#9281 restructure baremetal configuration - backport 4.14
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/baremetal.py
Labels: Verified, team/ecosystem, size/L, lgtm

#9282 restructure baremetal configuration - backport 4.13
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/baremetal.py
Labels: Verified, team/ecosystem, size/L, lgtm

#9283 restructure baremetal configuration - backport 4.12
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/baremetal.py
Labels: Verified, team/ecosystem, size/L, lgtm

#9284 restructure baremetal configuration - backport 4.11
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/baremetal.py
Labels: Verified, team/ecosystem, size/L, lgtm

#9305 [MDR] Change msa name
  ocs_ci/deployment/deployment.py
Labels: bug, Verified, size/XS, lgtm, DR

#9296 Use cluster context with cluster resources and add test - write to bucket from client
  ocs_ci/ocs/awscli_pod.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/objectbucket.py
  tests/conftest.py
  tests/functional/object/mcg/test_provider_client.py
Labels: Verified, size/L, Squad/Red, lgtm, provider-client

#9313 Update MCG bucket policy usage to fix MalformedPolicy errors
  ocs_ci/ocs/resources/bucket_policy.py
  tests/conftest.py
  tests/functional/object/mcg/flowtest/test_mcg_namespace_disruptions_crd.py
  tests/functional/object/mcg/test_bucket_policy.py
Labels: High Priority, Verified, size/M, MCG, Squad/Red, lgtm

#9324 Revert "Only apply region node to worker nodes for noobaa IBM Cloud C…
  ocs_ci/utility/ibmcloud.py
Labels: size/XS, lgtm

#9325 Revert "Only apply region node to worker nodes for noobaa IBM Cloud C…
  ocs_ci/utility/ibmcloud.py
Labels: team/ecosystem, size/XS, lgtm

#9331 Register missing marks in pytest.ini to avoid warnings
  pytest.ini
Labels: team/ecosystem, size/S, lgtm

#9082 Test Rook Ceph OSD Flapping GSS BZ-2223959
  ocs_ci/helpers/helpers.py
  tests/functional/z_cluster/test_rook_ceph_osd_flapping.py
Labels: Verified, team/e2e, size/L, Customer defects, lgtm

#8210 Test the mcg object-expiration policy
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/mcg_lifecycle_policies.py
  ocs_ci/utility/utils.py
  tests/functional/object/mcg/test_object_expiration.py
  tests/libtest/test_s3_tag_utils.py
Labels: Verified, size/XXL, MCG, Squad/Red, lgtm, MCG-4.14

#9321 Add the `skipif_disconnected_cluster` decorator to `test_log_based_bucket_replication.py`
  tests/functional/object/mcg/test_log_based_bucket_replication.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm

#9014 [RDR] Skip deletion of drpc.yaml when deleting Subscription-based workloads
  ocs_ci/ocs/dr/dr_workload.py
Labels: Verified, size/S, lgtm, DR, Squad/Turquoise

#9276 [RDR] Exclude PVCs created by VolSync when fetching image_uuids
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/XS, lgtm, DR, Squad/Turquoise

#9273 Enhancements for test_pvc_delete_subvolumegroup.py
  tests/manage/pv_services/test_pvc_delete_subvolumegroup.py
Labels: Verified, size/XS, Squad/Green, lgtm

#9154 GSS BZ-2214838 Automation, Test Rook Reclaim Namespace
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/resources/pod.py
  tests/functional/pv/space_reclaim/test_rook_reclaim_namespace.py
  tests/functional/z_cluster/test_rook_ceph_osd_flapping.py
Labels: Verified, team/e2e, size/L, Customer defects, lgtm

#9277 Bumps ACM and Submariner versions for OCP 4.15 and later
  conf/ocsci/acm_2.10.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.15-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.16-config.yaml
Labels: Verified, size/S, lgtm, DR, Squad/Turquoise

#9330 Move to pytest-order plugin out of not maintained pytest-ordering
  ocs_ci/framework/pytest_customization/marks.py
  setup.py
  tests/functional/z_cluster/upgrade/test_check_pdb_post_upgrade.py
Labels: Verified, team/ecosystem, size/S, lgtm

#8993 Refined in-transit encryption test cases.
  ocs_ci/ocs/resources/storage_cluster.py
  tests/functional/encryption/test_intransit_encryption_sanity.py
  tests/functional/encryption/test_mon_failure_in_intransit_encryption.py
Labels: Verified, size/M, lgtm

#9337 MDR 4.14 deployment fixes
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/XS, lgtm

#9275 use k8s-cluster-name in external mode
  conf/ocsci/enable_restricted_auth_permission_with_cluster_name.yaml
  conf/ocsci/enable_restricted_auth_permission_with_k8s_cluster_name.yaml
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, team/ecosystem, size/S, lgtm

#9356 bump package versions for vulnerability in cryptography
  setup.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#9271 Tune the UI tests for Provider
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/odf_topology.py
  ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
  ocs_ci/ocs/ui/page_objects/object_bucket_claims_tab.py
  ocs_ci/ocs/ui/page_objects/object_storage.py
  ocs_ci/ocs/ui/page_objects/odf_topology_tab.py
  ocs_ci/ocs/ui/page_objects/page_navigator.py
  ocs_ci/ocs/ui/pvc_ui.py
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/ui/views.py
  tests/conftest.py
  tests/cross_functional/ui/test_add_capacity_ui.py
  tests/cross_functional/ui/test_create_pool_block_pool.py
  tests/cross_functional/ui/test_creation_and_deletion_of_sc_and_rbdpool.py
  tests/cross_functional/ui/test_odf_topology.py
  tests/cross_functional/ui/test_validation_ui.py
  tests/functional/ui/test_capacity_breakdown_ui.py
  tests/functional/ui/test_error_improvements.py
  tests/functional/ui/test_non_admin_user.py
  tests/functional/ui/test_pvc_ui.py
  tests/functional/ui/test_quickstarts.py
Labels: size/XL, lgtm, Squad/Black, provider-client

#9358 Passing correct accessmode to the tests pvc
  tests/functional/pv/pvc_clone/test_pvc_to_pvc_clone.py
Labels: size/S, lgtm

#8367 4.14 System test: Test MCG object expiration with disruptions like node drain, restart, nb db recovery
  ocs_ci/helpers/e2e_helpers.py
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/pod.py
  tests/conftest.py
  tests/cross_functional/conftest.py
  tests/cross_functional/system_test/test_object_expiration.py
  tests/functional/workloads/app/amq/test_rgw_kafka_notifications.py
Labels: Verified, team/e2e, size/XL, MCG, Squad/Red, lgtm

#9148 Move noobaa scale and upgrade tests to cross_functional dir.
  tests/cross_functional/scale/noobaa/test_hsbench.py
  tests/cross_functional/scale/noobaa/test_list_objects.py
  tests/cross_functional/scale/noobaa/test_scale_bucket_replication.py
  tests/cross_functional/scale/noobaa/test_scale_endpoint.py
  tests/cross_functional/scale/noobaa/test_scale_namespace_crd.py
  tests/cross_functional/scale/noobaa/test_scale_namespace_rpc.py
  tests/cross_functional/scale/noobaa/test_scale_obc_create_delete.py
  tests/cross_functional/scale/noobaa/test_scale_obc_creation.py
  tests/cross_functional/scale/noobaa/test_scale_obc_creation_repsin_noobaa_pods.py
  tests/cross_functional/scale/noobaa/test_scale_obc_start_time_respin_noobaa_pods.py
  tests/cross_functional/scale/noobaa/test_warp.py
  tests/cross_functional/scale/upgrade/test_upgrade_with_scaled_obc.py
  tests/cross_functional/scale/upgrade/test_upgrade_with_scaled_rgw_obc.py
Labels: size/XS, scale, MCG, lgtm

#9248 CNV automation: Classes and helper functions - Virtctl, VirtualMachine, VirtualMachineInstance and VM workloads
  ocs_ci/helpers/cnv_helpers.py
  ocs_ci/ocs/cnv/virtctl.py
  ocs_ci/ocs/cnv/virtual_machine.py
  ocs_ci/ocs/cnv/virtual_machine_instance.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/templates/cnv-deployment/vm-secret.yaml
  ocs_ci/templates/cnv-vm-workload/vm-standalone-pvc/pvc.yaml
  ocs_ci/templates/cnv-vm-workload/vm-standalone-pvc/source.yaml
  ocs_ci/templates/cnv-vm-workload/vm-standalone-pvc/vm.yaml
  tests/functional/workloads/cnv/test_vm_lifecycle_and_io.py
  tests/functional/workloads/cnv/test_vm_single_disk_hot_plugging_unplugging.py
Labels: Verified, team/e2e, size/XXL, lgtm

#9359 display test case which breaks ceph health in reports/email
  ocs_ci/utility/utils.py
  tests/test_failure_propagator.py
Labels: Verified, size/XS, lgtm

#9376 Get the HCI provider IBMCloud Baremetal machines by the node names instead of the node IPs
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/ibmcloud_bm.py
Labels: Verified, size/S, lgtm, provider-client

#9364 Create a new image for Fedora with FIO
  ocs_ci/helpers/helpers.py
  ocs_ci/templates/app-pods/fedora_dc.yaml
  tests/functional/workloads/ocp/registry/test_pod_from_registry.py
Labels: size/XS, lgtm

#9329 Pull the mcg-cli and odf-cli images from same function retrieve_cli_binary function
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/mcg.py
Labels: Needs Testing, Verified, size/L, lgtm

#9094 Test to verify the hub restore when active hub down following failover and relocate of app
  ocs_ci/deployment/deployment.py
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/dr/dr_workload.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/utils.py
  ocs_ci/templates/ocs-deployment/multicluster/restore.yaml
  tests/conftest.py
  tests/functional/disaster-recovery/metro-dr/test_active_hub_down_and_restore.py
Labels: size/XL, lgtm, DR

#9385 use infraID in ccoctl
  conf/deployment/ibmcloud/ipi_3az_rhcos_3m_3w.yaml
  ocs_ci/deployment/ibmcloud.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/utility/utils.py
Labels: Needs Deployment Testing, team/ecosystem, size/M, lgtm
