Repository red-hat-storage/ocs-ci, pull requests merged in 2024-01, with the labels that each got.

#9096 catch botocore exception for fetching bucket versioning
  ocs_ci/ocs/resources/objectbucket.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#9101 Fixes Invalid principal in policy issue
  tests/manage/mcg/test_bucket_policy.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#9099 Fixes bucket policy issue
  tests/manage/mcg/test_bucket_policy.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#9054 [release-4.12 backport] Refactor nsfs_bucket_factory_fixture and fix various NSFS issues
  ocs_ci/ocs/resources/mcg_params.py
  ocs_ci/ocs/resources/objectbucket.py
  ocs_ci/ocs/resources/pod.py
  tests/conftest.py
  tests/manage/mcg/test_nsfs.py
Labels: Verified, size/L, MCG, Squad/Red, lgtm, MCG-4.12, cherry-pick

#9053 [release-4.13 backport] Refactor nsfs_bucket_factory_fixture and fix various NSFS issues
  ocs_ci/ocs/resources/mcg_params.py
  ocs_ci/ocs/resources/objectbucket.py
  ocs_ci/ocs/resources/pod.py
  tests/conftest.py
  tests/manage/mcg/test_nsfs.py
Labels: Verified, size/L, MCG, Squad/Red, lgtm, MCG-4.13, cherry-pick

#9058 Restructured nfs-feature testcases
  tests/functional/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Labels: size/XS, Squad/Brown, lgtm

#9106 Append custom prefixes at start of dictionary for AWS cleanup script
  ocs_ci/cleanup/aws/cleanup.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#9076 Test automation for encrypted volume expansion with vault and KMIP co…
  ocs_ci/helpers/helpers.py
  tests/functional/pv/pv_encryption/test_encrypted_pvc_no_expansion_option.py
  tests/functional/pv/pv_encryption/test_encrypted_rbd_volume_expansion.py
Labels: Verified, size/L, lgtm

#9103 Add polarion IDs in test_ceph_capacity_recovery.py and test_auto_recl…
  tests/functional/pv/pv_services/test_ceph_capacity_recovery.py
  tests/functional/pv/space_reclaim/test_auto_reclaim_space_cronjob.py
Labels: size/XS, lgtm

#9113 Fixes:8872
  tests/functional/pv/pv_services/test_write_to_cephfs_pvc_with_nonroot_user.py
Labels: Verified, size/XS, lgtm

#9114 backport fix 9113
  tests/manage/pv_services/test_write_to_cephfs_pvc_with_nonroot_user.py
Labels: Verified, size/XS, lgtm

#9072 Use COS as noobaa backing store for IBM Cloud IPI
  ocs_ci/deployment/deployment.py
  ocs_ci/utility/ibmcloud.py
Labels: Verified, team/ecosystem, size/S, lgtm

#8171 Combine pv_services disruption testcases
  tests/functional/pv/pv_services/test_resource_deletion_during_pvc_pod_creation_deletion_and_io.py
Labels: Test Case, Verified, team/manage, size/XL, Squad/Green, lgtm

#9081 PR for accesing restored pvc with ROX mode.
  tests/conftest.py
  tests/functional/pv/pvc_snapshot/test_snapshot_restore_with_different_access_mode.py
Labels: team/e2e, size/M, Customer defects, lgtm

#9125 Fix docs
  docs/conf.py
  docs/getting_started.md
  docs/multicluster_test_example.md
  docs/usage.md
  docs/usecases/odf_with_kms.md
  docs/usecases/using_alternative_ocp_mirrors.md
  ocs_ci/cleanup/__init__.py
  ocs_ci/cleanup/aws/__init__.py
  ocs_ci/deployment/helpers/__init__.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/ui/page_objects/__init__.py
  requirements-docs.txt
  setup.py
  tests/manage/mcg/test_virtual_hosted_buckets.py
Labels: team/ecosystem, size/M, lgtm

#8972 Add test_hci_metrics_available
  ocs_ci/ocs/metrics.py
  tests/functional/monitoring/prometheus/metrics/test_monitoring_defaults.py
Labels: Verified, size/S, Squad/Blue, lgtm, provider-client

#9133 Fix docs
  docs/conf.py
  docs/getting_started.md
  docs/multicluster_test_example.md
  docs/usage.md
  docs/usecases/odf_with_kms.md
  docs/usecases/using_alternative_ocp_mirrors.md
  ocs_ci/cleanup/__init__.py
  ocs_ci/cleanup/aws/__init__.py
  ocs_ci/deployment/helpers/__init__.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/ui/page_objects/__init__.py
  requirements-docs.txt
  setup.py
Labels: team/ecosystem, size/M, lgtm, cherry-pick

#9135 Fix docs
  docs/conf.py
  docs/getting_started.md
  docs/multicluster_test_example.md
  docs/usage.md
  docs/usecases/odf_with_kms.md
  docs/usecases/using_alternative_ocp_mirrors.md
  ocs_ci/cleanup/__init__.py
  ocs_ci/cleanup/aws/__init__.py
  ocs_ci/deployment/helpers/__init__.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/hsbench.py
  ocs_ci/ocs/ui/page_objects/__init__.py
  requirements-docs.txt
  setup.py
Labels: team/ecosystem, size/M, lgtm, cherry-pick

#9136 Fix docs
  docs/conf.py
  docs/getting_started.md
  docs/multicluster_test_example.md
  docs/usage.md
  docs/usecases/odf_with_kms.md
  docs/usecases/using_alternative_ocp_mirrors.md
  ocs_ci/cleanup/__init__.py
  ocs_ci/cleanup/aws/__init__.py
  ocs_ci/deployment/helpers/__init__.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/hsbench.py
  ocs_ci/ocs/ui/page_objects/__init__.py
  requirements-docs.txt
  setup.py
Labels: team/ecosystem, size/M, lgtm, cherry-pick

#9116 raise exception with existing node count
  ocs_ci/ocs/node.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#9107 Adding OCP 4.16 config files
  ocs_ci/framework/conf/ocp_version/ocp-4.16-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.16-upgrade.yaml
Labels: Verified, team/ecosystem, size/S, lgtm

#9109 verify exporter pods
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#9112 Revert skip bucket creation
  tests/conftest.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#7271 Stretch cluster: test shutdowns and crash scenarios
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/helpers/helpers.py
  ocs_ci/helpers/stretchcluster_helper.py
  ocs_ci/helpers/stretchcluster_helpers.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/stretchcluster.py
  ocs_ci/templates/workloads/logwriter/logwriter.rbd.yaml
  tests/conftest.py
  tests/disaster-recovery/sc_arbiter/test_netsplit.py
  tests/disaster-recovery/sc_arbiter/test_zone_shutdown_and_crash.py
Labels: Verified, team/e2e, size/XXL, new feature, Customer defects, lgtm

#9097 Automate bug 2109101 and 2209098
  ocs_ci/ocs/constants.py
  tests/disaster-recovery/sc_arbiter/test_noobaa_in_stretch.py
  tests/disaster-recovery/sc_arbiter/test_rgw_in_stretch.py
  tests/manage/mcg/test_virtual_hosted_buckets.py
Labels: Verified, team/e2e, size/L, MCG, Customer defects, lgtm

#8981 Verify noobaa root secrets are not publicly exposed
  ocs_ci/deployment/helpers/mcg_helpers.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/manage/mcg/test_noobaa_secret.py
  tests/manage/mcg/test_s3_regenerate_creds.py
Labels: Verified, team/e2e, size/L, MCG, Customer defects, Squad/Red, lgtm

#8240 Add test case for new_PVC scenario of selinux relabeling solution
  ocs_ci/helpers/helpers.py
  tests/conftest.py
  tests/cross_functional/kcs/test_selinux_relabel_solution.py
Labels: team/e2e, size/L, lgtm

#9139 Add security fixes
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/elasticsearch.py
  ocs_ci/ocs/perfresult.py
  ocs_ci/ocs/perftests.py
  ocs_ci/templates/workloads/osd_scale/osd_scale_benchmark.yaml
  ocs_ci/templates/workloads/smallfile/SmallFile.yaml
  setup.py
  tests/e2e/performance/io_workload/test_fio_benchmark.py
  tests/e2e/performance/io_workload/test_small_file_workload.py
  tests/libtest/test_elasticsearch.py
Labels: team/ecosystem, size/L, lgtm

#9038 Relocate remaining ecosystem tests to the functional test directory
  tests/ecosystem/__init__.py
  tests/ecosystem/deployment/__init__.py
  tests/functional/deployment/test_acm.py
  tests/functional/upgrade/__init__.py
  tests/functional/upgrade/conftest.py
  tests/functional/upgrade/test_configuration.py
  tests/functional/upgrade/test_logging_upgrade.py
  tests/functional/upgrade/test_monitoring_after_ocp_upgrade.py
  tests/functional/upgrade/test_noobaa.py
  tests/functional/upgrade/test_resources.py
  tests/functional/upgrade/test_upgrade.py
  tests/functional/upgrade/test_upgrade_ocp.py
  tests/functional/upgrade/test_upgrade_sc_allowexpansion_false.py
Labels: Needs Testing, Verified, team/ecosystem, size/XS, lgtm

#9147 Only apply region node to worker nodes for noobaa IBM Cloud COS
  ocs_ci/utility/ibmcloud.py
Labels: Verified, size/XS, lgtm

#9151 restructure ui tests
  ocs_ci/ocs/ui/page_objects/block_and_file.py
  tests/cross_functional/ui/test_add_capacity_ui.py
  tests/cross_functional/ui/test_create_pool_block_pool.py
  tests/cross_functional/ui/test_creation_and_deletion_of_sc_and_rbdpool.py
  tests/cross_functional/ui/test_odf_topology.py
  tests/cross_functional/ui/test_validation_ui.py
  tests/functional/ui/test_capacity_breakdown_ui.py
  tests/functional/ui/test_error_improvements.py
  tests/functional/ui/test_non_admin_user.py
  tests/functional/ui/test_pv_encryption_ui.py
  tests/functional/ui/test_quickstarts.py
Labels: Verified, size/XS, lgtm

#9078 Provider client specific alerting tests
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storageconsumer.py
  tests/functional/monitoring/conftest.py
  tests/functional/monitoring/prometheus/alerts/test_provider_client.py
Labels: Verified, size/L, Squad/Blue, provider-client

#9046 RDR tests directory re-structure
  tests/functional/disaster-recovery/__init__.py
  tests/functional/disaster-recovery/regional-dr/__init__.py
  tests/functional/disaster-recovery/regional-dr/conftest.py
  tests/functional/disaster-recovery/regional-dr/test_failover.py
  tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate.py
  tests/functional/disaster-recovery/regional-dr/test_managed_cluster_node_failure.py
  tests/functional/disaster-recovery/regional-dr/test_negative_failover_relocate_ui.py
  tests/functional/disaster-recovery/regional-dr/test_node_operations_during_failover_relocate.py
  tests/functional/disaster-recovery/regional-dr/test_relocate.py
  tests/functional/disaster-recovery/regional-dr/test_sequential_failover.py
  tests/functional/disaster-recovery/regional-dr/test_sequential_relocate.py
Labels: Verified, size/XS, lgtm, DR, Squad/Turquoise

#9104 Provider-Client: Add runs_on_provider marker in test case
  tests/manage/z_cluster/test_delete_rook_ceph_mon_pod.py
  tests/manage/z_cluster/test_rook_ceph_log_rotate.py
  tests/manage/z_cluster/test_rook_ceph_operator_log_type.py
Labels: Verified, size/XS, lgtm, provider-client

#9020 Fix get_cephfs_subvolumegroup function for HCI client setup
  ocs_ci/helpers/helpers.py
Labels: Verified, size/S, lgtm, provider-client

#8562 Optimize MCG test bucket creation/deletion tests
  tests/manage/mcg/test_bucket_creation_deletion.py
  tests/manage/mcg/test_bucket_deletion.py
Labels: Needs Testing, Verified, team/e2e, size/L, MCG, Squad/Red, lgtm

#9165 check exporter pod count based on ceph pods
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, lgtm

#8933 Relocate functional MCG and RGW tests from `tests/manage` to `tests/functional/object`
  tests/functional/object/mcg/__init__.py
  tests/functional/object/mcg/conftest.py
  tests/functional/object/mcg/flowtest/test_mcg_namespace_disruptions_crd.py
  tests/functional/object/mcg/flowtest/test_mcg_namespace_disruptions_rpc.py
  tests/functional/object/mcg/lifecycle/test_mcg_namespace_lifecyle_crd.py
  tests/functional/object/mcg/lifecycle/test_mcg_namespace_lifecyle_rpc.py
  tests/functional/object/mcg/lifecycle/test_mcg_namespace_s3_ops_crd.py
  tests/functional/object/mcg/lifecycle/test_mcg_namespace_s3_ops_rpc.py
  tests/functional/object/mcg/test_admission_control.py
  tests/functional/object/mcg/test_azure_noobaa_sa.py
  tests/functional/object/mcg/test_bucket_creation_deletion.py
  tests/functional/object/mcg/test_bucket_deletion.py
  tests/functional/object/mcg/test_bucket_policy.py
  tests/functional/object/mcg/test_bucket_replication.py
  tests/functional/object/mcg/test_cached_buckets.py
  tests/functional/object/mcg/test_credentials_reset.py
  tests/functional/object/mcg/test_db_nfs_mount.py
  tests/functional/object/mcg/test_endpoint_autoscale.py
  tests/functional/object/mcg/test_host_node_failure.py
  tests/functional/object/mcg/test_kms.py
  tests/functional/object/mcg/test_log_based_bucket_replication.py
  tests/functional/object/mcg/test_mcg_resources_disruptions.py
  tests/functional/object/mcg/test_multi_region.py
  tests/functional/object/mcg/test_multicloud.py
  tests/functional/object/mcg/test_multipart_upload.py
  tests/functional/object/mcg/test_namespace_crd.py
  tests/functional/object/mcg/test_namespace_rpc.py
  tests/functional/object/mcg/test_nb_mgmt_endpoint.py
  tests/functional/object/mcg/test_noobaa_prometheus.py
  tests/functional/object/mcg/test_noobaa_secret.py
  tests/functional/object/mcg/test_nsfs.py
  tests/functional/object/mcg/test_object_expiration.py
  tests/functional/object/mcg/test_object_integrity.py
  tests/functional/object/mcg/test_object_versioning.py
  tests/functional/object/mcg/test_pv_pool.py
  tests/functional/object/mcg/test_s3_prefix_list.py
  tests/functional/object/mcg/test_s3_regenerate_creds.py
  tests/functional/object/mcg/test_s3_routes.py
  tests/functional/object/mcg/test_s3_with_java_sdk.py
  tests/functional/object/mcg/test_verify_noobaa_status.py
  tests/functional/object/mcg/test_virtual_hosted_buckets.py
  tests/functional/object/mcg/test_write_to_bucket.py
  tests/functional/object/mcg/ui/test_mcg_ui.py
  tests/functional/object/mcg/ui/test_namespace_store.py
  tests/functional/object/mcg/ui/test_verify_region_list.py
  tests/functional/object/rgw/conftest.py
  tests/functional/object/rgw/test_bucket_creation.py
  tests/functional/object/rgw/test_bucket_deletion.py
  tests/functional/object/rgw/test_host_node_failure.py
  tests/functional/object/rgw/test_multipart_upload.py
  tests/functional/object/rgw/test_obc_quota.py
  tests/functional/object/rgw/test_object_bucket_size.py
  tests/functional/object/rgw/test_object_integrity.py
  tests/functional/object/rgw/test_rgw_pod_existence.py
  tests/functional/object/rgw/test_rgw_routes.py
Labels: Verified, size/XS, MCG, RGW, Squad/Red, lgtm

#9043 OCP Deployment on vSphere via Assisted Installer
  conf/deployment/vsphere/ai_1az_rhcos_vsan_3m_3w.yaml
  conf/deployment/vsphere/ai_1az_rhcos_vsan_3m_3w_hci.yaml
  ocs_ci/deployment/assisted_installer.py
  ocs_ci/deployment/factory.py
  ocs_ci/deployment/helpers/prechecks.py
  ocs_ci/deployment/vmware.py
  ocs_ci/framework/conf/default_config.yaml
  terraform/ai/vsphere/main.tf
  terraform/ai/vsphere/terraform.tfvars.example
  terraform/ai/vsphere/variables.tf
  terraform/ai/vsphere/vm/main.tf
  terraform/ai/vsphere/vm/variables.tf
Labels: Verified, team/ecosystem, size/L, lgtm

#9050 Add Dockerfile for nginx pod
  Docker_files/nginx/Dockerfile
Labels: size/S, lgtm

#9174 Add cluster kubeconfig while using tools pod in provider-client setup
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/XS, lgtm

#9168 [release-4.14 backport] Skip `test_upgrade_mcg_io` until https://url.corp.redhat.com/c960ed4 is complete
  tests/ecosystem/upgrade/test_noobaa.py
Labels: size/XS, MCG, upgrade, Squad/Red, lgtm

#8958 Log the md5sum list in case of an IndexError exception in verify_s3_object_integrity(
  ocs_ci/ocs/bucket_utils.py
Labels: enhancement, size/XS, MCG, Squad/Red, lgtm

#9057 `test_anonymous_read_only`: Use s3_get_object with retry
  tests/functional/object/mcg/test_bucket_policy.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm, backport-required

#8980 Refactor awscli fixture to avoid "s3cli already exists" leftovers
  ocs_ci/ocs/constants.py
  tests/conftest.py
  tests/libtest/test_awscli_leftovers.py
Labels: High Priority, Verified, size/L, MCG, Squad/Red, lgtm, backport-required

#8979 Patch the noobaa CR instead of the OCS StorageCluster at `test_disable_nb_lb`
  tests/functional/object/mcg/test_s3_routes.py
Labels: Verified, size/M, MCG, Squad/Red, lgtm

#8626 Warp - Added test cases for pv, aws, azure and gcp
  tests/e2e/scale/noobaa/test_warp.py
Labels: Verified, size/M, scale, MCG, Squad/Red, lgtm

#9095 Adds functionality of downloading objects using s3cmd utility
  ocs_ci/ocs/bucket_utils.py
  tests/functional/object/rgw/test_multipart_upload.py
Labels: Verified, size/L, RGW, Squad/Red, lgtm

#9119 [release-4.13 backport] Skip `test_upgrade_mcg_io` until https://url.corp.redhat.com/c960ed4 is complete
  tests/ecosystem/upgrade/test_noobaa.py
Labels: size/XS, MCG, upgrade, Squad/Red

#9018 Fix `test_noobaa_rebuild` and make sure it updates the mcg_obj_session s3 credentials after resetting the noobaa-admin secret
  ocs_ci/ocs/resources/mcg.py
  tests/cross_functional/kcs/test_noobaa_rebuild.py
Labels: High Priority, Verified, size/M, MCG, Squad/Magenta, Squad/Red, lgtm

#9182 restructured z-cluster and other brown squad testcases
  tests/functional/z_cluster/__init__.py
  tests/functional/z_cluster/cluster_expansion/__init__.py
  tests/functional/z_cluster/cluster_expansion/conftest.py
  tests/functional/z_cluster/cluster_expansion/test_add_capacity.py
  tests/functional/z_cluster/cluster_expansion/test_add_capacity_entry_exit_criteria.py
  tests/functional/z_cluster/cluster_expansion/test_add_capacity_with_node_restart.py
  tests/functional/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
  tests/functional/z_cluster/cluster_expansion/test_delete_pod.py
  tests/functional/z_cluster/cluster_expansion/test_node_expansion.py
  tests/functional/z_cluster/cluster_expansion/test_verify_ceph_csidriver_runs_on_non_ocs_nodes.py
  tests/functional/z_cluster/cluster_reduction/__init__.py
  tests/functional/z_cluster/conftest.py
  tests/functional/z_cluster/nodes/__init__.py
  tests/functional/z_cluster/nodes/test_automated_recovery_from_failed_nodes_proactive_IPI.py
  tests/functional/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
  tests/functional/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_ms.py
  tests/functional/z_cluster/nodes/test_az_failure.py
  tests/functional/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
  tests/functional/z_cluster/nodes/test_check_pods_status_after_node_failure.py
  tests/functional/z_cluster/nodes/test_disk_failures.py
  tests/functional/z_cluster/nodes/test_node_kernel_crash_ceph_fsync.py
  tests/functional/z_cluster/nodes/test_node_replacement_proactive.py
  tests/functional/z_cluster/nodes/test_node_replacement_reactive_aws_ipi.py
  tests/functional/z_cluster/nodes/test_nodes_maintenance.py
  tests/functional/z_cluster/nodes/test_nodes_restart.py
  tests/functional/z_cluster/nodes/test_nodes_restart_ms.py
  tests/functional/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
  tests/functional/z_cluster/nodes/test_rolling_shutdown_and_recovery.py
  tests/functional/z_cluster/nodes/test_rolling_shutdown_and_recovery_ms.py
  tests/functional/z_cluster/nodes/test_rolling_terminate_and_recovery.py
  tests/functional/z_cluster/nodes/test_toleration.py
  tests/functional/z_cluster/nodes/test_worker_nodes_network_failures.py
  tests/functional/z_cluster/test_add_mds_to_cluster.py
  tests/functional/z_cluster/test_ceph_default_values_check.py
  tests/functional/z_cluster/test_ceph_pg_log_dups_trim.py
  tests/functional/z_cluster/test_coredump_check_for_ceph_daemon_crash.py
  tests/functional/z_cluster/test_delete_local_volume_sym_link.py
  tests/functional/z_cluster/test_delete_osd_deployment.py
  tests/functional/z_cluster/test_delete_rook_ceph_mon_pod.py
  tests/functional/z_cluster/test_hugepages.py
  tests/functional/z_cluster/test_mon_data_avail_warn.py
  tests/functional/z_cluster/test_mon_log_trimming.py
  tests/functional/z_cluster/test_multiple_mon_pods_stays_on_same_node.py
  tests/functional/z_cluster/test_must_gather.py
  tests/functional/z_cluster/test_no_liveness_probe.py
  tests/functional/z_cluster/test_noobaa_xss_vulnerability.py
  tests/functional/z_cluster/test_osd_heap_profile.py
  tests/functional/z_cluster/test_remove_mon_from_cluster.py
  tests/functional/z_cluster/test_restart_mgr_while_two_mons_down.py
  tests/functional/z_cluster/test_rook_ceph_log_rotate.py
  tests/functional/z_cluster/test_rook_ceph_operator_log_type.py
  tests/functional/z_cluster/test_rook_operator_restart_during_mon_failover.py
  tests/functional/z_cluster/test_scc.py
  tests/functional/z_cluster/upgrade/__init__.py
  tests/functional/z_cluster/upgrade/test_check_pdb_post_upgrade.py
Labels: size/XS, Squad/Brown, lgtm

#9176 Unpin junit_family and use default version (xunit2)
  pytest.ini
Labels: Verified, team/ecosystem, size/XS, lgtm

#9188 Use the correct namespace while waiting for new pod in disruption_helpers
  ocs_ci/helpers/disruption_helpers.py
Labels: Verified, size/XS, lgtm, provider-client

#9184 Make sure ccoctl binary is downloaded if doesn't exist in destroy job
  ocs_ci/deployment/ibmcloud.py
Labels: Verified, team/ecosystem, size/S, lgtm

#9195 Fix deployment for IBM Cloud ROKS deployment with enabling Noobaa
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#9160 MDR tests directory re-structure
  tests/functional/__init__.py
  tests/functional/disaster-recovery/metro-dr/__init__.py
  tests/functional/disaster-recovery/metro-dr/conftest.py
  tests/functional/disaster-recovery/metro-dr/test_app_failover_and_relocate.py
Labels: Verified, size/XS, lgtm, Squad/Turquoise

#9177 Replacing crypt device check from pod to node.
  ocs_ci/ocs/node.py
  tests/functional/pv/pv_encryption/test_encrypted_rbd_pvc_clone.py
  tests/functional/pv/pv_encryption/test_encrypted_rbd_pvc_snapshot.py
  tests/functional/pv/pv_encryption/test_kmip_rbd_pv_encryption.py
  tests/functional/pv/pv_encryption/test_rbd_pv_encryption.py
  tests/functional/pv/pv_encryption/test_rbd_pv_encryption_vaulttenantsa.py
  tests/functional/ui/test_pv_encryption_ui.py
Labels: Verified, size/L, lgtm

#9169 [RDR] Add Initial Bownfield changes for RDR
  conf/ocsci/brownfield_mode.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
Labels: size/S, lgtm, DR

#9062 [RDR] Fix deployment failure with downstream submariner
  ocs_ci/ocs/acm/acm.py
Labels: Verified, size/XS, lgtm, DR, Squad/Turquoise

#9212 Update timeout value to wait for pods in resource deletion tests
  tests/functional/pv/pv_services/test_resource_deletion_during_pvc_pod_creation_and_io.py
  tests/functional/pv/pv_services/test_resource_deletion_during_pvc_pod_deletion_and_io.py
Labels: Verified, size/S, lgtm, provider-client

#9213 Update get_plugin_provisioner_leader to pass namespace to the function get_pod_logs
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/XS, lgtm, provider-client

#9196 Fix post-installation checks for client cluster
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/M, lgtm, provider-client

#9162 Update PVC expansion check on pods in test
  tests/functional/pv/pvc_resize/test_resource_deletion_during_pvc_expansion.py
Labels: Verified, size/S, Squad/Green, lgtm

#9150 verify ux-backend-server pod
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#9225 Fixes directory path for skipping irrelevant tests
  tests/functional/object/mcg/conftest.py
  tests/functional/object/rgw/conftest.py
Labels: size/XS, MCG, Squad/Red, lgtm

#9233 4.15 project dropdown and test_dashboard_validation
  ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
  ocs_ci/ocs/ui/page_objects/page_navigator.py
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/ui/views.py
Labels: size/L, lgtm

#9234 assisted installer api: removing deprecated keys
  ocs_ci/deployment/assisted_installer.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#9189 Release 4.13 cherry pick pr 9072 9147
  ocs_ci/deployment/deployment.py
  ocs_ci/utility/ibmcloud.py
Labels: team/ecosystem, size/S, lgtm, cherry-pick

#9190 Release 4.12 cherry pick pr 9072 9147
  ocs_ci/deployment/deployment.py
  ocs_ci/utility/ibmcloud.py
Labels: team/ecosystem, size/S, lgtm, cherry-pick

#9191 Release 4.11 cherry pick pr 9072 9147
  ocs_ci/deployment/deployment.py
  ocs_ci/utility/ibmcloud.py
Labels: team/ecosystem, size/S, lgtm, cherry-pick

#9236 Release 4.14 cherry pick pr 9072 9147
  ocs_ci/deployment/deployment.py
  ocs_ci/utility/ibmcloud.py
Labels: team/ecosystem, size/S, lgtm, cherry-pick

#9227 Increase node drain timeout to avoid intermittent failures in test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
  tests/functional/z_cluster/cluster_expansion/test_crashcollector_pod_existence_on_ceph_pods_running_nodes.py
Labels: Verified, size/XS, lgtm

#9237 Bare metal deployment: create BAREMETALBASE class
  ocs_ci/deployment/baremetal.py
Labels: Verified, team/ecosystem, size/L, lgtm

#9231 Exclude the master nodes when using HCI Provider
  ocs_ci/ocs/node.py
Labels: Verified, size/S, lgtm, provider-client

#9238 Adding CommandFailed exception for retry
  ocs_ci/ocs/cluster.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#9232 sweeping S3 buckets in aws cleanup script
  ocs_ci/cleanup/aws/cleanup.py
  ocs_ci/utility/aws.py
Labels: Verified, team/ecosystem, size/L, lgtm

#9245 Change the value of the mds cache memory limit
  tests/functional/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#9229 config file IBM cloud 3M-6W
  conf/deployment/ibmcloud/ipi_3az_rhcos_3m_6w.yaml
Labels: Needs Deployment Testing, team/ecosystem, size/S, lgtm

#9241 Fix for backupstoragelocation name and drpolicy name(mdr)
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
Labels: bug, Verified, size/XS, lgtm, DR

#9247 Fix directory path in conftest
  tests/functional/pv/conftest.py
  tests/functional/storageclass/conftest.py
Labels: team/ecosystem, size/XS, lgtm

#9252 Add support for ODF 4.16
  ocs_ci/framework/conf/ocs_version/ocs-4.16.yaml
  ocs_ci/framework/main.py
  ocs_ci/utility/version.py
Labels: team/ecosystem, size/S, lgtm

#9253 change default networkType to OVNKubernetes
  ocs_ci/templates/ocp-deployment/install-config-aws-ipi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-aws-upi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-azure-ipi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-gcp-ipi.yaml.j2
  ocs_ci/templates/ocp-deployment/install-config-rhv-ipi.yaml.j2
Labels: Verified, team/ecosystem, size/S, lgtm

#9228 Run object tests on provider
  tests/functional/object/mcg/test_admission_control.py
  tests/functional/object/mcg/test_azure_noobaa_sa.py
  tests/functional/object/mcg/test_bucket_creation_deletion.py
  tests/functional/object/mcg/test_bucket_deletion.py
  tests/functional/object/mcg/test_bucket_policy.py
  tests/functional/object/mcg/test_bucket_replication.py
  tests/functional/object/mcg/test_cached_buckets.py
  tests/functional/object/mcg/test_credentials_reset.py
  tests/functional/object/mcg/test_db_nfs_mount.py
  tests/functional/object/mcg/test_endpoint_autoscale.py
  tests/functional/object/mcg/test_host_node_failure.py
  tests/functional/object/mcg/test_kms.py
  tests/functional/object/mcg/test_log_based_bucket_replication.py
  tests/functional/object/mcg/test_mcg_resources_disruptions.py
  tests/functional/object/mcg/test_multi_region.py
  tests/functional/object/mcg/test_multicloud.py
  tests/functional/object/mcg/test_multipart_upload.py
  tests/functional/object/mcg/test_namespace_crd.py
  tests/functional/object/mcg/test_namespace_rpc.py
  tests/functional/object/mcg/test_nb_mgmt_endpoint.py
  tests/functional/object/mcg/test_noobaa_prometheus.py
  tests/functional/object/mcg/test_noobaa_secret.py
  tests/functional/object/mcg/test_nsfs.py
  tests/functional/object/mcg/test_object_expiration.py
  tests/functional/object/mcg/test_object_integrity.py
  tests/functional/object/mcg/test_object_versioning.py
  tests/functional/object/mcg/test_pv_pool.py
  tests/functional/object/mcg/test_s3_prefix_list.py
  tests/functional/object/mcg/test_s3_regenerate_creds.py
  tests/functional/object/mcg/test_s3_routes.py
  tests/functional/object/mcg/test_s3_with_java_sdk.py
  tests/functional/object/mcg/test_verify_noobaa_status.py
  tests/functional/object/mcg/test_virtual_hosted_buckets.py
  tests/functional/object/mcg/test_write_to_bucket.py
  tests/functional/object/mcg/ui/test_mcg_ui.py
  tests/functional/object/mcg/ui/test_namespace_store.py
  tests/functional/object/mcg/ui/test_verify_region_list.py
  tests/functional/object/rgw/test_bucket_creation.py
  tests/functional/object/rgw/test_bucket_deletion.py
  tests/functional/object/rgw/test_host_node_failure.py
  tests/functional/object/rgw/test_multipart_upload.py
  tests/functional/object/rgw/test_obc_quota.py
  tests/functional/object/rgw/test_object_bucket_size.py
  tests/functional/object/rgw/test_object_integrity.py
  tests/functional/object/rgw/test_rgw_pod_existence.py
  tests/functional/object/rgw/test_rgw_routes.py
Labels: Verified, size/L, MCG, RGW, lgtm, provider-client

#9243 Verify that default noobaa backingstore uses rgw endpoint on provider
  ocs_ci/ocs/constants.py
  tests/functional/object/mcg/test_provider_client.py
Labels: Verified, size/M, Squad/Red, lgtm, provider-client
