Repository red-hat-storage/ocs-ci, pull requests merged in 2024-10, with the labels that each got.

#10547 introduce deploy_hosted_clusters configuration parameter
  conf/README.md
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/XS, lgtm

#10457 Fixes process timeout issue while uploading data and adds timeout while deleting bucket in scale scenario
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/resources/objectbucket.py
  ocs_ci/templates/app-pods/fedora_with_linuxtar_files.yaml
  tests/conftest.py
Labels: Verified, TestCase failing, size/S, scale, MCG, Squad/Orange, lgtm

#9402 Add Ability to perform Node operation on IBM Cloud IPI deployment
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/ibmcloud.py
  tests/functional/z_cluster/nodes/test_disk_failures.py
  tests/functional/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/L, Squad/Brown, lgtm

#10587 Check that the ceph-csi version matches the OCP version on the hosted clusters
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/utility/utils.py
  tests/functional/provider_mode/test_ceph_csi_image_versions.py
Labels: Verified, size/L, lgtm, provider-client

#10581 Add Cluster context section to docs
  docs/writing_tests.md
Labels: size/M, lgtm

#10606 use ocp-network-split from red-hat-storage org fork - release-4.14
  requirements.txt
  setup.py
Labels: team/ecosystem, size/XS, lgtm, cherry-pick

#10607 use ocp-network-split from red-hat-storage org fork - release-4.13
  requirements.txt
Labels: team/ecosystem, size/XS, lgtm, cherry-pick

#10608 use ocp-network-split from red-hat-storage org fork - release-4.12
  requirements.txt
Labels: team/ecosystem, size/XS, lgtm, cherry-pick

#10611 Adding OCP 4.17-ga files
  ocs_ci/framework/conf/ocp_version/ocp-4.17-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.17-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.17-ga-upgrade.yaml
Labels: Needs Deployment Testing, team/ecosystem, size/M, lgtm

#10614 Disconnected ocp deployment on vsphere - backport release 4.13
  conf/README.md
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_disconnected.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_disconnected_flexy.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w_disconnected.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w_disconnected_flexy.yaml
  ocs_ci/deployment/disconnected.py
  ocs_ci/deployment/ocp.py
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/connection.py
  ocs_ci/utility/load_balancer.py
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: team/ecosystem, size/L, lgtm, cherry-pick

#10612 Disconnected ocp deployment on vsphere - backport release 4.12
  conf/README.md
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_disconnected.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_3m_3w_disconnected_flexy.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w_disconnected.yaml
  conf/deployment/vsphere/upi_1az_rhcos_vsan_lso_vmdk_3m_3w_disconnected_flexy.yaml
  ocs_ci/deployment/disconnected.py
  ocs_ci/deployment/ocp.py
  ocs_ci/deployment/vmware.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/connection.py
  ocs_ci/utility/load_balancer.py
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: Verified, team/ecosystem, size/L, lgtm, cherry-pick

#10525 [bz:2274165] Test to verify mgr does not crash after enabling rook module
  tests/functional/pod_and_daemons/test_mgr_enable_rook_backend_module.py
Labels: Test Case, Verified, team/e2e, size/L, lgtm

#10617 Release lock when exception hit in exec_cmd
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/S, lgtm

#10582 Add validation of pod deletion
  tests/functional/pv/space_reclaim/test_rbd_space_reclaim.py
Labels: Verified, size/S, Squad/Green, lgtm

#10542 Restructure rdr
  conf/ocsci/dr_workload.yaml
Labels: Verified, size/M, lgtm

#10619 Add traceback dump
  ocs_ci/framework/main.py
Labels: size/XS, lgtm

#10610 Ingress Node Firewall deployment on un-released OCP version (from QE App Registry catalog)
  ocs_ci/deployment/ingress_node_firewall.py
  ocs_ci/deployment/qe_app_registry.py
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/M, lgtm

#10620 fix kubeconfig path for hosted clusters
  ocs_ci/deployment/helpers/hypershift_base.py
  ocs_ci/deployment/hosted_cluster.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#9552 Installing volsync addon on managed clusters with unreleased ACM version
  ocs_ci/deployment/deployment.py
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/L, lgtm

#10627 Fixed odf_cli tests cases
  ocs_ci/helpers/helpers.py
Labels: size/XS, lgtm

#10632 Fix security issues
  setup.py
Labels: Verified, size/XS, lgtm

#10572 Increase timeout for OCP Upgrade
  tests/functional/upgrade/test_upgrade_ocp.py
Labels: size/XS, lgtm

#10628 Fixed PVKeyrotation tests failures
  ocs_ci/helpers/keyrotation_helper.py
  ocs_ci/utility/kms.py
Labels: Verified, size/S, lgtm

#10638 Add retry for storageSystem check
  ocs_ci/ocs/resources/storage_cluster.py
Labels: team/ecosystem, size/XS, lgtm

#10623 Added new marker "rdr" for running RDR related tests
  ocs_ci/framework/pytest_customization/marks.py
  pytest.ini
  tests/functional/disaster-recovery/regional-dr/test_cnv_app_failover_and_relocate.py
  tests/functional/disaster-recovery/regional-dr/test_failover.py
  tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate.py
  tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate_discovered_apps.py
  tests/functional/disaster-recovery/regional-dr/test_managed_cluster_node_failure.py
  tests/functional/disaster-recovery/regional-dr/test_negative_failover_relocate_ui.py
  tests/functional/disaster-recovery/regional-dr/test_node_operations_during_failover_relocate.py
  tests/functional/disaster-recovery/regional-dr/test_rdr_monitoring_dashboard_ui.py
  tests/functional/disaster-recovery/regional-dr/test_relocate.py
  tests/functional/disaster-recovery/regional-dr/test_sequential_failover.py
  tests/functional/disaster-recovery/regional-dr/test_sequential_relocate.py
Labels: size/M, lgtm, DR, Squad/Turquoise

#10649 [Cherry-pick-10493] [Release-4.16]Fixed resource wrong status exception.
  tests/conftest.py
  tests/functional/pv/pv_encryption/test_encrypted_pvc_no_expansion_option.py
Labels: Verified, size/XS, lgtm

#10653 Fix Path for Cephfs Workloads RDR
  conf/ocsci/dr_workload.yaml
Labels: Verified, size/XS, lgtm, DR, Squad/Turquoise

#10651 Remove W/A for wait_timeout_for_healthy_osd_in_minutes
  ocs_ci/deployment/deployment.py
Labels: team/ecosystem, size/S, lgtm

#10656 Expand user in path for traceback log
  ocs_ci/framework/main.py
Labels: size/XS, lgtm

#10636 GSS-BZ-2245068: Add an unlabeled pod to the openshift-storage ns
  tests/cross_functional/ui/test_odf_topology.py
Labels: Verified, team/e2e, size/S, Customer defects, lgtm

#10648 Added networkpolicy creation for hosted clusters before creating storageclient
  ocs_ci/deployment/hosted_cluster.py
Labels: Verified, size/S, lgtm

#10562 add post_ocs_upgrade marker for pg num checking
  tests/functional/z_cluster/test_ceph_default_values_check.py
Labels: team/ecosystem, size/XS, lgtm

#10421 rosa hcp deployment
  conf/README.md
  conf/deployment/aws/rosa_hcp_1az_3w_m5.12x.yaml
  conf/deployment/aws/rosa_hcp_1az_6w_m5.2x.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/factory.py
  ocs_ci/deployment/fusion_aas.py
  ocs_ci/deployment/helpers/hypershift_base.py
  ocs_ci/deployment/helpers/rosa_cluster_helpers.py
  ocs_ci/deployment/helpers/rosa_prod_cluster_helpers.py
  ocs_ci/deployment/ocp.py
  ocs_ci/deployment/rosa.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/node.py
  ocs_ci/ocs/registry.py
  ocs_ci/utility/aws.py
  ocs_ci/utility/openshift_dedicated.py
  ocs_ci/utility/retry.py
  ocs_ci/utility/rosa.py
  ocs_ci/utility/utils.py
Labels: Verified, size/XL, lgtm

#10593 remove double retry decorator
  ocs_ci/ocs/resources/mcg.py
Labels: team/ecosystem, size/XS, lgtm

#10676 make check_pvs_created last max 1H6m
  ocs_ci/utility/localstorage.py
Labels: size/XS, lgtm, backport-required

#10658 FDF Deployment support
  conf/ocsci/fdf_deployment.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/fusion_data_foundation.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/fusion-data-foundation/data-foundation-instance.yaml
  ocs_ci/templates/fusion-data-foundation/image-digest-mirror-set.yaml
  ocs_ci/templates/fusion-data-foundation/image-tag-mirror-set.yaml
  ocs_ci/templates/fusion-data-foundation/spectrum-fusion.yaml
Labels: team/ecosystem, size/L, lgtm

#10683 include IndexError while collect upgrade marks
  tests/conftest.py
Labels: team/ecosystem, size/XS, lgtm

#10571 Remove provider mode skip marker from space reclaim tests
  tests/functional/pv/space_reclaim/test_rbd_space_reclaim.py
Labels: Verified, size/S, lgtm, provider-client

#10659 Fixed keyrotation test failures
  ocs_ci/helpers/keyrotation_helper.py
  tests/functional/encryption/test_encryption_keyrotation.py
Labels: size/S, lgtm, backport-required

#10660 [Cherry-Pick-10141][Release-4.16] Fixed default sc tests case which was failing
  ocs_ci/helpers/helpers.py
  tests/functional/storageclass/test_rbd_default_storageclass.py
Labels: Verified, size/S, lgtm

#10694 remove Rotational duplicate in LocalVolumeSet
  ocs_ci/deployment/helpers/lso_helpers.py
  ocs_ci/templates/ocs-deployment/local-volume-set.yaml
Labels: Verified, team/ecosystem, size/XS, lgtm

#10583 [release-4.15 backport] Separate the cloning logic from `override_default_backingstore_fixture`
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/backingstore.py
  tests/conftest.py
  tests/libtest/test_clone_backingstore.py
Labels: Verified, size/L, MCG, Squad/Red, lgtm, cherry-pick

#10531 [release-4.16 backport] Set a priviliged service account for the NSFS interface deployment for NSFS tests
  tests/conftest.py
Labels: size/S, MCG, Squad/Red, lgtm, cherry-pick

#10527 [release-4.16 backport] Use the secure external endpoint and the needed CA for RGW SSL external deployments
  ocs_ci/ocs/awscli_pod.py
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/rgw.py
Labels: size/S, RGW, Squad/Red, lgtm, cherry-pick

#10699 RHCOS 4.18 template
  ocs_ci/framework/conf/ocp_version/ocp-4.18-config.yaml
Labels: Verified, team/ecosystem, size/XS, lgtm

#10696 mdr marker for running MDR related tests
  ocs_ci/framework/pytest_customization/marks.py
  pytest.ini
  tests/functional/disaster-recovery/metro-dr/test_active_hub_down_and_restore.py
  tests/functional/disaster-recovery/metro-dr/test_app_failover_and_relocate.py
  tests/functional/disaster-recovery/metro-dr/test_app_failover_and_relocate_when_entire_one_zone_down.py
  tests/functional/disaster-recovery/metro-dr/test_cnv_app_failover_relocate.py
  tests/functional/disaster-recovery/metro-dr/test_multiple_apps_failover_and_relocate.py
  tests/functional/disaster-recovery/metro-dr/test_no_data_loss_and_corruption_on_failures.py
  tests/functional/disaster-recovery/metro-dr/test_replace_cluster.py
Labels: size/S, lgtm, DR, Squad/Turquoise

#10631 bz:2294723, test to update placement from spread to mirror of multiregion bucketclass
  tests/functional/object/mcg/test_multi_region.py
Labels: Test Case, Verified, team/e2e, size/M, lgtm

#10675 Fix test_nsfs_system test case
  tests/cross_functional/system_test/test_nsfs_system.py
Labels: Verified, size/M, lgtm

#10085 Fixing test_performance_profile_validation
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/functional/z_cluster/test_performance_profile_validation.py
Labels: Verified, size/L, Squad/Brown, lgtm

#10708 Fix IBM Cloud managed deployment for monitoring
  ocs_ci/ocs/monitoring.py
Labels: Verified, size/S, lgtm

#10565 Adds support of dumping around 5M IOs through noobaa endpoint to default backing store
  ocs_ci/ocs/warp.py
  ocs_ci/templates/workloads/warp/warp_obj.yaml
  tests/cross_functional/scale/noobaa/test_warp.py
Labels: Test Case, Verified, size/M, scale, Squad/Orange, lgtm

#10713 increase retries ( 10 min ) to verify storagesystem status
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Needs Testing, team/ecosystem, size/XS, lgtm

#10605 Added provider_mode tags to mark regression testcases for provider-client clusters
  ocs_ci/framework/pytest_customization/marks.py
  pytest.ini
  tests/cross_functional/system_test/multicluster/test_post_installation_state.py
  tests/functional/monitoring/prometheus/alerts/test_alerting_works.py
  tests/functional/monitoring/prometheus/alerts/test_ceph.py
  tests/functional/monitoring/prometheus/alerts/test_deployment_status.py
  tests/functional/monitoring/prometheus/metrics/test_monitoring_defaults.py
  tests/functional/monitoring/prometheus/metrics/test_ocs_utilization.py
  tests/functional/monitoring/test_monitoring_tool.py
  tests/functional/object/mcg/test_bucket_policy.py
  tests/functional/object/mcg/ui/test_mcg_ui.py
  tests/functional/pv/pv_services/test_change_reclaim_policy_of_pv.py
  tests/functional/pv/pv_services/test_create_large_sized_pvc_while_io_in_progress.py
  tests/functional/pv/pv_services/test_delete_create_pvc_same_name.py
  tests/functional/pv/pv_services/test_no_space_left.py
  tests/functional/pv/pv_services/test_pvc_concurrent_deletion_creation.py
  tests/functional/pv/pv_services/test_pvc_delete_verify_size_is_returned_to_backendpool.py
  tests/functional/pv/pv_services/test_pvc_deletion_during_io.py
  tests/functional/pv/pv_services/test_pvc_evict_ceph_clients.py
  tests/functional/pv/pv_services/test_pvc_rwx_writeable_after_pod_deletions.py
  tests/functional/pv/pv_services/test_raw_block_pv.py
  tests/functional/pv/pv_services/test_run_io_multiple_pods.py
  tests/functional/pv/pv_services/test_verify_rwo_using_multiple_pods.py
  tests/functional/pv/pvc_clone/test_pvc_to_pvc_clone.py
  tests/functional/pv/pvc_resize/test_pvc_expansion.py
  tests/functional/pv/pvc_snapshot/test_pvc_snapshot.py
  tests/functional/pv/pvc_snapshot/test_rbd_block_pvc_snapshot.py
  tests/functional/pv/pvc_snapshot/test_snapshot_restore_with_different_access_mode.py
Labels: Verified, size/L, lgtm

#10655 [RDR] Remove redundant argument from conftest.py and dr_workload.py
  ocs_ci/ocs/dr/dr_workload.py
  tests/conftest.py
Labels: Verified, size/XS, lgtm, DR, Squad/Turquoise

#10442 disable dr
  ocs_ci/helpers/dr_helpers.py
  tests/functional/disaster-recovery/regional-dr/test_disable_dr.py
Labels: Verified, size/L, lgtm, Squad/Turquoise

#10622 Adding a new test for csi logs rotation feature
  ocs_ci/ocs/resources/pod.py
  tests/functional/pod_and_daemons/test_csi_logs_rotation.py
Labels: size/L, Squad/Brown, lgtm

#10716 Fix configmap name to whitelist metrics needed for ACM observability on DR monitoring dashboard
  ocs_ci/templates/DR/observability-metrics-configmap.yaml
Labels: High Priority, Verified, size/XS, lgtm, Squad/Turquoise, approved

#10674 Use only_major_minor to validate Csi sidecar count
  ocs_ci/deployment/deployment.py
Labels: Verified, size/XS, lgtm, DR

#10695 increasing timeout and add marker
  tests/cross_functional/ui/test_create_pool_block_pool.py
  tests/cross_functional/ui/test_creation_and_deletion_of_sc_and_rbdpool.py
  tests/functional/pv/pvc_snapshot/test_small_files_pvc_cloned_status.py
Labels: Verified, size/S, Squad/Green, lgtm

#10703 add ocp install log, delete cluster
  ocs_ci/deployment/assisted_installer.py
  ocs_ci/deployment/helpers/rosa_cluster_helpers.py
  ocs_ci/deployment/rosa.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/deployment.py
  ocs_ci/utility/rosa.py
Labels: Verified, size/L, platforms, lgtm

#9635 [release-4.15 backport] Use the nsfs-deployment pod for file access commands in `nsfs_bucket_factory` instead of the noobaa-endpoint pods
  tests/conftest.py
Labels: Verified, size/S, MCG, Squad/Red, cherry-pick

#10630 Adds test script for validating bucket delete operation using OBC generated credentials
  tests/functional/object/mcg/test_bucket_delete_using_obc_creds.py
Labels: Verified, size/M, MCG, Customer defects, Squad/Red, lgtm

#10175 [4.17] RHSTOR-5501 Feature automation: Store relevant Owner metadata for MCG objects
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  tests/conftest.py
  tests/functional/object/mcg/test_obj_owner_md.py
Labels: Verified, size/L, MCG, Squad/Red, lgtm

#10722 Fix test_noobaa_db_backup_recovery_locally
  tests/cross_functional/kcs/test_noobaa_db_backup_and_recovery.py
Labels: Verified, team/e2e, size/XS, Squad/Magenta, lgtm

#10692 remove cryptography package
  setup.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#10720 Fix update_container_with_mirrored_image for local images
  ocs_ci/utility/utils.py
Labels: size/XS, Squad/Magenta, lgtm

#10594 Collect ceph data for External mode
  ocs_ci/ocs/utils.py
  scripts/bash/mg_external.sh
Labels: Verified, size/L, lgtm

#10626 Added setup fixture to test "get_cli_cmd"
  ocs_ci/helpers/odf_cli.py
  tests/functional/conftest.py
  tests/functional/odf-cli/test_get_commands.py
Labels: bug, Verified, size/L, lgtm

#10721 reboot server if not properly discovered by Assisted Installer
  ocs_ci/deployment/assisted_installer.py
  ocs_ci/deployment/baremetal.py
Labels: Verified, team/ecosystem, size/S, lgtm

#10741 fix BM AI deployment on octo argo
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/connection.py
Labels: Verified, team/ecosystem, size/M, lgtm

#10735 fix ordering of testcases
  tests/cross_functional/kcs/test_monitor_recovery.py
  tests/cross_functional/system_test/multicluster/test_ms_markers.py
  tests/functional/disaster-recovery/sc_arbiter/test_add_capacity.py
  tests/functional/z_cluster/cluster_expansion/test_add_capacity.py
  tests/functional/z_cluster/cluster_expansion/test_resize_osd.py
  tests/libtest/test_hci_pc_markers.py
Labels: team/ecosystem, size/S, lgtm

#10726 use stable tag for ODF 4.18
  ocs_ci/framework/conf/ocs_version/ocs-4.18.yaml
Labels: Verified, team/ecosystem, size/XS, lgtm

#10681 Add the param 'allowVolumeExpansion: true' to allow resize OSD with GCP
  ocs_ci/templates/ocs-deployment/storageclass.gcp.yaml
Labels: Verified, team/ecosystem, size/XS, lgtm

#10782 fix external_cluster_helpers.upload_rgw_cert_ca
  ocs_ci/deployment/helpers/external_cluster_helpers.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#10700 Support deployment of pre-GA versions of Fusion and FDF
  conf/ocsci/fdf_deployment_pre_ga.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/fusion.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/fusion-data-foundation/catalog-source.yaml.j2
  ocs_ci/templates/fusion-data-foundation/data-foundation-instance.yaml
Labels: Verified, team/ecosystem, size/M, lgtm
