Repository red-hat-storage/ocs-ci, pull requests merged in 2025-06, with the labels that each got.

#12200 [RDR] Retrieve mirroring status from CBPR for ODF 4.19
  ocs_ci/helpers/dr_helpers.py
Labels: Verified, size/S, lgtm, Squad/Turquoise

#12289 Create ocs configmap before enabling rook debug mode
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocs-deployment/rook-ceph-operator-configmap.yaml
Labels: Verified, size/S, lgtm

#12235 Stabilize RDR deployment by using OCP to ACM navigation fix
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/ui/acm_ui.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/M, lgtm

#12299 Fix OCP deployment on vSphere via Assisted Installer
  terraform/ai/vsphere/vm/main.tf
Labels: Verified, team/ecosystem, size/XS, lgtm

#10376 ocs and ocp upgrade testcases for provider-client
  conf/README.md
  ocs_ci/deployment/cnv.py
  ocs_ci/deployment/helpers/hypershift_base.py
  ocs_ci/deployment/helpers/lso_helpers.py
  ocs_ci/deployment/metallb.py
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/acm_upgrade.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/provider_client_upgrade.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/storage_client.py
  ocs_ci/templates/ocs-deployment/multicluster/acm_unreleased_version.yaml
  ocs_ci/utility/ocp_upgrade.py
  ocs_ci/utility/utils.py
  tests/functional/upgrade/test_upgrade.py
  tests/functional/upgrade/test_upgrade_ocp.py
  tests/libtest/test_provider_create_hosted_cluster.py
Labels: Verified, size/XL, lgtm

#12239 rbac added. workaround for mce-2.8.2
  ocs_ci/deployment/hosted_cluster.py
  ocs_ci/templates/hosted-cluster/rbac-wa.yaml
Labels: Verified, size/M, lgtm, provider-client

#12314 Config to set default value 20% required for rbd and cephfs update strategy test
  conf/upgrade/rbd_cephfs_default_update_strategy_20p.yaml
Labels: Verified, size/S, lgtm

#11111 [4.18 system test] Test bucket replication with object versioning
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/resources/mcg_replication_policy.py
  ocs_ci/ocs/resources/mockup_bucket_logger.py
  tests/conftest.py
  tests/cross_functional/conftest.py
  tests/cross_functional/system_test/test_mcg_replication_with_disruptions.py
Labels: Verified, team/e2e, size/XL, MCG, lgtm

#12315 extend time for waiting for packagemanifest in set_upgrade_channel
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#12304 [release-4.18] Stabilize RDR deployment by using OCP to ACM navigation fix
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/ui/acm_ui.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/M, lgtm, DR, Squad/Turquoise

#12323 [ACM UI] Pattern fly v6 locator for Infrastructure
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/XS, ui_automation, lgtm, DR, Squad/Turquoise

#12300 fixes #12298: Fix logwriter statefulset with rbd setup in stretch cluster tests
  ocs_ci/helpers/helpers.py
  tests/functional/disaster-recovery/sc_arbiter/test_add_capacity.py
  tests/functional/disaster-recovery/sc_arbiter/test_device_replacement.py
  tests/functional/disaster-recovery/sc_arbiter/test_mon_osd_failures.py
  tests/functional/disaster-recovery/sc_arbiter/test_netsplit.py
  tests/functional/disaster-recovery/sc_arbiter/test_zone_shutdown_and_crash.py
Labels: Verified, team/e2e, size/M, lgtm

#12143 Address edge case in MCG.wait_for_ready_status()
  ocs_ci/ocs/resources/mcg.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#12306 Fixes AWS CLI region issue
  ocs_ci/ocs/constants.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#12111 Fix test_abort_incomplete_multipart_upload
  ocs_ci/ocs/bucket_utils.py
  tests/functional/object/mcg/test_lifecycle_configuration.py
Labels: Verified, size/M, MCG, Squad/Red, lgtm

#12266 added storage classes to storage consumer for distribution
  ocs_ci/deployment/hosted_cluster.py
  ocs_ci/deployment/provider_client/storage_client_deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_client.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/resources/storageconsumer.py
  ocs_ci/templates/ocs-deployment/provider-mode/native_storage_client.yaml
  tests/functional/z_cluster/nodes/test_nodes_restart_hci.py
Labels: Verified, size/L, lgtm

#12124 Create a new test for the storage auto scaling
  ocs_ci/helpers/helpers.py
  ocs_ci/helpers/storage_auto_scaler.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/storage-auto-scaling/storage-autoscaler.yaml
  tests/functional/z_cluster/cluster_expansion/test_storage_auto_scaling.py
Labels: Verified, size/XL, new feature, Squad/Brown, lgtm

#12342 Add custom brew catalog for OADP to all clusters + add annotation for…
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/utils.py
Labels: size/L, lgtm

#12242 FDF storage configuration after deployment
  ocs_ci/deployment/fusion.py
  ocs_ci/deployment/fusion_data_foundation.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/fusion-data-foundation/odfcluster.yaml
  ocs_ci/utility/framework/fusion_fdf_init.py
Labels: Verified, team/ecosystem, size/L, lgtm

#12146 Add Submariner support over IBM CLOUD IPI
  ocs_ci/deployment/acm.py
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/templates/acm-deployment/clusterset.yaml
  ocs_ci/templates/acm-deployment/submariner_addon.yaml
  ocs_ci/templates/acm-deployment/submariner_broker.yaml
  ocs_ci/templates/acm-deployment/submariner_config.yaml
  ocs_ci/utility/ibmcloud.py
Labels: Verified, size/L, lgtm, DR

#12360 Add polarion and jira marker in the test case test_subvolume_group_pinning
  tests/functional/storageclass/test_csi_subvolume_group_property.py
Labels: Verified, size/XS, Squad/Green, lgtm

#12349 FDF import fix
  .gitignore
  ocs_ci/deployment/fusion_data_foundation.py
  ocs_ci/helpers/helpers.py
Labels: team/ecosystem, size/S, Merge As Is (Don't Squash), lgtm

#12364 Update provisioner label in the test test_clone_when_full
  tests/functional/pv/pvc_clone/test_clone_when_pvc_full.py
Labels: Verified, size/XS, Squad/Green, lgtm

#12371 Fix endpoint reference
  ocs_ci/ocs/resources/mcg.py
Labels: size/XS, lgtm

#12375 Don't fail the collection of logs when running deployment
  conf/README.md
  ocs_ci/framework/pytest_customization/ocscilib.py
  tests/conftest.py
Labels: size/S, lgtm

#12383 Introduce lock for downloaing subctl binary
  ocs_ci/ocs/utils.py
Labels: team/ecosystem, size/S, lgtm, DR

#12344 increase timeout for checking toolbox
  ocs_ci/ocs/utils.py
Labels: team/ecosystem, size/XS, lgtm

#12385 Set unreleased subctl version in ocp 4.19 config
  ocs_ci/framework/conf/ocp_version/ocp-4.19-config.yaml
Labels: size/XS, lgtm

#12392 BM OCP deployment via Assisted Installer: handle pending user action
  ocs_ci/deployment/assisted_installer.py
  ocs_ci/deployment/baremetal.py
Labels: Verified, team/ecosystem, size/M, lgtm

#12382 fix test cases
  ocs_ci/ocs/resources/pod.py
  tests/cross_functional/kcs/test_noobaa_db_backup_and_recovery.py
  tests/cross_functional/kcs/test_noobaadb_pw_reset.py
Labels: Verified, size/S, lgtm

#12393 fix test_pods_csi_log_rotation 4.18,4.19
  ocs_ci/ocs/resources/pod.py
  tests/functional/pod_and_daemons/test_csi_logs_rotation.py
Labels: Verified, size/S, Squad/Brown, lgtm

#12234 Enables machine autorepair with machine health checks
  ocs_ci/deployment/helpers/hypershift_base.py
Labels: size/XS, lgtm, provider-client

#12245 Ypersky pv based bs data distribution
  tests/functional/object/mcg/test_pv_pool.py
Labels: Verified, size/L, MCG, Squad/Red, lgtm

#12395 Add loggers to Submariner unreleased installation flow
  ocs_ci/ocs/acm/acm.py
Labels: Verified, size/XS, lgtm, DR, Squad/Turquoise

#12391 Fix AttributeError in RDR Discovered apps tests
  ocs_ci/ocs/dr/dr_workload.py
  tests/conftest.py
Labels: size/XS, lgtm, Squad/Turquoise

#12415 Moved resiliency tests under tests/cross_functional/resilience folder
  tests/cross_functional/resilience/conftest.py
  tests/cross_functional/resilience/test_platfrom_failures_scenarios.py
  tests/cross_functional/resilience/test_storage_component_failure_scenarios.py
Labels: size/XS, lgtm

#12422 Increase timeout for waiting for noobaa resource
  ocs_ci/ocs/cluster.py
Labels: size/XS, lgtm

#12421 changed selector name
  tests/functional/workloads/app/test_jenkins_simulation.py
Labels: Verified, size/XS, Squad/Magenta, lgtm

#12418 Fix IBM Cloud managed deployment for 4.18
  ocs_ci/deployment/deployment.py
Labels: size/XS, lgtm

#12410 Handle cases when OCP is GAed but ODF build is not rebuilt yet
  ocs_ci/deployment/helpers/lso_helpers.py
Labels: size/XS, lgtm

#12404 Fix quickstarts UI tests
  tests/functional/ui/test_quickstarts.py
Labels: Verified, size/S, lgtm, Squad/Black

#12436 Remove test dashboard validation UI from acceptance
  tests/ui/test_validation_ui.py
Labels: size/XS, lgtm

#12432 OCP 4.19 GA config files
  ocs_ci/framework/conf/ocp_version/ocp-4.19-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.19-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.19-ga-upgrade.yaml
Labels: size/M, lgtm

#12096 Fix issue with node labels[Replica-1]
  ocs_ci/ocs/replica_one.py
  tests/functional/storageclass/test_replica1.py
Labels: Verified, size/L, lgtm

#12276 fix get_ceph_tools_pod to run with provider context
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/utils.py
Labels: size/L, lgtm

#12454 Fix to validation ui and delete cluster validation
  ocs_ci/ocs/ui/page_objects/resource_list.py
  ocs_ci/ocs/ui/views.py
  tests/cross_functional/ui/test_validation_ui.py
Labels: size/M, lgtm

#11811 Change wording of obc creation rule
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
Labels: Verified, size/XS, lgtm, Squad/Black

#12457 Fix UI deployment for 4.19
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/S, lgtm

#11336 Adding get_and_apply_idms_from_catalog function
  ocs_ci/deployment/acm.py
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/disconnected.py
  ocs_ci/deployment/helpers/hypershift_base.py
  ocs_ci/deployment/helpers/idms_parser.py
  ocs_ci/deployment/helpers/lso_helpers.py
  ocs_ci/deployment/metallb.py
  ocs_ci/helpers/disconnected.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/templates/acm-deployment/submariner_downstream_brew_idms.yaml
  ocs_ci/templates/ocp-deployment/oc-mirror-imageset-config-v2.yaml
  ocs_ci/utility/deployment.py
Labels: Verified, size/XL, lgtm

#12439 Improve noobaa pods upgrade validation
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, size/L, lgtm

#12460 fix ACM Deployment IDMS yaml - apiVersion
  ocs_ci/templates/acm-deployment/submariner_downstream_brew_idms.yaml
Labels: team/ecosystem, size/XS, lgtm

#12387 fix run_fio_benchmark_operator
  ocs_ci/ocs/benchmark_operator_fio.py
  tests/cross_functional/system_test/test_cluster_full_and_recovery.py
Labels: Verified, team/e2e, size/M, Squad/Magenta, lgtm

#12449 add more time for wait node: multi-client upgrade
  ocs_ci/utility/utils.py
Labels: size/XS, lgtm

#12274 Fixed metadata test failures
  ocs_ci/ocs/constants.py
  ocs_ci/utility/metadata_utils.py
  tests/functional/pv/add_metadata_feature/test_metadata.py
Labels: Verified, size/L, lgtm

#12452 Removing irrelevant polarion ids
  tests/functional/pv/pv_services/test_rwop_pvc.py
Labels: size/S, lgtm

#12445 get_onboarding_ticket_secret add retry
  ocs_ci/ocs/resources/storageconsumer.py
Labels: size/XS, lgtm, Squad/Yellow

#12345 Test that there are no errors in operator pod logs
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/conftest.py
  tests/functional/deployment/test_operator.py
Labels: Verified, size/M, lgtm

#12373 change MCG_NS_AWS_ENDPOINT to include region
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/cloud_manager.py
  ocs_ci/ocs/resources/mcg.py
  tests/conftest.py
  tests/functional/object/mcg/flowtest/test_mcg_namespace_disruptions_crd.py
  tests/functional/object/mcg/flowtest/test_mcg_namespace_disruptions_rpc.py
  tests/functional/object/mcg/lifecycle/test_mcg_namespace_lifecyle_crd.py
  tests/functional/object/mcg/lifecycle/test_mcg_namespace_lifecyle_rpc.py
  tests/functional/object/mcg/lifecycle/test_mcg_namespace_s3_ops_crd.py
  tests/functional/object/mcg/lifecycle/test_mcg_namespace_s3_ops_rpc.py
  tests/functional/object/mcg/test_namespace_crd.py
  tests/functional/object/mcg/test_namespace_rpc.py
Labels: Verified, team/ecosystem, size/M, lgtm

#12316 fix for 11237
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/app-pods/nfs_test_app.yaml
  ocs_ci/utility/nfs_utils.py
  ocs_ci/utility/utils.py
  tests/functional/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
Labels: Verified, size/L, Squad/Brown, lgtm

#12499 Add germenywestcentral ARO config
  conf/deployment/azure/managed_aro_germanywestcentral_3az_rhcos_3m_3w.yaml
  ocs_ci/utility/azure_utils.py
  ocs_ci/utility/ssl_certs.py
Labels: size/M, lgtm

#12496 bump mce. apply max mirrors wa for kubevirt clusters
  ocs_ci/deployment/hosted_cluster.py
  ocs_ci/deployment/mce.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/mce-deployment/mce_subscription.yaml
Labels: Verified, workaround, size/M, lgtm, Squad/Yellow, provider-client
