Repository red-hat-storage/ocs-ci, pull requests merged in 2025-08, with the labels that each got.

#12826 test_account_update_with_custom_creds_using_cli - a fix to occasional failures
  tests/functional/object/mcg/test_custom_credentials_using_mcg_cli.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm, Automation Backlog

#11977 Add RDR Upgrade scenario: Refactor the code to accomodate RDR upgrades and introduce relevant markers to the upgrade tests
  ocs_ci/ocs/constants.py
  ocs_ci/utility/multicluster.py
  tests/conftest.py
  tests/functional/upgrade/test_upgrade.py
  tests/functional/upgrade/test_upgrade_ocp.py
Labels: Verified, team/ecosystem, size/L, lgtm, DR

#12823 add toleration to drivers
  ocs_ci/helpers/helpers.py
  tests/functional/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Labels: Verified, size/L, Squad/Brown, lgtm

#12843 Updating the region of AWS
  tests/functional/object/mcg/test_namespace_crd.py
Labels: Verified, size/XS, lgtm

#12847 use endpoint and region from pytest params
  tests/functional/object/mcg/test_bucket_replication.py
  tests/functional/object/mcg/test_cached_buckets.py
  tests/functional/object/mcg/test_namespace_crd.py
Labels: Verified, size/M, lgtm

#12814 Defaulting ocs-ci to ODF 4.20
  ocs_ci/framework/conf/default_config.yaml
  setup.py
Labels: team/ecosystem, size/S, lgtm

#12291 [RDR][Mulitclient]Get provider index based on config value if present
  conf/README.md
  ocs_ci/framework/__init__.py
Labels: size/S, lgtm, provider-client

#12845 Don't use config structure as a default for namespace parameter
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/resources/namespacestore.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/storage_client.py
Labels: Verified, size/L, lgtm

#12840 configure proxy trustedCA in hosted clusters and provide custom CA certificate to AWS s3 cli pod
  ocs_ci/deployment/hosted_cluster.py
  ocs_ci/ocs/awscli_pod.py
  ocs_ci/utility/ssl_certs.py
Labels: Verified, team/ecosystem, size/M, lgtm

#12841 Fix the Ceph capacity validation after the OSD resize test
  ocs_ci/helpers/osd_resize.py
  tests/functional/z_cluster/cluster_expansion/test_resize_osd.py
Labels: Verified, size/M, Squad/Brown, lgtm

#12656 increase IBM_CLOUD_LOAD_BALANCER_QUOTA
  ocs_ci/ocs/defaults.py
Labels: team/ecosystem, size/XS, lgtm

#12269 Added must-gather test to odf4.19
  ocs_ci/ocs/must_gather/const_must_gather.py
Labels: size/S, lgtm

#12876 Update Release branch for ocs-workloads
  conf/ocsci/dr_workload.yaml
Labels: size/XS, lgtm, DR

#12574 Update cluster context in tier1/tier4 tests
  ocs_ci/ocs/fiojob.py
  tests/functional/monitoring/prometheus/alerts/test_ceph.py
  tests/functional/monitoring/prometheus/alerts/test_encryption.py
  tests/functional/monitoring/prometheus/alerts/test_hpa.py
  tests/functional/monitoring/prometheus/alerts/test_noobaa.py
  tests/functional/monitoring/prometheus/alerts/test_prometheus_rules.py
  tests/functional/monitoring/prometheus/alerts/test_rgw.py
  tests/functional/object/mcg/test_bucket_creation_deletion.py
  tests/functional/object/mcg/test_noobaa_secret.py
  tests/functional/object/mcg/test_verify_noobaa_status.py
Labels: Verified, size/L, lgtm, provider-client

#12890 Skip customstorageclass tests on provider mode
  tests/functional/storageclass/test_custom_storageclass_names.py
Labels: size/XS, lgtm

#12899 Wait before verifying removal of OSD
  ocs_ci/ocs/resources/pod.py
Labels: Verified, TestCase failing, size/XS, Squad/Brown, lgtm

#12860 raise appropriate error when Noobaa encryption key not found in CipherTrust Manager
  ocs_ci/utility/kms.py
Labels: size/XS, lgtm

#12851 [release-4.18] [RDR] Update MirrorPeer template to remove deprecated field
  ocs_ci/templates/ocs-deployment/multicluster/mirror_peer_rdr.yaml
Labels: Verified, size/XS, lgtm, Squad/Turquoise

#12689 [release-4.18] Add report cli arg for fusion and fdf
  ocs_ci/utility/framework/fusion_fdf_init.py
Labels: team/ecosystem, size/S, lgtm, cherry-pick

#12885 Fix test_noobaa_secret_in_env_variable
  ocs_ci/deployment/helpers/mcg_helpers.py
Labels: Verified, size/M, MCG, Squad/Red, lgtm, provider-client

#12071 Added validation for pod STATUS_COMPLETED
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/S, Squad/Brown, lgtm

#12932 consumer-verification-on-client-creation fix
  ocs_ci/deployment/hosted_cluster.py
Labels: Verified, size/XS, lgtm, provider-client, provider mode deployment

#12892 Except missing storagesystem CR
  tests/functional/z_cluster/test_storagesystem.py
Labels: bug, Verified, size/S, lgtm

#12041 Run on all clients push missing configs
  ocs_ci/deployment/helpers/hypershift_base.py
  ocs_ci/deployment/hosted_cluster.py
  ocs_ci/deployment/ocp.py
  ocs_ci/framework/exceptions.py
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/ocs.py
  ocs_ci/ocs/resources/packagemanifest.py
  ocs_ci/utility/version.py
  tests/conftest.py
  tests/functional/object/mcg/test_provider_client.py
  tests/functional/pod_and_daemons/test_ephemeral_pod.py
  tests/functional/pv/pv_services/test_create_large_sized_pvc_while_io_in_progress.py
  tests/functional/pv/pv_services/test_pvc_concurrent_deletion_creation.py
  tests/functional/pv/pv_services/test_pvc_deletion_during_io.py
  tests/functional/pv/pv_services/test_pvc_rwx_writeable_after_pod_deletions.py
  tests/functional/pv/pv_services/test_raw_block_pv.py
  tests/functional/pv/pv_services/test_run_io_multiple_pods.py
  tests/functional/pv/pv_services/test_rwop_pvc.py
  tests/functional/pv/pv_services/test_verify_rwo_using_multiple_pods.py
  tests/functional/pv/pvc_clone/test_pvc_to_pvc_clone.py
  tests/functional/pv/pvc_resize/test_pvc_expansion.py
  tests/functional/pv/pvc_snapshot/test_pvc_snapshot.py
  tests/functional/pv/pvc_snapshot/test_rbd_block_pvc_snapshot.py
  tests/functional/pv/pvc_snapshot/test_snapshot_restore_with_different_access_mode.py
  tests/libtest/test_multicluster.py
Labels: Verified, size/XL, lgtm

#12947 fix setup_multicluster_marker
  ocs_ci/framework/pytest_customization/marks.py
Labels: size/S, lgtm

#12888 fix_ceph_health to True in install verification
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#12867 fix uniqueidentifier in cs-thales-kmip
  ocs_ci/utility/kms.py
Labels: Verified, size/XS, lgtm

#12973 Moving test_create_scale_pods_and_pvcs_using_kube_job to orange squad
  tests/functional/workloads/test_create_scale_pods_and_pvcs_using_kube_job.py
Labels: size/XS, Squad/Orange, Squad/Magenta, lgtm

#12341 delete IBM resources based in resource id
  ocs_ci/deployment/ibmcloud.py
Labels: team/ecosystem, size/M, lgtm

#12949 Increase timeout for PVC factory
  tests/functional/pv/pvc_resize/test_pvc_expansion.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#12902 Fix s3_copy_object for when metadata is not provided
  ocs_ci/ocs/bucket_utils.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#12963 Improve IBM Cloud force cleanup
  ocs_ci/deployment/ibmcloud.py
Labels: size/L, lgtm

#11088 CNV abrupt shutdown cluster while VMs in different state.
  ocs_ci/ocs/cnv/virtctl.py
  ocs_ci/ocs/cnv/virtual_machine.py
  tests/conftest.py
  tests/functional/workloads/cnv/test_cnv_cluster_shutdown_recovery.py
Labels: Verified, team/e2e, size/L, lgtm

#12988 Improve hypercovnerged deployment in CNV
  ocs_ci/utility/retry.py
  ocs_ci/utility/utils.py
Labels: size/S, lgtm

#13000 Re-try exec_cmd in case of client connetion lost
  ocs_ci/utility/retry.py
  ocs_ci/utility/utils.py
Labels: size/S, lgtm

#12993 Fix the function that get the hosted cluster names
  ocs_ci/deployment/helpers/hypershift_base.py
Labels: Verified, size/XS, lgtm, provider-client

#12989 correct idms that fails deploy metallb
  ocs_ci/deployment/helpers/lso_helpers.py
  ocs_ci/deployment/metallb.py
  ocs_ci/ocs/constants.py
Labels: size/L, lgtm

#13004 Fix the DB query in test_unidirectional_bucketclass_replication
  tests/functional/object/mcg/test_bucket_replication.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#12527 Adds support of md_blow tool
  ocs_ci/ocs/md_blow.py
Labels: Verified, size/L, MCG, Squad/Red, lgtm

#13011 Add Submariner support over IBM CLOUD IPI (#12146)
  ocs_ci/deployment/acm.py
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/templates/acm-deployment/clusterset.yaml
  ocs_ci/templates/acm-deployment/submariner_addon.yaml
  ocs_ci/templates/acm-deployment/submariner_broker.yaml
  ocs_ci/templates/acm-deployment/submariner_config.yaml
  ocs_ci/utility/ibmcloud.py
Labels: Verified, size/L, lgtm

#12960 Add decorator to wrap functions with RunWithProviderConfigContextIfAvailable
  ocs_ci/framework/__init__.py
  tests/libtest/test_multicluster.py
Labels: enhancement, Verified, size/M, lgtm, provider-client

#13040 Increase timeout for snapshot restore in test test_pvc_snapshot
  tests/functional/pv/pvc_snapshot/test_pvc_snapshot.py
Labels: size/XS, lgtm

#13053 patch the storageclient with storageconsumer uid
  ocs_ci/helpers/helpers.py
Labels: Verified, team/ecosystem, size/M, lgtm

#13052 Fix image tag discovery condition
  ocs_ci/deployment/deployment.py
  ocs_ci/utility/multicluster.py
Labels: Verified, size/S, lgtm
