Repository red-hat-storage/ocs-ci, pull requests merged in 2025-09, with the labels that each got.

#13070 remove adm-d mirrors for metallb installation
  ocs_ci/deployment/metallb.py
Labels: Verified, size/XS, lgtm, provider mode deployment

#12874 hub-spoke-deployment-merge for hub depl stage
  conf/README.md
  conf/deployment/baremetal/ai_1az_rhcos_nvme_intel_3m_3w_hci.yaml
  conf/deployment/fusion_hci_pc/provider_bm_upi_1az_rhcos_nvme_3m_3w.yaml
  conf/deployment/vsphere/ipi_1az_rhcos_vsan_3m_3w_multi_client_hub.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/hosted_cluster.py
  ocs_ci/deployment/provider_client/storage_client_deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocs-deployment/provider-mode/ocs_storagecluster.yaml
  ocs_ci/templates/ocs-deployment/provider-mode/ocs_storagecluster_converged.yaml
  ocs_ci/templates/ocs-deployment/provider-mode/ocs_storagecluster_updated.yaml
  tests/functional/deployment/test_deployment.py
Labels: size/XL, lgtm, provider-client

#13083 use odf-cli for live deployments
  ocs_ci/helpers/helpers.py
Labels: Verified, team/ecosystem, size/S, lgtm

#12999 [CNV + ODF] Validate Clone of restored VM
  tests/functional/workloads/cnv/test_vm_snapshot_cloning_ops.py
Labels: Verified, size/M, Squad/Magenta, lgtm

#13057 update RHCOS for ODF 4.20
  ocs_ci/framework/conf/ocp_version/ocp-4.20-config.yaml
Labels: Verified, team/ecosystem, size/XS, lgtm

#12971 disconnected packages for 4.20
  ocs_ci/ocs/constants.py
Labels: Needs Testing, team/ecosystem, size/XS, lgtm

#12771 Fusion FDF ReportPortal compatibility fixes
  ocs_ci/utility/framework/fusion_fdf_init.py
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/M, lgtm

#13039 Adjusted Test ceph_config_values_in_rook_config_override to 4.20
  ocs_ci/ocs/constants.py
  tests/functional/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/M, lgtm

#13038 Add max_servers parameter to control FIO server pod count
  ocs_ci/ocs/benchmark_operator_fio.py
  tests/conftest.py
  tests/functional/z_cluster/cluster_expansion/test_storage_auto_scaling.py
  tests/libtest/test_benchmark_operator.py
Labels: Verified, size/M, Squad/Brown, lgtm

#13103 Default to Released version for ACM in 4.19
  ocs_ci/framework/conf/ocp_version/ocp-4.19-config.yaml
Labels: size/XS, lgtm

#13013 <GSS Closed Loop BZ: 2141422> Verify mds cache trim in standby-replay mode
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/helpers/e2e_helpers.py
  tests/functional/pod_and_daemons/test_mds_cache_trim_standby.py
Labels: Verified, team/e2e, size/L, Customer defects, lgtm

#13108 increase timeout for registry-cephfs-rwx-pvc
  ocs_ci/ocs/registry.py
Labels: team/ecosystem, size/XS, lgtm

#13114 Apply W/A for ACM bug in 4.19
  ocs_ci/deployment/deployment.py
Labels: size/S, lgtm

#13043 Update BucketNotificationsManager::get_events to filter out NooBaa's TestEvent
  ocs_ci/ocs/resources/bucket_notifications_manager.py
  tests/functional/object/mcg/test_bucket_notifications.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#13037 update cluster context of noobaa resources
  ocs_ci/ocs/resources/backingstore.py
  ocs_ci/ocs/resources/bucketclass.py
  ocs_ci/ocs/resources/cloud_manager.py
  ocs_ci/ocs/resources/cloud_uls.py
  tests/conftest.py
Labels: Verified, size/XL, lgtm

#13120 Fix disconnected packages for 4.20
  ocs_ci/helpers/disconnected.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/S, lgtm

#13044 Test automation for the feature enforce schedule precedance for reclaimspace and keyrotation operation.
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
  tests/conftest.py
  tests/functional/pv/pv_encryption/test_disable_pv_keyrotation.py
  tests/functional/pv/space_reclaim/test_auto_reclaim_space_cronjob.py
  tests/functional/pv/space_reclaim/test_disable_reclaimspace_operation.py
  tests/functional/pv/space_reclaim/test_rbd_reclaimspace_cronjob.py
  tests/functional/storageclass/test_enforce_storageclass_precedance_for_KRRS.py
  tests/functional/storageclass/test_storageclass_reclaim_space.py
Labels: Verified, size/XL, lgtm

#13149 Add missing key when importing MCE cluster to ACM
  ocs_ci/ocs/acm/acm.py
Labels: Verified, size/XS, lgtm, DR

#13135 Fix race condition: test accessed clusterresourcequota before StorageCluster created it
  tests/functional/pv/pv_services/test_overprovision_level_policy_control_with_capacity.py
Labels: Verified, size/S, lgtm

#12206 Multiple failovers/relocates without any disruptions of discovered apps
  tests/conftest.py
  tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate_discovered_apps.py
Labels: Verified, size/L, lgtm, DR

#13182 Add IBM Cloud to platforms for UI deployment
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/page_objects/page_navigator.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/XS, lgtm, Squad/Black

#13145 fix(test_csiaddon_pod_security.py): adapt CSI addon pod security test for ODF 4.20 version
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  tests/functional/pod_and_daemons/test_csiaddon_pod_security.py
Labels: Verified, size/M, lgtm

#13111 Fix conflict with packagemanifest for mcg-operator from submariner CS
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/packagemanifest.py
Labels: Verified, team/ecosystem, size/XS, lgtm, DR

#13156 Fix restart_nodes_by_stop_and_start_force for IBM Cloud
  ocs_ci/utility/ibmcloud.py
Labels: Verified, size/M, lgtm

#13158 Fix restart_nodes_by_stop_and_start_force for IBM Cloud
  ocs_ci/utility/ibmcloud.py
Labels: Verified, size/M, lgtm

#12931 Ignore failures in rpm collector which causes test_change_cluster_resource_profile to fail
  tests/conftest.py
  tests/functional/z_cluster/test_performance_profile_validation.py
Labels: Verified, size/S, Squad/Brown, lgtm

#13085 Adding tests for RHSTOR-7208
  ocs_ci/ocs/bucket_utils.py
  tests/functional/object/mcg/test_bucket_replication_and_its_metrics.py
Labels: Verified, size/L, Squad/Red, lgtm

#12641 Added marker to skip for hci-clients
  tests/functional/z_cluster/test_multiple_mds.py
  tests/functional/z_cluster/test_storagesystem.py
Labels: Verified, size/XS, lgtm

#13227 fix(test_disable_pv_keyrotation_globally): resolve timing issue in PV key rotation disable/enable test
  ocs_ci/helpers/keyrotation_helper.py
  tests/functional/pv/pv_encryption/test_disable_pv_keyrotation.py
Labels: Verified, size/M, lgtm

#13223 test_credentials_reset.py: Restore tests that were accidentally removed
  tests/functional/object/mcg/test_credentials_reset.py
Labels: Verified, size/L, MCG, Squad/Red, lgtm

#12166 Run IO during PVC expansion in test case test_pvc_expand_expanded_pvc
  tests/functional/pv/pvc_resize/test_pvc_expansion.py
Labels: Verified, size/M, Squad/Green, lgtm

#13238 Fixed (updated) constant for rook-ceph-values 4.20
  ocs_ci/ocs/constants.py
Labels: High Priority, Verified, size/XS, Squad/Brown, lgtm

#12978 Support RDR deployment on provider and client clusters
  conf/README.md
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/__init__.py
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/acm/acm.py
  ocs_ci/utility/version.py
Labels: Verified, size/L, lgtm, provider-client

#13208 POM flow change 4.20
  ocs_ci/helpers/osd_resize.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/block_pool.py
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/page_objects/block_and_file.py
  ocs_ci/ocs/ui/page_objects/block_pools.py
  ocs_ci/ocs/ui/page_objects/ceph_block_pool.py
  ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
  ocs_ci/ocs/ui/page_objects/df_overview.py
  ocs_ci/ocs/ui/page_objects/overview_tab.py
  ocs_ci/ocs/ui/page_objects/page_navigator.py
  ocs_ci/ocs/ui/page_objects/resource_list.py
  ocs_ci/ocs/ui/page_objects/storage_cluster.py
  ocs_ci/ocs/ui/page_objects/storage_system_details.py
  ocs_ci/ocs/ui/page_objects/storage_system_tab.py
  ocs_ci/ocs/ui/validation_ui.py
  ocs_ci/ocs/ui/views.py
  tests/cross_functional/ui/test_odf_topology.py
  tests/cross_functional/ui/test_validation_ui.py
  tests/functional/encryption/test_encryption_configuration_dashboard.py
  tests/functional/storageclass/test_delete_rbd_pool_attached_to_sc.py
  tests/functional/ui/test_capacity_breakdown_ui.py
  tests/functional/ui/test_error_improvements.py
  tests/functional/ui/test_odf_storage_consumption_trend.py
  tests/libtest/test_ui_pom.py
Labels: size/XXL, lgtm

#13248 Submariner install on client clusters
  ocs_ci/deployment/acm.py
  ocs_ci/ocs/acm/acm.py
Labels: Verified, size/M, lgtm, provider-client

#13256 Adding ODF 4.21 config files
  ocs_ci/framework/conf/ocs_version/ocs-4.21.yaml
  ocs_ci/utility/framework/initialization.py
Labels: team/ecosystem, size/S, lgtm

#13250 Removing metadata disable tests cases
  ocs_ci/utility/metadata_utils.py
  tests/functional/pv/add_metadata_feature/test_metadata.py
Labels: size/L, Squad/Green, lgtm

#13204 Make 'disable_default_sources' default True for hcp clusters
  ocs_ci/deployment/hosted_cluster.py
Labels: size/XS, lgtm, provider-client

#13278 Fix UI deployment for 4.20
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/XS, lgtm, Squad/Black

#13231 switch context on deployment_pod_factory factory. Unblock pvc deletion.
  tests/conftest.py
  tests/functional/pv/pv_services/test_run_io_multiple_pods.py
Labels: Verified, size/M, lgtm

#13288 locators-for-dashboard420
  ocs_ci/ocs/ui/views.py
Labels: size/M, ui_automation, lgtm

#13287 test_obj_owner_in_obc_buckets.py - increasing timeout for nss reaching healthy state
  ocs_ci/ocs/resources/namespacestore.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm, Automation Backlog

#13274 A fix to test_pv_data_dist - increasing backingstore deletion timeout
  tests/functional/object/mcg/test_pv_pool.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm, Automation Backlog

#13225 Fixing Bugs for FDF Deployment on some SDS cluster
  ocs_ci/deployment/fusion_data_foundation.py
  ocs_ci/framework/conf/fdf_version/fdf-4.18.yaml
  ocs_ci/templates/fusion-data-foundation/data-foundation-instance.yaml
Labels: team/ecosystem, size/M, lgtm
