Repository red-hat-storage/ocs-ci, pull requests merged in 2025-07, with the labels that each got.

#12514 increase retry for fetching noobaa pods during upgrade
  ocs_ci/ocs/ocs_upgrade.py
Labels: Needs Testing, team/ecosystem, lgtm

#12465 add retry on backingstore readiness
  ocs_ci/ocs/bucket_utils.py
Labels: Verified, size/XS, lgtm

#12536 Update condition for slow ops W/A to be applied from 4.18
  ocs_ci/deployment/deployment.py
Labels: size/XS, lgtm

#12522 Fixes typo while applying notification to bucket
  ocs_ci/ocs/resources/bucket_notifications_manager.py
Labels: High Priority, Verified, MCG, lgtm

#12529 Debug RGW ceph override
  conf/README.md
  conf/ocsci/cephClusterDebugRgw.yaml
  ocs_ci/deployment/deployment.py
Labels: Verified, size/S, lgtm

#12531 Increase timeout for OCP upgrade
  tests/functional/upgrade/test_upgrade_ocp.py
Labels: Verified, size/XS, lgtm

#12556 disable consumer check to prevent build failures
  ocs_ci/ocs/resources/storageconsumer.py
Labels: size/XS, lgtm, product-bug

#12560 disable-consumer-check-tmp-typeerror
  ocs_ci/ocs/resources/storageconsumer.py
Labels: size/XS, lgtm

#12447 fix ns for multi-client deployment
  ocs_ci/deployment/cnv.py
Labels: Verified, size/XS, lgtm, provider mode deployment

#12564 Fixes CORS script for ipV6 deployment
  tests/functional/object/mcg/test_cors_config_elements.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm

#12477 Consider provider mode and odf upgrade for operator pod tests
  tests/conftest.py
  tests/functional/deployment/test_operator.py
Labels: Verified, size/M, lgtm

#12572 [release-4.18] update condition for slowops for upgrade
  ocs_ci/ocs/ocs_upgrade.py
Labels: size/XS, lgtm

#12566 bump catsrc of hcp clients on upgrade
  ocs_ci/deployment/hosted_cluster.py
  ocs_ci/ocs/acm_upgrade.py
  ocs_ci/ocs/provider_client_upgrade.py
Labels: Verified, size/M, lgtm, provider mode deployment

#12561 Wait more time for verifying the node names in the Ceph OSD status
  ocs_ci/ocs/machine.py
  ocs_ci/ocs/node.py
Labels: Verified, size/M, Squad/Brown, lgtm

#12578 removed import create_unique_resource_name from vm_snapshot_restore_f…
  tests/conftest.py
Labels: Verified, size/XS, Squad/Magenta, lgtm

#12233 Parameterize rdr_ui tests with CLI and remove using global config
  conf/ocsci/dr_ui.yaml
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/helpers/dr_helpers_ui.py
  ocs_ci/ocs/acm/acm.py
  tests/conftest.py
  tests/functional/disaster-recovery/regional-dr/test_failover.py
  tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate.py
  tests/functional/disaster-recovery/regional-dr/test_negative_failover_relocate_ui.py
  tests/functional/disaster-recovery/regional-dr/test_rdr_monitoring_dashboard_ui.py
  tests/functional/disaster-recovery/regional-dr/test_relocate.py
  tests/functional/disaster-recovery/regional-dr/test_warning_and_alerting.py
Labels: Verified, size/L, lgtm, DR, Squad/Turquoise

#12588 Fix ceph_rocksdb_* metric names
  ocs_ci/ocs/metrics.py
Labels: Verified, size/XS, Squad/Blue, lgtm

#12583 Fixes method name mismatch issue while calling it
  tests/functional/object/rgw/test_rgw_read_affinity.py
Labels: Verified, size/XS, RGW, Squad/Red, lgtm

#12591 Fix noobaa pods for MCG Only deployment
  ocs_ci/ocs/ocs_upgrade.py
Labels: size/M, lgtm

#12586 Fix MDR setup with avoiding removal rgw-admin-ops-user for non primary cluster
  ocs_ci/deployment/helpers/external_cluster_helpers.py
Labels: Verified, size/XS, lgtm

#12552 Update DPA yaml for Hub recovery with ACM 2.14/ODF 4.19
  ocs_ci/templates/ocs-deployment/multicluster/dpa_acm.yaml
Labels: Verified, size/XS, lgtm, DR, Squad/Turquoise

#12554 Retry AMQ cleanup if failed due to temporay issue
  ocs_ci/ocs/amq.py
  tests/functional/workloads/app/amq/test_amq_node_reboot_and_shutdown.py
Labels: Verified, size/L, Squad/Magenta, lgtm

#12623 Stop exporting workload data to google spreadhseet
  tests/functional/workloads/app/couchbase/test_couchbase.py
  tests/functional/workloads/app/jenkins/test_jenkins.py
  tests/functional/workloads/app/pgsql/test_pgsql.py
Labels: team/e2e, size/S, Squad/Magenta, lgtm

#12611 Fix 4.19 UI deployment to meet convergence changes
  ocs_ci/ocs/ui/deployment_ui.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/L, ui_automation, lgtm

#12519 Added placement related changes and removed placementrule from "deploy_workloads_on_managed_clusters" fixture
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/dr/dr_workload.py
  tests/conftest.py
  tests/functional/disaster-recovery/metro-dr/test_multiple_apps_failover_and_relocate.py
Labels: Verified, size/L, lgtm, DR

#12637 update must gather image for 4.20
  ocs_ci/framework/conf/ocs_version/ocs-4.20.yaml
Labels: team/ecosystem, size/XS, lgtm

#12642 get storageclass for vSphere cluster
  ocs_ci/deployment/helpers/storage_class.py
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#12639 To skip system_test.test_mcg_replication_with_disruptions on aws
  tests/cross_functional/system_test/test_mcg_replication_with_disruptions.py
Labels: TestCase failing, team/e2e, size/XS, Squad/Magenta, lgtm

#12167 Added 4.19 values- test_validate_ceph_config_values_in_rook_config_override
  ocs_ci/ocs/constants.py
  tests/functional/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/M, lgtm

#12636 Create submariner catsrc when deploying submariner from CLI
  ocs_ci/ocs/acm/acm.py
Labels: Verified, size/M, lgtm, DR

#12594 Deploy ACM build from Konflux repo
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/ocp_version/ocp-4.19-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.19-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.19-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.20-config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/templates/acm-deployment/acm_brew_idms.yaml
  ocs_ci/templates/acm-deployment/acm_catalogsource.yaml
  ocs_ci/templates/acm-deployment/mce_catalogsource.yaml
  tests/functional/deployment/test_acm.py
Labels: Verified, size/L, lgtm, DR

#12648 Fix all clusters locator for 4.19
  ocs_ci/ocs/ui/views.py
Labels: Verified, size/S, lgtm, Squad/Black

#12609 initialize vrg_list
  ocs_ci/helpers/dr_helpers.py
Labels: team/ecosystem, size/XS, lgtm

#12661 changed version check to live check
  tests/functional/z_cluster/test_ceph_default_values_check.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#12671 Fix for function get_csvs_start_with_prefix
  ocs_ci/ocs/resources/csv.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#12665 fix retry code for StorageCluster creation
  ocs_ci/deployment/provider_client/storage_client_deployment.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#12254 Create new decorator to enable the recovery profile High in the Ceph rebalance
  conf/ocsci/disable_high_recovery_during_rebalance.yaml
  ocs_ci/deployment/helpers/odf_deployment_helpers.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/helpers/odf_cli.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/utility/decorators.py
  tests/functional/conftest.py
  tests/functional/z_cluster/cluster_expansion/test_add_capacity.py
  tests/libtest/test_wait_for_ceph_rebalance.py
Labels: Verified, team/ecosystem, size/L, Squad/Brown, lgtm

#12635 Skips executing IBM backed NSFS creation test if FIPS is enabled on cluster
  tests/functional/object/mcg/test_namespace_crd.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm, backport-required

#12629 Fixes rgw object download method
  ocs_ci/ocs/bucket_utils.py
Labels: Verified, size/S, RGW, Squad/Red, lgtm

#12654 remove storagesystem creation in multistoragecluster
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#12655 OCP upgrade timeout
  tests/functional/upgrade/test_upgrade_ocp.py
Labels: team/ecosystem, size/XS, upgrade, lgtm

#12662 support to install previous Fusion GA releases
  docs/usecases/fusion_and_fdf.md
  ocs_ci/deployment/fusion.py
  ocs_ci/framework/conf/fusion_version/fusion-2.10-ga.yaml
  ocs_ci/framework/conf/fusion_version/fusion-2.8-ga.yaml
  ocs_ci/framework/conf/fusion_version/fusion-2.9-ga.yaml
Labels: team/ecosystem, size/S, lgtm

#10857 [MCG Stress Testing] Stress the cluster with bulk s3 operations
  ocs_ci/helpers/helpers.py
  ocs_ci/helpers/mcg_stress_helper.py
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/bucket_policy.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/templates/mcg/stress-cli-service-ca-configmap.yaml
  ocs_ci/templates/mcg/stress-cli-sts.yaml
  tests/conftest.py
  tests/cross_functional/conftest.py
  tests/cross_functional/stress/test_noobaa_under_stress.py
Labels: Verified, team/e2e, size/XXL, MCG, Squad/Red, lgtm, stress-automation

#12673 Improve wait_for_storage_pod
  ocs_ci/ocs/resources/pod.py
  tests/functional/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
Labels: Verified, size/S, Squad/Brown, lgtm

#12417 [stretch-cluster] Add sync vm data writes
  tests/functional/disaster-recovery/sc_arbiter/test_add_capacity.py
  tests/functional/disaster-recovery/sc_arbiter/test_device_replacement.py
  tests/functional/disaster-recovery/sc_arbiter/test_mon_osd_failures.py
  tests/functional/disaster-recovery/sc_arbiter/test_netsplit.py
  tests/functional/disaster-recovery/sc_arbiter/test_zone_shutdown_and_crash.py
  tests/functional/disaster-recovery/sc_arbiter/test_zone_unaware_app.py
Labels: Verified, team/e2e, size/L, lgtm

#12714 Add konflux_build flag to 4.17 and 4.16
  ocs_ci/framework/conf/ocs_version/ocs-4.16.yaml
  ocs_ci/framework/conf/ocs_version/ocs-4.17.yaml
Labels: size/XS, lgtm

#12715 Adjust stage testing for konflux builds
  conf/README.md
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/ocs_version/ocs-4.18.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/templates/ocs-deployment/stageImageContentSourcePolicy.yaml
  ocs_ci/templates/ocs-deployment/stage_image_digest_mirror_set.yaml
  ocs_ci/templates/ocs-deployment/stage_image_tag_mirror_set.yaml
  ocs_ci/utility/deployment.py
Labels: size/L, lgtm

#12722 increase-timeout-storageClient-create
  ocs_ci/deployment/hosted_cluster.py
Labels: size/XS, lgtm

#12412 Execute priority test cases from all clients
  tests/conftest.py
  tests/functional/pv/pv_services/test_create_large_sized_pvc_while_io_in_progress.py
  tests/functional/pv/pv_services/test_pvc_concurrent_deletion_creation.py
  tests/functional/pv/pv_services/test_pvc_deletion_during_io.py
  tests/functional/pv/pv_services/test_pvc_rwx_writeable_after_pod_deletions.py
  tests/functional/pv/pv_services/test_raw_block_pv.py
  tests/functional/pv/pv_services/test_run_io_multiple_pods.py
  tests/functional/pv/pv_services/test_verify_rwo_using_multiple_pods.py
  tests/functional/pv/pvc_clone/test_pvc_to_pvc_clone.py
  tests/functional/pv/pvc_resize/test_pvc_expansion.py
  tests/functional/pv/pvc_snapshot/test_pvc_snapshot.py
  tests/functional/pv/pvc_snapshot/test_rbd_block_pvc_snapshot.py
  tests/functional/pv/pvc_snapshot/test_snapshot_restore_with_different_access_mode.py
  tests/libtest/test_multicluster.py
Labels: Verified, size/L, lgtm, provider-client

#12646 Add runs_on_provider decorator in TestMonFailuresWithIntransitEncryption
  tests/functional/encryption/test_mon_failure_in_intransit_encryption.py
Labels: size/XS, lgtm, provider-client

#12745 enable workload_ui.WorkloadUi for disconnected clusters
  ocs_ci/ocs/ui/workload_ui.py
Labels: team/ecosystem, size/XS, lgtm

#12751 Inscreasing timeouts for nss creation and nss deletion
  ocs_ci/ocs/resources/namespacestore.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm, Automation Backlog

#12735 delete subscriptions webhook and bring down ocs-client-operator-controller-manager
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, size/S, lgtm

#12736 Skip crash test in stretch cluster until we have WA implemented or fix
  tests/functional/disaster-recovery/sc_arbiter/test_zone_shutdown_and_crash.py
Labels: Verified, team/e2e, size/XS, lgtm

#12770 Removed test TestDefaultMetadataDisabled since metadata is enabled by default from 4.19
  tests/functional/pv/add_metadata_feature/test_metadata.py
Labels: size/M, lgtm

#12785 use latest oc-mirror version for images mirroring - release-4.17
  ocs_ci/helpers/disconnected.py
Labels: team/ecosystem, size/XS, lgtm

#12495 Adding Vdbench Workload Automation to ocs-ci
  ocs_ci/helpers/vdbench_helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/resiliency/resiliency_helper.py
  ocs_ci/resiliency/resiliency_workload.py
  ocs_ci/templates/workloads/vdbench/configmap.yaml.j2
  ocs_ci/templates/workloads/vdbench/deployment.yaml.j2
  ocs_ci/templates/workloads/vdbench/vdbench_benchmark.yaml.j2
  ocs_ci/workloads/README.md
  ocs_ci/workloads/__init__.py
  ocs_ci/workloads/vdbench.py
  tests/cross_functional/resilience/conftest.py
  tests/cross_functional/resilience/test_app_scale_on_storage_component_failure.py
Labels: Verified, size/XXL, lgtm

#12769 use timeout which is more than mcp timeout in exec_cmd
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/S, lgtm

#12762 enable workload_ui.WorkloadUi for disconnected clusters - backport to release-4.17
  ocs_ci/ocs/ui/workload_ui.py
Labels: Verified, team/ecosystem, size/S, lgtm

#12746 Check objecstore users with retry
  ocs_ci/deployment/deployment.py
Labels: size/M, lgtm

#12686 Increase retry in validate_ciphertrust_deployment
  ocs_ci/utility/kms.py
Labels: size/XS, lgtm

#12754 Update fusion and fdf deployment doc
  docs/usecases/fusion_and_fdf.md
Labels: documentation, team/ecosystem, size/S, lgtm

#12802 Retry ocs olm operator query if the response is not ok
  ocs_ci/utility/utils.py
Labels: Verified, team/ecosystem, size/M, lgtm

#12806 remove WA of deleting subscriptions webhook
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/S, lgtm

#12674 Add a new test for autoscaler behavior with OCS operator deletion and updates metadata for existing autoscaler-related tests
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/cluster.py
  tests/functional/z_cluster/cluster_expansion/test_storage_auto_scaling.py
Labels: Verified, size/L, new feature, Squad/Brown, lgtm

#12680 Adds custom config to verify dedup feature for 4.16
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/mcg.py
  tests/conftest.py
  tests/functional/object/mcg/test_write_to_bucket.py
Labels: Verified, size/L, MCG, Squad/Red, lgtm, cherry-pick

#12616 Issue#11479 is uncertain issue while execution because slowness in update
  tests/functional/upgrade/test_configuration.py
Labels: Verified, size/XS, lgtm

#12718 Fixed Leftover exception due to job-pods
  ocs_ci/utility/environment_check.py
Labels: Verified, size/M, lgtm

#12816 Skipping ocp-logging due to issue 11604 (#12699)
  ocs_ci/utility/deployment_openshift_logging.py
  tests/functional/workloads/ocp/logging/test_openshift-logging.py
Labels: size/XS, lgtm

#12819 Revert "Adds custom config to verify dedup feature for 4.16"
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/mcg.py
  tests/conftest.py
  tests/functional/object/mcg/test_write_to_bucket.py
Labels: size/L, lgtm
