Repository red-hat-storage/ocs-ci, pull requests merged in 2025-05, with the labels that each got.

#12032 Fix test_automated_recovery_from_stopped_node_and_start[True] on clusters with 6W
  ocs_ci/ocs/node.py
  tests/functional/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
Labels: High Priority, Verified, size/M, Squad/Brown, lgtm

#12051 Bump pytest-jira package and openshift-python-wrapper version
  setup.py
Labels: size/XS, lgtm

#12045 use 4.19 version instead of z version
  ocs_ci/deployment/helpers/odf_deployment_helpers.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/ocs/utils.py
Labels: Verified, team/ecosystem, size/L, lgtm

#11352 Skipif added to test test_debug_verbosity_of_ceph_components
  tests/functional/odf-cli/test_debug_verbocity_of_ceph_component.py
Labels: size/XS, lgtm

#11931 Add configuration of cephfs plugin update strategy for TC OCS-6709
  conf/upgrade/cephfs_update_strategy_50p.yaml
  conf/upgrade/rbd_update_strategy_50p.yaml
Labels: Verified, size/S, lgtm

#11756 [RHSTOR-6624] - Missing MCG Lifecycle Configuration rules: basic tests and utils
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/resources/mcg_lifecycle_policies.py
  tests/functional/object/mcg/test_lifecycle_configuration.py
Labels: Verified, size/XL, MCG, Squad/Red, lgtm

#12049 Fix slow ops issue in rdr deployment
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/utility/utils.py
Labels: size/M, lgtm

#12054 increase timeout for checking noobaa pods after upgrade
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, size/XS, lgtm

#12052 noobaa-default-backing-store-noobaa-pod is part of default_noobaa_pods in MCG only deployment
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#12072 Fix slow ops issue in rdr deployment
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/utility/utils.py
Labels: size/M, lgtm

#12079 [release-4.18] recover module crash
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/XS, lgtm

#11757 Add Multi Namespace Test for Discovered apps using resource label
  conf/ocsci/dr_workload.yaml
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/dr/dr_workload.py
  tests/conftest.py
  tests/functional/disaster-recovery/regional-dr/test_cnv_failover_and_relocate_discovered_apps.py
  tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate_discovered_apps.py
  tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate_discovered_apps_multi_ns.py
Labels: Verified, size/XL, lgtm, DR

#12056 Compose rdr_ui marker with skipif
  ocs_ci/framework/pytest_customization/marks.py
Labels: Verified, size/XS, lgtm

#12065 Switch to Release branch release-4.16
  conf/ocsci/dr_workload.yaml
Labels: lgtm, DR

#12063 Switch to Release branch release-4.18
  conf/ocsci/dr_workload.yaml
Labels: size/XS, lgtm, DR

#12061 Switch to Release branch release-4.17
  conf/ocsci/dr_workload.yaml
Labels: size/XS, lgtm, DR

#12034 Add CSI Addon Pod Security Validation Test
  ocs_ci/ocs/resources/pod.py
  tests/functional/pod_and_daemons/test_csiaddon_pod_security.py
Labels: Verified, size/L, lgtm

#12083 Make sure run_id is unique by using miliseconds instead of only seconds
  ocs_ci/utility/framework/fusion_fdf_init.py
  ocs_ci/utility/framework/initialization.py
Labels: team/ecosystem, size/XS, lgtm

#12086 fix existing yaml configs with nodepool replicas
  conf/deployment/fusion_hci_pc/client_bm_upi_1az_rhcos_nvme_2w.yaml
  conf/deployment/fusion_hci_pc/client_bm_upi_1az_rhcos_nvme_3w.yaml
Labels: Verified, size/XS, lgtm

#12090 Make sure run id is unique - backport to release 4.17
  ocs_ci/utility/framework/initialization.py
Labels: team/ecosystem, size/XS, lgtm, cherry-pick

#12087 nodeplugin pods on compute nodes only
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Needs Testing, team/ecosystem, size/S, lgtm

#11990 Delete thanos bucket created for ACM observability during cluster teardown
  tests/conftest.py
Labels: Verified, size/S, lgtm

#12103 Use separate fio files and add sync after I/O in test test_pvc_expansion_when_full
  tests/functional/pv/pvc_resize/test_pvc_expansion_when_full.py
Labels: Verified, size/S, Squad/Green, lgtm

#12107 Remove cephblockpoolradosnamespaces before cephblockpool
  tests/conftest.py
Labels: High Priority, Verified, size/S, lgtm

#12108 Add additional check on Progression status of Discovered CephFS
  ocs_ci/helpers/dr_helpers.py
Labels: Verified, size/XS, DR, Squad/Turquoise

#12120 Skipping logging deployment/tests on 4.19 and above using old stack(EFK)
  tests/functional/workloads/ocp/logging/test_openshift-logging.py
Labels: size/XS, lgtm

#11932 Fix test test_max_unavaialable_rbd for issue 11908
  tests/functional/upgrade/test_configuration.py
Labels: Verified, size/S, lgtm

#12117 Update fixture name dc_pod_factory to deployment_pod_factory in tests
  tests/conftest.py
  tests/functional/monitoring/prometheus/alerts/test_alert_mds_cache_high_usage.py
  tests/functional/monitoring/prometheus/alerts/test_alert_mds_cpu_high_usage.py
  tests/functional/pv/pv_services/test_cephfs_pvc_with_chunk_size.py
  tests/functional/pv/pv_services/test_run_io_multiple_pods.py
  tests/functional/pv/pv_services/test_rwo_pvc_fencing_unfencing.py
  tests/functional/z_cluster/nodes/test_worker_nodes_network_failures.py
Labels: High Priority, Verified, size/S, Squad/Green, Squad/Brown, Squad/Blue, lgtm

#12106 Adds more test coverage for CORS feature
  tests/functional/object/mcg/test_cors_config_elements.py
Labels: Verified, size/XL, MCG, lgtm

#12048 Adds happy path testing for RGW ReadAffinity feature
  tests/functional/object/rgw/test_rgw_read_affinity.py
Labels: Verified, size/L, RGW, Squad/Red, lgtm

#12073 RDR chnages for 4.19
  ocs_ci/deployment/deployment.py
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocs-deployment/multicluster/service_exporter.yaml
Labels: Verified, team/ecosystem, size/L, lgtm, DR, Squad/Turquoise

#12042 Refactor determination of storageclass for deployments
  ocs_ci/deployment/aws.py
  ocs_ci/deployment/azure.py
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/gcp.py
  ocs_ci/deployment/helpers/storage_class.py
  ocs_ci/deployment/ibmcloud.py
  ocs_ci/deployment/rhv.py
  ocs_ci/deployment/tests/test_cloud.py
  ocs_ci/deployment/vmware.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/L, lgtm

#11682 Recipe with checkhooks necessary configs
  conf/ocsci/dr_workload.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/dr/dr_workload.py
  ocs_ci/templates/DR/drpc_with_recipe.yaml
  ocs_ci/templates/DR/recipe_with_checkhooks.yaml
  ocs_ci/templates/DR/secret.yaml
  tests/conftest.py
  tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate_discovered_apps.py
Labels: Verified, size/L, lgtm, DR

#12131 skip check for storageclient pod
  ocs_ci/ocs/resources/pod.py
  tests/functional/z_cluster/nodes/test_toleration.py
Labels: size/XS, lgtm

#12115 remove oc in exec_oc_cmd
  ocs_ci/deployment/ibm.py
  ocs_ci/utility/utils.py
Labels: team/ecosystem, size/XS, lgtm

#11204 Pause the IO in Background for the resize osd test
  tests/functional/z_cluster/cluster_expansion/test_resize_osd.py
Labels: size/S, Squad/Brown, lgtm

#12136 Fix test_noobaa_db_cleartext_postgres_password.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm

#12069 Skipping ibmcloud testcase for machine not found error: v4.17
  tests/functional/z_cluster/nodes/test_node_replacement_proactive.py
Labels: size/XS, lgtm

#12110 Fix calcualtion of check_storage_size_is_reflected_in_ui
  ocs_ci/helpers/osd_resize.py
  ocs_ci/ocs/cluster.py
Labels: size/S, lgtm

#12126 Adds upgrade scenarios for readAffinity feature
  tests/functional/object/rgw/test_rgw_read_affinity.py
Labels: Verified, size/XS, RGW, Squad/Red, lgtm

#12098 Update noobaa-db queries at test_unidirectional_bucketclass_replication and add jira decorator for bug
  tests/functional/object/mcg/test_bucket_replication.py
Labels: Verified, size/M, MCG, Squad/Red, lgtm

#12141 Fix `test_verify_noobaa_db_service`
  tests/functional/object/mcg/test_verify_noobaa_status.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#12140 Update test_object_expiration_in_minutes: use expiration rules without ExpiredObjectDeleteMarker
  tests/functional/object/mcg/test_object_expiration.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm

#12160 Storageclass map for baremetal and HCI baremetal
  ocs_ci/deployment/helpers/storage_class.py
Labels: team/ecosystem, size/XS, lgtm

#11624 Added code for continuous io on VM
  ocs_ci/helpers/cnv_helpers.py
  tests/conftest.py
  tests/functional/workloads/cnv/test_vm_lifecycle_and_io.py
Labels: Verified, team/e2e, size/L, Squad/Magenta, lgtm

#12170 add time to deploy mce on cluster 4.18
  ocs_ci/deployment/mce.py
Labels: Verified, size/XS, lgtm

#12084 Update the noobaa_db_backup_and_recovery_locally fixture to use the new noobaa-db HA solution
  ocs_ci/ocs/constants.py
  tests/cross_functional/conftest.py
  tests/cross_functional/kcs/test_noobaa_db_backup_and_recovery.py
Labels: Verified, size/L, MCG, Squad/Magenta, Squad/Red, lgtm

#12173 correct storage client name to customer used one
  ocs_ci/deployment/hosted_cluster.py
Labels: size/XS, lgtm

#12174 Collect logs on success fix
  ocs_ci/deployment/deployment.py
Labels: size/XS, lgtm

#12177 [release-4.18] Delete thanos bucket created for ACM observability during cluster teardown
  tests/conftest.py
Labels: size/S, lgtm, DR, Squad/Turquoise

#12130 Use delete_all_objects_in_batches wherever we used bucket.objects.all.delete()
  ocs_ci/cleanup/aws/cleanup.py
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/resources/cloud_manager.py
  ocs_ci/ocs/resources/objectbucket.py
  ocs_ci/ocs/resources/s3_batch_deleter.py
  tests/libtest/test_s3_batch_deleter.py
Labels: size/L, lgtm

#12180 Pin oslo.utils version
  setup.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#12156 Use active ACM cluster context for the test test_acm_import
  ocs_ci/framework/__init__.py
  ocs_ci/ocs/acm/acm.py
  tests/functional/deployment/test_acm.py
Labels: Verified, size/S, lgtm, DR

#12181 [release-4.16] Delete thanos bucket created for ACM observability during cluster teardown
  tests/conftest.py
Labels: size/S, lgtm, DR, Squad/Turquoise

#12185 Use provider cluster_namespace if provider kubeconfig is used for tools pod
  ocs_ci/ocs/resources/pod.py
Labels: size/S, lgtm, provider-client

#12151 Do not skip obc UI test
  ocs_ci/ocs/ui/views.py
  tests/functional/object/mcg/ui/test_mcg_ui.py
Labels: Verified, size/XS, lgtm

#12040 Basic check for missing storage system and running pods
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/storage_cluster.py
  tests/functional/deployment/test_operator.py
  tests/functional/z_cluster/test_storagesystem.py
Labels: Verified, size/L, lgtm

#12171 Storage class map update for IBM Power Deployment
  ocs_ci/deployment/helpers/storage_class.py
Labels: size/XS, lgtm

#10886 Updated local storage template to accept different version
  ocs_ci/templates/ocs-deployment/local-storage-optional-operators.yaml
Labels: Verified, size/XS, lgtm

#12091 Fix `test_versioning_parallel_ops`
  tests/functional/object/mcg/test_object_versioning.py
Labels: Verified, size/M, MCG, Squad/Red, lgtm

#12198 Fix MCG only deplyment KeyError `status`
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/XS, lgtm

#12220 Add runs_on_provider decorator in the tests TestSecretsAndSecurityContext
  tests/functional/pv/pv_encryption/test_secrets_on_pods.py
Labels: Verified, size/XS, lgtm, provider-client

#12209 Increasing bucket deletion timeout - fix to issue #11846
  ocs_ci/ocs/resources/objectbucket.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm, Automation Backlog

#11839 fix get_ceph_tools_pod to run with provider context
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/utils.py
Labels: Verified, size/L, lgtm

#11922 [GSS]Close loop BZ:2260550 Automation
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/node.py
  tests/functional/object/mcg/test_standalone_noobaa_pod_node_affinity.py
Labels: Verified, team/e2e, size/L, Customer defects, lgtm

#12243 Revert "fix get_ceph_tools_pod to run with provider context (#11839)"
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/utils.py
Labels: size/L, lgtm

#12212 increase ocp upgrade timeout for arbiter
  ocs_ci/ocs/ocs_upgrade.py
  tests/functional/upgrade/test_upgrade_ocp.py
Labels: Verified, team/ecosystem, size/S, lgtm

#12214 [release-4.18] Fix several tier1 tests for provider mode
  ocs_ci/ocs/resources/mcg.py
  tests/functional/monitoring/prometheus/metrics/test_mcg_hpa.py
  tests/functional/pv/pv_services/test_change_reclaim_policy_of_pv.py
  tests/functional/upgrade/test_configuration.py
Labels: size/L, lgtm, provider-client

#12264 Skip test_ceph_recovery
  tests/functional/pv/pv_services/test_ceph_capacity_recovery.py
Labels: size/XS, lgtm

#11000 [Stretch cluster] Support zone unaware apps for zone shutdown tests
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/stretchcluster.py
  ocs_ci/templates/CSI/addons/network-fence-class.yaml
  ocs_ci/templates/CSI/addons/network-fence-rbd.yaml
  ocs_ci/templates/workloads/logwriter/cephfs.logreader.yaml
  tests/conftest.py
  tests/functional/disaster-recovery/sc_arbiter/test_zone_unaware_app.py
Labels: Verified, team/e2e, size/XL, lgtm

#12228 continue to destroy cluster incase of failed in fetching vms
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/S, lgtm

#12268 Fix multus configuration
  conf/deployment/vsphere/upi_1az_rhcos_multus_public_vsan_3m_3w.yaml
Labels: size/XS, lgtm

#12279 changed oc rsync to oc cp command
  tests/functional/workloads/test_data_consistency.py
Labels: Verified, size/XS, Squad/Magenta, lgtm

#12195 Added new fixture as workaround[test_ephemeral_pod_creation]
  tests/functional/pod_and_daemons/test_ephemeral_pod.py
Labels: Verified, size/XS, lgtm

#12273 delete IBM cos objects in batches
  ocs_ci/utility/ibmcloud.py
Labels: Verified, team/ecosystem, size/M, lgtm

#11199 CNV vm clone with PVC expansion ops
  ocs_ci/helpers/cnv_helpers.py
  tests/conftest.py
  tests/functional/workloads/cnv/test_vm_snapshot_cloning_ops.py
Labels: Verified, team/e2e, size/L, lgtm

#12223 Add the klusterlet-config annotation in ManagedCluster CR to import MCE cluster
  ocs_ci/ocs/acm/acm.py
Labels: Verified, size/M, lgtm, provider-client
