Repository red-hat-storage/ocs-ci, pull requests merged in 2025-02, with the labels that each got.

#11267 Fix IBM Cloud upgrade
  ocs_ci/ocs/ocs_upgrade.py
Labels: size/XS, lgtm

#10943 [GSS] Test if MCG secrets are used in env variables and bucketclass can be modified
  ocs_ci/deployment/helpers/mcg_helpers.py
  tests/conftest.py
  tests/functional/object/mcg/test_bucketclass.py
  tests/functional/object/mcg/test_noobaa_secret.py
Labels: Verified, team/e2e, size/L, MCG, Customer defects, Squad/Red, lgtm

#11219 Fix memory leak in Get bucket replication test
  tests/functional/object/mcg/test_bucket_replication.py
Labels: size/S, lgtm

#11284 Try to get vault path token in deploy function
  ocs_ci/utility/kms.py
Labels: Verified, size/XS, lgtm

#11161 Improvements for MG collections
  conf/README.md
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/utils.py
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: size/L, lgtm

#11269 Skipping test if KMS configured other than vault
  tests/functional/pv/pv_encryption/test_pv_keyrotation.py
Labels: size/XS, lgtm

#11275 Fix config path for upgrade strategy
  ocs_ci/ocs/ocs_upgrade.py
Labels: size/XS, upgrade, lgtm

#11303 Stabilize and adjust `test_bucket_notifications`
  ocs_ci/ocs/amq.py
  ocs_ci/ocs/resources/bucket_notifications_manager.py
  ocs_ci/ocs/resources/mcg.py
  tests/functional/object/mcg/test_bucket_notifications.py
Labels: Verified, size/L, MCG, Squad/Red, lgtm

#11171 Cherry-pick to release 4.16 multus for Vsphere (#10906)
  conf/deployment/vsphere/upi_1az_rhcos_multus_vsan_3m_3w.yaml
  ocs_ci/deployment/vmware.py
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocs-deployment/node_network_configuration_policy.yaml
  ocs_ci/utility/vsphere.py
Labels: Verified, size/L, lgtm

#11170 Cherry-pick to release4.17 multus for Vsphere (#10906)
  conf/deployment/vsphere/upi_1az_rhcos_multus_vsan_3m_3w.yaml
  ocs_ci/deployment/vmware.py
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocs-deployment/node_network_configuration_policy.yaml
  ocs_ci/utility/vsphere.py
Labels: Verified, size/L, lgtm

#11096 Create new test for create multiple device classes
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/device_classes.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/pv.py
  ocs_ci/ocs/resources/pvc.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/templates/multiple-deviceclasses/deviceclass-cephblockpool.yaml
  ocs_ci/templates/multiple-deviceclasses/deviceclass-storageclass.yaml
  ocs_ci/templates/multiple-deviceclasses/storage-device-set.yaml
  tests/functional/z_cluster/cluster_expansion/test_create_multiple_device_classes.py
Labels: Verified, size/XL, new feature, lgtm

#11295 Clear crash warnings and osd removal leftovers in the teardown of the node replacement test
  tests/functional/z_cluster/nodes/test_node_replacement_proactive.py
Labels: Verified, size/S, Squad/Brown, lgtm

#11304 baremetal AI deployment: support uefi boot mode
  ocs_ci/deployment/baremetal.py
Labels: Verified, team/ecosystem, size/S, lgtm

#11300 Delete leftover dns records when destroying ibmcloud clusters
  ocs_ci/deployment/ibmcloud.py
  ocs_ci/utility/ibmcloud.py
Labels: Verified, team/ecosystem, size/M, lgtm

#11314 [release-4.16] Delete leftover dns records when destroying ibmcloud clusters
  ocs_ci/deployment/ibmcloud.py
  ocs_ci/utility/ibmcloud.py
Labels: size/M, lgtm, cherry-pick

#11315 [release-4.15] Delete leftover dns records when destroying ibmcloud clusters
  ocs_ci/deployment/ibmcloud.py
  ocs_ci/utility/ibmcloud.py
Labels: size/M, lgtm, cherry-pick

#11316 [release-4.14] Delete leftover dns records when destroying ibmcloud clusters
  ocs_ci/deployment/ibmcloud.py
  ocs_ci/utility/ibmcloud.py
Labels: size/M, lgtm, cherry-pick

#11310 Skipping test case with kubeadmin password for IBM Cloud
  tests/conftest.py
  tests/functional/z_cluster/cluster_expansion/test_resize_osd.py
Labels: size/XS, lgtm

#11343 Added ttl value to the vault token generation command
  ocs_ci/utility/kms.py
Labels: Verified, size/XS, lgtm

#11296 Increasing timeout of re-balance with IBM Cloud managed Cluster
  ocs_ci/ocs/cluster.py
Labels: size/XS, lgtm

#11278 Fixed intransit encryption test case
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/S, lgtm

#11329 `BucketLoggingManager::wait_for_logs_pvc_mount_status` - Increase the timeout from 2 minutes to 5
  ocs_ci/ocs/resources/bucket_logging_manager.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#11321 Stabilize add-env-var MCG fixtures
  tests/conftest.py
Labels: Verified, size/S, MCG, Squad/Magenta, Squad/Red, lgtm

#11324 Ignore rook-ceph-osd-key-rotation leftovers
  ocs_ci/ocs/constants.py
  ocs_ci/utility/environment_check.py
Labels: Verified, size/XS, Squad/Green, Squad/Red, lgtm

#11289 Bumps ACM and Submariner version for OCP 4.16
  conf/ocsci/submariner_downstream.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.16-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.16-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.16-ga-minus1-config.yaml
Labels: Verified, size/S, lgtm, DR, Squad/Turquoise

#11359 Server doesn't have a resource type "Machine" issue fixed in IBM cloud managed platform
  tests/functional/z_cluster/nodes/test_node_replacement_proactive.py
Labels: size/XS, lgtm

#11292 OCP 4.19 RHCOS template
  ocs_ci/framework/conf/ocp_version/ocp-4.19-config.yaml
Labels: Verified, team/ecosystem, size/XS, lgtm

#11366 Fixed index error in the code
  tests/functional/odf-cli/test_pvc_stale_volume_cleanup_cli.py
Labels: Verified, size/XS, lgtm

#11360 Added rook-ceph-osd-encryption-key name in EXPECTED_NAMES list
  tests/functional/pv/pv_encryption/test_secrets_on_pods.py
Labels: Verified, size/S, lgtm

#11358 string comparison check reformatted
  tests/functional/encryption/test_encryption_configuration_dashboard.py
Labels: Verified, size/XS, lgtm

#11346 Fix the functions "check_taint_on_nodes" and "untaint_nodes"
  ocs_ci/ocs/node.py
Labels: Verified, size/M, Squad/Brown, lgtm

#11149 VM hot plugging and unplugging
  ocs_ci/helpers/cnv_helpers.py
  ocs_ci/ocs/cnv/virtual_machine.py
  ocs_ci/templates/cnv-vm-workload/vm.yaml
  tests/functional/workloads/cnv/test_vm_hotplug_unplug.py
  tests/functional/workloads/cnv/test_vm_single_disk_hot_plugging_unplugging.py
Labels: team/e2e, size/L, lgtm

#11388 fix getting host names from ceph
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/node.py
Labels: Verified, team/ecosystem, size/M, lgtm

#11368 update locators test_validate_topology_configuration
  ocs_ci/ocs/ui/page_objects/odf_topology_tab.py
  ocs_ci/ocs/ui/views.py
Labels: Verified, TestCase failing, size/M, lgtm

#11299 Remove catalogImageTemplate annotation from IBM Operator CatalogSource
  ocs_ci/templates/fusion/catalog-source.yaml
Labels: Verified, team/ecosystem, size/XS, lgtm

#11305 Update observability Configmap for new Volsync namespace
  ocs_ci/templates/DR/observability-metrics-configmap.yaml
Labels: Verified, lgtm, DR

#11362 Remove Unused metric
  ocs_ci/templates/DR/observability-metrics-configmap.yaml
Labels: lgtm, DR

#11238 [RDR] "Inconsistent data on target cluster" warning alert on Failover/Relocate modal due to Sync delays
  ocs_ci/helpers/dr_helpers_ui.py
  ocs_ci/ocs/acm/acm.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/acm_ui.py
  ocs_ci/ocs/ui/views.py
  tests/functional/disaster-recovery/regional-dr/test_warning_and_alerting.py
Labels: Verified, size/XL, ui_automation, lgtm, Squad/Turquoise

#11322 Simplify `bucket_utils.py::upload_obj_versions`
  ocs_ci/ocs/bucket_utils.py
  tests/functional/object/mcg/test_bucket_replication_with_versioning.py
Labels: Verified, size/M, MCG, Squad/Red, lgtm

#11283 Adding a new test case for bucketclass NSS creation with Cache via CLI
  ocs_ci/ocs/resources/mcg.py
  tests/functional/object/mcg/test_namespace_crd.py
Labels: Verified, size/M, MCG, Squad/Red, lgtm, approved

#11416 Fixed storagecluster status check code
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, size/XS, lgtm

#11327 cluster load: Refresh prometheus_api connection in case of connection error
  ocs_ci/ocs/cluster_load.py
Labels: size/S, lgtm

#11421 Handle cluster load problems causing stuck execution
  ocs_ci/ocs/cluster_load.py
  tests/conftest.py
Labels: size/M, lgtm, cherry-pick

#11422 Handle cluster load problems causing stuck execution
  ocs_ci/ocs/cluster_load.py
  tests/conftest.py
Labels: size/M, lgtm, cherry-pick

#11423 [release-4.16] cluster load: Refresh prometheus_api connection in case of connection error
  ocs_ci/ocs/cluster_load.py
Labels: size/S, lgtm

#11389 Skip RPM collection for development mode
  tests/conftest.py
Labels: team/ecosystem, size/XS, lgtm

#11363 Skipping test case with kubeadmin password for IBM Cloud - 4.17
  tests/functional/z_cluster/cluster_expansion/test_resize_osd.py
Labels: size/XS, lgtm

#11386 Adds script to validate OBC quota update functionality using mcg cli
  tests/functional/object/mcg/test_obc_quota_update_using_cli.py
Labels: Verified, size/M, MCG, Customer defects, Squad/Red, lgtm

#11381 `test_bucket_notifications` - update the get-bucket-notification command
  ocs_ci/ocs/resources/bucket_notifications_manager.py
  tests/functional/object/mcg/test_bucket_notifications.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm

#11340 `test_object_actions` - double the sleep from 60 seconds to 120
  tests/functional/object/mcg/test_bucket_policy.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#11216 Add `test_bidirectional_deletion_sync` to `TestLogBasedBucketReplication`
  ocs_ci/ocs/resources/mockup_bucket_logger.py
  tests/functional/object/mcg/test_log_based_bucket_replication.py
Labels: Verified, size/L, MCG, Squad/Red, lgtm

#11426 Handle cluster load problems causing stuck execution
  ocs_ci/ocs/cluster_load.py
  tests/conftest.py
Labels: size/M, lgtm, cherry-pick

#11437 Handle cluster load problems causing stuck execution
  ocs_ci/ocs/cluster_load.py
  tests/conftest.py
Labels: size/M, lgtm

#11414 Update ceph rgw metrics
  ocs_ci/ocs/metrics.py
Labels: Verified, team/e2e, size/S, Squad/Magenta, lgtm

#11353 [DFBUGS-368] Deprecate test_alert_mds_cache_high_usage.py till further changes.
  tests/functional/monitoring/prometheus/alerts/test_alert_mds_cache_high_usage.py
Labels: bug, team/e2e, size/S, lgtm

#11419 Fix test_project_admin_obcs_access test
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/page_objects/page_navigator.py
  ocs_ci/ocs/ui/views.py
  tests/functional/ui/test_non_admin_user.py
Labels: Verified, size/S, lgtm, Squad/Black

#11449 Revert "cluster load: Refresh prometheus_api connection in case of connection error"
  ocs_ci/ocs/cluster_load.py
Labels: size/S, lgtm

#11458 [release-4.17] exclude NOOBAA_PSQL_12_IMAGE for image verification after upgrade
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/utils.py
Labels: team/ecosystem, size/M, lgtm

#11457 [release-4.16] exclude NOOBAA_PSQL_12_IMAGE for image verification after upgrade
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/utils.py
Labels: team/ecosystem, size/M, lgtm

#11474 add @retry to Assisted Installer API requests
  ocs_ci/utility/assisted_installer.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#11470 Ignore detect-version pods in rpm version collection
  ocs_ci/ocs/utils.py
Labels: size/XS, lgtm

#11356 Stabilize MDSCPUUsageHigh alert test case
  tests/functional/monitoring/prometheus/alerts/test_alert_mds_cpu_high_usage.py
Labels: enhancement, size/S, lgtm

#11038 Added mce.py file for mce installation related methods
  conf/README.md
  ocs_ci/deployment/hosted_cluster.py
  ocs_ci/deployment/mce.py
  ocs_ci/deployment/provider_client/storage_client_deployment.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/mce-deployment/image-override.json
  ocs_ci/templates/mce-deployment/mce_catsrc.yaml
  ocs_ci/templates/mce-deployment/mce_namespace.yaml
  ocs_ci/templates/mce-deployment/mce_operator.yaml
  ocs_ci/templates/mce-deployment/mce_subscription.yaml
  tests/libtest/test_provider_create_hosted_cluster.py
Labels: Verified, size/L, lgtm, provider-client

#11484 Fix in detect-version pods rpm collection
  ocs_ci/ocs/utils.py
Labels: size/XS, lgtm

#11443 [4.18]TestErrorMessageImprovements: fix locator and logic
  ocs_ci/ocs/ui/page_objects/bucket_class_tab.py
  ocs_ci/ocs/ui/page_objects/data_foundation_tabs_common.py
  ocs_ci/ocs/ui/page_objects/namespace_store_tab.py
  ocs_ci/ocs/ui/page_objects/storage_system_tab.py
  ocs_ci/ocs/ui/views.py
  tests/functional/ui/test_error_improvements.py
Labels: Verified, size/S, lgtm

#11439 requested_cap_breakdown: replace busybox with ubi8 for disconected clusters
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/odf_topology.py
  ocs_ci/ocs/ui/page_objects/odf_topology_tab.py
  ocs_ci/ocs/ui/workload_ui.py
  ocs_ci/templates/app-deployments/ubi8-simple.yaml
  tests/cross_functional/ui/test_odf_topology.py
  tests/functional/ui/test_capacity_breakdown_ui.py
Labels: Verified, TestCase failing, size/L, lgtm

#11442 Delete OIDC provider during teardown
  ocs_ci/utility/aws.py
Labels: Verified, team/ecosystem, size/S, lgtm

#11331 exclude-metrics-dependant-tests-for-external-mode
  tests/functional/monitoring/prometheus/metrics/test_monitoring_defaults.py
Labels: Verified, TestCase failing, size/XS, lgtm

#11325 test_monitoring_shows_mon_down add jira decorator
  tests/functional/monitoring/prometheus/metrics/test_monitoring_negative.py
Labels: Verified, TestCase failing, size/XS, lgtm

#11319 test_ceph_osd_slow_ops_alert minimize osd complient time
  tests/functional/monitoring/prometheus/alerts/test_ceph.py
Labels: Verified, size/XS, lgtm

#11475 Deprecate test_object_bucket_size
  tests/functional/object/rgw/test_object_bucket_size.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#11473 test_nsfs.py - add the Jira label for DFBUGS-153
  tests/functional/object/mcg/test_nsfs.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#11260 [4.18] MCG Bucket Notifications - add advanced tests
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/resources/bucket_notifications_manager.py
  tests/conftest.py
  tests/functional/object/mcg/test_bucket_notifications.py
Labels: Verified, size/L, MCG, Squad/Red, lgtm

#11229 Increase bucket creation timeout for test_recovery_from_volume_deletion
  tests/functional/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/XS, lgtm

#11498 Take LSO unreleased image dynamically
  ocs_ci/deployment/helpers/lso_helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/ocs-deployment/local-storage-optional-operators.yaml
Labels: size/XS, lgtm

#11502 get buckets and their regions for IBM cloud
  ocs_ci/utility/ibmcloud.py
Labels: team/ecosystem, size/M, lgtm

#11504 adding regions in constants
  ocs_ci/ocs/constants.py
Labels: team/ecosystem, size/XS, lgtm

#11500 Adding OCP 4.18-ga files
  ocs_ci/framework/conf/ocp_version/ocp-4.18-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.18-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.18-ga-upgrade.yaml
Labels: Verified, size/M, lgtm

#11469 Add re-tries on pod toleration check for test_non_ocs_taint_and_tolerations post re-spin
  tests/functional/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#11505 Login back to origin region in IBM Cloud if it was not changed
  ocs_ci/deployment/ibmcloud.py
Labels: Verified, size/XS, lgtm

#11501 Add timeout to cluster load join thread
  ocs_ci/ocs/cluster_load.py
Labels: Verified, size/XS, lgtm

#11515 Ensure that get_current_test_marks doesn't return non-relevant marks for utility tests such as test_failure_propagator
  ocs_ci/framework/pytest_customization/marks.py
  pytest.ini
  tests/conftest.py
  tests/test_failure_propagator.py
Labels: enhancement, Verified, size/S, lgtm

#11516 Remove unneeded catsource check
  ocs_ci/deployment/provider_client/storage_client_deployment.py
Labels: Verified, size/XS, lgtm, provider-client

#11407 Fixed keyrotaion tests for KV2 version
  ocs_ci/helpers/keyrotation_helper.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/utils.py
  ocs_ci/utility/kms.py
  tests/functional/encryption/test_encryption_keyrotation.py
Labels: Verified, size/L, lgtm

#11512 Changing order of parameters of SC fixture
  tests/conftest.py
Labels: size/S, lgtm

#11494 skip the test
  tests/functional/pv/pv_services/test_pvc_evict_ceph_clients.py
Labels: size/XS, Squad/Green, lgtm
