Repository red-hat-storage/ocs-ci, pull requests merged in 2025-03, with the labels that each got.

#11522 Fix ceph health
  ocs_ci/ocs/exceptions.py
  ocs_ci/utility/utils.py
  tests/conftest.py
Labels: Verified, size/L, lgtm

#11491 graceful shutdown VM's in vSphere
  ocs_ci/utility/vsphere.py
Labels: team/ecosystem, size/S, lgtm

#11551 move RHEL worker nodes deployment configs to deprecated directory
  conf/deprecated/aws_upi_rhel7_workers.yaml
  conf/deprecated/aws_upi_rhel8_workers.yaml
  conf/deprecated/deployment/aws/upi_1az_rhel7_3m_3w.yaml
  conf/deprecated/deployment/aws/upi_1az_rhel_lso_3m_3w.yaml
  conf/deprecated/deployment/aws/upi_3az_rhel8_3m_3w.yaml
  conf/deprecated/deployment/aws/upi_3az_rhel_3m_3w.yaml
  conf/deprecated/deployment/aws/upi_3az_rhel_lso_3m_3w.yaml
  conf/deprecated/deployment/baremetal/upi_1az_rhel_nvme_intel_3m_3w.yaml
  conf/deprecated/deployment/vsphere/upi_1az_rhel_multus_vmfs_3m_3w.yaml
  conf/deprecated/deployment/vsphere/upi_1az_rhel_multus_vsan_3m_3w.yaml
  conf/deprecated/deployment/vsphere/upi_1az_rhel_vmfs_3m_3w.yaml
  conf/deprecated/deployment/vsphere/upi_1az_rhel_vmfs_lso_directpath_3m_3w.yaml
  conf/deprecated/deployment/vsphere/upi_1az_rhel_vmfs_lso_rdm_3m_3w.yaml
  conf/deprecated/deployment/vsphere/upi_1az_rhel_vmfs_lso_vmdk_3m_3w.yaml
  conf/deprecated/deployment/vsphere/upi_1az_rhel_vsan_3m_3w.yaml
  conf/deprecated/deployment/vsphere/upi_1az_rhel_vsan_lso_directpath_3m_3w.yaml
  conf/deprecated/deployment/vsphere/upi_1az_rhel_vsan_lso_rdm_3m_3w.yaml
  conf/deprecated/deployment/vsphere/upi_1az_rhel_vsan_lso_vmdk_3m_3w.yaml
Labels: team/ecosystem, size/XS, lgtm

#11438 [4.18] Test bucket replication with versioning - minor refactor to existing test + advanced tests
  ocs_ci/ocs/bucket_utils.py
  tests/functional/object/mcg/test_bucket_replication_with_versioning.py
Labels: Verified, size/L, MCG, Squad/Red, lgtm

#11379 Add rosa-ocp-version endpoint
  docs/usage.md
  ocs_ci/utility/rosa.py
  ocs_ci/utility/version.py
  setup.py
Labels: Verified, size/L, lgtm

#11539 Adding a new test case for NSS creation with Multi bucketclass type via CLI
  ocs_ci/ocs/resources/mcg.py
  tests/functional/object/mcg/test_namespace_crd.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm

#11487 Fix getting the external mode RBD storageclass when using rbd namespace
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/helpers/external_cluster_helpers.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/M, lgtm

#11558 Added in-transit encryption enable-disable operation after adding worker node to the cluster.
  tests/functional/z_cluster/cluster_expansion/test_node_expansion.py
Labels: Verified, size/M, lgtm

#11555 Change update strategy after upgrade started
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, size/S, upgrade, lgtm

#11556 Add vault v2 3m 3w 3i config file
  conf/deployment/aws/ipi_3az_rhcos_3m_3w_3i_vault_v2.yaml
Labels: Verified, size/M, lgtm

#11580 Remove jira marker from test_detach_attach_worker_volume to allow it to run
  tests/functional/z_cluster/nodes/test_disk_failures.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#11581 [ODF 4.15] Add re-tries on pod toleration check for test_non_ocs_taint_and_tolerations post re-spin
  tests/functional/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#11585 Increase bucket creation timeout for test_recovery_from_volume_deletion_cli_tool
  ocs_ci/ocs/resources/objectbucket.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#11523 add-hyperconverged-into-dependencies
  conf/README.md
  conf/examples/provider_mode_ibm_cloud_baremetal_kubevirt_clients.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/helpers/hypershift_base.py
  ocs_ci/deployment/hosted_cluster.py
  ocs_ci/deployment/hyperconverged.py
  ocs_ci/deployment/mce.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/exceptions.py
  ocs_ci/ocs/resources/deployment.py
  ocs_ci/templates/hyperconverged-deployment/hyperconverged-catsrc.yaml
  ocs_ci/templates/hyperconverged-deployment/hyperconverged.yaml
  ocs_ci/templates/hyperconverged-deployment/hyperconverged_namespace.yaml
  ocs_ci/templates/hyperconverged-deployment/hyperconverged_operator_group.yaml
  ocs_ci/templates/hyperconverged-deployment/hyperconverged_subscription.yaml
  ocs_ci/templates/mce-deployment/mce_catsrc.yaml
  ocs_ci/templates/mce-deployment/mce_subscription.yaml
  ocs_ci/utility/managedservice.py
  ocs_ci/utility/utils.py
  tests/libtest/test_provider_create_hosted_cluster.py
Labels: Verified, size/XL, lgtm

#11492 Stretch cluster: Minor fixes and skip tests with bugzilla
  ocs_ci/ocs/resources/stretchcluster.py
  tests/functional/disaster-recovery/sc_arbiter/test_add_capacity.py
  tests/functional/disaster-recovery/sc_arbiter/test_device_replacement.py
  tests/functional/disaster-recovery/sc_arbiter/test_rgw_in_stretch.py
  tests/functional/disaster-recovery/sc_arbiter/test_zone_shutdown_and_crash.py
Labels: Verified, team/e2e, size/M, lgtm

#11601 Increase timeout when creating PVC from snapshot in test test_pvc_snapshot
  tests/functional/pv/pvc_snapshot/test_pvc_snapshot.py
Labels: Verified, size/XS, Squad/Green, lgtm

#11603 Adding 4 new test cases for aws/azure/ibmcos and gcp and a support for nss creation for gcp platform
  ocs_ci/ocs/resources/namespacestore.py
  tests/functional/object/mcg/test_namespace_crd.py
Labels: Verified, size/M, MCG, Squad/Red, lgtm

#11589 Ceph full thresholds upgrade combinations
  ocs_ci/ocs/ocs_upgrade.py
  tests/functional/z_cluster/test_storagecluster_ceph_full_thresholds_params.py
Labels: Verified, size/L, lgtm

#11622 A fix to test_namespace_bucket_creation_crd[RGW-CLI-Cache] failure
  ocs_ci/ocs/resources/mcg.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#11609 Download the external mode script from the configmap by default
  ocs_ci/deployment/helpers/external_cluster_helpers.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#11617 Increased retries to validate ceph health metrics is updated on prometheus pod during mgr running node reboot.
  tests/functional/workloads/ocp/monitoring/test_monitoring_on_negative_scenarios.py
Labels: size/XS, lgtm

#11497 Adding kms policy name for same kms encryption keys
  ocs_ci/utility/kms.py
Labels: Verified, size/M, lgtm

#11631 Don't reload nmstate subscription
  ocs_ci/deployment/nmstate.py
Labels: size/XS, lgtm

#11629 fix retry for validate_pdb_creation function
  ocs_ci/ocs/cluster.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#11403 Stabilize object expiration system test
  tests/cross_functional/conftest.py
  tests/cross_functional/system_test/test_object_expiration_system.py
Labels: Verified, team/e2e, size/XS, Squad/Magenta, lgtm

#11586 ROSA HCP Deployment, fix parametrization issue
  ocs_ci/deployment/deployment.py
  ocs_ci/utility/rosa.py
Labels: Verified, size/S, lgtm

#11610 add workaround for issues with uefi boot order
  conf/README.md
  ocs_ci/deployment/baremetal.py
  ocs_ci/utility/baremetal.py
Labels: Verified, team/ecosystem, size/L, lgtm

#11554 update docs/usage.md documentation
  docs/usage.md
Labels: team/ecosystem, size/L, lgtm

#11440 storage classes check for provider cluster
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Needs Testing, team/ecosystem, size/XS, lgtm

#11615 Skip test cases which require tool box in MCG Only deployment
  tests/cross_functional/scale/upgrade/test_upgrade_with_scaled_rgw_obc.py
  tests/functional/monitoring/workload/test_workload_with_distruptions.py
  tests/functional/pod_and_daemons/test_mgr_pods.py
  tests/functional/storageclass/test_cross_sc_clone_snap_restore.py
  tests/functional/upgrade/test_configuration.py
Labels: team/ecosystem, size/S, lgtm

#11544 Stabilize enable_bucket_notifs_on_cr
  ocs_ci/ocs/resources/bucket_notifications_manager.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm

#10925 Renamed deprecated_test_start_pre_upgrade_pod_io under Brown squad
  tests/functional/upgrade/test_resources.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#11406 Improve vrg discovered app
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/dr/dr_workload.py
  tests/functional/disaster-recovery/regional-dr/test_cnv_failover_and_relocate_discovered_apps.py
  tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate_discovered_apps.py
Labels: Verified, size/M, lgtm

#11056 Removes missed redundant tests from orange squad
  tests/cross_functional/scale/test_scale_12_OCS_worker_nodes_and_6000_PVCs.py
Labels: size/XS, Squad/Orange, lgtm

#11613 Defaulting ocs-ci to ODF 4.19
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/utility/version.py
  setup.py
Labels: team/ecosystem, size/S, lgtm

#11644 Fix issue where rosa platforms weren't considered for deploying STS on AWS
  ocs_ci/deployment/deployment.py
  ocs_ci/ocs/constants.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#11649 Increase timeout for restore pod
  tests/functional/pv/pvc_snapshot/test_pvc_snapshot.py
Labels: Needs Testing, team/ecosystem, size/XS, lgtm

#11653 Increase default noobaa pod count by 1 due to cnpg pod
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#11652 Add cnv dployment retries and increase timeouts
  ocs_ci/deployment/cnv.py
Labels: Verified, size/S, lgtm

#11658 Add OCP 4.19 upgrade config file
  ocs_ci/framework/conf/ocp_version/ocp-4.19-upgrade.yaml
Labels: size/XS, lgtm

#11672 [4.16] Backport stretch cluster code to stabilize the runs
  ocs_ci/helpers/stretchcluster_helper.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/stretchcluster.py
  tests/functional/disaster-recovery/sc_arbiter/test_netsplit.py
  tests/functional/disaster-recovery/sc_arbiter/test_zone_shutdown_and_crash.py
Labels: team/e2e, size/XL, lgtm, cherry-pick

#11673 Expose installer_path before return when custom_ocp_image used
  ocs_ci/utility/utils.py
Labels: Verified, size/XS, lgtm

#11665 use semantic version instead of parse_version
  tests/functional/upgrade/test_upgrade_ocp.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#11552 Validate the resiliency of the ODF + OpenShift Virtualization system in case of Worker node failure
  ocs_ci/ocs/cnv/virtual_machine.py
  tests/functional/workloads/cnv/test_vm_worker_node_fail.py
Labels: size/L, lgtm

#11383 Perform add storage capacity to cluster while having multiple VMs on cluster
  ocs_ci/ocs/cnv/virtual_machine.py
  tests/functional/workloads/cnv/test_vm_add_capacity.py
Labels: team/e2e, size/L, Squad/Magenta, lgtm

#11655 verification of cnpg pod
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/S, lgtm

#11681 Add W/A for IBM Cloud IPI Deployment blocker OCPBUGS-53258
  ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
Labels: Verified, size/XS, lgtm

#11684 Add 4.19 entry for disconnected required packages
  ocs_ci/ocs/constants.py
Labels: Needs Deployment Testing, team/ecosystem, size/XS, lgtm

#11654 Add kubevirt as plugin to DataProtectionApplication
  ocs_ci/templates/DR/dpa_discovered_apps.yaml
Labels: size/XS, lgtm, DR

#11686 verify controller manager for csi and odf-operator
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
Labels: Verified, team/ecosystem, size/S, lgtm

#11701 Delete bugzilla decorator
  docs/writing_tests.md
  setup.py
  tests/cross_functional/flowtest/test_base_operation_node_drain.py
  tests/cross_functional/kcs/test_mon_crash_recovery_scenario.py
  tests/cross_functional/kcs/test_monitor_recovery.py
  tests/cross_functional/kcs/test_noobaa_db_backup_and_recovery.py
  tests/cross_functional/kcs/test_noobaa_rebuild.py
  tests/cross_functional/performance/csi_tests/test_pvc_clone_performance.py
  tests/cross_functional/scale/test_pv_scale_ocs_create_delete_pvcs.py
  tests/cross_functional/ui/test_validation_ui.py
  tests/functional/disaster-recovery/sc_arbiter/test_add_capacity.py
  tests/functional/disaster-recovery/sc_arbiter/test_netsplit.py
  tests/functional/disaster-recovery/sc_arbiter/test_zone_shutdown_and_crash.py
  tests/functional/monitoring/prometheus/alerts/test_capacity.py
  tests/functional/monitoring/prometheus/alerts/test_rgw.py
  tests/functional/monitoring/prometheus/metrics/test_monitoring_defaults.py
  tests/functional/object/mcg/test_bucket_creation_deletion.py
  tests/functional/object/mcg/test_bucket_deletion.py
  tests/functional/object/mcg/test_bucket_policy.py
  tests/functional/object/mcg/test_bucket_replication.py
  tests/functional/object/mcg/test_namespace_rpc.py
  tests/functional/object/mcg/test_pv_pool.py
  tests/functional/object/mcg/ui/test_namespace_store.py
  tests/functional/object/rgw/test_host_node_failure.py
  tests/functional/pv/add_metadata_feature/test_metadata.py
  tests/functional/pv/pv_services/test_cephfs_with_mds_network_failure.py
  tests/functional/pv/pv_services/test_dynamic_pvc_accessmodes_with_reclaim_policies.py
  tests/functional/pv/pv_services/test_no_space_left.py
  tests/functional/pv/pv_services/test_pvc_evict_ceph_clients.py
  tests/functional/pv/pv_services/test_verify_rwo_using_multiple_pods.py
  tests/functional/storageclass/test_storageclass_encryption_option.py
  tests/functional/z_cluster/cluster_expansion/test_verify_ceph_csidriver_runs_on_non_ocs_nodes.py
  tests/functional/z_cluster/nodes/test_automated_recovery_from_failed_nodes_reactive_IPI.py
  tests/functional/z_cluster/nodes/test_check_pod_status_after_two_nodes_shutdown_recovery.py
  tests/functional/z_cluster/test_ceph_pg_log_dups_trim.py
  tests/functional/z_cluster/test_delete_osd_deployment.py
  tests/functional/z_cluster/test_delete_rook_ceph_mon_pod.py
  tests/functional/z_cluster/test_multiple_mon_pods_stays_on_same_node.py
Labels: size/M, lgtm

#11697 [release-4.14] use semantic version instead of parse_version
  tests/ecosystem/upgrade/test_upgrade_ocp.py
Labels: size/XS, lgtm

#11695 [release-4.16] use semantic version instead of parse_version
  tests/functional/upgrade/test_upgrade_ocp.py
Labels: size/XS, lgtm

#11694 [release-4.17] use semantic version instead of parse_version
  tests/functional/upgrade/test_upgrade_ocp.py
Labels: size/XS, lgtm

#11702 limit retry logic under threshold ( 4 hours ) for test_reboot_on_tainted_node
  tests/functional/z_cluster/nodes/test_non_ocs_taint_and_toleration.py
Labels: team/ecosystem, lgtm

#11582 Skip external KMS encryption tests if discunnect env deployed
  tests/functional/encryption/test_encryption_keyrotation.py
  tests/functional/pv/pv_encryption/test_disable_pv_keyrotation.py
Labels: size/XS, lgtm

#11013 Discovered apps with cephfs with resource label
  conf/ocsci/dr_workload.yaml
  tests/conftest.py
  tests/functional/disaster-recovery/regional-dr/test_failover_and_relocate_discovered_apps.py
Labels: Verified, size/L, lgtm, DR, Squad/Turquoise

#11692 move cnpg pod addition to after initialization of MCG Only block
  ocs_ci/ocs/ocs_upgrade.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#11233 Update the check for mirroring status and backend volume deletion based on the storageclient
  ocs_ci/framework/__init__.py
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/resources/pod.py
  tests/libtest/test_find_radosnamespace_and_subvolumegroup.py
Labels: Verified, size/L, lgtm, provider-client

#11669 skip collecting ceph external when OCP deployment failed
  ocs_ci/ocs/utils.py
Labels: team/ecosystem, size/XS, lgtm

#11691 test_node_maintenance_on_ROSA_HCP. fix extended mon termination issue
  tests/functional/z_cluster/nodes/test_nodes_maintenance.py
Labels: Verified, size/S, lgtm

#11688 update rosa cli version to latest for 419
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/XS, lgtm

#11724 Adding retry to osd_encryption_verification operation
  tests/functional/z_cluster/cluster_expansion/test_add_capacity.py
Labels: Verified, size/XS, lgtm, backport-required

#11431 VolumeSynchronizationDelay alert on the DR dashboard due to sync delays
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/ocs/ui/views.py
  tests/conftest.py
  tests/functional/disaster-recovery/regional-dr/test_negative_failover_relocate_ui.py
  tests/functional/disaster-recovery/regional-dr/test_rdr_monitoring_dashboard_ui.py
  tests/functional/disaster-recovery/regional-dr/test_warning_and_alerting.py
Labels: Verified, size/L, ui_automation, lgtm, DR, Squad/Turquoise, backlog-grooming

#10153 [GSS] Test object lists with millions of objects under single directory
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/constants.py
  tests/conftest.py
  tests/cross_functional/scale/noobaa/test_delete_objects.py
  tests/cross_functional/scale/noobaa/test_list_objects.py
Labels: Verified, team/e2e, size/L, MCG, Customer defects, Squad/Red, lgtm

#11709 increase bluestore_slow_ops_warn_threshold and bluestore_slow_ops_warn_lifetime
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/helpers/odf_deployment_helpers.py
Labels: Verified, team/ecosystem, size/M, lgtm

#10603 [system test] verify cluster-wide-encryption key at clusterfull, OSD resize, noobaa rebuild, noobaa db recovery scenarios.
  ocs_ci/helpers/e2e_helpers.py
  ocs_ci/helpers/keyrotation_helper.py
  tests/conftest.py
  tests/cross_functional/conftest.py
  tests/cross_functional/system_test/test_cluster_wide_key_rotation_systemtest.py
Labels: Verified, team/e2e, size/XL, lgtm

#11618 Iterate over client cluster contexts
  ocs_ci/framework/__init__.py
  ocs_ci/ocs/cluster.py
Labels: Verified, size/S, lgtm, provider-client

#11727 add skipif ibm cloud managed in more ui tests
  tests/functional/ui/test_alert_text.py
  tests/functional/ui/test_capacity_breakdown_ui.py
  tests/functional/z_cluster/cluster_expansion/test_resize_osd.py
Labels: Verified, size/XS, lgtm

#11726 skip-ibm-cloud-ui-tests-consumption-trend-master
  tests/functional/ui/test_odf_storage_consumption_trend.py
Labels: Verified, size/XS, lgtm

#11751 multus vsphere configuration
  conf/deployment/vsphere/upi_1az_rhcos_multus_vsan_3m_3w.yaml
Labels: size/XS, lgtm

#11752 use bluestore_slow_ops_warn only from ODF 4.19 version
  ocs_ci/deployment/deployment.py
Labels: Verified, team/ecosystem, size/M, lgtm

#11755 Bumps ACM and Submariner version for OCP 4.18 and later
  conf/ocsci/submariner_downstream.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.18-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.18-ga-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.18-ga-minus1-config.yaml
  ocs_ci/framework/conf/ocp_version/ocp-4.19-config.yaml
Labels: Verified, size/S, lgtm, DR, Squad/Turquoise

#11782 Ignore F824 in flake8
  tox.ini
Labels: size/XS, lgtm

#11742 Add an alternate way to verify if the IBM cloud BM machines are stopped
  ocs_ci/ocs/platform_nodes.py
  ocs_ci/utility/ibmcloud_bm.py
  tests/libtest/test_ibm_cloud_bm.py
Labels: Verified, size/M, lgtm, provider-client

#11789 Revert "Add W/A for IBM Cloud IPI Deployment blocker OCPBUGS-53258"
  ocs_ci/templates/ocp-deployment/install-config-ibm_cloud-ipi.yaml.j2
Labels: size/XS, lgtm

#11792 extend timeout in mce check_supported_versions
  ocs_ci/deployment/mce.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#11567 Fusion FDF decouple
  conf/ocsci/fdf_deployment.yaml
  conf/ocsci/fdf_pre_release_deployment.yaml
  conf/ocsci/fusion_deployment.yaml
  conf/ocsci/fusion_pre_release_deployment.yaml
  docs/usecases/fusion_and_fdf.md
  ocs_ci/deployment/deployment.py
  ocs_ci/deployment/fusion.py
  ocs_ci/deployment/fusion_data_foundation.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/conf/fdf_version/fdf-4.18.yaml
  ocs_ci/framework/conf/fusion_version/fusion-2.10.yaml
  ocs_ci/framework/conf/fusion_version/fusion-2.8.yaml
  ocs_ci/framework/conf/fusion_version/fusion-2.9.yaml
  ocs_ci/framework/exceptions.py
  ocs_ci/framework/fusion/main.py
  ocs_ci/framework/fusion_data_foundation/main.py
  ocs_ci/ocs/constants.py
  ocs_ci/templates/fusion/spectrum-fusion.yaml
  ocs_ci/utility/framework/fusion_fdf_init.py
  ocs_ci/utility/utils.py
  setup.py
Labels: Verified, team/ecosystem, size/XXL, lgtm
