Repository red-hat-storage/ocs-ci, pull requests merged in 2025-10, with the labels that each got.

#13310 Wait for noobaa before validation KMS
  ocs_ci/utility/kms.py
Labels: Verified, size/XS, lgtm

#13306 Remove OCP MG image from default config
  ocs_ci/framework/conf/default_config.yaml
Labels: Verified, size/XS, lgtm

#13315 temp submariner fix
  ocs_ci/deployment/acm.py
  ocs_ci/ocs/constants.py
Labels: Verified, size/S, lgtm

#13293 scale down pods and remove pvc before removing cluster for vSphere IPI
  ocs_ci/deployment/vmware.py
Labels: Verified, team/ecosystem, size/XS, lgtm

#13282 Fix a few UI tests failing in 4.20
  ocs_ci/ocs/ui/page_objects/encryption_module.py
  ocs_ci/ocs/ui/page_objects/object_bucket_claims_tab.py
  ocs_ci/ocs/ui/page_objects/object_storage.py
  ocs_ci/ocs/ui/page_objects/page_navigator.py
  ocs_ci/ocs/ui/storageclass.py
  ocs_ci/ocs/ui/views.py
  tests/cross_functional/ui/test_validation_ui.py
  tests/functional/encryption/test_encryption_configuration_dashboard.py
  tests/functional/object/mcg/ui/test_mcg_ui.py
  tests/functional/ui/test_error_improvements.py
Labels: Verified, size/L, lgtm, Squad/Black

#13326 418 provider deployment adjustments
  ocs_ci/deployment/hosted_cluster.py
  ocs_ci/deployment/mce.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_client.py
Labels: Verified, size/S, lgtm

#13329 4.19 Upgrade acm version 1-line fix
  ocs_ci/ocs/acm_upgrade.py
Labels: Verified, size/XS, lgtm
