Repository red-hat-storage/ocs-ci, pull requests merged in 2025-01, with the labels that each got.

#10580 [Stretch cluster] Stabilize stretch cluster tests and support CNV workloads in MON & OSD failure test cases
  ocs_ci/helpers/stretchcluster_helper.py
  ocs_ci/ocs/cnv/virtual_machine.py
  ocs_ci/ocs/resources/pod.py
  ocs_ci/ocs/resources/stretchcluster.py
  tests/conftest.py
  tests/functional/disaster-recovery/sc_arbiter/test_mon_osd_failures.py
  tests/functional/disaster-recovery/sc_arbiter/test_netsplit.py
  tests/functional/disaster-recovery/sc_arbiter/test_zone_shutdown_and_crash.py
Labels: Verified, team/e2e, size/XL, lgtm

#8699 Mdr upgrade scenario
  conf/README.md
  ocs_ci/framework/__init__.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/framework/pytest_customization/ocscilib.py
  ocs_ci/ocs/acm_upgrade.py
  ocs_ci/ocs/cluster.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/defaults.py
  ocs_ci/ocs/dr_upgrade.py
  ocs_ci/ocs/ocs_upgrade.py
  ocs_ci/ocs/utils.py
  ocs_ci/templates/acm-deployment/acm_brew_icsp.yaml
  ocs_ci/utility/multicluster.py
  ocs_ci/utility/utils.py
  tests/conftest.py
  tests/functional/upgrade/test_upgrade.py
  tests/functional/upgrade/test_upgrade_ocp.py
Labels: Verified, team/ecosystem, size/XXL, lgtm, DR

#11052 Fixed tests failure test_secrets_in_env_variables
  tests/functional/pv/pv_encryption/test_secrets_on_pods.py
Labels: Verified, size/XS, lgtm, backport-required

#10957 [4.18] Test bucket replication with versioning - utility functions and happy path validation
  ocs_ci/ocs/bucket_utils.py
  ocs_ci/ocs/resources/mcg_replication_policy.py
  tests/functional/object/mcg/test_bucket_replication_with_versioning.py
Labels: Verified, size/L, MCG, Squad/Red, lgtm

#11082 Fix AMQ setup by cloning the latest compatible branch of strimzi-kafka-operator
  ocs_ci/ocs/amq.py
Labels: Verified, size/XS, RGW, Squad/Magenta, Squad/Red, lgtm

#11100 Get current ODF CSV for ROKS cluster from Install Plan
  ocs_ci/ocs/resources/packagemanifest.py
Labels: Verified, size/S, lgtm

#11108 add jira mark DFBUGS-1284
  tests/functional/pod_and_daemons/test_mgr_enable_rook_backend_module.py
Labels: size/XS, lgtm

#11118 Removed password field from vm yaml
  ocs_ci/templates/cnv-vm-workload/vm.yaml
Labels: team/e2e, size/XS, Squad/Magenta, lgtm

#11109 fix variable overwrite for storing IBM cloud buckets
  ocs_ci/utility/ibmcloud.py
Labels: team/ecosystem, size/S, lgtm

#11106 avoid circular import when importing MCG
  ocs_ci/ocs/resources/pod.py
Labels: team/ecosystem, size/XS, lgtm

#11117 trim testcase path for test_pods_csi_log_rotation
  tests/functional/pod_and_daemons/test_csi_logs_rotation.py
Labels: team/ecosystem, size/S, lgtm

#11116 Fix config_index fixture for ocp upgrade
  tests/functional/upgrade/test_upgrade_ocp.py
Labels: Verified, size/XS, lgtm

#11130 Generate parametrized pytests only if it's multicluster and upgrade run
  tests/conftest.py
Labels: Verified, team/ecosystem, size/XS, lgtm, DR

#11102 Multus ipv6 on vsphere
  conf/deployment/vsphere/upi_1az_rhcos_multus_public_cluster_vsan_3m_3w_ipv6.yaml
  conf/ocsci/vsphere_upi_enable_multus_ipv6_single_stack.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/helpers/helpers.py
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/storage_cluster.py
  ocs_ci/templates/ocs-deployment/multus-cluster-net-ipv6.yaml
  ocs_ci/templates/ocs-deployment/multus-public-net-ipv6.yaml
  ocs_ci/templates/ocs-deployment/node_network_configuration_policy_ipv6.yaml
Labels: size/L, lgtm

#11140 Change multus configuration file for Jenkins job
  conf/deployment/vsphere/upi_1az_rhcos_multus_public_cluster_vsan_3m_3w.yaml
  conf/deployment/vsphere/upi_1az_rhcos_multus_vsan_3m_3w.yaml
Labels: size/M, lgtm

#10972 must gather minimal crds test case
  ocs_ci/ocs/must_gather/const_must_gather.py
  tests/functional/z_cluster/test_must_gather_minimal_crds.py
Labels: Verified, size/L, lgtm

#11043 Test Automation for encryption dashboard summary
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/ui/helpers_ui.py
  ocs_ci/ocs/ui/page_objects/encryption_module.py
  ocs_ci/ocs/ui/page_objects/storage_system_details.py
  ocs_ci/ocs/ui/views.py
  tests/functional/encryption/test_encryption_configuration_dashboard.py
Labels: Verified, size/L, lgtm

#11148 Skip the ROSA HCP platform resize OSD test if the resize OSD count is more than the AWS max resize count
  ocs_ci/helpers/osd_resize.py
Labels: Verified, size/XS, Squad/Brown, lgtm

#11121 Updated in-transit encryption test automation for enable/disable operations.
  tests/conftest.py
  tests/functional/encryption/test_intransit_encryption_sanity.py
Labels: Verified, size/L, lgtm

#11139 Upgrade paramiko to 3.5.0
  setup.py
Labels: size/XS, lgtm

#11119 Adding support in creation of bucket class with mcg cli and a new test case for creation of rgw namespacestore using mcg-cli
  ocs_ci/ocs/resources/bucketclass.py
  ocs_ci/ocs/resources/mcg.py
  tests/functional/object/mcg/test_namespace_crd.py
Labels: Verified, size/M, Squad/Red, lgtm

#11162 Fix upgrade for non managed IBM Cloud platforms
  ocs_ci/ocs/ocs_upgrade.py
Labels: size/XS, lgtm

#11131 changed multi_cnv_workload fixture to create parallel VMs
  ocs_ci/ocs/cnv/virtual_machine.py
  ocs_ci/templates/cnv-vm-workload/vm.yaml
  tests/conftest.py
  tests/functional/workloads/cnv/test_multi_vm_configurations.py
Labels: Verified, team/e2e, size/M, lgtm

#10801 Adding functionality to set same token value across cluster
  ocs_ci/utility/kms.py
Labels: Verified, size/S, lgtm

#11099 Updating TestVmSnapshotClone tests with multi_cnv_workload fixture
  ocs_ci/ocs/cnv/virtual_machine.py
  tests/functional/workloads/cnv/test_vm_snapshot_cloning_ops.py
Labels: Verified, team/e2e, size/M, lgtm

#10973 Test case changes for RHSTOR-5823
  tests/functional/monitoring/prometheus/alerts/test_alert_mds_cpu_high_usage.py
Labels: team/e2e, size/S, lgtm

#10862 Adding test automation for reclaimspace disable operation
  ocs_ci/helpers/helpers.py
  tests/functional/pv/space_reclaim/test_disable_reclaimspace_operation.py
Labels: Verified, size/L, lgtm

#11147 Label the s3cli pod's Namespace with `S3CLI_APP_LABEL` to ignore potential false leftover error
  tests/conftest.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#11181 Adding setter function for vault_path_token
  ocs_ci/utility/kms.py
Labels: Verified, size/XS, lgtm

#11187 Removing indexing
  tests/conftest.py
Labels: Verified, team/e2e, size/XS, lgtm

#11153 [ROSA HCP] storage encryption. fix namespace issue
  ocs_ci/utility/kms.py
Labels: Verified, TestCase failing, size/XS, lgtm

#11144 add screenshot to prove numbers in logs
  ocs_ci/helpers/osd_resize.py
Labels: size/XS, lgtm, Squad/Black

#11120 test_ceph_pg_log_dups_trim - fix the test
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/XS, lgtm

#11104 wrap s3 benchmark-tool - ns in hostname fixed
  ocs_ci/ocs/warp.py
Labels: Verified, TestCase failing, size/XS, lgtm

#11074 [ROSA HCP] test_db_scc correct service acc namespace
  tests/functional/object/mcg/test_mcg_resources_disruptions.py
Labels: Verified, TestCase failing, size/XS, lgtm

#11078 [ROSA HCP] skip tests related to master nodes operations
  tests/functional/workloads/app/amq/test_amq_node_reboot_and_shutdown.py
  tests/functional/workloads/app/couchbase/test_couchbase_node_reboot.py
  tests/functional/z_cluster/nodes/test_nodes_maintenance.py
Labels: TestCase failing, size/S, lgtm

#11185 Mark test_prometheus_rule_failures as flaky
  tests/functional/monitoring/prometheus/alerts/test_alerting_works.py
Labels: Verified, size/XS, Squad/Blue, lgtm

#10869 Azure STS deployment support
  conf/deployment/azure/ipi_3az_rhcos_sts_3m_3w.yaml
  docs/supported_platforms.md
  ocs_ci/deployment/aws.py
  ocs_ci/deployment/azure.py
  ocs_ci/deployment/deployment.py
  ocs_ci/utility/azure_utils.py
  ocs_ci/utility/cco.py
  setup.py
Labels: Verified, team/ecosystem, size/L, lgtm

#11001 Test Automation for clusterwide encryption keyrotation
  ocs_ci/framework/pytest_customization/marks.py
  ocs_ci/helpers/keyrotation_helper.py
  ocs_ci/utility/kms.py
  tests/functional/encryption/test_encryption_keyrotation.py
Labels: Verified, size/L, lgtm

#11200 Fix vault path token condition
  ocs_ci/utility/kms.py
Labels: size/XS, lgtm

#11183 Preserve the working directory during log collection
  ocs_ci/ocs/utils.py
Labels: size/XS, lgtm

#11198 Ignore controller-detect-version pods in leftover check
  ocs_ci/ocs/constants.py
  ocs_ci/utility/environment_check.py
Labels: size/XS, lgtm

#11222 Fix destroy KMS Vault
  ocs_ci/utility/kms.py
Labels: Verified, size/M, lgtm

#11225 Add toleration on api-server pod
  ocs_ci/helpers/helpers.py
Labels: Verified, size/XS, lgtm

#11213 Skipping test cases with kubeadmin password
  tests/conftest.py
Labels: size/XS, lgtm

#11208 test_ceph_pg_log_dups_trim increase timeout on log copy process
  ocs_ci/ocs/rados_utils.py
  ocs_ci/ocs/resources/pod.py
Labels: Verified, size/M, lgtm

#10554 make test_unprivileged_user_odf_access work on ROSA and ROSA HCP
  ocs_ci/ocs/ocp.py
  ocs_ci/ocs/ui/base_ui.py
  ocs_ci/ocs/ui/views.py
  ocs_ci/utility/rosa.py
  ocs_ci/utility/users.py
  tests/functional/ui/test_non_admin_user.py
Labels: Verified, size/L, lgtm, Squad/Black

#11226 [release-4.16][Cherry-pick-10659] Fixed keyrotation test failures
  ocs_ci/helpers/keyrotation_helper.py
  tests/functional/encryption/test_encryption_keyrotation.py
Labels: Verified, size/S, lgtm

#11041 [4.18] Test MCG bucket notifications - utility functions and happy path validation
  ocs_ci/ocs/constants.py
  ocs_ci/ocs/resources/bucket_notifications_manager.py
  tests/functional/object/mcg/test_bucket_notifications.py
Labels: Verified, size/L, MCG, Squad/Red, lgtm

#11227 Adding a new test case for rgw namespacestore created with cli
  tests/functional/object/mcg/test_write_to_bucket.py
Labels: Verified, size/S, MCG, Squad/Red, lgtm

#11173 test_bucket_logs.py - Adding skip on external deployments following issue 10983
  tests/functional/object/mcg/test_bucket_logs.py
Labels: Verified, size/XS, MCG, Squad/Red, lgtm

#11086 `test_bucket_logs_integrity` - fix race condition by waiting for logs to appear before awaiting their removal
  ocs_ci/ocs/resources/bucket_logging_manager.py
Labels: Verified, size/M, MCG, Squad/Red, lgtm

#11110 Adds condition for skipping BS creation on IBM cloud for FIPS enabled cluster
  tests/functional/object/mcg/test_multicloud.py
  tests/functional/object/mcg/test_write_to_bucket.py
Labels: Verified, size/M, MCG, Squad/Red, lgtm

#11073 [ROSA HCP] prep for production CI jobs
  conf/deployment/aws/rosa_hcp_1az_3w_m5.12x.yaml
  conf/deployment/aws/rosa_hcp_1az_6w_m5.2x.yaml
  ocs_ci/deployment/rosa.py
  ocs_ci/framework/conf/default_config.yaml
  ocs_ci/ocs/ocp.py
  ocs_ci/utility/rosa.py
  ocs_ci/utility/version.py
  tests/functional/upgrade/test_upgrade_ocp.py
Labels: Verified, size/L, lgtm

#10936 disable dr for discovered apps
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/ocs/dr/dr_workload.py
  tests/functional/disaster-recovery/regional-dr/test_disable_dr.py
Labels: Verified, size/M, lgtm, DR, Squad/Turquoise

#11247 Skip test_cross_class_different_pool_clone_snap_restore test for external mode
  tests/functional/storageclass/test_cross_sc_clone_snap_restore.py
Labels: size/XS, lgtm

#11228 Fix `MCG::reset_endpoint_pods` race condition - use rollout restart instead of deleting pods by name
  ocs_ci/ocs/resources/mcg.py
  ocs_ci/ocs/resources/pod.py
  tests/conftest.py
  tests/functional/disaster-recovery/sc_arbiter/test_mon_osd_failures.py
  tests/functional/disaster-recovery/sc_arbiter/test_noobaa_in_stretch.py
Labels: Verified, size/M, MCG, Squad/Red, lgtm

#11263 Fix IBM Cloud upgrade
  ocs_ci/ocs/ocs_upgrade.py
Labels: size/XS, lgtm

#11252 Skipping test cases with kubeadmin password - release4.17
  tests/conftest.py
Labels: size/XS, lgtm

#10966 Added Test Automation for disable keyrotation operation
  ocs_ci/helpers/keyrotation_helper.py
  ocs_ci/ocs/constants.py
  tests/functional/pv/pv_encryption/test_disable_pv_keyrotation.py
Labels: Verified, size/L, lgtm

#11224 Update retry logic with some limits
  .pre-commit-config.yaml
  ocs_ci/deployment/deployment.py
  ocs_ci/helpers/dr_helpers.py
  ocs_ci/utility/retry.py
  scripts/python/checks/validate_retry_usage.py
  tests/cross_functional/system_test/test_graceful_nodes_shutdown.py
  tests/cross_functional/system_test/test_mcg_replication_with_disruptions.py
  tests/functional/disaster-recovery/sc_arbiter/test_zone_shutdown_and_crash.py
  tests/functional/monitoring/conftest.py
  tests/functional/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py
  tests/functional/workloads/app/amq/test_amq_node_reboot_and_shutdown.py
  tests/functional/workloads/app/couchbase/test_couchbase_node_reboot.py
  tests/functional/workloads/ocp/monitoring/test_monitoring_on_negative_scenarios.py
  tests/functional/workloads/ocp/registry/test_registry_reboot_node.py
  tests/functional/workloads/ocp/registry/test_registry_shutdown_and_recovery_node.py
  tox.ini
Labels: size/L, lgtm
